### ISSUE TITLE
Improving Search Filters

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1001]
In efforts to resolve the "Verifiable" filter confusion, here is a proposal:

![image](https://cloud.githubusercontent.com/assets/11527994/16015012/a4f029a8-3148-11e6-8655-2a9879f594af.png)
- Group quality grade
- Separate out media and put it in the advanced section. Also wondering if these filters are really necessary.

**Comment by loarie** [comment]
I like separating out quality and moving media into more, but not clear to me why we need to change the existing 'x has photos' 'x has sounds'  checkboxes

**Comment by joellebel** [comment]
Because if we keep has photos as just a checkbox then it will need to be checked by default and I'm trying to minimize what must be checked by default.

**Comment by loarie** [comment]
That doesn't make sense to me. The two variables are (1) what the checkbox does and (2) the label. You mentioned before changing the label from 'has photos' to 'Observations with photos only' which I don't feel strongly about but seems fine. But re: what the checkbox does, 'has photos' filters things down to only those observations with photos. Thats not a default filter (by default we're showing stuff with both photos and no photos as long as they are verifiable) - so why would you think it would need to be checked?

**Comment by joellebel** [comment]
ok. fine.

See revised...

![image](https://cloud.githubusercontent.com/assets/11527994/16063541/d1bd1822-324e-11e6-944b-ef4bc1083cd8.png)

**Comment by joellebel** [comment]
Actually "Only has photos" doesn't make sense. I'm fine with "Has photos" and "Had media".

@kueda and @pleary just wondering when this is on the horizons. Let me know if you need anything else from me or @loarie

**Comment by joellebel** [comment]
@loarie do you still see this as a priority? I remember we had some confusion with folks. I kinda see it as a higher priority since we don't really use this "verifiable" language on the site anywhere else.

**Comment by joellebel** [comment]
We can ditch the media filter changes. Verifiable seemed to be the point of big confusion, anyways.
