### ISSUE TITLE
Identifier Agree Button Modification

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1007]
In Identifier grid biew we discussed only showing the Agree button on observations having a community ID of species level or lower. This way no one can mistakenly make a coarser ID on an ob.

**Comment by joellebel** [comment]
Furthermore...

Wondering if we want to do away with agree buttons on ob detail screens on IDs that are coarser than genus level. ...since as  you were saying @kueda agreeing with a coarse ID doesn't really move the ball forward.

I can always make a separate issue for this, but just thought I'd bring it up here.

**Comment by naturalistcharlie** [comment]
Is it not valuable to agree to genus level? Have we decided those are not
useful for research grade? I don't feel strongly about it but i sometimes
do agree with them and maybe i should not bother

On Wed, Jun 15, 2016 at 4:59 PM, joellebel <notifications@github.com> wrote:

> Furthermore...
>
> Wondering if we want to do away with agree buttons on ob detail screens on
> IDs that are coarser than genus level. ...since as you were saying @kueda
> <https://github.com/kueda> agreeing with a coarse ID doesn't really move
> the ball forward.
>
> I can always make a separate issue for this, but just thought I'd bring it
> up here.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/1007#issuecomment-226318243>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AG1tk1iJP8xK1M9-Gk1tIQQ6HGZDdC9iks5qMGejgaJpZM4I14wN>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
