### ISSUE TITLE
specific location description posted to followers' dashboard for obscured observations!

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/inaturalist#1012]
user Jtuttle found a major 'hole' in geoprivacy...

from their post on http://www.inaturalist.org/posts/6518-a-new-way-to-add-observations#activity_comment_548803:

_the locational privacy issue I'm referring to is this: For anyone I follow, when she/he posts several observations with location obscured or private, the *actual* locations, down to the address and/or coordinates, are listed beneath the set of observations in my dashboard. So I have to assume that this is occurring with others for *my* obscured/private observations as well. For example, if my husband uses the app (and probably also the website) to upload observations made at our home address, even if he has made the location obscured or private, our home address will display underneath his observations in my dashboard (e.g., "See whiteoak's observations from {FULL ADDRESS}...")! When I go to individual observations, the location is obscured or blocked, but the location information is still right there on my dashboard. If I upload obscured or private observations via the website and enter my own location name (e.g., "Chatham County", but not otherwise overriding the coordinates pulled from the photo), I *think* it gets around this issue, but I'm not really sure of that._

I just checked this and it is true. it doesn't show the address when i look but does show the street name. See screenshot below:

![image](https://cloud.githubusercontent.com/assets/7171475/16275330/8e8f4dfc-3877-11e6-8373-5cc0f2c2547c.png)

here's the observation:

http://www.inaturalist.org/observations/3493779

![image](https://cloud.githubusercontent.com/assets/7171475/16275383/c47378da-3877-11e6-95af-0631b7d2f631.png)

I just checked by viewing my account from a different account and it is true for observations I've made and obscured at my home as well. In this case it doesn't matter because I literally live on 'main street' of a state capital (albeit a small one) and that is all it says for mine, so not a big deal there. But for a small, short street it could be a much bigger issue.

**Comment by kueda** [comment]
The only thing we do to the "place guess" or "locality notes" when you obscure the coordinates is strip leading numbers, and that's the way it's been (by design) since the days before we had a performative way to access more conventional place names. Think about how one could deal with this problem: if you have an arbitrary string of text, how are you supposed to choose what parts are very specific and what parts aren't? "1234 Bogus St., Oakland, CA" is pretty well structured and we could remove the street from that, but what about "1234 The Cedars Oakland/Orinda Califarnia" or worse,  "Oakland, CA, the only red house on Bogus St., behind the rosemary bush by the garage"? Free, user-editable text is hard for machines to make sense of, and while we can sort of control the street addresses the apps generate, we can't absolutely stop people from entering very specific locality information that we simply cannot parse. And if you think my made-up examples are obtuse, here are some real place guesses:

* 209-1 Dogok-ri, Maepo-eup Danyang-gun, Chungcheongbuk-do
* Kepler track above Iris Burn in beech forest
* Thalkirchner Straße 240 81371 München
* wind turbine
* -47.20516       167.681383 (yes, people put coordinates in this field)

All that being said, these days we *could* treat the `place_guess` in the same way that we do `private_latitude`, while still showing *some* textual description of the place in the form of names of the admin-level places that contain the coordinates. But even then the system is imperfect when the true coordinates are right at the edge of the obscuration cell and revealing the name of the containing places gives the viewer a very exact idea of where the true coordinates are.

My point here is that while we could perhaps improve the situation, perfection is impossible, so I would not describe this as a "major hole". As we've tried to say from the beginning of the debates over revealing coordinates, if you really don't want to disclose information, don't post it to the Internet. We try to do what we can, but we can't stop people from revealing locations *and* allow them to communicate openly.

**Comment by naturalistcharlie** [comment]
I know the system isn't perfect and isn't meant for 'super top secret'
anything. Maybe major hole is excessive. However, in this case it seems
quite clear to me at least that the downsides of sharing that sort of info
in the dashboard far outweigh the upsides. Why even have the place guess in
the dashboard notification at all? If I want to see where my friend
observed something, I click on it. Then all obscuring rules apply. Removing
that little text string would offer a lot more geoprivacy without a real
downside that I see.

Overall, I don't understand the sentiment "if you really don't want to
disclose information, don't post it to the Internet". I use websites for
all sorts of variably personal information... bank accounts, credit card
numbers sent to Amazon, private email, semi-private Facebook posts,
whatever. Perhaps more relevant, I've posted a LOT of private biodiversity
data to the Internet via NatureServe Biotics. My point isn't that iNat
should replace BIOTICS but if you have a button that says 'private
location' it seems to me that it's best to take reasonable non odious
efforts to keep the data private. Like not posting that seemingly
unnecessary string of text on the dashboard. There's certainly a happy
medium between 'location says private but anyone who tries can easily see
it' and the obnoxious 12 step authentication and security questions stupid
bank websites have. And this issue isn't stopping people from revealing
locations... this is people revealing locations without necessarily knowing
it. At least in the case of two users (that other person and me) there was
information being shared that the user wasn't aware was being shared.

More broadly, I've lately been discussing iNaturalist with a lot of really
wonderful ecologists, scientists, and land managers. It's a hard sell to
get people to use inat when they aren't tech types, despite the fact that
it's probably the most powerful tool for naturalists since field notebooks
were invented, but interest is starting to rise. However almost EVERY time
the conversation comes up, geoprivacy comes up as a concern. Concern about
species prone to collection but also brought up when proposing the idea
that we can use iNat to help landowners learn about their land. If I visit
a wetland on private land, iNat is a wonderful way to collect data that can
easily and quickly be provided to the landowner for their own knowledge,
education, and enjoyment of the biodiversity on their land. The landowner
can add to it too, or can post things and share them with us for ID help.
The data will also be shared with the rest of the world - except the
location will be obscured. Vermont has a ton of rural roads with just one
or two homes along them and privacy leaks like this are dealbreakers for
probably thousands of people here who want a reasonable measure of privacy
(else they wouldn't live on a road with just two houses on it). In my mind,
if a few small changes mean a potential flowering of the scientific
community (which means much better ID help and a stronger community) as
well as a wide expansion of the ability to use iNat for land management and
private lands issues, it seems worth allowing this little bit of 'mission
creep' to the site. But of course that's your call, not mine.

I know I kind of have a history of requesting bizzare obscure features that
like, no one else ever will use but I can tell you this is different. I've
talked to a lot of current and potential users... not in a seditious way
but just casually... and this stuff comes up more often than I can count.
In the least I think it's worthy of further discussion... though since I'm
not sure what forum is best for that I will leave it at this for now:
stronger (but not obscenely secret) geoprivacy means more data for everyone.

Thanks, as always!

On Wed, Jun 22, 2016 at 3:08 PM, Ken-ichi <notifications@github.com> wrote:

> The only thing we do to the "place guess" or "locality notes" when you
> obscure the coordinates is strip leading numbers, and that's the way it's
> been (by design) since the days before we had a performative way to access
> more conventional place names. Think about how one could deal with this
> problem: if you have an arbitrary string of text, how are you supposed to
> choose what parts are very specific and what parts aren't? "1234 Bogus St.,
> Oakland, CA" is pretty well structured and we could remove the street from
> that, but what about "1234 The Cedars Oakland/Orinda Califarnia" or worse,
> "Oakland, CA, the only red house on Bogus St., behind the rosemary bush by
> the garage"? Free, user-editable text is hard for machines to make sense
> of, and while we can sort of control the street addresses the apps
> generate, we can't absolutely stop people from entering very specific
> locality information that we simply cannot parse. And if you think my
> made-up examples are obtuse, here are some real place guesses:
>
>    - 209-1 Dogok-ri, Maepo-eup Danyang-gun, Chungcheongbuk-do
>    - Kepler track above Iris Burn in beech forest
>    - Thalkirchner Straße 240 81371 München
>    - wind turbine
>    - -47.20516 167.681383 (yes, people put coordinates in this field)
>
> All that being said, these days we *could* treat the place_guess in the
> same way that we do private_latitude, while still showing *some* textual
> description of the place in the form of names of the admin-level places
> that contain the coordinates. But even then the system is imperfect when
> the true coordinates are right at the edge of the obscuration cell and
> revealing the name of the containing places gives the viewer a very exact
> idea of where the true coordinates are.
>
> My point here is that while we could perhaps improve the situation,
> perfection is impossible, so I would not describe this as a "major hole".
> As we've tried to say from the beginning of the debates over revealing
> coordinates, if you really don't want to disclose information, don't post
> it to the Internet. We try to do what we can, but we can't stop people from
> revealing locations *and* allow them to communicate openly.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/1012#issuecomment-227846316>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AG1tk9d9EVV1BRjWyF1Wp4tCGx-FoCK4ks5qOYgkgaJpZM4I7_iL>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by kueda** [comment]
So, the dashboard has been completely changed and these locations are no longer showing up. Issue resolved?
