### ISSUE TITLE
translations for the uploader

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1013]
@calonso-conabio, http://www.inaturalist.org/observations/upload?locale=es-MX needs to have a few strings translated:

- [x] `accuracy_meters`
- [x] `add_a_field`
- [x] `add_tags`
- [ ] `add_to_a_project`
- [x] `are_you_sure_remove_photo`
- [x] `choose_photos`
- [x] `combine`
- [x] `confirm`
- [x] `continue`
- [x] `drag_and_drop_some_photos`
- [x] `drop_it`
- [x] `edit_multiple_dates`
- [x] `edit_multiple_descriptions`
- [x] `edit_multiple_locations`
- [x] `edit_multiple_species`
- [x] `editing_observations`
- [x] `fields_`
- [x] `from_flickr_facebook_etc`
- [x] `from_soundcloud`
- [x] `go_back`
- [x] `going_to_your_observations`
- [x] `import_sounds`
- [x] `loading_metadata`
- [x] `locality_notes`
- [x] `location_is_obscured`
- [x] `location_is_private`
- [x] `location_is_public`
- [x] `more_import_options`
- [x] `multiple`
- [x] `multiple_select_option`
- [x] `observation_without_photo`
- [ ] `old_observation_form`
- [x] `photo_s`
- [x] `remove_observations`
- [x] `saving_num_of_count_observations`
- [x] `select_observations_to_edit`
- [x] `some_observations_failed`
- [x] `species_name_cap`
- [x] `submit_observations`
- [x] `these_observations_have_not_been_uploaded_yet`
- [x] `uploader`: there are several things that need to be translated here
- [x] `view_field_options`
- [x] `x_observations_failed`
- [x] `you_are_submitting_obs_with_no_date_or_no_location`
- [x] `you_are_submitting_obs_without_photos_and_names`

These tool is already live, but we're hoping to make it the main way to add observations next week or the week after.

**Comment by kueda** [comment]
@calonso-conabio, we're hoping to make the switch to the uploader as the primary way to add observations by the end of this week. Any chance you could get to these translations by then?

**Comment by calonso-conabio** [comment]
sure @kueda , i will send you the translations before the end of the week


regards.
