### ISSUE TITLE
include Google Maps API key for all uses of Google Maps

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1018]
Google recently [changed their policies](http://googlegeodevelopers.blogspot.com/2016/06/building-for-scale-updates-to-google.html) to require an API key. They're grandfathering in existing users like us, but it doesn't seem like they're extending the same courtesy to requests coming from localhost, so gmaps development is essentially impossible at the moment. This is especially annoying because now we have to wait for API key approval every time we use a Google Map, which I think means a bunch of refactoring.

**Comment by loarie** [comment]
Is there something we could ask for from google that would help here?  e.g. some sort of free premium account

**Comment by kueda** [comment]
Probably, but we need to see what our usage looks like, and I'm not sure we can know that before including the API key with our requests.

**Comment by dianashk** [comment]
I just came across the iNaturalist.org site today and it looks really cool! 🚀 You guys are doing a really great job!

I work for an open-source mapping company, Mapzen, so naturally was curious which map provider you're using. It's so exciting that the work you're doing is open-source as well, so it's easy to find answers to such questions. :) While searching for the answer, I immediately came across this issue. It's kind of a big bummer. 😞 

At the risk of being too forward, I feel obligated to let you know that Mapzen is a great alternative. 😊  We are entirely open-source, and all of our services are built on top of open data projects such as [OpenStreetMap](www.openstreetmap.org) and [Who's on First](www.whosonfirst.mapzen.com). We offer a free tier with very generous rate limits. See [here](https://mapzen.com/products) for details. It might be enough to sustain your load. We have beautiful vector tiles that work well with Leaflet. We have geocoding in case you'd like to offer a search capability. All you need to get started with any service is a github account.
