### ISSUE TITLE
can't remove coordinates for photos with coordinates in uploader

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1019]
When you upload a photo that has GPS coordinates in the uploader and then delete the coordinates in the location editor, it seems like they're gone (it even warns you about uploading an obs without coordinates), but when you submit the observation, it has coordinates.

**Comment by pleary** [comment]
Looks like that was coming from https://github.com/inaturalist/inaturalist/blob/master/app/controllers/observations_controller.rb#L614 which is using lat/lng, date, and species info from the photos of the obs has none. Do we want to suppress all these assignments, skip this block, for obs uploaded with the uploader?

**Comment by pleary** [comment]
I've suppressed them all. What the user sees before they upload is what they'll get, and we won't try to fill in any blanks
