### ISSUE TITLE
observation fields not getting parsed from tags in uploader

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1022]
The following file has the `eating` and `Insect life stage` fields specified as tags, but they don't seem to get added in production or on gonatus.

![img_6954](https://cloud.githubusercontent.com/assets/22691/16361244/6630cc18-3b3e-11e6-86de-4af75a6ce996.jpg)

**Comment by pleary** [comment]
I'm not seeing any tags or fields when I upload this with the old add obs form either. Do you? Not sure if it's this version of the image, or this is perhaps an EXIF parsing problem that isn't new with the uploader.

**Comment by pleary** [comment]
nevermind - found the problem. And I guess add obs was never assigning tags or OFVs
