### ISSUE TITLE
Search for taxa within  "IDs"

### ISSUE THREAD

**Issue by rspfau** [inaturalist/inaturalist#1027]
There have been several instances when I was trying to identify an observation and could remember identifying an earlier observation of that same species, but I couldn't remember what the species name was.  However, I knew the family or genus.  I wished I could search my past IDs for that family or genus so I could more easily find the past ID and get the species name for the new observation. Is this something that might actually be useful to anyone but me?  It would sure save a lot of time doing all the  research again to figure out the ID a second time.

**Comment by loarie** [comment]
You can see your IDs here http://www.inaturalist.org/identifications/loarie but you're proposing including a taxon search filter there?

**Comment by rspfau** [comment]
Yes, like there is for “Observations”.  So that one can search for taxa that one has IDed.

**Comment by loarie** [comment]
I agree would be nice to have

**Comment by carrieseltzer** [comment]
On our radar but we're tracking this via a [feature request on the forum](https://forum.inaturalist.org/t/search-and-filter-identifications/1304) so I'll close here.
