### ISSUE TITLE
improved "subscribe to a taxon"

### ISSUE THREAD

**Issue by rspfau** [inaturalist/inaturalist#1036]
The "subscribe to a taxon" needs a locality filter.  I'd love to subscribe to observations of taxa within areas in which I'm familiar with the taxon in question--but not for the entire world.

**Comment by loarie** [comment]
You can do this by subscribing to a place and adding an optional taxon filter. e.g to subscribe to beetles of California, click on Subscribe to a place and add place=california and taxon=beetles
