### ISSUE TITLE
Ampersands display with HTML in first part of profiles

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1038]
The "&amp;" is displaying on the website when someone uses an ampersand in the first paragraph of their profile. See screenshot below for my test of the first and second paragraphs of the profile. 

![screen shot 2016-07-05 at 2 54 53 pm](https://cloud.githubusercontent.com/assets/7501183/16596182/c287f4b2-42c0-11e6-94d2-37357a987711.png)

Here's someone who for real (not just for test) uses an ampersand in the first paragraph: http://www.inaturalist.org/people/ctkremer

**Comment by carrieseltzer** [comment]
Perhaps relatedly, hyperlinks don't work in the first paragraph of the profile either. (They just don't appear at all). I had a hyperlink on "National Geographic's Great Nature Project" which works fine when I pasted it into a lower paragraph.

Exact text so you can see the link: " I previously managed <a href="https://www.inaturalist.org/projects/national-geographic-great-nature-project">National Geographic's Great Nature Project</a>.

**Comment by pleary** [comment]
I just pushed a fix for "&amp ;", but I didn't address the link issue. The code is explicitly removing tags from the upper portion of the profile, and I'm not sure what motivated that so I'll leave that be until someone else can advise about that. The apersand fix has not yet been released, but will go out later today

**Comment by carrieseltzer** [comment]
Thanks Patrick! I wouldn't be surprised if the link removal is to prevent links from working in spam accounts.
