### ISSUE TITLE
Map not working on Naturalista Colombia

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1041]
When I first loaded the homepage (http://naturalista.biodiversidad.co/observations) I can see the map, but then it very quickly vanishes and gives an error (see screen shot). 

![screen shot 2016-07-05 at 9 48 23 pm](https://cloud.githubusercontent.com/assets/7501183/16605321/f03fb738-42fb-11e6-8481-08460297cac1.png)

Maybe this is a non-issue if Colombia isn't supposed to be up and running yet, but I checked it out because it's linked on the network page (http://www.inaturalist.org/pages/network). Also wanted to report just in case people *are* using it but don't know how to report issues.

Happening on both Chrome and Safari. Not logged in.

While I'm looking at Colombia, the people page isn't loading at all. See screen shot below. 
![screen shot 2016-07-05 at 9 59 52 pm](https://cloud.githubusercontent.com/assets/7501183/16605323/f4d625a2-42fb-11e6-9f0e-885998f4fe9c.png)

Edited to add: Maybe the mapping is related to #1018?

**Comment by loarie** [comment]
the map issue is fixed - I think the service unavailable thing is just a load hiccup, right @pleary, but not necessarily a bug? I've seen it too on that Colombian server from time to time. Are we just not giving it much in terms of resources?
