### ISSUE TITLE
invalid coordinates in EXIF not triggering validation errors in uploader

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1046]
The image below has wacky GPS EXIF data something like

```
GPS Date/Time                   : 0000:00:00 00:00:00Z
GPS Latitude                    : 17056881 deg 51' 12.15" N
GPS Longitude                   : 17056881 deg 51' 12.15" E
GPS Position                    : 17056881 deg 51' 12.15" N, 17056881 deg 51' 12.15" E
```

Currently when you add that to the uploader, it just interprets those coordinates and sticks them in the location field, and when you submit the observation, it fails to save silently. So IMO,

- [ ] uploading a photo with coordinates that are not in valid decimal degrees should just put nothing in the location field
- [ ] submit an obs that is invalid should show an error message somewhere, either before submit is complete or on the obs/:login page you land on afterwards.

![p1040909](https://cloud.githubusercontent.com/assets/22691/16672731/d70c9698-445c-11e6-9e6e-7087555590fe.jpg)

**Comment by pleary** [comment]
that doesn't really seem like valid lat/lng data even for degrees since lat is the same as lng. I can continue with ignoring bad values, but do you possibly have a photo with valid geo data in degree format? I could use that to test conversion between the formats

**Comment by kueda** [comment]
I'm not actually sure there is any variation in the format the coordinates are stored in, e.g. one of my own photos looks like this in exiftool:

```
GPS Latitude                    : 37 deg 5' 6.21" N
GPS Longitude                   : 122 deg 3' 39.75" W
GPS Position                    : 37 deg 5' 6.21" N, 122 deg 3' 39.75" W
```

and that uploaded just fine. This issue is mostly to address the silently failure of impossible coordinates like `17056881 deg 51' 12.15" N`, which *look* like they're getting set in the uploader but are actually result in no location since they're impossible.

**Comment by pleary** [comment]
OK - this should be mostly addressed in that we won't use invalid coordinates, and you shouldn't be able to save the location data in the uploader if the coordinates are invalid
