### ISSUE TITLE
Clickable GBIF Points?

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/inaturalist#1050]
How hard would it be to make the GBIF points on the map all clickable like the iNat observations are? I think I would use that a lot.

**Comment by pleary** [comment]
We're using the GBIF maps API for that layer, and that API appears to only offer customization of tile images http://www.gbif.org/developer/maps . What we would need to create clickable points is some kind of corresponding data API for each tile that specifies the clickable locations and what they are. We use UTFGrid for our own tile data http://api.inaturalist.org/v1/docs/#!/UTFGrid/get_points_zoom_x_y_grid_json .

Ideally GBIF would create and provide this API. If they did, it would be pretty straight forward to start using it to make clickable points. Without a UTFGrid or similar API, if we had to create something custom with other APIs of theirs, it would be a real pain and I don't think performative enough to be usable.

**Comment by naturalistcharlie** [comment]
So I should request it from the gbif side. That makes sense, thanks!

On Monday, July 11, 2016, Patrick Leary <notifications@github.com> wrote:

> We're using the GBIF maps API for that layer, and that API appears to only
> offer customization of tile images http://www.gbif.org/developer/maps .
> What we would need to create clickable points is some kind of corresponding
> data API for each tile that specifies the clickable locations and what they
> are. We use UTFGrid for our own tile data
> http://api.inaturalist.org/v1/docs/#!/UTFGrid/get_points_zoom_x_y_grid_json
> .
>
> Ideally GBIF would create and provide this API. If they did, it would be
> pretty straight forward to start using it to make clickable points. Without
> a UTFGrid or similar API, if we had to create something custom with other
> APIs of theirs, it would be a real pain and I don't think performative
> enough to be usable.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/1050#issuecomment-231759566>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AG1tk5zasWDV7m-GUfGBzox4wv775V-Sks5qUlmVgaJpZM4JInmE>
> .
>


-- 
Sent from Gmail Mobile
