### ISSUE TITLE
Naturalista Colombia is not available in the mobile version

### ISSUE THREAD

**Issue by adrisoacha** [inaturalist/inaturalist#1052]
Hello @loarie and guys,

Naturalista Colombia is not available in the mobile version option iNaturalist Network. When this option is active, all Colombian users by default have this affiliation or is necessary to change the setting manually?

Thanks,

Karen

**Comment by loarie** [comment]
Correct - we will need to add Naturalista Colombia to a new release of the iOS and Android apps when you guys are ready. Are you ready? What is your timeline for launching the site?

**Comment by adrisoacha** [comment]
The first presentation will be on 29th July.

**Comment by loarie** [comment]
OK will try to get It in the apps by then - Made iOS https://github.com/inaturalist/INaturalistIOS/issues/296 and Android https://github.com/inaturalist/iNaturalistAndroid/issues/192 issues

**Comment by loarie** [comment]
Hi @adrisoacha  - we're on track to have NaturaLista CO loaded onto the apps this week. Can you find testers with iOS and Android devices in Colombia who can test that the app is properly recognizing the country based on the SIM card?

**Comment by adrisoacha** [comment]
Hi @loarie, Great! We could test it, we await the release. Thanks!

**Comment by loarie** [comment]
great can you send us the email address for the iOS tester?

**Comment by adrisoacha** [comment]
ksoacha@humboldt.org.co
jdmartinez@humboldt.org.co
jgamboa@humboldt.org.co
cgutierrez@humboldt.org.co
molaya@humboldt.org.co

**Comment by loarie** [comment]
do all of these emails need to be added as testers? I'm not sure if we have limits on/costs associated with adding tester accounts - @alexshepard ?

**Comment by alexshepard** [comment]
I only need one or two people who 1) have iOS devices, and 2) are available to test in the next 24 hours.

Thanks,
Alex

**Comment by adrisoacha** [comment]
Then ksoacha@humboldt.or.go and jdmartinez@humboldt.org.co
We can test in the next 24 hours. 

Thanks!

**Comment by alexshepard** [comment]
OK, I've sent invitations to join TestFlight for these two users.

@adrisoacha I couldn't help but notice that in the two email addresses you provided, the domain names are very close but not the same. Is there a typo in one?

Thanks,
Alex

**Comment by adrisoacha** [comment]
Yes it was a mistake, they are both @humboldt.org.co

**Comment by adrisoacha** [comment]
@alexshepard Hi Alex, did you sent us invitations? We did not received, please could you confirm. Thanks! Karen

**Comment by alexshepard** [comment]
Yes, the invitations were sent, please check your spam folder.

However, Apple has approved the latest release for general publication, and that version has the Naturalista partner available in the dropdown. So you can try downloading directly from the iOS app store, make sure you download iNaturalist version 2.6.14.

Best,
alex

**Comment by adrisoacha** [comment]
Hi @alexshepard @loarie 

1) I can select to NaturaLista Colombia in these release for iOS. In advance to avoid confusion, it's possible NaturaLista will be NaturaLista Mexico?

2) One suggest for text: 
![img_3174](https://cloud.githubusercontent.com/assets/16558682/17227129/6f1b5692-54d2-11e6-97ad-6e120ce724e3.PNG)

Please replace:
¿Usar Naturalista Colombia?
Selecciona aceptar para compartir tus datos y que la información que recibes esté de acuerdo con tu ubicación.
No  / Aceptar

Naturalista logo may be larger?

3) An error has occurred trying to upload observation: **user cannot be spammer**  

4) I didn't received the TestFlight notification. For testing Android version, maybe is better with email: adrisoacha@gmail.com

This is great! Thanks, 

Karen
