### ISSUE TITLE
Image and ID preview not working on Twitter

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1055]
When sharing a link on twitter, it would be much more attractive and informative to display an image thumbnail and the species id. See screen shot below.

![screen shot 2016-07-12 at 2 32 40 pm](https://cloud.githubusercontent.com/assets/7501183/16778801/8c06c1a2-483d-11e6-9a7b-bc9e832dde5e.png)

...and I feel a little foolish for sharing a sad-looking link.

I think this used to work? Apparently I haven't tried in a few months, but it was working back in April. (see another screen shot of me trying to be an inaturalist evangelist while also tweeting about something else). 
![screen shot 2016-07-12 at 2 34 46 pm](https://cloud.githubusercontent.com/assets/7501183/16778861/e8df17a8-483d-11e6-8fce-8fb40c355597.png)

**Comment by alexshepard** [comment]
What's the observation URL?

**Comment by carrieseltzer** [comment]
http://www.inaturalist.org/observations/3667339
and
http://www.inaturalist.org/observations/3667342

**Comment by carrieseltzer** [comment]
And the twitter links: https://twitter.com/carrieseltzer/status/752932338045255680
https://twitter.com/carrieseltzer/status/752927904162574336

**Comment by kueda** [comment]
This happens when we have a photo without a file extension, and at the moment this is happening for all iPhone observations made with the last version or two. We're working on fixing that. However, this is kind of a more pervasive problem whenever we receive a photo with no file extension info, and we have a number of photos like that, mostly from the apps. Ensuring that they all get an appropriate extension requires consistent detection of the content type, and I'm not convinced that's happening on the server. Still not sure why, though...

**Comment by carrieseltzer** [comment]
Oh wow, I see what you mean. The images I've uploaded from my phone aren't showing ANY photo metadata on iNat. I downloaded the same image, added it to the observation, and re-ordered them so that one is first.
Uploaded from 2.6.13 build 338: http://www.inaturalist.org/photos/4246454
Downloaded and then uploaded on the website: http://www.inaturalist.org/photos/4252292

I'll use the workaround for the time being to only tweet out observations that I've uploaded on the website. Unfortunately, twitter doesn't seem to re-try the link (or maybe it just takes more time?).

Interestingly, images uploaded from the iOS app DO get previews in Facebook (but you have to paste it in twice because it never works the first time), but no taxonomic description. 

![screen shot 2016-07-13 at 10 29 19 am](https://cloud.githubusercontent.com/assets/7501183/16806974/bb50ae8a-48e4-11e6-8e31-316e83fccc78.png)

**Comment by alexshepard** [comment]
Can you try the latest TestFlight release (2.6.14 build 239), Carrie? It should fix thumbnails on Twitter for new uploads from iOS. Fixing thumbnails for affected, previously uploaded photos

**Comment by carrieseltzer** [comment]
Metadata came through on pics, but pic still didn't appear on Twitter. Maybe there's a lag? I'll check later this afternoon

![screen shot 2016-07-14 at 11 53 26 am](https://cloud.githubusercontent.com/assets/7501183/16846279/c6199d06-49b9-11e6-936b-6bca8756323c.png)


Taxonomic description also still not working on Facebook or Twitter. 

![screen shot 2016-07-14 at 11 53 26 am](https://cloud.githubusercontent.com/assets/7501183/16846283/cfb17da2-49b9-11e6-8966-e4f798fcc10d.png)

**Comment by alexshepard** [comment]
Can you give a link to the observation?

**Comment by carrieseltzer** [comment]
Oops! Sorry! http://www.inaturalist.org/observations/3677025

**Comment by alexshepard** [comment]
Thanks @carrieseltzer 

http://www.inaturalist.org/observations/3677025.json

Looks like the file extensions are in the thumbnail URLs, @kueda 
What next?

**Comment by kueda** [comment]
You got me, one of the mysteries of twitter. I went to https://cards-dev.twitter.com/validator and the image showed up after I tried it a few times. I suspect that sometimes sites like twitter will just give up if they can't load the image fast enough, but of course, they also complain if they can't get an image that's big enough.

**Comment by carrieseltzer** [comment]
It's all working now, image and taxon. I think there's just a bit of a lag before twitter picks up the preview image for some reason. Facebook is a little bit like that in that it NEVER gets the image the first time a URL is pasted in so I know there's some kind of lag/caching there too. I think we can close this. Thank you!

**Comment by kueda** [comment]
This *should* be fixed. New photos added to the site are getting a file extension whether they like it or not, and the iPhone app has been updated to send photo data a bit more like it was before the recent change.
