### ISSUE TITLE
Idea: Embed google group somewhere in iNat site

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1056]
The Google Group is a little hard to find. There are 1004 members of the Google group which is a small fraction of the 70K+ who have added observations (I'm counting unverifiable there). 

Here's another site that displays their google group posts within the site: http://symbiota.org/docs/google-group/

**Comment by kueda** [comment]
What's the advantage of doing this vs. linking directly to it from the footer? If we embed it that won't make it any easier for people to actually participate int he Google Group.

**Comment by carrieseltzer** [comment]
I think the advantage is visibility and findability. I wouldn't click on feedback in the footer unless I really had something to say, but if I were poking around for more information about iNaturalist and saw that there are several posts a day in a forum-like space I might be interested in exploring. Since you don't have to be logged in to read the posts, I think people are more likely to stumble across them if it's visible on a page within iNaturalist, maybe somewhere in the help or about sections.

**Comment by carrieseltzer** [comment]
This is clearly no longer relevant considering the awesome integration of the Discourse forum.
