### ISSUE TITLE
Dashboard Quick Fixes

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1057]
There's a bit of duplication going on and perhaps some unnecessary info present by default.

@loarie Just out of curiosity is it possible to hide the observation blurb within the timeline so it's only visible when the update is expanded. See below mock ups....
### Current

![image](https://cloud.githubusercontent.com/assets/11527994/16821226/fb1b054a-4909-11e6-83f7-aa22a891d054.png)
##### Collapsed

![image](https://cloud.githubusercontent.com/assets/11527994/16821284/291783a6-490a-11e6-9b01-ea3e1c28016f.png)
#### Expanded
- The ob blurb is only available when expanded. 

![image](https://cloud.githubusercontent.com/assets/11527994/16821370/c48f01c4-490a-11e6-808a-eb65f1285047.png)
#### Collapsed with larger thumbnail

Here's a look at what it would look like with a larger thumbnail on the left.

![image](https://cloud.githubusercontent.com/assets/11527994/16821670/5f71f3e4-490c-11e6-81a7-2694a106a7e7.png)
# Agree Button

It's a little inefficient that clicking the Agree button takes you to the observation since the whole point of having it there is to agree from that page. I think @kueda mentioned it would be difficult to change that. Just wanted to document this. What about having it open in a new tab so at least the user isn't taken from the page?

**Comment by joellebel** [comment]
Will let you know when this issue is ready to go...

**Comment by joellebel** [comment]
Ok. This issue is ready to go!

**Comment by kueda** [comment]
IMO having the observation context is a good thing. I'm ok with having the "Agree?" link open a new tab, though.

**Comment by loarie** [comment]
@joellebel thats how it was when we first released it to gorilla but the (only 2) google group comments were do to confusion thinking the ident row was the obs row and thus confusion about why the default taxon photo: https://groups.google.com/d/msg/inaturalist/up78oJkNAoY/j6lp2iRAAQAJ

You were on vacation at the time so I just made that change to keep Tony and Kent happy but happy for alternative solutions. Your proposed larger timeline icon might help some but read through the Google feedback

**Comment by joellebel** [comment]
Ok. Will read through the google feedback. 2 peops doesn't sound like an alarming number to me. Weren't people also complaining that it was too spread out and long?
