### ISSUE TITLE
uuids for anything you can make with the APIs

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1059]
Server-generated sequential IDs are problematic for a lot of reasons, but the worst for us is that mobile clients can't know what they are before the send data to the server, which makes it tricky to deal with syncing data, especially in poor network conditions. We already partially handle this with the `uuid` columns in `observations` and `observation_photos`, but the same problems exist for any record that can be made and submitted through our API, and we don't currently generate UUIDs for records not made by our own mobile apps.

So to conclusively deal with this I think we need UUIDs for all records you can make with the APIs, certainly ones used by our mobile apps.

- [ ] add UUID columns for models you can make with the APIs that don't already have them
  - [ ] `Comment`
  - [ ] `Identification`
  - [ ] `ObservationFieldValue`
  - [ ] `ProjectObservation`
- [ ] change models that have UUIDs to set them on creation
  - [x] `Observation`
  - [ ] `ObservationPhoto`
- [ ] Set UUIDs on all past records that don't have them
  - [ ] `Comment`
  - [ ] `Identification`
  - [ ] `ObservationFieldValue`
  - [ ] `ProjectObservation`
  - [ ] `Observation`
  - [ ] `ObservationPhoto`

@alexshepard, am I missing anything? @pleary, does this seem reasonable? Probably going to be a lot of extra data in a number of tables.

**Comment by alexshepard** [comment]
Is there any way to lazily generate them?

**Comment by kueda** [comment]
https://github.com/inaturalist/inaturalist/pull/1088
https://github.com/inaturalist/inaturalist/pull/1106
