### ISSUE TITLE
Card borders

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1062]
@kueda can we add the standard bootstrap outlines to the grid view cards on /observations and any where else we have cards? On on o screen you can't see the gray bg color of the page and so you don't get the box at all, sadly.

#### Current
![image](https://cloud.githubusercontent.com/assets/11527994/16890046/f084fdec-4a9f-11e6-9eef-6f16c7320fb8.png)

#### Proposed

It would look like this with the border...

![image](https://cloud.githubusercontent.com/assets/11527994/16890103/814172de-4aa0-11e6-9691-c1d1f04ad638.png)

**Comment by kueda** [comment]
This issue should be done.
