### ISSUE TITLE
New Activity State

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1063]
When receiving dozens of IDs at time I'm finding it easier to check them on mobile because they are clearly indicated in the list view with a red icon. I realize we will one day redo the list view on webalong with the dashboard, but wanted to propose the below idea of a new activity state when there is new activity on an ob that user has not seen yet... 

The third and fourth obs have new comments and IDs indicated with the dark pink badge....

![image](https://cloud.githubusercontent.com/assets/11527994/16890268/dcea96e6-4aa1-11e6-9887-237d7379143e.png)

Here's how it would look on the grid view...

![image](https://cloud.githubusercontent.com/assets/11527994/16890473/dd4bd9c2-4aa3-11e6-8af4-4760cad0b8af.png)

Here's a reverse treatment, but I don't think it's as noticeable...

![image](https://cloud.githubusercontent.com/assets/11527994/16890497/05e70ee2-4aa4-11e6-8c90-37cb32cf1b45.png)

Looking forward to everyone's feedback.

**Comment by joellebel** [comment]
@loarie @kueda @tiwane @pleary @alexshepard interested in your input. 

Just wondering if anyone else would find this useful? I don't think we need to revise the "Your Observations" screen anymore. However, some sort of indication in obs search grid view would be handy. Would that significantly slow down page loads?

**Comment by alexshepard** [comment]
It took me a few minutes of looking at the middle grid view to even find what you were talking about, so I would say it might need more emphasis/differentiation.

**Comment by joellebel** [comment]
@alexshepard were you looking at this view, at 100% zoom? https://cloud.githubusercontent.com/assets/11527994/16890473/dd4bd9c2-4aa3-11e6-8af4-4760cad0b8af.png
