### ISSUE TITLE
Page 2 Link in Pagination Links Broken on /Observations

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1065]
Whenever I am looking at observations in grid view here: http://www.inaturalist.org/observations/ and click on page 2 here...
![image](https://cloud.githubusercontent.com/assets/11527994/16891807/cf2e9dbe-4ab4-11e6-98b1-06a8a7cce93e.png)

...nothing happens when I click the link. However, when I go to page 3, it works from there.

**Comment by tiwane** [comment]
Seems to only happen to me when I'm filtering. Works when no filters are selected.

**Comment by joellebel** [comment]
This appears to work for me now both with and without filters.
