### ISSUE TITLE
When not logged in, obs search offers and defaults to "Your Observations"

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#1071]
"Your Observations" probably shouldn't even be an option if you're not logged in, and certainly shouldn't be highlighted by default

**Comment by joellebel** [comment]
I agree it probably shouldn't be highlighted when not logged in. However, the presence of it can be an entry way for sign ups. For example, when someone clicks on it they can get a modal prompting them to log in / sign up. Also, sometimes I think I'm logged in, but I'm not. It would be a helpful prompt for folks that already have an account to log in.

**Comment by joellebel** [comment]
Looks like we went with the former. okeedoke. I take it that was probably easier?

**Comment by kueda** [comment]
Yeah, but I also just feel like that would be a pretty weak place to recruit new users. IMO the strongest place to entice new users who have been browsing the site to sign up is probably comments and IDs.
