### ISSUE TITLE
Hide dashboard item gear icon when not relevant

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/inaturalist#1073]
I'm not sure what it is that I'm no longer subscribed to here?

I'm not sure if this is happening because I can't unsubscribe to my own content, or because I can't unsubscribe to projects that I'm not a member of, but this tooltip is confusing.

![image](https://cloud.githubusercontent.com/assets/515947/17110749/5b99a8de-5253-11e6-9f76-67b4fd495418.png)

**Comment by kueda** [comment]
This applies to updates about

- [ ] project aggregation
- [ ] taxon changes

Anything else you've noticed?

**Comment by alexshepard** [comment]
All I've noticed it on is project aggregation.
