### ISSUE TITLE
Unobserved by You filter

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1081]
I know we're all busy, but I would LOVE LOVE LOVE a "Unobserved by You" filter on obs search here...

![image](https://cloud.githubusercontent.com/assets/11527994/17160105/512db638-5357-11e6-91a9-34b5b70fffb7.png)

This way I could quickly see where I'm lacking in obs and set some personal goals. 

It could go right under "Threatened"

**Comment by kueda** [comment]
So what you mean here are "observations of taxa that you haven't observed" right?

**Comment by joellebel** [comment]
correct!

**Comment by joellebel** [comment]
One other idea is this...

![image](https://cloud.githubusercontent.com/assets/11527994/18178192/4166d502-7032-11e6-9499-6a7d47a07d58.png)

Pros:

* You could more easily and quickly toggle between what you've seen and haven't

Cons: 

* After toggling an option (for example, choosing "Unobserved by You) and clicking back to the Observations tab, folks unconsciously may be expecting to see those search results filtered to Unobserved by You as well. However, I think it's pretty apparent that ui below the tabs refer only to that tab. 


I prefer this option, but if the first option is a lot quicker I'd be happy with that. 

I also think "Unobserved by You" is kinda clunky. I'm totally open to other ideas for that label.

**Comment by joellebel** [comment]
Just wondering if anyone had any feedback on the latest design for this feature. I'm a big fan of the toggle being closer to the images as opposed to having to crawl back up to the filters menu.... but I'm also very excited about this feature ;)

**Comment by pleary** [comment]
We now have a filter in the API for this http://api.inaturalist.org/v1/observations/species_counts?rank=species&unobserved_by_user_id=42780&place_id=2

**Comment by joellebel** [comment]
Beautiful.

**Comment by joellebel** [comment]
@pleary and @kueda I was talking about this issue. When you get a chance, can you pass along the url. The api thing is little weird for me. Thanks!

**Comment by loarie** [comment]
the api URL two comments up is all there is
