### ISSUE TITLE
Mentioning someone in tags doesn't notify them

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1087]
Should mentions work in tags? I told someone "tag me in your observation @carrieseltzer" and he did exactly that, but I didn't get a notification from iNaturalist. 

Link to observation: http://www.inaturalist.org/observations/3784985

If this isn't an easy fix I'll just be more explicit with my instructions to new users. Usually they use the app so it isn't an issue since there isn't a tags field there.

**Comment by kueda** [comment]
IMO this is an extreme edge case that has more to do with people not understanding what the very "tag" in this context. I'd say close this unless there are strong objections.

**Comment by carrieseltzer** [comment]
Agreed. I'll be more explicit in my instructions to new users in the future. Thanks!
