### ISSUE TITLE
Naturalista.Co: errors in text and images Android version

### ISSUE THREAD

**Issue by adrisoacha** [inaturalist/inaturalist#1091]
Hi @loarie,
Please check the text and images in the Android version.
Logo is pixelated
Text is in english and is incorrect

![screenshot_20160802-222037](https://cloud.githubusercontent.com/assets/16558682/17367990/eb59e438-5957-11e6-813f-ee64a3f68f60.png)

Our suggest: 
NaturaLista Colombia es miembro de la red iNaturalist. Selecciona OK para compartir tus datos y que la información que recibes esté de acuerdo con tu ubicación.

Thanks!
Karen

**Comment by loarie** [comment]
@budowski what dimensions do you need for an unpixelated logo? Also - do you know why the text is not being translated? Ideally in Spanish it would say: '¿Usar Naturalista Colombia?
Selecciona aceptar para compartir tus datos y que la información que recibes esté de acuerdo con tu ubicación.
No / Aceptar'

**Comment by kueda** [comment]
Please file Android issues in https://github.com/inaturalist/iNaturalistAndroid. This repo is for the Rails application that powers the website.

**Comment by loarie** [comment]
whoops sorry thought this was https://github.com/inaturalist/iNaturalistAndroid/issues/192 - @adrisoacha please comment on that issue there
