### ISSUE TITLE
Naturalista.Co: errors in text and images iOS version

### ISSUE THREAD

**Issue by adrisoacha** [inaturalist/inaturalist#1092]
Hi @loarie 

Our suggest for this text:

¿Usar Naturalista Colombia?
Selecciona aceptar para compartir tus datos y que la información que recibes esté de acuerdo con tu ubicación.
No / Aceptar

Naturalista logo may be larger?

![img_3174](https://cloud.githubusercontent.com/assets/16558682/17372949/ad785a82-596b-11e6-8bc5-4c7b774fa747.PNG)

**Comment by loarie** [comment]
@alexshepard, what dimensions of the logo do you need? Also is the same 'Use XXX?' text used for all sites or can the preferred text be easily inserted?

**Comment by kueda** [comment]
If you have issues with the iNat app please contact us directly or file issues in https://github.com/inaturalist/INaturalistIOS/

**Comment by loarie** [comment]
whoops sorry thought this was https://github.com/inaturalist/INaturalistIOS/issues/296 @adrisoacha please add comments to that issue there
