### ISSUE TITLE
Change "Subscribe" text to "Follow" throughout site

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1093]
The below is places are where a form of "Subscription" is used.
#### Dashboard

![image](https://cloud.githubusercontent.com/assets/11527994/17452858/8cde5272-5b28-11e6-9036-f309e39c91ca.png)
#### Ob detail

![image](https://cloud.githubusercontent.com/assets/11527994/17452870/b04f10ac-5b28-11e6-994f-cc8ef4353fe5.png)
#### Species Page

![image](https://cloud.githubusercontent.com/assets/11527994/17452956/baef01d8-5b29-11e6-9973-f85a2232d596.png)
#### Places

![image](https://cloud.githubusercontent.com/assets/11527994/17452969/de50dd68-5b29-11e6-9027-355706b330bf.png)

**Comment by kueda** [comment]
Do you also want to change the word "Subscriptions" and if so to what? "Followings" sounds weird to me.
