### ISSUE TITLE
Naturalista.Co: sig in facebook doesn't work

### ISSUE THREAD

**Issue by adrisoacha** [inaturalist/inaturalist#1096]
Hi @loarie 

When try to sig  in with facebook:
![log in face](https://cloud.githubusercontent.com/assets/16558682/17463642/de587b1a-5c8f-11e6-9122-dcc8471ac3a0.png)

Thanks!
Karen

**Comment by pleary** [comment]
Thanks for making a ticket. Logging in to http://naturalista.biodiversidad.co/ via Facebook should be working now
