### ISSUE TITLE
Update how we calculate project.update_users_taxa_counts

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#1108]
project has a method update_users_taxa_counts (https://github.com/inaturalist/inaturalist/blob/master/app/models/project.rb#L693) that is count distinct taxa a user has observed based on their ID OR project curator ID. Those counts now differ from the scoreboard where we're showing counts from ES.

This is one of the slowest queries we run, and it runs all the time, for example during project aggregation. I'd like to make the count just taxa observed, and perform the query with ES

**Comment by pleary** [comment]
As far as I can tell the column ProjectUser.taxa_count is used in 4 places:
http://www.inaturalist.org/projects/vermont-atlas-of-life?iframe=true (as species)
http://www.inaturalist.org/projects/vermont-atlas-of-life/contributors (as taxa observed)
http://www.inaturalist.org/projects/vermont-atlas-of-life/contributors/pleary (as taxa observed)
http://www.inaturalist.org/projects/vermont-atlas-of-life/contributors?format=widget (as species)

The current query is looking at the observations the user has in the project and is counting the distinct taxa where the observation's taxon is a species or below, OR where the latest project curator ID is a species or below. The curator ID bit is specific to this project species count, so it produces different numbers than say obs search http://www.inaturalist.org/observations?place_id=any&project_id=558&verifiable=any&view=observers . It's also a super slow DB query that can take multiple seconds per query.

I am proposing changing this logic to ignore the project curator ID bit and just count the obs species like we do in other places, and to have the counts be consistent with what's on obs search. I could then use a faster elasticsearch query to generate the counts. Thoughts?

**Comment by kueda** [comment]
I will defer to @loarie on this one. I suspect this was one of the many inane contortions we employed to satisfy project managers (in this case managers who wanted *their* IDs to be the ones that counted, not necessarily observers). I'd be more happy with consistency.

**Comment by loarie** [comment]
I'd prefer that we count consistently as we do on obs search (specifically you mean leaves with subspecies rolled up to their species parents correct)?

**Comment by pleary** [comment]
Ok, so it sounds like you're in agreement with my proposal. Yes, specifically the counts will be the count of distinct "species", where anything under species is counted as it's species. So it's not "leaves", but this more intelligent "species" count, which is the same as we use on obs search or the project main page stats.

So shall I merge and deploy?
