### ISSUE TITLE
Withdraw link removal

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1113]
How does everyone feel about the "withdraw" link only showing up on hover? Right now it's so showy it's almost making me second guess my IDs. ;) Also, this would be consistent with the Edit and Flag links.

**Comment by kueda** [comment]
When filing issues please remember to explain where on the site you're talking about with URLs. We show the Withdraw link in a number of places. Which ones are you referring to specifically?

**Comment by joellebel** [comment]
Sorry. Here...

http://www.inaturalist.org/observations/3905305

![image](https://cloud.githubusercontent.com/assets/11527994/17756884/d708e5f6-6497-11e6-8fbd-bed65e40b090.png)

The "Withdraw" right next to "Your ID: West Coast Lady (Vanessa annabella)"

**Comment by kueda** [comment]
Sure, I'm ok with that.

**Comment by joellebel** [comment]
Just out of curiosity... where else does the "Withdraw" show up on the site? I'll add it to this issue.
