### ISSUE TITLE
new loading states for Identify

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1119]
When you make a new comment or ID in Identify, the only loading indicator is a spinner at the bottom of the list of comments and IDs. If that list isn't scrolled to the bottom, you don't see it, which causes some people to click "Agree?" a million times, but also just doesn't adqueately communicate state to the user.

- [x] When you click "Agree?" next to an identification the button should be replaced with a disabled spinner button, a la the "zoom-in" example at http://msurguy.github.io/ladda-bootstrap/
- [x] Use the same treatment for the Agree button in the modal footer
- [x] Use the same treatment for the Agree buttons in the obs grid
- [ ] <s>Use the same treatment for the Save button in comment form</s> [doesn't really make sense since we just hide that form on submit anyway]
- [ ] <s>Use the same treatment for the Save button in identification form</s>
- [x] When any of these actions complete (i.e. we're no longer loading), scroll to the bottom of the discussion list to show the new item

Optional: different BG treatments for identification being agreed with, some kind of flash animation for newly inserted item.

**Comment by joellebel** [comment]
Just for visual reference... 

## Button Progress State

* button and button border turn #74ac00; loader animation is white. (Disregard the fact that the loader is a little too big in this mock up)

![image](https://cloud.githubusercontent.com/assets/11527994/17867815/ed8d4250-6860-11e6-9f96-3922fb3f496c.png)

## State Proposal for new comment and IDs

When a new ID is added from the agree button, the column scrolls down to reveal the latest ID added and the new ID is #74ac00 at 10% for about 3 seconds and then fades to 0%.

Note: I also added an "Agreed" badge. This is something we currently don't do elsewhere in the site. Let me know if you want to tackle it later. If we don't do the Agreed badge, then the "Agree" button should should get the same disabled state treatment (minus the checkmark) as the footer Agree button. 


![image](https://cloud.githubusercontent.com/assets/11527994/17869150/c7426f98-6866-11e6-8b74-8a89e5c94e7b.png)
