### ISSUE TITLE
default taxon_name position should be nil not 0

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1125]
currently the default TaxonName.position = 0
but this means that if there has been previous work towards curating the order of taxon names (position  = 1,2,3,...) and a new taxon name is created (which will have the default position = 0)
then that new name will become the default name (0 < 1,2,3,...)

The position of these new names should default to a position greater than curated positions (1,2,3,etc.) 

One solution would be to make the default position nil and ensure that nil is treated as a position greater than all integers

Alternatively, we could add logic to make 0 treated as a position greater than non-zero integers in the context of taxon_name positions

thoughts @kueda? This issue was raised by James here https://groups.google.com/forum/#!topic/inaturalist/1UvqMXcWNgg

**Comment by kueda** [comment]
@loarie, I assume @cyberhobo's solution works for you? He's just assigning every new taxon name a position greater than all the existing positions, so it should always sort last.

**Comment by loarie** [comment]
looks great - thanks @cyberhobo! look forward to alerting the google group when this is deployed

**Comment by kueda** [comment]
Should be deployed now if you want to test.

**Comment by loarie** [comment]
Tested and looks great. Thanks Dylan! I'll email the google group

**Comment by cyberhobo** [comment]
Sweet! Glad that's sorted.
