### ISSUE TITLE
new taxon page

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1132]
Functional Spec: https://docs.google.com/document/d/12Jv2Fdu-DkLTTz2cD78ZXiHl-Y1KHJYSC7y2I5ni1Ec
Design: https://projects.invisionapp.com/share/GP8CRSB5Z
UX: https://docs.google.com/document/d/1XKYJf12s2hfIBxASPcT1gGJPCMyRehpkEdVoS8YUPcM

Pending API issues
- https://github.com/inaturalist/iNaturalistAPI/issues/35
- https://github.com/inaturalist/iNaturalistAPI/issues/36
- https://github.com/inaturalist/iNaturalistAPI/issues/37
- https://github.com/inaturalist/iNaturalistAPI/issues/40

Progress:
- [x] preheader
  - [x] ancestry
  - [x] permalink
  - [x] search
- [x] header
  - [x] name
  - [x] location chooser
- [x] hero
  - [x] conservation status
  - [x] photo preview
  - [x] leaders
    - [x] observer
    - [x] identifier
    - [x] species
    - [x] total
  - [x] charts
    - [x] month histogram
    - [x] chronology
- [ ] tabs
  - [x] map
  - [x] articles
    - [x] artcile (no ability to switch?)
    - [x] taxon links
  - [x] highlights
    - [x] popular descendant species
    - [x] rare descendat species
  - [ ] interactions
    - [ ] ???
  - [x] taxonomy
    - [x] hierarchy
    - [x] links
  - [x] names
  - [x] status
  - [x] curation button

**Comment by kueda** [comment]
Some remaining todos, mostly from feedback in the Google Group:

- [x] add taxon_changes_count and taxon_schemes_count to the index
- [x] handle inactive taxon, e.g. "Hyla regilla was swapped into Pseudacris regilla"
- [ ] sticky
  - [x] place preference
  - [x] tab choice
  - [ ] taxon crumb expansion
- [ ] zoom map to the extent of the observations
- [ ] stop histograms from flickering with every update: need to get shouldUPdateWIthProps working, or whatever
- [ ] trending cards are too small to show a lot of scinames, and too small to really compare the images
- [ ] inf scroll approach for grouped photo browser results
- [ ] photo viewer: sort grouped results by faves
- [ ] deleting a photo should re-index all associated taxa
- [ ] grafting a taxon should re-index the taxon
- [ ] editing a taxon name should re-index the taxon
- [ ] source is not linked at "Near Threatened Globally (Source: IUCN Red List)"
- [x] alphabetize taxa in taxonomy tab
- [ ] experiment with the wikipedia summary up top
- [ ] tooltip for first observation
- [ ] can we get attribution on the PhotoPreview
- [ ] endemic / introduced status bar
- [ ] tooltip for crumbs in taxon crumbs
- [ ] more names below main name
- [ ] unicode chars f'ing up, e.g. http://www.inaturalist.org/taxa/243970-Larus-glaucescens---occidentalis and 
- [ ] brand new taxon that hasn't been indexed yet doesn't show
- [ ] don't show view yours link if you haven't seen it

**Comment by joellebel** [comment]
I have to Greg Shuetrim...

> A minor issue - "highlights" is not a very informative name for the tab showing recent activity (trending/rare occurrences). I was not sure what to expect under that tab but perhaps "trends" might be more indicative (interpreting a lack of records for a taxon as a trend of a different kind).

"Trends" would be a more descriptive name for this tab since technically both most observed and least observed are trends. 

In case we don't want any repetition, the "Trending" heading could be "In Season" (not sure though if that term is inaccurate for some taxa) 

@kueda not sure where to put this feedback. Let me know if you would like it somewhere else.

**Comment by joellebel** [comment]
In the photo browser on rollover, can we add back the name of the species for both grid and quilt view. Talking about this rollover...


![image](https://cloud.githubusercontent.com/assets/11527994/21155818/80610ad8-c128-11e6-8753-03d4c6252975.png)

**Comment by joellebel** [comment]
In the name of [Leonard Cohen...](https://www.youtube.com/watch?v=ttEMYvpoR-k&feature=youtu.be&t=37)
