### ISSUE TITLE
'mappable' shouldn't include  'Evidence of Organism = no'

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1140]
e.g. http://www.inaturalist.org/observations/1847929 which has 'Evidence of Organism = no'
<img width="1018" alt="screen shot 2016-09-12 at 2 51 24 pm" src="https://cloud.githubusercontent.com/assets/598026/18454314/68f32d86-78f8-11e6-98c7-d3fd12060eff.png">
but is mappable
```
o = Observation.find(1847929)
o.mappable
 => true 
```

**Comment by loarie** [comment]
nor appropriate = no http://www.inaturalist.org/observations/3214501

**Comment by pleary** [comment]
new rules deployed and affected observations updated
