### ISSUE TITLE
add identifications to the ES index

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1142]
This will allow us to

1. Open up /identifications
1. Make an endpoint that shows taxa similar to other taxa based on misidentifications (#1138)
1. ???
1. Profit

@loarie, if there are other use cases for IDs in ES you can think of, please holler, b/c re-indexing identifications will be time consuming, so we should get as much as we need in there on the first go.

**Comment by loarie** [comment]
Things I'm aware of...
General site scalability:
5. reduce performance hit from taxonomy curation
Obs Detail revamp:
6. Make endpoint that shows people who can help ID an observation based on past IDs (for new obs detail screen)
Missions Roadmap:
7. Make endpoint that shows 'iNat records' https://github.com/inaturalist/inaturalist/issues/630#issuecomment-245181664 (if approach seems reasonable and feasible) for a place/time-cutoff
8. We'll need a way to make sure a Science Mission for species X only gets sent to a person who has improving IDs for species X, but not all details of 'Generating Science Targets for User / Location'  endpoint worked out (see missions roadmap)

**Comment by pleary** [comment]
This ticket as worded is done since there is an IDs index that is populated. Some of Scott's items are also done, but they don't all have separate tickets. Please create them as separate tickets if they still need to be tracked
