### ISSUE TITLE
Spelling error in website boilerplate text regarding "You've got updates"

### ISSUE THREAD

**Issue by shuetrim** [inaturalist/inaturalist#1143]
Here is a first shot at raising a Github issue:

The text in the "You've got updates" section on my [iNat home page](http://www.inaturalist.org/home) is

Stay current with updates on the following...

Your Content: Activity on your observations such as comments, identifications, or faves from the iNaturalist community. You will also receive updates when someone adds your observation to a project or annotated it with additional fields.
People: New observations or journal posts from the people you follow.
Organisms, Projects & Places: New observations from specific organisms or places you're subscribed to'. You can also join projects to be updated when they publish project journal posts.
Discussions you've engaged in: Commenting or adding identifications to someone >>>elses<<< content automatically subscribes you to any new activity on this content. Use the 'Manage your subscriptions' tool to stop >>>>recieving<<< updates.

"elses" should have an apostrophe, I think...

Also "receiving" is misspelt.

Regards

Geoff Shuetrim

**Comment by shuetrim** [comment]
I am going to fix the problems in the en.yml file (there are a couple of other recieve instances in the file) and will issue a pull request, just to make sure I have the workflow down...

**Comment by kueda** [comment]
Pull request works for us!

**Comment by loarie** [comment]
great talking you today Geoff!

**Comment by shuetrim** [comment]
Just to confirm, is [this process](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/) the one that you prefer contributors to use?

**Comment by kueda** [comment]
Pretty much: fork, feature branch, PR. Though for minor stuff in repos that you're not doing a lot of active dev on, just using github's editing functionality is probably fine too (basically does the same thing minus the feature branch, I think).

**Comment by carrieseltzer** [comment]
This was fixed in https://github.com/inaturalist/inaturalist/pull/1145
