### ISSUE TITLE
iNaturalist setup on Ubuntu - syntax errors in elastic_model.rb during database setup

### ISSUE THREAD

**Issue by shuetrim** [inaturalist/inaturalist#1146]
I am trying to set up iNaturalist on a Ubuntu 15.04 server, following the [development setup guide](https://github.com/inaturalist/inaturalist/wiki/development-setup-guide)

The command:
rake db:setup
is failing with a message:

`
Couldn't create database for {"host"=>"localhost", "encoding"=>"utf8", "adapter"=>"postgis", "username"=>"geoff", "template"=>"template_postgis", "database"=>"inaturalist_test"}
rake aborted!
SyntaxError: inaturalist/lib/elastic_model/elastic_model.rb:159: syntax error, unexpected ':', expecting =>
          { term: { "user.id": opts[:user].id } },
                              ^
inaturalist/lib/elastic_model/elastic_model.rb:159: syntax error, unexpected '}', expecting keyword_end
          { term: { "user.id": opts[:user].id } },
                                               ^
inaturalist/lib/elastic_model/elastic_model.rb:160: syntax error, unexpected ':', expecting =>
...envelope: { "private_#{field}": coords } }) ]}
...                               ^
inaturalist/lib/elastic_model/elastic_model.rb:279: syntax error, unexpected end-of-input, expecting keyword_end
`
I then set up elasticsearch before retrying the database setup but that did not resolve the issue.

**Comment by englishm** [comment]
This looks like you might be using an older version of Ruby that doesn't recognize the newer hash syntax. What version of Ruby are you using?

**Comment by shuetrim** [comment]
It looks like Ruby 2.1.2 was installed as a dependency by the apt-get install rails command.

**Comment by kueda** [comment]
FWIW I'm using Ruby 2.2.1p85 locally, so anything at that version and above should be fine. I highly recommend using RVM. The dev setup guide is basically always out of date, so look upon it with a jaundiced eye. There's also https://github.com/pleary/inaturalist-vagrant, which *might* still work, though I kind of doubt it.

**Comment by shuetrim** [comment]
Thanks.  I will sort out the Ruby upgrade through RVM and see how I get on.

**Comment by pleary** [comment]
That inaturalist-vagrant repo is out of date and should probably be removed. The newer way is to use vagrant through test-kitchen in https://github.com/inaturalist/inaturalist-cookbook . But none of that is documented, and there are probably some things out of date in there that need updating. At one point I had visions of creating development machine images that you could download and run in VirtualBox or something, but we just never had any potential users so it never came to be.

I'd be interested to hear how you make out, and if you have any recommendations for us to help people like you get starting working on the Rails codebase.

**Comment by shuetrim** [comment]
Thanks for the guidance on the inaturalist-vagrant repo.  I will avoid it.  As I go through the setup process I am putting together one or more shell scripts that do the basic web server installation and configuration. They can be added to the relevant Wiki page when I have it working.

**Comment by shuetrim** [comment]
I now have the iNat homepage running on a test machine now. The process was pretty smooth given I have no background with Ruby/Rails etc.

I did run into a few errors while doing the rake db:setup step:
#Couldn't create database for {"host"=>"localhost", "encoding"=>"utf8", "adapter"=>"postgis", "username"=>"postgres", "template"=>"template_postgis", "database"=>"inaturalist_test"}
#inaturalist/db/structure.sql:14: ERROR:  unrecognized configuration parameter "row_security"
#inaturalist/db/structure.sql:34: ERROR:  PostGIS is already installed in schema 'public', uninstall it first
#inaturalist/db/structure.sql:41: ERROR:  extension "postgis" does not exist
#inaturalist/db/structure.sql:262: ERROR:  function "st_aslatlontext" already exists with same argument types
#inaturalist/db/structure.sql:14: ERROR:  unrecognized configuration parameter "row_security"
#inaturalist/db/structure.sql:34: ERROR:  PostGIS is already installed in schema 'public', uninstall it first
#inaturalist/db/structure.sql:41: ERROR:  extension "postgis" does not exist
#inaturalist/db/structure.sql:262: ERROR:  function "st_aslatlontext" already exists with same argument types

But at end I had both inaturalist_test and inaturalist_development databases installed (Checked in pgadmin) as did the seed data. 

For posterity, the steps on Ubuntu are set out in [the attached text file](https://github.com/inaturalist/inaturalist/files/479206/inaturalist.on.ubuntu.guide.txt).

**Comment by kueda** [comment]
K, I assume this is no longer a problem then, so I'm closing. I also should have mentioned earlier on that https://github.com/inaturalist/inaturalist/blob/master/.travis.yml is probably a good guide for Ubuntu users as well, since those are instructions we send to travis when it sets up machines for continuous integration.
