### ISSUE TITLE
Atlases

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1154]
An atlas describes a set of continuous, non-overlapping places covering the Earth's land surface (atlas places)
<img width="999" alt="screen shot 2016-09-27 at 9 45 52 pm" src="https://cloud.githubusercontent.com/assets/598026/18901031/319f3630-84fc-11e6-8e01-0ae72bd8d9ef.png">
'atlas presences' are the a atlas places that encompass a species range while 'atlas absences' are the atlas places that are outside the species range
<img width="898" alt="screen shot 2016-09-27 at 9 46 10 pm" src="https://cloud.githubusercontent.com/assets/598026/18901049/677e8d32-84fc-11e6-8968-33dcd25978c1.png">
Atlas presences are determined from the existence of default_checklist listed_taxa for the species for the atlas places. Atlas absences are implied from the absence of default_checklist listed_taxa for atlas places
```ruby
# new model
Atlas
  # taxon
  # place_set
  # comments

  # after_create
  #  update manually_added = true for all listed_taxa in atlas place_set
  #  (or some other way of making sure they don't get destroyed
  #  if the observation they are sourced to is destroyed)
```
Here the place_set summarizes the set of admin_level 0,1,& 2 places that comprise the atlas (atlas places). The notation for place_set is [[explode_admin0],[explode_admin1]] where explode_admin0 is the array of admin_level 0 place ids that are exploded (e.g. swap out the country US for the set of descendant states) and explode_admin1 is the set of admin_level 1 place ids that are exploded (e.g. swap out the state CA with the set of descendant counties). 

Thus a place_set of ```[[],[]]``` would just be the set of all admin_level 0 places with nothing exploded. Likewise, ```[[1,6793,6712,6744,6878,7182,7190,7161,6903,6681,6986,6803],[]]``` would be the set of admin_level 0 places except for US,MX,CA,AU,BR,CL,AR,RU,CN,IN,ZA,NZ which would be replaced by (exploded) with their descendant admin_level 1 places

Here is some code which takes a taxon_id and a place_set and returns the set of atlas presences place_ids as determined by the listed_taxa:
```ruby
taxon_id = 36204 #western fence lizard

#place_set = [[],[]] # don't explode anything
place_set = [[1,6793,6712,6744,6878,7182,7190,7161,6903,6681,6986,6803],[]] #explode these countries: US,MX,CA,AU,BR,CL,AR,RU,CN,IN,ZA,NZ
#place_set = [[1,6793,6712,6744,6878,7182,7190,7161,6903,6681,6986,6803],[14]] #explode these countries: US,MX,CA,AU,BR,CL,AR,RU,CN,IN,ZA,NZ and this state CA

ancestry_string = "(places.ancestry = ? OR places.ancestry LIKE ? OR places.ancestry LIKE ?)"
explode_admin0 = place_set[0]
explode_admin0_ancestors = explode_admin0.map{|i| ["#{i}","%/#{i}","%/#{i}/%"]}.flatten
explode_admin1 = place_set[1]
explode_admin1 = explode_admin1.select{|i| Place.find(i).ancestry.split("/").map{|i| explode_admin0.include? i.to_i}.any?} #ignore any place_ids that are not descendants of elements of the explode_admin0 set
explode_admin1_ancestors = explode_admin1.map{|i| ["#{i}","%/#{i}","%/#{i}/%"]}.flatten
condition_string = "listed_taxa.taxon_id = #{taxon_id} AND places.check_list_id = listed_taxa.list_id AND (places.admin_level=0)"
condition_string = "listed_taxa.taxon_id = #{taxon_id} AND places.check_list_id = listed_taxa.list_id AND ((places.admin_level=0 AND places.id NOT IN (?)) OR (places.admin_level=1 AND ( #{[ancestry_string].cycle(explode_admin0.count).to_a.join(' OR ')} )))" if explode_admin0.count > 0
condition_string = "listed_taxa.taxon_id = #{taxon_id} AND places.check_list_id = listed_taxa.list_id AND ((places.admin_level=0 AND places.id NOT IN (?)) OR (places.admin_level=1 AND ( #{[ancestry_string].cycle(explode_admin0.count).to_a.join(' OR ')} ) AND places.id NOT IN (?)) OR (places.admin_level=2 AND ( #{[ancestry_string].cycle(explode_admin1.count).to_a.join(' OR ')} )))" if explode_admin1.count > 0
conditions = [
 condition_string,
 [explode_admin0.empty? ? nil : explode_admin0],
 explode_admin0_ancestors.empty? ? nil : explode_admin0_ancestors,
 [explode_admin1.empty? ? nil : explode_admin1],
 explode_admin1_ancestors.empty? ? nil : explode_admin1_ancestors
].flatten(1).compact
atlas_presence_place_ids = ListedTaxon.joins(:place).where(conditions).map{|a| a.place_id}

atlas_presence_place_ids
=> [52, 46, 22, 8501, 50, 40, 10, 14]
```
When listed_taxa are created/destroyed, check whether they belong to the place_set for an atlas for that species. For example, if I created a listed_taxa for western fence lizard in Arizona (place_id = 40), check whether an atlas exists for western fence lizard, and Arizona is a member of the atlas_places (places that comprise the atlas):
```ruby
place_set = [[1,6793,6712,6744,6878,7182,7190,7161,6903,6681,6986,6803],[]] #explode countries US,MX,CA,AU,BR,CL,AR,RU,CN,IN,ZA,NZ
ancestry_string = "(places.ancestry = ? OR places.ancestry LIKE ? OR places.ancestry LIKE ?)"
explode_admin0 = place_set[0]
explode_admin0_ancestors = explode_admin0.map{|i| ["#{i}","%/#{i}","%/#{i}/%"]}.flatten
explode_admin1 = place_set[1]
explode_admin1 = explode_admin1.select{|i| Place.find(i).ancestry.split("/").map{|i| explode_admin0.include? i.to_i}.any?} #ignore any place_ids that are not descendants of elements of the explode_admin0 set
explode_admin1_ancestors = explode_admin1.map{|i| ["#{i}","%/#{i}","%/#{i}/%"]}.flatten
condition_string = "(places.admin_level=0)"
condition_string = "(places.admin_level=0 AND places.id NOT IN (?)) OR (places.admin_level=1 AND ( #{[ancestry_string].cycle(explode_admin0.count).to_a.join(' OR ')} ))" if explode_admin0.count > 0
condition_string = "(places.admin_level=0 AND places.id NOT IN (?)) OR (places.admin_level=1 AND ( #{[ancestry_string].cycle(explode_admin0.count).to_a.join(' OR ')} ) AND places.id NOT IN (?)) OR (places.admin_level=2 AND ( #{[ancestry_string].cycle(explode_admin1.count).to_a.join(' OR ')} ))" if explode_admin1.count > 0
conditions = [
 condition_string,
 [explode_admin0.empty? ? nil : explode_admin0],
 explode_admin0_ancestors.empty? ? nil : explode_admin0_ancestors,
 [explode_admin1.empty? ? nil : explode_admin1],
 explode_admin1_ancestors.empty? ? nil : explode_admin1_ancestors
].flatten(1).compact
atlas_place_ids = Place.where(conditions).map{|a| a.id}
atlas_place_ids.include? 40

=> true #Arizona is a member of the atlas places for western fence lizard
```
If the listed_taxa that was created or destroyed was a member of the atlas places for that species, then log the change with an atlas_log:
```ruby
# new model
AtlasLog
  # atlas
  # place
  # created_destroyed (whether we're logging the creation/destruction of a listed_taxon or rather if nil...
  # exploded_collapsed (we're logging that someone exploded/collapsed an atlas place)
  # user
  # created_on
```
For example, ```#<AtlasLog atlas: xxx, place_id: 40, created_destroyed: created, exploded_collapsed: nil>``` would mean someone added Arizona to the atlas presences for atlas xxx

If an existing atlas.place_set is altered, we can also keep track of this in an atlas_log. For example, ```#<AtlasLog atlas: xxx, place_id: 14, created_destroyed: nil, exploded_collapsed: exploded>``` would mean someone altered atlas xxx by exploding the state of California down to counties

**Comment by kueda** [comment]
Assuming that an "exploded" place means a place that we ignore and instead use it's childen (with admin levels), e.g. not using Canada and instead using its provinces, here's an alternative implementation suggestion:

```ruby
# using https://github.com/collectiveidea/audited for tracking changes to the models

Atlas
  belongs_to :taxon
  has_many :atlas_places
  audited
  has_associated_audits # means you can see the change history for its atlas_places

AtlasPlace
  belongs_to :atlas
  # has boolean column :use_child_places
  audited associated_with: :atlas
```

If we need to keep track of which places are "exploded", I think that justifies a separate model instead of using ListedTaxon. AtlasPlaces could still be created based on the presence / absence of relevant listed taxa (or not), this just seems like a more Rails-ish way to model and store the required data. The `place_set` approach you described would work but feels a bit awkward to me, like we're trying to avoid the a clearer way of doing this to accommodate using ListedTaxon.

**Comment by loarie** [comment]
@pleary - thoughts on whether the set of places that make up the atlas ('atlas places') are better stored in summary form as a single record (e.g as I'm suggesting with the place_set = [[1,6793,6712,6744,6878,7182,7190,7161,6903,6681,6986,6803],[14]] notation) or as an association with a separate table with explicit records for each atlas place (as ken-ichi's suggesting)?

**Comment by pleary** [comment]
I think I'd prefer to have the separate model. That way it is more explicit without hidden semantics in the structure of the `place_set` string. Not sure what that would look like though - does it include every resulting post-explosion place or just a reference to the parent. If we could get away with the latter then it could be a fairly small table

**Comment by kueda** [comment]
I was thinking an `Atlas` would have an `AtlasPlace` for every place where the taxon occurs, with the assumption that it is always complete, but you could imagine something different and a little more like Scott's proposal:

```ruby
Atlas
  belongs_to :taxon
  has_many :exploded_atlas_places

  # totally untested, but I think this is somethign like Scott's example
  def places
    exploded_place_ids_to_include = []
    exploded_place_ids_to_exclude = []
    exploded_atlas_places.each do |place|
      exploded_place_ids_to_exclude << place.id
      exploded_place_ids_to_include += place.children.where( "admin_level IS NOT NULL" ).map(&:id)
    end
    Place.
      joins( listed_taxa: :list ).
      where( "lists.type = 'CheckList'").
      where( "lists.id = places.check_list_id" )
      where( "listed_taxa.taxon_id = ?", taxon ).
      # countries or the children of any exploded place
      where( "(admin_level = 0 OR places.id IN (?))", exploded_place_ids_to_include ).
      where( "places.id NOT IN (?)", exploded_place_ids_to_exclude )
  end

ExplodedAtlasPlace
  belongs_to :atlas
```

So that would be a small table and easier for me to read / understand in the future, but it would mean we'd need to dynamically compute the Atlas based on a query on listed_taxa (including an `OR` and a `NOT IN`) every time we needed to show it, so I'd be a bit concerned about performance.

**Comment by loarie** [comment]
I tested Ken-ichi's approach and it looks great. I made 2 minor modifications:
1. I changed ```admin_level IS NOT NULL``` to ```admin_level IN (0,1,2)``` so we're strictly talking about an atlas of Countries/States/Counties and excluding parks (admin_level = 10)
2. Ken-ichi's code doesn't work if ```exploded_atlas_places = []```. I'm not sure if this is a wise fix, but adding a dummy place id of ```0``` (ie ```exploded_place_ids_to_include = [0]``` and ```exploded_place_ids_to_exclude = [0]```) deals with this case. Here's the altered method:
```
def places
  exploded_place_ids_to_include = [0]
  exploded_place_ids_to_exclude = [0]
  exploded_atlas_places.each do |place|
    exploded_place_ids_to_exclude << place.id
    exploded_place_ids_to_include += place.children.where( "admin_level IN (0,1,2)" ).map(&:id)
  end
  places = Place.joins( listed_taxa: :list ).
    where( "lists.type = 'CheckList'").
    where( "lists.id = places.check_list_id" ).
    where( "listed_taxa.taxon_id = ?", taxon ).
    where( "(admin_level = 0 OR places.id IN (?))", exploded_place_ids_to_include ).
    where( "places.id NOT IN (?)", exploded_place_ids_to_exclude )
end
```

**Comment by loarie** [comment]
@pleary what are your performance thoughts on making a record for each atlas place (big table, but simple query) versus a record for each exploded atlas place (small table, more complex query) following on Ken-ichi's work above?

**Comment by pleary** [comment]
Do you have any estimates of numbers? There are 8.6 million listed taxa - will this table have about the same? I think to comment on performance I'll need to know a little more about it - like roughly what would be the size difference in storing exploded vs storing non exploded (i.e. how many places are exploded and how many "children" does an exploded place have").

But it seems to me though that you're ultimately searching listed_taxa on the same number of place_ids no matter how the data is stored in atlas_places. You're just getting those places from the table, or from another query or a join. But I'm also a little lost and would benefit from actually seeing the tables and the data that would be in them

**Comment by loarie** [comment]
If we assumes that most taxa would go with the default I proposed of exploding these countries to states [US,MX,CA,AU,BR,CL,AR,RU,CN,IN,ZA,NZ] that results in 253+12+323= 588 atlas-places per species

if we assume ~10,000 birds, mammals, amphibians, reptiles ~40,000 taxa we could easily imagine having atlases for, that means 40,000 * 588 = 23,520,000 records if we were to store each atlas-place explicitly

vs. 12 * 40,000 = 480,000 if we were to just store the exploded_atlas_places

so storing exploded_atlas_places would be about 480,000/23,520,000 = 2% of the records of storing atlas_places

But with the big table approach, fetching the atlas-places would be trivial and fetching the atlas-place-presences would involve:
```
atlas_place_presences = Place.joins( listed_taxa: :list ).
    where( "lists.type = 'CheckList'").
    where( "lists.id = places.check_list_id" ).
    where( "listed_taxa.taxon_id = ?", taxon ).
    where( "places.id IN (?)", atlas_place_ids )
```

With the small table approach, fetching atlas-places would involve:
```
exploded_place_ids_to_include = [0]
exploded_place_ids_to_exclude = [0]
exploded_atlas_places.each do |place|
  exploded_place_ids_to_exclude << place.id
  exploded_place_ids_to_include += place.children.where( "admin_level IN (0,1,2)" ).map(&:id)
end
atlas_places = Place.
  where( "(admin_level = 0 OR places.id IN (?))", exploded_place_ids_to_include ).
  where( "places.id NOT IN (?)", exploded_place_ids_to_exclude )
```
And fetching the atlas-place-presences would involve Ken-ichi's query above

**Comment by loarie** [comment]
@kueda with ```AtlasLog``` above I was trying to capture 2 things:
 (1) changes to atlas-places: e.g. when an atlas-place is created/destroyed (eg. someone explodes CA to its child counties)
 (2) changes to atlas-place-presences: e.g. when a default checklist listed-taxon is created or destroyed for a taxon with an atlas and when that listing belongs to an atlas-place

Sounds like we can use https://github.com/collectiveidea/audited for tracking changes to the atlas-places. But I don't think it would work for tracking atlas-place-presences. Tracking atlas-place-presence changes might be more trouble than its work, but it would be nice to know what would be involved on the cost side to compare with the benefits. Thoughts on how to do it?

**Comment by pleary** [comment]
My experience with updates, of which we had 10s of millions, was that it was best to move most querying into ES and keep the DB table more normalized, i.e. fewer rows. In my opinion, given the comparative scale of exploded vs non-exploded places, I'd try the approach where atlas places are not exploded - that we look up descendants on the fly. Or if things become unwieldy in the DB, we store a normalized version in ES like most other things. It'll also save space in the DB which is a good thing

**Comment by kueda** [comment]
Regarding the audited gem, we might be able to implement logging of when listed taxa are created or destroyed with a `last_presence_change_at` column that stores a timestamp of the last time a presence changed and require a comment that details what changed and how, e.g. `atlas.update_attributes!( last_presence_change_at: Time.now, audit_comment: "California (14) deleted")`. IMO that's getting a bit awkward though, so if we want to pursue the original model of assuming all country-level admin places are covered and only storing the exploded places, then I think your original `AtlasLog` model would be more appropriate. The audited gem is really focused on changes to models, which makes it hard to store changes to models that don't exist, or that exist but to serve different purposes like `ListedTaxon`.

Patrick, I can't quite tell, you're advocating for only explicitly storing exploded places, right? So it would be fewer rows in the DB and would either require the SQL queries Scott described above or a new ES index for default check-listed taxa?

**Comment by loarie** [comment]
My reading of patrick's comment (but correct me if I'm wrong @pleary) is that he is advocating for only explicitly storing exploded places as you say (e.g. smaller table but more complex SQL/ES index).

If we are going with storing exploded places only and you think that means the audited gem isn't appropriate, then I'm fine with a separate AtlasLog model.
