### ISSUE TITLE
Safari freezes when trying to search taxa in a user's observations

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1173]
This just happened to me twice where I got the spinning pinwheel of death and had to force quit. 
Mac 10.11.6
Version 9.1.3 (11601.7.8)

To replicate: 
Go to a user's observations (e.g. http://www.inaturalist.org/observations/parkecology)
Start typing in the taxon box
Dropdown gets stuck, get pinwheel that doesn't go away.
Force quit

**Comment by carrieseltzer** [comment]
I think it just happened again when I tried to search for a user name (parkecology) in the observations search filters (http://www.inaturalist.org/observations). It may be related to autocorrect in Safari. It corrected parkecology to be two words, and that's when it got stuck. It similarly likes to correct dicots to something else. If you can't repeat the error above, try searching for dicots or something else that gets autocorrected.

**Comment by cyberhobo** [comment]
I took a shot at reproducing this in OSX 10.11.6 Safari Version 10.0 (11602.1.50.0.10) and wasn't able to. I did get the two word correction, but no freeze.
<img width="322" alt="screenshot 2016-10-11 17 44 21" src="https://cloud.githubusercontent.com/assets/286838/19289861/bde8bfa6-8fda-11e6-861d-4d947b0833e7.png">

**Comment by carrieseltzer** [comment]
Alright, my computer seems to have fixed itself on this one. I can't replicate it now either. But before I shut down my computer last night, it froze one more time while adding an ID in an observation. It had something to do with the ID dropdown. Will reopen if it happens again.
