### ISSUE TITLE
Unnecessary field icons in Add Obs

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1175]
Can we remove the icons located next to the below next to the fields as they are redundant? They're also inconsistent with the Tags UI.

![image](https://cloud.githubusercontent.com/assets/11527994/19279104/b7109bb8-8f94-11e6-8064-126a624aa2ab.png)

![image](https://cloud.githubusercontent.com/assets/11527994/19279268/92c879dc-8f95-11e6-8768-34e9e913700e.png)

**Comment by kueda** [comment]
I think I agree, but I feel like @pleary had an opinion about this. Was it just alignment issues, Patrick, or was there something more functional?

**Comment by joellebel** [comment]
looks great. tnx.
