### ISSUE TITLE
Add API endpoint for all observations not in an array of place_ids

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1177]
I want a way to look for any observations outside of a taxa's atlas place presences (#1154) since these would either be cool discoveries or data quality issues that should be fixed.

Can we add an API endpoint to obs/search that returns all observations not in an array of place_ids (the atlas presence places in this use case)?

e.g. if the atlas presence places included everything here except Minnesota, I could use them and this proposed API endpoint to fetch the observation of <a href="http://www.inaturalist.org/taxa/73669-Aspidoscelis-gularis">Aspidoscelis gularis</a>  in Minnesota
<img width="353" alt="screen shot 2016-10-14 at 11 36 37 am" src="https://cloud.githubusercontent.com/assets/598026/19398659/88e75e5a-9202-11e6-8565-90dba0850b87.png">

**Comment by pleary** [comment]
How's this http://www.inaturalist.org/observations?not_in_place=1,6712,6793 ?

**Comment by loarie** [comment]
perfect!
