### ISSUE TITLE
DarwinCore Archive SimpleMultimedia extension should always include an identifier

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1179]
The `identifier` field is supposed to be a URL to the original media, but some of our photos don't have an `original_url` set. So

1) Let's _only_ include photos that have some kind of legit URL and not broken flickr photos etc
2) Let's use the _best_ URL for the identifier field, i.e. `original_url || large_url || medium_url`

**Comment by kueda** [comment]
@jlegind, if we change all the values for `identifier` in the SimpleMultimedia file of our DwC-A, will that cause problems for you guys at GBIF? We have been using the URL of the photo from its original provider. It's a little problematic b/c in rare cases we don't have permission to access that so it's blank, and less rare cases, that URL has broken b/c the provider has changed it. We've dealt with the latter case by keeping our own copy of every photo (defaulting to a smaller size if we don't have the original), so we can now change the `identifier` we provide for each photo in our DwC-A to something that is both unique and stable, but I want to make sure doing so doesn't complete mess up iNat images on GBIF.

**Comment by kueda** [comment]
@jlegind, do you have an opinion on this? I'd like to make sure we don't screw things up for GBIF by making this change.

**Comment by jlegind** [comment]
Hi Ken-Ichi, changing the identifiers in the multimedia file should not be an issue as long as the identifiers in the core file match the new key.
