### ISSUE TITLE
Project Lists should not create listings from observations

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1190]
currently project lists create listings from observations (like default place checklists and user life lists)

However this is breaking use-cases that use the project list as a manually curated reference, e.g.  the must-be-on-list rule as follows:
1. user adds an observation to a project with a must-be-on-list rule of something on the list
2. community changes the ID to something not on the list
3. listing is added to the list for that species based on that obs
4. now the curated project list has something on it that wasn't indented and observations of that are aggregated into the project

Proposal is to make it so that Project Lists do not create listings from observation (like non-default place checklists)

This might bother some people who use project lists to track the species represented by observations in their project, but they can (1) use obs/search for that or (2) manually update their project list as needed with taxa sourced to observations

The only complaints I've personally gotten about project lists relate to the must-be-on-list use-case, so I suspect that if we make this change the benefit experienced by those users will outweigh the cost to anyone still using project lists to track the species represented by project obs

**Comment by loarie** [comment]
@kueda do you want to take a crack at this or do you want me to look into it?

**Comment by kueda** [comment]
Go for it if you have the time. Otherwise I'll try and get to it when I finish / get sick of the taxon page.

**Comment by loarie** [comment]
I'll try to take a crack assuming that Gem updating issue you experienced doesn't cause an even worse delay on my end
