### ISSUE TITLE
uploader overwrites taxon after image upload

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1194]
To replicate,

1. Drag in a photo to the uploader
1. While the image is uploading, change the taxon
1. Let the image upload finish. If the image had a keyword that resolved to a taxon, that will overwrite the taxon you chose in 2. If it had no taxon, there will be no visible change but submitting the observation will result in *just* the species guess being submitted, leading to unexpected results

See https://groups.google.com/d/topic/inaturalist/AGSVDFkKhXk/discussion

**Comment by tnywlls** [comment]
Great work in identifying that sequence :-)
The variability of upload time versus completing typing in a taxon would explain a lot about the repeatability of running into this - ie much more likely to strike with larger uploads.

If the same occurs with entering the description field it would explain why it is often apparently difficult to remove the default "OLYMPUS" description that is obtained from the metadata.  Eg I add a bunch of files, select and combine them, then enter the taxon and description (usually just deleting the default description) while the files are uploading.  Only to find that that default description sometimes reappears in the resulting observation.

**Comment by pleary** [comment]
I deployed some code that I think fixes this. The uploader now won't let file metadata overwrite existing values (taxon_id was the only field affected). It will also keep track of what fields have been changed, so in the case where a description is added automatically via EXIF tags, then is deleted by the user, the metadata from the server response doesn't then set the description again.
