### ISSUE TITLE
IDs of inactive taxon shouldn't be included in Community ID

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1195]
As discussed here: https://groups.google.com/forum/#!topic/inaturalist/yV3fdkKamAY

The community is frustrated that after a taxonomic split it can take a very long time for an Obs Community ID to migrate to the new taxon, because of the >2/3 ID rule needed required for a CID

Proposal is to make it so that the IDs of inactive taxa are ignored in CID calculations

thoughts @kueda?

**Comment by kueda** [comment]
Still interested in this, since we're mucking with the CID at the moment?

**Comment by loarie** [comment]
Yes pls
