### ISSUE TITLE
obs search map zooms into 0,0 after clearing place from grid view

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1198]
1. Go to http://www.inaturalist.org/observations?place_id=14&subview=grid&taxon_id=62803
1. Click the "x" next to "California" in the upper right to clear the place filter
1. Switch to map view
1. The map is zoomed way into 0,0

I think the ideal behavior here would be to zoom into the extent of the currently mapped observations, but failing that I think it should zoom out so most of the world is in view.

**Comment by pleary** [comment]
Fixed
