### ISSUE TITLE
Naturalista Colombia: people page doesn't work

### ISSUE THREAD

**Issue by adrisoacha** [inaturalist/inaturalist#1200]
http://naturalista.biodiversidad.co/people

![image](https://cloud.githubusercontent.com/assets/16558682/20564377/0293cabe-b15b-11e6-9993-e5273dd4c9e2.png)

**Comment by pleary** [comment]
This is working for me. Could you try again? Do other pages work? Does it happen every time, or just some times?

If it's still happening, could you try running `nslookup naturalista.biodiversidad.co` in a console somewhere and let me know what IP address it resolves to.

**Comment by pleary** [comment]
There might be a slow query slowing down the people page. I'd still be interested to know if other pages show the same problem, or if this is isolated to the people page

**Comment by adrisoacha** [comment]
Still not working, apparently is isolated to the people page.

**Comment by pleary** [comment]
One of the queries on the people page for this site was being run very inefficiently by Postgresql. I made a small change which helps, but the page is still very slow to load. I don't think it will fail anymore, so if you see "Service Unavailable" again please let me know

**Comment by adrisoacha** [comment]
Thank you! It have been working well.
