### ISSUE TITLE
Moving between Observations and Identify interfaces with filters

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1210]
Sometimes I want to browse cultivated plant observations and then switch to the Identifications interface, but it's a little complicated by assumptions and interface. 

If I start here with 221 observations of cultivated Passiflora:
http://www.inaturalist.org/observations?captive=true&place_id=any&subview=grid&taxon_id=51452&verifiable=any

And open up the filter box to click "Identify", it brings me here (shows no observations, because the needs id filter is in conflict with "captive"):
http://www.inaturalist.org/observations/identify?verifiable=any&captive=true&place_id=any&taxon_id=51452

But what I want to see is:
http://www.inaturalist.org/observations/identify?verifiable=any&quality_grade=any&captive=true&place_id=any&taxon_id=51452

As I dig into this, I'm realizing that there are assumptions being made by the Identify page that can't be seen in the URL (i.e. it assumes quality_grade=needs_id and reviewed=false), so maybe this is more complicated than I thought. But finishing my thought, I have 2 ideas for improving this.

Suggestion 1:  (easiest?)
Simply keep filters set on observation page (i.e. don't add "needs id") when clicking "identify", perhaps notifying people how to exclude the observations they have already reviewed.

Suggestion 2: (what I'd prefer)
Make a few more interface changes to improve the experience of switching between the Observations and Identify interfaces:
a. Add a button somewhere on the Observations interface that makes it easier to see how you can switch to the Identify interface. It could even still be within the filters, but it could be bigger, and maybe even have a kind of tutorial bubble the first time someone clicks in there that points out what it's for. 
b. Make the filter box/options exactly the same for Observations and Identify. Right now "captive" isn't an option in the Identify filters (I manually add it in the URL since I know it works for Observations).

**Comment by kueda** [comment]
Not that into 2a, but 2b seems ok. The original intent was to have the same filters, but I probably forgot some. Identify and Search use totally different platforms so we couldn't just use the same code from Search when we made Identify.

**Comment by carrieseltzer** [comment]
Somewhere along the way, a change was made that preserves the captive selection from Explore to Identify.
