### ISSUE TITLE
Complete Sets

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1217]
A set of listed taxa is more useful if it can be interpreted as a complete set (e.g. ALL amphibians in Sonoma County as opposed to SOME). Currently, complete sets are indicated on iNat by adding a separate place checklist flagged as 'comprehensive'. This system isn't ideal because:
1. If I make a comprehensive list for Apiaceae of California but there are other listed-taxa for California Apiaceae on other lists, these will display in the identotron. To remedy this I'd have to delete listings on lists owned by other people which is usually not permitted.
2. The system allows multiple listings for the same taxon/place which is complicating curation of listings (e.g. if I delete a 'bad listing' from the default checklist it might still display on the place page/identotron because there are other listings for that place/taxon) and the display of listings (various listings might have different establishment means - which one do we show?). Primary-listings were built to solve the latter issue but its broken at the moment.
3. The philosophy behind comprehensive lists is that there's a static external source for a comprehensive list and a single owner of that list. In my experience this isn't ideal because taxonomy issues etc. mean that the external list usually requires curation, and sometimes the list owner isn't responsive which can create problems (e.g. if there's a comprehensive list for Apiaceae of California that is 'wrong' it prevents me from making listings in that taxon/place not in that list). I'm interested in exploring a more community-curated notion of completeness where numerous people work together to curate the set of listings that can be interpreted as a complete set via discussion around creating/destroying listings.

This proposal is for a different approach which, similar to 'atlases' #1154, uses an additional piece of information (in this case a 'complete set' for a taxon/place) to (1) make the existing set of relevant default-checklist listings interpretable as comprehensive and (2) track changes to this set via a log of Alterations.

``` ruby
# new model
CompleteSet
  # taxon
  # place
  # description
  # source
```
<img width="377" alt="screen shot 2016-12-06 at 4 57 57 pm" src="https://cloud.githubusercontent.com/assets/598026/20950565/5400d20a-bbd5-11e6-8fef-c7adc738c70f.png">

The complete_set show view would display the set of relevant listed-taxa from the default-checklist, the alteration log, comments, and any warnings (e.g. there is already a complete set for a parent of this taxon) 
<img width="958" alt="screen shot 2016-12-06 at 4 58 20 pm" src="https://cloud.githubusercontent.com/assets/598026/20950566/55507dfe-bbd5-11e6-8460-e2b918277fac.png">

## modifying Alterations
Currently, when listed_taxa are created/destroyed for taxa that have atlases, it is logged in an AtlasAlteration:
```AtlasAlteration(id: integer, atlas_id: integer, user_id: integer, place_id: integer, action: string, created_at: datetime, updated_at: datetime)```
AtlasAlterations are also used to log the creation/destruction of ExplodedAtlasPlaces

Since its a bit weird mixing logs for creating/destroying listings with logs for exploding/collapsing atlas places in the same table, and since CompleteSets require the same sort of logging for creating/destroying listings, I propose reserving AtlasAlterations for logging exploding/collapsing atlas places and creating a new table:
```ListingAlteration(id: integer, taxon_id: integer, user_id: integer, place_id: integer, action: string, created_at: datetime, updated_at: datetime)```
which will be used for logging creating/destroying listings regardless if its because they are tracked via atlases or complete_sets

I'll split these ideas off as a separate issue, but once complete-sets are built, I propose to modify places/show, the identotron, and default checklist/show as follows:
## Subsequent modifications to places/show
1. By default show api.inaturalist.org/v1/observations/species_counts in the species guide section rather than listings
2. Include all complete-set taxa for the place in the tree-nav on the left and decorate with links to the complete-set
<img width="978" alt="screen shot 2016-12-06 at 4 58 37 pm" src="https://cloud.githubusercontent.com/assets/598026/20950570/57f8c64c-bbd5-11e6-8e9e-2bfe714e67dc.png">

3. If someone filters by a taxon with a complete-set (or a descendant of a taxon with a complete set), then show the listings from the default-checklist on the species guide
<img width="981" alt="screen shot 2016-12-06 at 4 58 46 pm" src="https://cloud.githubusercontent.com/assets/598026/20950576/6140bcaa-bbd5-11e6-9dc2-a3526b54258f.png">

## Subsequent modifications to identotron
these would be in a similar spirit to places/show, e.g.
1. if no taxon is chosen or the taxon is not of/descendant of a taxon with a complete_set for a place show api.inaturalist.org/v1/observations/species_counts.
2. If the taxon chosen is a of/descendant of a taxon with a complete_set for the selected place show the set of listings from the default-checklist and indicate that its a complete set of listings

## Subsequent modifications to default checklist/show
currently the default checklist shows a unique set of all listings from the place (not just the set of listings from the list) this makes it difficult for the community to curate whats on/off a default checklist as described above. I propose to only show listings from the default checklist, and give anyone permissions to create/destroy these listings (they will be logged with ListingAlterations if there is a relevant atlas or complete set). Non-default checklists for a place will still be there and can be referenced but won't get mixed in with the default checklist. If non-default checklists exist to indicate completeness (comprehensive lists) owners would be encouraged to rather create complete-sets and curate the set of listings on the default checklist.

**Comment by kueda** [comment]
If it's still tied to listed taxa, don't you have the same problem of being unable to *remove* taxa from a CompleteSet? What if I added Marbled Salamander to the Marin County default check list, and you make a CompleteSet for the amphibians of Marin County? You'd want to remove Marbled Salamander but you can't because it's on my list. You could only do that as a site curator, so are you proposing this system is only for site curators?

Also, as you anticipated, I don't see a bright future in moving from external authority to internal debate. What if you're a site curator and I'm a site curator and I say Marbled Salamander doesn't exist in Marin County, or worse, I insist that there are 17 subspecies of B. attenuatus in Marin County and we end up just arguing about it endlessly. If you don't have a technical mechanism for resolving conflicts like these, what is your policy solution?

**Comment by loarie** [comment]
> What if I added Marbled Salamander to the Marin County default check list, and you make a CompleteSet for the amphibians of Marin County? You'd want to remove Marbled Salamander but you can't because it's on my list.

You mean I can't because its your listed_taxa right? It would be on the default list for a standard place so it wouldn't be your list

> You could only do that as a site curator, so are you proposing this system is only for site curators?

Sounds good to start. People who curate atlases and complete sets should be able to destroy listings. 

> or worse, I insist that there are 17 subspecies of B. attenuatus in Marin County and we end up just arguing about it endlessly.

Both Atlases and Choice sets depend on clear taxonomic authorities to work. I think the solution would be to only allow atlases/choice sets for clades/places where we have clear taxonomic authorities like Clements or Pelham. But this means we can start with my pilot set of US amphibs/reptiles/mammals/birds/butterflies/odonata which all have clear taxonomic authorities.

> What if you're a site curator and I'm a site curator and I say Marbled Salamander doesn't exist in Marin County, 

I may be more optimistic than you, but I think there's enough ways to channel disagreements into proactive collaborative work. For example, if you deleted my listing of Marbled Salamander, I could see that you did so logged on the Marin County Amphibian complete set. And I felt strongly about it, I would mention you in a comment on the choice set asking you why you did it. I might also add it back with an external reference to back up my claim. Or better yet try to produce an observation. I think the philosophy of 'if there's no range map or GBIF records or other published record of this thing in this place, best to be conservative and assume it doesn't live there.' is pretty non-controversial.
