### ISSUE TITLE
Clicking zoom on photo in Upload screen freezes page

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1218]
Was able to reproduce this on Chrome, Firefox and Safari on my Mac.

https://groups.google.com/forum/#!topic/inaturalist/H7IS8ZXB6mY

**Comment by tiwane** [comment]
Another user says it happened to her when she clicked on the taxon in the card, not the photo. Using Firefox version 50.

https://groups.google.com/forum/#!topic/inaturalist/Ze3FQTUTo5E

**Comment by pleary** [comment]
I think this is fixed now. Could you test it on your end @tiwane ?
