### ISSUE TITLE
Can Atlases act as umbrellas for descendant taxa/places?

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1221]
Imagine I had an atlas for taxon C that included atlas places at the US State level (e.g. US was exploded). Currently, unless there were a listing for taxon C in Utah, the atlas would consider taxon C absent from Utah - even if there were listings for descendant taxon A in a Utah County (or listings for taxon C in a Utah County, or listings for taxon A in Utah etc.).
<img width="943" alt="screen shot 2016-12-07 at 11 21 08 am" src="https://cloud.githubusercontent.com/assets/598026/20985331/e85e52e4-bc78-11e6-9209-64f6280cb1ea.png">
While this might be the best way to do this, it would be potentially more powerful if atlases could act as umbrellas for descendant taxa/places. Specifically:
1. The atlas map would visualize listings of descendant taxa/places bubbled up to the level of the atlased taxon and the atlas places (e.g. show Utah present for taxon C based on listings of taxon A in a Utah county).
2. If someone listed a descendant taxa in a descendant atlas place, the umbrella atlas would log it
3. If I destroyed a listing for an atlas place (e.g. asserted that taxon C is absent from Utah) all listings of descendant places/taxa would also be destroyed.

The downside of this approach is that the queries become much more complex. For example, consider adjusting the presence_places method:
https://github.com/inaturalist/inaturalist/blob/master/app/models/atlas.rb#L20
```
def presence_places
  exploded_place_ids_to_include, exploded_place_ids_to_exclude = get_exploded_place_ids_to_include_and_exclude
  places = Place.joins( listed_taxa: :list ).
    where( "lists.type = 'CheckList'").
    where( "lists.id = places.check_list_id" ).
    where( "listed_taxa.taxon_id = ?", taxon )
  places = if exploded_place_ids_to_include.blank?
    places.where( admin_level: 0 )
  else
    places.where( "(admin_level = 0 OR places.id IN (?))", exploded_place_ids_to_include )
  end
  unless exploded_place_ids_to_exclude.blank?
    places = places.where( "places.id NOT IN (?)", exploded_place_ids_to_exclude )
  end
  places
end
```
To have it consider listings of descendant taxa we could condition on taxa ancestors like so. But this slows things down significantly. Also - are we still supporting listed_taxa.taxon_ancestor_ids or should this be done with a join through to taxa?
```
class Atlas < ActiveRecord::Base
  def presence_places_considering_descendant_taxa
    exploded_place_ids_to_include, exploded_place_ids_to_exclude = get_exploded_place_ids_to_include_and_exclude
    places = Place.joins( listed_taxa: :list ).
      where( "lists.type = 'CheckList'").
      where( "lists.id = places.check_list_id" ).
      where( "listed_taxa.taxon_id = ? OR listed_taxa.taxon_ancestor_ids LIKE (?) OR listed_taxa.taxon_ancestor_ids LIKE (?)", taxon, "%/#{taxon.id}", "%/#{taxon.id}/%" )
    places = if exploded_place_ids_to_include.blank?
      places.where( admin_level: 0 )
    else
      places.where( "(admin_level = 0 OR places.id IN (?))", exploded_place_ids_to_include )
    end
    unless exploded_place_ids_to_exclude.blank?
      places = places.where( "places.id NOT IN (?)", exploded_place_ids_to_exclude )
    end
    places.distinct
  end
end
```
Considering not just descendant taxa but also descendant places makes things even more complex. The following works but is impossibly slow: 
```
class Atlas < ActiveRecord::Base  
  def get_continent_place_ids
    Place.where(admin_level: 0).map{|p| p.ancestry}.compact.map{|ancestry| ancestry.split("/")}.flatten.uniq
  end
  
  def presence_places_considering_descendant_taxa_and_places
    continent_place_ids = get_continent_place_ids
    exploded_place_ids_to_include, exploded_place_ids_to_exclude = get_exploded_place_ids_to_include_and_exclude
    places = Place.joins( listed_taxa: :list ).
      where( "lists.type = 'CheckList'").
      where( "lists.id = places.check_list_id" ).
      where( "listed_taxa.taxon_id = ? OR listed_taxa.taxon_ancestor_ids LIKE (?) OR listed_taxa.taxon_ancestor_ids LIKE (?)", taxon, "%/#{taxon.id}", "%/#{taxon.id}/%" ).
      where( "admin_level IN (?)", [0,1,2] ) #get all the atlas places with listings regardless of country/state/county
    place_ids = places. #find the set of places excluding exploded places and bubbling up descendant places to the encompassing atlas place
      map{|p| 
        (p.ancestry.nil? ? [p.id.to_s] : [p.ancestry.split("/"),p.id.to_s].flatten). #get an array of place ancestor ids and place_id
          select{|pid| (!exploded_place_ids_to_exclude.include? pid.to_i) && (!continent_place_ids.include? pid)}[0] #excluding any exploded places or continent ancestors
      }.uniq.compact.map{|a| a.to_i}                                                                                 #grab the most ancestral place
    places = Place.where(id: place_ids) #this is the set of atlas places with listings on the place (or descendant places)
  end
end
```

@pleary @kueda can you see a way of making the above query performative or should I abandon this idea of atlases communicating with descendant places/taxa?

**Comment by pleary** [comment]
How far up the tree do you want to go? Trying to get a sense for the maximum number of descendants you might needs to query at one time. Do you want to go all the way up to Kingdom?

**Comment by pleary** [comment]
I took a crack at this, and have something that might be working OK. I've made at least one assumption though, which we should talk about.

Assuming the `List` model has an association `has_one :check_list_place, class_name: "Place", foreign_key: :check_list_id`, then to look at descendant taxa but not places could be:

``` ruby
  def presence_places_considering_descendant_taxa
    exploded_place_ids_to_include, exploded_place_ids_to_exclude = get_exploded_place_ids_to_include_and_exclude
    scope = ListedTaxon.joins( { list: :check_list_place } ).
      where( "lists.type = 'CheckList'").
      where( "listed_taxa.taxon_id IN (?)", taxon.taxon_ancestors_as_ancestor.pluck(:taxon_id) )
    if exploded_place_ids_to_include.blank?
      scope = scope.where( "places.admin_level = 0" )
    else
      scope = scope.where( "(places.admin_level = 0 OR places.id IN (?))", exploded_place_ids_to_include )
    end
    unless exploded_place_ids_to_exclude.blank?
      scope = scope.where( "places.id NOT IN (?)", exploded_place_ids_to_exclude )
    end
    Place.where(id: scope.select("listed_taxa.place_id").distinct.pluck(:place_id))
  end
```

And to look at descendant taxa, and get the proper atlas places looking at place ancestors, could be something like:

``` ruby
  def presence_places_considering_descendant_taxa_and_places
    exploded_place_ids_to_include, exploded_place_ids_to_exclude = get_exploded_place_ids_to_include_and_exclude
    scope = ListedTaxon.joins( { list: :check_list_place } ).
      where( "lists.type = 'CheckList'").
      where( "listed_taxa.taxon_id IN (?)", taxon.taxon_ancestors_as_ancestor.pluck(:taxon_id) )

    descendants_places = Place.where(id: scope.select("listed_taxa.place_id").distinct.pluck(:place_id))
    place_ancestors = descendants_places.map(&:ancestor_place_ids).flatten.compact.uniq

    scope = Place.where(id: place_ancestors)
    if exploded_place_ids_to_include.blank?
      scope = scope.where( "places.admin_level = 0" )
    else
      scope = scope.where( "(places.admin_level = 0 OR places.id IN (?))", exploded_place_ids_to_include )
    end
    unless exploded_place_ids_to_exclude.blank?
      scope = scope.where( "places.id NOT IN (?)", exploded_place_ids_to_exclude )
    end
    scope
  end
```

**Comment by loarie** [comment]
that works great Patrick and seems pretty fast. If you think this is performative, than I propose we do have Atlases work as 'umbrellas' like this. Theres a few things that would have to change with Altases to make them work this way (e.g. logging creation/destruction of listed_taxa for descendant taxa or places).  In terms of the Atlas UI - the implication would be if you 'removed' an atlas_presence_place by clicking the map it would destroy all listed_taxa for that place (+ desc places) and taxon (+ desc taxa). (which can be destructive but I think necessary to curate these listings) - the implication would be if you 'created' an atlas_presence_place by clicking on an atlas_place would be unchanged (e.g. it would create a listing for that place/taxon - sound reasonable?
