### ISSUE TITLE
Using atlases to make taxon_splits less destructive

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1233]
Taxon Splits are necessary to keep pace with taxonomy changes, but they can be very destructive because the community has to manually reID every observations formerly belonging to the split taxon. 

For example, here's a split I'm dreading to make because it will affect 192 observations:
http://www.inaturalist.org/taxon_changes/18657
<img width="970" alt="screen shot 2016-12-21 at 5 35 08 pm" src="https://cloud.githubusercontent.com/assets/598026/21412276/f5531634-c7a3-11e6-8ae9-36494e473f5e.png">

The recent Western Scrub Jay split and Black Tailed Rattlesnake split were examples of the burden these splits placed on the iNat community

I propose that we modify taxon_changes so that if to-be-split taxon is Atlased then observations from atlas_presence_places that belong unambiguously to one of the resulting-from-split taxa are automatically moved (as with swaps). Only the observations within atlas_presence_places that will be duplicated across resulting-from-split taxa will have to be manually re-identified (as with splits currently).

In this example, observations from Iowa and Missouri would have to be manually reclassified.
<img width="694" alt="screen shot 2016-12-21 at 5 36 56 pm" src="https://cloud.githubusercontent.com/assets/598026/21412319/3e189dee-c7a4-11e6-8428-2d93af8c76c9.png">

This would be easiest to do if we could assume the resulting-from-split taxa don't already have atlases. That shouldn't be the case but would screw things up if it happened. Maybe make it clear that any existing atlases associated with the resulting-from-split taxa will be written over

Then adding a UI to the taxon map that allows people to toggle atlas-presence-places as being 'shared' or belonging to just one of the resulting-from-split taxa could inform the taxon-split how to move observations.

**Comment by loarie** [comment]
@pleary and @kueda thoughts on the above?

**Comment by kueda** [comment]
I think I may have been working on what I thought this issues described vs what it actually describes. I don't think I entirely understand this bit:

> I propose that we modify taxon_changes so that if to-be-split taxon is Atlased then observations from atlas_presence_places that belong unambiguously to one of the resulting-from-split taxa are automatically moved (as with swaps). Only the observations within atlas_presence_places that will be duplicated across resulting-from-split taxa will have to be manually re-identified (as with splits currently).

There's nothing called an "atlas presence place" in our database, so I assume you're referring to the ListedTaxon records associated with the  input taxon, yes? At present those don't get moved when committing a TaxonSplit, and unless the output taxa were atlased, I don't know how we could unambiguously assign those listed taxa two any of the output taxa.

Here's a slightly different proposal in line with what I was originally assuming: continue to do nothing for splits *unless* all of the output taxa have been atlased. If they have, then anything in a place within only one of the atlases associated with the output taxa can be treated as if it was a taxon swap. Anything that is outside of any of the atlased places or inside a place that is in multiple output atlases gets left alone and must be manually curated. With this technique we could update anything with coordinates or an associated place.

**Comment by loarie** [comment]
that could work - but it could get complex if the output taxa have atlases at different scales (e.g. output 1 has atlas-presence-place CA but output 2 has atlas-presence-place Sonoma) it would have to be smart enough to know that Sonoma is a child of CA and therefore CA is a place with 2 of the atlases associated with it.

But this would work if you think its easier than the approach I laid out though.

I guess my approach would involve making an atlas-presence-place association with a taxon split that had some sort of structure like [{atlas_presence_place: 14, destination: 1},{atlas_presence_place: 18, destination: 2},{atlas_presence_place: 12, destination: nil}] which means move all obs in 14 to output 1, obs in 18 to taxon 2 and leave obs in 12 alone

**Comment by kueda** [comment]
I hadn't thought of the different scales issue, but I think my current approach will handle it. I'll add tests for that case, though, thanks. I don't love the idea of embedding a place-based mapping in the TaxonSplit itself b/c that essentially duplicates the effort put into an atlas, and will probably encourage people to only add mappings that are relevant to the data they can see, e.g. they'll probably only make mappings for the places where there are observations, which will migrate the data, but give less information about what the overall split is intended to describe.

**Comment by loarie** [comment]
if you can handle the different scale issue - your approach sounds great
