### ISSUE TITLE
add identifications of the nearest, common, active ancestor in response to taxon splits

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1235]
Currently, a taxon split results in observations with identifications related to inactive taxa, because we can't automatically migrate identifications to one of the active, output taxa of the split. Many (most?) people are not very responsive about updating their identifications after a split, which leaves many observations where the majority of identifications are of inactive taxa, which currently count as votes toward the community ID, and thus, engaged people who add new identifications for the active taxa have trouble updating the community ID because their IDs count as contradictions.

Several solutions were proposed at https://groups.google.com/forum/#!msg/inaturalist/yV3fdkKamAY/eOzlOeL5AQAJ, but here's the one I think we should go with (as proposed by Jakob, I think): for each identification of an inactive input taxon, add an identification of its nearest active ancestor. So if _Homo sapiens_ is split into _Homo neosapiens_ and _Homo radichiosapiens_, every identification of _H. sapiens_ should be made not current and new identifications of _Homo_ should be added. Presumably all the people who added IDs of _H. sapiens_ agree the observation depicts something that is also in _Homo_, and we can't know their intentions on a more specific taxonomic level until they state them in the form of new identifications. This also makes it so new identifications do not contradict the IDs of inactive taxa.

Another example: if _H. sapiens_ is split into _H. neosapiens_ and _Protohomo homoensis_, IDs of _H. sapiens_ would be replaced with IDs of Homonidae, since that contains all the input and output taxa of the split.

**Comment by loarie** [comment]
complements #1209 towards making taxon_splits less destructive/burdensome for the IDer community
