### ISSUE TITLE
Combining/importing lists

### ISSUE THREAD

**Issue by RobBuckBirder1003** [inaturalist/inaturalist#1238]
I have made a species life list but have not actually submitted any observations. How can I convert some of my species from my overall life list to more specific lists? Like, birds on one list, mollusks on another, amphibians on another and so on.

Thanks,

Robert Buckert

**Comment by kueda** [comment]
Hi Robert, this isn't functionality we currently support. However, you could download your life list as CSV, sort out the groups you want to make into their own lists, make new lists on the website, and add the taxa by pasting in values from the CSV (or by uploading new CSV files).
