### ISSUE TITLE
Service unavailable triggering on new taxon ranges when kmls ~4MB

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1246]
This happens when a KML ~>= 4km is uploaded via http://www.inaturalist.org/taxon_ranges/new
for example https://dl.dropboxusercontent.com/u/1288081/le_ol.kml

**Comment by kueda** [comment]
What's the taxon in question?

**Comment by loarie** [comment]
the above kml is of http://www.inaturalist.org/taxa/39670-Lepidochelys-olivacea - but it happens whenever the KML is large, irrelevant to the taxon_id associated with the new taxon_range

**Comment by pleary** [comment]
The symptom was a long-running Passenger process, running for 30+ minutes and spiking CPU. It is possible that was "normal", but the process should minimally be put into a delayed job so we don't get a Passenger queue backup and show the heavy load message

**Comment by kueda** [comment]
Ok. Just for peace of mind, can you post a KML of a taxon that *doesn't* have a massive, date-line spanning range?

**Comment by loarie** [comment]
sure, I can post a large shapefile with a more contained area, but I won't be able to guarantee that it causes the service_unavialable error in production since I don't think Patrick wants me trying that again in production

**Comment by loarie** [comment]
okay this one is only 3.4 MB, but its fairly complex short of spanning the date line https://dl.dropboxusercontent.com/u/1288081/coyote.kml - will that work?
