### ISSUE TITLE
Apply PPSR_CORE metadata standard to projects

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1249]
It would be nice to get iNaturalist project metadata in this standard format eventually. Filing it here so I don't have to worry about forgetting that this exists.

Fields defined here:
http://citizenscience.org/2015/10/09/ppsr_core-metadata-standard/

**Comment by loarie** [comment]
is this a software ticket carrie? or a best practices discussion more suitable for the google group?

**Comment by carrieseltzer** [comment]
I suppose it could be up for discussion about how interested other people are in this, but my intention was primarily to bookmark it as something for incorporation into a larger projects overhaul (if funding materializes for that). I didn't intend for it to be high priority but more of a back-burner feature improvement.

**Comment by loarie** [comment]
might be better to put in in a google doc and float it by the google group. We're trying (and I'm guilty of not doing this) to restrict github issues to well fleshed out software tickets that are ready to be implemented, or at least have technical details discussed. This seems like its still in the functional spec phase
