### ISSUE TITLE
Refining Dashboard New User Text

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1252]
## Current

![image](https://cloud.githubusercontent.com/assets/11527994/21781340/cb8c0904-d663-11e6-844c-f43c57f7fa47.png)

## Proposed

Just thought I'd trim this down a bit to the following...

"iNaturalist is all about sharing and discussing observations of living things. Below are discussions happening right now. (Note: You are automatically subscribed to any discussions you contribute comments or identifications to. Manage these updates in the "Subscriptions" section to the right.)"

Feel free to correct my grammar.

**Comment by loarie** [comment]
done
