### ISSUE TITLE
use nocaptcha

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1259]
https://www.google.com/recaptcha/intro/index.html

Use used to use recaptcha but ditched it since it proved too much of a barrier to sign up. It's gotten a lot better since then and our spam problems have gotten worse, so let's give it another try.

* show recaptcha on web signup form
* don't prevent signups via the API, i.e. via our own mobile apps

**Comment by pleary** [comment]
This is fixed in 25feb02, bb352f8, and 9dd7add
