### ISSUE TITLE
ElasticSearhc issue after creating a new account and while running rake es:rebuild

### ISSUE THREAD

**Issue by chivoX** [inaturalist/inaturalist#1260]
Hi im  getting this error after creating an account and after rruning this rake task

rake es:rebuild

Elasticsearch::Transport::Transport::Errors::BadRequest - [400] {"error":{"root_cause":[{"type":"parsing_exception","reason":"no [query] registered for [filtered]","line":1,"col":22}],"type":"parsing_exception","reason":"no [query] registered for [filtered]","line":1,"col":22},"status":400}:

Am I missing something from the installation steps ?

**Comment by pleary** [comment]
Sorry, the documentation was written before Elasticsearch 5.x was released  a few months ago. The Rails codebase is only compatible with Elasticsearch 2.x for now

**Comment by chivoX** [comment]
thanks, trying that out

**Comment by pleary** [comment]
No problem. Another point of reference reference would be our travis config https://github.com/inaturalist/inaturalist/blob/master/.travis.yml which is used to build linux machines on Travis's end every time we commit, so we know that's working and up-to-date

**Comment by chivoX** [comment]
oh ok great thanks a lot for that too, that will be of great help !
