### ISSUE TITLE
Issue with site on the home after creating an account

### ISSUE THREAD

**Issue by chivoX** [inaturalist/inaturalist#1261]
Im getting a nil error right after creating and account.

undefined method `getting_started_url' for nil:NilClass

= link_to @site.getting_started_url, target: "_blank" do

im prety sure this would have to do with some config files not being properly set up but could you give me a hint on his?

**Comment by pleary** [comment]
sounds like ApplicationController::set_site is finding a site to load. Make sure there's a site in the site table, and you probably need to set site_id in config.yml

**Comment by chivoX** [comment]
u mean directly on the yml file adding a line like this one:

site_id: 1

**Comment by pleary** [comment]
Here's the example config.yml https://github.com/inaturalist/inaturalist/blob/master/config/config.yml.example, and you'll want to add site_id like:

```
base: &base
    site_id: 1
```

**Comment by chivoX** [comment]
yeah that did the trick thanks a lot
