### ISSUE TITLE
‘chloropleth’ API endpoint 

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1262]
observations API endpoint that takes a taxon_id and an array of places and returns observation counts for that taxon in each place
```api.inaturalist.org/v1/observations/choropleth?places=14,12&taxon_id=2041&verifiable=true…```
analogous to ```histogram``` but binned by place_id rather than time.

Needed to add observed/unobserved styling to atlas maps, as described:
https://docs.google.com/document/d/16Q-DLHkTkSL0rFDkLGcXbqQEyBAEDykpfwreIBu2f2Y/edit#

**Comment by pleary** [comment]
I believe this is a request for a new API endpoint? Would you mind adding it to https://github.com/inaturalist/iNaturalistAPI/issues instead? It would be helpful to include a little snippet of the response. That might help me understand "analogous to histogram". I'm assuming you want a place_id and a count of observations, but it's not very clear to me.

And the second part about the styling - that's not a separate requirement of this ticket is it? I'm guessing that's just a description of how you plan to use this new endpoint? Sorry - I'm not being intentionally thick, just need a little more specifics so I can deliver what you need

**Comment by loarie** [comment]
whoops sorry I rewrote here https://github.com/inaturalist/iNaturalistAPI/issues/56

ignore the styling bit, I was just describing how I plan to use the endpoint
