### ISSUE TITLE
Sass error while deploying

### ISSUE THREAD

**Issue by chivoX** [inaturalist/inaturalist#1263]
Im getting this error while running the deploy

Sass::SyntaxError: File to import not found or unreadable: ../../../../node_modules/react-image-gallery/src/ImageGallery.

Any idea on why this may be happening ?

**Comment by kueda** [comment]
Make sure your deploy process is running `npm install` before the sass processor runs and that that is succeeding. For example, our config/deploy.rb looks something like

```
  desc "Install node packages"
  task :npm_install do
    on roles(:app) do
      within release_path do
        execute :npm, :install
        execute :node, "./node_modules/.bin/gulp webpack"
      end
    end
  end

  before "deploy:assets:precompile", :npm_install
```

That's adding hook before the assets get pre-compiled that installs all the npm packages and runs webpack to compile our react / es6 code.

**Comment by chivoX** [comment]
thanks that help me to get it running now im just missing assets but thats something i could handle myself maybe, but if you any pointers about it , i wouldnt complain :D

**Comment by kueda** [comment]
Which assets are you missing / what error message are you seeing?

**Comment by chivoX** [comment]
http://biopanama.com/ this is it. Like nothing :D

**Comment by kueda** [comment]
You need to edit `config/config.yml` and add some values that work for your site. I'm seeing a lot of references to `yoursite.com`, which is just the default value.

**Comment by chivoX** [comment]
yes !! that was the problem I set eveything up and it started working, any recomendations on getting elasticsearch running ?

**Comment by kueda** [comment]
As far as I know the instructions at https://github.com/inaturalist/inaturalist/wiki/development-setup-guide should work.
