### ISSUE TITLE
Any recomendations on how to setup postgres and postgis for this project ?

### ISSUE THREAD

**Issue by chivoX** [inaturalist/inaturalist#1266]
Hi Ive been tying to get to porject to work on Ubuntu but getting a lot of problems with PostGis, 
any recomendations on how to set it up and is that database.yml up to date with the config you guys use in prod ?

Basically when running the rake db:setup command several tables are nor being created because of this making the app not to work properly.

**Comment by pleary** [comment]
Feel free to email me directly and we can talk about this. If your database isn't being set up properly then you might have a problem with your database.yml, or with gems, or with postgres, or many other things, but it's not an issue with this codebase. So I'll close this ticket and we can have a separate discussion over email
