### ISSUE TITLE
Some followers show up twice

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1271]
Tiny bug, but some folks' followers list repeats users (https://groups.google.com/forum/#!topic/inaturalist/1QIPEntIEKE)

Examples: http://www.inaturalist.org/people/whaichi/followers and http://www.inaturalist.org/people/153013

**Comment by kueda** [comment]
Should be fixed now. Removed the duplicates and added a stricter rule to ensure these duplicates don't pop up again.
