### ISSUE TITLE
Incorporating Page Views in the Ob Detail Screen

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1276]
It has been a burning desire by some of us to know how many people are viewing ob detail screens. Ultimately, it would be nice to know how many live, physical human beings are viewing each ob, but it may be difficult to rule out robots. If simpler, a great place to start would be to track how many logged-in users are visiting a particular ob detail screen which could be displayed as a stat somewhere on the page. I personally would still find this information interesting, particularly when I'm really excited about an ob. Just think, for all the obs that have many comments and several faves, there's probably double the amount of people who viewed it.

**NOTE:** This is not a feature that would be part of the ob detail revamp first release.

**Comment by joellebel** [comment]
@kueda @loarie @pleary feel free to comment and/or add any functional specs if necessary.

**Comment by carrieseltzer** [comment]
More likely to do something based on the number of times an observation has been marked as reviewed, as suggested [on the forum](https://forum.inaturalist.org/t/show-number-of-reviewers-for-an-observation/38623).
