### ISSUE TITLE
Figuring out the best method to track web sign ups

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1277]
@kueda was looking through google web analytics and couldn't determine the best method to track if sign ups are successful. I'm thinking we might consider giving a different url to the first time a viewer looks at the dashboard. Not sure how feasible that is. It would appear Google Web Analytics Goals is perfect for this scenario. However, there also might be better event tracking solutions. 

Bottom line... I don't really care what method we use. I just would like to track the percentage of people that click on "Sign Up" and complete the sign up form. Would also be nice to know what page they clicked "Sign Up" from and what other pages they viewed in that session before clicking sign up. Might also be nice to know what they do the first time they see the dashboard, but that is secondary to the act of signing up.

**Comment by joellebel** [comment]
After more research, I think it may be best to remove any parameters after /home. Currently, after completing the sign up flow the url retains the parameter of the screen you were on before entering /signup. For example, “https://www.inaturalist.org/signup?return_to=https://www.inaturalist.org/observations". I am not 100% sure, but if this is something easy to do, it would rule out any doubts I have about tracking the flow of signup to dashboard. 

Also, if we could give the /home a different url like /home_first or something for the first time a user views the dashboard, I would be able to track it more easily in Google Analytics. However, let me know if it's something complicated to do.

**Comment by kueda** [comment]
Man, analytics is kind of brutal. I made it so new users land on `/home?new_user=true` and updated the goals in Analytics. Let's see if that has any effect.

**Comment by joellebel** [comment]
Tell me about it! Thanks a bunch!!

**Comment by kueda** [comment]
Joelle, can we close this or is there more you wanted to do? Tracking specific errors in signups seems like it might be a different issue.
