### ISSUE TITLE
API call for project does not return 2 project parameters in json object

### ISSUE THREAD

**Issue by naeluh** [inaturalist/inaturalist#1281]
Hi ,

From a specific project is it possible to pull these 2 stats ? Just the number ?

4 Observations
2 Species
3 People

I saw in the api it returns the

"project_observations_count":4,

But I could not find the others ?

I don't need any other info than the count.

Let me know if that makes sense. 

thanks ,

Nick

**Comment by pleary** [comment]
If you're looking to get the numbers that are on the project show page, those are being generated by the newer node.js-based iNaturalist API http://api.inaturalist.org/v1/docs/ . You can make the following calls to get those counts:

http://api.inaturalist.org/v1/observations?project_id=100&per_page=0
http://api.inaturalist.org/v1/observations/species_counts?project_id=100&per_page=0http://api.inaturalist.org/v1/observations/observers?project_id=100&per_page=1 (there's a bug with this endpoint which interprets per_page=0 as having no per_page param, and returns everything)

Obviously you can change the per_page parameter if you want to get back actual results and not just totals

**Comment by naeluh** [comment]
Hi @pleary ,

You know I just noticed the node.js api on the dev page.

I actually was just about to type the same answer. 

thanks for the quick reply !

Nick
