### ISSUE TITLE
Identify taxon autocomplete triggers many API calls

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#1305]
There are a few states which trigger updating the Identify page, which I don't think need to. It's not a huge problem, but may as well not hit the API if we don't need to. Seems like there are onChange and/or onBlur triggers on the taxon search field which might be over active.

The following actions trigger reloading obs and stats:
- Load http://www.inaturalist.org/observations/identify , click in the taxon search box, and click out of it
- Load Identify, click on the taxon search box, and type any letter
- Do the above and then delete the letter, thus clearing all text in the field

Right now, to load the page, click on taxon search, type "a", delete "a", then click outside the taxon search field results in a total of 46 API requests (a handful of which are OPTIONS requests, and all of which are requested to be uncached per their `ttl` param)

**Comment by kueda** [comment]
I think this was fixed in ab3912eeeb329117387842cb16b2a806d62c6bc0
