### ISSUE TITLE
taxa associated with observation matches CID? quality metric

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1309]
If the user opts out of the community ID and is unresponsive, there obs will be needs_id indefinitely which can be frustrating to IDers
http://www.inaturalist.org/observations/2361061

Currently, I use a no-vote on 'Community can confirm/improve ID?' to kick these obs out of needs_id into casual. But this isn't how that quality metric was intended to be used and this could be automated. I propose we add a 'taxa associated with observation matches CID?' quality metric. If someone opts out of CID and these don't match, an obs would be casual.

Thoughts @kueda?

**Comment by kueda** [comment]
So if someone has opted out of the CID and their ID doesn't match the CID or descend from the CID taxon, the observations is automatically casual? I think I'm ok with that, though I think I'd prefer to implement it not as a QualityMetric but instead like we do for "Non-human" or "Date?" Work for you?

**Comment by loarie** [comment]
I agree that it should be like 'non-human'

Where you say 'their ID doesn't match the CID or descend from the CID' I was thinking 'their ID doesn't match the CID nor is an ancestor of the CID' 
e.g. if the CID is Taricha torosa and the obs.taxon is Taricha, that would not be casual, but if the CID is Taricha and the obs.taxon is Taricha torosa that would be causal

**Comment by kueda** [comment]
I think that makes more sense. Sorry about that.

**Comment by loarie** [comment]
ok cool - sounds like we're in agreement here. 

This is the only use case I use 'Community can confirm/improve ID?' for. I wonder if folks would complain if we pulled that?

**Comment by kueda** [comment]
Just so this doesn't get deleted:

- [ ] obs is casual if taxon != CID taxon
- [ ] reassess all obs where CID taxon exists and taxon != CID taxon
- [ ] ensure quality grade changes when opt-out preference changes (I think it should already)

**Comment by loarie** [comment]
No.s 1 & 2 should be conditioned on opt-out preference

**Comment by kueda** [comment]
Some ideas from the Google Group that I think are worth discussing:

1) Should we only make it casual when a threshold of disagreeing IDs is met? E.g. if I insist it's *Vulpes* and you say it's *Vulpes vulpes*, maybe it only becomes `Casual` when there's one more ID of *Vulpes vulpes*, or two.
2) Should there be a rank distinction? E.g. only do this when the CID is at species level or below? Handles most situation where the observer's ID is at species level but the CID isn't.
3) Should there be an order / disagreement condition, e.g. only boot to `Casual` when CID != taxon && disagreement_count > 0`?

All are added complications that I don't love, but they satisfy some folks. Could start without them and see how people feel.

**Comment by loarie** [comment]
if we're going down this complex route, my preference would be that:
1) if the user opts out of CID
2) if CID is descendant to obs.taxon count that as CID support for obs.taxon
3) put obs in Research vs. Casual based on rank of obs.taxon (ie rank finer than family = research)

But I'm also fine with keeping things simple (e.g. CID != obs.taxon means casual), unless you think there's not enough community buy in for that simple approach

**Comment by kueda** [comment]
I take it that means you don't like any of those google group ideas? I feel like those are all easier to explain and implement than your preferred complicated version.

**Comment by loarie** [comment]
I don't feel super strongly. But, no I feel like 1,2,3 above seem pretty ad-hoc. I'd explain my preference this way:
"if you opt out of the community ID, your obs will stay in Needs ID until it gets reviewed by the community. It will be booted to casual if the community disagrees with your ID, otherwise it will be placed into casual or research based on the rank of your ID (an ID finer than family means research)."

But objectively since this is such a tiny minority of cases, and subjectively since I've never really understood the whole opting out of CID thing, I'm fine with keeping it simple
