### ISSUE TITLE
IDs with taxon_change_ids shouldn't count towards Ancestor Disagreements

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1310]
When IDs are automatically created from taxon changes, they shouldn't count towards Ancestor Disagreements. For example, `cladonia_chris's ID: Pixie Cup Lichens (Genus Cladonia) Added as part of a taxon swap` wasn't intended to disagree with the IDs of Cladonia furcata that were made after the now not current ID `cladonia_chris's ID: Reindeer Lichens (Genus Cladina [inactive]) (inactive taxon)` made over a year ago http://www.inaturalist.org/observations/1377161

While there haven't been many issues caused by this in the past, there's the potential for more now that ambiguous taxon-splits create ancestor IDs automatically, so this might be a good loose end to tie up.
<img width="683" alt="screen shot 2017-03-09 at 3 18 47 pm" src="https://cloud.githubusercontent.com/assets/598026/23775210/5fc77486-04dc-11e7-8436-1eb58c895ab2.png">
<img width="1238" alt="screen shot 2017-03-09 at 3 19 06 pm" src="https://cloud.githubusercontent.com/assets/598026/23775209/5fc6b186-04dc-11e7-89a7-ce4325d913d8.png">

**Comment by kueda** [comment]
Just to be clear, you'd like them to count, just not toward the disagreements, right?

**Comment by loarie** [comment]
exactly - 

Here's another use case for such 'blind IDs' e.g. IDs that are agnostic to chronology https://docs.google.com/document/d/1SRRsTSzCpgFzCxc7kj9e8nS-BWxHY5LzG5AXBTLAoME/edit

**Comment by kueda** [comment]
We could solve this know by setting every identification with a `taxon_change_id` to have `disagreement` set to `false`, right?

**Comment by loarie** [comment]
That would solve the situations where the ID generated by the taxon_change is an ancestor of the obs.taxon, but not in situations where its a sibling, e.g.:
```
1. User A: Taricha torosa
2. User B: Plethodon
3. -=Taricha torosa split=-
4. User A: Taricha
```
So we could either do that to partly fix this issue,

or we could wrap this in with the #1595 to have the CID count IDs with taxon_change_ids at the time of their original_created_at_date, e.g.:
```
1. User A: Taricha torosa
2. User B: Plethodon
3. -=Taricha torosa split=-
4. User A: Taricha (where original_created_at date = 1)
```
Thoughts?

**Comment by kueda** [comment]
Ok, if my proposal is only going to be a partial fix let's not do that. Not sure what you mean by "wrap this in." Do you mean that other issue would solve the same problem this one does, or just that they are related pieces of work?

**Comment by loarie** [comment]
If Identifications had a original_created_at col as proposed in #1595  then we could use that data to alter how the CID is calculated. But altering how the CID is calculated weren't specifically mentioned in #1595. So we could make a new issue that builds on #1595

**Comment by kueda** [comment]
...ok, I think you're saying this issue and #1595 are still separate, useful pieces of work, so I'll work on this and we'll get to 1595 when we get to it.

**Comment by loarie** [comment]
I was saying I think we should close/ignore this issue, implement #1595 and then create a new issue titled something like 'use original_created_at col as created_at date for IDs generated by taxon_changes in CID calculation'

**Comment by kueda** [comment]
Roger.
