### ISSUE TITLE
not all taxon children displaying on taxon page taxonomy tab

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1335]
e.g. under http://www.inaturalist.org/taxa/50800-Lithophragma I don't see Lithophragma campanulatum which was created Fri, 13 May 2011 21:42:47 UTC +00:00

**Comment by kueda** [comment]
Should be fixed by https://github.com/inaturalist/iNaturalistAPI/commit/8ea3fe5410cbaff185ccd0ab41abbcd6de011bfc
