### ISSUE TITLE
optionally add a floating indicator onto observation photos 

### ISSUE THREAD

**Issue by Chungzuwalla** [inaturalist/inaturalist#1344]
https://groups.google.com/forum/#!topic/inaturalist/MYVF4Qhypyg

Discussion of this enhancement in the group is pretty supportive, but there's no input from any devs.  Maybe we can get something going here about how this would actually look & work in practice?

**Comment by kueda** [comment]
Sifting through old issues here. Please actually describe what change you're proposing here and don't just link to a description elsewhere. I don't know what you mean by a "floating indicator" or what part of the website you're proposing adding it to.
