### ISSUE TITLE
Add Obs Alert

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1349]
So many times I've accidentally closed the add obs tab while looking at another open tab. This can mean a loss of a lot of obs.

Is it possible to create a dialogue modal confirming the closing action, if they attempt to close it while looking at another tab. Facebook does this. If you are in the middle of creating a post, go to another tab and try to close the Facebook tab, you are taken back to the Facebook tab and given the alert like so... 

![image](https://cloud.githubusercontent.com/assets/11527994/25456595/32d14458-2a88-11e7-8596-8beb4c344def.png)

The dialogue also remains regardless of what tab you go to...

![image](https://cloud.githubusercontent.com/assets/11527994/25456626/4c23c87c-2a88-11e7-9766-1134a1598834.png)

**Comment by pleary** [comment]
This is working for me in Chrome, Safari, and FF on my Mac. If there are any obs cards, you should get an alert. Sounds like you're not seeing that message. What version of Chrome are you using? Does it work for you in other browsers?

**Comment by joellebel** [comment]
My apologies I can't reproduce this bug now. Consarnit. I only reported it because I thought we didn't have that functionality. 

One thing I am noticing though... If you drag 100+ obs onto Add Obs, immediately go to another tab and try to close Add Obs, you won't get the alert. However, I think that's an edge case. 

Works for me on Chrome Version 57.0.2987.133 (64-bit), FF 42.0 and Safari Version 10.1 (12603.1.30.0.34)

I'm on Mac Sierra 10.12.4.

If you're not finding anything wrong, I guess we can close this issue.

**Comment by joellebel** [comment]
Haven't been really able to replicate this bug, so closing
