### ISSUE TITLE
species not appearing in the species tab

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1360]
The Species Tab on obs search is capped at 500 species, but in some situations, a taxon that *should* appear there does not. Here's one:

https://www.inaturalist.org/observations?nelat=35.97800618085566&nelng=-92.098388671875&place_id=any&swlat=25.621715959845755&swlng=-103.656005859375&taxon_id=47208&view=species

If you look at https://www.inaturalist.org/observations?nelat=35.97800618085566&nelng=-92.098388671875&place_id=any&swlat=25.621715959845755&swlng=-103.656005859375&taxon_id=311038&view=species, you'll see that *Anomoea rufifrons* has 9 obs and should be on that list.

**Comment by pleary** [comment]
I think this is fixed in inaturalist/iNaturalistAPI@eabca83
