### ISSUE TITLE
duplicate, current identifications

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1377]
Some how, this happened on http://www.inaturalist.org/observations/394090:

![screen shot 2017-05-30 at 4 04 42 pm](https://cloud.githubusercontent.com/assets/22691/26608674/ba567c98-4551-11e7-95d0-22aeabea0031.png)

Having trouble hunting it down right now b/c Kibana is down, but I wanted to at least file it. Need to figure out where these requests came from.

**Comment by irag** [comment]
I had a duplicate too. So I deleted one of them, but both got deleted. Now I'm screwed because it was already added to two projects.   Is there any way to recover this?  It was for a sweetgum, first I ever did and there were about 6 photos.  maybe more.

**Comment by loarie** [comment]
Pretty sure this was fixed here https://github.com/inaturalist/inaturalist/issues/1491
irag please send help inquiries to help@inaturalist.org
