### ISSUE TITLE
2 'umbrella slideshows'

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1387]
Analogous to http://www.inaturalist.org/stats/cnc2017

we need slideshows for each of the following 2 projects:

http://www.inaturalist.org/projects/bioblitz-canada-150

http://www.inaturalist.org/projects/parks-canada-bioblitz

Question 1:
the cnc2017 slideshow shows a places count on the first slide and a leaderboard on the last slide. I presume these are coming for the 'must be in place' rules in the umbrella project? If so thats how these should work

Question 2: @kueda or @pleary preference for who wants to take a crack at this work?

**Comment by kueda** [comment]
What do you want to call this umbrella thing?

**Comment by loarie** [comment]
how about
http://www.inaturalist.org/stats/canada_150
and
http://www.inaturalist.org/stats/parks_canada
?
