### ISSUE TITLE
method isn't indexing the observation after the quality grade change

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1392]
Scott noticed this when using the web uploader:
1) dragged a bunch of photos in
2) selected all added locations
3) submit

they are indexed as casual even though they should be needs_id
e.g. https://www.inaturalist.org/observations/6730846

**Comment by kueda** [comment]
Does this happen consistently with all images, or just some?

**Comment by loarie** [comment]
I just reproduced with 4 photos using the above 3 steps, so I think its consistent and reproducable
