### ISSUE TITLE
Change title of photo info page

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1395]
This is a lower priority item but.... Can we make the title of the photo info page "Photo Info"? Here's a sample URL. http://www.inaturalist.org/photos/8581736 I don't think the number needs to be in the title nor the photos rights as all that info is on the right. I remember it taking me forever to figure out what this page was when I first started using iNat. Now that it's more prominent, I suspect more people will be clicking on it. 

Lastly, since the link to get to this page is an "info" link, it would be a nice follow through if the title was more aligned with the link.

**Comment by kueda** [comment]
I'm fine with something like `Info for Photo 1234` but I think the photo ID should be in there so the title is unique. We don't want a browser history that looks like

```
Photo Info
Photo Info
Photo Info
Photo Info
Photo Info
```

if they're all different photos.
