### ISSUE TITLE
Make sure observations from the Android app get an oauth_application_id

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#1401]
Starting around mid-April we started to get observations from the Android app that don't have `oauth_application_id`s, but seemingly have proper user agents.

- [x] Make sure these get `oauth_application_id`s
- [x] Apply the same check for iPhone and FishTagger apps
- [x] Apply the missing oauth_application_ids retroactively and re-index those observations
- [x] Remove the `device_url` conditional on https://github.com/inaturalist/inaturalist/blob/master/app/views/observations/show.html.erb#L417 so the view is only looking at `oauth_application_id`
- [x] When all that's done, observations like http://www.inaturalist.org/observations/6753970 should show the "This observation was created using..." bit in the Copyright and More section in the new obs show page, which is only looking at `oauth_application_id` and not the `user_agent`
- [x] [No longer necessary since Patrick refactored to use ES instead] Finally, retroactively update SiteStatistics so we're getting the right counts in the Web/iPhone/Android chart (or make a new ticket for that once the rest of these tasks are done)

**Comment by kueda** [comment]
Partially done in 66d7892ac040055d5fc704732ee1490a7db493a9. Obs/show-specific stuff listed here probably isn't necessary now that we have a new obs/show. Still need to retro-actively fill in oauth application IDs for obs that need them.
