### ISSUE TITLE
Observation::set_community_taxa DJ gets stuck

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#1403]
Observation::set_community_taxa
args: {:user=>264009}

This runs for a very long time and ultimately fails. Maybe we don't need to do anything for observations where the owner's ID is equal to the community ID, thus saving some processing time??

**Comment by pleary** [comment]
This has not happened for a while, so I'm closing it

**Comment by kueda** [comment]
Re-opening since it's still an occasional problem. I'll try and refactor to use ES.

**Comment by pleary** [comment]
Looks like this was addressed in 41bc439
