### ISSUE TITLE
multiple taxa for controlled terms

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1405]
Controlled terms should be associated with multiple taxa. They also probably need to be excepted from certain taxa for situations where most taxa within a clade should have a term except for a few. So, perhaps a join model?

```
ControlledTermTaxon
  controlled_term_id
  taxon_id
  exception (default: false)

class ControlledTerm
  has_many :controlled_term_taxa
  has_many :taxa, through: :controlled_term_taxa, where: { exception: false }
  has_many :excepted_taxa,
    through: :controlled_term_taxa,
    as: :taxon,
    where: { exception: true }
```

TODO

- [x] make `ControlledTermTaxon` migration and class
- [x] update `ControlledTerm`, perhaps leave existing `valid_within_clade` column at first as a fallback
- [x] update `ControlledTerm.for_taxon`
- [x] update `ControlledTerm#applicable_to_taxon`
- [x] update `ControlledTerm#as_indexed_json`: Need to index an array of taxon IDs and another array of excepted taxon IDs, I think, so maybe just `taxon_ids` and `excepted_taxon_ids`
- [x] Update controlled term form to show associated taxa and their exception status
- [x] update iNaturalistAPI to use these new index values
- [ ] remove the old column

**Comment by kueda** [comment]
@pleary, I've noticed while working on this that most of the filtration of terms for taxa seems to happen in `annotations.jsx` and not in iNaturalistAPI. I've maintained that here but is that your preference? Seems like api.inaturalist.org/v1/controlled_terms/for_taxon does not look at ancestors of the chosen taxon at present, but in theory it could.

**Comment by pleary** [comment]
I don't have a strong preference. for_taxon does allow filtering the attribute terms by taxon_id if the user sends that param. I call it from the obs show page it with multiple taxon_ids, all the IDs in the ancestry of the taxon I care about, so the attribute terms I get back are relevant to only the taxon in the observations. It is not, however, filtering the value terms.

If we wanted to do the filtering in the API then it means we'd probably switch that to only allowing a single taxon_id be sent to the API, and then we'd need an extra DB call or ES query to look up that taxon so we know what its ancestors are. I suppose that's better for the end user, in that they won't have to do any filtering on the API responses, but it'll slow down the API ever so slightly. If you want to try it that way, that's OK with me.
