### ISSUE TITLE
Better integrate Google Photos

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1408]
Currently I can import photos from my Google Photos account via the "Import from Picasa" framework, but it won't import correct Time/Date, and no location data at all.  Is it possible to import photos with correct metadata from Google Photos? There's some support in the Google Group.

https://groups.google.com/forum/#!searchin/inaturalist/google$20photos%7Csort:relevance/inaturalist/fgpKZvgnDpw/zMzxWlM4BAAJ

**Comment by kueda** [comment]
I can see some issues with date/time and photo sizes, but I'm not seeing a problem with location import. Can you cite a specific example or provide a file?

**Comment by akleinhesselink** [comment]
Also having trouble with meta data on google photos. I'm using iNaturalist on Chrome on my desktop. Upload works but photo metadata is left out so I have to figure out where and when photos were taken to make observations.

**Comment by kueda** [comment]
Again, I am not going to make any progress here without concrete examples, so email us files or send us URLs of photos I can use to try and recreate these problems.

**Comment by akleinhesselink** [comment]
Apologies if this is confusion on my part.  This may be a problem with my google photos settings.  

But here's what I'm seeing:  when I add observations from "more import options" and then import a photo from flickr, the date and time metadata are automatically imported into the observation. 

Here's a flickr image: 
https://flic.kr/p/Y1REF6

And here's an observation on iNaturalist created from that image: 
https://www.inaturalist.org/observations/7623914

However, when I try to add an observation in the same way from google photos (by selecting "more import options" and then selecting "picasa" (there's no link for google photos) and then my image, the date and time does not automatically populate the new observation being created. 

Here's a link to an album with the same image as above on google photos: 
https://goo.gl/photos/SCQNbB32cY6GY6Xo8

And here's an iNaturalist observation that I tried to create from that google photo: 
https://www.inaturalist.org/photos/9969239

When I'm logged in to iNaturalist I can view the GPS metadata associated with both the image from flickr and from google/picasa.

I'm attach two screenshots that show image info from both of the records (I hope these work): 

![flickr_screencapture-inaturalist-org-photos-9967441-1503535929520](https://user-images.githubusercontent.com/5205626/29644591-2c89ddb0-882c-11e7-8be3-5df8304af508.png)

![google_screencapture-inaturalist-org-photos-9969239-1503535876355](https://user-images.githubusercontent.com/5205626/29644611-5a5357b2-882c-11e7-8493-8d66a01a5001.png)

**Comment by tiwane** [comment]
Here's a photo that I exported from Capture One Pro, with date/time/location metadata embedded. 

![dsc04221](https://user-images.githubusercontent.com/15896181/29650057-23be113a-884d-11e7-86a0-573bca7842af.jpg)

When I upload it to Google Photos then import it from there into iNat (via https://www.inaturalist.org/observations/import then Google > Picasa > Auto Backup), iNat can't read the location metadata:

<img width="993" alt="screen shot 2017-08-23 at 9 46 48 pm" src="https://user-images.githubusercontent.com/15896181/29650051-1a521196-884d-11e7-9c81-0f8a9da57696.png">

When I upload the photo via https://www.inaturalist.org/observations/upload the location is read by iNat:

<img width="322" alt="screen shot 2017-08-23 at 9 47 17 pm" src="https://user-images.githubusercontent.com/15896181/29650102-76c73bfe-884d-11e7-88cd-0b071bfd95df.png">

Same thing with a photo I take on my phone then upload via the Google Photos app.

**Comment by kueda** [comment]
I spent a few hours looking into this today without much luck. I can replicate the experience you guys are having when I test your accounts, but when I upload the same photos to my account they import just fine. I'm going to try extracting the metadata from the photo files instead of the API responses which should "fix" the problem, but it will also make imports much slower b/c we have to grab the whole photo to get its metadata.

**Comment by akleinhesselink** [comment]
Thanks for looking into this!

**Comment by kueda** [comment]
Can you two confirm that this is working now? I think I went with the ugly but functional fix, so as far as I know it should be working.

**Comment by akleinhesselink** [comment]
It looks like it works.  One minor issue, I'm seeing that it doesn't automatically get the timezone. The time looks correct but it's defaulting to Hawaiian Standard Time (HST/GMT 10) for my observations made in California.  The google photos info says Pacific Daylight Time (GMT 7).  This may be a problem with my settings so I'll let someone else check that out.   

Here's an example observation I just created using the google photos import: 

http://www.inaturalist.org/observations/7794611

Let me know if you want me to provide you more specifics.

Sorry Google Photos is offering a proper API.  Seems like they are trying to make it harder for people to use this product. 

Thanks again, 
Andy

**Comment by kueda** [comment]
The time zone thing is an unrelated issue. We set timezones based on what the user chooses for that observation (currently impossible from the uploader but doable when editing), from the date/time string (e.g. if it looks something like 2017/08/21 11:15 PM CDT), and then from the user's preference. When deriving dates from photos, we generally don't get zone info, so we usually end up relying on the user's preferred time zone, and yours is set to Hawaii. You can change that at https://www.inaturalist.org/users/edit
