### ISSUE TITLE
ActionController::RoutingError

### ISSUE THREAD

**Issue by jailsonleocadio** [inaturalist/inaturalist#1415]
When I click on "Add Observations" (/observations/upload) on homepage of a logged user, nothing is showed on page.

The log is:

 **ActionController::RoutingError (No route matches [GET] "/javascripts/observations-uploader-webpack.js"):**
   **config/initializers/logstasher_catch_all_errors.rb:8:in `call'**

Similar error is obtained with the request of page: /observations/identify.
Are the requested javascript files available in the repository?

**Comment by pleary** [comment]
We use gulp/webpack to prepare our React JS code for use by the Rails asset pipeline. Make sure your gems are up-to-date and use `gulp` to compile `observations-uploader-webpack.js` and several others

**Comment by pleary** [comment]
sorry, it's not a gem. We also use node.js packages, which is what `gulp` is. There's a `.nvmrc` file if you use NVM to manage node, or otherwise try to run node `5.8.0` or similar. Then `npm install` and then `gulp` should work. We probably have some documentation that needs updating

**Comment by jailsonleocadio** [comment]
Thank you! This was very helpful.
