### ISSUE TITLE
Zooming on small photos in Identify doesn't work

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1420]
In Identify, zooming on small photos makes them smaller and places them in upper left-hand corner (https://www.inaturalist.org/observations/7165086)

<img width="1384" alt="screen shot 2017-07-22 at 10 45 06 pm" src="https://user-images.githubusercontent.com/15896181/28500277-425bf51c-6f7a-11e7-8159-a8625b9dc4c2.png">

**Comment by kueda** [comment]
I addressed this by just making it impossible to zoom in on things that have already been scaled up to fit the space: https://www.inaturalist.org/observations/identify?quality_grade=any&user_id=neiltsutsui&taxon_id=28339&place_id=any
