### ISSUE TITLE
Clone pt.yml from pt-br.yml

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1424]
iNat already has pt-br.yml (Brazilian Portuguese) that is mostly (~80%) complete. We don't yet have pt.yml (Portuguese). But our Portuguese partners would prefer to start with a pt.yml cloned from pt-br.yml that they then alter rather than start a pt.yml from scratch.

On Translatewiki it looks like pt is 23% translated:
https://translatewiki.net/wiki/Special:MessageGroupStats/out-inaturalist#sortable:3=asc
@Nikerabbit / @translatewiki what will happen on the translate wiki side if we duplicate a pt.yml file from pt-br.yml? Will that squash the 23% work thats happened on translate wiki during the next harvest? If so is there a better way to achieve this?

**Comment by Nikerabbit** [comment]
I would recommend to just start translating it on translatewiki.net. The translators can set pt-br as an assistant language in their preferences. That allows easy access to those translations when they are available.
