### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by jailsonleocadio** [inaturalist/inaturalist#1429]
How can I generate the requested files?

assets/bootstrap.css.map
assets/on-screen.umd.js.map

Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by kueda** [comment]
We don't generate `.map` files so I'm not sure what that means. Can you provide a screenshot of the error you're seeing?

**Comment by jailsonleocadio** [comment]
There is no error in the screen. But when I inspect the page, the console indicates: Failed to load resource: the server responded with a status of 404 (Not Found).

**Comment by kueda** [comment]
Yup, that's what I'm asking for, a screenshot of the screen with the console errors. That way I can see what URL you're at and what the actual errors are.

**Comment by kueda** [comment]
Closing for now. If you can provide the requested info please re-open.
