### ISSUE TITLE
Transfer Protocol

### ISSUE THREAD

**Issue by jailsonleocadio** [inaturalist/inaturalist#1430]
The attachments (images) are requested with https. Is it possible to configure to use only http?

The server I'm using there is no SSL certificate. Is it possible to host the iNat this way?

**Comment by kueda** [comment]
There are a couple ways we generate image URLs. Can you provide a screenshot of a specific image? For a lot of things you can control this with `CONFIG.assets_host` and `CONFIG.site_url` in production. See  https://github.com/inaturalist/inaturalist/blob/master/config/environments/production.rb#L46

**Comment by jailsonleocadio** [comment]
It's in development mode. The images of observations aren't shown on browser because they are requested with https.

**Comment by kueda** [comment]
Well then please give me something to understand exactly what image is broken. There are a lot of images referenced in this code base and numerous ways to construct URLs that vary based on environment, type of image etc, so unless I have some information about what images are broken I can't really help you.

**Comment by jailsonleocadio** [comment]
In the case of this image, I created a new observation and added only one image.
But the image isn't shown when I click to view the observation details.

![captura de tela 2017-07-31 as 21 25 45](https://user-images.githubusercontent.com/1500146/28804021-0724b088-7637-11e7-8ac8-59d9bffbbc16.png)

If I inspect the code page on the browser and remove the 's' of the 'https' of the image url, the image is showed normally.

![captura de tela 2017-07-31 as 21 33 38](https://user-images.githubusercontent.com/1500146/28804187-fa5ed54e-7637-11e7-8f8e-f7942d73b63c.png)

**Comment by kueda** [comment]
What are the values of `CONFIG.assets_host` and `CONFIG.site_url` in `config/config.yml`?

**Comment by jailsonleocadio** [comment]
In this file, the `CONFIG.site_url` is with the value `site_url: http://www.jailsonleocadio.org` without https.

There isn't the `CONFIG.assets_host`.

**Comment by pleary** [comment]
Search for `s3_protocol` and replace `https` with `http`. We need to allow that to be configured. If you want to do that and send a pull request, that'd be great. Otherwise just change what you need locally and we'll eventually make that more flexible

**Comment by jailsonleocadio** [comment]
@pleary Almost every `s3_protocol` is defined into the condition `if Rails.env.production?`.
That's not my case.

I solved the problem editing the regular expression in `with_fixed_https` (`config/initializers/extensions.rb`). Maybe this isn't the best solution, but for now it helped.

**Comment by pleary** [comment]
We have since added a config option for `CONFIG.s3_protocol`. It sounds like this may not help you because you may not be using the S3 uploads. I'm not sure why editing `with_fixed_https` should make a difference for you running locally, as that method changes pre-defined domains, such as static.inaturalist.org. That shouldn't matter unless you're using local DNS to change what those domains point to.

Given are moving towards only supporting https requests, I'm going to close this. Please feel free to re-open if you think this is premature, but please list the specific requirement if you do so
