### ISSUE TITLE
Populating taxon field during upload should bail when encountering taxonomic synonyms from photo keyword

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1437]
When I uploaded this photo to the web, the taxon field populated as Melissodes pileata, even though the photo was tagged as only Melissodes. This was due to M. pileata having a scientific name of just Melissodes (which has now been deleted).

The uploader, however, should not put in any taxon if it encounters a synonym, to avoid this situation.

![dsc02478](https://user-images.githubusercontent.com/15896181/28804351-701f0a2c-7617-11e7-94ad-c05886913933.jpg)

**Comment by kueda** [comment]
I seem to remember fixing this, and I can't replicate it with this photo. Do you think this is still happening?
