### ISSUE TITLE
Obs Detail Design Nitty Grits

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1440]
- [x] The iconic taxa icon needs to be centered within its box: http://www.inaturalist.org/observations/7338818

![image](https://user-images.githubusercontent.com/11527994/28948382-33665cca-786a-11e7-9136-8ed9030e2cf4.png)

- [x]  The iconic taxa icon needs box border like the one above: http://www.inaturalist.org/observations/7338818 

![image](https://user-images.githubusercontent.com/11527994/28948405-58e99520-786a-11e7-9a44-46463b8ca0d7.png)

- [x] Activity time line needs line between comments/IDs. See styling specs [here](http://www.thinkmoredesign.com/inat/Specs/Web/Observation_Detail/Observation_Detail_v01_r07/#artboard25)

![image](https://user-images.githubusercontent.com/11527994/28948439-8aedd798-786a-11e7-9036-7904ffe18b5d.png)

- [x] Need some space between the question and the checkboxes... Currently looks like this...
![image](https://user-images.githubusercontent.com/11527994/28948510-fb1bf77a-786a-11e7-9bf0-4b6f163c440e.png)
Should look like this: 
![image](https://user-images.githubusercontent.com/11527994/28948499-e5a4a892-786a-11e7-9c86-ea253b743c2b.png)

- [x] The same problem above exists in the Identify Tool obs. Should I make a separate issue for that?

- [x] Can we make the chevrons exactly centered in their circles on Chrome? Annoying, I know. Seems to be fine on FF. 
![image](https://user-images.githubusercontent.com/11527994/29238204-968fbfb4-7ee4-11e7-8729-879f32072cdc.png)

- [x] The Description and Activity headings need a bottom margin of 20px. Currently, they are 10px

- [x] Project thumbnails need an additional 3px of right margin so there's ample spacing between it and the project name. Should look like this...
![image](https://user-images.githubusercontent.com/11527994/29238251-cd42fac0-7ee5-11e7-9e6c-5f33a3f1bb3b.png)

 - [ ]  Did you want to add the hover states to the "Nearby Obs.." etcs sections? ...or I can make a separate issue for that.

**Comment by joellebel** [comment]
@kueda not done yet, but just didn't want to lose this list. Will let you know when I'm done.

**Comment by joellebel** [comment]
@kueda ok. this is ready to go! Let me know if you

**Comment by kueda** [comment]
I think I got everything except the last one. Nearby Obs and Obs of Relatives both have hover states already.
