### ISSUE TITLE
Make Discoveries feed from recent_taxa api

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1443]
The existing recent_taxa api can be used to provide the stream of 'Discoveries' proposed here: https://docs.google.com/document/d/1LAP6zI9X-Fd8vaGU81R-ncuftCQ3bgLktPoJy7FDOz0/edit
Fo example, to show the 10 most recently 'discovered' reptile species use: :
```
taxon_id=26036
url = "http://api.inaturalist.org/v1/identifications/recent_taxa?taxon_id=#{taxon_id}&category=improving,leading&hrank=species&quality_grade=research,needs_id"
uri = URI(url)
response = Net::HTTP.get(uri); nil
dat = JSON.parse(response); nil
dat["results"].map{|a| a["identification"]["observation"]["id"]}.uniq[0..10]
```

Existing issues with the recent_taxa API include:

1. Identifications in ES getting out of sync as described here: https://github.com/inaturalist/inaturalist/issues/1196

2. New taxon_ids resulting from taxon changes are getting logged as Discoveries. e.g. first ID of Species A posted 2 years ago, last week Species A swapped into Species B, Species B would be logged as a discovery this week. By excluding IDs with taxon_change_id not nil we could avoid this (it will mean we're overlooking some species, but I think this would do more good than harm)

**Comment by kueda** [comment]
I *think* 1 has been dealt with. Do you have any examples of 2 happening? The `recent_taxa` endpoint *should* be ignoring identifications from taxon changes, but if it's not it would help to have an example while debugging it.

**Comment by loarie** [comment]
I'm seeing 
http://www.inaturalist.org/observations/24158
in the response to http://api.inaturalist.org/v1/identifications/recent_taxa?taxon_id=20978&category=improving,leading&hrank=species&quality_grade=research,needs_id
even though the recent IDs all have non-nil taxon_change_ids

**Comment by kueda** [comment]
TODO

- [ ] Drop ident categories

**Comment by loarie** [comment]
this looks good
