### ISSUE TITLE
'Wanted' API

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1444]
To provide the Wanted stream proposed here https://docs.google.com/document/d/1LAP6zI9X-Fd8vaGU81R-ncuftCQ3bgLktPoJy7FDOz0/edit
we'd need a way to take a 'complete' taxon node, (a) fetch all of its species level descendants and (b) intersect them with the set of taxa represented by observations for that taxon.

A limitation of using the existing observations/species_counts API for (b) is that it only returns 500 species which might be an issue for large clades

**Comment by kueda** [comment]
Todo

- [ ] "Wanted" seems to be excluding taxa that are represented in Casual obs, e.g. _Homo sapiens_ should *always* be "Wanted" within _Homo_ b/c observations of that taxon are always Casual

**Comment by loarie** [comment]
@kueda - moving this comment from the commit (it still seems to be happening):

I think your wanted algorithm is excluding taxa with only casual obs from wanted, e.g. http://gorilla.inaturalist.org/taxa/187004-Acanthurus-polyzona should be represented among the wanted here: http://gorilla.inaturalist.org/taxa/55382-Acanthurus#highlights-tab but its missing because it has one casual obs. My preference is to consistently only 'count' taxa ticked-off with verifiable obs to make it consistent with the species-observed/total ratio and the discoveries feed.

**Comment by loarie** [comment]
also just confirming that the other todo above 'Don't show "Wanted" on taxa/show if there are none' also doesn't yet seem done
http://gorilla.inaturalist.org/taxa/24229-Acris#highlights-tab
