### ISSUE TITLE
Sound Observation Icon Revisions

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1449]
# Treatment for Ob Search Grid View

![image](https://user-images.githubusercontent.com/11527994/29200894-11b23898-7e0e-11e7-94eb-914398ed7237.png)

* the background is #ddd and the icon is #777

(I was going to suggest using the same treatment for photo-less obs, but I wouldn’t want folks to mistake the two. Eventually, perhaps, we can use color to indicate what iconic taxa the ob is in.)

## Question:  
The icon is looking a little big. Is it the same size as the one we use for photo-less obs?

# Design for Dashboard Timeline

![image](https://user-images.githubusercontent.com/11527994/29200933-67a301ce-7e0e-11e7-8807-ce24bb9eb83b.png)

* Please use the Grid View bg and icon color treatment for the above situation
* The icon is going to have to be a little smaller there, as well, so there’s ample padding.

**Comment by kueda** [comment]
These should all be addressed in 0f72a984b49207df6646056dfa8ec030366f53dd... which I'll get on a test server if/when we have one again.
