### ISSUE TITLE
Aggregation option when creating a bioblitz project not visible to non-curators

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1454]
If someone who is not a site curator creates a bioblitz project, they can't see the option to "automatically add observations to this project" unless they first save and then edit the project. 

I didn't know this until talking someone else (non-curator) through creating a bioblitz project.

Fixing this would cut down on the "why isn't my bioblitz project aggregating observations?" posts.

**Comment by pleary** [comment]
We've removed the project aggregation option, which makes this issue obsolete
