### ISSUE TITLE
Add the ability to change time zone in the Obs upload page

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1455]
If I'm on a trip and am uploading observations, the obs upload page defaults to my account's default time zone, meaning the observations I'm uploading have the incorrect time zone applied to them. As of now there's no way to quickly change one's time zone on the upload page, but it'd be a great addition.

**Comment by kueda** [comment]
For the record, I think you said you didn't think this would be necessary with [automatic time zone assignment](https://github.com/inaturalist/inaturalist/pull/2799), right @tiwane? I certainly don't think it is.
