### ISSUE TITLE
Can't zoom in on photo when using Identify for Obs with both Photos and Sounds

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1457]
This was brought up in this thread: https://groups.google.com/forum/#!topic/inaturalist/CoEwk2IEcCU

Here's a link for obs with both photos and sounds in Identify: https://groups.google.com/forum/#!topic/inaturalist/CoEwk2IEcCU

**Comment by kueda** [comment]
Were you able to replicate? Zoom works just fine for me in Firefox and Chrome.

**Comment by kueda** [comment]
Please re-open if you can provide conditions for replication.
