### ISSUE TITLE
About home page data

### ISSUE THREAD

**Issue by jailsonleocadio** [inaturalist/inaturalist#1460]
Hi, guys! The `HOMEPAGE_DATA` (`_index.html.haml:6`) is setted manually? If yes, how can I do that?
I'm interested in adding some observations to home page slide.

**Comment by kueda** [comment]
It comes from the Site record, so you can edit it by going to /sites and putting some relevant JSON  in the `homepage data` field for the relevant site.

**Comment by jailsonleocadio** [comment]
Thank you!
