### ISSUE TITLE
Observations update

### ISSUE THREAD

**Issue by jailsonleocadio** [inaturalist/inaturalist#1461]
When I do some modifications in my observations at **inaturalist.org**, these updates aren't downloaded in Android App.
I think the problem occurs because the value `updated_at` isn't updated every time I modify the observation.

For example: to delete observation's species name, to change the location, to alter if it is captive or not ...

But some others modifications updates the value and it's downloaded in the App: to include a species name.

**Comment by kueda** [comment]
This sounds like an issue with the Android app and not the Rails app. In theory when you pull to refresh the Android app should get updates on all your observations that were updated since the last time you pulled down observations from the website.
