### ISSUE TITLE
add date_updated in allowed values for order_by in API

### ISSUE THREAD

**Issue by eliagbayani** [inaturalist/inaturalist#1467]
In the API reference:
https://www.inaturalist.org/pages/api+reference
The "order_by" allowed values are only these two:
    observed_on
    date_added

date_added here is very helpful.
To make better API request (less loops) and part of the workaround of the 10k limit hopefully iNat can add another allowed value which is: date_updated.

**Comment by pleary** [comment]
Hey Eli. The API that documentation refers to has sort of been deprecated for most data reading requests in favor of https://api.inaturalist.org/v1/docs/ , which is generally faster for fetching data. I'd recommend you use the latter if you're just querying for observations.

I just added an option to sort observations results in the new API by `updated_at` https://api.inaturalist.org/v1/observations?per_page=1&order_by=updated_at&order=desc . FYI that API has its own codebase at https://github.com/inaturalist/iNaturalistAPI and the relevant commit is inaturalist/iNaturalistAPI@362d1ccdc5b29903826054d9b0e124dcbde17035

I didn't add that to the documentation though, as it's hard to explain what exactly that does, and it might be frustrating to use. Using that sort option will sort requests by the value of the `updated_at` column in the `observations` database table, but `updated_at` isn't updated for every single data change which could affect an observation's response object. For example, if a taxon's name changes, that doesn't automatically trigger an update of every observation of that taxon, or observations of descendants of that taxon for that matter. Same goes for most metadata on associations (username changes, project metadata changes, etc.).

If you scan the code in this codebase, any model that implements `Shared::TouchesObservationModule` will trigger an update of their associated observation on CRUD operations, so for example an observation will be updated if a new ID is added to it, or its added to a project. So it'll be useful for some things, but not everything

**Comment by eliagbayani** [comment]
Hi Patrick! Glad to talk to you again.
Thanks for explaining how the field updated_at is being used. Very helpful.
Also doing order_by=updated_at now works like a charm. I think we're now getting the records we want. Thanks a lot again Patrick!
