### ISSUE TITLE
DELETE /observations/{id} responds with incorrect status code

### ISSUE THREAD

**Issue by kgarsuta** [inaturalist/inaturalist#1469]
DELETE /observations/{id}.json without proper credentials (e.g. don't own observation) responds with Status 200 OK. This should respond with Status 401 Unauthorized (like other endpoints).

**Comment by NeimadTL** [comment]
Hi, @kgarsuta @kueda 

Looks like the status code `, status: :unauthorized` is missing in the render method on this line : [https://github.com/inaturalist/inaturalist/blob/183cadef95c3fb4ac841a51d637d818bc24ab348/app/controllers/observations_controller.rb#L2505](url)

Would be agree be agree with me on that ? I'm a newcomer, still new to ruby, rails and oss in general. 
Thanks.

**Comment by kueda** [comment]
When I do `curl -XDELETE -v https://www.inaturalist.org/observations/12919932.json` I get a `401 Unauthorized` response, so I think this got fixed somewhere along the way. Regarding the body of the response, the responses from our Rails API are pretty inconsistent and I don't think we include a `status` attribute that much. I recommend using our Node API which is a lot more consistent: curl -XDELETE -v https://api.inaturalist.org/v1/observations/12919932. Docs at http://api.inaturalist.org/v1/docs/#!/Observations/delete_observations_id

**Comment by NeimadTL** [comment]
ok. thank you @kueda. Anything you could suggest a beginner to work on (preferably ruby on rails) ?

**Comment by kueda** [comment]
First step is to actually get a local version of iNat running, which is no small feat. We have a few other issues labeled easy that might be good to try from there: https://github.com/inaturalist/inaturalist/labels/easy

**Comment by NeimadTL** [comment]
yeah you were right : bundler is giving me a hard time with puma. Thank you.
