### ISSUE TITLE
500 error when sending image to POST /observation_photos endpoint

### ISSUE THREAD

**Issue by isabisa** [inaturalist/inaturalist#1483]
I'm developing a WordPress website that allows users to submit observations that are then pushed to the iNaturalist API. I have successfully authenticated, pushed the observation data, and received the ID of the observation from the API. I am completely hung up on pushing a photo with the POST /observation_photos endpoint.

The `multitype/form-data` call is as follows:

    $boundary = wp_generate_password( 24 );

    $body = '';
    $body .= '--' . $boundary . "\r\n";
    $body .= 'Content-Disposition: form-data; name="file"; filename="' . basename($photo_sized) . "\"\r\n";
    $body .= 'Content-Type: ' . $photo_type . "\r\n\r\n";
    $body .=file_get_contents($photo_sized) . "\r\n";
    $body .= '--' . $boundary . "\r\n";
    $body .= 'Content-Disposition: form-data; name="observation_photo"' . "\r\n";
    $body .= 'Content-Type: application/json' . "\r\n\r\n";
    $body .= json_encode(['observation_id' => $inat_id]) . "\r\n";
    $body .= '--' . $boundary . '--' . "\r\n";
    
    $photo_payload = [
        'method' => 'POST',
        'timeout' => 10,
        'headers' => [
            'Authorization' => "Bearer $auth",
            'Content-Type' => "multipart/form-data; boundary=$boundary"
        ],
        'body' => $body
    ];

The resulting $photo_payload array is:

    [method] => POST
    [timeout] => 10
    [headers] => Array
        (
            [Authorization] => Bearer 1c83ea71XXXXXXXXXXXXX
            [Content-Type] => multipart/form-data; boundary=abc
        )

    [body] => --abc
    Content-Disposition: form-data; name="file"; filename="20170816_071116-150x150.jpg"
    Content-Type: image/jpeg
    
    [raw image data]
    --abc
    Content-Disposition: form-data; name="observation_photo"
    Content-Type: application/json

    {"observation_id":"8014211"}
    --abc--

When this is sent to the iNaturalist API via `$post_photo = wp_remote_post('http://www.inaturalist.org/observation_photos', $photo_payload);` it results in a 500 error.

I debugged the HTTP POST with this tool: https://www.posttestserver.com/ and it returned successfully.

The response from `$post_photo = wp_remote_post('http://posttestserver.com/post.php', $photo_payload);` is:

    Time: Thu, 21 Sep 17 15:15:26 +0000
    Source ip: 96.10.225.162

    Headers (Some may be inserted by server)
    HTTP_USER_AGENT = WordPress/4.8.1; http://ecoexplore.dev
    HTTP_HOST = posttestserver.com
    HTTP_ACCEPT = */*
    HTTP_ACCEPT_ENCODING = deflate, gzip
    HTTP_REFERER = http://posttestserver.com/post.php
    CONTENT_TYPE = multipart/form-data; boundary=wdoMBiSuQ7Ou!GHAU*dTZ@0C
    HTTP_CONNECTION = close
    CONTENT_LENGTH = 7908
    HTTP_EXPECT = 100-continue
    REMOTE_ADDR = 96.10.225.162
    DOCUMENT_ROOT = /var/www/html
    REQUEST_SCHEME = http
    CONTEXT_PREFIX = 
    CONTEXT_DOCUMENT_ROOT = /var/www/html
    REMOTE_PORT = 53709
    GATEWAY_INTERFACE = CGI/1.1
    REQUEST_METHOD = POST
    QUERY_STRING = 
    REQUEST_URI = /post.php
    PHP_SELF = /post.php
    REQUEST_TIME_FLOAT = 1506006926.227
    REQUEST_TIME = 1506006926

    Post Params:
    key: 'observation_photo' value: '{"observation_id":"8014211"}'
    Empty post body.

    == Multipart File upload. ==
    Received 1 file(s)
     0: posted name=file
        name: 20170816_071116-150x150.jpg
        type: image/jpeg
        error: 0
        size: 7585
        SHA1: a7577144c4abd121f126ce4c2bbc3b015376fa41
    Uploaded File: http://posttestserver.com/files/2017/09/21/f_15.15.261132167080

(Full results available here: http://www.posttestserver.com/data/2017/09/21/15.15.26838095947)

I believe there is something on the iNaturalist side that is breaking when it receives the image file.

**Comment by kueda** [comment]
Hm, so yes, a 500 means there's a problem we're not handling well on our end. In this case what we're getting from you looks something like

```
{
  "action": "create",
  "controller": "observation_photos",
  "file": "#<ActionDispatch::Http::UploadedFile:0x007ff4103b1cd8>",
  "observation_photo": "{\"observation_id\":\"8014211\"}"
}
```
So the `observation_photo` in your JSON is just being received as a string and not a nested object. Have you tried removing the `Content-Disposition`? I think that's only for data intended to be represented in a file. Something like
```
--abc
Content-Type: application/json

{"observation_photo": {"observation_id":"8014211"}}
--abc--
```

**Comment by isabisa** [comment]
@kueda thanks for the quick response! I tried changing the multipart request to:

    --abc
    Content-Disposition: form-data; name="file"; filename="20170816_071116-150x150.jpg"
    Content-Type: image/jpeg

    [raw image junk here]
    --abc
    Content-Type: application/json

    {"observation_photo":{"observation_id":"8014211"}}
    --abc--

And received this error: `502 Bad Gateway: Incomplete response received from application.`

**Comment by kueda** [comment]
Weird, I think you were formatting your original request correctly, but for whatever reason Rails is not happy with JSON included as part of a multipart request, so if `Content-Type` is `multipart/form-data` it doesn't do any further parsing of `Content-Type` within the parts.  So try something like this:

```
[body] => --abc
Content-Disposition: form-data; name="file"; filename="20170816_071116-150x150.jpg"
Content-Type: image/jpeg

[raw image data]
--abc
Content-Disposition: form-data; name="observation_photo[observation_id]"

8014211
--abc--
```

**Comment by isabisa** [comment]
You sir are a miracle worker!

**Comment by kueda** [comment]
Glad that worked. I have worked the miracle of realizing how un-miraculous Rails is. A dubious power. I've update the docs a bit to add a note about this, many thanks for pointing it out.
