### ISSUE TITLE
Mutiple Active IDs on some Observations

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1491]
Some observations have multiple active IDs from the same user:

https://www.inaturalist.org/observations/8088018

https://www.inaturalist.org/observations/7016576

**Comment by kueda** [comment]
Looks like your standard-issue race condition. This user created the same observation twice within milliseconds of each other from the iOS app:

http://goggia/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-26T22:06:45.781Z',mode:absolute,to:'2017-09-27T22:21:45.781Z'))&_a=(columns:!(_source),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'user_name:samwerts%20%26%26%20controller_action:%22IdentificationsController::create%22')),sort:!('@timestamp',desc))

@pleary, how would you feel about altering [this index](https://github.com/inaturalist/inaturalist/blob/8601c2a9ed152d2780d9c8914a247f875f04c1a1/db/migrate/20151014213826_add_index_identifications_user_id_current.rb#L3) to something like
```
add_index :identifications, [ :user_id, :current, :observation_id ], unique: true
```
In theory all identifications should be unique on those three attributes, and keeping the order like that should preserve the speed of looking up current idents for a user.

**Comment by pleary** [comment]
Couldn't a user have more than one non-current ID on an observation? Maybe it would work if we added taxon_id to the index, but then you're talking about a pretty huge index on 4 columns in a table of 10+million rows.

**Comment by kueda** [comment]
Hadn't thought about that. How about a partial index, e.g.

```
add_index :identifications, [ :user_id, :current, :observation_id ],
  unique: true, where: "current"
```

I *think* that would preserve the performance gains of the original index while preventing these duplicates, though maybe I'm misunderstanding how the original index is being used.

**Comment by pleary** [comment]
I think that would work. I don't have any experience with partial indices (something Mysql doesn't support). I'm trying it out locally, but sounds like it'll work. Since you're only applying the index to rows where `current=t` (I assume this is what `where: "current"` does), then does `current` need to be in the index? We could keep the existing  2 column index, and create a new two column index of just `[ :user_id, :observation_id ], where: "current"`. I'm building some locally to compare the relative sizes

**Comment by kueda** [comment]
Yes, I think that would do it. Might make `index_identifications_on_observation_id_and_created_at` unnecessary if we want to save index space.

**Comment by pleary** [comment]
Seems to be working for me. Looks like adding `:current` to the partial index makes it about 40% larger than if you leave it off (493MB vs 351MB). I think we should leave the other index for now, at least I personally want to know more about how partial indices work. Seems like they'll only index rows where current are true, and we're likely needing an index on `observation_id` for all IDs
