### ISSUE TITLE
Still getting email updates even though I've turned them off

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1492]
Even though I only subscribe to project invites and messages, I'm still receiving daily emails showing new observations from users that I follow. Another user in the Google Group is experiencing something similar: https://groups.google.com/forum/#!topic/inaturalist/bRMYmOJN4MM

**Comment by tommydevitt** [comment]
Yes, having the same problem.

**Comment by kueda** [comment]
There is no preference for not receiving updates about new observations from people you follow. Presumably if you didn't want those updates you would not follow them. That's the only effect following has. Or is there something broken that I'm missing here?

**Comment by kueda** [comment]
Ah, I guess you still get those updates on your dashboard. So is what you're asking for here to just not receive updates about new observations from people you follow in your daily updates email?

**Comment by tommydevitt** [comment]
Yes, that's correct. I thought that checking the "Don't send me email" would have turned that off. I can easily stop following people though if that's the only solution.

**Comment by kueda** [comment]
@tommydevitt, that sounds like a slightly different issue. Are you https://www.inaturalist.org/people/tommyd? If so, I can't see any emails we've delivered to the email address associated with that user account, so it seems like the `Don't send me any email!` preference is working on our end. Is it possible you have a different account that you're getting updates for?

**Comment by kueda** [comment]
I'm going to close this since with the new user preferences providing more control over what gets into the daily update email I think the original issue here has been fixed. If it hasn't, please re-open. If there really is a problem with the `Don't send me any email!` preference please start a new issue. So far I don't have any direct evidence that that's happening.
