### ISSUE TITLE
clearing location on obs/edit sets location to 0,0 rather than null

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1496]
e.g. https://www.inaturalist.org/observations/8221732/edit the clear button is:
<img width="383" alt="screen shot 2017-10-08 at 8 02 54 am" src="https://user-images.githubusercontent.com/598026/31317966-1ebb26c0-abff-11e7-855d-3811c0f62117.png">
which results in:
<img width="402" alt="screen shot 2017-10-08 at 8 03 20 am" src="https://user-images.githubusercontent.com/598026/31317970-2dde59d8-abff-11e7-8b77-8d1414c4eaa2.png">

**Comment by pleary** [comment]
fixed on master branch, and is on staging. We just need to deploy to production
