### ISSUE TITLE
Bug in publishing observation pictures to GBIF?

### ISSUE THREAD

**Issue by peterdesmet** [inaturalist/inaturalist#1499]
_Note: this is an issue regarding the publication of research-grade observations to GBIF. Let me know if I should submit it elsewhere._

I noticed that pictures associated with my observations are not published on GBIF. Compare for example https://www.inaturalist.org/observations/7105924 with https://www.gbif.org/occurrence/1580508424.

While other (including recent) observations still have pictures: https://www.gbif.org/occurrence/1668889513

Any idea what might be causing this?

**Comment by kueda** [comment]
We had a bug in which CC0 images were getting omitted but it should be fixed by 9ee5c3a9ee83aa291bb89a66afc0562d3069da32

**Comment by peterdesmet** [comment]
Thanks for the fix! How often is the data published to GBIF i.e. when can I see if the issue has been resolved?

**Comment by kueda** [comment]
@dnoesgaard, since you were the one that first brought this cc0 image question to my attention, can you comment on how frequently GBIF ingests iNat's DwC-A? I was under the impression it was monthly.

**Comment by dnoesgaard** [comment]
At the moment it should be every week, but we can do it as often as you like. I just triggered a crawl now. You could also trigger the crawl yourself using an [API call](https://www.gbif.org/developer/registry#datasets) (http://api.gbif.org/v1/dataset/{UUID}/crawl).

How often is the DwC-A regenerated?

**Comment by dnoesgaard** [comment]
@peterdesmet, fwiw, I see my own CC0 images from iNat in GBIF now.

**Comment by kueda** [comment]
We generate the GBIF DwC-a every Thursday.

**Comment by peterdesmet** [comment]
Thanks! Indeed resolved
