### ISSUE TITLE
Dashboard Agree Button Consistency

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1500]
Confusion has arisen regarding the "Agree?" button in the dashboard. Making the Agree button consistent with the ob detail screen would most likely remedy this. Here's a screenshot of that button just for reference:

![image](https://user-images.githubusercontent.com/11527994/31515871-9cf0da9a-af4b-11e7-9659-ea9ff058c136.png)

We could add the Compare button next to it for ultimate consistency, but I kinda feel like more involved interactions should be limited to ob detail screen itself. The dashboard tends to be for quick and simple interactions. Feel free to convince me out of that. 

Also noticed the "Remove" button is inconsistent with the ob detail screen where users have the option to edit or withdraw their IDs. We can either get rid of that button entirely or replace it with "Withdraw" and "Edit" buttons with the same style. Remove can have an X icon and Edit can have the pencil icon. Kinda feel like this is advanced functionality that should be limited to the ob detail screen, but I can see how it would be handy here. 

![image](https://user-images.githubusercontent.com/11527994/31516229-b772cb66-af4c-11e7-819a-30c6d88fc400.png)

**Comment by tiwane** [comment]
I "agree" that the button should not have a question mark, and that more involved interactions should be relegated to the Obs detail screen.

**Comment by joellebel** [comment]
Also, let's figure out if we want the "Widthdraw" and "Edit" buttons or simply an "Agreed" state and folks can do any further Agree editing on the ob itself.

"Widthdraw" and "Edit" buttons are good for quick fixes to mistakes, if the user does one of these processes and goes back to the dashboard will be there be caching issues? By caching issues, I mean the "Agree" button will still be showing. @kueda ?

**Comment by kueda** [comment]
@wykhuh, check out https://www.inaturalist.org/home. You probably won't see anything there since it doesn't seem like you're following anyone and haven't made any observations, comments, or IDs. Try using iNat for a week, e.g. add some observations, leave some comments, follow some people, and you should have some updates there. It'll also help you understand these issues a bit better. I guess you could do this with test accounts locally, but it always helps to have the experience in a production environment.

**Comment by kueda** [comment]
Wow, this issue is old. FWIW, the dashboard is due for an overhaul, hopefully early in the coming year, but if anyone wants to address the issues raised here, I think the clear todos on the dashboard are:

- [ ] Change `Remove` to `Withdraw`
- [ ] Change `Agree?` to `Agree`
