### ISSUE TITLE
Drag and drop on Upload page is buggy in Safari

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1506]
After dropping one card on another in the Upload page, the window scrolls down to the bottom of the page instead of staying where you are. This doesn't happen in Firefox and Chrome.

**Comment by tiwane** [comment]
Ah ha! I tried this a bunch of different ways, with different adblockers and extensions installed and uninstalled. None of that made a difference. 

However, adding a species is what affects things. I can drag and drop cards onto each other fine _until_ I add a species name to an observation - either with suggestions or when I type it in. Once I do that, dragging cards onto each other results in the page scrolling down to the bottom.

@kueda can you replicate?

**Comment by kueda** [comment]
I can replicate but I haven't been able to figure it out. To be slightly more specific, when you add a taxon to any card in Safari, dragging any card onto any other card causes the drag-and-drop area to scroll to the bottom.

**Comment by tiwane** [comment]
Not seeing this behavior anymore, so will close the issue.
