### ISSUE TITLE
Give Username Error During Sign Up a New URL

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1507]
Looks like when folks try to sign up with a username already in use they go this url: https://www.inaturalist.org/users

See below screenshot for reference:

![image](https://user-images.githubusercontent.com/11527994/31640222-dd73d600-b291-11e7-8b5a-0c5229caf009.png)

Can we make this url https://www.inaturalist.org/username_taken or something unique? This will help us better track successful sign ups. Plus, if we find folks are quite often having username trouble, we work can on an alternative solution, such as offering username suggestions.

**Comment by kueda** [comment]
I don't think using a new URL would be the best way to do this. If we want to track this at some point, maybe add something to logstash or airbrake.
