### ISSUE TITLE
User who added conservation status should be listed as source if there isn't an authority

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1509]
Currently looking like

<img width="960" alt="screen shot 2017-10-18 at 4 50 01 pm" src="https://user-images.githubusercontent.com/22691/31747890-77d56be4-b424-11e7-84bd-65db29b38928.png">

at https://www.inaturalist.org/taxa/4777-Gymnogyps. And a rider: updating conservation status should re-index the taxon.

**Comment by pleary** [comment]
We seemingly don't currently record the user_id that added a conservation status. There's a `user_id` column in the `conservation_statuses` table, but there's only 252 records out of 140980 that have a user_id, and they're all Scott. Shall we start to populate the user_id when conservation statuses are manually added? There's not much we can do with the existing statuses that don't have user_ids

**Comment by carrieseltzer** [comment]
Yes, I noticed that we've only recorded Scott too. We should just populate it going forward, but hopefully with #767 in place most people will choose to add a new authority if possible.

**Comment by kueda** [comment]
This is sort of working, but there's some [weirdness](https://github.com/inaturalist/iNaturalistAPI/commit/dafa0800c9f3936e59acaeece0972c9d650e5b39) with the iNat API, associate loading, and async/await methods that I still don't entirely understand (TL;DR, conservation statuses aren't getting returned with their user, in taxon api responses, even though they are for me locally).

**Comment by kueda** [comment]
IMO, remaining problem was not well-articulated or reproducible, so I'm closing again.
