### ISSUE TITLE
Support ident_user_id param on obs search

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1512]
Talking about this with @kueda and he suggested making a URL like this one work: https://www.inaturalist.org/observations?ident_user_id=1234

- [x] https://www.inaturalist.org/observations?ident_user_id=1234 should return observations identified by user 1234, regardless of whether the ID is current
- [ ] https://www.inaturalist.org/observations?ident_user_id=1234&ident_taxon_id=5678 should return observations where user 1234 added an ID of taxon 5678

**Comment by tiwane** [comment]
johnnybirder also suggests "it would be great if that URL-based search could also incorporate a function where you can search for observations that you reviewed but not added an ID. Maybe something like reviewed=true&ID=NULL or something like that?"

**Comment by kueda** [comment]
Updated the desc to make it a bit more explicit. Not sure I understand Johnny's use case. Marking an observation as reviewed means you ID'd it or you don't want to ID it. If you think you might ID it later, don't mark it as reviewed.

**Comment by tiwane** [comment]
I suppose this would be better for Identify. I think he wants to go back through observations he's marked as reviewed because he wants to ID them now that he knows more.

**Comment by joellebel** [comment]
I can see how this would be great for the Identify too. However, I personally, wouldn't mind a filter in Obs Search under my "My Observations" labelled "My Identifications" and it would only show obs I've left an ID on.

**Comment by johnnybirder** [comment]
Thanks Tony - spot-on on the explanation for ID=NULL. Another example: in early days I've marked many observations as "reviewed" without adding IDs. But now with so many new iNatters onboard, there is a need to review reviewers' IDs as well. So basically, I want to review the ID=NULL obs and their IDs, and make sure I follow them from here on forward. Hope that's clear.

**Comment by tiwane** [comment]
This has been implemented.
