### ISSUE TITLE
API: Identification withdraw/restore

### ISSUE THREAD

**Issue by kgarsuta** [inaturalist/inaturalist#1514]
There isn't a documented way to "restore" an Identification through the API. Is it correct to assume that DELETE is synonymous to "withdraw"? Could you point me to the documentation if I missed it? Otherwise, is this something you plan to implement?

**Comment by kueda** [comment]
`DELETE /v1/identifications/:id` will delete that observation forever. It's the same as editing the ID on the web and deleting it, not withdrawing it. To withdraw, you `PATCH /v1/identifications/:id` and set `current` to `false`. To restore, do the same and set `current` to `true`.

**Comment by kgarsuta** [comment]
Thanks @kueda appreciate it.
