### ISSUE TITLE
New icon for Improving label

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1519]
I think these need their own icons so they don't get confused. Here's one idea...

This uses the fontawesome anchor. Not the perfect icon, but I'm not sure there'a perfect icon to describe...

![image](https://user-images.githubusercontent.com/11527994/32068891-697d5eee-ba3c-11e7-965d-e632f7da657b.png)

# Dir 1:

![image](https://user-images.githubusercontent.com/11527994/32068835-39b382ba-ba3c-11e7-86e8-5cc37f99087f.png)

Also, thought about using the number 1, but don't think that would translate well to other languages. 

# Dir 2:

I experimented with incorporating it into the text and now an info icon can fit nicely. 

![image](https://user-images.githubusercontent.com/11527994/32069217-4e941978-ba3d-11e7-910d-4a2d388d3acb.png)

# Lastly 

Can we bring all icons in these labels about 2-3px closer to their labels. (including Maverick)

**Comment by kueda** [comment]
Personally I like the trophy icon for "Improving" and I feel like we need a new icon for "Leading" that indicates that they're out on the edge, maybe an icon of a runner like http://freeflaticons.com/wp-content/uploads/2014/09/runner-copy-1411788899k84gn.png or something. I like the current layout b/c it scans well, you can just look down the right side to get a sense of the categories.

**Comment by tiwane** [comment]
I like the runner for leading.

**Comment by joellebel** [comment]
Here's a look at not making the header of the IDs green. Maybe that's what's bothering me. It's making all IDs seem overly special. When I originally designed it, I thought there was only going to be one label, not two. 

![image](https://user-images.githubusercontent.com/11527994/32070106-1023a804-ba40-11e7-8bc8-dfcda13625a4.png)

**Comment by joellebel** [comment]
Runner could definitely work. Will try it.

**Comment by joellebel** [comment]
## Leading: Runner with lines

![image](https://user-images.githubusercontent.com/11527994/32252071-f65c8a34-be50-11e7-9eeb-d921d2b242cc.png)


## Leading: Runner 

![image](https://user-images.githubusercontent.com/11527994/32252191-89785b40-be51-11e7-8294-b0a0cc5183bd.png)


## Improving: Nerd Glasses

Not too nuts about this, but was just curious

![image](https://user-images.githubusercontent.com/11527994/32252237-bcd8bf3e-be51-11e7-9930-c66c6464073c.png)


# Gray BG 

I also think the bg should no longer turn light green. It's too much. Here's my preference for icons and BGs. I'm still not totally sold on the trophy, but I think it works. I'm also not sold on the fact that we need to show both the Improving and Leading labels either, but if I'm the only one, that's fine. 

![image](https://user-images.githubusercontent.com/11527994/32252696-d5a5a9bc-be53-11e7-8465-95e1c691407c.png)

**Comment by kueda** [comment]
No opinion on the header background color, I like the runner with lines for the Leading icon.

**Comment by tiwane** [comment]
I kinda like the green background, but am fine with grey.

**Comment by joellebel** [comment]
Ok. Cool. If no one else has a strong argument against the runner, I'll prep the icon for dev.

**Comment by joellebel** [comment]
Ok. Ok. I've had a slight change of mind now that I think I understand what a Leading ID is or could be. Why don't we do this...

![image](https://user-images.githubusercontent.com/11527994/32682336-e4f00e08-c628-11e7-97b6-57a7dcba00b5.png)


Keep the background color for Improving Maverick IDs since IMO they are slightly more important. Leading ID bg stays gray, because it's only possibly improving and/or just directions the CID could go. 


I also experimented with this, but then Leading doesn't look tappable and people might miss the info blurb...

![image](https://user-images.githubusercontent.com/11527994/32682437-89b3f288-c629-11e7-9ccf-1196b502f0a7.png)

**Comment by joellebel** [comment]
and here is Leading in blue, just for kicks...

![image](https://user-images.githubusercontent.com/11527994/32682489-d68cdcdc-c629-11e7-977f-38203702ace2.png)

**Comment by kueda** [comment]
Fine with that, but dislike the blue and black icons.

**Comment by joellebel** [comment]
Ya, I think I prefer the green for Leading...

![image](https://user-images.githubusercontent.com/11527994/32742815-5649f70c-c85f-11e7-867c-3191d367f0c5.png)

If no one else, has any comments, I'd say this is ready for the oven. I'll put the icon on dropbox and let you know where it is.

**Comment by joellebel** [comment]
@kueda the leading icon is ready to go and is on dropbox here: 
Design > Universal Assets > icn_leading_id.svg

Doesn't look like any attribution is necessary: https://thenounproject.com/icon/61513/
