### ISSUE TITLE
Prevent message and journal composition pages from being closed accidentally

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1520]
Can we make the Message and Journal composition pages like the Add Observations page, where you'll get a warning if you close its tab?

**Comment by kueda** [comment]
Can you clarify exactly what you want here? Should the popup be exactly the same as the one we're using at https://www.inaturalist.org/observations/upload? Should it appear only if you've edited / added text to the title and body?

**Comment by tiwane** [comment]
I'm OK with the pop-up being the same, and it should only appear if one has edited or added text to the title or body.

**Comment by tiwane** [comment]
Yup! Thanks.
