### ISSUE TITLE
KML Downloads only downloading the first page of the file.

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1523]
Rather than downloading the entire results of a search, downloaded KMLs seem to only contain the first page or so of the KML. For example, a KML download from [this search](https://www.inaturalist.org/observations?nelat=37.484038&nelng=-122.1153741&place_id=any&swlat=37.451938&swlng=-122.15611189999998&verifiable=any) returns 30 observations but the search has 718.

**Comment by kueda** [comment]
Not a bug, that's just the way it works. We used to have a KML with a "Network Link" that would dynamically load more data from iNat when viewed in Google Earth, but I think it ended up being more buggy. If this person wants all results from the search they should just export CSV. IMO, we should remove that KML link.
