### ISSUE TITLE
oauth login goes to https://www.inaturalist.org/messages/count

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1528]
I use oauth with Google and this morning logging in brought me to https://www.inaturalist.org/messages/count instead of the dashboard. See screenshot.

<img width="1376" alt="screen shot 2017-11-03 at 8 25 47 am" src="https://user-images.githubusercontent.com/7501183/32373682-d80b0480-c070-11e7-8786-c2198026f198.png">

Less savvy users will be confused.

Using Safari Version 10.1.2 (10603.3.8) on OS 10.10.5.

**Comment by kueda** [comment]
Yeah, this is a pretty strange issue that I've only seen in Safari. @pleary, any thoughts on this?

**Comment by kueda** [comment]
Ok, I'm going to assume this is fixed. Please re-open if it's not.

**Comment by kueda** [comment]
@carrieseltzer, do you know if this is still happening?

**Comment by carrieseltzer** [comment]
I don't use oauth anymore (or Safari much either), so I haven't experienced it. However,  I had this vague recollection that someone else reported it in the last couple of months, but I can't find mention of it on the forum.

**Comment by kueda** [comment]
Ok, I'm going to assume / hope it's fixed. Please re-open if you encounter more folks experiencing this.
