### ISSUE TITLE
Taxon Curators

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1532]
- [x] TaxonCurator belongs to a taxon and a user
- [x] Taxon and User have many TaxonCurators
- [x] TaxonCurators must belong to a complete taxon
- [x] TaxonCurators get destroyed when a taxon becomes not complete
- [x] Admins can create/destroy taxon_curators (UI on user profiles or users/curation)
- [x] Display taxon_curators on taxon pages
<img width="1187" alt="screen shot 2017-11-05 at 11 20 24 pm" src="https://user-images.githubusercontent.com/598026/32429565-028d97e8-c280-11e7-99e1-5d578e27d5f1.png">

- [ ] Only taxon_curators (or admins but not other curators) can:
  - [ ] graft to the complete taxon or its descendants
  - [ ] edit the complete taxon or its descendants
  - [ ] commit taxon changes where the taxon_change.taxon or one of the taxon_change.taxon_change_taxa are the complete taxon or its descendants
<img width="525" alt="screen shot 2017-11-05 at 11 26 54 pm" src="https://user-images.githubusercontent.com/598026/32429739-d561c86a-c280-11e7-8e19-4897ccf4edb1.png">

**Comment by kueda** [comment]
Technically it looks fine, but I want to see something written on how we choose curators for specific taxa, what happens when taxon curators can't agree, and what the process is for effecting changes to taxa under the dominion of taxon curators.

**Comment by loarie** [comment]
Ok - I'll work on the squishier side of this if you work on the functionality side

**Comment by loarie** [comment]
Re: our conversation about descendant-ranks, I added https://github.com/inaturalist/inaturalist/issues/1535 

This issue would be modified such that the grafting/editing restrictions stop at the descendant rank (ie for Proteaceae to genus, only the taxon_curator can graft to Proteaceae or edit the family/genus, but any curator can graft to the genus or edit sp/ssp)

**Comment by loarie** [comment]
I tested this and it looks good. One bug and one suggestion:

Bug: should be able to graft within a complete taxon clade if admin or curator but can't. To reproduce:
1. Make taxon 33117 complete at rank species
2. log in as admin
3. create a new ssp Basiliscus kuedii with parent Basiliscus
should not raise 'Ancestry includes the complete taxon <Taxon 33117: Genus Basiliscus>. Contact the curators of that taxon to request changes.' error, but does

Suggestion: Can we float the text to the right of the profile pic rather than below?
<img width="414" alt="screen shot 2017-11-14 at 1 52 20 pm" src="https://user-images.githubusercontent.com/598026/32808686-c6fa198e-c948-11e7-924d-ae8907b9bc63.png">

**Comment by loarie** [comment]
also looks great

**Comment by loarie** [comment]
@kueda - even for locked taxon pages we need to allow general curators access to edit:
1) conservation statuses
2) wikipedia article links (optionally?)

what's your preferred method for making this happen? (ie allow taxa/edit but grey out certain fields, make separate UI for cons statuses, etc.)

**Comment by kueda** [comment]
I'd prefer to allow editing of descendants of complete taxa but disallow changing the parent. Are there other attributes of complete descendants that general site curators shouldn't be able to change?

**Comment by loarie** [comment]
Can we also disable the rank and concept_status fields for taxa falling under a complete taxon (ie the taxon and its descendants down to complete_rank)?

**Comment by kueda** [comment]
Ok, so for complete taxa and their descendants, the TaxonCurators should be able to edit everything but general site curators

- [ ] cannot edit rank
- [ ] cannot edit is_active
- [ ] cannot edit complete
- [ ] cannot edit complete_rank
- [ ] cannot edit parent / ancestry (i.e. can't move the taxon around the tree)

**Comment by loarie** [comment]
correct (and since currently no one except admins can edit taxon.name thats implied and as desired)
