### ISSUE TITLE
Add Pupa as life stage for Coleoptera

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1536]
Currently Coleoptera has only Egg, Larva, and Adult as available life stages in Annotations. Can Pupa be added to it?

**Comment by kueda** [comment]
You can do this as an admin on the site. Go to https://www.inaturalist.org/controlled_terms, edit Life Stage / Pupa, and add Coleoptera as one of the taxa associated with that term.

**Comment by tiwane** [comment]
Cool, thanks.
