### ISSUE TITLE
identifications/species_counts broken

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1537]
identifications/species_counts seems to be broken, here's the URL from the example in the API docs
http://api.inaturalist.org/v1/identifications/species_counts?current=true&order=desc&order_by=created_at&taxon_of=identification
which yields an error

Possibly related to the new pagination changes?

**Comment by loarie** [comment]
ugh - sorry for making this issue in the wrong repo and assigning the wrong person.

**Comment by kueda** [comment]
No worries, just trying to save Patrick some bother while he's probably cooking dinner. Should be fixed by https://github.com/inaturalist/iNaturalistAPI/commit/845c2d357c988b020a014559b7e71fafda87b5ff, just need to deploy.
