### ISSUE TITLE
Slideshow cutoff on Windows

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1542]
The slideshow renders well in all browsers on Mac, but seems to cutoff in all browsers on Windows 7 & 10 (see below). @pleary is there an easy fix for this?
Windows 10 Chrome
![unnamed-5](https://user-images.githubusercontent.com/598026/32904329-044e1c54-caac-11e7-9fb9-1175ff14e795.jpg)
Windows 10 Edge (Explorer replacement)
![unnamed-4](https://user-images.githubusercontent.com/598026/32904345-09fcd190-caac-11e7-9af8-430adbed333a.jpg)
Windows 10 Firefox
![unnamed-3](https://user-images.githubusercontent.com/598026/32904349-0b00e608-caac-11e7-873e-240de154b7d5.jpg)
Windows 7 Chrome
![unnamed-2](https://user-images.githubusercontent.com/598026/32904351-0cb31340-caac-11e7-9084-b7bebfff0cfb.jpg)
Windows 7 Explorer
![unnamed-1](https://user-images.githubusercontent.com/598026/32904358-0f106160-caac-11e7-9227-25837f249b4d.jpg)
Windows 7 Firefox:
![unnamed](https://user-images.githubusercontent.com/598026/32904384-16ef3d3e-caac-11e7-960f-20a5c7b7c380.jpg)

**Comment by pleary** [comment]
Chrome 62.0.3202.94 on my Mac:
<img width="1658" alt="screen shot 2017-11-20 at 1 40 12 pm" src="https://user-images.githubusercontent.com/48566/33035293-98612fcc-cdf8-11e7-9e0c-2d2b2eb9a4e2.png">

I don't think this is specific to Windows. The slideshow was designed to be displayed on a 16:9 ratio screen (specifically 1920x1080 television screens). We could tweak the design to work on wider screens, but just keep in mind that we use the same ratio regardless of the screen. So if we optimize it for wider screens, it'll look worse on 16:9 screens. Alternatively, it should look OK if the user uses fullscreen, or make the browser narrower

**Comment by loarie** [comment]
thnx, let me ask James...
