### ISSUE TITLE
Language Picker Designs

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1548]
# Round1

We currently have browser detection, but for the rare instances it doesn't work, it's important to give the user a language picker option. Please keep that in mind when looking over these. 

## Direction 1: Dropdown

This has a dropdown that is always present in the lower right. I gave it a little "language" icon so it a little more noticeable. See below...

![image](https://user-images.githubusercontent.com/11527994/33031689-99b77228-cde4-11e7-8d9c-df80e48b3813.png)

Note: If a logged in user changes the language from this dropdown, the language preference in settings should be updated

## Direction 2: Footer Band

Here's a more noticeable version. I would recommend this is only necessary when the user is logged out. I think it's adding some unwanted noise to the footer when logged in.

![image](https://user-images.githubusercontent.com/11527994/33032803-f468ab58-cde7-11e7-9f76-ac98817c1d14.png)

## Direction 3: Logged Out / Header

Here's an idea that would occur only when the user is logged out. This way anyone who is new to the site can quickly change the language without much fuss for the rare occasions the browser detection doesn't work. 

I am a little concerned it's detracted from the Log in/Sign Up button which is pretty important. 

Feel free to check out user stats here... Our biggest audiences are Spanish and English speaking... https://analytics.google.com/analytics/web/#report/visitors-language/a248105w5541749p5717755/%3Fexplorer-table-tableMode.selected%3Dpie%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.rowStart%3D0%26explorer-table.rowCount%3D25/

![image](https://user-images.githubusercontent.com/11527994/33033119-ffaa3788-cde8-11e7-87d7-b7a7199d72f5.png)

**Comment by joellebel** [comment]
...and here's what Direction 3 looks like with the longest language in it. This way you can get an idea of spacing. This is on a 13in macbook.

![image](https://user-images.githubusercontent.com/11527994/33042913-20c07ae8-ce09-11e7-91fe-892fd06f0314.png)

**Comment by kueda** [comment]
I thought we agreed on the footer already, no? I'm for 1 or 2, don't have a preference so please choose one.

**Comment by loarie** [comment]
I like Dir1

**Comment by joellebel** [comment]
oh. yes. You're right. We did decide on a footer, but never really talked about having a separate scenario for if the user is logged out. Ok Let's go with Direction 1. I'll write up some specs now!

**Comment by joellebel** [comment]
# Visual Specs

* Can we use the same style as this button with the following changes...
![image](https://user-images.githubusercontent.com/11527994/33048224-6800307c-ce1f-11e7-9111-05f63ad3367d.png)

* Button bg is #484848
* Text is white
* icon is inat green and is from the ionicons (I already splained it's location)
* Can you make the icon a little closer to the text like it is here: 


I may want to increase the text size to 16px, but first want to see if we can get away with this

**Comment by joellebel** [comment]
Looking fab. Two minor things... 

* If we wanted to get super picker the lang. picker button could go one pixel to the left so it aligns with the CAS logo

![image](https://user-images.githubusercontent.com/11527994/33158116-d0a9b946-cfcc-11e7-952c-c36b6433e752.png)


* Can we make the border of the button #8D8D8D ?
