### ISSUE TITLE
Include iNat photo ID as a column in the SimpleMultimedia DwC-A extension file

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1553]
It's sort of already there for all the photos that already resolve in the photo URL, but it would make processing easier for some of our partners. Probably should check with GBIF to confirm that adding additional fields won't screw up their processing.

**Comment by gvanhorn38** [comment]
I can definitely parse the inat photo ids from the url. This is fine if the url will always have the photo id in it. However, explicitly adding a photo id column might provide a bit of future-proofing in case the way you guys construct image urls does change?
