### ISSUE TITLE
Overlapping page features in journal posts in Safari

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1554]
The left rail displays behind the body of journal posts in Safari, no matter the window size. See screenshots of https://www.inaturalist.org/projects/city-nature-challenge-2017-washington-dc-metro-area/journal/11693-we-re-getting-ready-for-the-2018-city-nature-challenge-april-27-30

<img width="1391" alt="screen shot 2017-11-28 at 2 12 43 pm" src="https://user-images.githubusercontent.com/7501183/33339202-6e1976c6-d446-11e7-9eb9-c3f632ff91f3.png">
<img width="660" alt="screen shot 2017-11-28 at 2 12 50 pm" src="https://user-images.githubusercontent.com/7501183/33339203-6e299aba-d446-11e7-9b9c-7e98d1b60549.png">

I see it looks fine in Chrome. I guess Safari is the problem child of browsers, like in #1528 

I'm using Safari Version 10.1.2 (10603.3.8)

This has been happening for weeks if not months.

**Comment by tiwane** [comment]
Hi Carrie,

In Safari 11.0.1 (13604.3.5) this isn't happening to me. I posted a test post with the same title and text as yours and it didn't happen either (it's now deleted).

Would you be able to upgrade and try again? Does it happen for any journal post, or just ones with long titles?

**Comment by carrieseltzer** [comment]
Ugh, sorry! I see it works fine on my personal computer. It's a safari 10.1.2 issue. My work laptop is locked in on 10.1.2 because it is running OS 10.10.5. I'll close this issue.

But for clarification, it's an issue viewing any journal posts, no matter who wrote them or the title length.
