### ISSUE TITLE
Allow all of user's subscriptions to be viewable in the Dashboard

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1561]
Currently only about 4 on one's subscriptions are viewable in the list on the right-hand side of the Dashboard are viewable. Would it be possible to have a small scrollable window where the user can see all of his/her subscriptions?

**Comment by kueda** [comment]
Not really. You can potentially be subscribed to an unlimited number of places, taxa, people, etc., so we're always going to have to abbreviate what we show on the dashboard itself. However, you can see them all by clicking the gear icon next to the "Subscriptions" header on the dashboard. Does that meet your need.

**Comment by tiwane** [comment]
Closing this as we're revamping subscriptions.
