### ISSUE TITLE
Wrong Icon for IDs in Dashboard Timeline

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1562]
When someone has a moment, can they update this icon with our current ID icon which is that upside down tag thingy. tnx. 

![image](https://user-images.githubusercontent.com/11527994/33637126-0b6a42a6-d9d4-11e7-96d8-2d25dd8c11b1.png)

**Comment by kueda** [comment]
We use the same icon for all "activity" which includes identifications, comments, mentions, etc. Not sure why we chose that bookmark icon, but do you still want to use the identification icon? Maybe a speech bubble would be more appropriate?

**Comment by joellebel** [comment]
Reeeahheeheeelly? Oh. Jeez. I never noticed that. It would be nice if the IDs got an ID icon and mentions and comments got the speech bubble. However, if that's a huge pain, I'd say we just get rid of them.
