### ISSUE TITLE
Ob detail timeline labelling needed for inactive taxa and withdrawn IDs

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1563]
Looks like the designs for inactive taxa and withdrawn IDs never made it to production. They can be found here: http://inaturalist.github.io/design/Specs/Web/Observation_Detail/Observation_Detail_v01_r07/#artboard26

For reference...

![image](https://user-images.githubusercontent.com/11527994/33639044-4f8476a0-d9de-11e7-9be9-2a4f3f6d001e.png)

This will prevent the confusion found in this ob, for example: https://www.inaturalist.org/observations/9023686

**Comment by kueda** [comment]
So both of the above are withdrawn but the second is of an inactive taxon? For the record, the confusion at https://www.inaturalist.org/observations/9023686 was due to 1) the vision API returning inactive taxa (see https://github.com/inaturalist/iNaturalistAPI/issues/96) and 2) the Android app not displaying when taxa are inactive at all, so I agreed to a version of _Limacia cockerelli_ that I didn't mean to.

**Comment by joellebel** [comment]
The Inactive Taxon treatment is of an inactive taxon. Does it look like a Withdrawn, Inactive taxon? 

Question: Does this mean there is a third state which is a withdrawn, inactive taxon? If so, I should design that then.

**Comment by kueda** [comment]
There are withdrawn identifications of inactive taxa. I think the strikeout style should just be for withdrawn IDs. That way it's obvious when an identification is withdraw, when it's of an inactive taxon, and when it's both.

**Comment by joellebel** [comment]
Ya. Makes sense. Didn't realize there were three states. BRB.

**Comment by joellebel** [comment]
Ok. Here's what I'm thinking...

![image](https://user-images.githubusercontent.com/11527994/33692543-aa822e8e-daa2-11e7-8fc6-32d8ab843d63.png)

![image](https://user-images.githubusercontent.com/11527994/33692546-aee82dd4-daa2-11e7-83e0-680235fe4a28.png)


![image](https://user-images.githubusercontent.com/11527994/33692551-b42383ac-daa2-11e7-8d9b-420c6f795e9e.png)

**Comment by kueda** [comment]
I think that's fine, but keep in mind that you're going to end up squeezing the vision decoration in there, so your header might end up reading

`pleary selected a computer vision suggestion | ID Withdrawn | Inactive Taxon | 4mo`

If that's what we want, we probably need some plan for wrapping. IMO, we don't *really* need the explicit "Withdrawn" label. I think the strikeout conveys that pretty well.

**Comment by joellebel** [comment]
Thought I had the design for long header text published somewhere, but I guess I didn't. Here's what happens:

![image](https://user-images.githubusercontent.com/11527994/33693050-5f96bac2-daa5-11e7-8413-c2b360931c85.png)

The "pleary suggested..." text should have a line height of 18px

I think we definitely need to tell the user why something is crossed out so it's clear that the IDer has elected to withdraw the ID him or herself. Plus, all the other timeline states have notations.

**Comment by joellebel** [comment]
ok. Will design the Android states based on these. We need all three of these states, right? Referring to this issue: https://github.com/inaturalist/iNaturalistAndroid/issues/442
