### ISSUE TITLE
Use ham! and spam!

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1564]
Currently send things to Akismet and use their opinion about whether or not something is spam, but we don't try to provide training data about false positives and negatives. Maybe we'd get better performance if we reported training data, so let's

- [x] call `ham!` for a record when a spam flag on that record is resolved
- [x] call `spam!` for a record when a spam flag is added by a user and not because of Akismet

**Comment by pleary** [comment]
fixed in #1585
