### ISSUE TITLE
"Wild" filter ineffective in Identify

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1579]
From bouteloua:

On Identify, when you click the Wild box in the filters, it adds "wild=true" to the URL. Captive/cultivated observations still appear in the search results.
https://www.inaturalist.org/observations/identify?quality_grade=casual&photos=true&wild=true

On Observations, when you click the Wild box in the filters, it adds "captive=false" to the URL. Captive/cultivated observations are properly excluded.
https://www.inaturalist.org/observations?captive=false&photos&place_id=any&quality_grade=casual&subview=grid&verifiable=any

**Comment by kueda** [comment]
I'm just going to get rid of the "Wild" checkbox in Identify. It doesn't really make any sense as a checkbox since an observation can't be both captive and wild.

**Comment by tiwane** [comment]
Sounds good to me.
