### ISSUE TITLE
Include user ID and photo position as optional values in DwC-A

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1583]
Related to #1553, mostly for @gvanhorn38. Also, make a new DwC-A for grant that includes all these as well as *only* licensed obs and images (we include references to all images in the GBIF DwC-A).

**Comment by gvanhorn38** [comment]
More details about why this useful:
- The user id is convenient when constructing dataset splits from the gbif archive and we want to ensure that all of a user's images fall on one side of the split. 
- The "primary image" for an observation is most likely to be the image that contains the subject. Additional photos for an observation sometimes are habitat shots.

**Comment by kueda** [comment]
If I ensure that every photo row in the file is ordered like it is on the website, would that meet your ordering need? I.e. not specifying the position of the photo explicitly, but implying it by the position of its row in the file relative to its core observation ID?

**Comment by gvanhorn38** [comment]
Yup, that would work perfectly.
