### ISSUE TITLE
@mention not working for some names when they contain same words as other @mentions in same comment

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1587]
Tony Rebelo found a weird edge case where he @mentioned three users: @outramps @outrampsjenny and @outrampsmarge in a comment on a journal post and what happens is that for the latter two, only @outramps is blue, so @outramps is mentioned three times. The "jenny" and "marge" parts are black. https://www.inaturalist.org/posts/13475-over-and-out-for-2017#activity_comment_1263188

<img width="549" alt="screen shot 2018-01-02 at 2 23 15 pm" src="https://user-images.githubusercontent.com/15896181/34502495-8e14bf92-efc8-11e7-825e-08bf5023fc9f.png">

This doesn't happen if you just put @outrampsjenny, so I guess there's a weird thing going on where if one part of an @mention is used, you can't @mention another user whose username begins with the same segment that's already been mentioned?

**Comment by pleary** [comment]
deployed to staging, and this looks fixed there. Will deploy to production soon
