### ISSUE TITLE
Error uploading the observation due to timezone

### ISSUE THREAD

**Issue by mutolisp** [inaturalist/inaturalist#1588]
Hi, 

One user uploaded a photo taken in the early morning via web interface, but the system told him "Observed on can't be in the future". But the timestamp is correct, and timezone is GMT+8 (CST). We're just wondering if it is the timezone problem.

This bug refer to [facebook iNaturalist Taiwan user group](https://www.facebook.com/photo.php?fbid=10210198000258297&set=gm.162902067811476&type=3&theater&ifg=1)

thank you,

**Comment by kueda** [comment]
Yeah, it's probably a time zone problem. I would suggest that they go to https://www.inaturalist.org/users/edit and set their time zone to whatever their local time zone is. If they're still having trouble, please have them reach out to us at help@inaturalist.org, and ask them to include their iNat username so we can check out their account.

**Comment by mutolisp** [comment]
Thank you! I'll tell the user to set up timezone first.

**Comment by mutolisp** [comment]
@kueda I just wondering if the following errors would be the timezone problems. Some of the users have configured timezone but got "Unknown Error" when uploading their observations. Several users have encountered such problem (the id of these users are pseudoshuigeeee, penlock). So is it possible to know what is the problem?

thank you!

Reference:

https://www.facebook.com/photo.php?fbid=10218211745789383&set=p.10218211745789383&type=3&theater
