### ISSUE TITLE
Problem with sound uploads

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1591]
Some users are reporting that they can't upload some .m4a sounds. When adding to the upload page, you get the red exclamation point. I can replicate this with [this sound](https://www.dropbox.com/s/dp81u83vq28v5bt/Voice%20011.m4a?dl=0) that one user sent. I'm not sure how it was recorded, I'll ask. 

However, this .m4a recorded from on my iPhone's voice recordings app and airdropped to my computer works fine (ignore exhalation at end). https://www.dropbox.com/s/6r84julge6zmsc6/Call%20At%20Redwood.m4a?dl=0

**Comment by tiwane** [comment]
The sounds that we aren't able to upload have all been recorded on Samsung phones using the default "voice recording" app.

**Comment by pleary** [comment]
This should be fixed in 91e591f. That's deployed and the above sound seems to be working

**Comment by tiwane** [comment]
Thanks! Works in Chrome, but weirdly I just noticed that playback is sort of not working in Firefox 57.0.1. The Samsung sounds I uploaded via Firefox will play in Chrome and Safari, but will not play in Firefox (https://www.inaturalist.org/observations/9366347). I uploaded an iPhone sound in Firefox and it plays fine in FF and other browsers: https://www.inaturalist.org/observations/9366403

**Comment by pleary** [comment]
Looks like Firefox can't currently play the 3GP files generated by these smartphones. So we need to decide what to do:

- Don't accept sounds in this format
- Attempt to convert 3GP sounds into mp3 or something else (and I suppose reject it if we can't successfully convert)
- Accept them as-is, but keep track of the mime type and put a notification somewhere that this format isn't compatible with all browsers

Anyone have preferences?

**Comment by kueda** [comment]
I think we have to reject the first option if we have enough people recording in this format that they're complaining. Conversion seems ideal but also a bit trickier, so I guess my vote is for conversion if you want to do it, but if that seems daunting then go with the accept as-is and hope Firefox starts supporting this format in the future.

**Comment by tiwane** [comment]
Another user emailed us and is unable to upload [this sound](https://www.dropbox.com/s/bk0j17ewfhl15tq/towhee.MP3?dl=0). I can replicate, I get the red exclamation point.

Will update when I know how the sound was recorded (device and software).

**Comment by tiwane** [comment]
Aaand, one more. [This one](https://www.dropbox.com/s/u1mmdrh0bww2zb0/frog3%2020%20Jan%202018.m4a?dl=0) is an .m4a generated from a movie file via Windows Movie Maker. Still won't work if converted via XLD.

**Comment by tiwane** [comment]
Here's one from a Sony sound recorder and output using the software Sound Organizer. I was able to convert it to another MP3 using XLD and it uploaded fine.

https://www.dropbox.com/s/supmrgqwl7xj2mp/180503_2144_02.mp3?dl=0

**Comment by kueda** [comment]
I think these recent mp3 issues stem from the fact that `file` on our production servers isn't doing a good job of recognizing the MIME type of mp3 files with metadata (even though the `file` on my laptop does). There's a fix described at https://superuser.com/a/445418 but it will require putting `/etc/magic` under chef control, and I'll need to talk with Patrick about the best way to do that on Monday.

The m4a file is trickier. It's a video file with a MIME type of `video/mp4`, but it has no video data, just audio. I'm not sure if we can detect that with `file`. We could with `ffprobe` but if we're installing that we might as well start converting audio files to something conventional. We could also just allow mp4 video and live with some large files, even if we never show them. Or continue disallowing it and hope that people who seem to be using Windows Movie Maker to make audio files can figure out how to export audio to mp3.

**Comment by kueda** [comment]
Patrick's recent change should have fixed the mp3 issues (worked for me on staging, at least). I futzed with the m4a file locally a bit and couldn't even get the uploader to accept it, despite trying the file extension and a bunch of potential mime type filters, so I suggest we just don't support mp4 video and suggest people convert o mp3 or wav.

**Comment by tiwane** [comment]
Sounds good.

**Comment by tiwane** [comment]
Sorry guys, one more sound, an m4a. User says he recorded it on his cellphone, and it's not from a video recording. XLD can't even open it, and neither will iTunes. Looks like he's using a Huawei, judging from his photo metadata. https://www.dropbox.com/s/wdcb59q17qlhmg7/Kenwyn%20Nature%20Park%20-%20clicking%20stream%20frog.m4a?dl=0

**Comment by kueda** [comment]
>  I suggest we just don't support mp4 video and suggest people convert o mp3 or wav

This is just yet another mp4 we're not going to be able distinguish from videos. I'm not saying this sounds are actually from videos, I am saying they are encoded as files the cannot be distinguished from video as far as our existing software is concerned, so our options are 1) support video, 2) do some more sophisticated type detection on the server using additional software, or 3) continue recommending that people convert to formats we do recognize. I support 1 and 3, and since 1 is a chunk of extra work (and storage) that probably requires a functional spec, I think 3 is the way to go for now and we should close this issue.

**Comment by tiwane** [comment]
OK, thanks.
