### ISSUE TITLE
Suggested modification to Explicit Disagree text (or alternative solutions)

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1594]
As mentioned here: https://groups.google.com/d/msg/inaturalist/x2XtUb8voDQ/IgrqHfOhAwAJ

A common use case of adding a coarser ID with the intent of coarsening the CID is not because you intend to say 'its definitely not Species A' but because you want to say 'From the evidence provided other species can't be ruled out'

For example, here the CID is at Ligidium gracile. I'd like to back it up to Ligidium since L. lapetum can't be ruled out:
https://www.inaturalist.org/observations/9314371

the only way to do so is to add a disagreement ID at rank genus, but I'd be saying 'its definitely not Ligidium gracile' which is not what I intend. (I intend to say that it can't be verified beyond Ligidium from the evidence provided)

Nick Block and Jakob iked the idea of including both of these in the popup. Something like:

```
Are you suggesting this isn't Dusky-blue Groundstreak Calycopis
isobeon or that it can't be verified as such from the evidence
provided?:
1. No comment, the Genus Calycopis is my best guess"
2. Yes, I am sure this is either not Dusky-blue Groundstreak
(Calycopis isobeon) or that it can't be verified as such based on the
evidence provided
```

Do people like this solution - if so can the language be word-smithed?

Charlie expressed concern that if he knows a species is Species A and observes it as such (maybe from the smell or something) that others will proactively go around and coarsen all his obs to whatever can be justified from the evidence. I understand his point, but I think this can be sorted out through norms ie something like this in our policy somewhere:
'The observer may have other evidence backing up their ID that is not evident in the media (e.g. smell of the plant etc.) and thus not available to the community. You should not agree with such identifications, but similarly you should not disagree with the observer's ID based on such external evidence just because you don't have access to this evidence. Only disagree with an observer's identification based on external evidence if you think it can't be that species'

thoughts @kueda @joellebel ?

**Comment by kueda** [comment]
Regarding the smell thing, I think people should be encouraged to ID based on the evidence provided, and if that bothers people they should opt out of the CID for those observations. I also consider the description to be a form of evidence, so if he's going on smell, he should write about the smell there. It's hard to provide evidence of smell that is as convincing as a photograph. Maybe reputation will help address this, e.g. prove you're good at plants by identifying photos of plants and we'll start trusting your observations that don't have adequate media evidence.

Regarding the main issue here, I actually used text in blind Identify that sort of addresses this:

```
1. Others could potentially refine this ID
1. This is the most specific ID the evidence justifies
```

I avoided that on the taxon page because it seemed a bit technical, but maybe that's inevitable. To keep the question format, we could go with something like

```
POTENTIAL DISAGREEMENT
Does the evidence provided support Ligidium gracile?
1. I don't know, but Genus Ligidium is my best guess.
1. No, Genus Ligidium is the most specific ID the evidence justifies.
```

**Comment by joellebel** [comment]
I agree with @kueda about the smell thang. I think that's rare and that's what descriptions are for. 


@kueda I like your text better because it's more concise. However, I'm wondering about this text:

> 2. No, Genus Ligidium is the most specific ID the evidence justifies.

I almost read that as your saying this ob cannot be IDed past the Genus Ligidiumn at all. Which isn't the case, right? Aren't you just trying to coarsen the ID because you know it's NOT a particular species, but could be another? Maybe I'm getting too semanticky?

**Comment by kueda** [comment]
I think "No, Genus Ligidium is the most specific ID the evidence justifies" means that the organism *could* be whatever, but the no one can determine that based on the evidence provided. So the intent is to coarsen the ID because you don't think anyone can take it further based on the evidence.

**Comment by loarie** [comment]
I agree with joelle. I'm not sure we can get away with not having both situations.

For example, if someone posts a woodlice photo of Common Pillbug when it is definitely not from a place I'm unfamiliar with, I add an ID of Oniscidea because I want to coarsen away from Common Pillbug. But it very likely CAN be ID'd beyond Oniscidea by the evidence provided.

Maybe:

```POTENTIAL DISAGREEMENT
Does the evidence provided support Armadillium vulgare?
1. I don't know, but Suborder Oniscidea is my best guess.
2. No, its not Armadillium vulgare OR the evidence can't rule out all other members of the Suborder Oniscidea```

**Comment by kueda** [comment]
Ok, how about this slight rewording, but with the same meaning intact (I think):
```
POTENTIAL DISAGREEMENT
Does the evidence provided support Armadillium vulgare?
1. I don't know, but Suborder Oniscidea is my best guess.
2. No, but it could be another member of Suborder Oniscidea.
```

**Comment by tiwane** [comment]
Sorry, just catching up with this. I think you've got the bases covered with that last one, Ken-ichi. That seems like an actual disagreement with the ID.

**Comment by loarie** [comment]
ugh - '2. No, it is another member of Suborder Oniscidea.' doesn't work in my original Ligidium example

In that example it is very likely Ligidium gracile, but another member of the genus can't be ruled out so best to coarsen the ID. So  '2. No, it is another member of Genus Ligidium.' isn't really correct

**Comment by kueda** [comment]
Ok, another stab:

```
POTENTIAL DISAGREEMENT
Does the evidence provided prove that this is Armadillium vulgare?
1. I don't know, but Suborder Oniscidea is my best guess.
2. No, but it is a member of Suborder Oniscidea.
```

I like that b/c it's simpler, though it's a bit vague in the case where it *could* be A. vulgare. If you're adamant about that "or" maybe

```
POTENTIAL DISAGREEMENT
Does the evidence provided prove that this is Armadillium vulgare?
1. I don't know, but Suborder Oniscidea is my best guess.
2. No, this is either not Armadillium vulgare or the other members of Suborder Oniscidea
   cannot be ruled out.
```

**Comment by loarie** [comment]
The former works for me - nice work coming up with something short that works in both cases

**Comment by loarie** [comment]
Should we also reassess '* loarie disagrees this is Western Spotted Skunk Spilogale gracilis' ?
e.g. something like '* loarie is suggesting an alternative to Western Spotted Skunk Spilogale gracilis'
or is this just minor semantics?

**Comment by tiwane** [comment]
"based on the evidence provided, loarie disagrees this is a Western Spotted Skunk Silogale gracilis"  ?

"suggesting an alternative" doesn't work seem to cover the bases

**Comment by loarie** [comment]
sorry tony - I deleted a comment that you replied to (I convinced myself that by saying 'potential disagreement' we're actually defining what we mean by disagreement on the site so its ok to use that term elsewhere)

**Comment by tiwane** [comment]
Gotcha.

**Comment by joellebel** [comment]
This one is my pick too:

```
POTENTIAL DISAGREEMENT
Does the evidence provided prove that this is 
Does the evidence provided prove that this is Armadillium vulgare?
1. I don't know, but Suborder Oniscidea is my best guess.
2. No, but it is a member of Suborder Oniscidea.
```

I like the succinctness. Just for a visual reference. This is how it would look on Android...

![image](https://user-images.githubusercontent.com/11527994/34634074-7c9c3b0e-f235-11e7-852b-45c42137a786.png)
