### ISSUE TITLE
Give users the option to display scientific names before common names

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1596]
There's a [vocal group on the Google Group](https://groups.google.com/forum/#!topic/inaturalist/ALjSvEiI-Iw
) who would like this option. The OP in the thread suggested a list of common names below the scientific name, like so:

![inaturalist-latin-name](https://user-images.githubusercontent.com/15896181/34688118-e53fd6ca-f465-11e7-88fc-46ebb7988315.jpg)

But I don't think that's necessary. Some others do like that idea, however.

**Comment by kueda** [comment]
Just to be clear, these people *do not* want to hide all common names, which they can already do, but they still want to see them?

**Comment by tiwane** [comment]
Yes. Colin Purrington was the one who started the thread and says "Such a display would help educate folks on why common names are sometimes problematic. E.g., there are often way too many common names to be useful, some are purely whimsical and not accepted by more than one person, and many map to other species entirely (corpse plant is an example). Demoting the common name might also help diffuse squabbles over which common name is THE common name, a tension that the default view (bottom image, below) tends to generate...I suspect that making the switch would make the platform more attractive to experts (of all types)."

Others agree, mainly those who are into plants and fungi, where common names are all over the place or 

Colin also thinks **_Scientific name_** (common names list) should be the default view, but I don't agree with that.

**Comment by kueda** [comment]
I'm not making this switch mandatory, which is the only way this would
"educate" people about the fallibility of common names, so that argument is
a non-starter. I think it's fine to make it optional, but will that really
placate anyone? If these people hate common NES so much why don't they just
disable them completely?

**Comment by tiwane** [comment]
I think having scientific name first will placate some. Others are pretty invested in Colin's idea of showing multiple common names, which I imagine would be tough to design. I don't think Colin would be placated unless this was the default view, but others would like the option. 

I can put it out there before you do any work on this.
