### ISSUE TITLE
Project observation field info not exporting

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1603]
User tonyrebelo points out that the CSV which is downloaded from "Export with private coordinates" from some of his projects, like [this one](https://www.inaturalist.org/projects/crew-site-sheet-s-afr), has all of the required observation field headings, but no data in them, even though the fields have been filled out in the observations. https://groups.google.com/forum/#!topic/inaturalist/eLTgXGTffds

**Comment by kueda** [comment]
Is this something that's going to get overhauled with the rest of projects, or are we basically leaving traditional projects alone?

**Comment by tiwane** [comment]
We're leaving traditional ones alone, for the time being.
