### ISSUE TITLE
IDs added by taxon change should not be disagreements

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1610]
e.g. https://www.inaturalist.org/observations/9304908

We should probably make it that identifications with taxon_change_ids don't generate disagreements.

**Comment by kueda** [comment]
What would you like to do about this situation:

ID 1: Canus lupus
ID 2: Canus (disagrees this is C. lupus)
(Obs Taxon is Canus)
(Canus swapped into Dogus)
ID 3: Dogus lupus (add as part of taxon change)
ID 4: Dogus ( added as part of taxon change, thus not a disagreement)
(Obs Taxon is Dogus lupus)

**Comment by loarie** [comment]
We'll ideally we could produce:

ID 1: Canus lupus
ID 2: Canus (disagrees this is C. lupus)
(Obs Taxon is Canus)
(Canus swapped into Dogus)
ID 3: Dogus lupus (add as part of taxon change)
ID 4: Dogus ( disagrees with D. lupus)
(Obs Taxon is Dogus)

But I spent some time thinking through it (even including ideas from here  #1595) and I don't think we could easily construct that.

Do you have any suggestions?

**Comment by kueda** [comment]
We could preserve disagreements for swaps and merges and not set disagreements for splits which would be annoying but probably not impossible. Not ideal, but maybe slightly better than just making them all not disagreements.

**Comment by loarie** [comment]
> We could preserve disagreements for swaps
how would you get ID 4 (Dogus) to disagree with D. lupus as opposed to C. lupus though? That seems complex

**Comment by kueda** [comment]
While swapping Canus into Dogus, we encounter ID 2 (ID of Canus). We see that ID 2's previous observation taxon, C. lupus, is a child of our input taxon, Canus, and is both inactive and has a single active synonym, D. lupus. We then assume disagreeing with C. lupus is the same as disagreeing with D. lupus so in our new identification, ID 4, we set the taxon to Dogus and the previous_obs_taxon to D. lupus.

And yes, complex, and maybe too prone to errors, and maybe not worth it. Up to you.
