### ISSUE TITLE
Adding an ancestor ID to your own observation when there is no CID uses CID (Unknown) rather than the observation.label as the 'disagreement'

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1612]
Steps to reproduce:
1. find an observation of yours with no CID and just your own identification
2. add an ancestor identification
3. note 'loarie disagrees this is Unknown'
<img width="542" alt="screen shot 2018-01-13 at 5 10 54 pm" src="https://user-images.githubusercontent.com/598026/34911748-6fa4aa48-f885-11e7-9e15-f3537c6c0d71.png">

I've confirmed this doesn't occur when there is a CID
<img width="551" alt="screen shot 2018-01-13 at 5 15 42 pm" src="https://user-images.githubusercontent.com/598026/34911745-6cc09490-f885-11e7-8a3b-00f419b13a6a.png">

or when its someone else's observations
<img width="561" alt="screen shot 2018-01-13 at 5 13 56 pm" src="https://user-images.githubusercontent.com/598026/34911747-6e2fb888-f885-11e7-8ebd-960266e461b1.png">

**Comment by kueda** [comment]
I think this is the same as https://github.com/inaturalist/inaturalist/issues/1616 (sorry, didn't realize they were the same when I first saw this).
