### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by Pyscowicz** [inaturalist/inaturalist#1617]
Translations for Explore, Learn, Meet, Press and Community Guidelines texts are missing from translatewiki.net and GitHub in all languages (also English). 
![translationmissing](https://user-images.githubusercontent.com/35464425/35005555-6f8e59e0-fafc-11e7-8eda-eef235e9a6c9.png)

**Comment by kueda** [comment]
Can you please be more specific about where you're seeing these strings? E.g. by "Explore" I think you mean the text next to "SIGN UP" at https://www.inaturalist.org while signed out. Including URLs will help us track these down.

**Comment by Pyscowicz** [comment]
All these texts are on the front page while signed out. EXPLORE, LEARN and MEET are next to SIGN UP. Press and Community Guidelines are at the footer as shown on the picture.
![guidelinesmissing](https://user-images.githubusercontent.com/35464425/35007329-05c948de-fb02-11e7-8be3-f80f239dd9d3.png)
