### ISSUE TITLE
Don't use probable taxon below species, deal with opt-out subspecies issue

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1620]
Two related changes that relate to subspecies:
1. Stop setting the Observation Taxon to the Probable Taxon if the Probable Taxon is an infraspecies within the Community Taxon, e.g. ID 1: Ensatina eschscholtzii, ID 2: Ensatina eschscholtzii ssp. xanthoptica should leave the Observation Taxon at Ensatina eschscholtzii, but ID 1: Genus Ensatina, ID 2: Ensatina eschscholtzii should also leave it at Ensatina eschscholtzii
1. Allow obs to be Research Grade if the observer has opted out of CID AND the Observation Taxon is a species that contains the Community Taxon

These deal with related problems. 1 addresses the fact that currently, an obs that is RG can be bumped into Needs ID by adding a single ID of a subspecies of the species, and unpleasant side-effect of the Probable Taxon approach we're now taking, which most people seem to like except in this situation. 2 addresses the fact that when a user opts out of CID and everyone agrees with their species-level ID but they agree at subspecific level, the obs is still in Needs ID, even though everyone agrees with the species-level ID, which kind of needlessly sequesters such observations in Needs ID even though no one can actually improve the situation (aside from the observer opting into the CID).

**Comment by loarie** [comment]
I'm ok with that
