### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by Pyscowicz** [inaturalist/inaturalist#1621]
I found missing translations from page [https://www.inaturalist.org/people/pyscowicz](url)

The missing translations are Journal Posts and Followers
![translationsmissing](https://user-images.githubusercontent.com/35464425/35041173-7f8470e2-fb8c-11e7-8f66-a5fbffcd600c.png)

[https://www.inaturalist.org/observations](url) On observations page when you click filters, there is some species on categories but two of them have missing translation as well. Missing translations are "en.all_taxa.fungi_and_lichens" and "en.all_taxa.molluscs"

![missingtranslations](https://user-images.githubusercontent.com/35464425/35193911-fb93f882-feb2-11e7-8aff-2950951c66f7.png)

**Comment by kueda** [comment]
Will get a fix out for the first set of missing keys soon. The ones in the Filters menu are a bit trickier. Give the framework we use on that page we have to translate from the default English common name into the current locale, and the default English common name can be changed by the site curators, so it's tricky to translate it properly. This might be a bit easier if we update this page, which we really should. In the meantime, I've made it so those button tag titles will just use the default scientific name of the taxon if the default English name can't be translated into the current locale.
