### ISSUE TITLE
Convert old BMP photos

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1634]
We have a number of photos that are BMPs, even though we don't allow them. I suspect they snuck in during a period when we didn't have adequate content type validations, because there don't seem to be any recent ones. Here are some photo IDs: 30969 53784 53790 53783 53788 53778 53782 53792 53789.

So, write a script that gets all these, converts them to JPGs, and updates the original with the JPG copy to trigger all the cutdowns. `original_url LIKE '%.bmp%' ` seems to pull up over 1000 observations.

**Comment by pleary** [comment]
These have been converted to JPGs
