### ISSUE TITLE
"Update with iNat Content" tool in Guides not always working

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1637]
In some taxa that do have correctly licensed photos on iNtat the "Update with iNat Content" tool (and the EOL one) doesn't load anything. One example, Gaga marginata. This seems to happen if the default taxon photo is all rights reserved.

**Comment by kueda** [comment]
Do you have any other examples? This taxon has only one photo associated with it and that photo is not licensed, so that explains why the photo doesn't get added and it has no Wikipedia page so we have no Wikipedia content to add, so that explains the lack of a guide section.

**Comment by tiwane** [comment]
I didn'tknow it selected only from photos chosen for the taxon, so perhaps not a bug. Will close for now.
