### ISSUE TITLE
Countries displaying their native names, not English/US names

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1650]
I noticed that countries now display their native names, rather than their English names. Eg, in [this observation](https://www.inaturalist.org/observations/9727606) it shows Jamhuri ya Uganda rather than Uganda, or [this one](https://www.inaturalist.org/observations/9745002), which hows Frankreich and not France. My account settings don't seem to affect this.

**Comment by kaldari** [comment]
That field is entered by the observer and can be anything, even total nonsense.

**Comment by kaldari** [comment]
Actually, if you're using the app, it looks like the app fills it in for you. I'm not sure how the app chooses the language though or if was responsible for the cases you describe.

**Comment by kueda** [comment]
Like Kaldari said, this is a user-editable field, so we just show what we have. So, not a bug, just behaving the way it was designed.
