### ISSUE TITLE
Updated documentation for a production setup

### ISSUE THREAD

**Issue by marco-pistone** [inaturalist/inaturalist#1657]
Hello,
i'm trying to install a production server based on ubuntu 16, but the documentation provided is quite old and many packages are outdated and the installation process is really hard.
There is an update documentation about setup or at least an updated dependencies package list that helps me to install iNaturalist?

Thanks in advance

**Comment by kueda** [comment]
As far as I know, https://github.com/inaturalist/inaturalist/wiki/development-setup-guide is pretty up-to-date, but another place to look for Ubuntu setup is https://github.com/inaturalist/inaturalist/blob/master/.travis.yml. That's our continuous integration setup for Travis, which rebuilds our entire stack on a fresh Ubuntu installation for every run.

If you're still having problems, please file issues with specific, reproducible problems we can address, e.g. with stack traces, error messages, details of your setup, etc.
