### ISSUE TITLE
OpenJDK 64-Bit allocation memory error

### ISSUE THREAD

**Issue by marco-pistone** [inaturalist/inaturalist#1658]
Hello i'm following the deveopment setup but when i arrive rake es:start i receive  this error:
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f48ea000000, 33554432, 0) failed; error='Cannot allocate memory' (errno=12).
Manually i've modified the jvm.options and stating the elasticsearch from inaturalist/elasticsearch/bin/elastichsearch it reads the options correctly, no the same if i use rake es:start.

Any help is appreciated

**Comment by pleary** [comment]
I've not seen this error before. On my local machine (Mac) when I run the rake task, ES properly reads jvm.options and sets the memory correctly.

The rake task is provided as a convenience for developers to use in their local development environment, but you don't need to start Elasticsearch with the rake task. If you can start it directly and have it read the proper config, then I recommend you do that. But if you find the issue and its a bug in this code, we'd be happy to accept a pull request
