### ISSUE TITLE
suggestions on identify different from suggestions on obs show

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1660]
e.g. compare
https://www.inaturalist.org/observations/9831491
<img width="586" alt="screen shot 2018-02-12 at 9 55 34 am" src="https://user-images.githubusercontent.com/598026/36111500-2b2ecf0c-0fdb-11e8-90f5-ba8456283134.png">
to
https://www.inaturalist.org/observations/identify?id=9831491
(uncheck taxon and place): the suggestions seem to be in reverse order (ie top suggestion at bottom)
<img width="300" alt="screen shot 2018-02-12 at 9 57 20 am" src="https://user-images.githubusercontent.com/598026/36111497-29a55e3a-0fdb-11e8-8cb2-f093a5e2b26a.png">

Obs show seems to be the right one and is also the one consistent with the computer vision demo
https://www.inaturalist.org/computer_vision_demo
<img width="397" alt="screen shot 2018-02-12 at 9 59 55 am" src="https://user-images.githubusercontent.com/598026/36111609-88823f90-0fdb-11e8-844e-a5ec0fd15d15.png">

**Comment by kueda** [comment]
Can you confirm that this is fixed on staging? Not really sure how this happened, didn't see much in the git history, and I feel like it was working fine a few days ago.

**Comment by loarie** [comment]
yes looks fixed thanks

**Comment by tiwane** [comment]
Is this one showing reverse order as well? https://www.inaturalist.org/taxa/7251-Passeriformes

![image](https://user-images.githubusercontent.com/15896181/36183815-0090892e-10e5-11e8-9934-c2d144bdbc43.png)

**Comment by kueda** [comment]
No, I think those are just bad vision results. They do differ from the computer vision demo results, though. Not sure why.
