### ISSUE TITLE
Sort by Species/Taxon name is buggy

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1661]
The sort by Species/Taxon Name under “Your Observations” is pretty buggy and inconsistent. For example, [my observations](https://www.inaturalist.org/observations/tiwane?filter_spam=false&order=asc&order_by=species_guess&user_id=28&viewer=28) start out ordered by genus name but then it switches to common name here:

<img width="290" alt="screen shot 2018-02-12 at 2 47 56 pm" src="https://user-images.githubusercontent.com/15896181/36124281-55cef772-1004-11e8-8b1b-d8312b1d99c9.png">

**Comment by kueda** [comment]
Are you talking about clicking on that column header? I propose we just remove that. We stopped supporting that sort in obs search and in the filters a long time ago.

**Comment by tiwane** [comment]
Yes. I'm fine with that. If it doesn't work, it shouldn't be an option.
