### ISSUE TITLE
Index public place IDs and private place IDs separately in the observations index

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1663]
Currently we just have a single `place_ids` property in the obs index that seems to be the IDs of all places with geometries that contain the private lat/lon. This causes at least three problems

1. Names of small places get exposed through the API for private and obscured observations, which can negate the effect of obscuration if the place is small enough (or at least this was true until this stopgap: https://github.com/inaturalist/iNaturalistAPI/issues/126)
1. Observations in small places can be found in place searches
1. Observations with large positional_accuracy show up in place searches for places that don't really contain them, e.g. https://www.inaturalist.org/observations/7412387 showing up at https://www.inaturalist.org/observations?place_id=143&subview=grid&taxon_id=48259

I think we *could* solve this by keeping two separate place ID properties in the observations index, one for places that actually contain the circle of positional_accuracy for the observation, and another for places that contain the circle of public_positional_accuracy for the observation (the latter is the larger of the positional_accuracy or the diagonal of its uncertainty cell). It would come with the cost of re-indexing all observations that have obscured or private coordinates and additional computation at indexing time to determine which places we should index.

Thoughts?

**Comment by tiwane** [comment]
If it works, I think this would be great.

**Comment by pleary** [comment]
Sounds good to me. This isn't so different from our indexing `location` and `private_location`, where we query on one or the other based on the session. So I think having `place_ids` and `private_place_ids` is a good approach. Hopefully we can make it so when we're bulk indexing 1000 observations, we can preload all the data we need to determine the public places with Rails preloading, and that we don't need extra queries for every observation we index
