### ISSUE TITLE
https://www.inaturalist.org/observations/8696309 links from GloBI to iNaturalist, but not vise versa

### ISSUE THREAD

**Issue by jhpoelen** [inaturalist/inaturalist#1667]
Expected: 
Because https://www.inaturalist.org/observations/8696309 is included in GloBI, iNaturalist points to where the observation is included in GloBI.

Actual:
No link to GloBI is provided on the observation page. (see attached image)

Note that other observations like https://www.inaturalist.org/observations/3948802 do show the expected linking behavior. 

Please let me know how I can help figure out what is going on.

![screenshot from 2018-02-19 14-48-18](https://user-images.githubusercontent.com/1084872/36400153-21b91424-1584-11e8-9db2-c8603519b122.png)

**Comment by kueda** [comment]
Was a silly issue of switching to HTTPS. Will have a fix running soon.

**Comment by jhpoelen** [comment]
@kueda thanks!
