### ISSUE TITLE
Display common names in "title case"

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1669]
To make things consistent throughout iNat, and allay some vocal users, it's probably best to have a capitalization display scheme that is the same for all taxa. There's no way to make everyone happy, but having a standard would be good.

So, would it be possible to display common names (regardless of how they're entered in our database) in "title case"? This would mean that all "important" words would be capitalized, but prepositions, articles, and conjunctions would not be (unless they're the first word).

 Examples:

- Cock-of-the-Rock
- Red-Breasted Merganser
- The Prince
- Savannah Sparrow
- Thread-Horns

Even better would be to not capitalize after a hyphen, if possible. Which would look like:

- Cock-of-the-rock
- Thread-horns
- Red-breasted Merganser

**Comment by kueda** [comment]
Todo

- [ ] 'i'iwi should be capitalized as 'I'iwi, and ‘i‘iwi as ‘I‘iwi
