### ISSUE TITLE
EOL imports grafting to subgenus/section rather than parent genus

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1672]
If a subgenus or section has the same name as its parent, species that are imported from EOL (and possible COL) get auto-grafted to the subgenus/section rather than the parent genus. This can happen with other taxa that have the same name (eg same genus name but two different kingdoms. 

See https://www.inaturalist.org/flags/215561

**Comment by kueda** [comment]
I wasn't able to replicate this but I added some code that might help prevent it. If it pops up again please re-open.
