### ISSUE TITLE
Remove or Change the "Add observation to place" link on Place pages

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1681]
With the new threshold we've set for accuracy circles and places, I don't think the current default for the Add an observation link in Places works. It will start an add obs page with the accuracy circle that is significantly larger than the place (eg https://www.inaturalist.org/observations/new?latitude=38.3551613671&longitude=-87.8264970335&place_guess=Beall+Woods+State+Park&place_id=122831&positional_accuracy=1457.592957362052), which is leading people to add observations that don't actually get put in the place. 

Personally I think we should just get rid of this feature, cause it is so old fashioned, but if anyone feels strongly about keeping it, the default accuracy needs to be changed.

**Comment by kueda** [comment]
I agree on remove. We really can't automatically create a point and radius that represents "somewhere in a place" unless that place has a perfectly circular boundary. Plus obs/new is not a page we should be encouraging.
