### ISSUE TITLE
Read GPSHPositioningError Data in Web Uploader

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1684]
If possible, it'd be great to record this data if it's in the EXIF tag. True, one can adjust the accuracy in the uploader, but if the user has done so already, this would make it easier.

**Comment by carrieseltzer** [comment]
And iOS already reads the "Horizontal Positioning Error" field, which means that you can upload previously taken photos with the app and still get accuracy. Seems like it should be a small thing to fix with a big payoff in data quality.

**Comment by kueda** [comment]
Can you provide some photos that have this in their EXIF? I don't have any I can test with.

**Comment by tiwane** [comment]
Here's one cassi sent. 
![img_8955 1](https://user-images.githubusercontent.com/15896181/37549151-b06e34fa-293a-11e8-9b6d-2b67dfd349f9.JPG)

**Comment by carrieseltzer** [comment]
Here's another:
![2018-03-07 08 19 49](https://user-images.githubusercontent.com/7501183/37549634-743b8afa-2958-11e8-999e-f853bbf977ac.jpg)
