### ISSUE TITLE
Index potential place IDs

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#1690]
Currently we index `place_ids` as the IDs of all the places whose bounding boxes contain the bounding box of the observation's accuracy circle. If an observation's accuracy circle touches California and Nevada, we can't say for sure whether the observation was made in California or Nevada, so it would be inaccurate to show that observation in searches for either state.

However, this breaks the `not_in_place` in the Node API, because if you search for observations that are not in California or Nevada, you will get that observation b/c its `place_ids` field in the index does contain California or Nevada, even though we know it must occur in one of those two places.

Here's a concrete example: https://www.inaturalist.org/atlases/4024 is marked as having observations that are not in the atlas, including https://www.inaturalist.org/observations/846809, which could be in Colorado, Oklahoma, or Kansas. Since we don't know which one it is in, we don't consider it to be in any of those places. The atlas is marked b/c currently `not_in_place=Colorado,Oklahoma,Kansas` turns up that observation, even though we can be sure it's not in any of those places.

An unpleasant solution to this would be to add yet another place IDs field to the observations index that includes the IDs of all the places that could contain the observation, i.e. the IDs of every place touched by its accuracy circle. We could call it `potential_place_ids`. Then something like `NOT IN potential_place_ids` would really show everything we're sure is not in those places. The downsides are are yet another slowdown in the obs indexing process and the need to re-index all obs again.

Any other ideas, or problems with this approach?

**Comment by loarie** [comment]
How about: 
1) always map an obs to a place based on its centroid regardless of its uncertainty
2) add accuracy to the search params so people could, for example, search obs from CA with accuracy > 5km?

Not exactly a solution to the problem described, but seems like it would generally address the concerns about avoiding problematic inaccurate obs

**Comment by kueda** [comment]
Can't do 1 because that enables you get around geoprivacy, e.g. you can see that Tony saw an SF Garter Snake in Año Nuevo by searching for obs in Año Nuevo. That's what https://github.com/inaturalist/inaturalist/issues/1663 was all about. It also creates potential false positives in place search results, but getting around geoprivacy is the big one.

I have no problem with 2, but I'm not sure how that addresses this issue.

**Comment by loarie** [comment]
Remind me why we're mixing uncertainty with obscuring? Just talking about uncertainty my 1 & 2 wouldn't involve #1663. While I understand the false positive concern, it seems like it could be generally addressed by 2 (ie if you want to search from obs from CA and want to be really sure that everything you're getting is at least within 1km of the CA border you could search for obs from CA with uncertainty < 1km)

Re: #1663, could we come up with a solution that only involves obscuring but not uncertainty? ie obscured obs only index place_ids from places where admin_level.nil? OR area > X? That might make it so a search of a small park doesn't turn up SF Gartersnake, but a search of Santa Cruz County would?

**Comment by kueda** [comment]
If you want to do it that way, go ahead and write it up and we can close this issue.

**Comment by loarie** [comment]
Thinking about this some more, I really only care about Atlases not being broken, and looks like there was already a lot of work done on #1663.

So rather than my more radical proposal, could we just have obs always index Atlas places (admin 0,1,2) with their true centroids (ie centroids or private centroids when obscured). But otherwise work unchanged?

Since Atlas places are big and the public can't create them seems like it wouldn't impinge on the threatened species trapping concerns

**Comment by kueda** [comment]
Ok, if you don't want to pursue the solution I proposed in this issue, please open another issue with your proposal.

**Comment by loarie** [comment]
Ok made an issue here #1691
