### ISSUE TITLE
Index place_ids on obs using their true lat/lngs for standard places 

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1691]
Issue #1663 addresses some issues associated with revealing private coordinates via small places and 'false positive of obs being returned in the wrong place when uncertainty is large relative to place size). But as described in #1690 it broke atlases which rely on the assumption that all obs fall within a standard place and thus take advantage of not_in_place queries.

This proposed change would make it so obs index place_ids using their lat/lngs (ie lat/lng or private lat/lng when obscured) for standard places (ie places with admin_levels.

**Comment by kueda** [comment]
1. What range of admin levels? All of them? b/c parks and towns can be really small.
1. If you only want to consider countries / states / counties, what do you want to do about really small ones like https://www.inaturalist.org/places/kalibato-lake? I'm sure there are some very small us counties too.

**Comment by loarie** [comment]
>What range of admin levels? All of them? b/c parks and towns can be really small.

Just 0,1,2 if you're concerned about National Parks

>If you only want to consider countries / states / counties, what do you want to do about really small ones like https://www.inaturalist.org/places/kalibato-lake? I'm sure there are some very small us counties too.

I personally don't think this is a problem. Its routinely considered sufficient to coarsen threatened species data to county (e.g. NatureServe, FIeldHerpForum, HerpMapper). Have there been specific complaints that displaying the county in which threatened species occur is irresponsible?

**Comment by kueda** [comment]
Nope, just trying to get clarity so this can be implemented. I am pretty sure you'll field complaints at some point from people complaining that you can search for threatened stuff in Kalibato Lake etc., but if that's how you want to do it, so be it. There is no perfect solution.

**Comment by loarie** [comment]
That would be my preference

**Comment by kueda** [comment]
Re-opening b/c this isn't really "done" until we've re-indexed all obs with `public_positional_accuracy` set.

**Comment by tiwane** [comment]
Just realized that this might create issues for City Nature Challenge. Because most of the CNC places are not 0,1, or 2 level places (I think, LA excepted), observations at the edges with uncertainties that fall outside the boundaries but have coordinates inside the places boundaries will not be counted. 

I'm not sure how big of an issue this would be, but it would mean that people observing threatened species near the boundaries of the CNC place will be wondering why their observation(s) aren't being counted for the challenge. As will those who are running the CNC. So if we keep this change, we should notify them. 

@loarie, any thoughts?

**Comment by loarie** [comment]
tony and I discussed this offline. My attempt at a recap:

Approach 1: Indexing obs by their 'true' (ie public or private if obscured) centroids
benefits:
a) obs always are assigned to a place (critical for Atlases since they are used to find 'out of range' obs)
b) can find place associated with obs and vice versa
costs:
a) places can be used to narrow down where obscured obs are located
b) places might fall in the wrong place (ie if an obs has lots of uncertainty with a centroid in place A - it might really be in place B and thus erroneously assigned to place A)

Approach 2: not indexing obs if their uncertainty (either from big accuracy circles, or via obscuration) bleeds out of a place
benefits:
a) places can't be used to narrow down where obscured obs are located
b) obs never returned in the wrong place
costs:
a) can't find place associated with obs
b) can't use places as an Atlas to find out of range obs

Currently we're going with Approach 1 for 'atlas places' (ie standard places of admin_level 0,1,2) and Approach 2 for all other places

There's clear trade-offs here so no solution is perfect. I think the Approach 1 benefits outweigh the costs for Atlas places so I wouldn't want to switch to Approach 2.

For other places, I don't have strong feelings. If Approach 2 benefit (a) is a big deal then it might out weigh the costs. But Approach 2 cost (a) is a burden.

@tiwane and @kueda do you think the Approach 2 benefits outweigh the costs for other places?

**Comment by kueda** [comment]
> @tiwane and @kueda do you think the Approach 2 benefits outweigh the costs for other places?

I do and posted an unpleasant but (IMO) workable solution at https://github.com/inaturalist/inaturalist/issues/1690. However, I don't think that solves Tony's problem unless projects work in a way that normal obs searches don't, and I'm too sick of this problem to argue my side. What we need here is a decision, unless someone else wants to come up with a solution to Tony's issues, https://github.com/inaturalist/inaturalist/issues/1663, and the atlas issue described above.

**Comment by loarie** [comment]
Cool - then lets stick with the status quo and incur the costs to CNC of dropping some from the count by responding that this is a consequence of the benefits of safeguarding threatened species

**Comment by tiwane** [comment]
OK, let's do it.

**Comment by kueda** [comment]
All obs should have been re-indexed.
