### ISSUE TITLE
Make the title of the "Flags" box on the Dashboard link to https://www.inaturalist.org/flags

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1694]
Part of bouteloua's suggestions in this thread: https://groups.google.com/forum/#!searchin/inaturalist/bouteloua%7Csort:date/inaturalist/BFe_XmLq6kY/ypw8F5rOBgAJ

**Comment by boucur** [comment]
:+1: 
alternatively, something like this for consistency:
```
<div class='panel-footer'>
`<a class="btn btn-primary btn-sm" href="/flags">View all</a>
</div>
```
