### ISSUE TITLE
Filtering flags results in 404

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1695]
Choosing a filter on the flags page (eg "copyright infringement") results in this URL: https://www.inaturalist.org/flags?utf8=%E2%9C%93&user_id=&flag=copyright_infringement&commit=submit which returns a 404. bouteloua points out that one would have to modify the URL to https://www.inaturalist.org/flags?flag=copyright_infringement to make it work.

**Comment by boucur** [comment]
Page 2 of filtered flags is still broken:
https://www.inaturalist.org/users//flags?commit=submit&flag=inappropriate&page=2&utf8=%E2%9C%93
.
.
![linkbroken](https://user-images.githubusercontent.com/4712407/37876457-33edafd0-3012-11e8-87bf-1e62213fc052.png)
