### ISSUE TITLE
Not getting warning for adding unacceptable observation to project

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1697]
When on the ob detail screen and attempting to add an observation to a project that does not meet the project's requirements, I don't get an error message. For example, https://www.inaturalist.org/observations/10181474 Try adding this ob to the Birds of Golden Gate Park project which only allows aves.

**Comment by joellebel** [comment]
FYI This error messaging currently works on staging

**Comment by pleary** [comment]
I believe this has since been resolved
