### ISSUE TITLE
Searching in a Place's checklist page returns "This list is empty!" 

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1700]
Related to https://github.com/inaturalist/inaturalist/issues/1699

1. Go to a Place's checklist page (eg https://www.inaturalist.org/check_lists/312-California-Check-List)

2. Search for anything (eg https://www.inaturalist.org/check_lists/312-California-Check-List?q=lizard)

3. You get a "This list is empty!" result.

Here's what I get in the console:

![image](https://user-images.githubusercontent.com/15896181/37675398-602843d2-2c32-11e8-8b9d-08ee97e3a4eb.png)

**Comment by kueda** [comment]
https://www.inaturalist.org/check_lists/312-California-Check-List?q=lizard still isn't working
