### ISSUE TITLE
Identify link from subscription takes me to a strange place

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1710]
I subscribe to Serpentes within California, and when I click on the Identify link it takes me to an Identify page that is definitely not California snakes. For example:

<img width="820" alt="screen shot 2018-04-02 at 2 30 57 pm" src="https://user-images.githubusercontent.com/15896181/38217704-2d450c96-3684-11e8-8a36-b92da444562d.png">

Takes me to [this page](https://www.inaturalist.org/observations/identify?created_d1=2018-04-02T13%3A06%3A25-0700&created_d2=2018-04-02T13%3A48%3A32-0700&place_id=14&subview=grid&verifiable=any). 

I _think_ this might be just when there are two instances of this subscription (eg the one shown above, plus one lower on the page showing a different California snake observation) appearing on the same page in the my dashboard but I'm not sure yet. 

My subscriptions:
<img width="396" alt="screen shot 2018-04-02 at 2 32 06 pm" src="https://user-images.githubusercontent.com/15896181/38217808-76a0e1a8-3684-11e8-9827-748f88cd2c1d.png">

**Comment by tiwane** [comment]
Seems to be happening again. Clicking on Identify here:
![image](https://user-images.githubusercontent.com/15896181/50617837-0acad080-0ea4-11e9-9fda-6187a51e1d09.png)

Leads to: https://www.inaturalist.org/observations/identify?created_d1=2019-01-02T15%3A19%3A35-0800&created_d2=2019-01-02T15%3A32%3A25-0800&place_id=14&subview=grid&verifiable=any

![image](https://user-images.githubusercontent.com/15896181/50617851-1918ec80-0ea4-11e9-8cf2-9dbdcd5f121d.png)

**Comment by kueda** [comment]
I *think* that commit fixed this.
