### ISSUE TITLE
Make default user icon consistent

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#1719]
Currently some user icons show up as...

![image](https://user-images.githubusercontent.com/11527994/38515155-45337c98-3be8-11e8-8943-dbd920bacd37.png)

Please make them all...

![image](https://user-images.githubusercontent.com/11527994/38515177-55950b10-3be8-11e8-8d6a-bc7149076936.png)

@kueda I assigned it to you because it would be nice if this was done before the new Projects and I think Patrick is pretty busy with that atm.

**Comment by kueda** [comment]
For my own reference, I *think* not using icon urls from google that contain `4252rscbv5M` will do it...

**Comment by joellebel** [comment]
@kueda just a note, it would be kinda nice to get to this soon so we have some consistency in the Project followers popup bubble: 


![image](https://user-images.githubusercontent.com/11527994/39076962-613ee21e-44b3-11e8-807f-91c159f8e537.png)

and the ob detail faves pop ups bubble:

![image](https://user-images.githubusercontent.com/11527994/39077007-a57f2ba0-44b3-11e8-9d8e-7f1383381de0.png)

We can use the same icon and treatment we use in the coments/IDs timeline the web ob detail screen:
![image](https://user-images.githubusercontent.com/11527994/39077077-19b3aa28-44b4-11e8-8443-f2744505ef8c.png)

Can we just make the icon of the person slightly smaller so there's more padding around it and center it within the gray circle? Tnx.

**Comment by joellebel** [comment]
Here's another place they're inconsistent.... On obs search results grid view:
![image](https://user-images.githubusercontent.com/11527994/39159910-28d6f9cc-471d-11e8-8a51-690524a97bf0.png)

Can we also make sure the white profile icon is centered in the gray circle? Gracias.

**Comment by kueda** [comment]
Well, I prevented some of these from getting created, but clearly some are still getting through:

- [ ] https://www.inaturalist.org/people/joannicole

**Comment by kueda** [comment]
That user is still a unique case, so I'm closing.
