### ISSUE TITLE
Missing translations and letter size problem

### ISSUE THREAD

**Issue by Pyscowicz** [inaturalist/inaturalist#1720]
Hey.

The missing translations on filters page which was already fixed seem to be back.

![oops](https://user-images.githubusercontent.com/35464425/38614130-ba5a2c1c-3d94-11e8-8053-3bab5a764cef.png)

Also the Export page (https://www.inaturalist.org/observations/export) have missing translations fi.date.range, fi.choose_collums, fi.basic, fi,geo and fi.taxon extras

![export](https://user-images.githubusercontent.com/35464425/38614513-1fdcd0de-3d96-11e8-9ab7-4e148d1a6bf2.png)

![translationsmissing](https://user-images.githubusercontent.com/35464425/38620227-a6e5c134-3da6-11e8-97ff-bf69f19e957b.png)

Second problem is strange letter size problem when using filters panel on observations page in other language than english (e.g Finnish/Suomi, my language)

![filters](https://user-images.githubusercontent.com/35464425/38614111-b24aa47a-3d94-11e8-8bea-2268a2d65c11.PNG)

**Comment by cmcheatle** [comment]
It seems a generic issue, as I am seeing something similar in Danish. It seems to be related to letters getting put into uppercase when they follow an accented character.

![image](https://user-images.githubusercontent.com/37387884/38629545-5cc77fe4-3d82-11e8-8478-9bf3e7f15eb2.png)

**Comment by Pyscowicz** [comment]
Yes, e.g on my picture the Päivitä Haku should be Päivitä haku and Tyhjennä Hakusuodattimet should be Tyhjennä Hakusuodattimet as they are translated but it's not big problem but HavaintopäIväMääRä and LisäYspäIväMääRä doesn't look good. Maybe someone should change texts to view as they are translated.

**Comment by kueda** [comment]
It's a capitalization issue. The capitalization Javascript we're using on this page doesn't handle unicode characters very well, so I'm going to try switching to CSS. Hopefully this will stop being a problem when we revise this page and use the version of this UI on Identify, which uses totally different code (even though it looks mostly the same).

**Comment by Pyscowicz** [comment]
That's great 😊 Remember also to fix these missing translations when you have time.

I found one more translation on https://www.inaturalist.org/projects/nogensnegle-i-danmark-nudibranchs-of-denmark/journal/new

en.formatting

**Comment by Pyscowicz** [comment]
Thanks for the changes. Now it looks much better. There is still some thing to do.
![better](https://user-images.githubusercontent.com/35464425/38731202-157f9b02-3f22-11e8-938c-43dd52fc7afc.PNG)

These words should not be in this form on filters window. Tarvitsee Tunnisteen should be Tarvitsee tunnisteen, Lisää Suodattimia should be Lisää suodattimia, Kuvien Lisensointi should be Kuvien lisensointi, On Ääniä and On Kuvia should be On ääniä and On kuvia, Tarkka Päivämäärä should be Tarkka päivämäärä and Mikä Tahansa should be Mikä tahansa. Every word begins in capital letters and it should not be like that.

**Comment by kueda** [comment]
I think we're getting into the weeds here, but for an attempt at clarity, are you saying that "Lisää Suodattimia" means something different in Suomi than "Lisää suodattimia" and if so, what is the difference in meaning? If this is a question of style rather than meaning I'm just going to leave this alone. In English, "More Filters" and "More filters" mean exactly the same thing, regardless of whether you think one or the other is more proper.

**Comment by kueda** [comment]
Ok, well that sounds more like a question of style and not of content, so I'm going to leave that alone. We'll keep your thoughts in mind for future work, but as I mentioned observations search uses some older code that is harder to update, so I'd prefer to deal with this when we update that page.
