### ISSUE TITLE
Words and phrases missing from Translatewiki strings

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1721]
https://www.inaturalist.org/projects/nogensnegle-i-danmark-nudibranchs-of-denmark
![image](https://user-images.githubusercontent.com/15896181/38631378-732cdc3e-3d6e-11e8-854d-b25b8a5e2529.png)

https://www.inaturalist.org/observations/import#csv_import
![image](https://user-images.githubusercontent.com/15896181/38631387-7b188d9e-3d6e-11e8-9310-e7ab8dbbc146.png)

![image](https://user-images.githubusercontent.com/15896181/38631425-928b2040-3d6e-11e8-9bcb-af9fd27ab9f2.png)

https://www.inaturalist.org/lists/911348-N-gensnegle-i-Danmarks-tjekliste?rank=species
![image](https://user-images.githubusercontent.com/15896181/38631432-9a905ecc-3d6e-11e8-9021-17685a6c650f.png)

https://www.inaturalist.org/projects/nogensnegle-i-danmark-nudibranchs-of-denmark/journal/new
![image](https://user-images.githubusercontent.com/15896181/38631457-aea2c094-3d6e-11e8-8ad9-f2efa89e3d05.png)

 
https://www.inaturalist.org/projects/nogensnegle-i-danmark-nudibranchs-of-denmark/assessments
![image](https://user-images.githubusercontent.com/15896181/38631474-b680bcbc-3d6e-11e8-8deb-8f7ac9bdadf8.png)

![image](https://user-images.githubusercontent.com/15896181/38631484-bac62834-3d6e-11e8-8c5b-8431cb27f27c.png)

https://www.inaturalist.org/project/nogensnegle-i-danmark-nudibranchs-of-denmark/terms
![image](https://user-images.githubusercontent.com/15896181/38631505-c836bde4-3d6e-11e8-9f30-eaaf2d270b74.png)

https://www.inaturalist.org/observations/new?project_id=17253
![image](https://user-images.githubusercontent.com/15896181/38631517-d2931896-3d6e-11e8-9c47-2e2d63ca6e18.png)

https://www.inaturalist.org/home?tab=updates
![image](https://user-images.githubusercontent.com/15896181/38631533-e1b86cf4-3d6e-11e8-9a98-6ae2c7cf83de.png)

https://www.inaturalist.org/subscriptions
![image](https://user-images.githubusercontent.com/15896181/38631554-eac4df9e-3d6e-11e8-82d6-389a81a85306.png)

https://www.inaturalist.org/people/jornari/followers
![image](https://user-images.githubusercontent.com/15896181/38631568-f2467804-3d6e-11e8-88db-9ee3c1b9abbf.png)

https://www.inaturalist.org/taxa/627586-Gulenia-orjani/browse_photos
![image](https://user-images.githubusercontent.com/15896181/38631581-fb83cb9c-3d6e-11e8-80c9-3fc2d2cebb10.png)

![image](https://user-images.githubusercontent.com/15896181/38631590-0078b2e8-3d6f-11e8-9180-9797f6c3d6ef.png)

https://www.inaturalist.org/taxa/627586/taxon_names/new
![image](https://user-images.githubusercontent.com/15896181/38631606-0a02b78c-3d6f-11e8-986b-e4ac7fb7b174.png)

https://www.inaturalist.org/people
![image](https://user-images.githubusercontent.com/15896181/38631616-13492b96-3d6f-11e8-9eef-7325c4faf045.png)

https://www.inaturalist.org/guides/7178/edit
![image](https://user-images.githubusercontent.com/15896181/38631625-1a26d3c8-3d6f-11e8-8abd-cae52b9cba34.png)

![image](https://user-images.githubusercontent.com/15896181/38631636-250a3dfc-3d6f-11e8-8016-8d9219bd9127.png)

https://www.inaturalist.org/guide_taxa/779176/edit
![image](https://user-images.githubusercontent.com/15896181/38631646-2cc59622-3d6f-11e8-99f7-9d686f78bc71.png)

![image](https://user-images.githubusercontent.com/15896181/38631673-3f393ea8-3d6f-11e8-8ae5-678166eb9cf8.png)

![image](https://user-images.githubusercontent.com/15896181/38631658-36a12670-3d6f-11e8-9476-3e31e801d13b.png)

![image](https://user-images.githubusercontent.com/15896181/38631691-4f3c8710-3d6f-11e8-9932-a32db964e0c0.png)

![image](https://user-images.githubusercontent.com/15896181/38631697-532bbaee-3d6f-11e8-91b8-f4ddd02013d0.png)

**Comment by kueda** [comment]
I dealt with most of these, mostly globalizing some things that weren't properly globalized (and thus weren't in translatewiki). Some I'm not going to deal with or are simply not appropriate for translation, including

* Example CSV at https://www.inaturalist.org/observations/import#csv_import
* Example HTML tags
* Anything that has to do with assessments (they're like in the sub-sub-sub-shed)
* Scientific iconic taxon names that are the same for everyone
* Text we don't control like photo attribution from EOL
