### ISSUE TITLE
Project Bug - Can't make someone a Manager

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1729]
"The project is called: "[Central Coast & Surrounds - UC California Naturalist Project](https://www.inaturalist.org/projects/central-coast-surrounds-ucsc-california-naturalist-project)".
The Admin is Brett Hall and he and I share access to the account via his sign in but I would like to be formally added as a manager. I am currently assistant admin for this project but not via iNaturlist. My iNaturalist username is"samanthaspurlin".
Brett tried to add me as "Manager" under Project Members but we receive the following error message: "Project user cannot be found". And the really odd part is that it seems to take us to a different project called "123" whose admin is floralin92."

When signing in as Brett I was able to replicate this issue.

**Comment by kueda** [comment]
Not sure what was going on here but I can no longer replicate it.
