### ISSUE TITLE
Profile Photo not changing

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1737]
A user wrote in and told me her profile pic hadn't changed, several hours after she uploaded a new photo. So I changed my profile photo via the web on Friday, April 20th (uploading a photo of an Ocotillo flower). A few hours later the new pic showed up in the iOS app in a few places, like on Obs Show, but nothing changed on the web. During the weekend my profile pic changed in most places where it is displayed small (IDs, Comments, etc) but today (Monday, April 23rd) my main profile pic still hasn't changed:

![image](https://user-images.githubusercontent.com/15896181/39160383-e792882a-471f-11e8-8ecf-0d85a34689a1.png)

**Comment by kueda** [comment]
I think I fixed this specific problem yesterday, but #1272 remains the source of our rotation problem.
