### ISSUE TITLE
Use GADM admin levels for place names in csv exports

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1744]
Presently, it appears that we only populate ``place_state_name`` in exports when the administrative unit is called a state. That means that for most other countries, exports do not provide useful information for separating out observations based on the ``place_state_name`` field. 

Proposal: In csv exports,
- [ ] Use GADM admin level 1 names to populate ``place_state_name``
- [ ] Use GADM admin level 2 names to populate ``place_county_name``

I found surprisingly little documentation at GADM.org about the levels (though they did mention the next version should be available this month).

**Comment by kueda** [comment]
How about adding `place_admin1_name`, `place_admin2_name`? Less obvious what they mean, but avoids the situation where you get County Wexford in Ireland or Quebec Province in Canada under the `place_state_name` column.

**Comment by kueda** [comment]
In addition, I don't think it's worth removing things at the moment.

**Comment by carrieseltzer** [comment]
Ok. When exporting data from the US those fields will look redundant, but I think that's ok.
