### ISSUE TITLE
Cannot make user who "joined" collection project via mobile an admin of said project

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1746]
If someone "joins" a collection project via mobile (so far I've tested only iOS but I imagine it works for both platforms), then they cannot be made an admin of said project. This error is returned:

![image](https://user-images.githubusercontent.com/15896181/39412543-f03264c0-4bd2-11e8-9537-beaefc838d64.png)

If one then goes to the project's webpage and clicks "unfollow" I think they still can't be added as an admin.

If one leaves a project via mobile, they can be added as an admin.

**Comment by kueda** [comment]
I think this is probably pending the discussion on what to do about joining / following projects.

**Comment by pleary** [comment]
This should actually be fixed now, if you want to check @tiwane . But definitely more to talk about next week

**Comment by pleary** [comment]
Fixed in d29242e
