### ISSUE TITLE
Fix place geom self-intersections or give users an error

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#1748]
Related to #1633 . Need to fix self-intersections in geometries, which psql is happy to accept, but ES is not.

https://www.inaturalist.org/places/moulton-valley-limestone-glades used to be an example but was manually fixed on 4/30 by using `Place.clean_geometry`

**Comment by kueda** [comment]
Looks like we already index based on `PlaceGeometry#simplified_geom`, which runs `cleangeometry`, which should remove self-intersections, right?

**Comment by pleary** [comment]
This should be fixed in a72ea53. Geometries with `bbox_area` less than 0.1 were not getting simplified, and were not getting run through `cleangeometry`. The fix just makes sure even these small geometries get a pass through `cleangeometry` before going into Elasticsearch.
