### ISSUE TITLE
"Inactive Taxon" label gets pushed off of photo in grid view for collection projects

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1757]
Via bouteloua:

![image 1](https://user-images.githubusercontent.com/15896181/39559904-9a47e61a-4e4e-11e8-8d06-d6f4f2e023d6.png)

**Comment by cmcheatle** [comment]
Unrelated, but it is the same screen, so maybe it can be fixed at the same time, it seems to be the only screen I can find where if you have common names listed first, the scientific name is not shown in brackets. It doesnot show on the screenprint above as it has the reverse order.

**Comment by kueda** [comment]
URL? I can't seem to replicate this locally.

**Comment by tiwane** [comment]
Here's the URL cassi gave me: https://www.inaturalist.org/projects/city-nature-challenge-2018-chicago-wilderness-region?tab=observations

**Comment by kueda** [comment]
Not seeing anything there, and I don't think I can replicate this in a more production-like environment, so I'm going to close. If you notice this again, please holler.
