### ISSUE TITLE
And links to View All Results Page

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1767]
Via bouteloua: can we add helpful taxon links to the "View All Results" page? 

Create New Taxon, Search External Name Providers, and Flag for Curation (maybe?).

![search-missingresults_inat](https://user-images.githubusercontent.com/15896181/39852913-2dd9b0ae-53d4-11e8-9900-651d8d364c91.png)

**Comment by kueda** [comment]
Should be handled in a532d61325188de50064688e4e9576a6a57ab9f0
