### ISSUE TITLE
Populate the first section of lexicons with the ones we have translated 

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1768]
For some lexicons on the Add a Common Name page, such as French, we will translate the language to match the user's locale. My locale is English, so I see French listed as "French". Other users have added lexicons (lexica?) using the proper name of their language, eg Francais. 

This becomes confusing when a user with their locale set to French tries to add a common name because the lexicon that iNat has added will be translated to appear as "Francais" and will be listed right next to the "Francais" lexicon added by someone else.  

If we could list the languages iNaturalist has added in the top section of the list, that should reduce some of this confusion.

**Comment by kueda** [comment]
Mostly fixed in 6645467, some additional stuff in d7e0ba1ed0efe889cba0d16980d290bebdfd67c4
