### ISSUE TITLE
Map improvements

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#177]
Maps capable of rendering large amounts of data quickly would greatly improve iNat's utility for visualizing biodiversity data.

A mapping system with the following features would be desireable:
1) Zooming out renders a density grid
![map_work2](https://f.cloud.github.com/assets/598026/1603445/8dc4a228-53aa-11e3-8629-8650a7fc7559.png)

2) Zooming in renders individual markers with clickable infowindows
![map_work](https://f.cloud.github.com/assets/598026/1603444/833495d4-53aa-11e3-8a2b-d0cca276bca6.png)

3) Markers distinguished between obscured/open wild/captive and casual/research grade

Are there any more features generalizable across all maps I'm forgetting?

iNat currently has maps in the following views each of which would need slight modifications:

A) /welcome
This map is useful for showing recent activity - 
Perhaps restrict this map to calendar day?

B) /observations/index
Keep Map/Sidebar layout and have mousing over of obs components in sidebar make them appear on the map?
Or switch to Grid/List/Map view?

C) /observations/:id/show
Always show obs as a marker
But also overlay all other obs on map
Toggle button to filter all obs/obs of same taxa?

D) /calendar/:login/date/
Restrict to calendar day & user?

C) /projects/:id/show
Restrict to project observations?

D) /places/:id/show#observatins_tab
Restrict to observations from within place?

E) /taxa/:id/show
Restrict to taxon
also render:
a) taxon range
b) GBIF points for that taxon
c) listed taxa as in /taxa/:id/map - styles to distinguishes present/absent, native/endemic/introduced, confirmed/reported on listed taxa geometries

**Comment by kueda** [comment]
I'm going to close this since most of it is done, but for the record, still todo:

* CHECKLISTED PLACE BOUNDARY LAYER
* GBIF OCCURRENCE LAYER

We should probably make separate issues for these
