### ISSUE TITLE
Link to actual flag on Curate Taxa page

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1774]
On our [Curate Taxa page](https://www.inaturalist.org/taxa/curation), clicking "view" for a flag takes you to the taxon's page and not to the flag itself. Can this link be changed to take you directly to the flag itself?

**Comment by kueda** [comment]
Tony reported that taxa with deleted flags are still showing the indicdator, so we may not be reindexing taxa after flags have been deleted.
