### ISSUE TITLE
Have search on projects/index search places used a project's observation rule(s)

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1778]
The way we currently search on projects/index does not return collection projects in Canada because it is searching only project place associated and not the places used in a project's observation rules. Can we search the latter as well?

**Comment by kueda** [comment]
Should be closed by #1782

**Comment by tiwane** [comment]
[This project](https://inaturalist.ca/projects/mcintosh-run-biodiversity-project) is not showing up in https://inaturalist.ca/projects search. But it should, yes?
