### ISSUE TITLE
project.place_id causing problems on project conversion

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1784]
https://www.inaturalist.org/projects/herps-of-southern-africa was a traditional project with a project.place_id of a continent and some conflicting must_be_in_place rules at the country level (not sure why) - in any event, when converted to  a collection project this project.place_id seems to still be there and is acting as an obs filter even though it doesnt appear as a place under Observation Requirements -> places

**Comment by tiwane** [comment]
Possibly another example of this here: https://www.inaturalist.org/projects/hoboken-waterfront-biodiversity-bioblitz-2018
