### ISSUE TITLE
Choose to have scientific or common names appear over observation thumbnails in app

### ISSUE THREAD

**Issue by kevinliam** [inaturalist/inaturalist#1794]
Hello,

Is it possible to allow users to select whether common or scientific names (or perhaps both!) appear over observation thumbnails? I'd like to be able to scroll through the thumbnails and brush up on the scientific names, as the common names can be misleading in terms of relatedness to other species.

Thank you!
Kevin

**Comment by kueda** [comment]
For new feature dev, please make suggestions in [our Google Group](http://groups.google.com/group/inaturalist/) or email help@inaturalist.org. We mostly use github for issues that engineers can take action on immediately, and stuff like this probably warrants a bit of discussion first. Not personally opposed to the proposal, though.
