### ISSUE TITLE
Indexing some taxa causes an infinite loop

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#1802]
For example `Taxon.find(158534).elastic_index!` causes an error `SystemStackError: stack level too deep`. This in turn causes some delayed jobs to fail and get stuck in the queue (I'll create another ticket for this). Seems like it might be related to queries for taxon changes

**Comment by kueda** [comment]
Had to deal with something like this in 6a9d5a8720caf6b441099d0f275c7feee43ed513, so this might be my bug.
