### ISSUE TITLE
Life Lists not Syncing

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1808]
Lists are buggy, but I thought I'd make a formal bug report, and Patrick suggested it as well. This user's [list](https://www.inaturalist.org/lists/794332-Yard-List) displays some taxa that he has observed, but in some instances those taxa are not linked to any of his observations, eg Thamnophis sirtalis and Automeris io. I tried reloading from observations, but nothing changed. 

<img width="250" alt="screen shot 2018-06-08 at 10 42 40 am" src="https://user-images.githubusercontent.com/15896181/41172431-b6aa8048-6b08-11e8-8d00-9b1bbb925c86.png">

**Comment by carrieseltzer** [comment]
Here is another example and symptom of what appears to be the same underlying issue.

https://www.inaturalist.org/lists/1362369-jdietrchs-Life-List?observed=any&page=1&q=&rank=leaves&taxonomic_status=active&view=plain

This user's life list total currently shows 6 of 14 taxa observed, but adding up each iconic taxon total equals 14. 

![screen shot 2018-10-10 at 9 20 23 pm](https://user-images.githubusercontent.com/7501183/46774826-5a996180-ccd2-11e8-9527-bb5b4fc0a6d6.png)

As described above, there are "view all" links missing from several taxa. For both users, the number of taxa with "view all" links equals the number of taxa shown as "observed" in the gray bar.

**Comment by carrieseltzer** [comment]
Scott, how do you know that in Tony's example the taxa were manually added? I had assumed in both cases that no species were manually added (user in my case confirmed no manual additions to the list).

**Comment by loarie** [comment]
Click on the listed_taxon and see that the source https://www.inaturalist.org/listed_taxa/21014629 is a user (not an observation)

**Comment by tiwane** [comment]
Closing this as we now have the dynamic life list.
