### ISSUE TITLE
Malformed spanish translations

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#1816]
In a8fe587 I removed 3 translations which had incorrect syntax. They were translations for pluralizable strings which contained the `other` form, but not the `one` form. It looks like maybe they used some other embedded syntax for pluralization that isn't one that works with our I18n plugin.

I'm not sure what the action is here. We should probably alert TranslateWiki of the incorrect syntax and find out if they added it or a translator. And we should make sure we don't merge in the same problem when we next pull in updates from TW

**Comment by kueda** [comment]
IMO, action is to check for this in a QA script ( #1818) and update the `qqq.yml` for these keys to notify translatewiki translators that plural keys must have both `one` and `other` forms.

**Comment by kueda** [comment]
Patrick removed the offending translations, and I modified the script from #1818 to check for them in the future.
