### ISSUE TITLE
Remove PDF generation for guides

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1819]
When clicking on "Generate PDF" for a Guide that is available for download (eg https://www.inaturalist.org/guides/7726) I get this:

![image](https://user-images.githubusercontent.com/15896181/41309436-a5280218-6e33-11e8-9f9a-1d9afa5eda45.png)

Clicking on Print/Preview then opening up a PDF does work as a workaround.

**Comment by kueda** [comment]
Any objection to just removing the PDF generation? You can basically do the same thing in any browser by printing as a PDF.

**Comment by tiwane** [comment]
No objection.
