### ISSUE TITLE
Login via Twitter results in whale shark error

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1821]
That's about it.

**Comment by kueda** [comment]
Should be fixed now. Twitter changed their policies and you now have to pre-approve every requested callback URL you use with a given set of credentials, i.e. the page on the website the user will return too after they approve the connection on twitter. The only one we had in the configs (https://apps.twitter.com/app/951541/settings) used http://www.inaturalist.org as the protocol/host, when we needed to use https. I also added callback URLs for naturalista.mx, inaturalist.nz, iaturalist.ca, and naturalista.biodiversidad.co. We'll need to add more for more partner sites in the future.

**Comment by tiwane** [comment]
Yup, looking good. Thanks.
