### ISSUE TITLE
Possibility to export project_id in the Dwc-A

### ISSUE THREAD

**Issue by cgendreau** [inaturalist/inaturalist#1828]
I was wondering if it would be possible to export the project_id of each observation (if they belong to one) ?

I don't think there is an obvious term to use at the Occurrence level. Maybe `datasetId` but since `datasetName` already contains the value "iNaturalist research-grade observations" it would be strange.

It might be possible to use the [Identifier extension](https://tools.gbif.org/dwca-validator/extension.do?id=gbif:Identifier) but that's probably more work to implement.

Thanks

**Comment by kueda** [comment]
We generate several DwC-A files for different purposes, and their content is generally intended for a specific partner, not for general use. We don't have a partner that requires project IDs, and even if we did I think we'd recommend they scrape data using the API instead, which is iNat-specific and has iNat-specific content like project identifiers. If project IDs are something you really need, I'd suggest using the API to retrieve them.

**Comment by cgendreau** [comment]
Thanks for your answer @kueda .
The main reason was to simplify aggregation of data. It is indeed possible to use the API but we need to do the mapping (and repeat that for all APIs we want to use). It is simply easier (for us) to get the data as Dwc-A (or maybe JSON-LD API response). That been said, I understand the iNat-specific part of it and using the API will give us what we need at the end.

Note: Just one clarification, the idea was more to query by project_id than to actually get its value for a specific observation. In other words, an export of my query as Dwc-A would also work for us.
