### ISSUE TITLE
Update all NatureWatch urls to direct to iNaturalist NZ

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1833]
With the changeover from naturewatch.org.nz to inaturalist.nz, NZBRN has requested that we update the urls. 

The mission: Find naturewatch.org.nz site-wide and replace with inaturalist.nz.

**Comment by Murray-Dawson** [comment]
That would be fantastic! It’s also a change in the links from http to https

There are a couple of comments on this from an eager community at https://inaturalist.nz/posts/16686-nature-watch-in-new-zealand-with-inaturalist-nz

Murray

**Comment by mjon** [comment]
Thanks Carrie.

For links in most places (like comments, observation descriptions), the domain name could also be removed altogether. That would make these links play nicely across all the iNat Network partners. So `https://inaturalist.nz/observations/13895518` could just be 
`/observations/13895518` if inside an `<a href>` tag.

Jon

**Comment by mjon** [comment]
Let us know if there's a way we can help with this.

**Comment by pleary** [comment]
I assume there will be some exceptions, for example the post and comments at https://www.inaturalist.org/posts/16686 . I wonder if we should only convert links from content creates before 2018-05-21 which is when the domain changed.

**Comment by pleary** [comment]
This is all set. We updated about 7,000 observations, 800 identifications, 16,000 comments, and a bunch of observation field values
