### ISSUE TITLE
Observations of taxa which are automatically set to private show up in non-county/state level places when searching

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1840]
For example, Wood Turtles are supposed to automatically get a geoprivacy of Private in Ontario, but three wood turtle observations show up when you search Algonquin Provincial Park: https://www.inaturalist.org/observations?place_id=90295&subview=grid&taxon_id=39865

Possibly linked to issue #1839?

**Comment by kueda** [comment]
Actually I take it back, I did not predict this specific problem, though this may be related to that issue. Or maybe there's some delayed job that didn't finish that was supposed to reindex those obs. Will investigate.

**Comment by tiwane** [comment]
I know you're crazy busy, but they asked if we have any updates here. Just let me know.
