### ISSUE TITLE
Stop auto-capitalizing translated strings

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1844]
In order to appropriately deal with the various conventions for capitalization in different languages, auto-capitalization should not be applied to translatable strings, and instead capitalization should be taken directly from the translated strings. This means there will be separate strings where the only difference is capitalization, e.g. a single string "observation" will become "Observation" and "observation" to allow for appropriate translation of capitalization. (Hope I've captured this appropriately). 

This should be done for strings for:
- [ ] website
(separate issues for Android and iOS)

**Comment by kueda** [comment]
FWIW, issues in this repo should just concern code in this repo, i.e. the website, so we should probably make separate issues in the iOS and Android repos if this is a problem there too. For personal reference, we need to remove almost all uses of:

- [ ] `_.startCase()`
- [ ] `text-transform: capitalize`

**Comment by kueda** [comment]
I think this is basically done. If there are new problems let's just open new issues.
