### ISSUE TITLE
Observations from suspended users showing up in Identify

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1846]
User maxallen is seeing observations from users who have been marked as spam in his Identify search, which is https://www.inaturalist.org/observations/identify?iconic_taxa=unknown&place_id=97395 eg:

<img width="1230" alt="screen shot 2018-07-09 at 1 57 50 pm" src="https://user-images.githubusercontent.com/15896181/42475676-2b368116-8380-11e8-8b08-d6872c71b287.png">

When he tries to mark them as reviewed, we return a 403 because the user has been suspended. And they don't get removed from his Identify search.

**Comment by kueda** [comment]
Do you remember if he was including Casual observations, or were these showing up with the default filters?

**Comment by tiwane** [comment]
Judging from that link, it doesn't look like it.
