### ISSUE TITLE
Listed taxon observation links lead to nowhere

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1848]
From bouteloua:

For example: https://www.inaturalist.org/flags/257924

-Navigate to https://www.inaturalist.org/listed_taxa/8861759
-Click "refresh" on left side of page where it says "0 observations"
-Leads to https://www.inaturalist.org/listed_taxa/refresh_observationcounts?listed_taxon_id=8861759 (sorry that doesn't exist)

-Click "0" where it says "0 observations"
-Leads to https://www.inaturalist.org/observations?taxon_id=77614&user_id=twillrichardson (1 observation of this taxon)

From Tony:

Here's what the console displays when clicking "0"

<img width="556" alt="screen shot 2018-07-12 at 5 18 21 pm" src="https://user-images.githubusercontent.com/15896181/42666071-ad2683b4-85f7-11e8-919e-15eb322d458d.png">

**Comment by natureali** [comment]
See this taxa also for the same problem. https://www.inaturalist.org/listed_taxa/21904660
