### ISSUE TITLE
Collection Projects About text won't wrap on main project page if there's a URL in it

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1851]
See:

https://www.inaturalist.org/projects/sf-dragonflies
https://www.inaturalist.org/projects/mycoflora-of-forest-park

Alex noted that if there's a breakable character early in the URL it will wrap correctly.

**Comment by alexshepard** [comment]
it doesn't even need to be a url, just a very long word without a breakable character (like a hyphen)
