### ISSUE TITLE
Have ORCID as a connected iNaturalist account

### ISSUE THREAD

**Issue by peterdesmet** [inaturalist/inaturalist#1857]
I would like to:

1) link my ORCID (https://orcid.org) with my iNaturalist account (i.e. have it as one of the connected accounts)
2) have the ORCID included in the Darwin Core data published to GBIF.

It could be included either as (will allow searches on ORCID in GBIF today):

```
recordedBy: Peter Desmet | https://orcid.org/0000-0002-8442-8025
```

or (nicer, but doesn't work yet):

```
http://rs.tdwg.org/dwc/terms/recordedBy: Peter Desmet
http://rs.tdwg.org/dwc/iri/recordedBy: https://orcid.org/0000-0002-8442-8025
```

**Comment by kueda** [comment]
@peterdesmet, can you confirm that `recordedBy: Peter Desmet | https://orcid.org/0000-0002-8442-8025` is still the best way to push this data to GBIF? Does GBIF actually parse that in any way, or do you just want *some* way to search the text of a GBIF export for an ORCID ID?

**Comment by kueda** [comment]
@dnoesgaard, perhaps you could answer this question? Is GBIF supporting `http://rs.tdwg.org/dwc/iri/recordedBy` at present, and/or is there a better way to incorporate ORCID IDs in a DwC-A for GBIF to ingest?

**Comment by peterdesmet** [comment]
GBIF does not parse that right now, so yes: basically a way for me to search, so i can understand if you do not want to implement this as such.

There is an increased interest in assigning ORCIDs to observations/specimens though. @timrobertson100 are there plans at GBIF to implement support for this?

**Comment by timrobertson100** [comment]
@kueda - GBIF doesn't currently recognise any `iri` namespace content.

GBIF need a way to support ORCIDs on records. We haven't designed how we would want to achieve that (be it IRI or some other format)

**Comment by kueda** [comment]
@timrobertson100, is there any harm in using pipe-separated values in the `http://rs.tdwg.org/dwc/terms/recordedBy` field as Peter suggested? We (at iNat) were also wondering if there was a non-intrusive way we could put iNaturalist usernames in the DwC-A exports for another partner, so the `recordedBy` field might look like

```
Ken-ichi Ueda | @kueda | https://orcid.org/0000-0003-0145-6846
```

The only problem I see with that is that it seems like the intent of the pipe-separated values was to identify separate individuals who made the recording, and not separate identifiers for the same individual.

Alternatively, we could do something like Peter proposed and use

```
http://rs.tdwg.org/dwc/terms/recordedBy: Peter Desmet
http://rs.tdwg.org/dwc/iri/recordedBy: https://orcid.org/0000-0002-8442-8025
http://xmlns.com/foaf/spec/#term_nick: peterdesmet
```
or maybe

```
http://www.inaturalist.org/terms/username: peterdesmet
```

to emphasize that it's an iNat username, but I don't think either of those would serve Peter's desire to search GBIF records for an ORCID ID.

**Comment by kueda** [comment]
@peterdesmet I can't move forward with this unless I get answers to my questions above, which seems like it's not going to happen, so I'm going to close. We can re-open if the situation changes.

**Comment by timrobertson100** [comment]
> unless I get answers to my questions above, which seems like it's not going to happen

Sorry @kueda - I was out a lot in 2018 but am back now.

> The only problem I see with that is that it seems like the intent of the pipe-separated values was to identify separate individuals who made the recording, and not separate identifiers for the same individual.

Yes. That would not be very portable.

I'd suggest going for `http://rs.tdwg.org/dwc/iri/recordedBy` or perhaps a better option (@peterdesmet ?) is `http://rs.gbif.org/terms/1.0/recordedByOrcid`.

The reality is that having the same term in 2 namespaces does not work for cell headers when used as spreadsheet data so I tend to think is better than half adopting IRIs (there are plenty of other fields one could question why are not using it).

If we went with a GBIF namepsace `recordedByOrcid` we could consider it an interim solution while this kind of thing settles?

**Comment by kueda** [comment]
Ok, ready to go with `recordedByOrcid` on our end. Just let us know when you're ready to process it at GBIF. If `http://rs.gbif.org/terms/1.0/recordedByOrcid` is going to be temporary, it would still be nice if it resolved to a page on GBIF explaining what it means and that it's temporary.

**Comment by MattBlissett** [comment]
I'll comment here so others see it.

Following the form of the existing DWC terms, should this be `recordedByID` (`http://rs.gbif.org/terms/1.0/recordedByID`), to allow for other identifiers? [ORCiD lists some](https://support.orcid.org/hc/en-us/articles/360006894854-Add-person-identifiers-other-identifiers-to-your-ORCID-record)

(Or maybe we want to get away from what could then be a multivalue field.)

**Comment by kueda** [comment]
I'm just going to merge in what we have on our end with `recordedByOrcid` since it shouldn't interfere with GBIF's existing ingestion process. If GBIF would like us to use a different term for the ORCID, please let us know.

**Comment by dshorthouse** [comment]
For what it's worth, I make use of the IRI namespace for recordedBy and identifiedBy on https://bloodhound-tracker.net and also have nowhere for these to go. There's been an interesting use-case of images taken of plants in the field submitted to iNaturalist prior to collection & then digitized elsewhere. See https://twitter.com/PirieMike/status/1116636814385852418. Strikes me that there's a nice opportunity here to put some pieces together by combining existing data.
