### ISSUE TITLE
Batch adding taxa to lists results in whale shark error if taxa aren't on iNaturalist

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1858]
For example, pasting this list into Batch Add will result in the whale shark. 

Lyophyllum transforme
Lyophyllum tylicolor
Macowanites candidus
Macrocystidia cucumis
Macrocystidia cucumis var. latifolia
Macrocystidia cucumis var. leucospora
Macrolepiota excoriata
Macrolepiota fuligineosquarrosa
Macrolepiota fuliginosa
Macrolepiota mastoidea
Macrolepiota permixta
Macrolepiota procera
Macrotyphula fistulosa
Macrotyphula juncea
Marasmiellus candidus
Marasmiellus humillimus
Marasmiellus perforans
Marasmiellus ramealis
Marasmiellus tricolor
Marasmiellus vaillantii
Marasmius anomalus
Marasmius bulliardii
Marasmius cohaerens
Marasmius collinus
Marasmius curreyi
Marasmius epiphylloides
Marasmius epiphyllus
Marasmius hudsonii
Marasmius limosus
Marasmius minutus
Marasmius oreades
Marasmius rotula
Marasmius torquescens
Marasmius wettsteinii
Marasmius wynnei
Marchandiomyces corallinus
Marchandiomyces quercinus
Megacollybia platyphylla
Melampsora allii-fragilis
Melampsora allii-populina
Melampsora amygdalinae
Melampsora caprearum
Melampsora epitea
Melampsora euphorbiae
Melampsora hypericorum
Melampsora laricis-pentandrae
Melampsora laricis-populina
Melampsora lini
Melampsora lini var. liniperda
Melampsora populnea
Melampsora ribesii-viminalis
Melampsora salicis-albae
Melampsora vernalis
Melampsorella caryophyllacearum
Melampsorella symphyti
Melampsoridium betulinum
Melampsoridium hiratsukanum
Melanogaster ambiguus
Melanogaster broomeanus
Melanogaster macrosporus
Melanogaster tuberiformis
Melanoleuca atripes
Melanoleuca brevipes
Melanoleuca cinereifolia
Melanoleuca cognata
Melanoleuca exscissa
Melanoleuca exscissa var. exscissa
Melanoleuca exscissa var. iris
Melanoleuca friesii
Melanoleuca grammopodia
Melanoleuca melaleuca
Melanoleuca microcephala
Melanoleuca nivea
Melanoleuca polioleuca
Melanoleuca polioleuca f. langei
Melanoleuca polioleuca f. pusilla
Melanoleuca polioleuca var. polioleuca
Melanoleuca rasilis
Melanoleuca schumacheri
Melanoleuca strictipes
Melanoleuca subpulverulenta
Melanoleuca verrucipes
Melanomphalia nigrescens
Melanophyllum eyrei
Melanophyllum haematospermum
Melzericium bourdotii
Melzericium udicola
Mensularia nodulosa
Mensularia radiata
Meottomyces dissimulans
Meripilus giganteus
Merismodes anomalus
Merismodes fasciculata
Merismodes granulosa
Merismodes ochracea
Merulicium fusisporum
Meruliopsis corium
Meruliopsis taxicola
Microbotryum scabiosae
Microbotryum stellariae
Microbotryum violaceum
Microsebacina microbasidia
Milesia magnusiana
Milesina blechni
Milesina dieteliana
Milesina feurichii
Milesina kriegeriana
Milesina murariae
Milesina scolopendrii
Minimedusa polyspora
Miyagia pseudosphaeria
Mucidula mucida
Mucronella bresadolae
Mucronella calva
Mucronella flava
Multiclavula vernalis
Muscinupta laevis
Mutinus caninus
Mutinus ravenelii
Mycaureola dilseae
Mycena abramsii
Mycena acicula
Mycena aciculata
Mycena adonis
Mycena adonis var. coccinea
Mycena aetites
Mycena alba
Mycena albidolilacea
Mycena algeriensis
Mycena alphitophora
Mycena amicta
Mycena arcangeliana
Mycena atropapillata
Mycena aurantiomarginata
Mycena belliae
Mycena bulbosa
Mycena capillaripes
Mycena capillaris
Mycena chlorantha
Mycena cinerella
Mycena citrinomarginata
Mycena clavata

**Comment by cmcheatle** [comment]
Just to clarify the title of the issue, I don't think the issue is related to a species in the list not being present in the database. I've successfully processed lists for this task where many items are not in the database, it runs fine and in the summary after execution simply shows which taxa were not found. You can actually see this visually in the 1st screenprint in this unrelated item on the google group : https://groups.google.com/forum/#!topic/inaturalist/LXq-7ufRk94

It's not the size of the list, I've successfully loaded lists of 999 items multiple times. I'm guessing perhaps there is something in one of the values, perhaps the length of the string it does not like.
