### ISSUE TITLE
Don't allow taxa to be grafted to an inactive taxon

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1862]
bouteloua suggests that marking a taxon inactive, either 1) manually through the edit page, or 2) through a taxon swap, should also automatically lock it from having new taxa grafted onto it. Sometimes auto imports from EOL will get grafted onto an inactive taxon.

**Comment by kueda** [comment]
Pretty sure this was handled in https://github.com/inaturalist/inaturalist/pull/1920 and more specifically  https://github.com/inaturalist/inaturalist/commit/ab6a40dcb03ec8723de21af8e646a0f96cd36f2e
