### ISSUE TITLE
Emphasize exact match in header search result

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1867]
via bouteloua:

Some taxa, like the mussell genus _Unio_, are difficult to find when using the header search. Here's what you get when you type in unio:

![image](https://user-images.githubusercontent.com/15896181/43501616-3b190684-950b-11e8-8c58-44b09d02e26e.png)

Would it be possible to give more weight to exact matches?

**Comment by kueda** [comment]
Some work toward this in https://github.com/inaturalist/iNaturalistAPI/commit/cef827f5c2104b3aec6c724af27b32035112bfc9, basically just giving more weight to taxa in search results.
