### ISSUE TITLE
Uploader no longer accepts photos dragged and dropped directly from Apple Photos

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1872]
Some users have, in the past. dragged and dropped photos directly from Apple Photos into the uploader but that apparently doesn't work anymore, do varying degrees in different browsers. From my testing:

Chrome: dragging photos does nothing. The photos do condense into a stack with a red number but that's it. Nothing in console.

Safari: I can drag and drop one photo at a time. Any more than that and nothing works. Nothing in console.

Firefox: Dragging and dropping does nothing. But console does return this:

![image](https://user-images.githubusercontent.com/15896181/44012183-16dc86b8-9e72-11e8-90ab-1316803c97cd.png)

**Comment by pleary** [comment]
Are you sure you were able to do this before? I know that Apple changed how drag-and-drop worked when they switched from iPhoto to Apple Photos. See https://groups.google.com/d/topic/inaturalist/YE-isTZbZJ0/discussion and the linked post. I believe Apple limited drag-and-drop from Photo to their own apps (Mail, Desktop, Safari, etc.). And even with that I think you lose geolocation info, and the only way to get that is by exporting from Photos.

**Comment by tiwane** [comment]
Thanks Patrick. I'll clarify with the user to specify which app she's using. She said "iPhoto" but I'm assuming she's using Photos, which has been out for a few years, I believe.

**Comment by pleary** [comment]
I believe this is beyond our control so I'll close this. Please re-open if I'm mistaken and there are steps to reproduce the issue
