### ISSUE TITLE
Search dialogue uses wrong date range string

### ISSUE THREAD

**Issue by ptalvistu** [inaturalist/inaturalist#1882]
![search](https://user-images.githubusercontent.com/38881755/44568072-d6206d00-a77d-11e8-8d19-fda361ae8f17.jpg)
It seems that the search dialogue for observations is not using the string Date picker.range for the ranges. 
Also can we stop with the forced capitalization of words! Or maybe we can add an option to each language which specifies whether capitalization of every word should be used. Here "Needs ID", "Has Sound", "Has Photo", "Photo Licensing", "Your Observations" all seem to be forcing the capitalization of every word although even the original "Has sound" doesn't capitalize the second word. I'm not completely sure if this is correct in English, but it is definitely not correct in Estonian. Hence, an option for each translated language about which method of capitalization to prefer could maybe be implemented? OR the code could respect the original translation (this wouldn't, however, solve the problem with species names that work in the same way).

**Comment by kueda** [comment]
We'll deal with capitalization in #1844 (not a trivial change). I'm not sure I understand the problem with the translation of "Range." Are you saying the word "Piirkond" does not apply to dates in Estonian and we need a new translatable string there?

**Comment by ptalvistu** [comment]
iNaturalist uses Range to denote both the area of a species (Piirkond) and a range of dates (Vahemik). Altogether there are three "Range" strings on Translatewiki: Date picker.range, Map.overlays.range and Range. I would assume that the first is used for dates, the second to place areas on maps and the third for the areas themselves. Hence I have translated the first as Vahemik and the others as Piirkond. However, it appears that the site is using one of the other two range strings here although there clearly exists Date picker.range that would be perfect for this instance.

**Comment by kueda** [comment]
Should have been fixed in 174c0a48b814930cbc567885b704bf6bf9f4bb95
