### ISSUE TITLE
Date format and wrong capitalization on observation page

### ISSUE THREAD

**Issue by ptalvistu** [inaturalist/inaturalist#1884]
![map](https://user-images.githubusercontent.com/38881755/44568577-197bdb00-a780-11e8-8409-dd4fc8a99c28.jpg)
On observation pages, the hovers for next and previous buttons don't seem to get any capitalization at all (unlike the species names elsewhere) and the date format doesn't seem to come from translatewiki.

**Comment by ptalvistu** [comment]
Translatewiki contains a bunch of strings that are used for date formatting but I am pretty sure I haven't encountered this string because I have moved the day in front of the month in all the other formatting strings. Does the formatting here come from Translatewiki?

**Comment by ptalvistu** [comment]
Also, it seems that the page title (the one in the head section of the html) is not capitalized for taxon pages.

**Comment by kueda** [comment]
Ok, I made the date formatting subject to translation on obs detail, but it will take at least a week for the new string to show up in translatewiki. I can't replicate the page title issue but that seems separate. If you can replicate, please make a new issue and be sure to include URLs, screenshots, etc.
