### ISSUE TITLE
Non translatable strings on observation page

### ISSUE THREAD

**Issue by ptalvistu** [inaturalist/inaturalist#1885]
![observation](https://user-images.githubusercontent.com/38881755/44568795-ef76e880-a780-11e8-94b8-2a6b9eb1adb1.jpg)
It seems that the observation page contains at least two locations where the strings are untranslatable?

**Comment by ptalvistu** [comment]
![view observations](https://user-images.githubusercontent.com/38881755/44568947-74fa9880-a781-11e8-818e-ed23c6024c4d.jpg)
Also the view observations string seems to be missing from translatewiki?

**Comment by kueda** [comment]
Casual / Needs ID / Research Grade on the obs detail page def. needs translating. I'm not seeing the second spot, unless you're referring to the test notice at the bottom, which is just a temporary test and thus not something we translate. The view observations text is in Translatewiki. Just search for "view observations of this taxon by"
