### ISSUE TITLE
Prevent iNat from importing taxa with unauthorized ranks from EOL

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1886]
Taxa with unauthorized ranks have no rank_level which creates problems with things like CID

Currently, all taxa with the unauthroized ranks / null rank_level  in iNat come from EOL.
```
bad_ranks = Taxon.where(is_active: true).pluck(:rank).uniq - Taxon::RANKS - ["stateofmatter"]
 => ["varietas", "unrankedclade"]
Taxon.where("is_active = true AND  rank IN (?)",bad_ranks).pluck(:source_id).uniq
 => [127] 
Taxon.where("is_active = true AND rank_level IS NULL AND rank != 'stateofmatter'").pluck(:source_id).uniq
 => [127]
Source.find(127)
 => #<Source id: 127, in_text: "EOL", citation: "Encyclopedia of Life. Available from http://www.eo...", url: "http://www.eol.org", created_at: "2012-08-01 05:00:40", updated_at: "2012-08-01 05:00:40", title: "Encyclopedia of Life", user_id: nil>
```
It would be great to prevent EOL from creating taxa with unauthorized ranks so these don't keep getting introduced

**Comment by kueda** [comment]
This has been released. Please close if you can't replicate these problems anymore.

**Comment by loarie** [comment]
thanks will keep an eye on it and reopen if there's any more weird ranks showing up
