### ISSUE TITLE
Moving descendants should be an opt-in option chosen by the committer 

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1888]
There are currently about 2,500 inactive taxa in the db with active children.
```
Select COUNT(*)
from taxa a
  join taxa b on a.id = any(string_to_array(b.ancestry, '/')::int[])
  WHERE a.is_active = FALSE AND b.is_active = TRUE;
```
These create issues with models that depend on ancestries free of inactive taxa. While they can be fixed, new ones are continually introduced.

We need validations to prevent:
1) an active taxon from being inactivated if it has active children
2) an inactive taxon from being activated if it has inactive parent
3) an active taxon from being created under/moved to an inactive parent

Since the only other pathway that can result in taxon activation inactivation other than taxa/new and taxa/edit are taxon_change#commit
we need to make sure taxon_change#commit checks:
1) that the input taxa (to be inactivated) don't have any active children
2) that the output taxa (to be activated) don't have inactive parents

@kueda are there any other edge cases I didn't think of here?

**Comment by kueda** [comment]
Not sure about edge cases, but is the implication here that if you want to make a taxon change with a taxon, you must first deal with all its descendants? Otherwise you'll be inactivating a taxon with active children. That means we should remove the functionality we have that automatically creates swaps for children when they can be made unambiguously. Not opposed to that, but it will make more work for curators.

**Comment by loarie** [comment]
I think we should either remove the move_input_children_to_output functionality and only allow a swap/merge/split to be committed if the input taxa have no descendants. I agree with will create more work for curators but will avoid three common 'bad' side-effects:

1) gender agreement mess
e.g. Mimulus guttatus  moved to Erythranthe is Erythranthe guttata not Erythranthe guttatus

2) unneccessary swaps
e.g. if a Genus named GenusA is merged into a Genus with the same name, it creates unneccessary swaps 
<img width="381" alt="screen shot 2018-08-24 at 6 38 31 pm" src="https://user-images.githubusercontent.com/598026/44613724-f1ff2f80-a7cc-11e8-8a4b-a85fd3813d29.png">
when instead the children should be moved
<img width="355" alt="screen shot 2018-08-24 at 6 38 35 pm" src="https://user-images.githubusercontent.com/598026/44613726-f297c600-a7cc-11e8-87e6-130b963d9094.png">

Or we should allow move_input_children_to_output functionality as an option which would mean a swap/merge could be committed if the taxa have descendants, but we'd have to improve it as follows:

1) make move_input_children_to_output work on all children regardless of whether the input RANK_LEVEL <= Taxon::GENUS_LEVEL
and figure out whether it should move the children, e.g. 
<img width="313" alt="screen shot 2018-08-24 at 6 38 25 pm" src="https://user-images.githubusercontent.com/598026/44613725-f297c600-a7cc-11e8-9796-3079fd54af74.png">
Or swap descendants who names might be impacted (e.g. species and ssp). And in this case it should act on both species and ssp descendants not just children, e.g.
<img width="370" alt="screen shot 2018-08-24 at 6 38 28 pm" src="https://user-images.githubusercontent.com/598026/44613727-f297c600-a7cc-11e8-8833-8cab012c2e59.png">

Of these two options, I think improving move_input_children_to_output is a better solution to removing it. But requires more work. We need do one or the other though rather than the status quo. Thoughts?

**Comment by loarie** [comment]
do you think you can take a crack at this on @kueda? do you prefer remove or improve?

**Comment by kueda** [comment]
> Make move_input_children_to_output work on all children regardless of whether the input RANK_LEVEL <= Taxon::GENUS_LEVEL

As far as I can tell this is how it works now. See https://github.com/inaturalist/inaturalist/blob/master/spec/models/taxon_swap_spec.rb#L203

> Or swap descendants who names might be impacted (e.g. species and ssp). And in this case it should act on both species and ssp descendants not just children

Again, this is how it works now. The only situation in which names would be impacted is when you swap or merge a genus, and in that situation, `move_input_children_to_output` will get called for the new swaps / merges created. I just added a spec to verify this: 78bc76cb2923a5c4fe799b0893fc98127129ad30

So it sounds like the changes you want is:

- [ ] Moving descendants should be an opt-in option chosen by the committer (or the creator of the change?)

Is that correct?

**Comment by loarie** [comment]
Sorry, I see now that I was testing with locked branches which is why I didn't realize that it was moving descendants. Here's a new failing spec for that locked use case in a new taxon_swap_improvements branch:
https://github.com/inaturalist/inaturalist/blob/taxon_swap_improvements/spec/models/taxon_swap_spec.rb#L213

Also I didn't realize that it autogenerated swaps not just for child sp but also descendant ssp. However, it does look like the existence of subgenera screw this up. Here's a failing spec
https://github.com/inaturalist/inaturalist/blob/taxon_swap_improvements/spec/models/taxon_swap_spec.rb#L633

Would you prefer that we:

1) protect around these edge cases by making it so that you can't commit swaps when the input taxon descends from a locked taxon or the input taxon is a genus and has subgeneric descendants

or

2) make it so that taxon swaps skip locks and properly handle the subgenus edge case?

But yes aside from the above, the only change I want is:

- [ ] Moving descendants should be an opt-in option chosen by the committer (or the creator of the change?)

Thoughts?

**Comment by kueda** [comment]
Whether or not to respect locks is up to you. I can work on making moving descendants opt-in this week.

**Comment by loarie** [comment]
My preference is 'make it so that taxon swaps skip locks and also properly handle the subgenus edge case' if its not too much work. Thanks

**Comment by loarie** [comment]
@kueda - this hypothetical example is a common structure for a taxon merge where Acris (sensu stricto) is on the left and Acris (sensu lato) is on the right:
<img width="1183" alt="screen shot 2018-09-12 at 11 20 48 pm" src="https://user-images.githubusercontent.com/598026/45470452-aa403980-b6e2-11e8-9d34-9520a9798d50.png">
I just realized that 'move children to output' is creating taxon swaps for all the children going from Acris (sensu stricto) to Acris (senus lato):
<img width="789" alt="screen shot 2018-09-12 at 11 21 10 pm" src="https://user-images.githubusercontent.com/598026/45470450-a90f0c80-b6e2-11e8-8e20-08d77c843db7.png">
which seems unnecessarily disruptive compared to just moving them (e.g. moving Acris blanchardii from Acris (sensu stricto) to Acris (sensu lato) when lots of IDs are involved.

Would it be hard to change this so that if the names for the input and the output are the same, it moves rather than swaps even if the inputs are species?

**Comment by kueda** [comment]
Check out https://github.com/inaturalist/inaturalist/compare/1888-opt-in-to-move-input-children-to-output and see what you think.
