### ISSUE TITLE
Avoid taxa with rank_level >= parent | <= children

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1889]
There are currently about 738 active taxa in the db with rank levels equal to or greater than their ancestors
```
Select COUNT(*)
from taxa a
  join taxa b on a.id = any(string_to_array(b.ancestry, '/')::int[])
  WHERE a.rank_level <= b.rank_level AND b.is_active = TRUE;
```
These create issues with models that require taxa with coarsening ancestries. While they can be fixed, new ones are continually introduced.

We need validations to prevent a taxon being saved if:
1) the rank is greater than or equal to its parent
2) the rank is less than or equal to any children

@kueda are there any other edge cases I didn't think of here?

**Comment by kueda** [comment]
Can't think of other edge cases. Do you want to work on this or should I?

**Comment by loarie** [comment]
I'll take a crack at this one
