### ISSUE TITLE
Why is there no Dutch available in the locale settings?

### ISSUE THREAD

**Issue by andrawaag** [inaturalist/inaturalist#1890]
I am trying to switch to Dutch as the main language on iNaturalist.com. However, there is no Dutch locale. 
![image](https://user-images.githubusercontent.com/770306/44629128-f3eefd00-a94a-11e8-96be-629bb635890e.png)

**Comment by cmcheatle** [comment]
@andrawaag - because the site / app has not yet been translated into Dutch.

If you wish to see Dutch common names, you can go to your Account Settings and set the "Prioritize common names used in this place" to the Netherlands.

**Comment by kueda** [comment]
FWIW, Dutch seems to be 38% translated on the website according to https://translatewiki.net/w/i.php?title=Special:MessageGroupStats&language=nl&group=out-inaturalist&showMessage. I can't remember what TW's threshold is before they start sending us the file, but I suspect it's something like 80%. If you want to see Dutch as a language option on iNat, you can help by adding translations on translatewiki.

**Comment by ptalvistu** [comment]
I think the percentage is way lower. Estonian was usable on the site already with under 50 percent translated (or maybe 50).
