### ISSUE TITLE
Taxon snippet when wiki article missing not properly internationalized

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#1894]
e.g. https://www.naturalista.mx/search?q=Mestra
<img width="587" alt="screen shot 2018-08-28 at 5 49 56 pm" src="https://user-images.githubusercontent.com/598026/44758707-ca6cd780-aaea-11e8-820e-4392beb2e160.png">
"Mestra amymone is a especies of insects with 1119 observations"
should be 
"Mestra amymone es una especie de insectos con 1119 observaciones"

**Comment by carrieseltzer** [comment]
This string looks ok in other languages (e.g. French, Italian, Russian), so I think this may just be an issue with it not being properly translated in Spanish (all 3 versions of Spanish). I'll point Carlos to [these threads](https://translatewiki.net/w/i.php?title=Special%3ASearchTranslations&query=is+a+species+of+with++observations) on translatewiki. If there are others, please let me know.

**Comment by kueda** [comment]
We discussed this in Slack yesterday, and Carrie's right, these are just strings that need *both* pluralizations to be translated on translatewiki.
