### ISSUE TITLE
Missing umlauts again

### ISSUE THREAD

**Issue by ptalvistu** [inaturalist/inaturalist#1895]
![umlauts](https://user-images.githubusercontent.com/38881755/44815406-194c6700-abe8-11e8-9ddf-ca3861e759b6.jpg)
Once again omlauts have gonne missing. Filtreeri Koha Jargi should have ä in Järgi and Vaata Koiki should be Vaata Kõiki.

**Comment by kueda** [comment]
This is basically something that will be handled by #1844.
