### ISSUE TITLE
Don't allow entering a common name without a language

### ISSUE THREAD

**Issue by ptalvistu** [inaturalist/inaturalist#1896]
Currently it is possible to enter a common name without specifying a language. Since a name string shouldn't be without an associated language/system, this sort of entry should be forbidden.

**Comment by kueda** [comment]
Is this actually causing a technical problem of some kind?

**Comment by ptalvistu** [comment]
I don't believe it actually creates any technical troubles. But I always try to flag the taxon for moderation when I see one such common name. However, I don't think that a name could or should be without a language/type since every name or identification has to be in some language. Why should anybody want to add a name to a taxon when they don't what language that name comes from? How trustworthy could that information be? How can it be verified if we don't know what we are verifying?

**Comment by kueda** [comment]
It is no more or less "trustworthy" or "verifiable" than a name with a language specified. Since there's is no real technical problem or impact on the user of the site, I'm going to close. If you can describe such a problem that this would solve, please re-open.
