### ISSUE TITLE
Improve Observation Requirements description text for Collection Projects

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1899]
A common mistake users make when creating a Collection project is feeling the need to enter info in fields for Taxa, Places, Users, and Quality Grade, believing they can't be left blank. Not sure how much it'll help, but adding something like

"Please specify the requirements for the observations to be added to this project. You can specify multiple species, places, and users, or quality grades to be automatically included, or leave a field blank if you have no specific requirement for it."

**Comment by pleary** [comment]
all set
