### ISSUE TITLE
Functionality changes to announcements page & announcements

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1903]
Depends on #1897 

Changes to the /announcements page:
- [x] When logged in as a Site Admin, /announcements should only show announcements that apply *uniquely to their site*.  
- [x] Site Admins should see the option to edit all announcements that they can see, i.e. all announcements applied uniquely to their site.
- [x] Add ability to search the body of announcements

Changes to creating/editing announcements:
- [x] The default Placement selection for all new announcements should be users/dashboard#sidebar
- [ ] Add ability to select “default” as a locale
- [x] Staff should be able to select multiple sites (rather than either all or a single site)
- [x] Site Admins should only be able to select their site when creating or editing announcements
- [x] Site Admins should be able to edit all announcements applied uniquely to their site

Changes to display prioritization (visibility of announcements for all users):
- [x] Site-specific announcements should take priority over “all site” announcements
- [x] Locale-specific announcements should take priority over “all locale” announcements

**Comment by kueda** [comment]
> Add ability to select “default” as a locale

What's the intent here? If you don't want to target a locale, you just don't choose a locale. Locale just *restricts* the audience of the announcement, so a "default" wouldn't do anything.

**Comment by carrieseltzer** [comment]
It appears to me that users can set their locale to "default", so this piece of the issue is intended to be able to reach those users. 

Yes, Tony and I have discussed targeting multiple sites but not all of them for announcements. This would allow us for example to put the blog post announcements on all sites that are predominantly English while not interfering with those that are predominantly non-English.

**Comment by kueda** [comment]
> It appears to me that users can set their locale to "default", so this piece of the issue is intended to be able to reach those users.

If a user chooses the "default" locale, a locale will still be set, they are just not explicitly choosing it. So if I choose "default" but I use Naturalista, my locale will be es-MX, and I will see both announcements with no locale and announcements with locale set to es-MX. If you use iNaturalist.org, we'll try to infer your locale from information your browser sends us, but if we can't we'll default to English. An announcement targeting *just* people who did not explicitly choose a locale would, in fact, reach no one, so I don't think adding that as an option will help anyone.

**Comment by carrieseltzer** [comment]
Thanks for explaining how the "default" account setting works. I understand now that it is not needed as a locale option for announcements. 

Yes, locale is probably better to use than site for my previous example. The most recent use case of wanting to select multiple sites but not all sites was to prevent bumping Canada's announcement about giant lacewings, but under the new site-specific override rule, Tony could make dashboard sidebar announcements for all sites without worrying about overriding a local announcement.

**Comment by kueda** [comment]
I think everything here is done and deployed. Can you close this if everything looks ok Carrie?

**Comment by carrieseltzer** [comment]
Looks good. The only thing that isn't working as expected as far as I can tell is that that site-specific announcements aren't overriding all-site announcements (two announcements are showing instead).

**Comment by kueda** [comment]
That was intentional. Presumably if we on staff want to speak to all users we should be able to do so regardless of what the network partners want, right? Announcements by site admins will still show, but ours will do.

**Comment by carrieseltzer** [comment]
To use downtime as probably the most important example, the thinking was that it would make sense for them to be able to override a global downtime announcement with a localized (language & time) downtime announcement. As it is now, they'd then see two announcements, which might look strange.

**Comment by kueda** [comment]
Ok, so when you used the word "priority" in the description above, you meant

- [ ] “all site” announcements should not display if there are site-specific announcements
- [ ] “all locale” announcements should not display if there are locale-specific announcements

Is that correct?

**Comment by carrieseltzer** [comment]
Yes, that's correct. I see now that "priority" was unclear.
