### ISSUE TITLE
Display more information about geoprivacy origin in Observation detail 

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#1905]
Currently, observations that are obscured by users' geoprivacy selections and observations obscured automatically from conservation statuses display the same information on observation detail pages. This seeks to distinguish them. 

On observation detail pages, "Details" below the map should reveal one of three details following Geoprivacy:

1. Geoprivacy: Obscured by user (e.g. https://www.inaturalist.org/observations/15469775)
2. Geoprivacy: Obscured automatically by conservation status (e.g. https://www.inaturalist.org/observations/5431408)
3. Geoprivacy: Obscured by user & Obscured automatically by conservation status
(e.g. observation with *both* types of obscuration: https://www.inaturalist.org/observations/15463221)

**Comment by kueda** [comment]
This depends on #1907

**Comment by kueda** [comment]
I've been working on this as a part of #2050 and it's currently looking something like this:

<img width="538" alt="screen shot 2019-01-17 at 12 55 16 pm" src="https://user-images.githubusercontent.com/22691/51348398-78a3fa00-1a57-11e9-93e8-cbdb25b3cd0e.png">

That would be in the map details popover when you click "Details" under the map on the obs details page. I can rework the text a bit, but @abhasinat, does this give you hives, and if so, do you want to think about how and/or where we could convey this information more concisely? This screen shot shows most of the possible information one could see. "Why the Coordinates Are Obscured" and "Who Can See the Coordinates" will always be visible to everyone. "Why You Can See the Coordinates" is only visible to people who can
