### ISSUE TITLE
Sorting by observed on date in list view of Collection projects results in blank page

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1906]
In the Observations tab of a Collection project, click on List view then sort by Observed on - a blank screen will result. Here is what the console displays:

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/15896181/45043569-5cf90380-b022-11e8-8817-2158abe89df3.png">

**Comment by pleary** [comment]
This fix has been deployed and seems like collection project list sort works OK now
