### ISSUE TITLE
Clicking on "Reviewed" box in Identify modal marks all other obs on that page as Reviewed

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1918]
Pretty much what the title says. I also can't use the right and left arrows once I've clicked on Reviewed, at least in Chrome. Nothing showed up in the console.

**Comment by kueda** [comment]
Can't replicate. Can you confirm that you're *clicking* reviewed and not using the `r` key, and can you explain how you know all the other obs are reviewed?

**Comment by marschind** [comment]
I am seeing the same behavior today with the Captive/Cultivated
      checkbox as well while using FireFox.
    
        -Mark
    
    
    On 9/10/18 7:22 PM, tiwane wrote:
    
    
      
      Looks like they're not being "recorded" as reviewed, but the
        "Reviewed" box is checked.
      
        Go to Identify.
        Click on the first observation and bring up the modal.
        Click on "Reviewed" to mark as reviewed.
        Go to the next observation. the "Reviewed" box is already
          marked.
        However, if you get out of the modal, you'll see that the
          second observation has not been marked as reviewed.
      
      Was able to replicate in both Safari and Chrome. Haven't tried
        FF.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/inaturalist/inaturalist","title":"inaturalist/inaturalist","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/inaturalist/inaturalist"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tiwane in #1918: Looks like they're not being \"recorded\" as reviewed, but the \"Reviewed\" box is checked.\r\n\r\n1. Go to Identify.\r\n2. Click on the first observation and bring up the modal.\r\n3. Click on \"Reviewed\" to mark as reviewed. \r\n4. Go to the next observation. the \"Reviewed\" box is already marked.\r\n5. However, if you get out of the modal, you'll see that the second observation has not been marked as reviewed.\r\n\r\nWas able to replicate in both Safari and Chrome. Haven't tried FF."}],"action":{"name":"View Issue","url":"https://github.com/inaturalist/inaturalist/issues/1918#issuecomment-420093251"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/inaturalist/inaturalist/issues/1918#issuecomment-420093251",
"url": "https://github.com/inaturalist/inaturalist/issues/1918#issuecomment-420093251",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [inaturalist/inaturalist] Clicking on \"Reviewed\" box in Identify modal marks all other obs on that page as Reviewed (#1918)",
"sections": [
{
"text": "",
"activityTitle": "**tiwane**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@tiwane",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"inaturalist/inaturalist\",\n\"issueId\": 1918,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"inaturalist/inaturalist\",\n\"issueId\": 1918\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/inaturalist/inaturalist/issues/1918#issuecomment-420093251"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 378023569\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by tiwane** [comment]
@marschind is this only when you are clicking on it, not pressing X?
