### ISSUE TITLE
Explain effect of choosing between CC licenses

### ISSUE THREAD

**Issue by MattBlissett** [inaturalist/inaturalist#1938]
![inat-license](https://user-images.githubusercontent.com/583320/46341809-7e590980-c639-11e8-98b9-b95d7c0e4550.png)

The user settings says "iNat uses your Creative Commons-licensed content to share with data partners like the Global Biodiversity Information Facility (GBIF)", but it isn't clear that only by choosing one of the first three (CC0, CC-BY, CC-BY-NC) will data be shared with GBIF.

Could you add some explanation? Maybe even a smily face when the sharing-friendly ones are chosen :-)

**Comment by kueda** [comment]
We have a number of different data partners and they have different sets of licensing preferences. While I agree we could do more to indicate which license choices have consequences for particularly prominent partners like GBIF, just leaving the default settings will achieve that. I also think this is just one of many problems with the settings page that should be addressed in a more comprehensive redesign.

**Comment by timrobertson100** [comment]
Hi folks

This continues to raise questions from iNaturalist users. I understand tracking the various licenses data partners use is a nuisance but given that you do explicitly name GBIF already, could I please ask you make a simple edit to the text? Perhaps to:

> Licensing your content gives other people the legal right to use it without asking your permission if they stick to the terms of the license. iNat uses your Creative Commons-licensed content to share with data partners. For example _No Copyright (CC0)_, _Attribution_ and _Attribution-NonCommercial_ licensed data will be shared with the [Global Biodiversity Information Facility](https://www.gbif.org) (GBIF), an international, inter-governmental organization that compiles and distributes biodiversity information from around the world. [Learn what these licenses mean](https://www.inaturalist.org)

**Comment by timrobertson100** [comment]
Thank you @kueda
