### ISSUE TITLE
Suggestion / request: use Dependabot to keep dependencies up-to-date

### ISSUE THREAD

**Issue by greysteil** [inaturalist/inaturalist#1939]
First of all, thanks for iNaturalist! Seriously cool project, and amazing to have it open source.

I've got a suggestion / request: would you be up for using [Dependabot](https://dependabot.com) to automatically create dependency update PRs for this repo? I ran it against my fork and it generated [these PRs](https://github.com/greysteil/inaturalist/pulls). I'll port the `devise` one across to this repo now because it's security related. I *think* it should be fine to merge, despite the major version bump (which was just to drop support for Ruby 2.0 and Rails 4.0).

I built Dependabot, but I'm honestly only suggesting it because I hope it can save you some time. I'd love any feedback, and obviously having open source repos using Dependabot helps boost its profile, but if it's not helpful to you then it's not really worth anything.

You can install it from [here](https://github.com/apps/dependabot) or [here](https://github.com/marketplace/dependabot) if you decide to give it a try. It's been through GitHub's security testing (to be allowed in the GitHub Marketplace) and is used by a few thousand organisations, and the source code is [here](https://github.com/dependabot/dependabot-core).

:octocat:

**Comment by kueda** [comment]
Thanks for the PR, and the suggestion. We're going to give Dependabot a try. If you're using iNaturalist, I hope you're enjoying it!

**Comment by greysteil** [comment]
Awesome! I’ll take a look through all the initial PRs and make sure everything goes smoothly from my side, too 🙂

**Comment by greysteil** [comment]
Closing since you're giving Dependabot a try - thanks! 🎉
