### ISSUE TITLE
Make content displayed on  /taxa/ configurable based on a place

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#195]
on /taxa/, NatureWatchNZ would like to continue showing New Zealand taxa only on the banner at the top, in the thumbnails making up the iconic_taxon mosaics, and in the iconic taxon icons (??). This would require making the contents of this page configurable
![screen shot 2013-12-11 at 11 52 15 am](https://f.cloud.github.com/assets/598026/1727868/e881b2e6-62a5-11e3-91ea-4de6bef8ca28.png)

This is part of the NatureWatchNZ wishlist

**Comment by loarie** [comment]
on http://www.inaturalist.org/taxa the default taxon thumbnails below each iconic taxon are just showing NZ species across all sites, it should be site (country) specific

**Comment by kueda** [comment]
The scope of this was just to filter the featured taxa. The problem here is that it's not showing images for the iconic taxa that predated the NatureWatch merger, so it's more a sorting thing. I'll fix that, but I won't make the iconic images site-specific.
