### ISSUE TITLE
Allow owner of collection project to transfer ownership to a project admin

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#1968]
We've had a few requests for this. Obviously one can just make a new project, but if this is possible, it would be nice to allow transfer of ownership.

**Comment by kueda** [comment]
What's the use case here? Project admins can do everything the "owner" can.

**Comment by tiwane** [comment]
This was a while ago, but it would be for situations like nature parks where one person created a project but wants to transfer ownership to an organizational account (if they're leaving the org).

**Comment by carrieseltzer** [comment]
Sometimes I help people set up projects and then I want to remove myself as admin of them, but I can't because I'm the project owner, e.g. https://www.inaturalist.org/projects/prince-william-wild-things

I'd love to be able to transfer ownership to the other admin, and then remove myself as admin.

**Comment by kueda** [comment]
Some further questions:

1. Should the admin be allowed to transfer ownership to a user without the `ORGANIZER` privilege? This would maintain our current limit on project creation, but it would create a kind of backdoor to project ownership by users who have not earned that privilege.
1. Should the admin be allowed to transfer ownership to a user who has not joined the project? This might enable some bad behavior.

**Comment by tiwane** [comment]
Yeah, we need to simplify those member type terms. 

No one needs to have the `ORGANIZER` privilege to create/admin a collection project, correct? (even though I wish it were so) So that wouldn't be a backdoor in this case.

**Comment by kueda** [comment]
Ah, forgot about that. I'll remove that restriction then.
