### ISSUE TITLE
Fixed size input boxes vs. tips inside them: let users see what the full text is

### ISSUE THREAD

**Issue by jidanni** [inaturalist/inaturalist#1996]
No matter on the signup page, or in the search boxes, please
don't chop your own text tip!
https://bugs.chromium.org/p/chromium/issues/detail?id=895049

**Comment by kueda** [comment]
Definitely not a good practice, though in this specific case I think it would be better if we addressed this in a redesign of the sign up and log in pages. I'll leave this open until we have a more structured proposal for that work.

**Comment by kueda** [comment]
Redesign complete!
