### ISSUE TITLE
Account setting place search should use larger database like observations place search

### ISSUE THREAD

**Issue by jidanni** [inaturalist/inaturalist#1999]
On [the observations page](https://www.inaturalist.org/observations) I could type in my full location
```
Dongshi District, Taichung City, Taiwan
```
Alas on ```Edit Your Account & Profile```'s similar box
```
Search place
Default place for observation searches.
```

A much simpler database is used which won't let one get that close.

**Comment by kueda** [comment]
Settings on your account must be tied to places iNat knows about. We can't do things like customize names you want based on stuff from the Google API. Just too many API requests.

**Comment by jidanni** [comment]
You know about the same place on one page, but not the other.

**Comment by kueda** [comment]
Perhaps I wasn't clear enough. On https://www.inaturalist.org/observations, we will take the user's search text and pass it along to Google to get a name and a bounding box back that we can use in observation searches. For options like your names place, we *could* allow you to search Google, but what would we do with that bounding box? Names on iNat are tied to iNaturalist places, not Google combinations of place names and bounding boxes, so when trying to use your place preference to customize names, we couldn't really do it without knowing *every* place that Google knows about a priori, which is not something we can do. We could store a bounding box as a default search on https://www.inaturalist.org/observations, but vanishingly few people like that feature, so I don't think we're going to develop it any further.

**Comment by jidanni** [comment]
All I know is on '''Edit Your Account & Profile''' I want a way to register where I live.
Simple '''Lat:____ Lon:____''' input fields would be fine and wouldn't cause you to pay more money to Google.
And/or "Chose where you live on this OpenStreetMap:".

And then you could use my location to help me find other naturalists nearby etc. other future uses.
