### ISSUE TITLE
Creative Commons license not correctly marked in HTML

### ISSUE THREAD

**Issue by nemobis** [inaturalist/inaturalist#2006]
https://www.inaturalist.org/photos/26387837 displays a link to CC-BY without a rel="license", so crawlers cannot index the image as being freely licensed.

https://wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license

Cc @dartar

**Comment by dartar** [comment]
Neat, @nemobis do you want to write up a summary at https://www.wikidata.org/wiki/Wikidata:WikiProject_iNaturalist so others are aware this has been fixed?

**Comment by pleary** [comment]
FYI this is fixed in the code, but not yet deployed. It should be live on the website in a few hours
