### ISSUE TITLE
Allow voting out of needs ID when observer opts out of CID

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2011]
https://www.inaturalist.org/observations/5657939 is a weird case where the owner has opted out of the CID and has a species-level ID, while numerous other identifiers have added coarse disagreements, but since those disagreement taxa are ancestors of observer's species, the observer's ID never becomes maverick and the obs gets stuck in Needs ID. I propose we make obs casual when the owner has opted out of the CID and the community votes the obs doesn't need more IDs.

**Comment by lincolndurey** [comment]
available for testing:
https://www.inaturalist.org/observations/5657939  Trombidium holosericeum
https://www.inaturalist.org/observations/6116902  Aedes notoscriptus
https://www.inaturalist.org/observations/1628750  Ipomoea lacunosa
https://www.inaturalist.org/observations/8759965  Urbanus
https://www.inaturalist.org/observations/7768650  Quercus laurifolia
https://www.inaturalist.org/observations/3423851  Euphorbia esula
https://www.inaturalist.org/observations/6305774   Euphorbia esula 4:2 still needsID
I have had good results when I can provide an out-of-branch taxon, like another species in that genus, and get the 3 votes.
