### ISSUE TITLE
Staff cannot delete user content

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2033]
I'm no longer able to delete offensive content posted by other users via users/curation. If I try to delete, say, an observation, I will be taken to the observation and see this banner:

![image](https://user-images.githubusercontent.com/15896181/48507887-feaa8700-e801-11e8-942a-4bce22624ed9.png)

**Comment by kueda** [comment]
Fixed in abf670939b986270dd119e5974c285d90ad10a9a
