### ISSUE TITLE
spam filter being triggered on account update?

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/inaturalist#2046]
I'm still seeing a lot of accounts with spam descriptions, and all of them are updated an hour or a day or a week after they were created:

- https://www.inaturalist.org/people/1344782.json updated a week after creation.
- https://www.inaturalist.org/people/1309027.json updated an hour after creation.
- https://www.inaturalist.org/people/1357528.json updated a day after creation.

My working theory is that updating a spam account requires a fair amount of extra work: holding onto account credentials, remembering the site, etc. There must be a good reason for a spambot to coming back to iNat a day later and making an update. Is Akismet being triggered to re-evaluate the account description when an account is updated?

**Comment by alexshepard** [comment]
Or is it possible that some API endpoints don't trigger Akismet spam evaluation?

**Comment by kueda** [comment]
As far as I've been able to tell the check is happening on update, which is not to say we don't still have a serious spam problem, but I don't think this is the culprit.
