### ISSUE TITLE
Taxon photo browser: header does not display localized common name

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2059]
Eg: https://www.inaturalist.org/taxa/144849-Cyanistes-caeruleus/browse_photos

<img width="1032" alt="screen shot 2018-11-27 at 11 35 48 am" src="https://user-images.githubusercontent.com/15896181/49107287-25bd7b80-f23a-11e8-8b6e-fdb77875704c.png">

**Comment by kueda** [comment]
Closed in 4936f84a
