### ISSUE TITLE
Add help options to "More" header menu

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2070]
I think a lot of people don't see our help pages on the left-hand side of the main Help/FAQ page. Rather than the the lone "Help" option in the More menu, can that section instead have:

FAQ
Video Tutorials
Managing Projects
Teacher's Guide

I feel like that would surface these a bit more.

**Comment by kueda** [comment]
I can almost guarantee this will bring complaints from non-English-speaking network partners. Do you want to just add these and see what happens, or only show them on iNaturalist.org, or only show them to English speakers, or make all of these configurable per-site?

**Comment by tiwane** [comment]
Sorry for the delay. Let's try inaturalist.org for the moment.
