### ISSUE TITLE
OLYMPUS DIGITAL CAMERA exif data slipping through the cracks

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2086]
We have been removing Olympus's "OLYMPUS DIGITAL CAMERA" caption text from photos for a while now, but some seem to be making it through recently.

Example:
https://www.inaturalist.org/observations/19005357

**Comment by kueda** [comment]
@tiwane do you have an example of an original photo file that causes this? I've tried replicating with files from my own Olympus camera and that text gets filtered out just fine.

**Comment by tiwane** [comment]
Yeah, here you go: https://www.dropbox.com/s/1cauhciftx89w4f/PB297216.JPG?dl=0
