### ISSUE TITLE
Description field cursor for uploader starts in a weird place

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2088]
1. Upload a geotagged photo at https://www.inaturalist.org/observations/upload
2. Wait for the "Loading metadata" to disappear
3. The gray "Description" text in the description field disappears and if you click in the description field, the cursor starts far to the right.

<img width="250" alt="image" src="https://user-images.githubusercontent.com/15896181/50358025-cd159180-050c-11e9-985c-eb6d627c778e.png">

**Comment by kueda** [comment]
Can't replicate in Chrome, Safari, Firefox, or Brave. Can you provide some more context, and/or the photo you're uploading?

**Comment by tiwane** [comment]
This hasn't happened to me for a while so I'm closing.
