### ISSUE TITLE
The page is shown in English even if the language of the site is Finnish or other

### ISSUE THREAD

**Issue by Pyscowicz** [inaturalist/inaturalist#2089]
Hey.

I found out that [Search for users](https://www.inaturalist.org/people/search) page is shown in English but the language I use on the site is Finnish.

Screenshot is from finnish version of the site.

![inaturalist](https://user-images.githubusercontent.com/35464425/50382447-edc61e80-06a7-11e9-9020-106030a3484e.PNG)

**Comment by kueda** [comment]
IMO, we should remove that page and redirect all requests to https://www.inaturalist.org/people/search to https://www.inaturalist.org/search?source%5B%5D=users

**Comment by Pyscowicz** [comment]
Sounds good, you know it better than me. I also found out that [here](https://www.inaturalist.org/search?source%5B%5D=users) text 'No Results' is missing from translations.

**Comment by tiwane** [comment]
I'd second that @kueda.

**Comment by cmcheatle** [comment]
One comment I would make regarding the proposed change is that the results of the same search string are not the same between the 2 pages. Compare:

https://www.inaturalist.org/search?utf8=%E2%9C%93&q=gaard&commit=Go&source%5B%5D=users

to 

https://www.inaturalist.org/people/search?utf8=%E2%9C%93&q=gaard&commit=Search

Searching for the same string on the first returns 2 items, the 2nd page returns 14 pages of results, including a lot of clearly valid users not found in the first search.

The 2nd page is used by the curators who try to get the spam accounts off the page, and right now the 1st one does not seem to replicate the functionality needed to do that.

**Comment by Pyscowicz** [comment]
This is off-topic and is not related to this thread but I have noticed that some things on the site looks outdated. Site looks great but contains stuff that doesn't fit in a new modern style.

Example this toolbar

![old toolbar](https://user-images.githubusercontent.com/35464425/50489345-d2dd0c80-0a0f-11e9-97d1-e878cf612a43.PNG)

Some pages use that toolbar and some pages use this new toolbar below, new toolbar looks much better, interesting why it's not used on every page that contain this toolbar, the order of the buttons on the toolbar are even different in these two toolbars.

![new toolbar](https://user-images.githubusercontent.com/35464425/50489354-e0929200-0a0f-11e9-9d0e-acaf9c1b0dd7.PNG)

Maybe these buttons should be green instead of blue, refers to the style of the site better.

Also the search bar seems to be different in different pages

![old search](https://user-images.githubusercontent.com/35464425/50489483-8c3be200-0a10-11e9-88e2-5c3a41d78775.PNG)
Some pages use this old search bar

![other old search](https://user-images.githubusercontent.com/35464425/50489494-99f16780-0a10-11e9-9356-076be4d515cd.PNG)
And others use this newer search bar with blue button

![new search](https://user-images.githubusercontent.com/35464425/50489501-a4136600-0a10-11e9-8d1b-1c64ee5b781f.PNG)

And some pages use this other search bar with green button, looks better than those two because the button is attached to the side of the bar and button is green when the other two are blue.

Thank you and apologize for reporting a development idea in the wrong place :)

**Comment by kueda** [comment]
@cmcheatle, user search was never intended for spam filtration specifically or for curatorial purposes generally. I've been experimenting with https://www.inaturalist.org/users/recent for this purpose if you want to try that out (should be visible to curators).

@Pyscowicz design consistency is an ongoing goal that we may never meet. We have one full time visual designer and two engineers who work on the website (which probably amounts to more like one full time equivalent for web front end, since we all do multiple things). Lack of consistency is annoying, but making new things and fixing broken things is usually takes higher priority.

**Comment by cmcheatle** [comment]
Hi Ken-ichi,

Yes curators do have access to users/recent.

It does not address though why the proposed page to switch to seems to miss so many valid users.

One benefit of that other page is it is the easiest / only effective way to find older spam accounts that slipped though, of which there are still many.
