### ISSUE TITLE
Make specific error message on uploader page when observation has more than 750 characters in its tags

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2098]
Right now if a user is on the [upload page](https://www.inaturalist.org/observations/upload) and tries to submit an observation that has more than 750 characters (cumulative) in its tags, they receive this error message:

![image](https://user-images.githubusercontent.com/15896181/50567169-956dcd00-0cf6-11e9-9af0-c6d986f013df.png)

Can we replace "unknown error" with something like "Observation has more than 750 characters in its tags."?

**Comment by kueda** [comment]
Should have been fixed in d5cdf8f690d65282cfdd5bed1b0f4f0a6df8b830
