### ISSUE TITLE
Flag detail page: "Back to flags" link sometimes leads to object or other page rather than /flags

### ISSUE THREAD

**Issue by boucur** [inaturalist/inaturalist#2108]
Some unexpected behavior in the "Back to flags" link on the flag detail page. It appears to link to the previous page from which you navigated to the flag. 

- If I copy the URL and open https://www.inaturalist.org/flags/320615 in a new tab, the "back to flags" link brings me to the object being flagged (in this case, the [observation](https://www.inaturalist.org/observations/19568731)) rather than https://www.inaturalist.org/flags/.

- If I navigate to that flag from a [filtered flag search](https://www.inaturalist.org/flags?utf8=%E2%9C%93&flagger_type=any&flagger_name=&flagger_user_id=&user_name=&user_id=&flaggable_type=all&flags%5B%5D=inappropriate&flags%5B%5D=other&reason_query=&resolved=yes&resolver_name=bouteloua&resolver_user_id=bouteloua&commit=Filter), the link now brings me back to that filtered search.

- If I click the link to that flag from this git issue; the back to flags link brings me to https://github.com/inaturalist/inaturalist/issues/new

**Expected behavior:** "Back to flags" is hard coded to bring me to https://www.inaturalist.org/flags/. 
_(It's kind of nice that it "remembers" the filtered flag search, but I already expect to use my back button rather than presuming that kind of nav link would remember the filters.)_

_If_ there is more than one flag on an object, a _secondary_ link could be added to the navigation, or elsewhere on that flag detail page, "Other flags on this object".

**Comment by kueda** [comment]
You can get to https://www.inaturalist.org/flags/320173 from https://www.inaturalist.org/taxa/78990/flags or from https://www.inaturalist.org/flags?flaggable_type=Taxon&taxon_id=55329. Since you can navigate to that page from multiple places, the meaning of back is ambiguous, so if "back" is hardcoded, it will only make sense in some contexts, not others. In your proposal, the only problem is when you navigate directly to the flag detail page from outside the site, which seems like a pretty rare case.

However, it sounds like your real problem is that you always want a way to get to https://www.inaturalist.org/flags from the flag detail page regardless of how you got there, right? How about just a link to "View all flags" on that page?

**Comment by boucur** [comment]
Some other in-site cases:

- Receive flag notification on dashboard; click "view flag" to go to flag detail page. Now "Back to flags" brings me to my dashboard
- Navigate to /observations (Explore page). Get a notification about a flag. Click flag notification. Now "Back to flags" brings me to /observations
- Flag linked in a comment; click link. Now "Back to flags" brings me to that comment
- Flag linked in a message; click link. Now "Back to flags" brings me to that message

Yeah, I think a "View all flags" nav link that always goes to /flags is sufficient. The current back button is duplicative to my browser back button.

(I would only care about going back to or ever seeing https://www.inaturalist.org/OBJECT/####/flags if there is more than one flag. In most cases there's just one flag.)

**Comment by boucur** [comment]
Maybe I'm just dumb, but I click this dang "back to flags" link multiple times a day on accident and it almost never brings me to a flags page. I still feel that a button in the top left corner should link to all flags, or there should be no link at all.

**Comment by tiwane** [comment]
I'd vote for removing it.

**Comment by boucur** [comment]
Brought up as well by Reuven: https://forum.inaturalist.org/t/back-to-flags-link-doesnt-always-lead-back-to-flags/8750
And Thomas: https://forum.inaturalist.org/t/back-to-flags-hyperlink-behaves-inconsistently/14800
