### ISSUE TITLE
Small TranslateWiki issue

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2109]
From Marcel Hospers: 

The sentence ''You have opted out of community identifications''
occurs twice in the translation tool:

https://translatewiki.net/w/i.php?title=Special:Translate&group=out-inaturalist&language=nl&filter=&action=translate

**Comment by kueda** [comment]
I only see it it once, and it certainly only appears once in https://github.com/inaturalist/inaturalist/blob/master/config/locales/en.yml, which is the only control we have over what strings are available for translation in translatewiki.

**Comment by tiwane** [comment]
OK, I'll let him know.

**Comment by tiwane** [comment]
For posterity, he says this is what he's seeing:

![image](https://user-images.githubusercontent.com/15896181/51067103-c803a980-15c3-11e9-89a2-0fbfc020ca11.png)

**Comment by Optilete** [comment]
and when I make an export I see two different keys, if you need unique keys so need two lines in Translatewiki:

The technical field tag is different. I made them bold:
#
**msgctxt "youve_opted_out_of_community_ids"**
msgid "You've opted out of community identifications"
msgstr "Je hebt je afgemeld voor community-determinaties"
and
#
**msgctxt "views.observations.community_id.you_have_opted_out"**
msgid "You have opted out of community identifications"
msgstr "Je hebt je afgemeld voor community-determinaties"
