### ISSUE TITLE
Uploading several large images gives 413 error

### ISSUE THREAD

**Issue by tigerhawkvok** [inaturalist/inaturalist#211]
When uploading several large images simultaneously via "edit", a 413 error ("Request too large") is spawned.

As a sample, the two images in http://www.inaturalist.org/observations/491400 worked fine individually but spawned an error uploading both simultaneously.

**Comment by kueda** [comment]
While this isn't exactly solved, the new uploader makes the whole image upload process a lot better and more parallel. You should be able to throw a lot of large images at it.

**Comment by kueda** [comment]
@LucaProvencal I don't work at iNat anymore, so that's a question for @pleary and @danrademacher.
