### ISSUE TITLE
Can't load images from Google Photos

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2122]
Go to https://www.inaturalist.org/observations/import#photo_import and select Google Photos. You get an endless spinner and nothing loads. Here's a console screenshot from Chrome. 

<img width="549" alt="image" src="https://user-images.githubusercontent.com/15896181/51777615-acfc6380-20b2-11e9-909b-7f791fd313bb.png">

**Comment by kueda** [comment]
Looked into this a bit and the API we've been using is, in fact, [dead](https://developers.google.com/picasa-web/docs/3.0/deprecation), so it's time to migrate to the new(er) [Google Photos API](https://developers.google.com/photos/). I'll look into whether we can continue to use the existing Google oauth tokens we have, but it does look like there are some critical differences, including the fact that the Google Photos API [does *not* include location data](https://developers.google.com/picasa-web/docs/3.0/developers_guide_migration).

**Comment by benj-d** [comment]
A quick look shows a brief explanation here: https://stackoverflow.com/questions/51336701/location-data-google-photos-api
and a Google Photos API ticket here: https://issuetracker.google.com/issues/80379228 
Though nothing seems to have come of it...

**Comment by benj-d** [comment]
Would accessing images using the Drive API be a suitable alternative? https://ctrlq.org/code/20059-image-exif-and-location

**Comment by tiwane** [comment]
Yeah, I'm leaning toward the latter suggestion as the best solution. Adding locations to the imported photos on iNat will be much more work than the download-upload workflow, and possibly be less accurate.

**Comment by kueda** [comment]
The saga continues: we can't use Google OAuth with the additional scope we need to access the Google Photos API without going through the verification process with Google. Not sure how we aren't verified as we've been collaborating with various teams at Google for years, but whatever. Rolled back the scope request and started the verification process.

**Comment by tiwane** [comment]
Still getting the spinner. Not sure console shows anything useful, but here it is. 

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/15896181/83317560-81c3e000-a1e2-11ea-8595-9ecb94754737.png">

**Comment by kueda** [comment]
We're verified, and I can import photos from Google, just can't get locations, which I think is permanent, so I'm closing again.
