### ISSUE TITLE
Update text and add one more confirmation level when deleting an account

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2127]
Currently if one tries to delete one's account, one is met with this:
 
<img width="636" alt="image" src="https://user-images.githubusercontent.com/15896181/51947017-463fb880-23d8-11e9-8b22-b06ec23a6e42.png">

Which a) doesn't specifically get across that deleting an account removes all observations, IDs, and comments and b) doesn't have one last confirmation that prevents the user from accidentally or casually deleting the account.

While we don't get too many requests from users who want their accounts resurrected, it is resource intensive, so in order to prevent more situations where users request a mulligan, I propose we:

- Edit the text to something like "Are you sure you want to delete your account?  By deleting your account, you will permanently remove all observations, IDs, comments, and projects you have contributed to iNaturalist. This cannot be undone, and we will be sorry to see you go."

- Once the user clicks "OK", have the user type in a word such as "yes", or perhaps even their password (Vimeo does this for video deletion), making them perform a conscious action to delete the account.

I suppose we should then decide on a policy for someone who wants an account restored: is that a strict "no" on our end, do we charge a fee, etc?

**Comment by tiwane** [comment]
That sounds like a good solution, although I would stipulate they should verifiable obs. 

Am still kicking around thoughts on the warning text.

**Comment by kueda** [comment]
Closed in efedbc83255719cc2fef9287b5ac82273a5177c5
