### ISSUE TITLE
unescaped markup in checklist view

### ISSUE THREAD

**Issue by dartar** [inaturalist/inaturalist#2134]
See attached. Link: https://www.inaturalist.org/check_lists/155186-Soberania-Check-List?page=1&view=photo
<img width="436" alt="screen shot 2019-02-03 at 10 17 17 pm" src="https://user-images.githubusercontent.com/209506/52192979-a9c74d00-2801-11e9-8476-752dcb5a707e.png">

**Comment by tiwane** [comment]
Just bumping this.
