### ISSUE TITLE
Web uploader erroneously reading horizontal accuracy in JPGs converted from HEIC

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2140]
1. On a Mac, open up [this photo](https://www.dropbox.com/s/0rep64qribtebj8/IMG_5455.HEIC?dl=0) (taken by Carrie on an iPhone XS) in Preview. If you take a look at the GPS data, you'll see it has a horizontal accuracy of ~5m:

<img width="296" alt="image" src="https://user-images.githubusercontent.com/15896181/52317414-c59f3000-2974-11e9-8bf3-f54ceb194a83.png">

2. Export as a JPG. Open up the JPG in Preview and you'll see it has the same horizontal accuracy. 

3. Add photo to the web uploader and click on location. You'll see it has an accuracy of ~238k m:

![image](https://user-images.githubusercontent.com/15896181/52317502-157df700-2975-11e9-9664-55361d7276d5.png)

Another user says the same thing was happening to him with iPhone photos imported into Lightroom, and then exported as JPGs.

Apparently this is not an issue when importing these photos directly into the iOS app.

**Comment by carrieseltzer** [comment]
I think this may be related to the non-integer format of the Horizontal Positioning Error from photos that were originally HEIC. Somehow, 5.574 is turned into 238172. In case more numbers help, here are a few more examples:

Horizontal Positioning Error: 7.652 to 104319
Horizontal Positioning Error: 4.94 to 69079
Horizontal Positioning Error: 5.115 to 72423

**Comment by kueda** [comment]
Fixed in 586bd2e375b81a5796eb7a779e45aa19009098d8
