### ISSUE TITLE
Taxon change update header can't be translated properly

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2142]
Currently looks like this:

<img width="782" alt="screen shot 2019-02-06 at 9 47 55 am" src="https://user-images.githubusercontent.com/22691/52361963-4ea97c00-29f4-11e9-823e-46206eb69b8b.png">

That's coming from https://github.com/inaturalist/inaturalist/blob/master/app/helpers/application_helper.rb#L1128, where we're modifying the article based on English rules in code. That should be up to the translators.

**Comment by Optilete** [comment]
Also 'replace with' is not translated in the update and the email with updates.

**Comment by Optilete** [comment]
> Also 'replace with' is not translated in the update and the email with updates.

![image](https://user-images.githubusercontent.com/46406827/54092853-a0e21200-4391-11e9-8f33-19ea273f50fe.png)
