### ISSUE TITLE
"project_observations_count" and "observed_taxa_count" in JSON object don't match actual counts for collection/umbrella projects

### ISSUE THREAD

**Issue by giorap** [inaturalist/inaturalist#2145]
Hello!

I am developing a web app that displays iNaturalist data across California's marine protected areas. I have recently generated projects for all marine protected areas and was playing around with the API to download all necessary information from those projects. 

It came to my attention that JSON objects appear to inaccurately summarize some of the information contained within the projects I created. In particular, "project_observations_count" appears to equal 0 for all the projects I generated, regardless of the number of observations they actually contain. For example, compare:
https://www.inaturalist.org/projects/california-mpas-montara-state-marine-reserve
https://www.inaturalist.org/projects/california-mpas-montara-state-marine-reserve.json

I did a bit of searching and this issue appears to apply broadly to most (if not all) projects with project_IDs 19517 and above, created on or after 20 April 2018, which I believe must coincide with the introduction of the new collection and umbrella projects.

I just wanted to a) flag this potential issue and b) ask whether, in case this issue is not easily resolved, there may be an alternative way to obtain project observations counts using the API.

Thank you so much for your help,
Gio

**Comment by pleary** [comment]
You can use the newer API at https://api.inaturalist.org for this. For example https://api.inaturalist.org/v1/observations?project_id=california-mpas-montara-state-marine-reserve

That API is the basis for all collection and umbrella projects so the counts return should accurately reflect what those projects are displaying. The JSON API available via the website will not return accurate information about these types of projects. We'll have to fix that. Thanks for the report!
