### ISSUE TITLE
Going to pages from some updates in the dashboard doesn't clear notification from header

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2169]
Right now if someone adds a comment to one of my observations and I click on the observation from my dashboard, that notification is marked as cleared in the header. For some content, however, that doesn't happen, such as:

- comment on a journal post
- flags
- taxon changes

**Comment by boucur** [comment]
Same issue for notifications about comments on "listed taxa" pages, e.g.
https://www.inaturalist.org/listed_taxa/6152456
