### ISSUE TITLE
Species API documentation

### ISSUE THREAD

**Issue by juliquiron** [inaturalist/inaturalist#217]
Hi all,

I'm looking at iNat API docs and seems that there are no way to get information about all species like showed in http://www.inaturalist.org/taxa

But playing with it geting: http://www.inaturalist.org/taxa.json seems that exists an API not documented.

What is happening? there is the option to GET/POST API with taxa.json? can I help to document it?

thanks!

**Comment by premasagar** [comment]
I noticed the /taxa/:id.json endpoint and came here looking for a mention of it. It has more data than the taxon summaries included in other responses, like /observations.json?taxon_id=:id

An example:
* https://www.inaturalist.org/taxa/48599.json
* https://www.inaturalist.org/observations.json?taxon_id=48599

**Comment by kueda** [comment]
I'm closing this b/c we've largely stopped using the Rails app for public-facing APIs. Please check out http://api.inaturalist.org/v1/docs/#/Taxa and if you have further requests please file issues at https://github.com/inaturalist/iNaturalistAPI
