### ISSUE TITLE
Add a "wild only" toggle to Identify page and have it marked by default

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2173]
As brought up [here](https://forum.inaturalist.org/t/make-captive-cultivated-not-automatically-no-id-needed/112): 

- some users are quite interested in identifying observations of non-wild organisms.
- many new users unwittingly add observations of non-wild organisms and thus never receive an ID and may not use the app again.

Would it be possible to add a "Wild only" toggle to the Identify page and have it marked by default? This way, if someone wants to identify non-wild organisms they can sift through observations that have the requisite evaluative attributes but are not wild?

**Comment by kueda** [comment]
That's essentially how it works now. Is the thinking that it's confusing to check "Captive" and uncheck "Needs ID"?

**Comment by tiwane** [comment]
Apparently it was too confusing for me. Then again I never want to look at non-wild observations. I think it's fine to keep it the way it is.

**Comment by kueda** [comment]
We could make it so when you click "Captive" it automatically changes the Data Quality filter to "Casual" which would basically do the same thing, and maybe make the process less confusing.

**Comment by tiwane** [comment]
OK, that sounds good.
