### ISSUE TITLE
Un-checking "verifiable" on taxon page map removes all observations from map

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2174]
eg https://www.inaturalist.org/taxa/82096-Magnolia

![image](https://user-images.githubusercontent.com/15896181/53921030-ec0fc400-4023-11e9-850e-1ed2889df241.png)

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/15896181/53921010-dbf7e480-4023-11e9-8fb1-4a6648db47fb.png">

**Comment by kueda** [comment]
Is this a bug? The checkbox defines a layer on the map, in this case a layer of all verifiable observations. If you uncheck it, you remove that layer... so no verifiable observations will appear.

**Comment by tiwane** [comment]
Gotcha. Here's a possible solution: https://forum.inaturalist.org/t/change-taxon-page-map-verifiable-unverifiable-functionality/571

**Comment by kueda** [comment]
That seems like a proposed solution to a different problem (showing captive stuff on taxon maps), so I'm going to close this, b/c it's working as intended
