### ISSUE TITLE
Maatian Maps

### ISSUE THREAD

**Issue by xavierherron** [inaturalist/inaturalist#2176]
Vertical Datums

We would like to share this information (vertical datum) and (vertical data projections) plus the paradigm considering the removal of virtually all dams.

 
This information will be shared for risk management in order to determine where to build resiliency structures for neighborhoods and communities and possible commercial applications.

I'm adding a link to this correspondence that has art and research I put together with some facts but there are more reasons to be found all around on this domain. https://superspacefaith.tumblr.com/post/180256186893/hydropower-reached-its-peak-in-the-1940s-forty

Sincerely, a huge fan

**Comment by kueda** [comment]
Hi Xavier. We use github issues to track proposed changes to our code that we can actually act on, and since I'm not seeing any such proposal here, I'm going to close this. If you have questions about iNat functionality, please ask a question at https://forum.inaturalist.org
