### ISSUE TITLE
When searching for observation fields on obs detail page and on the uploader, rank results by number of observations the field has been used on

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2181]
There are many observation fields that all serve basically the same purpose, eg fields that are used to indicate the organism is dead. Right now, when searching to add said information to an observation, I get:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/15896181/54063518-a38e0d00-41c1-11e9-9070-a2135a1c398a.png">

Which is a bit of a jumble. As a way to get some observation fields used more than others of the same ilk, and thus become more "universal" (and hopefully more useful) I  propose that search results like the one above be ranked by the number of observations on which each field has been used.

**Comment by kueda** [comment]
Ok, I'm pretty sure this should be addressed by 8d5b53c8375402d6dd40b067c2204989a7b89314, but be on the lookout for reports of people who cannot find their observation field.
