### ISSUE TITLE
Chrome's address autocomplete feature obscures location autosuggest in observations interface

### ISSUE THREAD

**Issue by kaldari** [inaturalist/inaturalist#2198]
If you have address autocomplete turned on in Chrome and you start typing in the location field of the observations interface (https://www.inaturalist.org/observations), Chrome's address autocomplete menu pops up and obscures the autosuggest menu, preventing you from being able to click on it (even though the field is marked `autocomplete="off"`). See upstream WONTFIXed bug at https://bugs.chromium.org/p/chromium/issues/detail?id=468153. Unfortunately, disabling this behavior from the HTML is not at all straightforward (https://gist.github.com/niksumeiko/360164708c3b326bd1c8), but it looks like there may be some hacky ways to work around Chrome's aberrant behavior.

**Comment by kaldari** [comment]
![Screen Shot 2019-03-21 at 4 13 51 PM](https://user-images.githubusercontent.com/1707155/54790739-67f93700-4bf4-11e9-9ae7-fa9a2432b44f.png)

**Comment by kueda** [comment]
@kaldari this has been released and it's working for me in Chrome 73.0.3683.86, so let me know if you're still seeing this problem. If so, I can try messing with the placeholder as you [suggested](https://github.com/inaturalist/inaturalist/commit/8e47a42e60c5a6fc2bbdb2a1baed0177be63aba9#commitcomment-32868502), though I'd rather not.

**Comment by kaldari** [comment]
@kueda - Confirmed that it's fixed for me as well. Thanks!
