### ISSUE TITLE
Show multiple taxa on one map

### ISSUE THREAD

**Issue by hamiltont** [inaturalist/inaturalist#2207]
This seems similar to #487, but I don't think that one was finished. 

For a taxonmap such as the one shown on https://www.inaturalist.org/taxa/29299-Nerodia it would be great to be able to show differently colored markers for different sub-taxa

**Comment by boucur** [comment]
This is the typical place to post feature requests:
https://forum.inaturalist.org/c/feature-requests/

**Comment by kueda** [comment]
Closing b/c it needs to be spec'd out more. We usually use github issues for actionable work, and as Cassi mentioned, we'd prefer that feature requests go through forum.inaturalist.org. FWIW, there are a lot of things we could use color for on the taxon maps (captive vs wild, native vs introduced, multiple infraspecies, etc), and it's not clear which one serves the most people.
