### ISSUE TITLE
Observation.reassess_coordinates_for_observations_of should use ES

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2213]
Currently it's executing a very slow database query to get all observations that have current identifications of a taxon (and its descendants). As of d39bb88a6a84ef2820d3e02ac2794d0858f2f29c, we are storing all taxon IDs from current identifications in the observations index, so we should be able to use that instead, but I think we still need to re-index all obs before we can do that.

**Comment by pleary** [comment]
Fixed in 870d702
