### ISSUE TITLE
When viewing iNat in a non-English language Taxon About section doesn't show English Wikipedia page if viewing language doesn't have one

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2216]
1. View iNat in Danish and go to https://www.inaturalist.org/taxa/522781-Diurnea-lipsiella
2. Danish Wikipedia doesn't have an entry for this taxon, but the English one does. Rather than show the English version, iNat searches EoL and shows nothing.

Chris Cheatle says that prior to some Wikipedia changes we made in the last few months, iNat would show the English Wikipedia article if one didn't exist for one's chosen language. Can that behavior be restored?

**Comment by kueda** [comment]
So what would be the preferred priority? Locale-specific Wikipedia, EOL, then English Wikipedia?
