### ISSUE TITLE
Connect to ORCID is broken

### ISSUE THREAD

**Issue by dshorthouse** [inaturalist/inaturalist#2226]
Attempting to connect to ORCID in my account for the first time throws an issue @ ORCID's end: "Please check your client id, scopes and redirect URIs.". Something appears to be amiss in your keys/redirect URLs or other for a functioning OAuth2 integration.

**Comment by kueda** [comment]
Thanks, it was a minor sysops hiccup that should be fixed now.

**Comment by pleary** [comment]
Sorry - I accidentally broke the ORCID config last night. Thanks for making a ticket!

**Comment by dshorthouse** [comment]
Thanks for the quick turn-around gents.
