### ISSUE TITLE
Allow rightsholder to be different from uploader in metadata editing interface

### ISSUE THREAD

**Issue by jar398** [inaturalist/inaturalist#2240]
The iNaturalist site assumes that the person with the iNaturalist account (the uploader) is the same as the rightsholder for the photograph. This is not necessarily the case. For example, last weekend I went to Great Meadows with a friend; I found specimens, the friend photographed them, and I uploaded them.

The site's legal terms of service allow me to upload someone else's properly licensed photos, but once uploaded there is no way to provide legally correct metadata. So this problem is purely technical, with the metadata editing interface, not legal.

I would suggest in the metadata editing interface that there be a way to say who the rightsholder is, or at least to say that the rightsholder is a third party. (In my case their name and license is given in the photo's EXIF data.) The summary language under "edit license" should be modified because "you" seems to be the person using the web interface, not the rightsholder, and if "you" is not the rightsholder, none of the options that are offered is legally justifiable, since they all require "you" to have legal rights to the image. This includes both the CC0 and "no license" options.

(By the way, for images that are in the public domain there ought to be an additional option, something like CC PDM - but I should submit that as a separate issue)

**Comment by kueda** [comment]
It is not strictly a technical issue. We don't really want people uploading photos taken by other people. We want everyone to experience iNat for themselves and benefit (or not) from community input in the same way. We value the *people* involved in iNat much more than we value the data. You can read more about what our priorities are at https://www.inaturalist.org/pages/what+is+it

That's not to say I'm opposed to this, but it's not simply a matter of adding some metadata to photos. This would represent a major change in our policies as well, so it's not something to be taken lightly.

Also, the Forum is a better place to raise issues like this that require discussion: https://forum.inaturalist.org/c/feature-requests. More people can provide input, and we can better gauge interest.

**Comment by jar398** [comment]
I can see now that it is not purely technical. But I don't understand the logic that rules out collaboration on an individual observation. If in another case, there were two photos for a single observation by two iNaturalist 'users', there would be no way for the metadata to be correct in that situation either. I also don't see why you want to exclude people who cannot or will not create an inaturalist account from participating - the effect is to decrease participation, which is the opposite of what you want.

I will remove these ten observations and take the discussion to the forum. Thanks for your attention!
