### ISSUE TITLE
Allow to search just photos

### ISSUE THREAD

**Issue by nemobis** [inaturalist/inaturalist#2242]
https://github.com/inaturalist/inaturalist/issues/1829 shows there is interest in being able to search photos on iNaturalist.

For a new user like me, there seems to be no search for photos at all at first. If I search a species in the main search bar I get something like https://www.inaturalist.org/search?q=Amaryllis-paradisicola and the top bar does not help, instead I have to click a link "view observations" next to a name, which leads to https://www.inaturalist.org/observations?taxon_id=579700

Once I'm on that page, nothing is shown at all unless I allow loading scripts from maps.google.com, which I don't want to do for a variety of reasons and is unexpected as I never asked for a map. Once I allow loading the map, a list of photos somewhat appears in the right corner. It would be nice to be able to get just that.

A workaround would be to provide a search API or some feed for external search engines to provide the service, for instance Creative Commons search [as suggested](https://twitter.com/ReaderMeter/status/1123392103042535424) by Dario.

**Comment by kueda** [comment]
I'm not really sure what you're asking for here, so I'm going to close this. You can search observations in the header by entering "Amaryllis paradisicola" and clicking the "View observations" link. You can also do so at https://www.inaturalist.org/observations. You can view all *photos* of a taxon from the taxon detail page (e.g. https://www.inaturalist.org/taxa/579700-Amaryllis-paradisicola) by clicking "View More" under the photo. If you're hitting bugs b/c you block scripts from Google, that's a different, larger issue concerning our dependency on Google. I'm not sure we'll ever make it possible to use the site without Google (certainly looking into it for users in China), but right now, there's no way around that.

FWIW, you might find GBIF's search tools a bit more satisfying, e.g. https://www.gbif.org/occurrence/gallery?media_type=StillImage&taxon_key=7346102. You can also filter that to only include iNat contributions to GBIF.

For future feature requests, please go through the [Forum](https://forum.inaturalist.org) so we can talk things through and the rest of the community can provide input. We'd prefer to reserve github issues for things where product-level discussions and decisions have already happened.
