### ISSUE TITLE
API: DELETE /observations/:id doesn't returns what's documented

### ISSUE THREAD

**Issue by niconoe** [inaturalist/inaturalist#2252]
I encountered the following issue while working on [Pyinaturalist](https://github.com/inbo/pyinaturalist).

When deleting an observation with the rest API (DELETE /observations/:id), your documentation shows an example where a proper JSON (occurrence details) is returned. In practice, it seems iNaturalist is returning an empty response body, with an HTTP status of 200.

Both options are fine for me, I just wanted to point the inconsistency. Tell me if you prefer to fix the documentation or the code, and I'll adapt Pyinaturalist to work with it.

**Comment by kueda** [comment]
Sorry about that, and about the late response. I updated the docs.
