### ISSUE TITLE
Can no longer choose Jamaica as an option in the Explore autosuggest menu

### ISSUE THREAD

**Issue by kaldari** [inaturalist/inaturalist#2253]
I'm not sure what changed, but I can no longer choose Jamaica as an option under Explore (https://www.inaturalist.org/observations). See screenshot:
![Screen Shot 2019-05-08 at 11 17 07 AM](https://user-images.githubusercontent.com/1707155/57386814-27915080-7183-11e9-9f95-c236ff4fb06a.png)
Perhaps preference should be given to exact matches (or just countries and states in general, since so many smaller places are named after them).

**Comment by pleary** [comment]
That search box uses a Google API to search places known to Google (which we then attempt to match to place known to iNaturalist after searching). One parameter we use when searching is the current bounds of the map in the map subtab of observation search. So if the map is focused on the north-east United States, you're more likely to get results from that area than other areas. Similarly you'll get different results depending on where the map is focused.

If you want to search all places known to iNaturalist, I recommend you open the filters menu, expand "More Filters", and search for Jamaica in the "Place" search field.

Nothing has changed on our end, and we don't control Google's place search algorithm, so I'll close this ticket.
