### ISSUE TITLE
Can't join converted collection project that was once invite-only

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2259]
This project was originally a traditional one, and invite-only. It was converted to a collection project but it can’t be joined by someone not invited, you get a 

`Membership in this project is by invitation only. If you'd like to join, please contact one of the curators below and request an invitation. `

error message. https://www.inaturalist.org/projects/butterflies-on-central-time

**Comment by pleary** [comment]
fixed on master branch, and is on staging. We just need to deploy to production
