### ISSUE TITLE
Resolved flag text is inaccurate

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2262]
From cmcheatle (https://forum.inaturalist.org/t/text-for-flag-resolution-notification-is-wrong/3229)

![image](https://user-images.githubusercontent.com/15896181/57669772-48153c80-75c1-11e9-8c00-8bb92f2449d1.png)

"2 problems in the text
    - contrary to what it says, I did not add the flag, I resolved it
    - it says the flag was created by a deleted user, this is not true, it was an automatic system flag generated by the iNat account"

**Comment by tiwane** [comment]
This can be marked completed, correct, @pleary?

**Comment by pleary** [comment]
yes this should be resolved now. It should now longer make any statement about who added the flag if its not associated with a user, nor anything about who originally flagged it
