### ISSUE TITLE
On observation details page, text started in Comments tab should appear in Suggest an ID tab and vice versa

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2266]
Suggestion from [this thread](https://forum.inaturalist.org/t/standardize-adding-ids-from-observation-detail-page-vs-identify/3085). If I start writing a omment but decide to switch over to Suggest an Identification (which, I have to admit, I often do) the text I've entered into Comment should be retained when I switch tabs, and vice versa.

**Comment by albullington** [comment]
@tiwane are you still seeing this issue? This is working for me on Chrome.

**Comment by tiwane** [comment]
Yeah, it's working. I'll close.
