### ISSUE TITLE
Attempt a validation to prevent observations from having an observed-on date that is after the submitted date

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2274]
Based somewhat on [this thread](https://forum.inaturalist.org/t/date-submitted-before-date-observed/3120), as well as attempts by some users to cheat for CNC by changing observed-on dates of their observations, can we try to perform a validation that prevents an observed-on date from being edited/added if it is *after* the submitted date?

Main issue would probably be accommodating time zones.

**Comment by kueda** [comment]
Many, many unintended consequences later, I think this is finally done.
