### ISSUE TITLE
Add a better description for taxon swap

### ISSUE THREAD

**Issue by kaldari** [inaturalist/inaturalist#2276]
The interface for a taxon change (e.g. https://www.inaturalist.org/taxon_changes/new?input_taxon_ids=53809&type=TaxonSwap) currently lists 5 different types of changes. Of these, it seems that "Swap" is probably the most commonly used. However, the description for "Swap" is extremely short and confusing: "1-to-1 name change". My understanding is that "Swap" actually means merge an existing taxon into another existing taxon. It would probably be better to call the feature "Synonymize" rather than "Swap", but at the very least it needs a better description. Both myself and Ken had to talk to other curators before we could figure out what it actually did.

**Comment by kueda** [comment]
"Synonymize" doesn't really work b/c that could also describe a merge, e.g. if you decide Species A and Species B are in fact both just Species B, then you've synonymized them. All taxon changes basically do the same things: deactivate the input taxon, activate the output taxon, and attempt to move all records associated with the input taxon to the output taxon whenever possible. Merges, splits, and swaps mostly differ in how much of that re-assignment we can automate and whether or not people need to be notified about changes they may have to perform manually.

"1-to-1 name change" isn't terribly descriptive, I agree. Would "Replace input taxon with the output taxon" be better?

**Comment by kaldari** [comment]
Yes, "Replace input taxon with the output taxon" would be a better description, or "Merge input taxon into the output taxon". Anything would be an improvement, really :)

**Comment by kaldari** [comment]
Created a pull request for this at https://github.com/inaturalist/inaturalist/pull/2714.
