### ISSUE TITLE
Collection projects with exclusion filters in should give correct counts in umbrella projects

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#2278]
Collection projects with exclusion filters aren't showing correct totals on umbrella project leaderboards.

Examples: 
https://www.inaturalist.org/projects/malaysia-outside-cnc shows a count of 48K
but the umbrella project containing it shows the same project with a count of 230K+
https://www.inaturalist.org/projects/malaysia-umbrella
![Screen Shot 2019-05-09 at 5 43 09 PM](https://user-images.githubusercontent.com/7501183/58127235-e6695980-7be2-11e9-85cd-10a5fad540ef.png)

The total number of observations recorded in the umbrella project should also be calculated taking into account the exclusion filters on contained projects. 

Here is another example pair of a collection project with exclusion filters and umbrella project with an incorrect tally:
https://www.inaturalist.org/projects/unknowns-of-naturemap?tab=observations
https://www.inaturalist.org/projects/naturemap-plants

**Comment by pleary** [comment]
This should be fixed now
