### ISSUE TITLE
On Obs detail, Projects section shouldn't show umbrella projects which the observer has not joined

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2279]
EG: https://www.inaturalist.org/observations/22138182

bouteloua has joined [Illinois Botanists Big Year 2019](https://www.inaturalist.org/projects/illinois-botanists-big-year-2019) but has not joined the [Great Lakes Botanists' 2019 Big Year](https://www.inaturalist.org/projects/great-lakes-botanists-big-year-2019). The latter is an umbrella project that includes the former project.

**Comment by pleary** [comment]
This bug should be fixed now. I think this example is no longer valid, but please let me know if you see this happening anywhere else.

**Comment by boucur** [comment]
weird, I don't remember joining that project. checked several other examples, e.g. none of these should be in "[Illinois Botanists Big Year](https://www.inaturalist.org/projects/illinois-botanists-big-year)" umbrella (just the 2019 collection project). Looks OK for me now!

https://www.inaturalist.org/observations/25780020
https://www.inaturalist.org/observations/25779225
https://www.inaturalist.org/observations/25424426
