### ISSUE TITLE
UX Suggestion - stop default action of backspace

### ISSUE THREAD

**Issue by PhasonMatrix** [inaturalist/inaturalist#2281]
I am a user of the iNaturalist web interface. When entering data for an observation, if I hit backspace in an empty species field, the browser takes the backspace key-press event and navigates to the previous page. The user loses all their work from the observations they were editing and had not uploaded yet.

**Comment by kueda** [comment]
Can you provide URLs and/or screenshots of the pages and specific fields you're referring to, as well as what browser you're using? For example, I just tried hitting the `delete` key on my keyboard inside numerous fields at https://www.inaturalist.org/observations/upload and could not replicate the behavior you're describing.

**Comment by kueda** [comment]
Ok, I'm not sure what I can here without further context. Please re-open if you can provide the context I requested.

**Comment by PhasonMatrix** [comment]
Hi @kueda , Sorry about the delay. I just tested again and was able to reproduce the issue. Steps to reproduce:
1. On the upload observations page (www.inaturalist.org/observations/upload) create at least two observations.
2. Select a species for the first observation.
3. Click out of the species textbox, then click back into it.
4. Press and hold backspace. the species name will be backspaced out and when it is completely gone, the browser takes the backspace keypress and navigates back to the previous page.

Not so much a problem if you only have a couple of observations. But if you have many, a lot of work is lost.

Hopefully this screenshot uploads okay:
![image](https://user-images.githubusercontent.com/37615629/60750840-99561100-9ff1-11e9-81fc-060512ac080c.png)

**Comment by kueda** [comment]
Ok, I still can't replicate, but maybe it's b/c I'm using a Mac keyboard. I take it you're on some kind of PC? Also, what browser and operating system?

**Comment by PhasonMatrix** [comment]
Sorry, I should have mentioned that. I'm using Firefox on Windows 10. I just tested on Chrome and I do not get the same behavior. Seems to be isolated to Firefox. Hope that helps.

**Comment by kueda** [comment]
Many years later, I still can't replicate this in Firefox, but we've also added a guard against leaving the Uploader without uploading, so hopefully that addresses this.
