### ISSUE TITLE
Log the first few lines of response for 422 errors

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2282]
Not all of our apps actually show the content of 422 responses, which can make it difficult to understand what's going wrong, so when we log a request in logstasher, let's include the first 15 lines of the response when

1. The response code is 422
1. The response format is JSON

**Comment by pleary** [comment]
I was not able to have logstash log the 422 error within the `ActionController` subtype of logstash logstash logs that we write for every request. We're using `ActiveSupport::Notifications.subscribe` for those logs and I couldn't see how to get the response body there. So I added an `ApplicationController` around filter and that'll write an additional log of subtype `Unprocessable` that contains the 422 error response. That's working in production now and you can search logstash Kibana for `subtype:"Unprocessable"`
