### ISSUE TITLE
"captive=false" param on Identify does not disappear

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2288]
On Identify, if one chooses checks Research Grade in the filters, this URL appears: https://www.inaturalist.org/observations/identify?quality_grade=needs_id%2Cresearch&captive=false

If one un-checks Research Grade, the URL becomes: https://www.inaturalist.org/observations/identify?captive=false

If one the checks Casual, this is the URL: https://www.inaturalist.org/observations/identify?quality_grade=needs_id%2Ccasual&captive=false

**Comment by kueda** [comment]
What you're describing is the behavior I would expect. What change are you proposing?

**Comment by tiwane** [comment]
Partly I'm curious as to why `captive=false` is necessary if you choose Needs ID and RG. By definition, aren't those already `captive=false`? I'm sure it has to do with something technical that I don't know about, but as I said, I'm curious.

More broadly, in the last example there, I would expect that `captive=false` be removed if I choose Casual, since I haven't specified yet that I want to see casual observations that have not been marked captive. I want to see *all* casual obs but the vestigial `captive=false` from my previous RG selection prevents me from doing so.

**Comment by kueda** [comment]
`captive=false` isn't necessary. So is the bug that `captive=false` is being set unnecessarily? If it's actually set in the URL, then I wouldn't expect it to disappear until you mess with the "Captive" checkbox.

**Comment by tiwane** [comment]
Yeah, I would remove it unless  you actually click "Captive" on or off.
