### ISSUE TITLE
Broken redirect on sign in

### ISSUE THREAD

**Issue by dartar** [inaturalist/inaturalist#2297]
I have found a bug that occurs on a mobile client when signing out and signing in again with a different username (disclosure: I created accounts for my parents and sometimes I log in with their credentials to check / fix things on their behalf). The bug causes the sign-in process to redirect to the following URL: https://www.inaturalist.org/users/updates_count.json instead of the user dashboard or whatever the original page was. 

Steps to reproduce:
1. Log in as user A
2. Visit the dashboard page
3. Select “sign out” from the hamburger menu
4. Log in as user B
5. The website will redirect to the above URL returning the following JSON response: {“count”:0}

Client: Safari for iOS latest version on an iPhone 7s. I haven’t tried to reproduce this with different browsers or devices but I’ve seen the bug multiple times.

**Comment by kueda** [comment]
I can't replicate this in desktop Safari or in iOS Safari in the Simulator, and I'm pretty sure this is the same as #1528. Are you logging in with normal credentials or are you logging in with Google or Facebook?

**Comment by kueda** [comment]
I deployed what *might* be a fix. Is this still happening for you, @dartar?

**Comment by kueda** [comment]
I'm assuming this is fixed. Please re-open if it's not.
