### ISSUE TITLE
"Dead Spot" on Explore and Taxon Maps

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2299]
If you zoom in on the map until you can see pins, observations in the upper left-hand corner of the map cannot be be clicked on. The pointer stays as an open hand.

**Comment by kueda** [comment]
I can replicate. It's sort of like the left 40% and upper 80% of the map view. Spent some time investigating this afternoon but didn't make any headway. Does this sound at all familiar, @pleary?

**Comment by pleary** [comment]
Seems like a bug in wax.g. For observations we always use at least 2 layers - one for the circles and one for points. They each have a min/maxZoom to say where they stop. wax.g was still looking at out-of-zoom layers for interactions, and for whatever reason the ordering must have changed recently and it was looking for interactions in the hidden layers and not the active layers. So I just made it so it'll never attempt to use an out-of-zoom layer for interactions. Hopefully that'll be a universal fix

**Comment by tiwane** [comment]
Looking good on Brave.
