### ISSUE TITLE
Welcome email subject in Russian was sent to English speaking user

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2307]
The subject line for use  1906824's welcome email was in Russian:

<img width="763" alt="image" src="https://user-images.githubusercontent.com/15896181/60047296-3756ec80-967e-11e9-8ced-30efbd7789cc.png">

**Comment by kueda** [comment]
So the commit above *might* fix this. It's hard to test b/c I think the bug had to do with a delayed job process getting stuck with a locale set to Russian based on some previous job it ran, and since I don't know what job that was, I can't really replicate it.
