### ISSUE TITLE
Why is exponential notation used in charts?

### ISSUE THREAD

**Issue by kevinhikaruevans** [inaturalist/inaturalist#2318]
Was just curious after reading [this forum post](https://forum.inaturalist.org/t/number-of-verifiable-observations-2e-4/4736). Is there a reason why exponential notation is used? It seems like it was intentional looking at the jsx. Would it be better to use a more readable format, like 10K instead of 1e+4?

https://github.com/inaturalist/inaturalist/blob/67320ef68834b9d9b64d9975df7b94902c76c56f/app/webpack/taxa/show/components/charts.jsx#L65-L76

PS: if this should be changed, can I do the PR for it?

**Comment by tiwane** [comment]
@pleary and @kueda any thoughts?

**Comment by kueda** [comment]
To answer the question of "why is it like this," a) sloth, and b) ease of translation. I'm fine with reviewing a PR that expresses those large numbers as something like `1K`, `10K`, `100K`, `1M`, etc., but keep in mind it must be translatable and the translation keys should have some context. Similar abbreviations like [`1h` for `1 hour`](https://github.com/inaturalist/inaturalist/blob/master/config/locales/en.yml#L2023) already cause a decent amount of confusion among translators, even with context.
