### ISSUE TITLE
Captive filter on observations/search not working right

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#232]
of 500,424 obs (http://www.inaturalist.org/observations)
the captive = false filter is returning 46,940 (http://www.inaturalist.org/observations?&captive=false)
and the captive = true filter is returning 5,643 (http://www.inaturalist.org/observations?&captive=true)
a spot check of the 46,940 obs returned from http://www.inaturalist.org/observations?&captive=false shows that many have captive=nil (e.g. http://www.inaturalist.org/observations/528205), evidence that captive=false includes captive=nil
then why does 46,940 + 5,643  != 500,424?

**Comment by pleary** [comment]
Search is now returning captive=nil and captive=false when the search param ?captive=false is set
