### ISSUE TITLE
Change the "Budding" controlled term value to "Flower budding"

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2326]
The controlled term value "Budding" under "Plant Phenology" is ambiguous, as it could mean either leaf budding or flower budding, and some users have been confused by it. We could change it to "Flower budding" to specify that it refers only the flower budding and still keep it under the Plant Phenology heading. This would allow us to use other terms like "leaf budding" under the Plant Phenology controlled term.

Alternatively, we could  change the current "Plant Phenology" to "Flower Phenology" having more specific values under one controlled term seems more efficient to me.

**Comment by pleary** [comment]
Given that we're currently limiting these terms to Angiosperms, it's safe to turn `Budding` into `Flower budding`. I think that's the best action for now, so fruiting can stay there and we can add leaf-related values later if we want.

**Comment by tiwane** [comment]
Cool, sound good to me.

**Comment by kueda** [comment]
Ok, so the decision here is just to turn "Budding" into "Flower Budding"? If so, todos are

- [ ] Add "Flower Budding" versions of all translatable strings in web and mobile
- [ ] Ensure these work on the web
- [ ] Release versions of the mobile apps with these updated source strings
- [ ] Deploy new strings in the web app
- [ ] Update the controlled term

**Comment by kueda** [comment]
Also, I assume you want the Identify keyboard shortcut to add a a `Flower Budding` annotation to remain `P+U`?

**Comment by tiwane** [comment]
Yeah.
