### ISSUE TITLE
Add meters to "positional_accuracy" when exporting data

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2328]
From https://forum.inaturalist.org/t/when-downloading-data-provide-units-for-the-positional-accuracy-field/3933

Can it be changed to something like 'positional_accuracy_(meters)' or whatever would work best?

**Comment by kueda** [comment]
Are you proposing we change the name of the column heading to make it clearer that the units are meters? IMO, this is implied and the disruption of changing the column name will do more harm than good.

**Comment by tiwane** [comment]
Agree that it's not particularly important. If it's not a good change I'll close this.

**Comment by carrieseltzer** [comment]
This issue of metadata describing the fields is one that should be addressed somehow to make the exports easier to interpret, but I agree that changing the name of the field is not the best way to approach it.
