### ISSUE TITLE
Changing "private" geoprivacy to "open" of an auto-obscured observation doesn't take

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2330]
1. Make an observation of an auto-obscured taxon. The example from the user was _Libellula vibrans_ in Ohio.

2. Before uploading, set geoprivacy to private.

3. After upload, edit observation's geoprivacy to open.

4. Map still shows private for other users, but under "Details" it says "open" for geoprivacy.

**Comment by pleary** [comment]
I have an open PR for this https://github.com/inaturalist/inaturalist/pull/2424. Would be great to have someone double check the code to make sure it's only fixing this bug and not causing other problems

**Comment by pleary** [comment]
This should be fixed now after this PR was merged
