### ISSUE TITLE
On collection project observations tab, show link to Explore at end of results

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2332]
From https://forum.inaturalist.org/t/display-all-observations-on-project-pages/4951

When you click on the "[X number of] Observations" tab, you are only shown about 200 observations, and there is no link at the bottom of the page to either load another page, or to view all observations in explore. I think pagination is the preferred solution from the community, if possible.

**Comment by kueda** [comment]
Ok, so what we want to do is when you've loaded all the results on this tab (200, I guess), show a link to `/observations?project_id=${project.slug}&verifiable=any&place_id=any` with the text "View more"

**Comment by bianavarga** [comment]
Working on this.
