### ISSUE TITLE
Split up i18n-js translations

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#2336]
The application_bundle is getting very large. It's over 800KB (compressed) to download, which is larger than even our biggest React/webpack JS (~600KB) and the next largest files needed for the website are usually the Whitney fonts (~350KB).

Part of what application_bundle contains is all the i18n-js translations for all languages. I wonder if we should start to split up those translations in separate files per locale (see https://github.com/fnando/i18n-js#export-configuration-for-translations), remove them from the application bundle, and then only have the client load translations for their locale and any needed fallback locales.

**Comment by kueda** [comment]
Just wanted to add that while this is even more relevant now, one complication is that each file would still need to translate a few things into all locales, mostly the names of the languages that correspond to the other locales so a language picker UI can show the name of the other language in that language.
