### ISSUE TITLE
Delete "observation fields" records doesn't work

### ISSUE THREAD

**Issue by jhammock** [inaturalist/inaturalist#2341]
I was offered a Delete link in the pop up menu when I selected the "Eating" field under Observation Fields at https://www.inaturalist.org/observations/8363566, so I think I have the authority to delete these. When I selected the link I saw a spinner briefly, but the record was not deleted.

**Comment by jhammock** [comment]
Let me see... Yes, I'm still offered a Delete link for that field, and nothing happens when I select it. No spinner showed when I tried it just now, in case that tells you anything


![Screen Shot 2020-02-06 at 10 23 22 AM](https://user-images.githubusercontent.com/3026567/73951018-ecb37900-48ca-11ea-9efc-629e4f71ba8e.png)

**Comment by kueda** [comment]
Ah, I see. You're trying to delete an observation field value created by someone else. Currently, only the person who added a value OR the observer can do that.
