### ISSUE TITLE
audio in DwC-A

### ISSUE THREAD

**Issue by dnoesgaard** [inaturalist/inaturalist#2344]
I've just started adding some audio-based observations to iNat and then I noticed that we don't have any iNat records in GBIF with audio—is that intentional or just not implemented?

**Comment by kueda** [comment]
Not implemented. I assume we'd set `type` to `Sound` and `identifier` to the sound file URL? I think we'd also have to change the file name from `images.csv` to `media.csv` but I assume that would be fine with you as long as we update the metadata accordingly?

**Comment by dnoesgaard** [comment]
Yeah, sounds about right, e.g.

```
{
"format": "audio/aac",
"identifier": "https://static.inaturalist.org/sounds/44751.x-m4a?1564471010",
"type": "Sound"
}
```

I don't think the filename matters as long as it's correctly referenced in meta.xml. I've seen DwC-As with multimedia.txt containing the mapping between occurrences and images, etc....

@manongros do you want to confirm?

**Comment by ManonGros** [comment]
Yes exactly, just make sure that the `meta.xml` reflects the changes.
For example in this case, in the extension field:
```
<files>
     <location>images.csv</location>
</files>
```
Would become:
```
<files>
     <location>media.csv</location>
</files>
```
PS: Note that we have a blogpost on how to share multimedia on GBIF: https://data-blog.gbif.org/post/gbif-multimedia/

**Comment by dnoesgaard** [comment]
@kueda, when should we expect to see this in production? It looks like iNat will be the third-largest GBIF publisher of records with audio (after Xeno-Canto and Borror Lab)

**Comment by kueda** [comment]
Probably next week. Last week's export should have included them but it looks like there was a problem introduced with these changes so I need to fix that and restart the export.

**Comment by kueda** [comment]
Ok, sounds are now included in our DwC-A exports, including the one we make for GBIF. One issue I'm seeing is that we seem to be including content with licenses you may not want, like CC BY-ND. We've actually been doing the same for photos for some time (e.g. https://www.gbif.org/occurrence/891073197). Should we restrict media to only include CC0, CC BY, and CC BY-NC content like we do for observations?

**Comment by dnoesgaard** [comment]
That should be fine. As long as the observations themselves are not more restrictive than CC BY-NC.
