### ISSUE TITLE
Link to misidentified observations from the Similar Species tab

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2348]
On the Similar Species tab of the taxon page, there is a number in the upper right-hand corner of each taxon, indicating how many observations have been misidentified as that species. Would it be possible to add a link to that number which would take you to an obs search page showing those misidentified observations?

**Comment by pleary** [comment]
How does this look @tiwane ? There's still an issue in Firefox which makes it impossible to click the link in the badge tooltip, which I'll fix

**Comment by tiwane** [comment]
Looking pretty good in Brave, Patrick.

**Comment by tiwane** [comment]
Still not working in Firefox (version 71.0)

**Comment by pleary** [comment]
I think this is finally fixed in Firefox if you'd like to try again

**Comment by tiwane** [comment]
Working for me! Will close.
