### ISSUE TITLE
Add explanatory text about privacy to Messages page

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2352]
It would be good to remind people that direct messages on iNat are direct and not necessarily private. iNaturalist staff can and do look at them if there is a complaint or flag. So perhaps under this part of the Read/Write message page (see below), we can add some text, maybe in gray, that says "Private messages on iNaturalist can be read by iNaturalist staff. In general, we only view private messages when they have been flagged for moderation. If you require truly private communication, please look into third parties that support strong encryption."

![image](https://user-images.githubusercontent.com/15896181/62502053-86765e00-b7a2-11e9-9841-15cce35d9641.png)

**Comment by kueda** [comment]
Do you want to wait on this until we update the Privacy Policy?

**Comment by tiwane** [comment]
Yes.
