### ISSUE TITLE
Swedish common names don't show when locale is set to Swedish

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2365]
I can replicate on staging: https://forum.inaturalist.org/t/newly-rolled-out-swedish-translation-is-not-displaying-common-names-in-swedish/5745

eg [_Larus occidnetalis_](https://www.inaturalist.org/taxa/4345-Larus-occidentalis) has a Swedish common name, but if you go to that page, you'll only see the scientific name:

![image](https://user-images.githubusercontent.com/15896181/62992272-ad1e3f80-be07-11e9-93be-72c467ddf06a.png)

**Comment by kueda** [comment]
Fix deployed, relevant taxa have been reindexed.
