### ISSUE TITLE
Signup/Login Screen photo should display species name

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/inaturalist#2366]
Currently, the caption for the photos on the signup/login screen only display the user's name and location of the observation, but not the name of the species.
![image (3)](https://user-images.githubusercontent.com/44380775/63065180-f4650880-beb9-11e9-8534-c9a225fc89f3.png)

A fix for this would be to change the "Photo by" text to "[Species Scientific Name] observed by" with the scientific name linking to the observation, observer linking to their profile page, and place to obs search in a bounding box, as it is now.

**Comment by kueda** [comment]
Why the scientific name? Generally we lead with a common name, especially when we don't know anything about the preferences of the viewer.

**Comment by tiwane** [comment]
I lobbied for this thinking it would be easier in that we wouldn't have to know anyone's language or place_id choices (I know language is usually detected though, correct?), and it would emphasize the importance of scientific names.

**Comment by kueda** [comment]
IMO, if we all believe that, then scientific names should be the default across the site. I think that's a bad idea b/c new naturalists generally find them cryptic, intimidating, and exclusive.
