### ISSUE TITLE
On an observation's edit page, sounds cannot be uploaded or deleted

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2378]
The area is grayed out, eg: https://www.inaturalist.org/observations/31556475/edit

![image](https://user-images.githubusercontent.com/15896181/63825391-7e2bc180-c90f-11e9-917b-6db0142bb247.png)

**Comment by boucur** [comment]
sorry if this still just hasn't gone live yet or something, but they're still showing up greyed out for me
