### ISSUE TITLE
Using Quito Time Zone (ECT) for account's time zone results in weird observed_on_string

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2379]
I set my account's time zone to:

![image](https://user-images.githubusercontent.com/15896181/63897037-bfbc7b00-c9a8-11e9-9b37-bf7adf78d26d.png)

When I upload photos like [this one](https://www.dropbox.com/s/7tdond5iaypiaqf/DSC09398.jpg?dl=0), here is what the uploader page displays:

![image](https://user-images.githubusercontent.com/15896181/63897086-d5ca3b80-c9a8-11e9-9122-c0785eb3b1a5.png)

The text in the date/time field is ```2019/08/25 12:15 PM -05```

And no time is displayed for the observation: https://www.inaturalist.org/observations/31694532

Editing an observation and changing its date/time to ```2019/08/25 12:13 PM -05:00``` results in https://www.inaturalist.org/observations/31694526

![image](https://user-images.githubusercontent.com/15896181/63897224-4b360c00-c9a9-11e9-9b8d-307c0bce4514.png)

**Comment by kueda** [comment]
Pretty sure this is fixed. Please re-open if I'm wrong.
