### ISSUE TITLE
Do not delete descendent places when deleting a parent place

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#2381]
Currently, if you create a place A, assign its parent as another community-curated place B, if the parent place B is deleted, A is also deleted without any warning or notification. 

To replicate:
-Create a place A
-Create a second place B and assign A as its parent place
-Delete A. See that B is also deleted.

Proposal:
1. When a community-curated place is deleted, assign any descendant places to the closest standard place in the place hierarchy.
2. If there is no standard place in the a descendent place's hierarchy, leave the place without any parent.

For 1 above, the [Washington Metropolitan Area](https://www.inaturalist.org/places/washington-metropolitan-area-us) has a place heirarchy like this: 
Places > North America (Continent) > United States (Country) > Mid-Atlantic States (Region) >Washington Metropolitan Area, US
If the [Mid-Atlantic States](https://www.inaturalist.org/places/mid-atlantic) place was deleted, then Washington Metropolitan Area should remain with United States as its new parent place.

**Comment by kueda** [comment]
My fix was a *little* different from your proposal, in that it grafts children to whatever the parent of the deleted place was, regardless of whether or not it was a standard (i.e. admin-level ) place, so in your example, Washington Metropolitan Area would have Mid-Atlantic States as its new parent. Hopefully that's not a problem.

**Comment by carrieseltzer** [comment]
That's fine to have it use the next parent generation place regardless of its status.
