### ISSUE TITLE
second_person_possessive_plural inexistence makes some translations not possible

### ISSUE THREAD

**Issue by vhamon** [inaturalist/inaturalist#2384]
In English, we have : 
second_person_possessive_singular : "**Your** %noun" (i.e. Your favorite)
second_person_possessive_plural : "**Your** %noun" (i.e. Your favorites)

In French (and maybe other languages), we have : 
second_person_possessive_singular : "**Votre** %noun" (i.e. Your favorite)
second_person_possessive_plural : "**Vos** %noun" (i.e. Your favorites)

The problem is that when someone translate "Your" in french, it could have two different translations and currently this creates a big grammar mistake that leads to **very bad user experience**.

cf ./app/views/votes/by_login.html.haml:4:      default: t(:second_person_possessive_singular_, :noun => t(:favorites).downcase))

I guess a fix could be to rename _second_person_possessive_singular__ to _second_person_possessive_plural_ and/or at least fix bad translations since it is very annoying.

**Comment by kueda** [comment]
Just to confirm, the correct title in French would be "Vos Favoris", right?

**Comment by vhamon** [comment]
> Just to confirm, the correct title in French would be "Vos Favoris", right?

Nearly that, it would be "Vos favoris" in this special case I guess.

**Comment by Optilete** [comment]
https://forum.inaturalist.org/t/translation-error-in-projects-overview-page/26186/3
