### ISSUE TITLE
Hitting "Enter" in the taxon chooser on Identify deletes taxon

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2389]
Using Safari 12.1.2. Seems to break https://github.com/inaturalist/inaturalist/issues/2101

Currently if you add an ID in the Identify modal (search for a taxon and then select it) and, while the cursor is still in the search box, you press enter. The chosen taxon disappears and results in:

<img width="279" alt="image" src="https://user-images.githubusercontent.com/15896181/64389486-be69fe80-cff7-11e9-9090-7c7cfa33b5d5.png">

**Comment by pleary** [comment]
I believe this is fixed. Would you mind trying it yourself to confirm?

**Comment by tiwane** [comment]
Yup, looking good. Thanks!
