### ISSUE TITLE
Broken link to Google Maps

### ISSUE THREAD

**Issue by dartar** [inaturalist/inaturalist#2391]
The Google Maps link in the location details of an observation generates searches formatted like the following:

`loc:38.5340805556,-121.5899888889`

This gives no results. Using the plain decimal coordinates without the `loc:` prefix seems to work fine:

`38.5340805556,-121.5899888889`

**Comment by kueda** [comment]
Both seem to work for me. Can you include a screenshot of what you're seeing with the current URL?

**Comment by dartar** [comment]
![3C0E0FAA-4C51-4503-92AB-423D434335FD](https://user-images.githubusercontent.com/209506/65733285-cd861e80-e082-11e9-88fa-00aa12c53e5d.jpeg)
This is a screenshot from a mobile browser on iOS.

**Comment by pleary** [comment]
I made this change, and the Google maps link is properly working on my iPhone now with the Google Maps app
