### ISSUE TITLE
Add an Alive or Dead annotation to Animalia

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2395]
I propose adding an `Alive or Dead` controlled term, affecting only Animalia at the moment (per @bouteloua and @bobby23's suggestion that confused users might flag perennial plants as “dead”). The three values are `Alive`, `Dead`, and `Cannot be determined`. 

I suggest `Alive` be defined as “Organism is living and shows no signs of imminent death.” and `Dead` as “Organism is dead or shows signs of imminent death.” Maybe too ambiguous, but I’ve come across plenty of dying snakes that I wouldn’t want to classify as “Alive”. It would be great if definitions could appear in a pop-up or tooltip.

I've added these to Gorilla, here's a screenshot showing a snake shed. In this case  `Cannot be determined` would be the correct choice.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/15896181/64755188-28464480-d4df-11e9-963e-0e14e70ae1a2.png">

A few ways this data could be used:

- In a taxon page chart; it would be interesting to see how many observations of each taxon are of dead or living individuals.

- Those looking for roadkill, either add an obs field or add them to a project, could search for obs of dead animals, making this easier. Several government agencies, as well as other groups, are into using iNat to track roadkill.

- If someone doesn't want to see dead animals, either because they are bothered by them, or because they are showing off iNat to others and don't want a bunch of dead animals to appear in search results, it would be possible to add a user preference to filter these out by default.

**Comment by tiwane** [comment]
One more thought: I suppose that if we add `Cannot be determined` for Dead/Alive, should it be added to existing annotations?

**Comment by pleary** [comment]
This all sounds good to me. The one thing I'm hesitant about is calling the term `Alive or Dead`. I like to think of the term/value fitting into the sentence `Its {term} is {value}`, e.g. `Its life stage is larvae`, and `Its alive or dead is alive` doesn't work. I think the concept will be clear given the options. Would something like `Vital status` or `Life status` be better?

I'm also OK with adding `Cannot be determined` to all terms
