### ISSUE TITLE
Provide attribution for place polygons

### ISSUE THREAD

**Issue by SK53** [inaturalist/inaturalist#2400]
Numerous external open data datasets, but notably OpenStreetMap, are good sources of place boundaries for projects. I'm thinking of specific 'estates', nature reserves, parks, university sites etc. However many such sources have an attribution requirement: usually a simple statement of copyright and possibly a link to the original source system. 

I'm not so familiar with attributes in KML, but this can be achieved in GeoJOSN. Perhaps more simply would be to ask for this information when someone creates a new place from KML. 

Presumably this would involve extension of the model for places.

**Comment by kueda** [comment]
Not opposed, but, as usual, the difficulty lies not in the model (a `Place` and a `PlaceGeometry` can both already have associated `Source` records), but in the UI. If we start supporting or even encouraging people to add geometries that come with usage requirements, even when those requirements aren't really legally enforceable in most jurisdictions, we would have to display attribution on every map where we display that data, and *that* seems like more trouble than this would be worth.

I'm going to close this b/c it's not ready for implementation. In the future, please make feature requests at https://forum.inaturalist.org/c/feature-requests/16. We try to restrict Github issues for work that is ready for development.
