### ISSUE TITLE
Obs with private/obscured geoprivacy should not show up in place-based subscriptions if they're not publicly indexed in that place

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2423]
After doing some testing, I've found that if I subscribe to a taxon in a place, (and it can be a small place, like [Knowland Park](https://www.inaturalist.org/places/knowland-park-oakland-ca-us)), any observation of that taxon uploaded to that place will show up in my news feed, regardless of the observation's geo privacy (obscured, auto-obscured, private).

Not sure if this is a bug or a feature, but I think if an observation is not publicly indexed as being in that place, it should show up in subscriptions for that place, since it allows other users to access location information which is otherwise not accessible.

**Comment by pleary** [comment]
Could you provide an example obs that created such a notification? It doesn't look possible according to the code, and I couldn't replicate this locally

**Comment by tiwane** [comment]
I can't replicate either. I think I was following my test account, so their obs were showing up in my newsfeed. Sorry about this.
