### ISSUE TITLE
Switch order of List tools

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2425]
Chris Cheatle suggests switching the order of "Re-apply list rules" and "Reload from observations" in the Tools menu, since in [Scott's reload instructions](https://www.inaturalist.org/pages/how_inaturalist_counts_taxa), list rules should be re-applied before one reloads.

![image](https://user-images.githubusercontent.com/15896181/66235008-eeaec680-e6a3-11e9-97e4-75869ffd1197.png)

**Comment by djtrack16** [comment]
hi, im new to this project and looking for issues to tackle, that merge into master appears to fix this. is that the case?
