### ISSUE TITLE
Limit Disable option to add an observation field if observer has opted out

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2431]
From: https://forum.inaturalist.org/t/disable-option-to-add-an-observation-field-if-observer-has-opted-out/7109

It can be irritating to go through the process of adding an obs field to an observation, *then* find out the field can't be added due to the observer's account setting. So if one cannot add a field to an observation, can that section be grayed out? 

 A tooltip explaining why the section is not available has also been suggested.

**Comment by pleary** [comment]
Could I get some guidance as to what the messages should be, and how they are presented? What I've implemented for now is to keep the field input, but disable it, and replace the placeholder text with a descriptive message. My working placeholder text is:
 - "Observer does not allow addition of observation fields"
 - "Observer only allows curators to add observation fields"

This is currently on staging if you want to try it there

**Comment by tiwane** [comment]
I think the presentation is fine, it's readily obvious that obs fields can't be added so no one will waste time doing so. Placeholder text suggestions:

- "Observer does not allow other users to add observation fields"
- "Observer only allows site curators to add observation fields"
