### ISSUE TITLE
In Identify, choosing two annotation filters doesn't work

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2440]
eg https://www.inaturalist.org/observations/identify?taxon_id=56582&term_id=1&term_value_id=2&without_term_id=9 will show observations marked as adult, but many of those observations will already have sex annotations.

Expected behavior: observations with Adult life stage annotations should be shown, but none of them should have any Sex annotation.

**Comment by kueda** [comment]
Mostly for my own reference, https://github.com/inaturalist/iNaturalistAPI/commit/6dd6e95cbb01aa073d5a4e50cc2c7634a31c23fe gets this working for term_id=x&without_term_id=y, but for some reason term_id=x&term_value_id=ywithout_term_id=z still doesn't work.

**Comment by pleary** [comment]
I _think_ this is working for combinations of `term_id`, `term_value_id`, and `without_term_id`. If I set with `Life Stage: Adult`, then I can select without `Alive or Dead` and the count drops and I see obs w/o Alive or Dead annotations.

One bit that's confusing is the `without_term_value_id`. The API documentation says `Must be combined with the term_id parameter`, and the code implements it this way - `without_term_value_id` is only in the context of `term_id`. Meaning you can search for obs with a `Life Stage` but not `Life Stage: Adult`. But, you cannot search for obs with a `Life Stage`, without a `Alive or Dead: Alive` annotation as the Identify UI implies, as `Alive` isn't a value of `Life Stage`.

So I think we should either update the Identify UI or change the behavior of the API to either add some new param(s), or make it so `without_term_value_id` is in the context of `term_id` _unless_ there's a `without_term_value_id` (i.e. `without_term_id` defaults to `term_id` but can be overridden)
