### ISSUE TITLE
Add ORCID support to metadata and user profiles

### ISSUE THREAD

**Issue by dartar** [inaturalist/inaturalist#2444]
ORCID is a unique identifier used by a growing number of platforms to represent the identity of contributors to research code, data, papers, and other research outputs. It is designed as a unique identifier for crediting contributions broadly defined, and iNaturalist falls well within its scope. 

Given that many scholars are contributing to iNaturalist as part of their “service to the profession”, it would be nice to:
1) support an ORCID field in the user profile
2) tag individual observations with their ORCID in the metadata/additional information page. 

ORCIDs are sequences of 16 digits. The canonical URL of an ORCID has the following format: https://orcid.org/0000-0002-0082-8508

**Comment by kueda** [comment]
You can already connect your iNat account to your ORCID account at https://www.inaturalist.org/users/edit, and we include a http://rs.gbif.org/terms/1.0/recordedByOrcid field in our DarwinCore Archives as an interim field until GBIF settles on a a field name for this attribute that they like (see #1857). I'm not exactly sure what you mean by the "metadata/additional information page." Could you provide a link to one such page?

**Comment by dartar** [comment]
> You can already connect your iNat account to your ORCID account at https://www.inaturalist.org/users/edit, and we include a http://rs.gbif.org/terms/1.0/recordedByOrcid field in our DarwinCore Archives as an interim field until GBIF settles on a a field name for this attribute that they like (see #1857). 

Oh that’s fantastic. I didn’t look hard enough!

> I'm not exactly sure what you mean by the "metadata/additional information page." Could you provide a link to one such page?

I was referring to pages with photo metadata like:
https://www.inaturalist.org/photos/54547699

**Comment by dartar** [comment]
I just tried completing the ORCID connection. I understand it’s an additional authentication method, it doesn’t really display the ORCID on one’s public profile. Does it?

**Comment by kueda** [comment]
No, there's no display on the profile. Is that something you want and if so why? Regarding the photo detail page, the intent there is to show information about the photo and not necessarily the photographer. What would be the benefit of showing an ORCID there?

**Comment by qgroom** [comment]
As long as my ORCID is kept with the record then I'm OK with the implementation. 
Ultimately this will allow my whole collecting profile to be put together.

**Comment by dartar** [comment]
> What would be the benefit of showing an ORCID there?
Displaying a link in a profile page or the photo details screen (in the same way as scholarly platforms do, e.g. Zenodo or Figshare) would help bring more awareness among ORCID users that they can tag their contributions in iNat and viceversa academic  iNat users about ORCID. Given that I never change my settings I was not aware of the ORCID integration at all until you pointed it out, and I’m a pretty heavy user of iNat and passionate advocate for ORCID, so I imagine this is invisible for 99% of users. 

I agree with Quentin that as long as the integration happens at the data level, that meets my needs too, although I don’t expect anyone to know about it or for this alone to drive further (mutual) adoption of iNat-ORCID links. 

https://zenodo.org/record/3405489
https://figshare.com/authors/Dario_Taraborelli/678193

**Comment by kueda** [comment]
Ok, so the remaining todo here is

-[ ] Show ORCID on the profile page if it exists, a la https://figshare.com/authors/Dario_Taraborelli/678193
