### ISSUE TITLE
Some code showing at bottom of journal entries

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2452]
eg https://www.inaturalist.org/blog/28281-cayman-islands-inaturalist-world-tour

<img width="788" alt="image" src="https://user-images.githubusercontent.com/15896181/67317977-b4c12b00-f4bf-11e9-9b39-a16c77d38857.png">

**Comment by kueda** [comment]
Should have been fixed in c1dbe2bf44
