### ISSUE TITLE
wrong date/time when uploading a photo taken in a different TZ as browser

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/inaturalist#2459]
![IMG_1349](https://user-images.githubusercontent.com/515947/67792764-ec3b5480-fa36-11e9-92dc-a0c1fb4c6f8a.jpeg)

The attached photo was taken at 5:30pm (Berlin time) in Berlin.
Exiftool reports this photo was taken:
`Date/Time Created               : 2019:09:08 17:28:50+02:00`

When I upload this to iNaturalist using the web uploader, it gets uploaded like this:
https://www.inaturalist.org/observations/35051008
Note that the observed on time is:
`Sep 8, 2019 · 5:28 PM PDT`

The timezone on my account is Pacific Time.

Here is the photo record for this photo, when uploaded to iNat:
https://www.inaturalist.org/photos/55245940
Note that the date/time, date/time original, and date/time digitized all show:
`Date time | 2019-09-08 17:28:49 -0700`

**Comment by kueda** [comment]
FWIW, my solution to this was to just start setting time zones automatically from locations: https://github.com/inaturalist/inaturalist/compare/time-zone-geometries. I [asked](https://forum.inaturalist.org/t/automatic-time-zones/7760) people in the Forum if that was going to cause problems, which may have been a mistake b/c of course someone is going to have problems. I basically lost heart at the time. I suspect some of the issues people have with that solution could be addressed by showing the auto-selected timezone in the Uploader and allowing the user to change the timezone in the Uploader, as well as a batch time-shifting tool, all of which are fairly fussy UI elements that drastically increase the visual complexity of an already-intimidating interface.
