### ISSUE TITLE
Project badge not showing on observation even though observer has joined the project

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2461]
[This observation](https://www.inaturalist.org/observations/34920592) is "in" [this project](https://www.inaturalist.org/projects/mycoflora-of-chicago-ima-member-observations), and the observer has joined the project, but the observation isn't showing a badge for the project.

<img width="410" alt="image" src="https://user-images.githubusercontent.com/15896181/67819030-cb8ff080-fa70-11e9-888b-6ce3340456b3.png">

**Comment by pleary** [comment]
I believe this was related to the creation of a ton of spam projects. When those were cleaned up I believe this was fixed, at least this instance is. Are there other examples? If not maybe we can close this until it comes up again

**Comment by tiwane** [comment]
No, no other examples so I'll close this.
