### ISSUE TITLE
Stale life list statistics in calendar view

### ISSUE THREAD

**Issue by dartar** [inaturalist/inaturalist#2476]
I just noticed the calendar view displays statistics that do not update once an observation’s ID is corrected. For example, [this list](https://www.inaturalist.org/calendar/radrat/2019/11/10) includes an observation of what we first thought was a Common Merganser but later corrected to a Common Goldeneye. The reference to Common Merganser seems to persist in the “life list first” statistics even after it got corrected. There seems to be a lag in propagating the correct ID or maybe the stats are not updated at all after the observations are created.

**Comment by pleary** [comment]
I think this was fixed in January in 8ae0e39. Calendar "Life list firsts" should now be dynamic and not based on the the users "Life list" list. Since this is a pretty old ticket I'm going to close it, but if anyone has examples to show otherwise, please re-open with links and an explanation
