### ISSUE TITLE
Photo browser won't work for taxa with an apostrophe in scientific name

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2478]
Copied from https://forum.inaturalist.org/t/browsing-taxa-photos-with-apostrophe-no-results-found/7958 I was able to replicate.

For the following taxa (a land planarian with an apostrophe in its species name) if you click on the “view more” photos you get “No results found”
https://www.inaturalist.org/taxa/740082
https://www.inaturalist.org/taxa/740082-Fletchamia-m’mahoni/browse_photos

When I replaced the apostrophe with %27 it seemed to work:
https://www.inaturalist.org/taxa/740082-Fletchamia-m'mahoni/browse_photos

**Comment by boucur** [comment]
Same with the little dropdown at the top of taxon pages next to the taxonomy: https://forum.inaturalist.org/t/broken-links-to-taxa-with-punctuation-in-the-name/1704/

**Comment by pleary** [comment]
This should be fixed now
