### ISSUE TITLE
get-observations-project-id has stopped working

### ISSUE THREAD

**Issue by glenpierce** [inaturalist/inaturalist#2483]
Per https://www.inaturalist.org/pages/api+reference#get-observations-project-id one could make a get request to http://www.inaturalist.org/observations/project/[projectName].json to get the observations in a given project, but this no longer seems to work. Is this a bug or has this functionality been deprecated?

**Comment by kueda** [comment]
More like removed than deprecated. I didn't realize we'd actually documented that endpoint, so... I guess I'll consider bringing it back and deprecating it properly, but it is pretty much totally redundant with https://api.inaturalist.org/v1/docs/#!/Observations/get_observations with the `project_id` param, so if you were using `/observations/project/:project_id`, I highly recommend switching to `https://api.inaturalist.org/v1/observations?project_id=:project_id`

**Comment by kueda** [comment]
Ok, this should be fixed and deployed, but again, I highly advise switching to api.inaturalist.org.
