### ISSUE TITLE
Use file name to automatically add an ID when uploading

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2488]
From https://forum.inaturalist.org/t/extract-species-name-from-photo-filename-upon-upload/6510

Some people use scientific names when naming their photo/sound files, eg crotalus_oreganus.jpg, although sometimes they're more complex. Is there any way to parse that file name and search iNat's taxonomy the way we do for keywords? Or do the many possible formats here make it not feasible?

**Comment by kueda** [comment]
We'll see how this goes. I can almost guarantee it will cause trouble for some people. One thing I know it's not going to do is handle hyphenated names like "Rough-skinned Newt." I don't know how to distinguish hyphens in names vs. hyphens as separators, e.g. `IMG_3034032-Rough-skinned NEWT 3494934.jpg`

**Comment by tiwane** [comment]
Is there any sort of ideal formatting we can tell people to use, in case they want to alter their workflow/organizational scheme?

**Comment by kueda** [comment]
As it currently stands, my advice would be
1. Use scientific names
1. Hyphens aren't going to work
1. We can only understand names exactly as they are in the iNat database (regardless of case), so if the name we have is "Wilson's Warbler" and your file name is `IMG_536-wilsons-warbler.jpg` that's not going to work, but `IMG_536-wilson's-warbler.jpg` would.

If we wanted to support hyphens, then we would have to advice people not to use hyphens as separators, so file names would have to look like `IMG_235_golden-crowned_kinglet.jpg` and not `IMG_235-golden-crowned-kinglet - Jan2001 - OMGWTFBBQ.jpg`. I really don't want to do that, though. I mostly just want this not to do much harm, and help a bit where it can, not work perfectly for everyone's weird file naming conventions.

**Comment by tiwane** [comment]
Sounds good to me.
