### ISSUE TITLE
Date/time metadata in some photos not being read in uploader

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2491]
[A user says](https://forum.inaturalist.org/t/metadata-not-being-read-in-standard-uploader/8189) that starting on Nov 22 or so, their photos' date/time are not being read when using /observations/upload. I can replicate with [this photo of theirs](https://www.dropbox.com/s/7ykugk5bw4dv56z/DSC04046.JPG?dl=0).

FWIW, they say this only happens with photos they have cropped.

**Comment by kueda** [comment]
I suspect 8f120dbf48683a56340fb7d25de351321e85bc0f may have fixed this. Can you still replicate it?

**Comment by tiwane** [comment]
No, it's working now.
