### ISSUE TITLE
Add banner to top of /guides noting its deprecated status

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2493]
We have an FAQ stating that Guides is a deprecated feature, but it's likely nobody will see that until they've started working on guides. Can we add a banner to the top of the page saying "Please note that as of January 2019, the Guides feature is presented "as is"; while we don’t have any plans to delete it, we don’t plan to develop it any further." so at least people know that going in?

**Comment by reosarevok** [comment]
Put a PR up for this (sorry, just saw now that I was supposed to notify that before).

**Comment by kueda** [comment]
No worries. I put up that CONTRIBUTING doc this week, and I put that thing about adding a comment first in case people were about to dedicate a lot of time to something we might not merge in. This wasn't one of those situations though.
