### ISSUE TITLE
Auto populate the Alive or Dead annotation from Observation Fields

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2497]
If possible, it might be good to add the Alive or Dead annotation based on some observation fields that do the same thing, like:

https://www.inaturalist.org/observation_fields/92
https://www.inaturalist.org/observation_fields/6541
https://www.inaturalist.org/observation_fields/6977
https://www.inaturalist.org/observation_fields/8046

There's also this roadkill field: https://www.inaturalist.org/observation_fields/160

**Comment by pleary** [comment]
The alive/dead/unkown ones should be easy. Should we just ignore `moribund` (90 instances) and `Injured` (1 instance), or would it be safe to assume those mean `alive`? We also probably can't definitively assign `Roadkill: no` to an annotation.

**Comment by tiwane** [comment]
I say ignore `moribund` and `injured`. And yes, didn't think about `Roadkill: no`, it obviously wouldn't fit, but `Roadkill: yes` should, correct?

**Comment by tiwane** [comment]
Hmm, I hadn't thought about annotating new obs that get these fields added to them, but I think that'd be cool. Do we do this for any other fields? 

One more field to consider for auto population: https://www.inaturalist.org/observation_fields/9111 (only AOR and DOR)

**Comment by pleary** [comment]
For any obs fields that have been converted to annotations, that happens on an ongoing basis when those fields are added. We do this for various life stages, sex, flowering phenology, and now with these fields.

I can add that other field. We need custom code for each field we decide to do this with, so I'm going to assume we now have the definitive list of fields to auto-populate, and could we please have a new ticket for any additional fields?

**Comment by tiwane** [comment]
Yup, that sounds good, I think this'll be helpful.
