### ISSUE TITLE
Bit of code showing in pop-up of Naturalista.mx registration screen

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2502]
https://www.naturalista.mx/signup

![image](https://user-images.githubusercontent.com/15896181/70262365-13c5c100-1749-11ea-9eab-ac205a14abc4.png)

**Comment by kueda** [comment]
Translation issue with invalid html that I missed in my QA. Should figure out a way to incorporate HTML validation into the translation spec.
