### ISSUE TITLE
Adding common name: have the Lexicon menu automatically match user's Locale when available

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2508]
From: https://forum.inaturalist.org/t/when-adding-common-names-set-the-language-the-website-app-is-in/8468

Users who add common names generally add names in their own language, so they've asked that the Lexicon menu be set to their account's Locale by default to save them some clicks and time when adding names.

![image](https://user-images.githubusercontent.com/15896181/70358412-2534c900-182e-11ea-9795-9bb533e2a3b6.png)

**Comment by tiwane** [comment]
Looks good on staging.

**Comment by Optilete** [comment]
Thanks, it does more then only looking good.... ;-)
