### ISSUE TITLE
Links in More Info on taxon page do not sort alphabetically if starting with lower case

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2515]
From: https://forum.inaturalist.org/t/links-in-more-info-on-taxon-page-do-not-sort-alphabetically-if-starting-with-lower-case/8568

eg eFlora is at the bottom of the list here: 

![image](https://user-images.githubusercontent.com/15896181/70753650-1cd70500-1cea-11ea-9e10-9ada2c0127f8.png)

FWIW, I noticed this on the locale chooser in Account Settings when my locale was set to French: 

<img width="303" alt="image" src="https://user-images.githubusercontent.com/15896181/70753797-7808f780-1cea-11ea-89c6-d7767565ee92.png">

**Comment by pleary** [comment]
This should be fixed now
