### ISSUE TITLE
In Lithuanian - common names with diacritic marks on first letter have first two letters capitalized

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2517]
eg https://www.inaturalist.org/taxa/54134-Trametes-versicolor

<img width="455" alt="image" src="https://user-images.githubusercontent.com/15896181/70755855-ddabb280-1cef-11ea-8b13-3cf789ec98a2.png">

https://www.inaturalist.org/taxa/48339-Russula

<img width="311" alt="image" src="https://user-images.githubusercontent.com/15896181/70755886-f0be8280-1cef-11ea-844a-e5249f5d68a3.png">

**Comment by kueda** [comment]
Closed in d1a4fabbbd7fbf74b91108fa32d14dbde713dadf
