### ISSUE TITLE
Access denied for downloading tl_2012_us_state.zip

### ISSUE THREAD

**Issue by reosarevok** [inaturalist/inaturalist#2520]
tools/import_us_states.rb does not work, because the file it attemps to download (http://www2.census.gov/geo/tiger/TIGER2012/STATE/tl_2012_us_state.zip) returns an "Access denied" error.

**Comment by kueda** [comment]
Weird, it works for me. I wonder if the US Census is blocking access from outside the US. If you're trying to follow the Development Setup Guide, you can just ignore that step. It's only there to load some seed data, and is not necessary for a functional development environment. I'll leave this open to remind myself to update or annotate the guide, though.

**Comment by Optilete** [comment]
> I wonder if the US Census is blocking access from outside the US.
If you still wonder, I can download this file from the link above.

**Comment by reosarevok** [comment]
I'm still getting access denied from Estonia. Weird :)

**Comment by Optilete** [comment]
How did you find me...but i have the file and can open it...

Op di 17 dec. 2019 om 23:06 schreef Nicolás Tamargo <
notifications@github.com>:
