### ISSUE TITLE
"view all" link on /flags is sometimes broken

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2523]
If you click on “view all” under a flagger’s username at /flags, the link works. However, if you start using filters and then click “view all,” the link is broken. Eg right now at /flags I see this. If I click on "view all" under atronox, it links to https://www.inaturalist.org/flags?flagger_type=user&flagger_user_id=485272 which works.

<img width="454" alt="image" src="https://user-images.githubusercontent.com/15896181/71055812-d7607080-210b-11ea-8dae-4d9e0fd40526.png">

If I filter to only see flagged photos (https://www.inaturalist.org/flags?utf8=%E2%9C%93&flagger_type=any&flagger_name=&flagger_user_id=&user_name=&user_id=&flaggable_type=Photo&flags%5B%5D=inappropriate&flags%5B%5D=other&reason_query=&resolved=no&resolver_name=&resolver_user_id=&commit=Filter) and click under "atronox" for the same flag, the link goes to https://www.inaturalist.org/users//flags?commit=Filter&flaggable_type=Photo&flagger_name=&flagger_type=user&flagger_user_id=485272&flags%5B%5D=inappropriate&flags%5B%5D=other&reason_query=&resolved=no&resolver_name=&resolver_user_id=&user_name=&utf8=%E2%9C%93 which is broken.

**Comment by pleary** [comment]
This should be fixed now
