### ISSUE TITLE
Flagging a message blocks recipient from viewing it again

### ISSUE THREAD

**Issue by boucur** [inaturalist/inaturalist#2532]
Well, this started with me receiving an actual inappropriate message insinuating I am mentally ill and take pleasure from bird corpses, but uh thankfully that person decided to just delete their account, so I tried some testing with a second account. When I had flagged their message as inappropriate, I tried to go back to it to copy and paste the text, but received a message that said "You don't have permission to do that". (Now that they deleted their account, the message link leads to a 404 page.)

https://www.inaturalist.org/messages/696001/ what zeet sent
https://www.inaturalist.org/messages/696001/flags bouteloua flagged as inappropriate
https://www.inaturalist.org/flags/455512
https://www.inaturalist.org/messages/696001/ now says "You don't have permission to do that" for bouteloua

Expected behavior: I should always be able to view my messages unless I choose to delete them. 

<hr>
Also my first/messier attempt below, looks like flagging as spam also hides it in perpetuity, even though it was marked as not spam:

Sent a message from a test account zeet and the message was auto-flagged as spam:
https://www.inaturalist.org/messages/695965/flags
https://www.inaturalist.org/messages/695965

While logged in as bouteloua I *cannot* see that message even though I flagged it as "not spam". "You don't have permission to do that"

I sent another one from zeet and am not sure why I can't see that while logged in as bouteloua.
https://www.inaturalist.org/messages/695971/flags (none)
https://www.inaturalist.org/messages/695971/

A third:
https://www.inaturalist.org/messages/695988
I can only view the last one in bouteloua's inbox:
![image](https://user-images.githubusercontent.com/4712407/71278510-6db7b080-231d-11ea-9d7f-affff4df7f31.png)

**Comment by kueda** [comment]
I'm sorry you had to deal with such an unpleasant person. My initial assumption was that if you're flagging a message, you no longer want to see it, so it currently deletes your copies of all messages in thread when you flag a message (the flag persist b/c it is associated with the sender's copy). We can certainly make it so flagging doesn't delete anything and the flagger can choose to keep the evidence of the bad behavior they flagged, but that brings up two related questions:

1. What should happen when you delete your own copy of the thread? Currently it deletes all your copies of the messages in the thread, but it does nothing to stop the sender from sending another message in the thread. Should we prevent message delivery if the recipient has flagged the thread the sender is replying to?
1. Should we prevent the sender from deleting their copies of the messages in the thread if any of them have been flagged? Currently, they can delete them and the flag will get deleted too, thus losing evidence of bad behavior. However, preventing the sender from deleting their copies also alerts them to the fact that they've been flagged, which might be bad.

**Comment by boucur** [comment]
1. No, I don't think flagging should directly prevent future message delivery. Maybe there can be some text to direct people to the mute and blocking features if they have flagged a message as inappropriate.

2. IMO flags should stand alone, i.e. content deletion shouldn't also delete associated flags.
https://groups.google.com/d/msg/inaturalist/BFe_XmLq6kY/EyTMPUjOBgAJ
https://forum.inaturalist.org/t/deleting-a-flagged-comment-should-not-delete-the-flags-that-discuss-it/250
This is more important for tracking and discussing inappropriate behavior than other types of flagged content.

**Comment by kueda** [comment]
Pretty sure this was resolved in https://github.com/inaturalist/inaturalist/pull/2563
