### ISSUE TITLE
Switching photos within an observation in Identify Modal resets the Suggestions maps

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2533]
From: https://forum.inaturalist.org/t/switching-photos-within-an-observation-in-identify-modal-resets-the-suggestions-maps/8740

to reproduce:
choose any multi-photo observation using the Identify Modal
go to the Suggestions tab
zoom in or out on any of the species mini maps
in the left side of the modal, select a different photo from the same observation

the result is that the mini map is reset

![image](https://user-images.githubusercontent.com/15896181/71288884-942b1b00-2320-11ea-8c9c-8bd37f484c20.png)

![image](https://user-images.githubusercontent.com/15896181/71288887-99886580-2320-11ea-912c-93f109c631bc.png)

**Comment by pleary** [comment]
should be fixed now
