### ISSUE TITLE
Flickr importer no longer importing GPS data

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2538]
When I try to import a Flickr photo (eg https://flic.kr/p/2i51YsT), iNat imports now everything *but* the location data. 

<img width="903" alt="image" src="https://user-images.githubusercontent.com/15896181/71449737-2e67d600-2708-11ea-8f4f-7e3f1297644e.png">

**Comment by kueda** [comment]
I see coordinates in your screenshot, but I suspect your issue is that the `place_guess` is not getting possible. I think I can fix that.

**Comment by tiwane** [comment]
Ah, can't believe I missed that.
