### ISSUE TITLE
Changes to obs field doesn't (seem to) change update_at for the parent obs

### ISSUE THREAD

**Issue by tomsaleeba** [inaturalist/inaturalist#2550]
Steps:
- create an observation in iNat (for my specific case, it's all via the API)
- add an obs field for that observation (the `/observation_field_values` endpoint)
- the `updated_at` for the obs will (correctly) update, take note of that value
- clobber that existing obs field by POSTing to the `/observation_field_values` endpoint with the same `observation_id` and `observation_field_id` but a different `value`
- check the `updated_at` attribute for the observation again

Expected:
The `updated_at` field has been updated to reflect when we touched the obs field.

Actual:
The `updated_at` field remains unchaged. It's worth noting that photos do *not* suffer this issue and *will* cause the `updated_at` field to be updated.

If implementing this is too much work, perhaps just expose the {created,updated}_at fields for the obs fields (`ofvs`) so clients can compute their own effective updated_at. These values are in the response to the POST/PUT/DELETE call to the obs field endpoint but not in the response for the GET to the observation endpoint, and there's no GET for the obs field values. This workaround sub-optimal but passable.

The use case is: our app keeps a record in it's local datastore that represents the edit operation and we wait to see the updated_at date change as confirmation of success. It works great for photos and changes to the core observation (species_guess, etc), just not for obs fields.

This may be loosely related to https://github.com/inaturalist/inaturalist/issues/2429 in the sense that some changes to an observation aren't reflected in the `updated_at` attribute.

**Comment by kueda** [comment]
I could not replicate this `POST /v1/observation_field_values` or `DELETE /v1/observation_field_values/:id`. Both set the `updated_at` attribute of the observation to the current datetime for me. `PUT /v1/observation_field_values/:id` is currently not designed to touch the observation, but maybe it should. First, though, can you double check that POST and DELETE are really not changing the observation record for you? If that's the case, maybe you could supply some examples with curl?

**Comment by tomsaleeba** [comment]
So it seems that it's only when you POST to clobber an existing value that the date is _not_ changed. When you add a new field or delete a field, the _date is updated_. Sorry for not completely testing :disappointed: . I'll update the original issue.

Let's pick on this obs: https://www.inaturalist.org/observations/36689258 (https://api.inaturalist.org/v1/observations/36689258)

The obs iteself has `updated_at: "2019-12-16T11:33:57+10:30"`.

It has an existing value for the only obs field was `Hill crest`. I just ran this curl to update the obs field value (yes, I'm using POST to clobber the existing value):
```
curl 'https://api.inaturalist.org/v1/observation_field_values' -H 'accept: application/json' -H 'authorization: eygetyourownapitokenLCJvYXV0aF9hcHBsaWNhdGlvbl9pZCI6Mzc1LCJleHAiOjE1Nzg2MTg5MDN9.13d7y-TH3yvGMoqeNkLHzge4C7TE2gFHRdje20AbMNV_Epy8XnKwgXpxNSCgu27DxJItFGh0ICqu9PiD_lV9_Q' -H 'content-type: application/json' --data-binary '{"observation_id":36689258,"observation_field_id":10432,"value":"Plain"}'
```
...and got a successful response:
```javascript
{
  "id": 10614488,
  "observation_id": 36689258,
  "observation_field_id": 10432,
  "value": "Plain",
  "created_at": "2019-12-16T11:33:56.802+10:30",
  "updated_at": "2020-01-09T11:52:03.679+10:30",
  "user_id": 1591469,
  "updater_id": 1591469,
  "uuid": "3c348eeb-7cf5-4bd5-8f3e-1c34b233ce7e",
  "created_at_utc": "2019-12-16T01:03:56.802Z",
  "updated_at_utc": "2020-01-09T01:22:03.679Z"
}
```

Now if we check the obs again, we can see the `updated_at` for the obs has _not_ changed. The obs field value has definitely updated too.

On another obs I have (https://api.inaturalist.org/v1/observations/36689672), I added an obs field (that was not already on the obs) and the `updated_at` _is_ updated. Deleting that field also updated the `updated_at` date.

**Comment by tomsaleeba** [comment]
Thanks :smile:

**Comment by kueda** [comment]
This has been deployed so give it a try.

**Comment by tomsaleeba** [comment]
Just deployed to our dev inat instance and it's working great, thank you :tada:
