### ISSUE TITLE
/taxa/Search bug - taxonomic groups filter not working

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2555]
From https://forum.inaturalist.org/t/species-search-behaviour-issue-bug/9314 I can replicate.

1. Go to https://www.inaturalist.org/taxa/search?utf8=%E2%9C%93&q=Monteiroa You'll see three insects and 5 plants.

![image](https://user-images.githubusercontent.com/15896181/72199335-8f252d00-33ef-11ea-9f91-ba0bca623ec7.png)

2. Click on "Plants" and you'll go to https://www.inaturalist.org/taxa/search?iconic_taxa=47126&q=Monteiroa&utf8=%E2%9C%93

One insect remains in search results, and although it says "5 results" there are actually 6 results. 

<img width="997" alt="image" src="https://user-images.githubusercontent.com/15896181/72199352-b3810980-33ef-11ea-96ac-c7c601a6e1af.png">

**Comment by kueda** [comment]
Pretty sure this was fixed in 09a6063d7b8969d74b0a3a97e2231c8a26d3ab2e
