### ISSUE TITLE
date difference error Inaturalist iphone app

### ISSUE THREAD

**Issue by Ospeleo** [inaturalist/inaturalist#2558]
Hi,

I don't know it is the right place to post, but...

Regular Inaturalist user for the last 5 years, I just downloaded the app for iphone. I use the app in french language.

On the landing page of the app, all my recent observations are sorted from the latest to the newest.

The observation I made yesterday is notified "2 days ago".
The observation I made 20 days ago (in december, while we're in january) is notified "one year ago"

**Comment by Ospeleo** [comment]
![Image PNG](https://user-images.githubusercontent.com/12714994/72649165-eb85d080-394a-11ea-8f86-7ec7cd2d5a47.png)

**Comment by kueda** [comment]
Please post a bug report in the Forum: https://forum.inaturalist.org/c/bug-reports/13. When you do so, it might also help to include the URL of one of those observations and a screenshot of what that observation looks like in the app on the observation detail view (i.e. when you tap on that observation). I'm guessing something got messed up with the translations.

FWIW, this github repo is for the iNaturalist web application, not the iPhone app. However, we'd prefer that most bug reports go through the Forum.
