### ISSUE TITLE
Observation fields added during upload are not being saved to observations

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2567]
From https://forum.inaturalist.org/t/observation-field-entries-rejected-during-obs-upload/9554 Supposedly it started about 6 days ago or so.

1. Start a new observation at `observations/upload`.
2. Add an observation field to it, eg Count.
3. Submit observation.
4. Observation has no observation field. 

This also happens if you use tags to make observation fields, eg `Roadkill=yes` and it's supposedly happening on mobile, but I haven't tested that yet.

**Comment by tiwane** [comment]
Can't replicate in iOS.

**Comment by kueda** [comment]
Closed in 9ad195a7ea70c5041832319a72aa1e377c471fe1
