### ISSUE TITLE
Explore adding annotations

### ISSUE THREAD

**Issue by tomsaleeba** [inaturalist/inaturalist#2577]
We're exploring how to support multi-valued questions in our app (that is a client to iNat) and have come up with all the options you'd expect for obs fields. Then we noticed that annotations already have this support built in and they get other benefits like the histogram charts and community voting. So we'd like to use annotations over obs fields where possible.

We'd like to explore two things:
 1. adding some extra values to Plant Phenology, and
 1. adding 3 new annotations, see below

We understand that adding new annotations [requires](https://github.com/inaturalist/inaturalist/issues/2326#issuecomment-555240008) [more](https://github.com/inaturalist/inaturalist/commit/05e41f74abe5989325c2a01d3022a0938e8e4d18#diff-e8cfedd2b8d925c721a0e470ec87e83dR31) than just entering them into the /controlled_terms web UI but felt we needed to ask the question.

We can see that including annotations in an export ([here](https://github.com/inaturalist/inaturalist/issues/1425), [here](https://github.com/inaturalist/inaturalist/issues/2471)) and allowing filtering by annotations ([here](https://github.com/inaturalist/inaturalist/issues/1427), [here](https://github.com/inaturalist/inaturalist/issues/1513)) are both on your radar, which is good news.

Here's a rough comparison of ours vs yours for plant phenology values. Some discussion about how our terms map, or don't, to your _fruiting_ might be required.

| Ours | Yours |
|------|-------|
| Vegetative |       |
| Budding | Flower budding |
| Flowering | Flowering |
| Senescent flower |  |
| Developing fruit | |
| Senescent fruit | |
|  | Fruiting |

We can see there's been a [change](https://github.com/inaturalist/inaturalist/issues/2326) to budding. This aligns with our term as our _vegetative_ covers leaf budding; and everything that is not reproductive.

Proposed new annotations:

Landuse of the immediate area
- Conservation and natural environments
- Production from relatively natural environments
- Production from dryland agriculture and plantations
- Production from irrigated agriculture plantations
- Intensive uses
- Water

Surface coarse fragments present
- Fine gravel or small pebbles <6 mm
- Medium gravel to medium pebbles 6 - 20 mm
- Coarse gravel to large pebbles 20 - 60 mm
- Cobbles 60 - 200 mm
- Stones 200 - 600 mm
- Boulders 600 - 2000 mm
- Large boulders >2000 mm

Evidence of disturbance and threats in the immediate area
- Chemical spray
- Cultivation (incl. pasture/ag activities)
- Dieback
- Fire
- Firewood/coarse woody debris removal
- Grazing - feral (observed or scats) (i.e. rabbits, feral/escaped goats)
- Grazing - native (observed or scats) (i.e. roo/possum scats)
- Grazing - stock (observed or scats) (i.e. cattle, sheep, goat)
- Mowing/slashing
- Rubbish dumping (excluding small litter items)
- Storm damage
- Soil erosion (incl. run-off)
- Trampling (human)
- Vegetation clearance
- Weed invasion
- Other human disturbance

We're dealing with Orchids but expect that these annotations would apply to at least plants but perhaps more of the taxa tree.

**Comment by kueda** [comment]
This is more of a product question than a technical one, so please address this at https://forum.inaturalist.org/. That said, keep in mind that annotations are explicitly *not* specific to individual projects or efforts. They are meant to be universal across the site. If your project / client has specific needs, it would be better to stick with observation fields, or to store whatever additional data you need within your own app.
