### ISSUE TITLE
Additional identify filters: by location obscurity, location accuracy and observation license

### ISSUE THREAD

**Issue by andrewharvey** [inaturalist/inaturalist#2584]
On the Identify page, there are some Filters, I'd like to suggest filters for:

- obscured location - any/yes/no
- location accuracy - < Xm
- observation licensing

I want to help out with identifications, but I'm not going to volunteer my time to contribute identifications where the observation is not open licensed (I'd like to filter out, all right reserved, potentially also the non-commercial observations).

Same goes for obscured locations, these are less useful for me as a data consumer, so I'd like to be able to focus on helping with identifications that are more useful when the have a location and that location is < 100m in accuracy. To do this I want to filter these out.

compared to the current options:
![Screenshot from 2020-02-15 22-48-16](https://user-images.githubusercontent.com/117278/74587333-47746f80-5045-11ea-8027-e872812fb5c4.png)

**Comment by kueda** [comment]
Thanks for the ideas, Andrew, but we'd prefer that feature requests like this go through the [Forum](https://forum.inaturalist.org/). For more guidelines for contributing via Github, please see https://github.com/inaturalist/inaturalist/blob/master/CONTRIBUTING.md

**Comment by andrewharvey** [comment]
Sorry my bad. I normally only read the CONTRIBUTING guide if I'm going to submit a PR.

If you're finding you're still getting a lot of feature requests as issues, if there was an ISSUES_TEMPLATE with a note about using the forum I would have noticed that.
