### ISSUE TITLE
CC-BY-NC photo shows up in taxon photo search for CC0 photos

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2592]
From: https://forum.inaturalist.org/t/copyrighted-images-with-wrong-licenses-showing-up-in-searches-filtered-by-cc-license/10251 

Go this URL, which searches for CC0 RG images of this taxon: https://www.inaturalist.org/taxa/49883-Betula-papyrifera/browse_photos?order_by=created_at&photo_license=cc0

This photo turns up, and it's CC-BY-NC: https://www.inaturalist.org/photos/30899473

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/15896181/75079435-88450c00-54bd-11ea-9add-b136a4ddccaf.png">

**Comment by kueda** [comment]
I didn't see that photo at that URL, but I did find a bug that might have caused it. Do you have any other examples of this happening?

**Comment by tiwane** [comment]
No.
