### ISSUE TITLE
Apostrophe not displaying correctly on browser tab for observation detail and taxon flag pages

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2600]
**Describe the bug**
For taxa with common names that include an apostrophe (or maybe a foot mark?), this mark shows up as `&#39;s` in the browser tab title.

**To Reproduce**
1. Go to https://www.inaturalist.org/observations/39249734 or https://www.inaturalist.org/taxa/144496/flags and make sure your locale is set to English
2. Check out the tab title.

**Expected behavior**
I would expect to see the proper punctuation mark appearing, as it does on the taxon page, eg https://www.inaturalist.org/taxa/144496-Gallinago-delicata

**Screenshots**

<img width="246" alt="image" src="https://user-images.githubusercontent.com/15896181/75481535-1145c280-5958-11ea-8646-d6eb515e5158.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox, Chrome, Safari
 - Version Current versions

**Additional context**

**Comment by tiwane** [comment]
This is still happening, eg https://www.inaturalist.org/taxa/144496-Gallinago-delicata

<img width="245" alt="image" src="https://user-images.githubusercontent.com/15896181/156056219-ea4a8d02-d5a3-4998-b7e3-e89a203bfe88.png">

(from https://forum.inaturalist.org/t/scrambled-apostrophes-in-page-titles/30022/2)

**Comment by rainhead** [comment]
This appears to have been fixed.
