### ISSUE TITLE
Invalid comments just disappear

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2612]
[//]: # (For feature requests, please use https://forum.inaturalist.org/c/feature-requests/16)

**Describe the bug**
Posting a comment on obs detail that is invalid removes all the text that you wrote, so you lose all your work

**To Reproduce**
1. Go to an observation detail page
1. Leave a comment that is more than 5000 characters
1. You'll get a validation error and then your comment will disappear

**Expected behavior**
I would expect my work not to be lost so I can edit it until it becomes valid

IMO, minimum fix would be
- [ ] If a comment or ident is invalid on submission, leave the UI alone so the user can fix the problem
- [ ] Don't allow text areas to have more text than is allowed

Ideally:
- [ ] Have some UI-alert about validation issues like length when they happen, before submission. I'm not sure if a character count is necessary for comments, but maybe a notice or tip should appear when you exceed the limit.

**Comment by kueda** [comment]
FYI, this got rolled into Markdown support. Since tony requested that we wait for the apps to support Markdown before we start enabling / encouraging it on the web, this is currently pending completion of https://github.com/inaturalist/INaturalistIOS/issues/553 (pretty much supported in Android, just pending some QA / QC: https://github.com/inaturalist/iNaturalistAndroid/issues/809)

**Comment by tiwane** [comment]
Can this be added to other comments, such as those on journal posts and flags?

**Comment by kueda** [comment]
What I did was add the hard cap on number of characters for the text area in the non-React identification editor, post editor, and comment field, but no additional warning UI.
