### ISSUE TITLE
Prevent creation of observations with more than 20 photos in the Uploader

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2623]
In the Uploader, make it so a photo or a card will not drop on a card that already has >= 20 photos.  In a perfect world, we would show some kind of error or popup that says, "Observations can only have 20 photos. To add more you will need to remove some" when the user tries to do this, but I'm not sure we can dispatch actions in response checking droppability.

**Comment by todtb** [comment]
I'll take a look at this.

We also want to prevent "combining" cards (ex: "Select All" > "Combine") into a stack with over 20 photos too, right? Is that the same as dragging a card on top of another?
