### ISSUE TITLE
bug with facebook inviter

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#263]
http://www.inaturalist.org/photos/inviter at a Facebook photo generated this link
http://www.inaturalist.org/facebook/invite?facebook_photo_id=10202752195058659
with a failwhale in the displayed icon
![screen shot 2014-05-21 at 6 42 23 pm](https://cloud.githubusercontent.com/assets/598026/3048939/6371422a-e152-11e3-968d-0bda899df894.png)
and the link didn't properly populate the photo in the add obs form
Prob not a top priority, but just thought I'd report it...

**Comment by kueda** [comment]
I don't think we've had a Facebook inviter for a long time.
