### ISSUE TITLE
Can't follow or unfollow a user on obs detail page

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2633]
1. Go to an observation by a user you don't follow.
2. Flick on "Follow" and select "Follow [username]"
3. Briefly see a spinner, but "Unfollow" doesn't appear next to the username to indicate you are now following them, and if you go to their profile you are not following them.

If you try to unfollow a user, the "Unfollow" link disappears briefly then reappears. Their profile page indicates you are still following them.

**Comment by kueda** [comment]
Should have been fixed in https://github.com/inaturalist/iNaturalistAPI/commit/8f921c7630d8c4d3dac4f456a372b3a744b70639
