### ISSUE TITLE
Places: show which collection projects are using a place, in addition to any traditional project

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2637]
From: https://forum.inaturalist.org/t/place-used-in-project-but-projects-tab-missing-on-the-place/11347

Currently, if a traditional project is using a place, we add a `Projects` tab on a place's page and list any projects using the place. A curator, then, will, know why they can't delete a place.

However, if it's only collection projects which are using the place, we don't add a `Projects` tab to the place page, eg [this project](https://www.inaturalist.org/projects/terra-ceia-bioblitz-2019) is using [this place](https://www.inaturalist.org/places/terra-ceia-preserve-state-park) but there's no indication of this relationship on the project's page:

<img width="573" alt="image" src="https://user-images.githubusercontent.com/15896181/78944208-39096980-7a72-11ea-8852-29de0e76ea57.png">

Is it possible to list collection projects which use a place on that place's page?

**Comment by cmcheatle** [comment]
'know why they can't delete a project.' should be cant delete a place.

**Comment by tiwane** [comment]
Thanks, fixed!
