### ISSUE TITLE
Identify - clicking page number button only brings you back to top of page

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2642]
From https://forum.inaturalist.org/t/page-navigation-isnt-working-in-identify/11466 I can replicate.

1. Go to `/identify`
2. Click on any of page numbers at the bottom of the page.
3. Browser goes back to top of page, no new observations load.

Console in FF:
<img width="1649" alt="image" src="https://user-images.githubusercontent.com/15896181/79188470-e9a99d00-7dd3-11ea-885a-013e6aea20a9.png">

**Comment by kueda** [comment]
Thanks, minor typo at https://github.com/inaturalist/inaturalist/commit/02e832d3ad5dfbc13eb0b5e763cd3f7e18229427#diff-1e115b3e17e85bc55b1fb8b664468097R3
