### ISSUE TITLE
Batch Edit - Common names from different locales are displayed

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2645]
1. Batch edit a bunch of your observations. 
2. On the batch edit page, some common names are not shown in your locale/place of choice, eg for me:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/15896181/79297315-a2ceac80-7e92-11ea-9324-e7d08b69ae89.png">

**Comment by kueda** [comment]
Can't replicate. Please include as much detail as possible including what user you're signed in as, what the locale and names place preferences are, etc.

**Comment by tiwane** [comment]
Signed in as myself, locale = English, names place = United States.
