### ISSUE TITLE
On Collection Projects main pages: display posted-on dates for journals

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2649]
Some collection project admins like to write multiple journal entries, save them as drafts, then post them at appropriate times. When the journal posts are show on the collection project's page, the original save date for the post is shown, not the posted-on date, eg:

![image](https://user-images.githubusercontent.com/15896181/79415739-fad4e400-7f62-11ea-881d-09f59acb1cb6.png)

So the posts are ordered correctly, but the dates are misleading. Can we display the posted on date rather than the saved on date?

**Comment by pleary** [comment]
This should have been fixed in 49dcda8
