### ISSUE TITLE
Use Weblate

### ISSUE THREAD

**Issue by comradekingu** [inaturalist/inaturalist#2667]
Would it be possible to use Weblate instead of Crowdin?
I would like to contribute to this without being tracked and profiled. My native language is nb_NO, and the translation for it is not good atm.

https://hosted.weblate.org/projects/ghini/ is already on Hosted Weblate :)

**Comment by kueda** [comment]
Webplate looks cool, but we're very happy with Crowdin and have no desire to use another platform at this time.
