### ISSUE TITLE
Use F-Droid

### ISSUE THREAD

**Issue by comradekingu** [inaturalist/inaturalist#2668]
Hello, hoping to see this on F-Droid, as downloading it from the Play store means accepting the tracking that it entails.

**Comment by Optilete** [comment]
Maybe this gives an answer. https://forum.inaturalist.org/t/support-android-build-with-only-libre-open-source-software-dependencies/2163 
Asking the question means answering it....

**Comment by comradekingu** [comment]
@Optilete Don't have to commit to anything. https://f-droid.org/en/docs/Inclusion_How-To/  Most projects are included as a result of being added to https://gitlab.com/fdroid/rfp/-/issues
I support OSM too, and full disclosure am part of OSM-NO. :)

**Comment by kueda** [comment]
This repo is for the iNaturalist web application. Downloading it from F-Droid to your phone would not be very satisfying. There was already an issue opened and closed on this topic in our Android app repo: https://github.com/inaturalist/iNaturalistAndroid/issues/654. To summarize: while I would like to remove our dependency on Google services from our Android app, it's not a high priority so we're not going to distribute in F-Droid any time soon.
