### ISSUE TITLE
Only allow project users to be made project managers

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2670]
In collection project lingo, only allow project members to be made project admins. Currently some unpleasant shenanigans are possible. Pretty sure this requires a change to

- [x] `Project#add_admins`
- [x] The admin autocomplete on the projects form so it only shows project members, not any user
- [x] Project form UI text to make it clear you can only make people admins after they have joined the project

**Comment by todtb** [comment]
I can take this on.

**Comment by todtb** [comment]
PR is up as a draft until the API endpoint is merged here: https://github.com/inaturalist/iNaturalistAPI/pull/195
