### ISSUE TITLE
Collection projects that have a date requirement in the future lack a flag link

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2673]
From https://forum.inaturalist.org/t/unable-to-flag-unstarted-bioblitz-project-as-spam/7217

Some spammers have created projects which can't be easily flagged due to this.

1. Create a collection project with an observed-on date that is in the future, which has a date range where the starting date is in the future.
2. There is no option to flag the project at the bottom of the project's page.
3. Change the date to something in the past.
4. Flag link appears.

**Comment by todtb** [comment]
I'll take a look at this. I just got this set up locally and this should be a pretty quick fix.

**Comment by kueda** [comment]
Holler if you run into any blockers. This will require some React work.
