### ISSUE TITLE
Allow Filtering Of Tags Or Multiple Observation IDs In Get /observations

### ISSUE THREAD

**Issue by tzinckgraf** [inaturalist/inaturalist#2679]
I have an application that is using the iNaturalist API. I am using iNaturalist to validate species identifications, which means syncing with the iNaturalist observations.
I am using the GET /observations endpoint to do a bulk search, but I only want to grab the observations I have not validated. Right now I have to grab all observations (in this case, by user id).
There are two options I can think of for this:
- Add a tag list parameter on the GET /observations endpoint
- Add an observation id's parameter on the GET /observations endpoint

As another request, I was hoping to be able to specify columns in the GET request to reduce the data. Not sure if we want that to be a separate issue.

Let me know the thoughts on this. I would be happy to work on it.

**Comment by kueda** [comment]
Hey, sorry I missed this. You can retrieve data about a handful of specific observations like this:

https://api.inaturalist.org/v1/observations/47374864,47354620,46572489

or like this:

https://api.inaturalist.org/v1/observations?id=47374864,47354620,46572489

You might also be interested in the `updated_since` param, e.g. https://api.inaturalist.org/v1/observations?id=47374864,47354620,46572489&updated_since=2020-05-28

There some more guidance at https://www.inaturalist.org/pages/api+recommended+practices

In general, I don't think we're interested in novel development on Rails-based API responses.

Regarding reducing response sizes (which are, admittedly and to our own detriment, enormous), that's something we're working on in v2 of the API, which will require clients to specify what fields they want in the response.

Also, can you provide a link to your application? We'd love to check it out.

**Comment by tzinckgraf** [comment]
Hey, thanks for the reply. I will read through the API recommended practices. That looks like exactly what I needed.

You can see our app at https://opentreemap.sustainablejc.org/. We have used the open source OpenTreeMap code and made some modifications to connect to iNaturalist.
