### ISSUE TITLE
Explore map view: mousing over observation makes pop-up block pin.

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2681]
1. Go to https://www.inaturalist.org/observations?place_id=152628 and make sure you're in map view.
2. Mouseover one of the observations on the side.
3. Correct pop-up appears, but its point is on the bottom of the pin. ![image](https://user-images.githubusercontent.com/15896181/82968218-a53c2000-9f81-11ea-9ea5-5eb798591443.png)

Clicking on the pin (which is always just above the pop-up described above) produces a "correctly" placed pop-up, which doesn't cover the pin.
<img width="490" alt="image" src="https://user-images.githubusercontent.com/15896181/82968248-b71dc300-9f81-11ea-925f-def1ddfc40a2.png">

**Comment by pleary** [comment]
I deployed some changes for explore. Any better now?

**Comment by pleary** [comment]
I think this is fixed so I'll close it, but please reopen with examples if you're still seeing the problem
