### ISSUE TITLE
Calendar display is off in Chrome when zoomed to 110%

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2682]
From: https://forum.inaturalist.org/t/calendar-broke/12843

Doesn't happen in Firefox at all, or in Chrome at other realistic zoom levels.

<img width="829" alt="image" src="https://user-images.githubusercontent.com/15896181/83073319-197bcf80-a025-11ea-957d-26b1fd6e1f2c.png">

**Comment by pleary** [comment]
works for me now on staging
