### ISSUE TITLE
Obs not showing it is in collection project even though it appears in search results

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2692]
**Describe the bug**
Per @tiwane, some obs are not getting collection projects to show up on obs detail, e.g
> [this obs](https://www.inaturalist.org/observations/46658598) and [this project](https://www.inaturalist.org/projects/caterpillars-of-eastern-north-america). The observer is a member of the project. 

https://www.inaturalist.org/observations/46658598 does not show that it's in that project, but it does show up at https://www.inaturalist.org/observations?place_id=any&project_id=caterpillars-of-eastern-north-america&subview=grid&user_id=zdufran&verifiable=any. I tried to look into it a bit but had trouble getting useful log data on staging.

**To Reproduce**
Not sure how it got in this state.

**Expected behavior**
The observation show display that it is in the project.

**Screenshots**

![Screen Shot 2020-06-03 at 5 45 33 PM](https://user-images.githubusercontent.com/22691/83702618-0ab39080-a5c2-11ea-994e-403faf98ac4d.png)

**Context**
 - OS: Mac OS 10.15.4
 - Browser Brave
 - Version 1.9.76

**Additional context**

**Comment by tiwane** [comment]
This just came in tonight.

After [this observation](https://www.inaturalist.org/observations/48287471) was annotated, it lost the [UC Cal Nat project](https://www.inaturalist.org/projects/uc-california-naturalist-program-certified-naturalists) badge. Still turns up in [searches](https://www.inaturalist.org/observations?place_id=any&project_id=uc-california-naturalist-program-certified-naturalists&subview=grid&taxon_id=50086&user_id=scubabruin&verifiable=any) for the project’s obs.

**Comment by tiwane** [comment]
I can consistently get the Sci Fri project badge to disappear when I add a`Life Stage` annotation, then reappear when I remove that annotation.

**Comment by tiwane** [comment]
I believe this is fixed now, so I'll close. Please reopen if need be.
