### ISSUE TITLE
Increase max image size (from 2048 pixels wide)

### ISSUE THREAD

**Issue by kaldari** [inaturalist/inaturalist#2696]
While importing images from iNaturalist to Wikimedia Commons (via [iNaturalist2Commons](https://commons.wikimedia.org/wiki/User:Kaldari/iNaturalist2Commons)), I noticed that most of the images have been downsampled to 2048 pixels wide (as the "original" size). While I'm sure that iNaturalist doesn't want to store hundreds of thousands of 20 megapixel photos, 2048 is pretty small, and it's ashamed that we're losing the original higher resolution versions, especially when they are freely licensed and could be used elsewhere. Even a modest increase to 3000 or 2500 would make a significant difference when reusing images in print, for example.

**Comment by kaldari** [comment]
If bandwidth usage by scrapers is the main concern (rather than storage), perhaps you could make the full res image only available via the API.

**Comment by boucur** [comment]
I think they generally want people to use the forum rather than Github to submit new feature requests/functionality changes:

> If, on the other hand, you want to request features, report bugs you've found while using this software, or discuss anything else about iNaturalist, please start by posting in the Forum. We mostly use Github for managing implementation, not for discussing what to implement or why we might want to implement it.

from the [Contributing guide](https://github.com/inaturalist/inaturalist/blob/master/CONTRIBUTING.md).

**Comment by kaldari** [comment]
I'll submit there instead.
