### ISSUE TITLE
Public location accuracy of observations of previously-obscured taxon do not get updated

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2703]
From: https://forum.inaturalist.org/t/changing-taxon-geoprivacy-from-obscured-to-open-does-not-update-observation-gps-accuracy-to-not-recorded/2970/7

(Best to do this on staging, for obvious reasons)

1. Make an observation that will be automatically obscured due to taxon geoprivacy.
2. Public location accuracy will show the obscuration cell's location accuracy:

<img width="490" alt="image" src="https://user-images.githubusercontent.com/15896181/84853917-22a10080-b015-11ea-8202-8640f299ab47.png">

3. Remove taxon geoprivacy obscuration for that taxon.
4. Your observation will still show the old observation cell location accuracy, even though it is no longer obscured.
5. Forcing a reindex of the observation clears the error.

**Comment by kueda** [comment]
I can no longer replicate this so I think I fixed it.
