### ISSUE TITLE
Using placeholder in obs edit screen adds HTML text

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2710]
From https://forum.inaturalist.org/t/html-in-id-placeholder/13589

1. Edit an observation on the website.
2. Type in a species and choose it as a placeholder:
![image](https://user-images.githubusercontent.com/15896181/85793469-e98a1f80-b6e9-11ea-8e4b-bace30c1630b.png)
3. Form contains HTML text
<img width="277" alt="image" src="https://user-images.githubusercontent.com/15896181/85793555-09b9de80-b6ea-11ea-9cba-df84fa369ce9.png">
4. Save the observation and it now shows the HTML.
<img width="434" alt="Screen Shot 2020-06-25 at 1 45 19 PM" src="https://user-images.githubusercontent.com/15896181/85793772-5a313c00-b6ea-11ea-84c6-34ffb1bf8ee5.png">

**Comment by todtb** [comment]
I'll take a look at this.
