### ISSUE TITLE
Support keyboard shortcuts in the TextEditor

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2722]
Specifically

- [x] `CMD-b` should be the same as clicking the "bold" button
- [x] `CMD-i` should be the same as clicking the "italic" button
- [x] `CMD-k` should be the same as clicking the "link" button (pilfered from Github, but so useful)

Using the `CTRL` versions should work in Windows, and it looks like [mousetrap](https://www.npmjs.com/package/mousetrap) supports a `mod` helper to do that, or we can just use `"ctrl-b", "cmd-b"`.

**Comment by todtb** [comment]
I'll work on this in tandem (as separate branches, of course) so I can better understand and make sure the work done on #2723 lines up with the other upcoming improvements.
