### ISSUE TITLE
Use the TextEditor in Identify

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2723]
Use the [`TextEditor`](https://github.com/inaturalist/inaturalist/blob/master/app/webpack/shared/components/text_editor.jsx) For comments and IDs like we do on obs detail.

**Comment by todtb** [comment]
I can take a look at this if you didn't already have a plan of action @kueda. Do you think it makes more sense to get this in "Identify" first or approach #2721, #2722, and #2724 first?

**Comment by kueda** [comment]
They all kind of complicate each other equally, so if you want to take a crack at this, go for it. Much obliged.
