### ISSUE TITLE
Inline editing of comments and ID bodies using the TextEditor

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2724]
Currently to edit these things the ActivityItems loads an old Rails edit form in a new window/tab. Performing this action inline would be an improvement, IMO, and allow us to use the TextEditor for editing in addition to creating.

- [ ] When you click "Edit" in the ActivityItem menu, replace the UserText with a form that includes a TextEditor populated with the `body` of the comment or ID. `href` should remain the same, but the click event should show the form and stop propagation.
- [ ] Editing form should have "Save" and "Cancel" buttons
- [ ] If we're making it so you can't get to the edit identification form we need to support identification deletion in the context menu. We don't *really* want people to do that, though, so that should be at the bottom, in gray, and maybe fire an "Are you sure?" confirm dialog

**Comment by todtb** [comment]
I can take a look at this next if you weren't already planning to. When you say stop propagation, you mean in react (`stopPropagation( )`) to prevent the click event from doing anything else, right? I'm not very familiar with it, but if it's just a matter of calling it, I can throw that in before showing the TextEditor.

**Comment by kueda** [comment]
Go for it. I was just recommending that the "Edit" menu item continue to be a link identifications/edit or comments/edit but that if all the JS is working normally, it should open the inline editor instead of opening the link.
