### ISSUE TITLE
Annotate observations with obs field "Teneral: Yes" to the Life Stage: Tenereal annotation

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2729]
About 2k observations have been marked with as "Teneral: Yes" with this observation field: https://www.inaturalist.org/observation_fields/9982 Nearly all are cicadas, and I just allowed `Life Stage=tenereal` to be used for cicadas, so can we retroactively map fields with these values to the proper annotation.

Side note: `Life Stage=teneral` only works with odonata and cicadas as of now, but some obs with these fields are of other taxa (eg diptera).

**Comment by pleary** [comment]
seems to be working on staging. After we deploy I'll look at porting over existing field values
