### ISSUE TITLE
Not all page contents load when using back/forward buttons in Safari

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2731]
Seem unique to Safari In this case I'm using version 13.1.1 (15609.2.9.1.2)

1. Go to Your Observations.
2. Click on an observation.
3. Click back in the brwoser to go to Your Observations.
4. Click forward again. Observation page loads header and footer, actual observation content doesn't load.

Console shot:
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/15896181/87252796-d0dc7200-c42a-11ea-96fa-70b6879f1339.png">

Also happens if you're on obs show to another page (eg click on username), then click back.

**Comment by pleary** [comment]
fixed on staging if you'd like to test

**Comment by tiwane** [comment]
Looking good to me.
