### ISSUE TITLE
Add ToS, PP, and CG consent to sign up

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2745]
Add an unchecked, required checkbox to the signup form with the text, "I agree to the [Terms of Service](https://www.inaturalist.org/terms) and [Privacy Policy](https://www.inaturalist.org/privacy), and I have reviewed the [Community Guidelines](https://www.inaturalist.org/pages/community+guidelines)." This should behave like the GDPR consent check in that you have to check it to enable the "Create an Account" button.

Also, add "(recommended)" to the end of the text describing the licensing consent.

**Comment by todtb** [comment]
I can add this in.
