### ISSUE TITLE
Honor taxon page place filter when clicking on the badge of a similar species result

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2749]
From: https://forum.inaturalist.org/t/similar-species-badge-link-doesnt-honor-place-id/14881

If one uses a place filter on a taxon page, eg Canada, and one goes to the the Similar Species tab, one sees:

![image](https://user-images.githubusercontent.com/15896181/88601864-67fa1a00-d026-11ea-9a75-498467039f1d.png)

However, clicking on the badge of a similar species takes you to Explore but with the param `place_id=any`. It would be best if we used the place ID of the current place filter for the taxon page.

**Comment by jwidness** [comment]
I don't have a dev environment to double-check, but I imagine it's just adding an if-else block around badgeText.

    if ( place ) {
        badgeText={(
            <a href={`/observations?ident_taxon_id_exclusive=${result.taxon.id},${taxon.id}&place_id=${place.id}&verifiable=any`}>
                { result.count }
            </a>
        )}
    } else {
        badgeText={(
            <a href={`/observations?ident_taxon_id_exclusive=${result.taxon.id},${taxon.id}&place_id=any&verifiable=any`}>
                { result.count }
            </a>
        )} 
    }

**Comment by tiwane** [comment]
This looks to be working for me. @jwidness?

**Comment by tiwane** [comment]
Whoops, nevermind, looks like it's closed on the forum. Closing here.
