### ISSUE TITLE
Remove "or email" from search field at https://www.inaturalist.org/people

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2753]
We don't actually search users' email addresses (which is a good thing, IMO) so that text should be removed. 

![image](https://user-images.githubusercontent.com/15896181/88978495-af75e580-d274-11ea-8aa3-d4d132c4573f.png)

**Comment by JoseChavez98** [comment]
Hi! I'll love to collaborate on the issue. Can you assign me?

**Comment by kueda** [comment]
@JoseChavez98 go for it. This would should be pretty straightforward. Since I'm not sure you've committed any code to iNat before, check out https://github.com/inaturalist/inaturalist/blob/master/CONTRIBUTING.md.
