### ISSUE TITLE
When duplicating an existing observation, don't include observation fields

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2754]
From: https://forum.inaturalist.org/t/when-duplicating-an-observation-sometimes-the-observation-fields-get-copied-over-and-other-times-do-not/14748

Observation fields are often specific to the organism in question, so if an observation is duplicated and the fields are carried over to the new observation, the fields are likely inaccurate. So they shouldn't be included when an existing observation is duplicated.

**Comment by todtb** [comment]
I can take a look at this.
