### ISSUE TITLE
Merging observation fields broken

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#276]
To reproduce:
1) http://www.inaturalist.org/observation_fields/701/edit and click Merge
2) Search for/select 'Dead or Alive' and click 
3) merge unsuccessful, redirects to http://www.inaturalist.org/observation_fields/701 with flash 'You must choose an observation field'

**Comment by kueda** [comment]
Is this still happening? If not can you close it?

**Comment by loarie** [comment]
I guess so, I'm not getting that error any more. But I can't fully test because I can't find obs fields not used in projects to merge....
