### ISSUE TITLE
Collection and Umbrella Projects: Rename "View All" button or make it view all. 

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2760]
On collection and umbrella projects, the "View All" button here...

![image](https://user-images.githubusercontent.com/15896181/89611677-a36cc380-d832-11ea-99ea-037b4913b0b1.png)

...refers to "Recent Observations", and if you click on it it shows "all" recent observations - a few hundred. However, it's so far from the "Recent Observations" text that most people (including myself) think it will take you to all observations in the project. There are two [feature](https://forum.inaturalist.org/t/associate-the-button-view-all-on-collection-project-overview-pages-directly-to-search-all-observations-in-it/12878) [requests](https://forum.inaturalist.org/t/display-all-observations-on-project-pages/4951) predicated on this interpretation.

I think we should either make the button's function more clear, or change it's function to match its name. A few options I'm thinking of:

1. Change the name to "View More". A bonus would be to add a "View All" button at the bottom of all the recent observations that takes you to obs search that shows all observations. 

2. Keep the name "View All" and show the current relative grid view, but add pagination and arrows to the bottom so one can actually look through all observations in the project in this view.

**Comment by kueda** [comment]
Which do you prefer? I think my preference would be a third option: link "View All" to obs search where you really can view them all.

**Comment by tiwane** [comment]
I'm fine with your suggestion, but I _do_ like the idea of a viewing all the observations in the relative grid view. But if it's it's more taxing, then it's not necessary.

**Comment by tiwane** [comment]
Might be worth putting a "View All" button at the bottom of `tab=observations` as well, some people have expected to see all observations on that tab because it has the total number on the tab.

**Comment by abhasinat** [comment]
I like @kueda's solution of having the "View All" button link to obs search for the project. I think the "Search" button on the observations tab takes them to obs search as well.
