### ISSUE TITLE
About section for ungrafted taxa shows whale shark 

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2770]
From https://forum.inaturalist.org/t/fail-whale-for-taxon-page-about-tab/15230

eg https://www.inaturalist.org/taxa/1114396-Schistura-crocotula (currently ungrafted)

![image](https://user-images.githubusercontent.com/15896181/89859300-877c6100-db55-11ea-92f3-023fe312d5ae.png)

**Comment by kueda** [comment]
Fixed in 771edce9fcac0a3ac5b0c13a1965ec626817e49d
