### ISSUE TITLE
Make sorting by date columns on Edit Observations screen "sticky"

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2773]
From https://forum.inaturalist.org/t/change-default-sort-order-of-your-observations-to-date-observed-instead-of-date-added/7803

It's fairly easy, some users would like the option to make the Date Observed and Date Added sorting columns on the Edit Observations screen "sticky", like how the number of obs displayed per page is, rather than it defaulting to date added (descending).

**Comment by kueda** [comment]
Are you referring to pages like https://www.inaturalist.org/observations/kueda? And can you define "sticky"? Should it be permanent, or can it only last as long as you are logged in?

**Comment by tiwane** [comment]
> Are you referring to pages like https://www.inaturalist.org/observations/kueda?

Yes.

> And can you define "sticky"? Should it be permanent, or can it only last as long as you are logged in?

I was thinking it would be analogous to the observations per page option, if possible, so it would last even after you log out. But, this is a pretty niche use case, so as long as you are logged in would work, IMO.

**Comment by todtb** [comment]
#2837 has a potential fix. How does this look for UI?

![Screen Shot 2020-10-18 at 11 11 00 AM](https://user-images.githubusercontent.com/19367605/96371978-9f162e00-1132-11eb-8303-24c01de166cc.png)

Clicking the column header (or otherwise passing ordering parameters) will override user default.

**Comment by kueda** [comment]
IMO, this doesn't require additional UI. I think it would suffice if the existing ways of specifying `order` and `order_by` were saved as preferences. What do you think @tiwane?

**Comment by tiwane** [comment]
Yeah, I don't think new UI is needed here. But that looks nice. :-)
