### ISSUE TITLE
Update network page link in web & email footer

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#2776]
Now that we have a translatable page, we should remove links to https://www.inaturalist.org/pages/network and replace them with https://www.inaturalist.org/sites/network so that people can see a translated version of the page.

The places where this needs to happen are:

- [x] website footer ([here](https://github.com/inaturalist/inaturalist/blob/main/app/helpers/application_helper.rb)?)

- [x] email footer ([here](https://github.com/inaturalist/inaturalist/blob/main/app/views/emailer/_footer.html.erb)?)

- [x] maybe this page for contributors ([here](https://github.com/inaturalist/inaturalist/blob/main/README.textile))

- [x] account settings page

Am I missing any links that aren't wiki pages?

**Comment by todtb** [comment]
@carrieseltzer The only other spot I'm seeing immediately is the user edit page ("Edit Your Account & Profile") underneath the "iNaturalist Network Affiliation" section. I can pick this up and double check.

**Comment by carrieseltzer** [comment]
Awesome, thanks! I added the account settings to the list above.

**Comment by Optilete** [comment]
In https://www.inaturalist.org/stats you missed the hyperlink wit title ''Observations By App''
Website
Created via iNaturalist or **iNaturalist Network websites**
