### ISSUE TITLE
Tooltips show [missing %{name} value] for Order Araneae and Family Ichneumonidae

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2784]
From https://forum.inaturalist.org/t/missing-name-value/15566

Mouseover Spiders and Ichneumonid Wasps on https://www.inaturalist.org/observations/56936240 and https://www.inaturalist.org/observations/56922216 and you'll see

![image](https://user-images.githubusercontent.com/15896181/90696716-a358c480-e231-11ea-995d-9916320a590d.png)

**Comment by RainbowKaito** [comment]
It's happening in apparently every taxon that's not a species or subspecies. Cassidini, Lepidoptera, _Charidotella_, Braconidae, _Oxalis_, _Ionoxalis_ (section), _Oxalis_ (subgenus)_, and so on. _Sterna trudeaui_ and _Viola tricolor_ spp. _tricolor_ don't have any problem, for example.
I use iNat in Brazilian Portuguese.

**Comment by RainbowKaito** [comment]
Just checked in the Crowdin platform the translation for Brazilian Portuguese and there's an untranslated string "%{rank} %{name}" that was added yesterday. The context text is "When a scientific name is displayed with its rank, e.g. Family Noctuidae or
Genus Noctua (but generally not Species Noctua pronuba)".
