### ISSUE TITLE
Explore scroll / search_after ES pagination to improve DwC-A performance

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2789]
We generate a very large DarwinCore Archive (DwC-A) for GBIF once a week using [`DarwinCore::Archive`](https://github.com/inaturalist/inaturalist/blob/main/lib/darwin_core/archive.rb), but at this point it's taking almost a week to generate, so that's about to become a problem. Patrick thinks we might speed it up by using [`search_after`](https://www.elastic.co/guide/en/elasticsearch/reference/7.8/paginate-search-results.html#search-after) or [`scroll`](https://www.elastic.co/guide/en/elasticsearch/reference/7.8/paginate-search-results.html#scroll-search-results) pagination in elasticsearch. This is probably hard to benchmark without production data, but might be doable with a bunch of synthesized data.

**Comment by pleary** [comment]
I looked into search_after and the scroll API, and neither seemed like they'd have a huge effect if just dropped into the method. Seems like the biggest problem for ES is sorting millions of records to return a result set, and for whatever `scroll` didn't impact that much. We might address that if we ever rebuild the indices by setting a default sort order - e.g. https://www.elastic.co/guide/en/elasticsearch/reference/master/index-modules-index-sorting.html

I tried to improve things in 4e3a98a by searching in smaller batches setting a min AND max ID, so each batch has to sort fewer records. This might make things up to 70% faster - we'll see after the next export

**Comment by pleary** [comment]
I did some work recently to allow the DwC-A script to use the Parallel gem with a configurable number of parallel workers. Between that and some other [recent performance improvements](https://github.com/inaturalist/inaturalist/commits/main/lib/darwin_core/archive.rb) it's taking about 26 hours to generate in production. In theory that could be sped up more if we ran it on a machine with more resources and used more Parallel workers
