### ISSUE TITLE
Too many signficant digits for latitude and longitude

### ISSUE THREAD

**Issue by kaldari** [inaturalist/inaturalist#28]
Right now when you pick an observation location from the map it fills in the latitude and longitude values to 10 decimal places. This is the equivalent of specifying a location to 1/100th of a millimeter. Since you can't actually zoom in that close in the map, and no camera's GPS system is anywhere near that accurate, it would be better to truncate the coordinates to a more reasonable number of decimal places, like 5 or 6. Five decimal places is the equivalent of specifying the location to the exact meter.

**Comment by kueda** [comment]
Whether or not this is absurd, these are the numbers reported by the devices we use to measure location (phone's positioning system, Google Maps). They may be unrealistically precise, but there's no way for us to know how unrealistically precise.
