### ISSUE TITLE
Inactive taxa get featured at https://www.inaturalist.org/taxa

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2801]
From https://forum.inaturalist.org/t/inactive-taxa-shouldnt-be-featured-on-taxa/16023

We should probably only feature active taxa here. 

eg ![image](https://user-images.githubusercontent.com/15896181/92312919-723efa80-ef7a-11ea-9a07-2ff96211ea62.png)

**Comment by kueda** [comment]
This is manually controlled, so if you want to unfeature it, edit the taxon and uncheck the box.

**Comment by jwidness** [comment]
I looked at the time and the box wasn't checked.

![image](https://user-images.githubusercontent.com/13769652/92313130-fbaff600-ef95-11ea-80d0-e7a44e09ff97.png)

See also Cassi's [comment in the forum](https://forum.inaturalist.org/t/what-is-the-featured-option-for-when-creating-a-new-taxon/15771)
