### ISSUE TITLE
For ":Allow observation fields from" user pref - don't let other users edit one's observation fields

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2812]
From: https://forum.inaturalist.org/t/disallow-others-to-edit-your-observation-fields-opt-in/13917/

Currently, one can choose to allow only site curators or oneself to add observation fields to one's observations:

![image](https://user-images.githubusercontent.com/15896181/93945633-2c10c780-fcec-11ea-960e-7aa7a7b553ca.png)

There's been a request to expand that preference to not allow other users to *edit* the observation fields on one's own observations. So something like "Allow Adding and Editing Observation Fields from".

**Comment by kueda** [comment]
If other people can edit but not add, that seems like a bug to me. What if we just made it so this existing pref applied to edits in addition to new fields?

**Comment by tiwane** [comment]
fine with me
