### ISSUE TITLE
Links to a user's observations should show all of their observations

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2815]
From https://forum.inaturalist.org/t/users-observations-link-missing-verifiable-any-and-place-any/16648

We recently changed links to a user's observations on various parts of the site (profile page, sub-heading navigator, user curation page, etc). They used to link to the edit observations page and now link to Explore. However, on Explore it only shows the user's verifiable observations. I know I usually want to see someone's entire set of observations because a) i'm often determining how many casual observations they have, and others on the forum have agreed. Also, it's a bit odd and possibly confusing to see that someone has 27,300 observations (eg on their profile), click on that link, then see that number turn to 26,187.

Therefore I think those links include the `verifiable=any` and `place=any`(if the latter is necessary?) so that we show someone's entire set of observations.

**Comment by todtb** [comment]
I can update these links. 

Quick question though @tiwane, do you think this (`verifiable=any` and `place=any`) should just be the default result set for observations? We could just change the behavior so no additional parameters in the url are needed. If not, and we only want to update a few links, which specific links should this apply to?

Thanks!

**Comment by tiwane** [comment]
Oh man, sorry for the late reply! 

These links: https://www.inaturalist.org/people/28 and https://www.inaturalist.org/admin/users/28

<img width="418" alt="image" src="https://user-images.githubusercontent.com/15896181/99121482-4ad76000-25b1-11eb-96c8-3ebd0292ac3e.png">

And this one, at https://www.inaturalist.org/home

<img width="384" alt="image" src="https://user-images.githubusercontent.com/15896181/99121568-79553b00-25b1-11eb-8914-bd2bc6fd0678.png">

**Comment by todtb** [comment]
No worries @tiwane, should be all set!

**Comment by tiwane** [comment]
Thanks @todtb!

**Comment by boucur** [comment]
Just noticed another one, header search View observaitons for users should also have place=any&verfiable=any:

![image](https://user-images.githubusercontent.com/4712407/103432103-d461e200-4b9f-11eb-9c19-9a390510f9e7.png)
https://www.inaturalist.org/observations?user_id=zeet

should be https://www.inaturalist.org/observations?user_id=zeet&place_id=any&verifiable=any

**Comment by todtb** [comment]
@boucur, @tiwane, 

Here's a PR to make the change in the universal autocomplete. https://github.com/inaturalist/inaturalist/pull/2906
