### ISSUE TITLE
On the People I Folow page, only count journal posts the user has posted to their own journal

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2817]
From: https://forum.inaturalist.org/t/my-list-of-people-i-follow-shows-journal-entries-but-when-i-click-on-view-journal-no-entries-appear-for-that-person/16314/6

Currently, on the page which displays the users I'm following (https://www.inaturalist.org/people/tiwane/following), we show how many journal entries a user has posted, eg

![image](https://user-images.githubusercontent.com/15896181/94732551-4285d700-031b-11eb-93be-2bda23627f11.png)

However, that number shows how many journal entries they've posted anywhere on iNat, like project journals or the iNat blog. For example, abhasm is listed as having 1 journal post (it was to the iNat blog), but if you click on it, you go to [his journal page](https://www.inaturalist.org/journal/abhasm) and there are no entries. This is confusing, so I think we should only count the number of posts the user has made on their personal account's journal.

**Comment by todtb** [comment]
Updated in #2836. Also updates similar count on "followers".
