### ISSUE TITLE
Journal count on profile page doesn't go down when journal entries are deleted

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2818]
From: https://forum.inaturalist.org/t/my-list-of-people-i-follow-shows-journal-entries-but-when-i-click-on-view-journal-no-entries-appear-for-that-person/16314/6

For example, @bouteloua's test account zeet had three journal posts, but two were deleted weeks ago. However, the profile page for zeet still shows 3 journal entries: https://www.inaturalist.org/people/zeet

**Comment by todtb** [comment]
I'll take a look.
