### ISSUE TITLE
Comment body / ID remark no longer persisting when switching tabs on obs detail

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2820]
**Describe the bug**
On the obs detail page, we used to ensure the text of the textarea for the comment form and the identification form would stay the same when switching between the forms (i.e. clicking on the different tabs), but that doesn't seem to be working any more.

**To Reproduce**
1. Go to any observation detail page
1. Enter some text in the comment form
1. Click on the "Suggest an Identification" tab

**Expected behavior**
The identification textarea will be blank, when it should have the text from the comment form

**Context**
 - OS: Mac OS 10.15.6
 - Browser: Brave 1.14.84

**Comment by todtb** [comment]
I can give this a go. I'm going to try converting from jQuery DOM manipulation to state based, with a ref on the parent `Activity` component to find and update the child `TextEditor`
