### ISSUE TITLE
Not capturing creator_id for names imported from external sources

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#2832]
When a scientific name is added from an external source such as EOL or COL, we are not storing the `user_id` of the account that imported the name in the `creator_id` field. We _are_ storing that information when a taxon is newly created from scratch.

**Expected behavior**
When someone adds a taxon from EOL or COL, I should be able to find their user id in the `creator_id` field of the taxon name associated with the taxon json. 

**Links**
_Paragalago cocos_ is an example of a taxon that was created from scratch and the valid scientific name contains a `creator_id` of `425992`.
[Taxon edit page](https://www.inaturalist.org/taxa/1127568/edit), [.json](https://www.inaturalist.org/taxa/1127568.json)

_Sylvicapra grimmia hindei_ is a taxon created by importing from EOL. The `creator_id` is `null`, even though it was also created by `425992`. 
[Taxon edit page](https://www.inaturalist.org/taxa/1122386/edit), [.json](https://www.inaturalist.org/taxa/1122386.json)

**Additional context**
Capturing this information will allow savvy curators to identify and reach out to people who may be overzealously importing many unresolved or extinct taxa.

**Comment by cmcheatle** [comment]
Is there any reason why uploads using the external searches of extinct taxa simply can't be blocked ?

CoL appears to list relatively few extinct taxa, EoL has a clearly defined field in the dataset marking extinction.

Another 20 extinct taxa added today that need to be fixed....

**Comment by jwidness** [comment]
Thanks for doing this, I'm finding it very helpful.
However, I think there was an unintended side-effect -- the edit taxon page now no longer says that the taxon was imported from an external name provider and more importantly, the source URL isn't available.

Previously:

![image](https://user-images.githubusercontent.com/13769652/101269622-c5257b00-373e-11eb-840d-c34011d0528b.png)


Now:

![image](https://user-images.githubusercontent.com/13769652/101269629-da9aa500-373e-11eb-97aa-8d5ab2fffb12.png)
