### ISSUE TITLE
Pinned Locations Displaying Oddly

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2838]
from: https://forum.inaturalist.org/t/pinned-places-are-shown-incorrectly/17378 I can replicate.

eg 

![image](https://user-images.githubusercontent.com/15896181/96375559-8f94e600-112e-11eb-8a65-08713fc3a1dd.png)

**Comment by kueda** [comment]
Pretty sure this is a combo of trying to use more accessible `<button>` elements with the Uploader not supporting the full suite of our custom Bootstrap styles like `.btn-nostyle`.
