### ISSUE TITLE
Facebook photo albums are no longer accessible

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2855]
1. Link your iNat account to your Facebook account.
2. Go to https://www.inaturalist.org/observations/import#photo_import and select Facebook as your source, if it's not already selected.
3. Your albums cannot be accessed.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/15896181/98032042-40a2ae00-1dc8-11eb-80ac-78dbd014c511.png">

**Comment by tiwane** [comment]
@kueda facebook albums will just not be accessible from now on, correct?

**Comment by kueda** [comment]
Yeah, I think everyone on the team is down with https://github.com/inaturalist/inaturalist/issues/2862, so this ones now kind of redundant.
