### ISSUE TITLE
Date Added: Months Filter not working in Identify

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2863]
From: https://forum.inaturalist.org/t/date-added-months-filter-not-working/17962 I can replicate.

Step 1:
Go to https://www.inaturalist.org/observations/identify

Step 2:
Click “Filters”

Step 3:
Click “More Filters”

Step 4:
Click “Months” under “Date Added”

Step 5:
Select “April”
(Note that it does not matter which month)
You will see that the url is now: https://www.inaturalist.org/observations/identify?created_month=4&createdDateType=month

Expected: Seeing observations that were uploaded in April (of any year)
Actual: Seeing observations that were uploaded most recently

**Comment by tiwane** [comment]
Has this been deployed? Not seeing it working in production.

**Comment by markapgar** [comment]
I have not seen this in prod either.

**Comment by kueda** [comment]
Closed prematurely I guess. Do you still want to work on this, @pleary?
