### ISSUE TITLE
In taxonomy tab, only use verifiable observations for counts.

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2864]
From: https://forum.inaturalist.org/t/casual-observations-used-inconsistently-on-taxon-page/17963

In the Taxonomy tab of a taxon page (eg https://www.inaturalist.org/taxa/51648-Clintonia), the numbers here include casual grade observations:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/15896181/98742917-115de500-2364-11eb-997d-e64b31fa04d2.png">

Other numbers on the page only count verifiable observations, so we should use only verifiable observations here as well.

**Comment by kueda** [comment]
I suspect the only reason I included those counts was b/c it was easy to include the total counts, as they're cached with the taxa in the index. Showing any other count will require fetching that data, which will either require one API request per count or a new API endpoint that will accept arbitrary taxon IDs and return counts.

**Comment by kueda** [comment]
Discussed with @pleary and @tiwane and we think that to do this we'd either have to make separate API requests for each child taxon we want to show a verifiable obs count for, or make an endpoint that accepts a list of arbitrary taxa and shows counts for them given obs search params, which Patrick thought would be a serious performance hit if we allowed a genuinely arbitrary list that could include 500 taxa or a lot of big taxa like all the descendants of Life. We don't really think this is worth that performance cost, so we could remove these counts to make all counts on the page consistent, but Tony thinks that would be even more disruptive than leaving it as it is, so we're going to do that.
