### ISSUE TITLE
Suggestions filters should persist when changing observation modal tabs

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2867]
The observation modal (detail view on Identify, Compare tool on obs detail) has a "Suggestions" tab that shows suggested taxa for identifications, and allows you to filter those suggestions in a few ways. However, if you view the suggestions, change a filter, navigate to another tab like Annotations, then navigate back to Suggestions, your filters will be reset to the defaults. The people demand that they not do that. The filters *should* still reset when navigating between observations, and I don't think they need to persist when you close the modal.

**Comment by todtb** [comment]
Looks like the "Sort By" and "Source" filters are working as expected, but not the "Taxon" and "Place" filters. I can start looking into why/how to fix. I would think it might also make sense not to fire the query each time the tab is changed, but rather when the tab is first selected and subsequently when changing filters.

**Comment by kueda** [comment]
> I would think it might also make sense not to fire the query each time the tab is changed, but rather when the tab is first selected and subsequently when changing filters.

Sounds good. Also need to fire it after changing observation, of course.
