### ISSUE TITLE
New Lifelists: On right pane in Species view, have the number and label change when Show value changes

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2870]
Currently in new lifelists, if the user chooses Species view, we show the number of leaves by default (red circle). But if the user changes the "Show" menu to another taxonomic level, eg Family (red arrow) the number and label don't change to reflect the new Show value:

![image](https://user-images.githubusercontent.com/15896181/99730397-37286f80-2a71-11eb-82c0-c4002a58312f.png)

Can we make the number and label reflect the taxonomic level chosen for Show?

**Comment by todtb** [comment]
I can take a look at this.

**Comment by todtb** [comment]
PR #2873 is open for a quick workaround. Also while working on this it took a little bit to set up some realistic taxonomic hierarchies. The readme has some info on importing some seed taxa, but do you have any tooling that you're using for creating realistic relational data @kueda or @pleary? For example a species with all its ancestral clades/ranks? If not, I can put together something that would build out a development seed set of species with associated Class, Order, Family, Genera, etc., but I figured I'd check first.

**Comment by kueda** [comment]
Hey @todtb sorry for the late reply. I don't have any tooling like that. I usually rely on [`Taxon.import`](https://github.com/inaturalist/inaturalist/blob/main/app/models/taxon.rb#L1695), which will attempt to import a taxon by name and all its ancestors from external taxonomy providers, so you could set up a basic taxonomy with `Taxon.import("Vulpes vulpes"); Taxon.import("Quercus agrifolia"); Taxon.import("Amanita muscaria")`. However, maybe it would be more useful for development purposes to have a script like `tools/import-inat-taxon.rb` that accepts a name and imports a branch of the taxonomy from iNat itself.

**Comment by pleary** [comment]
Fixed in #2873. Thanks again @todtb!
