### ISSUE TITLE
Created on date param not being applied from URL

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2874]
From https://forum.inaturalist.org/t/observations-page-date-filter-in-url-should-be-enabled-by-default/18308

1. Create a URL with a created on end date but no begin date, eg https://www.inaturalist.org/observations?created_d2=2019-09-29&place_id=any&taxon_id=134205

2. Paste it into the browser and load it.

3. The date param is not being applied, and that shows in the UI:

<img width="319" alt="image" src="https://user-images.githubusercontent.com/15896181/100678912-273b4600-3323-11eb-8fb9-dfe95b9f77c5.png">

Selecting the radio button will apply the filter. Pasting a URL with a begin and end date doesn't result in this issue, nor does using a begin date only.

**Comment by kueda** [comment]
This seems to be working now. Please re-open if it's not, @tiwane.
