### ISSUE TITLE
Photo browser annotation filters show wrong value when no annotated obs

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2879]
**Describe the bug**
The taxon photo browser annotation filters incorrectly display "Any" when set to value not represented in observations of the taxon in question.

**To Reproduce**
1. Go to the photo browser for a taxon with observations that have the Life Stage: Larva annotation, e.g. https://www.inaturalist.org/taxa/48663-Danaus/browse_photos, and set filters to the defaults, except set Life Stage to Larva. Here are the full filters:
  * Grouping: Non
  * Life Stage: Larva
  * Sex: Any
  * Alive or Dead: Any
  * Order By: Faves
  * Photo Licensning: Any
  * Quality Grade: Research
1. Go to the photo browser for a taxon with observations that **do not** have the Life Stage: Larva annotation, e.g. https://www.inaturalist.org/taxa/1080209-Cimbex-rubidus/browse_photos
1. The Life Stage filter is set to Any, even though it should be set to Larva, and no photos are shown

**Expected behavior**
When the Life Stage filter is set to Larva, the filter should still display as "Any" even when the taxon has no observations with that annotation.

**Additional context**
Reported by several people in the Forum and by [Tony in Slack](https://inaturalist.slack.com/archives/C02F8RN5Q/p1607274033036600). Related to work on https://github.com/inaturalist/inaturalist/issues/2816

**Comment by tiwane** [comment]
There are also issues when going between taxa that don't share the same annotation, let alone value. eg

1. Go to https://www.inaturalist.org/taxa/47125-Angiospermae/browse_photos and choose `Flowering` for `Plant Phenology`

![image](https://user-images.githubusercontent.com/15896181/101531799-924ed300-3948-11eb-80aa-90385616c269.png)

2. Go to the [photo browser for Kingdom Fungi](https://www.inaturalist.org/taxa/47170-Fungi/browse_photos) and you'll see this: 

<img width="801" alt="image" src="https://user-images.githubusercontent.com/15896181/101532012-ca561600-3948-11eb-94c5-d82c3aff7254.png">

There's no way to change the `Plant Phenology` filter here so you won't see any photos. I would expect that an irrelevant annotation would not affect the photo browser, or for there to be a "reset filters" option.

**Comment by synrg** [comment]
Will it take some time to roll this out on the site now, or is it not really fixed? I tried Bibio photo browser, set Larva filter, then went to Fungi photo browser and it says "No observations yet" still.
