### ISSUE TITLE
Link from GBIF dataset metadata should correctly filter observations

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#2885]
Belatedly making an issue after an internal conversation related to the text we display associated with our [GBIF dataset](https://www.gbif.org/dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7). The issue: clicking the link that is supposed to display only the observations included in the GBIF export instead includes all research-grade observations because the `created_d2` and `license` parameters aren't working as passed.

As identified by @kueda, three things are needed to make the link work as expected:
1) we need Explore and the API to support `created_d2` alone (without a `created_d1`) in a url with or without a full ISO 8601 datetime
2) Explore needs to support the `license param` (not just the API)
3) update the GBIF DwC-A metadata so the URL uses lowercase license codes instead of uppercase. 

For 1), if I use the filters to set a `created_d2` date, it filters appropriately. But if I take the link that generates, and paste it into a new tab, it doesn't filter by `created_d2`. Here's an example of my RG observations created before Jan 1, 2016: https://www.inaturalist.org/observations?created_d2=2016-01-01&place_id=any&quality_grade=research&subview=grid&user_id=carrieseltzer (it should display 570, but instead displays all 6,824). Clicking into filters shows 2016-01-01 already in the "date added" range, and selecting the "range" radiobutton then brings the right results.

**Comment by jwidness** [comment]
#2874 is also related to point 1.

**Comment by carrieseltzer** [comment]
Since #2874 is closed, only these two items remain to properly filter the observations from the GBIF dataset metadata:

- [ ] Explore needs to support the license param (not just the API)

- [ ] update the GBIF DwC-A metadata so the URL uses lowercase license codes instead of uppercase.

**Comment by jwidness** [comment]
`license` seems to have some unexpected case-sensitivity.  If you choose from the Photo Licensing drop-down in Explore's More Filters, the URL populates with a capitalized photo license, e.g. https://www.inaturalist.org/observations?photo_license=CC0&place_id=any.  However, it will also accept lowercase, e.g. https://www.inaturalist.org/observations?photo_license=cc0&place_id=any.  The behavior for `license` is not like `photo_license` -- it will only accept the lowercase version, e.g. https://www.inaturalist.org/observations?license=cc0&place_id=any.

**Comment by kueda** [comment]
As far as I can tell the URL is now working, as is the link to Carrie's RG observations created before Jan 1, 2016.
