### ISSUE TITLE
iNat website does not stop user from removing required observation field from observation

### ISSUE THREAD

**Issue by tomsaleeba** [inaturalist/inaturalist#2888]
**Describe the bug**
When you have an observation that is in a project with a required obs field condition, the iNat website does *not* stop a user from editing that observation and removing that required observation field. Alternatively, doing this edit does not eject the, now invalid, observation from the project. I know obs fields and traditional projects are kind of deprecated, but wanted to have the bug known.

**To Reproduce**
1. create (or find) a (traditional) project with at least one required observation field
1. create an observation, with that required observation field
1. add the observation to the project
1. edit the observation using the iNat website (`https://<inat host>/observations/3780/edit`) and remove the required observation field

**Expected behavior**
The system must not let the required obs field be removed as it's a condition of being in the project.

**Actual behaviour**
There is no error, the obs field is removed, and the obs is left in the project.

**Context**
 - inaturalist commit c56c350083174fd1434947c8c637e9922944a0a0

**Comment by kueda** [comment]
I'll try and limit this kind of thing by adding some validation to the ObservationFieldValuesController and removing the "Remove" links on the obs edit form, but making this absolutely impossible would require us to change the way v1 of the API is working, i.e. that it accepts nested attributes for obs field values on update and that those nested values can include a `_destroy` attribute to remove them, which might break our own mobile apps, so I think I'm going to hold off on going that far.

**Comment by kueda** [comment]
@tomsaleeba can you still reproduce this with the steps you listed above?

**Comment by tomsaleeba** [comment]
@kueda I cannot reproduce. That's usually a bad thing when I say that but in this case it's good, it means this issue is fixed.

Thanks :+1:
