### ISSUE TITLE
remove private_positional_accuracy

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#2891]
We currently have a `private_positional_accuracy` attribute on observations which is always `nil` and not used anywhere except in the observation exports (via the observations/export and the legacy traditional project exporter)

We also have `positional_accuracy` and `public_positional_accuracy` which we are using. For unobscured obs 
`positional_accuracy` = `public_positional_accuracy`
for obscured obs a coarser value is added to `positional_accuracy`

to remove `private_positional_accuracy`, we need to remove it from the DB and make it so that the exporters include
`public_positional_accuracy` as a default column and `positional_accuracy` as a "protected" column to be included in exports that include non-public information such as "private_latitude", "private_place_guess" etc.

Optional improvement to make API responses more elegant
remove `positional_accuracy` from public API responses (this info isn't sensitive like private_latitude, but isn't really needed in the absense of these non-public attributes)

Optional improvement for consistency with other non-public location data
rename `positional_accuracy` to be `private_positional_accuracy`
rename `public_positional_accuracy` to be `positional_accuracy`

**Comment by kueda** [comment]
It's not entirely clear to me that the positional accuracy *does* need to be protected, and I suspect the only reason we added these extra positional accuracy columns was not to protect the true value but to provide a measure of the uncertainty applied to the `latitude` and `longitude` columns that incorporates `positional_accuracy` *and* obscuration. If lat and lon are the obscured values, then their uncertainty is `max(radius_of_the_obscuration_cell, positional_accuracy)`.

So I guess I'm in favor of removing `private_positional_accuracy` but not any of the other stuff. If the real problem here is that `public_positional_accuracy` is a confusing name, maybe it needs a new name (`coordinate_uncertainty`?), but I think that would be a very small gain for the disruption it would cause to anyone using that column.

FWIW, @carrieseltzer and @pleary may also have opinions here.

**Comment by loarie** [comment]
To clarify, you want to add `public_positional_accuracy` to the exports (alongside the existing `positional_accuracy`) and include it in all exports, even those that don't include non-public geographic information?

Thats fine with me as long as we clarify in documentation that in both the API and exports `public_positional_accuracy` = `positional_accuracy` for unobscured obs and that for obscured obs `positional_accuracy` refers to the accuracy around the private coords which may not be visible and `public_positional_accuracy` refers to the accuracy associated with the public coords

**Comment by kueda** [comment]
`positional_accuracy` is not, to my knowledge, private, and I don't think it needs to be, so I'm not in favor of an attribute named `private_positional_accuracy` if that information is not, in fact, private. If I'm not understanding this, can you explain the risk posed by exposing `positional_accuracy` for obscured obs?

**Comment by loarie** [comment]
I agree there's no risk of making sensitive information available. 

But there is a risk of confusion for users interpreting API responses and exports that include the 'private package' (e.g. private_latitude, private_longitude, private_place_guess) [use case 1] and to a lesser extent users interpreting API responses and exports that do not include the 'private package' [use case 2]. Specifically

use case 1:
Fred downloads an export that includes the cols that includes non-public data he has access to. As a result he sees
`latitude`, `longitude`, `place_guess`, `private_latitude`, `private_longitude`, `private_place_guess`, `positional_accuracy`, and `public_positional_accuracy` columns. While `private_latitude`, `private_longitude`, `private_place_guess` are all blank in some rows both `positional_accuracy`, and `public_positional_accuracy` have values in each row (sometimes they are the same and sometimes they are different). Giving the inconsistent naming convention and the fact duplicated (rather than blank) accuracy values, its not clear to Fred that `positional_accuracy` corresponds to the uncertainty associated with the `private_latitude` and `private_longitude fields` and that `public_positional_accuracy` corresponds the uncertainty associated with the `latitude` and `longitude` fields

use case 2: 
Jane doesn't have an iNat account. She looks at an API response that has fields for `latitude`, `longitude`, `place_guess`, `positional_accuracy`, and `public_positional_accuracy`. `positional_accuracy` and `public_positional_accuracy` to be identical at least in the data she downloaded so she just picks one, but she's left a bit confused by why both fields are present in the response if they are indeed the same and wondering if she did something wrong and is using the wrong accuracy.

**Comment by kueda** [comment]
I understand the confusion you're trying to prevent, but I still think it would be better to leave `positional_accuracy` alone and/or always include it, and rename `public_positional_accuracy` to `coordinate_uncertainty` to better describe what it actually is (i.e. not a "public" version of a potentially-hidden `positional_accuracy` but rather the uncertainty attached to the most accurate coordinates you are seeing). I don't love that approach either b/c it's a lot of churn for little gain, but it seems like the lease confusing option to me.

Adding a `private_positional_accuracy` just makes things more confusing, not less, in my opinion. Again, maybe @carrieseltzer or @pleary can break our tie.

**Comment by loarie** [comment]
OK @carrieseltzer and @pleary I hope this diagram helps. Sounds like Ken-ichi and I are agreed to the consensus step. I'm happy to stop there. Or do my additional optional 'Scott's step'. I've also included Ken-ichi's optional additional step. My ranking of preference would be: (1) consensus step + scott's step, (2) consensus step only, (3) consensus step + ken-ichi's step. curious what you think
<img width="546" alt="Screen Shot 2021-01-05 at 5 06 26 PM" src="https://user-images.githubusercontent.com/598026/103716615-5ffcb980-4f78-11eb-9c7d-e5a0c2d949dd.png">

**Comment by carrieseltzer** [comment]
It appears I totally dropped the thread on this very related issue #569 in 20218. If there's still a branch with that work @kueda did, maybe the easiest thing is to try that first?

**Comment by jwidness** [comment]
If I can throw in 2 cents as an identifier -- having the "private" positional accuracy for obscured observations is sometimes useful.  For example, if I see an observer has entered 5 m as the accuracy, but it's obscured to 28 km, I can ask them to (without giving away anything too specific) share more info about the location, which can be a big help for narrowing down an ID.

**Comment by loarie** [comment]
I'm not sure if going back to #569 helps or just adds another layer of confusion. We do now have `coordinates_obscured` in exports so at least some of what was discussed in that issue was implemented. If you want to build on #569 can you explain/map what is being proposed and how its different from whats currently in production?

Alternatively, can we move forward with the consensus solution which is to remove `private positional accuracy` from the DB and replace that column in the CSV exports with a column representing `public positional accuracy` - I still think my optional step would make things less confusing but that would remove the bug (showing the wrong attribute) and would reduce this to an improvement situation (as what people need to do with the export could be explained in some not super elegant documentation)

**Comment by carrieseltzer** [comment]
I am fine with whatever you decide on this.

**Comment by loarie** [comment]
ok here's a simple approach that just yanks private_positional_accuracy and includes public_positional_accuracy in exports https://github.com/inaturalist/inaturalist/pull/2940
e.g. the 'consensus step' above - does this look ok @kueda

**Comment by kueda** [comment]
Can we close this, @loarie?

**Comment by loarie** [comment]
yes thanks
