### ISSUE TITLE
Identify: Clicking on "View more unreviewed" often loads a page with obs I marked as reviewed

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2898]
So I usually go through obs pretty fast via the modal and mark them everything as reviewed. When I get to the end of a page I usually hit Enter to "View more unreviewed". When I do that, the next  page that loads often includes observations I'd marked as reviewed on the last page. Here's a video showing that (the centipede obs):

https://photos.app.goo.gl/1waHKXyDcno9PXuV9

It's *often* the last few obs of the previous page, but sometimes it's not, and the number of obs varies.

**Comment by kueda** [comment]
I think this is just lag in updating the index, and I don't think there's much we can do about it.
