### ISSUE TITLE
Date is being parsed in comments

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2917]
From: https://forum.inaturalist.org/t/dates-in-comments-are-parsed-somehow/19386

Write a date in this format: `2021-01-09T01:01:01+02:00` in a comment on an observation and iNat says "Invalid date":

<img width="381" alt="image" src="https://user-images.githubusercontent.com/15896181/104271186-1b2cc300-544f-11eb-81cd-e5039aac4b0c.png">

**Comment by kueda** [comment]
Should be fixed by https://github.com/inaturalist/iNaturalistAPI/commit/754e410db4ad25498aebe51bcf881583db52f4a0
