### ISSUE TITLE
Account Settings: Who can add observation fields to my observations? not working properly

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2922]
From: https://forum.inaturalist.org/t/new-account-settings-page-says-anyone-can-add-observation-fields-to-my-obs-but-actually-only-i-can/19430

User bouteloua had this setting set to `Only you` before the new Account Settings was released, but on the new Account Settings page they're seeing `Anyone`. However, if one goes to their observations, they'll see

![image](https://user-images.githubusercontent.com/15896181/104511199-3871a680-55a1-11eb-807e-48c7bf208f84.png)

My account had it set to `Anyone` before new Account Settings page was released. If I choose `Only you` and save, it does not change who can add an observation field to my observations - anyone still can. If I select `Curators` and save, only curators can add obs fields to my observations.

**Comment by albullington** [comment]
@kueda This appears to be working as expected on the client side -- we're fetching one of these three options from `preferred_observation_fields_by` in `users.me`: 

- `anyone`
- `curators`
- `only_you`

Locally, they all seem to be saving and returning the expected value from `users.me`, so I think this is either an API issue or perhaps these aren't the correct names for these three options?
