### ISSUE TITLE
Account Settings page: no error message if the new username you save has already been taken

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2931]
1. In Account Settings page, enter in a username you know has been taken, like `tiwane`.
2. "Save Settings" button turns blue, but nothing happens if you click it. The username you just entered stays in the field.
3. Navigate to another page on iNaturalist - your original username is still displayed.
4. Go back to Account Settings: your original username is shown in the username field.

Expected: if one tries to save a username that is either already taken or is not formatted properly, the Save Settings button should gray out, one's original username should be shown in the field, and an error message should be displayed.

**Comment by albullington** [comment]
Closed by commit [#013a5d](https://github.com/inaturalist/inaturalist/commit/013a5d66a60ed9696b7c5a85836feac89d3c82f3)
