### ISSUE TITLE
Account Settings: unfollowing yet trusting someone = you still see their new obs in your dashboard

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2933]
From: https://www.inaturalist.org/observations?place_id=2764&subview=grid&taxon_id=146199 I can replicate.

1. Using your real account go to a test account's profile and follow them.
2. Go to the Relationships screen in your Account Setting then uncheck "Following" and check "Trust with Hidden Coordinates.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/15896181/105241196-27391480-5b22-11eb-96d7-0db85961fe5c.png">

3. Go to the test account's profile and you'll see you're not listed as following them. 
4. Log in to test account and upload an observation. That observation will show up in the real account's dashboard, even though there is no indication the test account is being followed.

FWIW, the trusting part of this seems to work, it's just the following part that gets confused.

**Comment by albullington** [comment]
I can replicate this too. Though I think this one is more in @kueda's court -- `following` appears to be saving the expected values via the relationships endpoint.
