### ISSUE TITLE
Suggestions don't appear when trying to @-mention someone

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2938]
From: https://forum.inaturalist.org/t/suggestions-not-showing-when-trying-to-mention-someone/19714

Add a comment to an observation and start typing in someone's username, eg `@carrieseltzer`. No suggestions pop up. The user does get notified of the mention, though.

Console shot from FF 84.0.2:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/15896181/105752296-f3803500-5efb-11eb-816b-d87972a56ddf.png">

**Comment by kueda** [comment]
This got deployed this morning, correct? Still seems to be broken for me.

**Comment by pleary** [comment]
I haven't deployed today. Production is running 42a43f3 from yesterday

**Comment by farmerkatherine** [comment]
@pleary this still happens maybe 95% of the time on my Android mobile. I almost never get anything at all but once in a while it comes up. Been happening for months on my old phone and continued on my new. 

My current phone is a Galaxy S24, iNat v1.30.15 (608).

Is there a newer bug that's open? Do we reopen this one as happening again?
