### ISSUE TITLE
I am devolping a project with iNaturalist api, the request is: when I up a photo, the api give me the best choice and three main suggestions based in the photo I up. The api can do it? I haven´t could find with what function.

### ISSUE THREAD

**Issue by lpineda7** [inaturalist/inaturalist#2939]
[//]: # (For feature requests and bug reports not specifically concerning code, please use https://forum.inaturalist.org/c/feature-requests/16. iNat staff will make github issues if/when an actionable solution emerges)

**Describe the bug**
A clear and concise description of what the bug is, preferably with citations to the relevant code in this github repo.

**To Reproduce**
1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Context**

**Additional context**

**Comment by boucur** [comment]
Hi @lpineda7, if you have a question, it's best to post it to the forum (https://forum.inaturalist.org/) or send an email to help@inaturalist.org. Specific examples or screenshots will help troubleshoot the problem.

**Comment by loarie** [comment]
@lpineda7 what boucur said, but I can confirm that the iNaturalist computer vision api which would do what you describe is unfortunately currently not publicly available. The public iNaturalist API https://github.com/inaturalist/iNaturalistAPI is for reading data and, if writing data, it should be data you want to post to your own account and share with the iNaturalist community which doesn't sound like what you want (e.g. an observation that you made).
