### ISSUE TITLE
Users filter is not appearing on project about page

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#2948]
**Describe the bug**
When you click "Read more" on the project detail page and get to a page like https://www.inaturalist.org/projects/test-arizona-kueda?tab=about, we do not seem to be showing a users filter, i.e. the "Include Users" section of the project form.

**To Reproduce**
1. Make a collection project and choose some users in the "Include Users" section. Save it.
1. Go tot he detail page and click "Read more" in the header
1. Look at the list of filters on the right: there's no mention of the "Include Users" filter

**Expected behavior**
That project description should describe all the filters being applied to the project

**Additional context**
This came up while testing trusted collection projects. Project members need to have a complete understanding of what observations will be included in the project before choosing to to trust the project with their hidden coordinates.

**Comment by rawcomposition** [comment]
If I'm understanding correctly, we are already showing the `Include Users` filter [here](https://github.com/inaturalist/inaturalist/blob/main/app/webpack/projects/show/components/requirements.jsx#L217-L233). And it seems to be working as expected:
<img width="1245" alt="Screen Shot 2021-02-15 at 4 58 12 PM" src="https://user-images.githubusercontent.com/740090/107996904-89fdbe80-6faf-11eb-9b3c-12c537bc425f.png">

**Comment by kueda** [comment]
Cool, well I'm glad it's working in some contexts. In my example, I've checked the `Only display observations from project members (people who have joined the project)` option and as a result, the About page is showing

![Screen Shot 2021-02-16 at 11 30 03 AM](https://user-images.githubusercontent.com/22691/108111982-54f27a00-704a-11eb-82ef-bd10f7293f1e.png)

However, that project also has an "Include Users" filter applied, and that seems to be what is actually taking precedence, so the Project Requirements should reflect that.

**Comment by rawcomposition** [comment]
Got it, makes sense. What should happen if there's users chosen **and** the `Only display...` checkbox is checked?
Would something like this do the trick?
<img width="426" alt="Screen Shot 2021-02-16 at 4 58 30 PM" src="https://user-images.githubusercontent.com/740090/108127005-98fc7380-7078-11eb-9ece-db9cddd67eb1.png">

**Comment by kueda** [comment]
Hm, that setting isn't about who can view the content but about what observations get included in the project. Since the "Include Users" filter seems to be taking precedence, I think the "Users" row should list the users in the "Include Users" filter if present, and if not it should show "Project Members Only," and if neither then just show "Any"

**Comment by todtb** [comment]
I can take a look into this.
