### ISSUE TITLE
Account Settings - Improve Change Password Flow

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2954]
Here's the current flow for changing one's password in the new Account Settings Page:

1. Enter and confirm new password in the two required fields.
2. Click on blue "Change Password Button"
3. "Save Settings" button in upper right-hand corner turns blue, indicating you need to click it. 
4. Click Save Settings and the button turns gray and shows a time stamp.
5. Try to go anywhere else on iNat and discover you have been surreptitiously logged out.
6. Log in with new password, which has been saved and is working.

Issues:

Step 3: It's not apparent that you need to click on Save Settings to _actually_ change your password.
Step 4: a) you're logged out b) you are never told you have been logged out, which is both confusing and alarming, especially since you were changing your password.

Possible improvements?

- Make "Change Password" save the new password without the user having to click on Save Settings.
- If that's not possible, clearly indicate that the user needs to click on Save Settings.

- Don't log the user out once their password has been changed.
- If that's not possible, they should be taken to the log in screen and we should display a banner saying their password has been saved and that they need to log in again.

**Comment by kueda** [comment]
> Make "Change Password" save the new password without the user having to click on Save Settings

This is possible and I'm fine with that. @abhasinat, would you be ok with just some green text next to the "Change Password" button that says "Password changed!" or something?

> Don't log the user out once their password has been changed.

It's not immediately obvious why this is happening, but I actually think it should do this and in fact I think it should remove all authorizations you've granted to any other apps, including the iNat mobile apps, so you'll be forced to sign again. This gives people a lot more control in situations where they think their password and/or account has been compromised. Maybe that's a different issue. Anyway, I agree that "they should be taken to the log in screen and we should display a banner saying their password has been saved and that they need to log in again." I also think they need some warning in advance of that, either text on the profile editor or a confirmation dialog when they try to change their password. Thoughts, @abhasinat?

**Comment by abhasinat** [comment]
> This is possible and I'm fine with that. @abhasinat, would you be ok with just some green text next to the "Change Password" button that says "Password changed!" or something?

I think that's a great idea. A good solution might be to use the error state text styling from when someone enters an invalid email or an already taken username except in green (so its a confirmation state) with the text "Password successfully changed" after a user has successfully changed their password. If we want to go with immediately taking them to the login page after changing their password, we can show them a simple green banner with the text "Password successfully changed, please log in again" at the top of the login screen.

>  I also think they need some warning in advance of that, either text on the profile editor or a confirmation dialog when they try to change their password.

I agree, we can add some help text under Change password such as "Changing your password will log you out of all of active iNaturalist sessions across your devices"

**Comment by kueda** [comment]
Revisiting this: if we sign people out after changing their password, I don't think it should update in the background. I think the password form should behave like a regular HTML form, i.e. it should leave the page and discard all other changes, sign you out, and redirect you to the log in page. If we really sign people out after they change their password, then their current session is invalid anyway and any changes they make on users/edit won't stick until they sign in again.

Are people ok with that? That should be a pretty straightforward change.

**Comment by abhasinat** [comment]
Discarding all other changes and logging them out makes sense to me! With the help text and the confirmation banner I suggested above, I think this sounds great.

**Comment by tiwane** [comment]
Soudns good to me.

**Comment by pleary** [comment]
I started an implementation of this. @kueda for the removal of authorizations, what I have so far is here https://github.com/inaturalist/inaturalist/blob/2954-password-change-flow/app/models/user.rb#L1285 . Do you think that's sufficient or are there other things we should be deleting or revoking after a password change?

**Comment by kueda** [comment]
@pleary I think that's sufficient. I was wondering if there was a reason to delete `Doorkeeper::AccessGrant` records as well, but if you change your password I don't *think* that implies that you revoke authorization from third parties.

**Comment by pleary** [comment]
This is merged into main now. The merge behavior is that password changing is independent of other user settings. There is a warning in the form that changing your password will log you out of the website, and a confirmation dialog that says the same. Once the password is successfully changed, the user is logged out (any unsaved changes to settings are lost), the user is redirected to the login page with a message saying their password was changed and they need to log in again.

It does not yet include invalidating mobile app tokens. We can add that in once the related Android issue is implemented
