### ISSUE TITLE
License link on taxon page returns a 404

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2970]
1. Go to https://www.inaturalist.org/taxa/261600-Lygaeus-truculentus
2. Click on default photo (which is from Wikimedia Commons) and click on "some rights reserved" in the viewer modal.
3. Leads to https://creativecommons.org/licenses/pd/4.0/ and a 404

**Comment by kueda** [comment]
I think when the `license_code` is `pd` we should link to https://en.wikipedia.org/wiki/Public_domain
