### ISSUE TITLE
Clicking "Edit" on obs fields with datataype of "taxon" creates a blank page

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#2978]
From https://forum.inaturalist.org/t/cant-edit-observation-fields/20648

1. Go to https://www.inaturalist.org/observations/70106749
2. Click on the obs field "Host Plant ID" and choose "Edit".
3. Page becomes blank. 

Console shot: 

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/15896181/109262825-10d44780-77b7-11eb-88f3-24cb88fb311b.png">

**Comment by kueda** [comment]
I think this was fixed by f3ed514a45e7ebd00aa1b7e410b45751418cdee0
