### ISSUE TITLE
Limit place creation to 10 per day per user

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#3007]
Every once in a while a user will create dozens or hundreds of places in a day which can fill up the DelayedJobs queue with a lot of indexing jobs. These places are often nearly the same as existing places, or narrowly-used places that end up getting abandoned, leaving places in the database that we still need to index against. Eventually we could introduce the ability to dynamically search observations with a geometry w/o needing to create an actual place entry. For now, let's limit the number of places a user can create in a day

**Comment by kueda** [comment]
https://github.com/inaturalist/inaturalist/pull/3035 achieves this, I think, just a matter of merging and deploying when we think it's appropriate.
