### ISSUE TITLE
Remove "Search external name providers" feature during content freezes

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#3008]
During a content freeze we do not allow taxa to be moved. The "search external name providers" feature in the taxon autocomplete search is known to lead to many ungrafted taxa. Since these ungrafted taxa cannot be updated during a content freeze, it can lead to a large backlog of work for curators when the freeze is lifted. This is a feature we may want to remove entirely eventually, but for now remove it during a content freeze to reduce curator workload

**Comment by Optilete** [comment]
"Search external name providers" can be used for adding common names and I think it is a good idea to keep this feature.
