### ISSUE TITLE
On taxon pages, the About tab shows EoL entry rather than Wikipedia entry

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3019]
From: https://forum.inaturalist.org/t/incorrect-wikipedia-page-in-about-or-shows-eol-page-when-wiki-page-exists/21946 Happening for a lot of taxon pages. Here's an example. 

1. Go to https://www.inaturalist.org/taxa/83816-Ophrys-apifera
2. The about tab shows the EoL entry (and in Spanish, even though my locale is English)

<img width="509" alt="image" src="https://user-images.githubusercontent.com/15896181/115311478-91168980-a124-11eb-880a-8aecd8247204.png">

3. There is an English Wikipedia entry for this taxon: https://en.wikipedia.org/wiki/Ophrys_apifera

**Comment by tiwane** [comment]
Looking better, thanks. Not sure if it's related, but https://www.inaturalist.org/taxa/743180-Viola shows no Wikipedia article content but _does_ link to [the Wikipedia article about the instrument](https://en.wikipedia.org/wiki/Viola). 

<img width="544" alt="image" src="https://user-images.githubusercontent.com/15896181/115457504-7e11c100-a1d9-11eb-8d8a-7dfdb00e4cf0.png">

**Comment by kueda** [comment]
It's not related and I don't think it's really a problem worth fixing (sections? seriously?). If people want to map https://www.inaturalist.org/taxa/743180-Viola to a Wikidata concept which is then mapped to a Wikipedia page, it should work.
