### ISSUE TITLE
Featuring projects not working on iNaturalist.ca

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#3048]
Site admin tools of featuring collection projects (selecting "new & noteworthy" or "featured") for inaturalist.ca isn't working (selection doesn't remain after reloading the page & project doesn't show up as featured). Replicate by going to https://inaturalist.ca/projects and choosing a collection project to feature (e.g. https://inaturalist.ca/projects/observation-nation-bioobservateurs?tab=about). After choosing either option from "feature this project", it's not reflected on the Projects page.

Featuring works on iNaturalist.org. It also works for traditional projects on .ca, with the exception that a single project then occupies two slots in the "new & noteworthy" carousel (rather than filling the third available). Oddly, spot checking other sites, it is working for Guatemala & Israel, so this isn't a network-wide issue.

**Comment by pleary** [comment]
I think this should be fixed now, but I haven't tested in production yet. It would be great if you could try and replicate, and close if it seems resolved

**Comment by carrieseltzer** [comment]
Appears to be fixed for Canada! Passing on thanks from them.
