### ISSUE TITLE
Moderation Notes: make suspension a moderator action

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3050]
Request at: https://forum.inaturalist.org/t/show-suspensions-in-moderation-history/22777

Along with hiding/unhiding comments, suspension is the other major action curators can take, but it's not recorded in the moderation notes. 

I propose we add `suspend` and `unsuspend` moderation actions that apply to `User` that records when the user was suspended/reinstated, who suspended/reinstated them, and why.

Another improvement would be to make the curator enter a reason for suspending/reinstating the user, which could be entered in the `Body` field. Minimum 10 characters, max of 150 characters, or something like that.

**Comment by kueda** [comment]
Certainly doable. Do you want to make this a requirement for admins as well? Rephrased: is there ever a reason for anyone to suspend or unsuspend a user without providing an explanation for each action?

**Comment by tiwane** [comment]
Not sure how much work this would  be, but it'd be great if it could be prioritized. A recent incident made it easy for someone to claim a suspension was done by someone for personal reasons but it's not easy to track down the suspension actions (and they're probably gone from the logs by now).

**Comment by tiwane** [comment]
If we require a reason for suspension, there should be explantory text like:

> Please cite the Community Guideline(s) the user violated and refrain from adding personal opinions.
