### ISSUE TITLE
422 error when making a new place - return user to page and show helpful error message

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3066]
When a user creates a new page and gets a 422 error (which happened recently when one of hte place's polygons had fewer than four points) we showed them a 404 page, which was both inaccurate and not helpful to them. So for 422s let's return them to the place creation page and show them a helpful error message like we do for other errors.

**Comment by pleary** [comment]
This should be fixed now, at least for the error that led to this ticket
