### ISSUE TITLE
User.forget should remove media from all possible s3 buckets

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3068]
Since we moved to hosting CC-licensed media in a separate s3 bucket, `User.forget` is potentially not deleting media that was CC-licensed at the time it was deleted. Currently we don't remove media from the private bucket when a license change necessitates moving it to the public bucket, which means we can never be sure whether there's a copy lingering in the private bucket unless we check. Thus, to remove media associated with `DeletedPhoto` records, we need to issue delete requests to both the public and private buckets.

**Comment by pleary** [comment]
This should be fixed in 51594fc
