### ISSUE TITLE
Web uploader: all projects appear in drop-down menu, not just traditional projects

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3071]
thebeachcomber reports that until a few days ago, only traditional projects showed up in the Projects dropdown menu on the uploader, but now all projects one has joined do, including collection/umbrella projects.

<img width="448" alt="image" src="https://user-images.githubusercontent.com/15896181/120400519-e08ad080-c2f2-11eb-9176-3e530946148c.png">

**Comment by kueda** [comment]
Should be fixed by https://github.com/inaturalist/iNaturalistAPI/commit/b357f5050c51f7b8356c4427a69829e72e2eecb8
