### ISSUE TITLE
Favorites page: tab title doesn't display properly

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3078]
1. Go to https://www.inaturalist.org/faves/loarie or to the favoites page of any user that is not you.
2. The apostrophe is not displayed properly in the browser's tab:

<img width="154" alt="image" src="https://user-images.githubusercontent.com/15896181/121267858-b21c7080-c871-11eb-9561-bdeadfda9ed8.png">

**Comment by lvddergovt** [comment]
Instead of the HTML code, you should use the normal apostrophe ( ' ) as the title tag doesn't support HTML code.
