### ISSUE TITLE
Make it easier to find places outside the scope of a network site

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#3081]
If someone searches from /places on a network site for a place that is either A) actually outside the scope of the network site or B) inside the network site scope but hasn't been assigned a parent place inside the network site scope, they cannot find the place. This leads to confusion.

When searching for projects, there is always an option to "view projects from everywhere" from /projects/search. e.g. 
<img width="802" alt="Screen Shot 2021-06-11 at 8 10 04 AM" src="https://user-images.githubusercontent.com/7501183/121684272-7b6e7200-ca8c-11eb-9c5e-a249f3e000fa.png">

There is no such "view places from everywhere" option on /places. 

I see 2 possible approaches here:
1. Add a link to "view places from everywhere", which would require adding something like the `everywhere=true` to the place search api, e.g. allow something like https://uk.inaturalist.org/places/search?commit=Search&everywhere=true&q=auckland&utf8=%E2%9C%93 (currently returns no results), which is analogous to https://uk.inaturalist.org/projects/search?commit=Search&everywhere=true&q=auckland&utf8=%E2%9C%93
2. Change /places searches to return results from the header search filtered to places, e.g. https://uk.inaturalist.org/search?q=auckland&source%5B%5D=places

If we go with option 2, I suggest that we also change the search results from /projects to behave similarly.

**Comment by kueda** [comment]
Assuming option 2 means getting rid of that site-specific project/place filtering, then I prefer that.

**Comment by kueda** [comment]
@carrieseltzer should we proceed with option 2?

**Comment by carrieseltzer** [comment]
Yes I think so

> --


Carrie Seltzer, PhD
Stakeholder Engagement Strategist
iNaturalist
California Academy of Sciences

Note: I am based in Washington, DC (check local time
<https://www.timeanddate.com/worldclock/usa/washington-dc> for scheduling
purposes)
