### ISSUE TITLE
Logstasher.write_hash fails with stack level too deep

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3093]
In the rails5 branch, almost every request writes the error `Logstasher.write_hash failed: stack level too deep`. Presumably there's some recursive logic in there somewhere, but I'm guessing that means logstash logs aren't getting written.

**Comment by kueda** [comment]
@pleary was this fixed in 606c3054d762eb81192b0f82fa9cce6786e17320?

**Comment by pleary** [comment]
yes I believe so. I'll close this
