### ISSUE TITLE
Add comment field to new flag form

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3098]
- [ ] On the [new flag page](https://www.inaturalist.org/taxa/47655/flags/new), add a textarea labeled "Comment" that will create the flag and add a new comment by the user on that flag; indicate that the comment is to add supporting rationale for the proposed change like links
- [ ] Indicate that the "Reason" is required, since there's now an optional field in the form
- [ ] Remove the "Add Another Flag" link (why is that even there)

**Comment by fredunit** [comment]
What is flag? is it flag variable?

**Comment by kueda** [comment]
A [Flag](https://github.com/inaturalist/inaturalist/blob/main/lib/acts_as_flaggable/flag.rb) is a record indicating that something should change, usually that the site curators or sometimes site admins should do something about it. So if you think a taxon name is outdated and should change, you can add a Flag to that Taxon to indicate that a curator should update the taxon record somehow. The Flag model has a `flag` attribute that is a string describing what's wrong and what should change. However, the flag attribute is short, and sometimes curators need more information than people can provide there to actually enact the requested change, so flaggers are encouraged to leave a comment on the Flag with that additional information. The current flag form doesn't make that easy, though: you have to create your Flag record, then you get redirected back to the taxon page, then you have to go back the detail page of the flag you just made and add a comment. The proposed change here is to simplify this process by adding a comment field to the flag form so people can provide all the information a curator requires in a single form.

**Comment by todtb** [comment]
Hey @fredunit, were you thinking of taking a look at this? 

I was just working on a few other changes to Flags, and was considering picking this up if you weren't already working it.

**Comment by tiwane** [comment]
@todtb (or anyone) if you do have time to look at this, that would be awesome.

**Comment by bianavarga** [comment]
I'll grab this 😄

**Comment by bianavarga** [comment]
I think this will either a) require more refactoring of existing code than I feel comfortable doing without first consulting with someone b) require some nugget of rails knowledge that I have yet to acquire as I figure my way around.

The confusion stems from the fact that flags already have both a `comment` field, which seems to be used to provide details about how/why the flag was resolved, and a `comments` field, which holds the array of comments related to the flag.

However, I think this is causing some trouble related to assumptions that Rails makes about singular & plural words.
For instance, this HAML, which I believe should create a text area field for editing the body of the first comment:

```
= f.fields_for( @flag.comments.first ) do |f_comments|
    = f_comments.text_area :body, class: "pull-left", maxlength: 5000, style: "height: 150px;"
```

instead results in a field with the name `flag[comment][body]`, which Rails interprets as being related to the `comment` field and not the `comments` field.

I think it would be reasonable here to refactor `comment` to be called `resolution_comment`, ideally without having to perform a database migration. Does that sound like the right course of action? Is there another approach here that I am missing?

Thank you!

--Biana
