### ISSUE TITLE
Add keyboard shortcut for controlling image brightness in Identify

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3100]
We already have a control for image brightness, but some people have requested that we add a keyboard shortcut to control it, e.g. `CMD+UP` and `CMD+DOWN`. IMO, this will probably require pulling the brightness state out of the component and into the app state where we can modify it with a Redux action. Brightness will have to remain obs/photo-specific as it is in the current component state-based approach.

**Comment by zdankowicz** [comment]
Hi,

Isn't brightness at the moment photo-specific?

**Comment by kueda** [comment]
It's specific to the obs *and* the photo. I updated the desc. Thanks.

**Comment by kueda** [comment]
Closed in https://github.com/inaturalist/inaturalist/pull/3207
