### ISSUE TITLE
Alphabetical sort by scientific name in Compare

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3108]
Currently Compare (`ObservationModal`) suggestions support the default sort and a `taxonomy` sort. We'd like to add an alphabetical sort by scientific name to that list called `Scientific Name`. Depends on https://github.com/inaturalist/iNaturalistAPI/issues/260. Will require adding that option to the UI and sending `order_by=sciname` to taxa/suggest.

**Comment by todtb** [comment]
https://github.com/inaturalist/iNaturalistAPI/pull/261 Should enable this, I can start looking into adding in the FE.
