### ISSUE TITLE
Adding a new conservation status incorrectly marks existing statuses as updated

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3120]
From https://forum.inaturalist.org/t/adding-a-new-conservation-status-incorrectly-marks-existing-statuses-as-updated/23465 I can replicate.

1. Find a taxon with an existing conservation status.
2. Add another conservation status to it and save.
3. On the Status screen of the taxon, all conservations statuses show and "updated by" date and attribution to you and to the current time and date, even if existing statuses were not touched.

**Comment by todtb** [comment]
I can start looking into this
