### ISSUE TITLE
Show site ids on /announcements

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#3127]
With more network members using announcements, it would be useful for staff to be able to see at a glance which announcements are on which sites (since we see them all). Can we add a column after `Placement` that displays the site IDs associated with each announcement on /announcements? 

This will also help make it more visible to network members when they're looking at (and therefore shouldn't edit) an announcement displayed on multiple sites.

<img width="1012" alt="Screen Shot 2021-07-14 at 9 43 28 AM" src="https://user-images.githubusercontent.com/7501183/125632868-63b26323-762e-4e66-a165-3d7232bc36c3.png">

**Comment by todtb** [comment]
Coming right up

**Comment by todtb** [comment]
Hey @carrieseltzer, got a PR (https://github.com/inaturalist/inaturalist/pull/3134) but wasn't sure if you wanted this column visible for ALL admins (including site specific), or just top level admins. For now it's the latter, but a very simple fix if you were thinking of making it visible for all.

**Comment by carrieseltzer** [comment]
Thanks @todtb! It should be visible for all site admins, not only iNat staff.

**Comment by kueda** [comment]
Only staff (`is_admin?`) and site admins (`is_site_admin_of?( @site )`) can even see this page, so I think it's ok to show the "Sites" column to everyone who can see the page, even if the site admins just see the same thing for all their announcements (if they see something different then that would be a good indication that something's wrong, but it's also theoretically possible for one user to be a site admin for several sites).

**Comment by carrieseltzer** [comment]
Sometimes staff (mostly me I guess) make announcements visible on multiple sites, so in those cases it would help the site admins see that an announcement isn't only on their site, so any edits they make would impact all selected sites.
