### ISSUE TITLE
Display announcement number in page title (browser tab name)

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#3128]
I frequently have multiple tabs open with announcements and refer to the announcement numbers in UTM tags. Currently, all announcements have the same page title "iNaturalist". I propose updating the page titles as follows:

"Announcements" for https://www.inaturalist.org/announcements
"[announcement number]" for pages where you view announcements, e.g. "732" for https://www.inaturalist.org/announcements/732
"Edit [announcement number]" for pages where you edit announcements, e.g. "Edit 732" for https://www.inaturalist.org/announcements/732/edit

These page titles do not need to be translated.

Not urgent or important, but if it's easy it would really help me navigate my tabs and dramatically reduce the odds of me editing the wrong announcement.

**Comment by todtb** [comment]
On it

**Comment by carrieseltzer** [comment]
This small thing makes a huge difference for me. Thanks @todtb!
