### ISSUE TITLE
Remove ProjectInvitation

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3129]
This was a model that recorded a request that an observation be added to a project. This was before collection projects (which don't record explicit inclusion in a project), and it seems like it was something we abandoned around that time, or maybe when we redid the obs detail page. Either way, there doesn't seem to be a way to actually create these things anymore, so we should just remove the remaining infrastructure:

- [x] Check to see if there are any remaining legitimate uses of this (we're not using it in the mobile apps, are we?!)
- [x] Remove `ProjectInvitationsController` and all associated views and routes
- [x] Remove any links to actions in that controller, including the one on `ProjectsController#by_user`
- [x] Remove related translation keys
- [x] Remove the `ProjectInvitation` model
- [x] Add a migration to remove the `project_invitations` table

**Comment by todtb** [comment]
I think it makes sense to do this in a (at least) 3-step process:
- Remove routes, controllers, views, links, etc.
- Remove model, associations, i18n keys
- Drop table

I'm testing a build of the first step here: #3137
