### ISSUE TITLE
Reposting obs to FB not working

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#315]
Sub-issue 1:
My iNat obs seemed to have stopped reposting to Facebook between August 15th and August 17th as shown by my activity feed:
![screen shot 2014-09-16 at 12 20 06 pm](https://cloud.githubusercontent.com/assets/598026/4293571/72c40802-3dd7-11e4-8977-c1a372a924d1.png)

Sub-issue 2:
When Reposting obs to FB was working, it only appeared in my 'recent activity' as shown here:
![screen shot 2014-09-16 at 12 27 39 pm](https://cloud.githubusercontent.com/assets/598026/4293632/0b73ba20-3dd8-11e4-9bf2-58831b1d7e7d.png)
But it never posted to my wall as apps like Project Noah do:
![screen shot 2014-09-16 at 11 54 59 am](https://cloud.githubusercontent.com/assets/598026/4293634/134f416a-3dd8-11e4-8fb1-e73475df46b3.png)
This is the behavior I was expecting when I chose to automatically share my postings on FB

Sub-issue 3:
Currently, if I sign in with Facebook and opt-out of 'iNaturalist would like to post to Facebook for you.' permissions the 'Automatically share your observations on FB' checkboxes on Account and Obs/New are checked which is confusing. Might be better to uncheck those boxes if iNat doesn't have post permissions for that user, and if the user tries to check them, first direct them to a link to give iNat those permissions before allowing the boxes to be checked

**Comment by loarie** [comment]
still broken - ugh FB...

**Comment by carrieseltzer** [comment]
Some part of this appears to be working. If I go here: https://apps.facebook.com/inaturalist/?ref=br_tf
I see many observations submitted today, including the bee on the cosmos submitted by me, but I can't see it anywhere on my own page. I also can't make iNaturalist appear in the "apps and games" section of my profile (it doesn't show up as a result in search)
![screen shot 2015-11-05 at 12 39 32 pm](https://cloud.githubusercontent.com/assets/7501183/10976566/7c295bf2-83ba-11e5-8cf6-e13de75a143d.png)

**Comment by loarie** [comment]
thats different Carrie - the bug I mentioned is the functionality that reposted obs into your FB activity feed

**Comment by carrieseltzer** [comment]
Ok that definitely doesn't work.

**Comment by loarie** [comment]
#783 - decided not to fix this
