### ISSUE TITLE
Photo Inviter not working for Facebook

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#316]
Sub-issue 1: 500 error on photo invite if no FB post permissions
If inviter doesn't have FB post permissions, sending invite from http://www.inaturalist.org/photos/inviter gives 500 error rather than prompting the user with a pathway to give permissions

Sub-issue 2: Failwhale appearing in the FB comment generated by inviter
![screen shot 2014-09-16 at 10 48 14 am](https://cloud.githubusercontent.com/assets/598026/4293902/a37ca8ac-3dda-11e4-80b4-71483aa839ab.png)

Sub-issue 3: After clicking on comment, (e.g. https://www.facebook.com/dialog/oauth?response_type=code&client_id=26558815027&redirect_uri=http%3A%2F%2Fwww.inaturalist.org%2Fauth%2Ffacebook%2Fcallback&state=31dd5b11203e5e67040a4f515b4f2a3f43c04e85a0d6a0aa&scope=email%2Coffline_access%2Cpublish_stream%2Cuser_location%2Cuser_photos%2Cfriends_photos%2Cuser_groups%2Cread_stream) user can't cancel flow - is instead redirected to
![screen shot 2014-09-16 at 11 09 54 am](https://cloud.githubusercontent.com/assets/598026/4293924/ccd58412-3dda-11e4-853d-9ba541e2e5be.png)

Sub-issue 4: facebook_photo_id in obs/new broken
Obs new created by the invite flow with URLs like
http://www.inaturalist.org/observations/new?facebook_photo_id=186576361432187&project_id=40&taxon_id=36299&welcome=true#_=_ 
results in no FB photos in the form checked

**Comment by loarie** [comment]
still broken, ugh FB...

**Comment by carrieseltzer** [comment]
Yeah I've been meaning to post about this again. Way to go plowing thru github last night Scott! I think fb is your biggest competitor and fixing this would make it easier to encourage people to find their social network of naturalists here instead of there. 



—

**Comment by kueda** [comment]
I don't think we've had a Facebook inviter for a long time.
