### ISSUE TITLE
place_guess should not be publicly displayed for observations with obscured/private locations

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#317]
Currently, if iNat's intention is to publicly display (a) public coordinates and (b) encompassing places but not (c) private coordinates or (d) place_guess for obscured/private observations,
then views where place_guess display should be removed.

<b>Known places include</b>:
1. Views associated with Listed Taxa (e.g. https://www.inaturalist.org/listed_taxa/4808818) are displaying place_guess for obscured observations (e.g. https://www.inaturalist.org/observations/879992)
![screen shot 2014-09-16 at 4 22 59 pm](https://cloud.githubusercontent.com/assets/598026/4296494/8c671e40-3df8-11e4-9b5f-6db9b02dfdd4.png)
1. JSON responses
2. Perhaps exports such as darwincore

**Comment by loarie** [comment]
I just checked the listed taxa views/json for threatened species https://www.inaturalist.org/listed_taxa/4808818, the json for threatened obs https://www.inaturalist.org/observations/879992.json
But it looks like the place_guess for threatened species is still retained as the 'verbatim Locality' in the Darwin exports
I think if we make that edit we can close this issue and say that place_guess is not publically revealed for obs of threatened species

**Comment by loarie** [comment]
Looks like place_guess is still making it into the GBIF archive as 'verbatim Locality', example:
https://www.inaturalist.org/observations/2079948
<img width="648" alt="screen shot 2015-11-04 at 5 53 26 pm" src="https://github-cloud.s3.amazonaws.com/assets%2F598026%2F10957834%2F0686a4f6-831d-11e5-92eb-a5b222d56a84.png">

**Comment by carrieseltzer** [comment]
No longer happening. The Verbatim locality is now California, US in GBIF.
