### ISSUE TITLE
Clicking "View" in the taxon autocomplete in the Uploader chooses the taxon

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3172]
**Describe the bug**
When choosing a taxon in the uploader, the taxon autocomplete shows a "View" link with each suggested taxon so you can view that taxon's taxon page, but currently clicking that link selects that taxon. Instead, it should not make any change to the observation card.

**To Reproduce**
1. Go to https://www.inaturalist.org/observations/upload
1. Add a new observation without media
1. In the species field type in `red` or some other text that will generate selections
1. Click the "View" link to the right of the first suggestion; a new tab will open to load that taxon's taxon detail page, but when you return to the Uploader, you'll see that taxon has been chosen.

**Expected behavior**
That clicking the "View" link makes no change to the observation you are editing.

**Context**
 - OS: Mac OS 10.13.6
 - Browser: Brave Version 1.27.111 Chromium: 92.0.4515.131 (Official Build) (x86_64)

**Additional context**
Reported in the Forum: https://forum.inaturalist.org/t/web-uploader-dont-fill-in-the-taxon-field-when-view-is-clicked/24344

While this might require some React work, I'm guessing this will mostly be about the autocomplete jquery plugin.

**Comment by pleary** [comment]
This should be fixed
