### ISSUE TITLE
Make it so that obscuring-conservation-status on place ancestor doesn't override open-conservation-status on place descendant

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#3185]
This  is our current situation. In A there’s an obscuring-conservation-status on California and an open-conservation-satus on Nevada, but nothing on the US or Oregon. Only obs in California are actually obscured. In B there’s an open-conservation-status on the US but still only obs in California are actually obscured. In C there’s an obscuring-conservation-status on the US which acts to obscure all obs, even those in Nevada. 
<img width="739" alt="Screen Shot 2021-08-20 at 4 24 50 PM" src="https://user-images.githubusercontent.com/598026/130302922-b890b72e-adc7-4c6c-9a1a-34e7542ec7d2.png">
Instead we'd like the following behavior. A and B are the same, but in C, the open-conservation-status on Nevada would take precedence over the obscuring-conservation-status on the US.
<img width="734" alt="Screen Shot 2021-08-20 at 4 27 36 PM" src="https://user-images.githubusercontent.com/598026/130302918-69fb4b71-95b1-4e43-b61e-7e0991822bdc.png">
This would deal with the longstanding ‘rabbit is endangered globally but a big invasive species in australia’ issue
but is also necessary to create a simpler policy for deciding what gets obscured that doesn't require cracking down on existing Natureserve G and N ranked statuses that are currently complicating the destiny of descendant S ranked statuses.

**Comment by kueda** [comment]
Spent a little time writing tests for this, got a bit stuck on this: what is the place whose status should take precedence, the smallest place, or the leaf place? In your example, if US is not Nevada's parent, should an observation in Nevada not be obscured?

Also, what if US *is* Nevada's parent, but there is another place called Nevada2 that contains the obs coordinates and has no parent (or is the child of North America) and has a status for this taxon with geoprivacy set to "obscured"? I assume we obscure in that case?

**Comment by loarie** [comment]
Carrie and I discussed and we think we can restrict this to admin level 0 and 1 places (+ this new admin level we're going to make to accomodate SANBI, lets call it '-2').

In other words only open cs on admin level 0 and 1 places (countries and states) can take precedence over obscured cs on ancestor places. This would cover all current applications: the network (admin level 0,-2) application and the NatureServe (admin level 1) application. It also means you don't have to look at the place_id hierarchy or place size since the admin_level hierarchy is pretty simple (global, country:0, region:-2, state:1).

Even though they have admin_levels I think we should exclude counties:2, cities:3, parks: 10 (as being too small to be able to take precedence) and continents:-1 (as not having a clear set of children, ie is the US in North American even though Hawaii's in Oceania?)

**Comment by kueda** [comment]
That's certainly doable and we can proceed with that if you don't change your mind, but I anticipate confusion among the curators, as this means conservation status on community places can obscure coordinates but not open them up, which will necessitate some equally confusing documentation.

**Comment by loarie** [comment]
I think we have enough clarity to proceed. I agree there will be confusion but at least it will be mostly relegated to the wildwest of community curated places which are probably due for more structure anyway

**Comment by kueda** [comment]
Ok, some more questions:

1. What is the `taxon_geoprivacy` of an observation in Oakland of a species that is
  a. Obscured globally
  a. Open in the US
  a. Obscured in California
1. What is the `taxon_geoprivacy` of an observation in Oakland of a species that is
  a. Obscured globally
  a. Open in California
  a. Obscured in My East Bay, a place I made covering most of the East Bay with no admin level and whose parent is California
1. What is the `taxon_geoprivacy` of an observation in Oakland of a species that is
  a. Obscured globally
  a. Open in California
  a. Obscured in My West Coast, a place I made covering what I consider to be the West Coast with no admin level and no parent

**Comment by loarie** [comment]
1.  obscured
2. obscured
3. obscured

In these cases nothing has changed because upstream obscuring continues to take precedence over anything downstream (unless there is an open on country or state that would block upstream obscuring - but not downstream - which is not the case here) 

However: 

The taxon_geoprivacy of an observation in Oakland of a species that is
a. Obscured globally
b. Obscured in the US
c. Open in California
Should be open, because CA state open is blocking upstream obscuring statuses

The taxon_geoprivacy of an observation in Oakland of a species that is
a. Obscured globally
b. Obscured in California
c. Open in My East Bay, a place I made covering most of the East Bay with no admin level and whose parent is California
Should be obscured, because My East Bay open not state/country so can't block upstream obscuring statuses

The taxon_geoprivacy of an observation in Oakland of a species that is
a. Obscured globally
b. Obscured in California
c. Open in My West Coast, a place I made covering what I consider to be the West Coast with no admin level and no parent
Should be obscured, because My West Bay open not state/country so can't block upstream obscuring statuses

**Comment by kueda** [comment]
In example 3, how is California "upstream" of My West Coast? My West Coast has no parent, so we can't say that California contains My West Coast in the ancestor hierarchy (nor can we say that My West Coast contains California). My West Coast includes parts of Oregon, so the boundary of California doesn't contain the boundary of My West Coast. And, My West Coast extends from Alaska to Chile, so we can't say that California is somehow bigger than My West Coast.

**Comment by loarie** [comment]
Your Example 3 should be obscured because Open in California (admin level 1) should only take precedence over upstream Obscuring statuses on Country (admin level 0) or global. So while open in California is counteracting Obscured globally, Obscured in My West Coast is not an upstream admin level 1 or global status relative to California so can still obscure everything in the place

That said, this example is making me think statuses on non-nested non-standard places aren't really appropriate (ie anything other than a small park), and if there was a way to prevent associating conservation statuses with such a place that would be nice. Barring that I think as a curator I'd remove such an obscuring status on My West Coast and try to achieve it via statuses on states
