### ISSUE TITLE
Voting out of Needs ID broken in API v2

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3201]
**Describe the bug**
If you click "No, it's as good as it can be" in the DQA in v2 the box just unchecks itself

**To Reproduce**
1. Opt in to the v2 test
1. Go to any observation and at the bottom of the DQA after "Based on the evidence, can the Community Taxon still be confirmed or improved?" click the checkbox next to "No, it's as good as it can be"
1. The checkbox disables, shows a loading spinner, then unchecks and returns to its prior state

**Expected behavior**
It should vote the obs out of Needs ID

**Additional context**
This might just be due to the sequential ID being used instead of the UUID, b/c I clearly did some work on this in https://github.com/inaturalist/inaturalistjs/commit/e89764ffbd257e24ed166ddbb7af74275392750c

**Comment by pleary** [comment]
This appears to have been fixed
