### ISSUE TITLE
Traditional project - removing obs field rule doesn't make field not required

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3223]
Maybe not worth fixing, but reporting here:

1. Add required obs field to traditional project, and save.
2. Go to edit project screen and there is now a rule for that required field:
3. 
<img width="370" alt="image" src="https://user-images.githubusercontent.com/15896181/132768295-4a55c534-3ca3-4272-ac6e-0715d27560ab.png">

3. Click "remove" in that Project Rules section and save project, then go back to edit project page
4. Rule has been removed, but observation field is still required. 
5. Note that the project now shows it can be converted to a collection project, which is not really correct since the obs fiedl won't be a requirement of the collection project.

**Comment by pleary** [comment]
I committed a change that removes the `remove` link from the Observation Rules section for observation field rules. There is a separate section on the project edit page for changing observation field rules, which has a more robust set of options for editing project rules. That's already the only place to add and edit field rules, and after this change it will be the only place to remove them as well. Hopefully that's a reasonable approach. It will at least fix the main bug where the ProjectObservationRule can be removed w/o removing the corresponding ProjectObservationField

**Comment by tiwane** [comment]
Works for me.
