### ISSUE TITLE
Don't show relative dates for obscured obs in Explore

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3235]
We overlooked this in https://github.com/inaturalist/inaturalist/pull/3142, but we should use the same treatment we do elsewhere, i.e. if obscured show month and year. Yes, this has boundary issues for obs made this month, but that's what we're doing for obs detail, so might as well be consistent.

This applies to grid view, map view list, and the map view infowindows on Explore.

**Comment by tiwane** [comment]
Just bumping this as it was recently discussed in a Support Report.

**Comment by pleary** [comment]
<img width="763" alt="Screenshot 2023-02-13 at 10 48 52 AM" src="https://user-images.githubusercontent.com/48566/218505329-be333661-f6a3-403f-925a-cca15f73f95d.png">

Is this what we're looking for for grid view on explore? The string can be quite a lot longer than the relative date, so we may have wrapping issues in some cases. We're already using this "Month, Year" format in list view, just not yet in grid.

**Comment by kueda** [comment]
@pleary perhaps we could use the `month_year_short` date format in grid view to get ahead of wrapping issues. Otherwise yes, I think this is what we're looking for here.
