### ISSUE TITLE
Decorate conservation statuses cascading down from taxon ancestors on taxa/show status tab

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#3248]
The first status here https://www.inaturalist.org/taxa/39814-Terrapene-carolina is associated with the genus Terrapene and is cascading down to the species Terrapene carolina. currently, its impossible for non-curators to know where this status is coming from and the only way for curators is to view the taxon/edit screen for each taxon ancestor. 
<img width="819" alt="Screen Shot 2021-09-28 at 12 33 54 PM" src="https://user-images.githubusercontent.com/598026/135154001-e7730640-8bcd-4a11-bc76-e0f0896cc1ac.png">
This proposal is to somehow decorate statuses cascading down from taxon ancestors on the taxa/show status tab to indicate the ancestor taxon (e.g. Terrapene) that they are associated with.

**Comment by loarie** [comment]
@kueda any ideas on how to achieve this without adding a whole new column to the table? Or is that the best option

**Comment by kueda** [comment]
Not a huge fan of an additional column since most taxa won't have any distinct values in that column. One alternative approach might be to remove statuses that don't apply to the taxon the page is about and display them in separate tables below this table. Or you could also add a line in the Conservation Status column that says something like: "Status applied from a higher-level taxon: Genus _Terrapene_". IMO, both of those would be fine. Maybe @abhasinat  has an opinion.

**Comment by loarie** [comment]
> add a line in the Conservation Status column that says something like: "Status applied from a higher-level taxon: Genus Terrapene 

seems to be the simplest - happy to go with that

**Comment by abhasinat** [comment]
> add a line in the Conservation Status column that says something like: "Status applied from a higher-level taxon: Genus _Terrapene_"

I like this solution as well. I would link the relevant taxon name to its taxon page. Do we do anything like `/status` to have the page automatically scroll down and show the status tab? If we do, I would link to the status tab of the higher-level taxon.

**Comment by kueda** [comment]
> have the page automatically scroll down and show the status tab

We don't but we [should](https://github.com/inaturalist/inaturalist/issues/3257).

**Comment by seanclifford** [comment]
> I like this solution as well. I would link the relevant taxon name to its taxon page. Do we do anything like /status to have the page automatically scroll down and show the status tab? If we do, I would link to the status tab of the higher-level taxon.

The status tab is currently hidden when the taxa is higher than species level - so linking to the taxon status tab on genus or higher taxon pages won't be possible unless we start to show it on those taxon pages too.

**Comment by kueda** [comment]
> The status tab is currently hidden when the taxa is higher than species level - so linking to the taxon status tab on genus or higher taxon pages won't be possible unless we start to show it on those taxon pages too.

Good point. Scott, any preference? We could just show the Status tab *if* the taxon has any conservation statuses.

**Comment by loarie** [comment]
> We could just show the Status tab if the taxon has any conservation statuses.

seems fine to me

**Comment by bianavarga** [comment]
I've got this :-)
