### ISSUE TITLE
Batch Edit - Adding to project doesn't work

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3262]
From https://forum.inaturalist.org/t/batch-edit-add-to-project-doesnt-work/26947 I can replicate.

1. Go to batch edit screen and turn on batch editing
2. Select some observations and add them to a project (eg https://www.inaturalist.org/projects/organisms-on-or-near-appropriate-signs)
3. See a brief spinner next to to the project title and then you're taken to your dashboard
4. Observations are never added to the project

**Comment by seanclifford** [comment]
Fix ready to review and merge. Apologies to those whose workflow I broke for the last couple of weeks.
