### ISSUE TITLE
Adding conservation status to Spiranthes cernua results in whale shark

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3283]
1. Edit https://www.inaturalist.org/taxa/773385-Spiranthes-cernua
2. Add a new conservation status to it, based on [this NatureServe status](https://explorer.natureserve.org/Taxon/ELEMENT_GLOBAL.2.146077/Spiranthes_parksii). 
3. Save changes and you get a whale shark.

**Comment by kueda** [comment]
No longer results in a 500 error. FWIW, _S. cernua_ should not have a global status according to https://explorer.natureserve.org/Taxon/ELEMENT_GLOBAL.2.146077/Spiranthes_parksii, which describes _S. parksii_.
