### ISSUE TITLE
place_admin1_name & place_admin2_name have empty values in CSV export

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3293]
https://forum.inaturalist.org/t/place-admin1-name-place-admin2-name-are-empty-in-csv-export/27466 I can replicate.

1. Export a CSV and make sure the place_admin1_name and place_admin2_name columns are checked.
2. Open up CSV and there are no values in the columns.

pisum notes this might be related to the recent changes to place types.

**Comment by pleary** [comment]
This should be fixed now
