### ISSUE TITLE
Taxon subscriptions in a place should *include* observations at the selected rank

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#3295]
Presently, if you subscribe to a place and then a taxon, you will only receive subscription notifications for _descendants_ of the selected taxon. While this may have made sense for broader taxonomic targets, this renders it nearly useless for subscriptions of species in places. 

Since there is no messaging anywhere to indicate that this will not currently notify you for observations at the selected taxon, I think the risk of changing it is low. 

A typical use case for this is someone who wants to be notified when a particular invasive species of interest is detected in a certain place where it is not yet established.

**Comment by tiwane** [comment]
Looks good.
