### ISSUE TITLE
Unresolving a flag which you subscribe to results in dashboard notification of "deleted user resolved flag"

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3297]
[//]: # (For feature requests and bug reports not specifically concerning code, please use https://forum.inaturalist.org/c/feature-requests/16. iNat staff will make github issues if/when an actionable solution emerges)

**Describe the bug**

If one unresolves a flag one is subscribed to, one gets a notification saying a deleted user unresolved the flag. 

**To Reproduce**
1. Find a resolved flag and add a comment to it or subscribe to it.
2. Unresolve the flag.
3. Your dashboard will show that "deleted user" unresolved the flag. 

**Expected behavior**

**Screenshots**

<img width="442" alt="image" src="https://user-images.githubusercontent.com/15896181/140163082-ef77b724-b304-48ed-b30f-91d58c73d701.png">

**Context**
 - OS: Mac OS Big Sur
 - Browser FF 93

**Additional context**
https://forum.inaturalist.org/t/flag-resolved-by-a-deleted-user/11160

**Comment by pleary** [comment]
This should be resolved now. The dashboard notification will no longer say a deleted user resolved the flag, and will also list details about the flag and the fact that it is "unresolved"
