### ISSUE TITLE
For flags on deleted comments - retain URL of where it was posted

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3299]
When a comment is flagged, sometimes the creator of the flagged content deletes it. While we retain the text of the comment, there's no link to the observation/flag/journal post where the comment was originally posted, making it difficult to track down and understand (and to see if the commenter was targeting someone's content in particular). 

I think we should add the link to the comment below its content, eg 

<img width="333" alt="image" src="https://user-images.githubusercontent.com/15896181/140233249-9e026cf3-c66a-4903-a9e6-fa9d4af3d971.png">

**Comment by carrieseltzer** [comment]
What's the status of this? Sounds like we're storing the data since the commit, but not yet displaying it?

**Comment by kueda** [comment]
@carrieseltzer and @tiwane, looks like I worked on this over a year ago and probably forgot about it. I got the branch up to date today and it seems ok so I made a [PR](https://github.com/inaturalist/inaturalist/pull/3646). I can get it on staging for you if you want to test it out.
