### ISSUE TITLE
Add "observation created using" application field on Identify modal

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/inaturalist#3304]
There was a request that @tiwane highlighted for identifiers to be able to see what application created the observation in the identify modal. Identifiers typically have different responses for observations made by new users on Android vs iOS vs web and can give better instructions to correct errors when they can figure out what device an observer is using.

![Identify - obs made indicator](https://user-images.githubusercontent.com/44380775/140807656-3abeffe8-82a7-4a33-b221-e6ae630a900e.png)

My design suggestion is to include the icon and application name beneath the Location. Additionally, I would recommend adding about 5-10px of extra space beneath the Application name field to create some distinction between the data fields and the View/Follow buttons - right now the View/Follow buttons are difficult to scan as distinct from the data fields.

**Comment by kueda** [comment]
One minor design complication here is that in this situation the app icon should be square, but the app icon from the API might not be, so `background-size: contain` in a fixed size container might be preferable here, and we'll just live with some of the weirder icons.

**Comment by erebuseternal** [comment]
I'll take a look at this :)

**Comment by kueda** [comment]
@abhasinat, Marcel raises a good point in https://github.com/inaturalist/inaturalist/pull/3336: if we use the app icon, it's going to add distracting bit of color and inconsistency to that top section of the observation modal. Is there an icon (preferably a free fontawesome one) that you think would work there aside from the dark bullet in your mock? Or do you want to go with that dark bullet, or stick with a square, colorful version of the app icon? Keep in mind we don't have much control over that app icon, and even the ones we use for our own apps seem to have white backgrounds, which looks a bit odd over the gray of the obs modal. We can force the icons to be grayscale with `filter: grayscale(1)`, but we can't force them to use the exact shade of gray used by the other icons.

**Comment by abhasinat** [comment]
In my ideal world, I would like the Seek app icon and the iNaturalist app icon to show as their images, and everything else to show as one standardized symbol. Our apps should get priority and should be treated differently. Everything else can be represented by one standard icon– perhaps this icon from the Octicons pack in Fontastic? If standardization is easiest, I'm comfortable applying this treatment to the "This observation was created using" section on Observation detail, and everywhere else on the site as well.

<img width="134" alt="Screen Shot 2021-12-17 at 3 06 05 PM" src="https://user-images.githubusercontent.com/44380775/146617863-848ad797-464f-4c67-9c7e-199b791d531f.png">

**Comment by kueda** [comment]
Ok. @erebuseternal, do you want to try and do what Abhas suggested? Maybe just use the [Fontawesome upload icon](cloud-upload-alt) for the other apps and we can change to the octicon version after merging (we need to update our icon pack for that, I think).

**Comment by tiwane** [comment]
Looks good.
