### ISSUE TITLE
Javascript issues with Create a place drawing tools

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#332]
http://www.inaturalist.org/places/new
![screen shot 2014-10-02 at 2 39 51 pm](https://cloud.githubusercontent.com/assets/598026/4498915/b553bbfc-4a7c-11e4-85c6-26330bd8e455.png)

**Comment by loarie** [comment]
buttons still look weird

**Comment by carrieseltzer** [comment]
Looks ok in Safari Version 9.0.1 (10601.2.7.2) on OS 10.10.5.
![screen shot 2015-11-05 at 12 34 00 pm](https://cloud.githubusercontent.com/assets/7501183/10976403/a9734db2-83b9-11e5-94a9-36329ce960ea.png)
