### ISSUE TITLE
Collection project badge added to owner's obs when it should be

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3323]
1. Create a new collection project.
2. Add one or two user requirements (for accounts which are not yours)
3. Check "Project members only"
4. Save project
5. There will be 0 observations in the project
6. Check your observations - they'll all have a badge for this project even though they're not included in the project

**Comment by kueda** [comment]
FWIW, this might be a react issue, but I'm guessing it's an API issue instead. Needs investigation.

**Comment by pleary** [comment]
I believe this is fixed now. It was an issue with logic in the API
