### ISSUE TITLE
Dashboard: "Agree" button displays in English, regardless of one's language settings

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3330]
The "Agree" button shows "Agree"in English on one's dashboard but not on obs show. I tried this with multiple languages and with all of them "Agree" was displayed in English on the dashboard.

From https://forum.inaturalist.org/t/agree-not-translated-in-the-web-inaturalist-org/28150

**Comment by kueda** [comment]
Hm, I guess this got fixed at some point.
