### ISSUE TITLE
Clicking on a taxon between genus and species (e.g. subgenus) loads the about tab, not taxonomy tab

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3343]
From https://forum.inaturalist.org/t/clicking-on-a-taxon-between-genus-and-species-e-g-subgenus-loads-the-about-tab-not-taxonomy-tab/5077 I can replicate.

1. Go to https://www.inaturalist.org/taxa/121922-Eublemma
2. Go to Taxonomy tab
3. Click on a subgenus (eg Subgenus Odice).
4. That subgenus's taxon page loads, but the About tab is shown, not the Taxonomy tab.

Expected behavior: the subgenus page shows the Taxonomy tab, as it does if you click on a species or a coarser taxon.

**Comment by Mayuresh0072** [comment]
@kueda Hey, Can you please assign me this issue ? Thank You.

**Comment by Mayuresh0072** [comment]
@tiwane  can you tell for which specific ranks (rank levels to be specific) of taxon this bug is occurring ?

**Comment by Mayuresh0072** [comment]
Hello @kueda I have raised a PR for this issue. Please check and approve the changes and workflow so that it can be merged into main branch. Thanks.
