### ISSUE TITLE
YIR Animated Map is Off in Safari

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3351]
1. Use Safari on a Mac or iPhone. I'm using 15.1 on my Mac Air M1
2. Load https://www.inaturalist.org/stats/2021/tiwane
3. Scroll to the map
4. There are green dots that appear, but they are down in Mexico and Central America (I didn't go to either place in 2021) and are distorted - vertically stretched. 

eg

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/15896181/148702474-7d84d3ba-a74c-48ac-9c1a-ef326c2a1ada.png">

**Comment by pleary** [comment]
This appears to be fixed in safari for me - could you try again?

**Comment by tiwane** [comment]
Yup, thanks!
