### ISSUE TITLE
Remove "access to true coordinates," from trad project description at https://www.inaturalist.org/projects/new

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3365]
Current at https://www.inaturalist.org/projects/new it says 

> Do you need features from traditional projects, such as access to true coordinates, custom observation fields, or adding individual observations that can’t be automatically filtered? Use this link to create a traditional project instead. 

But since collection projects can now be trusted, the first example is no longer accurate.

**Comment by grfeller** [comment]
@tiwane Are you looking for something as simple as changing the first sentence from the above quote, that is, 

> Do you need features from traditional projects, such as access to true coordinates, custom observation fields, or adding individual observations that can’t be automatically filtered? 

to read

> Do you need features from traditional projects, such as custom observation fields,
> or adding individual observations that can’t be automatically
> filtered?

for the `en` locale?

**Comment by pleary** [comment]
@tiwane - can you confirm the modified text that @grfeller included is how you want that section to read?

**Comment by tiwane** [comment]
Yup, sounds good to me.

**Comment by pleary** [comment]
I committed the new text for translation. Let's wait it a few days before we swap it in to give translators time to translated the altered text.
