### ISSUE TITLE
Error running docker setup

### ISSUE THREAD

**Issue by rawcomposition** [inaturalist/inaturalist#3368]
I'm primarily a React developer, so dev-ops isn't my focus area. I'm attempting to follow the [docker contributing instructions](https://github.com/inaturalist/inaturalist/blob/main/CONTRIBUTING.md) and ran into a few issues.

I created `docker-compose.override.yml` and entered a username and password. I then ran `make services` and `ruby bin/setup`. A complete terminal log can be found here: **https://gist.github.com/rawcomposition/2fc60762430f79fa8115fa032b694f24**

1. There were several permissions issues installing gems. Should I run `ruby bin/setup` as `sudo`? When I tried that method I was warned against using `sudo` as it could make the application not work for non root users.

2. I received the error `PostgreSQL needs to be installed before setup can be completed.` Do I need to install PostgreSQL on my host machine? It's my understanding PostgreSQL runs entirely in docker. Perhaps I misunderstood the purpose of the `docker-compose.override.yml`, I assumed the `POSTGRES_USER` and `POSTGRES_PASSWORD` were arbitrary credentials that I should come up with, but maybe I'm supposed to install PostgreSQL on my host machine first and have those credentials refer to the host PostgreSQL credentials?

Clarification and recommendations on the above issues would be appreciated.

Running Apple silicon, Big Sur 11.6.1

**Comment by kueda** [comment]
I don't have an M1 to test this on, but I know @erebuseternal had to do some tweaking to get it to work, so you might want to check out https://github.com/erebuseternal/inat_setup for pointers on running the Rails app in its own Docker container.

If for some reason your not having trouble compiling dependencies and it's really a permissions issue, you might want to try RVM:

```bash
curl -sSL https://get.rvm.io | bash -s stable
cd inaturalist
rvm use
ruby bin/setup
```

**Comment by erebuseternal** [comment]
@rawcomposition feel free to reach out to me. Getting things setup on my M1 was pretty intense which was why I shared the repo @kueda just mentioned.

**Comment by rainhead** [comment]
The errors in OP's log suggest they might have missed the `rvm use` command, since bundler is trying to install to system directories. This is not affected by running on an m1 machine.

To anyone finding this wanting to run on an m1 machine, the only thing I had to do was to switch to a postgis docker image built for arm64:
```
inaturalist main % cat docker-compose.override.yml
version: "2"
services:
  pg:
    container_name: pg
    image: ghcr.io/baosystems/postgis:13-3.3
    environment:
      POSTGRES_USER: inaturalist
      POSTGRES_PASSWORD: inaturalist
```
I haven't done much with it yet, but it appears to be working. It's PostgreSQL 13 instead of 12, but I don't think that will be a problem. 14 is too new for the current database schema.

**Comment by kueda** [comment]
Going to close this since it's stale and I think all staff devs are can run the docker setup on Apple silicon. Please reopen if anyone's still experiencing the problem in the OP.
