### ISSUE TITLE
@-mentions in Notes section of uploader doesn't generate a notification

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3401]
From 

1. In the web uploader, add a new observation and @-mention someone.
2. Submit the observation.
3. That user is never notified.

Expected behavior: user(s) I @-mention in the notes section of a newly-submitted observation should be notified.

**Comment by tiwane** [comment]
@-mentioning someone in the Notes when making a new obs in iOS and Android does generate a notification.

**Comment by pleary** [comment]
I'm having trouble replicating this. I can mention users and they get notifications. Dashboard updates are cached for up to 15 minutes, so it may take a little bit to show on the dashboard, but the header notification should come through quicker. Are there other conditions that make them not show for you?

**Comment by tiwane** [comment]
I posted [this observation](https://www.inaturalist.org/observations/125087040) then logged in as testtonytest and waited close to half an hour, refreshing testtonytest's dashboard a few times. No notification ever came through. 

<img width="609" alt="image" src="https://user-images.githubusercontent.com/15896181/177653706-859d3179-1521-4853-bd42-8d7176a3c090.png">
