### ISSUE TITLE
Creating a new trad project with a required obs field puts it in weird limbo state

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3402]
This has to be done via a non-staff account, I think. I used inatstafftestaccount

1. Start a new traditional project.
2. Add a place to it
3. Add an observation field and make it required
4. Save the project

The new project is really weird. See this example: https://www.inaturalist.org/projects/test-bfw-3

When logged in as the project creator:

- I see no option for making a journal post:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/15896181/157996062-519cfb2d-c547-4401-b619-b91f4175548b.png">

- when I go to the [Members page](https://www.inaturalist.org/projects/test-bfw-3/members), I'm not listed as a Manager:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/15896181/157996126-7a265b76-2516-44f6-b2c2-f66a5d431fa7.png">

- I can edit the project but I can't delete it:

<img width="317" alt="image" src="https://user-images.githubusercontent.com/15896181/157996144-aef68948-3d90-45a7-982a-e1ab24226863.png">

Someone else said they can't invite users to their invite-only project.

**Comment by tiwane** [comment]
Related forum threads:

https://forum.inaturalist.org/t/writing-a-journal-post-not-possible-in-traditional-project/30271/
https://forum.inaturalist.org/t/problem-creating-a-custom-project-list-for-a-traditional-project/29683
https://forum.inaturalist.org/t/invites-for-a-traditional-project/30161

**Comment by jwidness** [comment]
When I was testing for the custom project list, I'm pretty sure I didn't have a required observation field or a place.  My recollection is that I just created a new traditional project and I was admin, but not curator/manager, and didn't have list editing privileges.

**Comment by tiwane** [comment]
Thanks Jane. Doing some more testing, it seems like anytime I make a new traditional project and add a rule before creating the project, it causes these issues. If I make a new project without any rules, it's created fine and I can add rules later.
