### ISSUE TITLE
Add Identify keyboard shortcut to play observation's sound

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3419]
From: https://www.google.com/url?q=https://forum.inaturalist.org/t/on-the-identification-screen-create-a-shortcut-key-to-play-the-first-sound-file-for-the-observation/30156

If one wants to play an observation's sound in the Identify modal, one has to use a mouse. Request is to add a keyboard shortcut to play the first sound of an observation. Ken-ichi suggested SPACE rather than CMD+P to not confuse it with the Print command.

**Comment by grfeller** [comment]
Hello, I have a possible approach for this request, but would like to check my understanding before creating a PR. (I am new to React/Rails.)

**Desired behavior**

1. User opens `Identify` view and selects an observation with one or more associated sounds.

![f1-io-wsnd](https://user-images.githubusercontent.com/16858088/202496440-c8f97646-05d9-40da-bc42-2873711560e2.png)

2. User presses `Space` and the first sound is played. If the sound is already playing, it will pause.

3. User toggles Keyboard Shortcuts and sees mapping for the `Space` key.

![f1-ks-pfs](https://user-images.githubusercontent.com/16858088/202491772-53f8b4ba-ea57-4bb8-b06d-50adcd2c8c13.png)

**Implementation questions**

On my development system, I created a new `action` called  `togglePlayFirstSound` :

```
export function togglePlayFirstSound( ) {
  return ( ) => {
    const player = $(".obs-media .sounds").find("audio:first")[0];
    if ( !player ) { 
      return; 
    }
    if ( player.paused ) {
      player.play( );
    }
    else
    {
      player.pause( );
    }
  };
}
```

Does this seem like a reasonable approach? (The jquery to get the audio element seems a little brittle to me,) 

Thanks in advance for any suggestions for improvement,

**Comment by kueda** [comment]
@grfeller that looks good to me. FWIW, whether you use jQuery or `getElementBy*`, I don't think there's another way to manipulate those dom elements. Maybe you could use a ref with the React `<audio>` component and control it with state, but that seems much more brittle to me.

My only additional request would be that in addition to playing the sound, you focus on the `<audio>` element. That way people can TAB to the next audio element, and someone using a screen reader will have a little more control.
