### ISSUE TITLE
When using a network node to make a new place, allow users to choose parent places from anywhere

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3423]
Currently, if you're signed in to a network node (eg iNatNZ) and you make a new place or edit an existing one, you can _only_ choose a parent place from that network node's country. This seems unnecessarily restrictive and I think we should allow users on network nodes to make places that have parents from anywhere in the world.

**Comment by kueda** [comment]
I believe this was once the desired behavior, particularly for NZ, though there might have been more of a priority on https://www.inaturalist.org/places/search than on pages like places/new. Have you confirmed that this is actually what the New Zealanders want?

**Comment by carrieseltzer** [comment]
I'll ask

**Comment by tiwane** [comment]
@carrieseltzer did you ever hear back about this?

**Comment by carrieseltzer** [comment]
No, I emailed again with you both on the thread.

**Comment by mjon** [comment]
Hi. Thanks for the prod @[carrieseltzer](https://github.com/carrieseltzer). I don't remember being fussy about this. (Maybe I've mellowed with age?) I'd certainly not have any objections to removing this restriction. I'd be surprised if Colin minded either. Thanks for asking.

**Comment by tiwane** [comment]
Working for me.
