### ISSUE TITLE
Add taxon photo changes to Taxon History

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3436]
Sometimes edit wars break out on taxon default photos. Motivations are probablly myriad - trolling, wanting to have their own photo be the default photo, differences of opinion, etc. Either way, since no one but staff can see which accounts have edited taxa default photos, it makes any sort of meaningful discussion practically impossible. 

So we should include default photo edits in Taxon History, to increase transparency and accountability and to allow people to communicate with each other about taxon photos. 

At minimum we should record which user made changes to taxon photos (actually re-ordered, added, or removed photos then saved changes) and when they did it. It would also be good to add an optional explanation field before saving. 

It would be cool to also include which photos were added or removed, as long as it doesn't end up being too unwiedy to display.

**Comment by kueda** [comment]
Are you asking to record changes only to the default photo, or to all taxon photos?

**Comment by carrieseltzer** [comment]
Preferably all taxon photo changes, IMO.

**Comment by tiwane** [comment]
Agree, all taxon photos.

**Comment by tiwane** [comment]
Updated title to be more accurate.
