### ISSUE TITLE
User's locale affecting AM/PM of some observations

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3437]
From https://forum.inaturalist.org/t/incorrectly-shown-time/31450

1. With your account's locale set to English, upload [this photo](https://www.dropbox.com/s/4q1d9y7dbr27std/DSC_3914.jpg?dl=0) via the web and give a location of 55.901087, 37.849474 (in the Moscow area).
2. The observation should show the correct observed on time, according to the photo's metadata.
<img width="187" alt="image" src="https://user-images.githubusercontent.com/15896181/166500067-7332dd9f-21b8-4612-b8a9-9145df5caae7.png">
3. Its JSON shows an observed_on_time of `2022/05/01 11:04 PM`
4. Change your account's locale to Russian.
5. Upload the same photo and give it the same location.
6. Observation shows AM (both in Russian and English, here's the English screenshot)
<img width="200" alt="image" src="https://user-images.githubusercontent.com/15896181/166500804-d185167c-0bb0-4a2e-8972-21770ee9f46b.png">
7. Its JSON shows an observed_on_string of `2022/05/01 11:04 вечера`

Weirdly, though, if you upload [this photo](https://www.dropbox.com/s/lst38991462qlu3/DSC_3471.jpg?dl=0) and use 55.902732, 37.848835 for its location it works fine in both English and Russian account locale settings. 

Users's original observations with these photos are at https://www.inaturalist.org/observations/114453949 and https://www.inaturalist.org/observations/114288623.

**Comment by kueda** [comment]
Some questions

1. When you say "The observation should show the correct observed on time" do you mean on the obs detail page, e.g. https://www.inaturalist.org/observations/115012325?
2. When you say, "it's JSON" do you mean https://www.inaturalist.org/observations/115012325.json, https://api.inaturalist.org/v1/observations/115012325, or something else?
3. There is no JSON attribute called `observed_on_time` that I can see, but maybe I'm not using the right parameters. What URL are you looking at when you see that?
