### ISSUE TITLE
In search results at admin/users, link observations number to Explore, not Edit Observations

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3444]
The obs number link at admin/users goes to Edit Observations, but I almost never want to go there, I want to see that user's observations on Explore. So the link should point me to Explore, not Edit Observations.

**Comment by grfeller** [comment]
Hello, all. I am new to iNaturalist/Rails development and would like to check my understanding of this issue before creating a PR.

The following steps/screenshots are based on app behavior on my development system.

When logged in as a user with `admin` privileges:

1. Open a view on `admin/users`

![fig-1-admin-users](https://user-images.githubusercontent.com/16858088/194361661-a8f93c96-800d-453e-a2c6-fd9930595801.png)

**Current behavior**

2. Follow the link in the `obs` column for the `testerson` user (above) and see the  `Edit Observations` view

![fig-2-edit-observations](https://user-images.githubusercontent.com/16858088/194560978-6440e7b3-42f8-4139-99fe-511d75c937ba.png)
 
**Desired behavior**

3. Follow the link in the `obs` column for the `testerson` user and see the `Explore` view

![fig-3-explore-observations](https://user-images.githubusercontent.com/16858088/194361804-38f0fe23-eab3-4295-a085-fd2d52272279.png)

Does the screenshot for `step 3` show the desired behavior? 

**Proposed change**

![diff-change](https://user-images.githubusercontent.com/16858088/194572042-a97e856c-597e-44bf-933d-88ff0a240dbc.png)

Does this change look reasonable? Is there a better approach?
