### ISSUE TITLE
Run SendGrid sync weekly

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3488]
Sometimes people accidentally (as far as I can tell) unsubscribe and if we don't catch it in time they have to wait until the next monthly sync until their update emails are restored. I don't know how taxing the sync is, but it would be great if it could be run every week or more often.

**Comment by kueda** [comment]
Frequency changed in https://github.com/inaturalist/inaturalist-cookbook/commit/9f1e6761910442b2e0598db72c0101f738541a31. Logs also indicate the process may have been failing intermittently with 503 errors recently, so I'm testing some changes to the script on staging. Will try and get these deployed next week.

**Comment by kueda** [comment]
Ok, handled some sendgrid errors in 4538a576bd6135952d632eb0add32ee60a35b4ed and deployed the scheduling change so it runs at 1am every Sunday.
