### ISSUE TITLE
Allow user to set LANGUAGE (not just area) in which common name is displayed

### ISSUE THREAD

**Issue by tomastelensky** [inaturalist/inaturalist#3492]
Currently, there is an issue, that when I go to Settings and set _"Prioritize common names used in this place"_ to _"Czechia"_, but I keep English for the whole UI, the common names are still in English. Many other users from different countries have reported this 3yrs ago: https://forum.inaturalist.org/t/common-name-language-and-place-prioritization/3961

Those taxons have Czech names, but these were not automatically assigned to "Czechia" (which could be done automatically as suggested by this request: https://forum.inaturalist.org/t/run-job-to-associate-translated-common-names-to-places/3964 )

I suggest that the simplest solution would be to allow user to actually **choose the language, not just an area!** Currently it is only possible by changing the language of the whole UI, but that's not preferable (I want to see the UI in the original English).

I started to use and love iNaturalist but this is a hindrance, and it has been unsolved for so long already. Would be really grateful if you fixed this!

**Comment by kueda** [comment]
We use github for technical tasks that a developer can work on, not for feature requests or bug reports that don't have a clear solution. Please use the Forum for that kind of feedback. When you do so, please provide specific, concrete cases, e.g. "My language is set to English, my names place is set to https://www.inaturalist.org/places/czechia, and when I view taxon X I expect to see name Y but instead I see name Z." This sounds more like a case of names not correctly getting associated with places than one of needing to choose separate languages for names and the UI.
