### ISSUE TITLE
Detect and prevent redirect loop on /donate

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3496]
When you visit https://www.inaturalist.org/donate, we redirect you back to https://www.inaturalist.org/donate with some `utm` URL params added so we can track some basic information about the donation like the fact that it came in via the website and it belongs to the default "campaign" on Donorbox. However, some forms of anti-tracking technology, like the Duck Duck Go browser extension, strip `utm` URL params, so in our case that results in an infinite redirect loop and the page never loads. These utm properties are very useful, but not absolutely necessary, so let's not trap DDG users in this loop.

- [x] When `/donate` redirects with `utm` params, include a redirects param that stores the number of redirects it has done, i.e. add `redirects=1` if absent, otherwise increment it
- [x] If `/donate` is about to perform its second redirect, don't redirect and just render the page without the `utm` URL params

**Comment by pleary** [comment]
This should be fixed now. Instead of going with `redirects=1` I made it a boolean since we'll never actually increment, instead we'll prevent the redirect if one has already occurred.
