### ISSUE TITLE
Use OpenStreetMap

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [inaturalist/inaturalist#3510]
Please use OpenStreetMap instead of Google Maps in the iNat map section

**Comment by kueda** [comment]
Please use the [Forum](https://forum.inaturalist.org/) for feature requests and make sure to look for existing threads on the topic. This one is covered at https://forum.inaturalist.org/t/use-openstreetmap-maps/2588. We use Github to coordinate issues that are ready for engineers to work on, whereas most feature requests need to be considered by staff and, if we decide to act on them, turned into specifications. For more info on contributing to this repo see https://github.com/inaturalist/inaturalist/blob/main/CONTRIBUTING.md
