### ISSUE TITLE
obs marked with Evidence of organism=no have infowindows but no markers in explore

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#3514]
As reported to help at iNat, https://www.inaturalist.org/observations/118166656 which is marked as Evidence of organism=no is returned by this search in explore and an infowindow appears for it, but a blue marker does not
https://www.inaturalist.org/observations?nelat=60.17473338922695&nelng=24.94805721970898&place_id=any&subview=map&swlat=60.173265940702265&swlng=24.9429824802528&taxon_id=1289484&user_id=kaupunkilinnut&verifiable=any

Desired behavior is for infowindows and markers to be in sync
<img width="941" alt="Screen Shot 2022-09-12 at 11 16 55 AM" src="https://user-images.githubusercontent.com/598026/189727071-16ff9edd-5b50-4972-81f5-0b5ccfd06b68.png">

**Comment by pleary** [comment]
We have a `mappable` attribute of observations which determines which observations get pins or markers on map tiles. The method considers all observations marked as not evidence of an organism as not mappable, see https://github.com/inaturalist/inaturalist/blob/main/app/models/observation.rb#L3047. We still show the infowindow on hover for these though. What is your preferred change? We could prevent the infowindows from showing on hover, or we could changing how the `mappable` attribute is calculated and reindex affected observations

**Comment by loarie** [comment]
I prefer prevent the infowindows from showing on hover

**Comment by pleary** [comment]
This should be fixed now
