### ISSUE TITLE
Indicating loading status while identifications and comments are saved on obs detail

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3521]
Currently when you add an identification or a comment on obs detail, we update the UI immediately and post the content in the background. This can give people the mistaken impression that their content was saved before it actually was. Instead,

- [x] The new activity item should be grayed out while loading
- [x] A loading spinner should appear over the activity item while it's loading

IMO, a 50% opacity white div with a `.loading_spinner` in it will probably do the trick.

**Comment by pleary** [comment]
I made some changes for this that are on staging if you want to test

**Comment by kueda** [comment]
Cool, replacing the accessory menu button is a good idea, since nothing in there is going to work until the ID is created. I guess the whole thing doesn't have to be grayed out. @abhasinat, this look good to you?

**Comment by pleary** [comment]
I just failed to commit the opacity bit. That's up now too for testing
