### ISSUE TITLE
Whale shark when going to https://www.inaturalist.org/taxon_changes and locale set to Maori

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3523]
1. With your locale set to English, go to https://www.inaturalist.org/taxon_changes It loads fine.
2. Using the footer locale chooser, swith your language to Maori.
3. Page reloads and you see a whale shark error.

I also tested this page with French, Japanease and Chinese (traditional) and the page loaded fine for those langauges. 

User who reported this also got a whale shark after saving a taxon change.

**Comment by pleary** [comment]
The main problem here is the Maori translation file does not include a `:one` option for the pluralization of the [translation key being used here](https://github.com/inaturalist/inaturalist/blob/main/config/locales/mi.yml#L20)

**Comment by pleary** [comment]
I implemented this by defining custom pluralization rules for the Maori locale. I didn't file an issue or make a PR for rails-18n as it looks like they want translations for the locale before you add any custom configuration for the locale. I certainly can't provide translations for Maori, nor am I confident that I understand Maori pluralization rules to create a ticket advocating for them in that repo. So I'm going to close this ticket as I believe the issue affecting iNaturalist is resolved
