### ISSUE TITLE
Agree and Compare buttons block long scientific names

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3524]
See https://forum.inaturalist.org/t/subspecies-name-cut-off-in-identify-modal/8914 and https://forum.inaturalist.org/t/long-taxon-name-cut-off-in-observation-by-compare-button/35394

If one's browser window is narrow enough, the agree and/or compare buttons cut off long scientific names.

**Examples**

Obs detail: https://www.inaturalist.org/observations/133157575

<img width="627" alt="image" src="https://user-images.githubusercontent.com/15896181/193899929-d1a9a1a0-11c1-47b9-bf35-5b3393c44b58.png">

Identify: https://www.inaturalist.org/observations/identify?quality_grade=needs_id%2Cresearch&verifiable=true&taxon_id=721125&locale=en

<img width="558" alt="image" src="https://user-images.githubusercontent.com/15896181/193900097-779abbb0-3301-4158-a07d-86c7d7f58978.png">

**Comment by kueda** [comment]
@tiwane what would you prefer here, an ellipsis?

**Comment by pleary** [comment]
I don't see this happening to the same extent with these two examples anymore. Do you have other examples where this is still happening in either the Observation details page, or Identify? Text can get cut off on very narrow displays when single words are longer than the space available for the name, or after sub-specific rank labels where we're using a non-breaking space, which I'd consider edge cases.

It looks to me like this is resolved when there is an available space to break on (please give examples if that's not the case). If that is the case, I guess my question is: is there anything regarding name wrapping we still want to take action on for this ticket?

**Comment by tiwane** [comment]
Nice! I'm not seeing this any longer either, in Safari, FF, and Chorme. I think we can close this, I can't think of other name wrapping issues at the moment.
