### ISSUE TITLE
Hide serial numbers in EXIF data from public view

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3527]
See https://forum.inaturalist.org/t/serial-numbers-in-exif-data/35153

Some photos include equipment serial numbers, eg `Lens serial number` here: https://www.inaturalist.org/photos/233472508 While unlikely, it's possible the serial number could be used to track someone across different sites (eg iNat and Flickr) and/or be used to make false warranty or theft claims, so we should hide it from public view like we do photo file names.

I tried out a few raw photos from Sony, Nikon, and Canon cameras in RawDigger and the only fields with "serial" in them are 

`Lens serial number`
`Serial number`
`Internal serial number`

so we should hide all of those.

**Comment by todtb** [comment]
I can take a look at this. I'm thinking:
1) Hide the serial number fields in the UI
2) Prevent future extraction of EXIF serial number fields (if possible)
