### ISSUE TITLE
Is the `thin` gem needed for dev?

### ISSUE THREAD

**Issue by frewsxcv** [inaturalist/inaturalist#3528]
https://github.com/inaturalist/inaturalist/blob/3e8715aac1bfe49527e0583cd3035c51321a5b8b/Gemfile#L134

I attempted to get iNaturalist running on my Mac but was having trouble getting the `thin` gem installed because there were frustrating errors with its underlying C dependencies (I can share these errors if you're curious). But it seems like `thin` might not even be required for dev since users can just use Rails' built in server. And if I remove the `thin` requirement, iNaturalist runs just fine. Thoughts on it being moved out of `dev`?

**Comment by pleary** [comment]
I don't think we need a development dependency on `thin`. Puma is the default rails development application server since Rails 5. I can't think of a reason to use thin anymore so I've removed it
