### ISSUE TITLE
Web uploader not parsing filename correctly

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3531]
(I asked @kueda to remove `orange` as a name we should match, so maybe that will fix this when it happens, but for now here's the bug report)

1. Name an image `orange crowned warbler.jpg`. Make sure the image has no keywords in its EXIF that might be interpreted by iNat.
2. Drop image into web uploader.
3. iNaturlist parses the file name and inserts an ID of Citrus × aurantium.

Expected: iNat inserts an ID of the bird _Leiothlypis celata_ based on the file name.

**Comment by rainhead** [comment]
@kueda can I prime my database with taxon names somehow, or is this nontrivial?

**Comment by kueda** [comment]
Hey @rainhead, sorry for not getting back to you, currently failing at vacation. To populate my dev env with taxa, I usually do something like

```ruby
%w(Vulpes Homo Quercus Apis Amanita rosilla bushtit orca panda).each { | name | Taxon.import( name ) }
```

`Taxon.import` should try to import the taxon and add whatever name you used. That's always been enough for my uses, but if you wanted to get fancier you could write a script that scrapes this data from the iNat API.

**Comment by rainhead** [comment]
On my computer, the taxon name is "Orange-crowned Warbler". The name search in `Taxon.tags_to_taxa` is case-insensitive, but does not allow "orange crowned" to match "orange-crowned".

If this is indeed the issue, the easiest way to address it is by doing additional normalization of the taxon names in the database, and updating `taxon_names_lower_name_index`. More complicated solutions might include switching to PostgreSQL's full text search, or perhaps ElasticSearch—I notice if I type "orange crowned warbler" in the site search bar, I get the right bird.

**Comment by rainhead** [comment]
Somewhat related: https://forum.inaturalist.org/t/taxon-searches-with-right-single-quotation-mark-instead-of-apostrophe-dont-work-on-ios/38085

**Comment by kueda** [comment]
I think further normalization of names in the db is actually going to be more complicated than an ES-based approach to adding more possible taxa to choose from in `Taxon.tags_to_taxa`, as the index is designed to solve these kinds of normalization problems.

@tiwane, can you confirm that the uploader is no longer applying identifications of _Citrus_ × _aurantium_ to photo files titled `orange crowned warbler.jpg`? I'm up for ensuring that such files get identifications of _Leiothlypis celata_ if someone wants to attempt an ES-based approach, but I also think this is closable if the Uploader has stopped doing the wrong thing.

**Comment by tiwane** [comment]
Yes, I'm not seeing that happen for `orange crowned warbler.jpg`.
