### ISSUE TITLE
Explore: Fullscreen map view button doesn't work

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3541]
From https://forum.inaturalist.org/t/full-screen-function-doesnt-respond/36767/2 I can replicate in FF 106.0.1

1. Go to https://www.inaturalist.org/observations?place_id=any&subview=map
2. Click on the fullscreen button
3. Nothing happens

Probably linked to boundary drawing tool implementation.

Here's a console shot:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/15896181/198504084-58c5c517-d517-4a21-bcbe-012ac10d5307.png">

**Comment by tiwane** [comment]
Potentially related: the "find my location" button is not working. If you click on it (and you're allowing iNat to access your location) you get a pop-up saying it failed to find your location. 

Console from Firefox:

<img width="990" alt="image" src="https://user-images.githubusercontent.com/15896181/198689357-632e1d6f-1d31-4915-aad5-de92eff1fe2f.png">

**Comment by pleary** [comment]
The fullscreen functionality should be restored in 7891e9ee.

I can't replicate the "Find your current location" failure in any browsers I have installed (Chrome, Brave, Safari, and Firefox on Mac OS 12.6). I get a prompt asking if I want to grant location access to the browser. If I accept it zooms to my location, and if I deny it says "Failed to find my location". Do you see the prompt? Do you have other permissions settings in your computer's OS that prevents the browser from access location information? Does it fail in all browsers or just Firefox?

**Comment by tiwane** [comment]
Missing step: make sure Location Services are turned off for your device... Works fine now, sorry about that.
