### ISSUE TITLE
Automate YIR generation

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3554]
Automatically run `YearStatistic.regenerate_defaults_for_year`

- [x] On 1 December of every year
- [x] On 1 January of every year
- [x] On every Sunday in December
- [x] At the bottom of global and site YIRs below where it says "Stats generated on DATE", add a new line of text with the same formatting that reads, "Stats will be generated every Sunday in December and on January 1st"

Optionally investigate ways to optimize generation while performing this work en masse.

Context: in the past I've just done this manually, but we should really automate it to guard against sloth and/or holiday-induced food comas.

**Comment by pleary** [comment]
I added two tasks to the production crontab - one for the Sundays, and one for the 1st of the month. I spent a little time trying to get `whenever` to not start a job if there was an existing process matching a pattern, to avoid doubling up when Sunday falls on Dec. or Jan. 1. But it wasn't as straight forward as I hoped, and we won't hit this until 2024, so I bailed and we can just tweak the schedule that year.
