### ISSUE TITLE
For Louisiana, place_county_name column on export page contains no values

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3570]
1. Export some observations from Louisiana. Include `place_county_name` and `place_admin2_name` columns.
2. Open the CSV. `place_county_name` fields are blank, and `place_admin2_name` fields contain the correct county/parish names.
3. Try the same thing in other states (I tried some in Arizona and California). Both columns include the county name. 

We should make sure that `place_county_name` works for Louisiana.

**Comment by kueda** [comment]
I'm guessing there's some literal lookup based on `place_type` instead of `admin_level` that's not working in Louisiana because they have parishes, not counties.

**Comment by pleary** [comment]
This should be fixed. I addressed it by making methods like `place_county_name` use their previous behavior, which is looking up the `county` place by looking at Place.place_type - but if no results are found, and the place type is also an admin level, fall back to looking up the place by admin level. I am seeing `place_county_name` populated for exports of observations from Louisiana now
