### ISSUE TITLE
Add observation_created_at to DeletedObservation

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3601]
It might help investigate some reports of deleted observations if we knew when the observation was created, not just when it was deleted, so `observation_created_at` in the `deleted_observations` table would store the value of `observation.created_at`.

- [ ] add the `observation_created_at` datetime column to `DeletedObservation`
- [ ] set its value to `observation.created_at` when the `Observation` gets deleted and the `DeletedObservation` gets created

**Comment by todtb** [comment]
#3603 should address this
