### ISSUE TITLE
String missing or incorrect for project addition error

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3604]
From https://forum.inaturalist.org/t/missing-text-in-pop-up-box/38070 I can replicate.

1. Go to an observation by a user who had project addition restrictions (eg [kueda - ](https://www.inaturalist.org/observations/144737850)
2. Attempt to add that observation to a project they don't belong to.
3. Pop-up says `[object Object]`

**Comment by rainhead** [comment]
Perhaps implicated: https://github.com/inaturalist/inaturalist/pull/3398/files#diff-d2b5da88588d5d1089548ee9dc7a98d40a81b234dea79697d97699c837bc5cbfL90-R90

**Comment by pleary** [comment]
This seems to be fixed now
