### ISSUE TITLE
Place search struggles with place names starting with Á

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#361]
For example, pasting
Área de Protección de Flora y Fauna Laguna de Términos
into the iNat place search field here
http://www.inaturalist.org/projects/apff-laguna-de-terminos-campeche/edit
can't find it

Changing the place name to 
Area de Proteccion de Flora y Fauna Laguna de Terminos
'fixes' it

**Comment by pleary** [comment]
Fixed in 9fd8056557df87cca4278255e4f875370a6dd3ca
