### ISSUE TITLE
Don't delete all data related to a user acount on account deletion

### ISSUE THREAD

**Issue by kroeckx** [inaturalist/inaturalist#3613]
It seems that recently one or more accounts got deleted, see https://forum.inaturalist.org/t/the-vanishing-of-a-fellow-inatter/38221. There seem to be 2 things that people want:
- We want to keep as much data as possible
- People have the right to be forgotten

As far as I understand, people grant a license to use the provided data, so I think we can actually keep things like observations and determinations. But if the user requests data to be deleted, we should at least delete all that is considered Personally Identifiable Information, which will include things like the account name and email address. It might also include things like the location of an observations.

It would be good that we can come to some agreement on what an acceptable solution is to keep as much data as possible.

**Comment by kueda** [comment]
Not opposed to development on this front, but we use Github for issues that are ready to work on, not feature discussion.

**Comment by kroeckx** [comment]
Where should this be discussed? I don't think the forum is the right place to discuss that.
