### ISSUE TITLE
Unable to filter for all rights reserved photos

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3630]
See: https://forum.inaturalist.org/t/cannot-filter-for-observations-with-all-rights-reserved-photos/18160

I'm unsure if this is a bug or intended, but some forum users said that `license=none` and `photo-license=none` params used to work when searching for all rights reserved photos. It's not possible to use those now, though, nor do `license=false` and `photo-license=false`. Can we make those work in the URL at least, if not add as an option to the UI?

Use case: some user want to find unlicensed photos so they can contact the observers and ask them to change the license or allow them to use the photos.

**Comment by kueda** [comment]
Can you be more specific about where on the site you're talking about? You can filter for licensed photos at https://www.inaturalist.org/observations, https://www.inaturalist.org/taxa/36204-Sceloporus-occidentalis/browse_photos, maybe elsewhere.

**Comment by tmesaglio** [comment]
via Explore. The dropdown options for licensing include all options **except** for all rights reserved
![image](https://user-images.githubusercontent.com/48739968/214969045-de53c2f9-baeb-4244-a188-00b188b855ed.png)

and directly editing the URL here doesn't work either

**Comment by pleary** [comment]
The observations search page previously supported a `photo_licensed` boolean parameter, and now additionally supports a `licensed` boolean parameter for observation licenses. Setting to false in either case returns only all rights reserved content, e.g. https://www.inaturalist.org/observations?photo_licensed=false, https://www.inaturalist.org/observations?licensed=false . No additional UI has been added

**Comment by tmesaglio** [comment]
perfect, thanks Patrick

**Comment by pleary** [comment]
I'm going to close this as the ability to filter is there. If someone wants to request updating the explore page UI, please open a separate ticket
