### ISSUE TITLE
Make taxon page map filters "sticky"

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3633]
See https://forum.inaturalist.org/t/option-to-always-show-gbif-data-on-maps/12451

Currently if I choose to add or remove map filters on a taxon page, eg

<img width="738" alt="image" src="https://user-images.githubusercontent.com/15896181/215222307-dd985cc8-735e-4c52-901e-0d091a5838ce.png">

then go to another taxon page, my choices for filter go back to the default:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/15896181/215222394-d66c62dd-8ed5-4e5b-b846-5d61921f416f.png">

Request is to have those choices remain until I change them.

**Comment by dartar** [comment]
I just discovered this functionality on the iNat forum and I wish I had known a GBIF observation layer existed, amazing! Making the filter selection sticky sounds a no brainer, but if this is not stored in user settings the selection would likely be only browser or device specific, correct? Have you considered:

- turning the GBIF layer on by default
- adding a user preference to make the preferred layer selection persistent _across browsers and devices_

I would also recommend using a more accessible color scheme for the GBIF layer. I don't have visual accessibility issues but the colors for verifiable observations and GBIF data are nearly indistinguishable especially in aggregate / when not zooming in the map to visualize individual points.

**Comment by rainhead** [comment]
Happy to take this if no one is already on it.
