### ISSUE TITLE
De-prioritize blocking in Account Settings

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3635]
In line with #3634, Account Settings currently display blocks and mutes side-by-side with blocks to the left, as if they were equivalent and blocks were slightly favored, when we would actually much prefer that people using mutes before they try a block. At the same time, blocks are necessary, so we're not trying to bury them out of existence (they're already pretty buried).

- [x] Change the layout of the Relationships section of Account Settings so Mutes and Blocks are on separate rows and the Blocks section appears after Mutes
- [x] When you try to mute someone, add a confirmation dialog with the title "Are you sure?" and the body "Muting someone prevents you from being notified about any of their activity, including "@" mentions, messages, or comments and identifications on your observations." (same text as in #3634). There should be a "Cancel" button that closes the dialog, and a "Mute" button that actually executes the API request.
- [x] When you try to block someone, add a confirmation dialog with the title "Are you sure?" and the body "Blocking prevents any communication between you and another user. It is for situations where another user may put your safety at risk, like stalking or other abusive behavior." There should be a "Cancel" button that closes the dialog, and a "Block" button that actually executes the API request.

**Comment by Mayuresh0072** [comment]
@kueda Hello, I want to work and contribute on this issue, please assign me this issue. Thanks.

**Comment by kueda** [comment]
Welcome, @Mayuresh0072! I assigned you, looking forward to seeing your work. FYI, you can find info about setting up a dev environment and how we like to name issue branches at https://github.com/inaturalist/inaturalist/blob/main/CONTRIBUTING.md

**Comment by Mayuresh0072** [comment]
@kueda Hey, can u tell me how to setup environment for windows . I had gone through contributing guide, but setup steps are only given for mac and linux. Thank You.

**Comment by kueda** [comment]
@Mayuresh0072, sorry I can't help you with Windows as I don't have a good way to run that OS and no one on our team uses it. You might be able to follow the [instructions for setting up Docker on Windows](https://docs.docker.com/desktop/install/windows-install/) and then following [our Docker setup instructions](https://github.com/inaturalist/inaturalist/blob/main/CONTRIBUTING.md#using-docker).

**Comment by kueda** [comment]
@Mayuresh0072 are you still planning on working on this? This is a pretty high priority for us that we'd like to get done soon, so if you don't plan on getting started this week, please let us know so we can un-assign you. If you're looking for another Javascript-focused issue to try, you might consider https://github.com/inaturalist/inaturalist/issues/3343

**Comment by kueda** [comment]
Alrighty, looking forward to your PR!

**Comment by Mayuresh0072** [comment]
@kueda Hi kueda, I had done my enviroment setup. When I created admin user for myself using the command provided - bundle exec rails r "admin = User.create!( login: 'admin', email: 'admin@localhost', password: 'adminpassword', password_confirmation: 'adminpassword' ); admin.roles << Role::ADMIN_ROLE" , and when I login into local website , it is telling me to verify the link through email to proceed further. So, can you please help me and tell how to login in local environment website?

**Comment by kueda** [comment]
@Mayuresh0072 open the console, find that user record, and confirm it, so something like `User.find_by_login( "admin" ).confirm`. I'll try and update the setup instructions tomorrow (we just started requiring email confirmation for new users in December).

**Comment by Mayuresh0072** [comment]
@kueda Thanks for the help.I have figured out the login problem. I am working on creating a dialogue box for mute and block. But I am not getting user list to test mute and block , i think this is because I have not run the Inaturalist API. When I tried to run make service for API  , I am getting following error. Please can you look at it and tell me how to fix it? Thank You.
![make_service_InaturalistAPI_error](https://user-images.githubusercontent.com/112636659/220989161-c50a8e7a-0106-4d44-8908-28bd887170ec.png)

**Comment by kueda** [comment]
@Mayuresh0072 you're probably running an older version of node. Make sure you're running the version specifified in the `.nvrmrc` file. If you use nvm (and we highly advise doing so), you should be able to run `nvm install` and `nvm use` to do this.

**Comment by Mayuresh0072** [comment]
@kueda I am not able to find .nvrmrc file in iNaturalist API. I am using node version 16.13.2 and i also tried to install it again using commnads -nvm install 16.13.2 and nvm use 16.13.2.  I am still getting the same error.

**Comment by kueda** [comment]
[It's in the repo](https://github.com/inaturalist/iNaturalistAPI/blob/main/.nvmrc) so if you don't have it locally perhaps you deleted it. Make sure your copy is up-to-date and you haven't deleted any files. FWIW, it looks like you're using Docker to run the API, so make sure you've followed ever step of the [Docker setup instructions](https://github.com/inaturalist/inaturalist/blob/main/CONTRIBUTING.md#using-docker), including making your own copies of `docker-compose.override.yml` and `config.js` in the API directory.

**Comment by Mayuresh0072** [comment]
@kueda Hi, I got that file. I am using the same version which is mentioned in the file,still there is error. So, I tried setting environment in other laptop ( M1). There I am  getting  error with installing gems in this command  - CFLAGS="-Wno-error=implicit-function-declaration" bundle. If possible, can we please talk on some platform like discord and help me to set up this enviroment. Thanks.

**Comment by kueda** [comment]
@Mayuresh0072, send me a [DM on iNat](https://www.inaturalist.org/people/kueda) with an email address and I'll invite you to our Slack channel for external developers.

In the meantime, I'm going to unassign you from this issue because we want to get it done this week. If you're still interested in contributing, leave a comment on https://github.com/inaturalist/inaturalist/issues/3343 and I'll assign you.

**Comment by Mayuresh0072** [comment]
@kueda I am not able to to message you on iNaturalist website, it says "must have three verifiable observations or three identifications for others to do that". mayureshwani789@gmail.com   -  this is my email id, please invite me to the slack channel and i will try to work on other issues.

**Comment by kueda** [comment]
Done! But also, you should really add at least three observations or identifications if you're going to work on iNat so you have some experience with what we're making.
