### ISSUE TITLE
Taxon links page: display comments just  below "created by"

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3638]
eg https://www.inaturalist.org/taxon_links/5840/edit

The instructions on the right push down the comments section so that it can't be see (I didn't know it existed...). This might cause someone to edit or remove it without seeing any important comments made.

<img width="850" alt="image" src="https://user-images.githubusercontent.com/15896181/215912892-00fba8f9-f1e4-4225-a096-44526365df73.png">

**Comment by todtb** [comment]
I'll take a look, hopefully a quick fix.
