### ISSUE TITLE
Small formatting issue on /identifications/username in Chrome

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3658]
From 

Using Chrome or Brave, got to https://www.inaturalist.org/identifications/tiwane You'll see the obs photo is above the obs taxon:

![image](https://user-images.githubusercontent.com/15896181/219797412-8a3225a2-a4d2-4f01-b1b3-0a1651f72dfa.png)

It should be to the right of the obs taxon (screenshot from Firefox): 

<img width="562" alt="image" src="https://user-images.githubusercontent.com/15896181/219797530-8ea55f0e-e1b5-4cf5-81a0-ab325fcc31e3.png">

**Comment by tiwane** [comment]
Same thing for notifications drop-down, when mousing over a notification:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/15896181/219797799-0a1363a7-f7fe-4618-865b-24b4cbd7d4e5.png">

**Comment by Kildor** [comment]
The problem is caused by `float: inline-end;`, which [is supported](https://caniuse.com/mdn-css_properties_float_flow_relative_values) only by firefox and last safari TP.
![image](https://user-images.githubusercontent.com/1320579/219828802-d7de3ee3-0a07-420a-a3b3-a060703a888e.png)
