### ISSUE TITLE
On emails, change URL for "Update subscription preferences" link

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3664]
See: https://forum.inaturalist.org/t/transactional-emails-not-available-for-toggle-in-web-interface/39379

Right now "Update subscription preferences" goes to https://www.inaturalist.org/users/edit, which can be confusing and involves another step of clicking "Notifications". We can instead send them directly to the Notifications page by using https://www.inaturalist.org/users/edit#notifications for that link instead. 

Howver, https://www.inaturalist.org/users/edit#notifications only works if one is already logged in to iNat. Is it possible for us to take them to that page when they log in?

**Comment by todtb** [comment]
@tiwane - From what I can tell, this anchor tag `#notifications` is never sent to the server and only applies on the client side when the page is loaded. What that means is a path is stored for the redirect once the user is logged in (`/users/edit`).

I think one option would be to change the email link to something like `/users/edit?notifications=true` which the server _WILL_ receive and can process as a redirect and I can start working on a PR for that.
