### ISSUE TITLE
Mismatch in observations per user

### ISSUE THREAD

**Issue by chleeb** [inaturalist/inaturalist#3680]
Hi,

there is a issue in the repository of the R-package `rinat`, that might be more linked to an issue in iNaturalist: 
https://github.com/ropensci/rinat/issues/55
In short, a request for all observations of an user results in the wrong number of observation:
User hannelore13 should have 7 observations (https://www.inaturalist.org/observations?user_id=hannelore13), but when requesting the data via API (as done by `get_inat_obs_user` in `rinat`) I get only 1 observation:
http://www.inaturalist.org/observations/hannelore13.json?&per_page=200&page=1
Also 
http://www.inaturalist.org/observations/hannelore13?&per_page=200&page=1
shows only 1 observation.

Is there any kind of filter I don't see/consider?

Best,
Christoph

**Comment by kueda** [comment]
Hi Christoph.

1. https://www.inaturalist.org/observations?place_id=any&user_id=hannelore13 shows 7 observations for me. You might want to check your default place filter if you're signed in when viewing that URL
1. https://www.inaturalist.org/observations/:username was always duplicative as an API endpoint, and is currently really only intended for viewing your own observations. I realize we have [some docs](https://www.inaturalist.org/pages/api+reference#get-observations-username) that don't explain this, so I can try to update those.
1. www.inaturalist.org `.json` endpoints are not the way we recommend you retrieve data. You might suggest to the rinat maintainers that they use api.inaturalist.org instead to retrieve faster and more schematically more consistent responses, e.g. https://api.inaturalist.org/v1/observations?user_id=hannelore13, which yields `total_results: 7`
