### ISSUE TITLE
Translation code showing on listed taxa edit page

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3689]
From https://forum.inaturalist.org/t/place-species-tab-translation-missing-span-element-rendered-as-text-on-species-details-at-least-for-english-and-french/40016

eg https://www.inaturalist.org/listed_taxa/94803447

<img width="310" alt="image" src="https://user-images.githubusercontent.com/15896181/224845326-e1851070-bc23-4583-8ba8-d9a79147c9dd.png">

**Comment by kueda** [comment]
Not sure when this got fixed it doesn't seem to be happening anymore.
