### ISSUE TITLE
Run a script to clean up duplicate and erroneous lexicons

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3693]
Per today's web meeting and https://forum.inaturalist.org/t/clean-up-currently-available-lexicons/12453 

@kueda said he has a script to clean up duplicate and erroneous lexicons, so we should run it and automate it.

**Comment by kueda** [comment]
Made numerous changes to the script in 4647d322b3a02f26a8b0fae0a6f5b7f4d31d6761, just the cleaning ran it successfully, and scheduled a job to run it every month before we generate the taxonomy DwC-A that contains the `VernacularName` files

**Comment by Optilete** [comment]
Frisian->West Frisian
