### ISSUE TITLE
Clicking "edit" on just about any taxon in the Brazil checklist results in whale shark

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3694]
1. Go to https://www.inaturalist.org/check_lists/7213-Brazil-Check-List
2. Click "Edit" for just about any taxon that page and you'll get a whale shark.

**Comment by kueda** [comment]
FWIW, the immediate problem of that page not loading is fixed, but the underlying problem of listed taxa existing without lists is not. I'm going to close this, but if anyone has repro steps for how listed taxa can exist without lists, please holler.
