### ISSUE TITLE
Users without organizer privileges can get to place creation page

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3700]
1. Use an account that lacks organizer privileges.
2. Go to inaturalist.org/places and search for a place at "Find a place".
3. On the results page, you'll see this on the upper right-hand side:

<img width="283" alt="image" src="https://user-images.githubusercontent.com/15896181/225747676-ba10c4a7-dbed-4073-a2fc-3445e3bc62b5.png">

4. That link takes you to the place creation page, but if you try to save your new place you'll hit and error that says you don't have organizer privileges.

Since users without organizer privileges can't actually make a new place, we should remove that link for non-organizer users. 

TODO

- [x] Remove "Not finding what you want? [Add a New Place](https://www.inaturalist.org/places/new)" text and link from `/places/search` if they do not have the organizer privilege
- [ ] `PlacesController#new` should redirect the user back if they don't have the organizer privilege (I think we just need to add `:new` to `requires_privilege :organizer, only: [:new, :create, :edit, :update, :destroy]`)

**Comment by Mayuresh0072** [comment]
Hello @kueda , Please assign me this issue . Thanks.

**Comment by Mayuresh0072** [comment]
@pleary @kueda As we have discussed in the slack, I think 2nd todo task is not needed, as it is already redirecting it to current page if user manually types URL and go to place creation page. There is no way user is goes to place creation page.  Just the thing is we need to correctly display the error message if user manually tries to open place creation link. Just a suggestion,  I think we should create a different issue for this task.
