### ISSUE TITLE
Live iNaturalist web app is using the development build of React

### ISSUE THREAD

**Issue by mattf96s** [inaturalist/inaturalist#3708]
**Describe the bug**
React is running in development mode on the live domain.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to an observation page.
2. Load the React Dev tools browser extension.
3. You can use the dev tools.

**Expected behavior**
The live domain uses the production build of React to avoid importing unnecessary bundles as well as avoiding the double render enforced by React Strict mode in development.

**Screenshots**
![image](https://user-images.githubusercontent.com/68327846/227884527-cacf7c58-5788-4934-a623-927dc4b4ce59.png)

**Context**
 - OS: MacOS Ventura 13.2.1 (22D68)
 - Browser: chrome
 - Version:  111.0.5563.110 (Official Build) (arm64)

**Additional context**

**Comment by Optilete** [comment]
Forum topic that might be related: https://forum.inaturalist.org/t/website-using-development-build-of-react/38620
