### ISSUE TITLE
Include more new place restrictions on https://www.inaturalist.org/places/new

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3712]
We receive emails from users who try to make a new place but their boundary contains too many observations and/or covers too large of an area. Those two restrictions are not publicly visible, so it leads to confusion and emails to help@inat and post on the forum.

I suggest we add the following two restrictions to the large yellow banner at https://www.inaturalist.org/places/new, under "Please keep in mind the following restrictions:"

- new places cannot contain over [200,000 observations](https://github.com/inaturalist/inaturalist/blob/main/app/models/place.rb#L205) ([10,000 during a content freeze](https://github.com/inaturalist/inaturalist/blob/main/app/models/place.rb#L206))
- new places cannot cover an area larger than X sq. km (about the size of Texas)

(I don't know the exact area limit)

**Comment by rainhead** [comment]
Taking a look, but in a bit over my head.
