### ISSUE TITLE
Identify: Sort by UI shows incorrect value when order=asc

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3717]
From https://forum.inaturalist.org/t/identify-modal-cannot-remove-sort-by-ascending-filter/40437

1. Go to https://www.inaturalist.org/observations/identify By default, obs are sorted Descending by Date Added
2. Change sort to Ascending, which gives you https://www.inaturalist.org/observations/identify?order=asc and shows you oldest observations first (using added on date)
3. Go to Filters and you'll see it still shows Descending

<img width="177" alt="image" src="https://user-images.githubusercontent.com/15896181/229367342-fd063442-6d48-4426-b7df-1353d2649dca.png">

4. Choose Ascending again. Nothing happens. UI still shows Descending

**Comment by Manishpandey11** [comment]
Hi @kueda 
I want to work on this issue. Can you please assign it to me?

**Comment by ShlokJswl** [comment]
Hello @kueda can I work on this issue since this is unassigned? I have already started setting up the dev environment.

**Comment by kueda** [comment]
Sure, @ShlokJswl. Are you all part of a class or something?

**Comment by Maxhou00** [comment]
Hello,

I have made a [PR](https://github.com/inaturalist/inaturalist/pull/4111) for this issue

**Comment by pleary** [comment]
Fix has been merged and deployed. Thanks @Maxhou00!
