### ISSUE TITLE
Let non-curators see (but not edit) the taxon names page

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3735]
Currently, only curators, site admins, and staff can see the /taxa/[taxon number]/names page (eg https://www.inaturalist.org/taxa/12937/names). That means if someone is investigating a question they have about a name, they can't see which places the name is associated with, and where it "ranks" in priority for both global use and place name preferences. 

We should make this page viewable by any user, but still only editable by curators, site admins and staff, so I suggest:

- [ ] Making the "Manage Names" button viewable for non-curators, but it should read "Common Names Chart" or something that doesn't indicate the user can alter anything.
- [ ] Non-curators should be able to see the list of names but not interact with them, so for those users we need to remove the "edit" links and make sure the names are not draggable.
- [ ] Change the text at the top to:

Taxa can have many common names. We support one default common name globally, which curators can change here by dragging a name to the top of the list. Curators can also specify default names in different places by editing the name and adding a place, but please only do this when different places have conflicting names.

**Comment by Mayuresh0072** [comment]
Hello @kueda , Please assign me this issue. Thanks.

**Comment by pleary** [comment]
We decided to handle this not by letting non-curators access the edit page, rather move the regional names to the names tab on the taxon page
