### ISSUE TITLE
Taxon page: match observed-on date display for Latest Observation with observation's geprivacy

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3736]
Currently, the taxon page shows the month, day, and year of the observed-on date for the "latest" observation of a taxon, eg 

<img width="218" alt="image" src="https://user-images.githubusercontent.com/15896181/232915032-256ad311-0ceb-477b-90a4-1e4e2af6f844.png">

It does this regardless of an observation's geoprivacy setting. Elsewhere on the website we only show the month and year for obscured and private observations, so we should do that here for observations with obscured and private geoprivacy.

**Comment by thatkaiguy** [comment]
Hello! I created a PR for this linked above.

Separately.. what's the best way to seed some test data for my development environment?

**Comment by kueda** [comment]
Thanks, @thatkaiguy, we'll take a look at your PR soon. Regarding seed data, you should have basic taxonomic data in your db if you followed the setup instructions, but you can add more taxa with `Taxon.import()`, e.g. `Taxon.import( "Homo sapiens" )`. For other tools, including stuff for content other than taxa, check these out:

* https://github.com/inaturalist/inaturalist/blob/main/tools/development_tools/import_taxon_from_production.rb
* https://github.com/inaturalist/inaturalist/blob/main/tools/import_place_from_production.rb
* https://github.com/inaturalist/inaturalist/blob/main/tools/load_production_controlled_terms.rb
* https://gist.github.com/kueda/33141cd50135f7b50a17df1bd3810629

**Comment by thatkaiguy** [comment]
I think this issue can now be closed
