### ISSUE TITLE
Feature Request: Multi-Lingual Support for Species' Common Names

### ISSUE THREAD

**Issue by MichalTorma** [inaturalist/inaturalist#3765]
Hello iNaturalist team,

I am writing to request a feature that I believe will enhance the user experience for multi-lingual individuals such as myself. I am a Slovak who often works with Latin species names in Norway and the dominant working language is often English.

At present, the iNaturalist app only displays the common name of a species in a single language. I find myself having to juggle different languages when trying to identify species, which can be quite challenging and confusing.

To help streamline this process, I propose a feature that allows displaying multiple common names of a species simultaneously. The user could be able to select their preferred languages from the settings, and then see the species' common names in all selected languages whenever they identify a species. This would essentially create a side-by-side comparison of the common names, aiding users in learning and memorizing species across languages.

This approach would significantly reduce the mental burden of switching between languages, and help users like me to consolidate our knowledge of species in different languages. Furthermore, this feature could potentially make the app more accessible and user-friendly for a wider international audience.

Thank you for considering this feature request. I strongly believe it would greatly enrich the iNaturalist app, and I look forward to hearing your thoughts on this suggestion.

Best regards,
Michal

**Comment by kueda** [comment]
Thanks for the suggestion, Michal. Please use the Forum to request new features, and check to see if someone has already requested what you want before starting a new topic (in this case, [someone has](https://forum.inaturalist.org/t/display-common-names-in-multiple-languages-on-taxon-labels/9378)).

In other news, we are working on a feature like this! It will launch on the website first, but we hope to figure out how to incorporate it into the apps once we work out the problems on the web.
