### ISSUE TITLE
Explore circle drawing tool - Places of Interest not working

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3769]
From https://forum.inaturalist.org/t/places-of-interest-misbehaving-when-using-circle-drawing-tool/42324 I can replicate.

1. Go to Explore page
2. Use the circle drawing tool to draw a circular boundary
3. Once Places of Interest reloads, click on it. 
4. The places listed are not related to the boundary that was drawn. They're places written in Cyrillic script.

eg here's what I see after [drawing a circle in the Bay Area](https://www.inaturalist.org/observations?lat=37.704238244856974&lng=-122.14402194205248&place_id=any&radius=16.353239108043645&subview=map):

<img width="550" alt="image" src="https://github.com/inaturalist/inaturalist/assets/15896181/7254b9fc-2b89-4740-8f7d-95e8ebef35e0">

**Comment by tiwane** [comment]
(the rectangle drawing tool appears to be working fine)

**Comment by rainhead** [comment]
- With a circular selection the frontend issues a nearby places query with `lat` and `lon` set, but no radius.
- The API does not expect these parameters and tries to bail: https://github.com/inaturalist/iNaturalistAPI/blob/main/lib/controllers/v1/places_controller.js#L84-L88
- The calling code incorrectly detects the bail (`undefined` vs `null`) and issues an unconstrained query for all places: https://github.com/inaturalist/iNaturalistAPI/blob/main/lib/controllers/v1/places_controller.js#L154

I think this just never got implemented.

One option is to always pass `swlat`, `nelng`, etc, but to also pass the shape to the API. I haven't looked at the ES API to see whether a circular query is an option.
