### ISSUE TITLE
Make arrow keys work on photo browser zoom 

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3771]
https://forum.inaturalist.org/t/arrow-keys-to-move-between-images-in-browse-photos/42258

On both taxon pages and taxon photo browser pages (eg https://www.inaturalist.org/taxa/55048-Trichodes-apiarius and https://www.inaturalist.org/taxa/55048-Trichodes-apiarius/browse_photos), you can click on a photo to zoom in. On each side of the photo are arrows you can click on to go to the next photo:

<img width="1286" alt="image" src="https://github.com/inaturalist/inaturalist/assets/15896181/6b6a4385-1236-4c31-b0e1-25f13bb690f1">

We should make it so the right and left arrow keys can also move between photos.

**Comment by jwidness** [comment]
Just to copy over what's on the forum -- the arrow keys used to work (implemented in 092007d), I'm guessing they broke with 543b39f
