### ISSUE TITLE
ModeratorActions for all comments

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3800]
At present, ModeratorActions can only be created for comments and identifications in React-based interfaces, e.g. on obs detail. For identifications this is sufficient because they must be associated with observations, but comments can be associated with a variety of models, and people performing moderation duties need to be able to hide inappropriate comments in all places where comments appear, so we would like to add a Rails-based tools for creating ModeratorActions for comments

## GET `/comments/:id/hide`
- [x] Add GET `/comments/:id/hide`
- [x] It should render a form that POSTs to `/moderator_actions` to create a `HIDE` action for that comment
- [x] The form should include a preview of the comment
- [x] The form must contain a `textarea` for the reason attribute that enforces `ModeratorAction::MINIMUM_REASON_LENGTH` and `ModeratorAction::MAXIMUM_REASON_LENGTH`
- [x] The form should include the same warning text we do on obs detail (`hide_desc`)

## `shared/activity_item` partial
- [x] Add an option to "Hide" in the mouseover controls if the authenticated user is a curator, and link that to the new `/comments/:id/hide`
- [x] If a comment is hidden and the viewer can see it (viewer is an admin, viewer is a curator, or viewer is the person who created the comment), the meta row show "Content Hidden" and the `fa-eye-slash` icon like we do on obs detail
- [x] If a comment is hidden and the viewer cannot see it, the "Content Hidden" notice and the timestamp are all that should be visible (no user icon, no username, etc.)
- [x] When a user clicks the "Content Hidden" notice, a popover should appear that includes everything it does on obs detail:
  - [x] Who hid the comment
  - [x] When the comment was hidden
  - [x] The ModeratorActions `reason`
  - [x] Link to flags on the comment
  - [x] If the viewer is the author of the comment, a link to /help

**Comment by kueda** [comment]
> Is this for any user? Right now if a user is not a curator they don't see anything if they click on "Content Hidden" on obs show.

I don't think that's the case. When I go to https://www.inaturalist.org/observations/156791372 while signed out, I can see a comment was hidden, and when I click "Content Hidden" I see the popover. We can remove that if you like, but that seems to be the way it works now.

**Comment by tiwane** [comment]
OK, I can see the popover now. I think it's fine to keep.
