### ISSUE TITLE
Compare numbers out

### ISSUE THREAD

**Issue by portedison** [inaturalist/inaturalist#3809]
**Describe the bug**
I know there is a disclaimer on the compare page, that it might be broke but thought you might be interested here.

When comparing a project id (opawaho-heathcote-river-bank-vegetation) the numbers for Silver Fern (Cyathea dealbata) are 6 in Opawaho, this should be 1, I'm not sure where the number 6 is coming from.

**To Reproduce**
1. Visit

https://www.inaturalist.org/observations/compare?s=eyJxdWVyaWVzIjpbeyJuYW1lIjoiQ2hyaXN0Y2h1cmNoIiwicGFyYW1zIjoicGxhY2VfaWQ9NDA0NjkmdGF4b25faWQ9Mzk5NDY0LDEzMTY2OSw3MDIzMCwzNDE2OTAsNDAxMDIyLDQwMTAxMiwzNjY2NTMsMTk3MDU2LDQwMTAzMCw0MDEwMzEsMzY2NjU4LDM2NjY2MSwzNjY2NjIsNDAxMDUwLDQwMTA1Myw1MDE5MSw1MjM5MCwxMjU5MjcsMTIyNzExLDM2NjYxMCwzNjY2MTksNzAyMjgsMjAwODQzLDQwMjQxNCw0MDI1MjksMjEwMTY1LDU0Njk5LDQxMTEzNywzNjY2OTAsMTk3MDYzLDIxMDk0Niw3MDI0MCwzMzYzMzgsMTg1MjQ5LDc4NTkxLDM2NjYyOCw4NTI3NSwxMzU1MDYsMTI2MTgxLDU0NjI5LDcxMDU0LDM2NjcwOCwyMTA5NDcsMzY2NjM2LDczODc2MCIsImNvbG9yIjoiIzFmNzdiNCJ9LHsibmFtZSI6Ik9wYXdhaG8iLCJwYXJhbXMiOiJwcm9qZWN0X2lkPW9wYXdhaG8taGVhdGhjb3RlLXJpdmVyLWJhbmstdmVnZXRhdGlvbiZ0YXhvbl9pZD0zOTk0NjQsMTMxNjY5LDcwMjMwLDM0MTY5MCw0MDEwMjIsNDAxMDEyLDM2NjY1MywxOTcwNTYsNDAxMDMwLDQwMTAzMSwzNjY2NTgsMzY2NjYxLDM2NjY2Miw0MDEwNTAsNDAxMDUzLDUwMTkxLDUyMzkwLDEyNTkyNywxMjI3MTEsMzY2NjEwLDM2NjYxOSw3MDIyOCwyMDA4NDMsNDAyNDE0LDQwMjUyOSwyMTAxNjUsNTQ2OTksNDExMTM3LDM2NjY5MCwxOTcwNjMsMjEwOTQ2LDcwMjQwLDMzNjMzOCwxODUyNDksNzg1OTEsMzY2NjI4LDg1Mjc1LDEzNTUwNiwxMjYxODEsNTQ2MjksNzEwNTQsMzY2NzA4LDIxMDk0NywzNjY2MzYsNzM4NzYwIiwiY29sb3IiOiIjZmY3ZjBlIn1dLCJ0YWIiOiJzcGVjaWVzIiwidGF4b25GaWx0ZXIiOiJub25lIiwidGF4b25GcmVxdWVuY2llc1NvcnRJbmRleCI6MCwidGF4b25GcmVxdWVuY2llc1NvcnRPcmRlciI6ImFzYyIsIm1hcExheW91dCI6ImNvbWJpbmVkIiwiaGlzdG9yeURhdGVGaWVsZCI6Im9ic2VydmVkIiwiaGlzdG9yeUxheW91dCI6ImNvbWJpbmVkIiwiaGlzdG9yeUludGVydmFsIjoid2VlayIsImNvbG9yU2NoZW1lIjoiY2F0ZWdvcmljYWwifQ%3D%3D

2. Click on Silver Fern (Cyathea dealbata) / Opawaho (says 6)

3. Confirm that the value should be 1.
https://www.inaturalist.org/observations?project_id=opawaho-heathcote-river-bank-vegetation&taxon_id=131669

**Comment by jwidness** [comment]
It's including 5 Casual observations. 

![image](https://github.com/inaturalist/inaturalist/assets/13769652/cf8bc817-c817-469a-95de-f838cdd6f97c)

If you add `&verifiable=true` to the compare string, you get the expected value of 1.

![image](https://github.com/inaturalist/inaturalist/assets/13769652/768740f4-1b3a-4a9e-83d4-cba79cddbc80)


Also, just a note that the developers have requested that bugs be reported on [the forum](https://forum.inaturalist.org/) rather than on github.

**Comment by portedison** [comment]
Too good. Thanks!
