### ISSUE TITLE
Link to Wikipedia for hybrid taxa is malformed

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3813]
From https://forum.inaturalist.org/t/broken-links-to-wikipedia-when-x-is-in-the-url-presumably-may-affect-other-special-characters/43371

1. Go to a hybrid taxon's page, like https://www.inaturalist.org/taxa/411276-Forsythia---intermedia
2. Under the About tab, click on the Wikipedia link
3. You're taken to https://en.wikipedia.org/wiki/Forsythia_Ã_intermedia which has no page on Wikipedia. The taxon's page is at https://en.wikipedia.org/wiki/Forsythia_%C3%97_intermedia

Tony

**Comment by muster-mark** [comment]
@tiwane I think you copied the display text of the link from the inaturalist form. You are actually taken to https://en.wikipedia.org/wiki/Crocosmia_%C3%83%C2%97_crocosmiiflora

`decodeURIComponent("%C3%83%C2%97"); // "Ã\u0097"`

Note the invisible "END OF GUARDED AREA" character which is invisible (and even then is not present in your post above).

**Comment by rainhead** [comment]
The arrow link to Wikipedia at https://www.inaturalist.org/taxa/411276-Forsythia---intermedia is correct:
```
<a href="https://en.wikipedia.org/wiki/Forsythia_%C3%97_intermedia"><i class="icon-link-external"></i></a>
``` 
Did this bug get fixed in the last month?

**Comment by rainhead** [comment]
Fixed by https://github.com/inaturalist/inaturalist/pull/3838.
