### ISSUE TITLE
Identify: map for previous observation shows when new observation is loaded in the modal

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3828]
I'm able to pretty consistently trigger this. 

1. Open the Identify modal.
2. Go to the Suggestions tab and select a suggestion (source doesn't seem to matter), then immediately hit the right arrow to go to the next observation
3. See a flicker and the map for the previou sobservation is shown on the next observation. It does not change or update if you do nothing.

https://github.com/inaturalist/inaturalist/assets/15896181/df8f61c8-e95d-40c4-bb8a-8709fb73b734

**Comment by pleary** [comment]
hopefully this is fixed now, with no additional issues introduced by this change
