### ISSUE TITLE
Small change to Identify keyboard shortcuts text

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3833]
When one hits `a` on the Identify modal, the agreement is with the Observation Taxon, not the Community Taxon, which some users don't know. 

- [ ] Change text on shortcuts pop-up to say
 
![image](https://github.com/inaturalist/inaturalist/assets/15896181/4c7f23ba-2130-4889-bbd3-f9db902eb7aa)

- [ ] Add an FAQ explaining the difference between Observation Taxon and Community taxon

**Comment by pleary** [comment]
I pushed a change to update the text for the label. Where is the FAQ that needs to be updated? Is that in a page we'll update after deploying?

**Comment by pleary** [comment]
this text has been updated on Identify
