### ISSUE TITLE
Create legend for toggling windshaft map layers

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#385]
Similar to how the GBIF layers are toggled on taxon/show, we'd like a good UI for toggling the windshaft layers on/off wherever they are shown. The toggle applies to both grids and point-level layers (i.e. when grids are off points are also off).

**Comment by pleary** [comment]
I have a version of this on Staging now using the existing GBIF Overlay toggle. It would be good to get confirmation the labels and descriptions used for the different layers - all observations, taxon range, place, observations featured. It's also worth taking a look at the guides card view which has pretty narrow maps and squeezes the text in the layer toggler. I even removed the map type selector there to make it all fit

**Comment by kueda** [comment]
Looking good. More things:

1. Change "Place Layer" to "Place boundary"
1. "Taxon Range Layer" to "Taxon Range"
1. "Observations Layer" to "Observations of this taxon" (assuming that's always what it is)
1. Scientific name in the taxon range layer byline should be italicized if it's a species or genus (species and genus names should always be italicized). If that's annoying I'm fine just skipping that byline.
1. Byline needs to be indented so it's flush with the layer title. Right now it's too far left:

![screen shot 2015-01-13 at 10 39 46 am](https://cloud.githubusercontent.com/assets/22691/5726489/8ac386d0-9b10-11e4-877b-89ed49a84953.png)

In general my habit has been to capitalize the first word only in labels. I reserve capitalizing all words for titles.

**Comment by pleary** [comment]
OK these changes are done and I made a pull request #421 . Pushing this to Staging now
