### ISSUE TITLE
DwC-A should not have data files without meta.xml entries

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3862]
Per https://github.com/globalbioticinteractions/globalbioticinteractions/issues/427#issuecomment-1703189698, when we use the `make_api_all_taxon_data` method, we just write a `taxa.csv` file into the archive without describing what it is and what its fields are in `meta.xml`. Instead, I think we should treat it like an extension to the observation core so it gets described in `meta.xml`.

There's also a lot of refactoring we could do in `archive.rb`, e.g. `make_descriptor` and `make_descriptor` both seem to contain a lot of logic that could be moved into the extension classes, but maybe that's out of scope.

**Comment by pleary** [comment]
I just focused on the ticket title and not the refactoring. I removed the `make_api_all_taxon_data` method and associated archive option since we aren't using it anymore. I'm not aware of other files that will get created that aren't documented in meta.xml
