### ISSUE TITLE
Timeout when searching for users in admin page

### ISSUE THREAD

**Issue by sylvain-morin** [inaturalist/inaturalist#3865]
When using the user search feature in admin page (ex: /admin/users?q=sylvain), the following query is executed:
`SELECT * FROM users WHERE login ILIKE "%sylvain%" OR name ILIKE "%sylvain%" OR email ILIKE "%sylvain%" OR last_ip LIKE "%sylvain%"`

This query, using wildcards, can't benefit from any index, and so is very heavy for the database (we got some monitoring alerts on prod db related to it). It can take several minutes, leading to timeouts in the web application (error 504).

Proposed solutions:

1) First, please use this user search feature on staging when possible, instead of prod.

2) We could rework this feature to have an exact search (no wildcard) and a "like" search (with wildcard)
The exact search will be a lot faster thanks to the indices.
However, there won't be any improvement for the current "like" search.

3) We could use Elasticsearch for this feature, instead of the database.
`name` and `login` are currently available in the user elastic index.
We should add `email` and `last_ip` with particular attention to this sensitive information.

**Comment by kueda** [comment]
I definitely support hitting the ES index on `login` and `name` first, either directly or using `InatApiServce` (the latter might help to exactly match the header search results.) If that fails we can perform individual db queries on `email` or `last_ip` without the leading wildcards, e.g. `ILIKE 'sylvain%`.

One thing I don't understand is why a query like `select id, login from users where login ilike 'sylvain%'` seems to be performing a seq scan. There's a btree index on the login column. Would [operator classes](https://www.postgresql.org/docs/current/indexes-opclass.html) help?
