### ISSUE TITLE
Switch YIR publications to GBIF literature endpoint

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3869]
We're currently hitting https://www.gbif.org/api/resource/search but while that works, it doesn't seem to be officially supported anymore, so we should switch to https://www.gbif.org/developer/literature.

**Comment by thatkaiguy** [comment]
I took a stab at this and have a WIP pr here https://github.com/inaturalist/inaturalist/pull/3887 but I do have a question..

Between the two endpoints, the responses seem to be the same except for the `_gbifDOIs` key. In the new response, the 'gbifDOI' is found in the returned 'tags'.

[non official api example call](https://www.gbif.org/api/resource/search?contentType=literature&gbifDatasetKey=50c9509d-22c7-4a22-a47d-8c48425ef4a7&limit=50&literatureType=journal&year=2020)

results in:
```javascript
"_gbifDOIs": [
  "doi:10.15468/dl.ruflo8"
]
```

[official api example call](https://www.gbif.org/api/resource/search?contentType=literature&gbifDatasetKey=50c9509d-22c7-4a22-a47d-8c48425ef4a7&limit=50&literatureType=journal&year=2020)

results in:
```javascript
  "tags": [
    ...,
    "gbifDOI:10.15468/dl.ruflo8",
  ]
```

The returned string has a different prefix also `doi:` vs `gbifDOI:`.

Does this prefix matter? I'm not familiar with what uses this value

My spec currently fails with
```
Diff:
       @@ -1,4 +1,4 @@
       -"_gbifDOIs" => ["doi:10.15468/dl.rwjrbf"],
       +"_gbifDOIs" => ["gbifDOI:10.15468/dl.rwjrbf"],
```

**Comment by kueda** [comment]
Thanks for your work on this so far, @thatkaiguy.

> Does this prefix matter?

Yes. These DOI get used at https://www.inaturalist.org/stats/2022#publications, where each publication has links to these GBIF data DOIs via https://dx.doi.org. This lets people confirm that iNat records were included in the data export that paper cited. However, note that https://dx.doi.org/doi:10.15468/dl.rwjrbf redirects correctly, but https://dx.doi.org/gbifDOI:10.15468/dl.rwjrbf does not, so we should not store that gbifDOI prefix unless we update the frontend code too... which will break Year In Review for past years, as the generated data is static. That prefix is not really necessary, though (https://dx.doi.org/10.15468/dl.rwjrbf redirects just fine), so I would actually just remove it. That will allow those dx.doi.org redirects to work and won't mess with how the frontend code works.
