### ISSUE TITLE
Update taxon ancestry denormalization when taxa are modified

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#389]
This currently happens daily. If we can get this to be near real time then we can start using this table for lots of other things. There are some slow delayed jobs whose performance can be greatly improved by using taxon_ancestors, but not until we know that table has the latest ancestry data. Ideally, changes to taxonomy also update taxon grid denormalization as well #388 (for example if a species is split we'd want that to be reflected in the grids ASAP).

**Comment by loarie** [comment]
cool - I understand now, this IS happening daily, and the aim here is to have it happen real time. Thanks
