### ISSUE TITLE
Observation Detail: display coordinates in a more easily copyable way

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3897]
From https://forum.inaturalist.org/t/easily-copy-coordinates/39278/

On observation detail, change the way we display coordinates so that they're easily copy-and-pasteable:

![image](https://github.com/inaturalist/inaturalist/assets/15896181/45510547-b306-4cbe-84af-9757ac53b01d)

**Comment by LucaProvencal** [comment]
@kueda Hi, I'm interested in working on this. If it's up for grabs please let me know. I also agree with the discussion in the forum of adding a button to copy the coords.

**Comment by kueda** [comment]
Go for it, @LucaProvencal. I'm up for adding a copy button too if you want to try that.

**Comment by kueda** [comment]
Hey @LucaProvencal, I've unassigned you from this issue since you haven't pushed any work on it in a few months.

**Comment by LucaProvencal** [comment]
@kueda Apologies, I found the place in the code to change this, but tried building the project locally and failed. Definitely keep me unassigned, if I have some time in the future I'll try to pick it back up.

**Comment by tiwane** [comment]
At today's web meeting, we decided we'd like to both display the coordinates in an easily copyable fashion, like in thefirst post here, and also add a Copy button next to them. @abhas, any thoughts?

**Comment by pleary** [comment]
an attempt at this has been deployed. Coordinates should be easier to highlight and copy. We also added a copy button that will show a tooltip saying users can click to copy, that'll show feedback when clicked that the coordinates have been copied. The displayed coordinates are truncated to fixed 5 significant digits, but when using the copy button the raw unmodified coordinates are copied
