### ISSUE TITLE
don't put obs research grade when CID doesn't = obs.taxon

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#3918]
When "Based on the evidence, can the Community Taxon still be confirmed or improved?" vote is no, don't kick an obs into RG from need_id unless the CID = obs.taxon

https://www.inaturalist.org/observations/62240849
<img width="819" alt="Screenshot 2023-10-29 at 9 29 40 PM" src="https://github.com/inaturalist/inaturalist/assets/598026/20ff183e-fb56-4914-9ff8-1329b5742c79">
<img width="1196" alt="Screenshot 2023-10-29 at 9 29 30 PM" src="https://github.com/inaturalist/inaturalist/assets/598026/43dfa710-8748-4d51-8342-ad127db034b1">
<img width="663" alt="Screenshot 2023-10-29 at 9 29 36 PM" src="https://github.com/inaturalist/inaturalist/assets/598026/5cf399fb-dca3-4afe-b899-de45aedb2ac9">

**Comment by jwidness** [comment]
Isn't this the same as #3321 ?

**Comment by loarie** [comment]
good call thanks
