### ISSUE TITLE
ID/Compare modal not honoring Scientific Name(Common Name) Preference

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3931]
See https://forum.inaturalist.org/t/id-compare-modal-not-honoring-scientific-name-common-name-preference/46627

1. In Account Settings, set your preferences to Scientific Name (Common Name).
2. Open up Suggestions in the Compare or Identify modal and tap on a taxon.
3. Scroll down to that taxon's taxonomy chart.
4. Scientific names are displayed after common names.
5. 
![image](https://github.com/inaturalist/inaturalist/assets/15896181/3e315be1-a77b-4cb6-a457-6ce27f58bf6c)

**Comment by Maxhou00** [comment]
Hello,

Here is a [PR](https://github.com/inaturalist/inaturalist/pull/3937) I worked on for this bug.
