### ISSUE TITLE
Remove the Log In option from our Freshdesk page

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3932]
I'd like to get rid of this Log In option, we don't need people to create new help.inaturalist.org accounts on Freshdesk.

<img width="556" alt="image" src="https://github.com/inaturalist/inaturalist/assets/15896181/97ec5663-8cc7-4b8e-807b-6aabe0a47d8b">

**Comment by pleary** [comment]
Login button should hidden now
