### ISSUE TITLE
Not all observations in Atlas of Living Australia (ALA) are displaying the ALA badge

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3933]
Eg https://www.inaturalist.org/observations/142614830 It's [in ALA](https://biocache.ala.org.au/occurrences/b536b378-4ba2-4921-be43-38e5404804c3), but there's no badge. 

I don't think this is an issue of delayed badgeification like with GBIF, this observaiton has been RG with those licenses for about a year now. And it could be an issue on ALA's end and not with us.

**Comment by pleary** [comment]
See also #3065

**Comment by pleary** [comment]
All ALA occurrences should be properly linked to iNaturalist observations now
