### ISSUE TITLE
Add iNatHelp to Translators YIR chart

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#3945]
We started https://crowdin.com/project/inathelp in 2023. The site it translates isn't quite live yet, but we should incorporate contributions to that project in our [translators chart](https://www.inaturalist.org/stats/2023/#translators). I think we might be using an outdated API for that, so this might not be trivial.

**Comment by Optilete** [comment]
I missed the iNatHelp column in https://www.inaturalist.org/stats/2024/#translators
