### ISSUE TITLE
Try to get the right regional variant Wikipedia page for users with a Chinese (traditional) locale

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3947]
Chinese wikipedia pages (eg https://zh.wikipedia.org/zh-tw/%E7%99%BD%E8%8A%B1%E9%AC%BC%E9%92%88%E8%8D%89) are available in multiple regional variants (eg Hong Kong or Taiwan), but we're not fetching that. Is there a way we can do so?

**Comment by kueda** [comment]
To clarify a bit, if your iNat account is set to use zh-TW and you go to https://www.inaturalist.org/taxa/1095846-Bidens-alba, you should see the Wikipedia content from https://zh.wikipedia.org/zh-tw/%E7%99%BD%E8%8A%B1%E9%AC%BC%E9%92%88%E8%8D%89, not https://zh.wikipedia.org/wiki/%E7%99%BD%E8%8A%B1%E9%AC%BC%E9%92%88%E8%8D%89

**Comment by tiwane** [comment]
I think this can be closed.
