### ISSUE TITLE
Disappearing photo connection to flickr when editing observation

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/inaturalist#395]
I was editing this old observation: http://www.inaturalist.org/observations/38813/edit - which previously had a picture of a hawk, linked from Flickr. I linked over to flickr to get the date and add it, because somehow i forgot to do that when i created the observation. The tab somehow froze up and i got the fail whale and then when I reloaded the photo was disconnected. Unfortunately my flickr account is a huge mess so i can't get it back without sorting through a million old photos. I probably won't bother since no one could ID the hawk anyway... but it seemed worth reporting the bug. It's the second time it happened, but the first time i had a link to the flickr photo so i just readded it.
Sorry, this isn't the best description, but maybe someone else has had it happen to them too

**Comment by kueda** [comment]
Charlie, is #379 pretty much the same as this, and if so can you close this, please?

**Comment by naturalistcharlie** [comment]
Hmm, I don't think so. This was my own observation. When you look at your photo's details on iNat, there is a connection to Flickr if the photo is from Flickr. I clicked that link to open flickr in a new tab and for some reason that caused the photo to delete from my iNat observation. The photo wasn't removed from flickr as described in 379, it was removed from iNat. 

Make sense? It's hard to explain and I didn't do the best job. It also didn't happen every time and thus is hard to replicate.

**Comment by kueda** [comment]
Do you mean you clicked the Flickr URL on http://www.inaturalist.org/photos/1397662 and that seemed to disassociate the photo from your observation on iNat? Or you clicked "View original by Charlie Hohn on Flickr" when viewing the photo popup on http://www.inaturalist.org/observations/38813 and that resulted in the disassociation? Either is pretty mystifying. Those are just links, and should cause an any alteration of data.

**Comment by naturalistcharlie** [comment]
I am pretty sure it was the former.  And yeah, it doesn't make any sense to
me either.  I suppose it may have been a fluke but I think it happened at
least one other time.  It also caused the fail whale.  Maybe it slowed down
and i hit stop and reload or something... but i don't see how that would
get rid of the photo either.

On Sun, Jan 11, 2015 at 7:50 PM, Ken-ichi <notifications@github.com> wrote:

> Do you mean you clicked the Flickr URL on
> http://www.inaturalist.org/photos/1397662 and that seemed to disassociate
> the photo from your observation on iNat? Or you clicked "View original by
> Charlie Hohn on Flickr" when viewing the photo popup on
> http://www.inaturalist.org/observations/38813 and that resulted in the
> disassociation? Either is pretty mystifying. Those are just links, and
> should cause an any alteration of data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/395#issuecomment-69520516>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by kueda** [comment]
Clicking https://www.flickr.com/photos/inyo395/6336171338/ could not cause the fail whale, or do anything on iNat. When you click on a link to another site, your browser sends a request directly to that site and does not tell iNat anything (though I think Google Analytics might be informed). If you clicked "Repair broken URLs," that could definitely do weird stuff, but it doesn't sound like that's what you did.

I'm going to close this b/c I don't know how to diagnose it with the information I have at hand, but if you can come up with a repeatable list of steps, or even a non-repeatable but explicit list of steps including URLs and exact links you clicked on, please re-open.
