### ISSUE TITLE
Hiding an ID should remove all of its effects on an observation

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3951]
There's been at least on user who's added IDs of auto-obscured taxa to other users' observations to make the observation obscured. Hiding these IDs removes them from the CID, but it still makes the observation obscured. If an ID is hidden, it shouldn't affect anything about the observation.

**Comment by tiwane** [comment]
Also, is it possible to run a script to update IDs that have already been hidden?

**Comment by pleary** [comment]
hidden IDs should no longer impact observation taxon geoprivacy, and any affected observations have been updated
