### ISSUE TITLE
Web Uploader: parse GPS coordinates when they're entered into the location search field of the location modal

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3952]
See: https://forum.inaturalist.org/t/unable-to-update-location-with-lat-long-coordinates/47201 

Since we made some backend changes with Google Maps, users can no longer get a usable result if they enter coordinates into the search field here:

<img width="509" alt="image" src="https://github.com/inaturalist/inaturalist/assets/15896181/de66af24-1355-482d-af8b-afbcd5bf8634">

If possible, we should detect coordinates entered into field and populate the lat/long fields below the map with them.

**Comment by pleary** [comment]
This should be working now. If a user enters valid decimal coordinates in the typical pattern `[-90 to 90],[-180 to 180]` we'll recognize that as coordinates as use them to focus the map, search Google for the corresponding place name, and populate the lat/lng attributes of the observation
