### ISSUE TITLE
Blockee can see observations of blocker on Explore map

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3958]
If you go to Explore and search for obserations of a user who's blocked you, you'll see them on the map view and can click through to them. They should not be viewable.

**Comment by acornmonkey** [comment]
No. It's problematic to implement this. It means that blocked users get inaccurate figures about how many observations there are.

In fact, the existence of the block feature may be problematic too. Honestly, it hinders the whole citizen science thing.

**Comment by pleary** [comment]
To generate different map tiles for every logged-in user would create some performance problems as it would affect our ability to cache map tiles. This is why most places users will see their own observations obscured in map tiles, as we are running the same queries and generating the same tile images for all users. If users could see different tile data based on blocking settings, we'd never be able to cache map tiles for authenticated requests at the load-balancer level. We'd always need the application to process the request and determine if the user is being blocked, and either re-use cached data if they are not, or regenerate the map tiles if they are. This would have big performance implications for things like the main explore page that loads nearly all observations as the queries for those map tiles are very slow.

Could we implement this in a different way that would allow the observations to appear on the map, but address the blocking in the UI? For example in the popup, display a warning that this observation is from a user that has blocked you. That way everyone can still see the same map tiles, but users with blocking constraints see a different presentation of the data for a given observation?

**Comment by tiwane** [comment]
> For example in the popup, display a warning that this observation is from a user that has blocked you.

You mean the popup when one clicks on an observation in the map? I don't think that adds any protection, really. I think I'm OK with resolving this.
