### ISSUE TITLE
Web uploader: Can't edit date on certain photos

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3960]
See: https://forum.inaturalist.org/t/uploading-edited-google-photos-images-from-desktop-results-in-uneditable-nan-values-for-dates/47563 I can replicate with the photo provided.

1. Download this photo, which has been edited on Google Photos, to your computer.
2. Add it to the web uploader. It says invalid date. 

<img width="283" alt="image" src="https://github.com/inaturalist/inaturalist/assets/15896181/5a5d975f-94a2-46e5-a1e9-3b2ee49d0d49">

3. Try to edit the date. You can't. 

<img width="283" alt="image" src="https://github.com/inaturalist/inaturalist/assets/15896181/16420fbc-7c86-4bc0-a356-1c2d11ccc09e">

Even if the date is unreadable we should still allow the user to edit it.

**Comment by pleary** [comment]
this appears to be fixed for the provided image, and hopefully for other images that were leading to "invalid dates"
