### ISSUE TITLE
archive imported photos

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#397]
At present we just store the URLs of photos imported from external providers like Flickr. While this saves some disk and bandwidth costs, it means we lose these photos if/when the external providers change the URLs (e.g. in response to changes in privacy settings), resulting in broken image URLs. Most people seem to expect that when they import a photo to iNat, iNat has that photo for ever, and the actual data gets transferred, so to meet that expectation and deal with a number of related bugs (e.g. #379), let's start importing the actual photo data.

There are a couple ways this could go down technically

1. Ditch FlickrPhoto, PicasaPhoto, and FacebookPhoto and make all imported photos LocalPhotos. We would have to download and convert all existing external photos.
1. Continue letting the photo subclasses work as they do, using the external URLs, but allow them to have a file attachment like LocalPhoto does, and set that with the original photo data when the photo is imported (probably as a background job). Less refactoring, but we would have to periodically check for broken links and fallback to our own image URLs when that happens. We kind of already do that for Flickr, I guess

Thoughts on implementation, @md5 & @pleary? I guess I lean toward 2.

**Comment by kueda** [comment]
Ok, we decided we'd add a new photo type called `RemotePhoto` and adopt something like option 1 above. So now this is looking something like

- [ ] add new `RemotePhoto` subclass of `Photo` that has the same `file` attachment as `LocalPhoto`
- [ ] add `provider_type` and `native_original_image_url` to the photos table
- [ ] create a rake task that goes through every `Photo` with `ObservationPhotos` that is not a `LocalPhoto` and and convert it into a `RemotePhoto`, setting it's `file` attachment and `native_original_image_url` using the `original_url`
- [ ] notify users that we are about to make this change and that anyone with broken images needs to relink their account to inat by date X, otherwise their broken photos will be removed from inat
- [ ] On date X, repair all broken photos
- [ ] once broken photos are repaired or deleted, run the `RemotePhoto` conversion task

**Comment by pleary** [comment]
I ended up ditching `RemotePhoto` and having these be different `subtype`s of `LocalPhoto`. `Photo` will gain `subtype` and `native_original_image_url`. All the subclasses still exist and do everything they used to, but the `ObservationsController` will turn the (unsaved) subclass instances into `LocalPhoto`s with file = remote url. When saved, the photos will be downloaded and processed the same as an uploaded photo. The subtypes can be helpful when needing to re-sync remote metadata or repairing broken photos.

I made `Photo.turn_remote_photo_into_local_photo` for the conversion, but no proper rake task right now. And the list of users with broken photos has been generated (ask me if you need it).

Open question - what do we do about photo uniqueness? Right now if someone tries to (re)attach a remote photo to an observation that is used in another observation, a reference is made to the same photo instance - a new instance is not created. I assume we should keep the same practice? If someone tries to add a `FlickrPhoto`, we should first check for a `LocalPhoto` of subtype `FlickrPhoto` with the same `native_photo_id`, then check for a `FlickrPhoto` with the same `native_photo_id` (until we convert them all), and if we find either we'll use that same instance.

**Comment by kueda** [comment]
> I assume we should keep the same practice?

Yes, unless there's a compelling reason not to.

**Comment by kueda** [comment]
How's this look for a rollout plan:

- [ ] merge in this work and deploy so newly imported photos start getting archived (@pleary)
- [ ] begin migrating all existing photos without broken links (@pleary)
- [ ] create a tool that allows people to fix their existing broken photos (@kueda)
- [ ] email all users with broken photos to ask them to use the fixit tool (@kueda)

First two can happen ASAP, dealing with the broken stuff is pending my work on the fixit tool.

**Comment by pleary** [comment]
looks good to me. I'm working on a few specs and will send a pull request shortly

**Comment by pleary** [comment]
At this point all photos that can be archived have been. The rest are unavailable for one reason or another. Here's the remainder:
```FacebookPhoto => 8230,
FlickrPhoto => 3978,
PicasaPhoto => 956```

All new photos should be coming in as LocalPhotos (I noticed one exception today with an image that was imported as a TaxonPhoto then associated with an observation. I'll keep an eye out for cases like this). I think we're ready to alert the users of the remaining broken photos

**Comment by kueda** [comment]
Emailed all the users with remaining broken photos.
