### ISSUE TITLE
Taxon page: stats are hidden when browser is narrow

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3977]
See https://forum.inaturalist.org/t/taxon-page-stats-hidden-when-browser-window-narrowed/48130

If you narrow the window of a taxon page enough (in my case, half the width of my 1512x982 screen resolution), the numbers on the right-hand side disappear and/or become tiny. eg https://www.inaturalist.org/taxa/174322-Colaspis

<img width="487" alt="image" src="https://github.com/inaturalist/inaturalist/assets/15896181/2dad8f27-4b16-4bac-832c-c4cb7ab3e66c">

**Comment by Maxhou00** [comment]
Hello, 

Made a small [PR](https://github.com/inaturalist/inaturalist/pull/4017) for this bug

**Comment by pleary** [comment]
Thanks!
