### ISSUE TITLE
Capitalize the first word of hybrid genera taxa

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#3988]
See https://forum.inaturalist.org/t/hybrid-genus-name-capitalization-is-automatically-removed/9696

eg https://www.inaturalist.org/taxa/1136625---phyllosasa-tranquillans should be × Phyllosasa tranquillans instead of × phyllosasa tranquillans

**Comment by Maxhou00** [comment]
Hello, 

I created a [PR](https://github.com/inaturalist/inaturalist/pull/4008), for this issue.

As I mention in my PR, it's actually only fixing this issue at the species level as I have seen it in every examples. I don't know if it's important to manage the case for every rank possible.

**Comment by pleary** [comment]
Thanks @Maxhou00. I extended this to taxa with rank `hybrid` as well in 7e35229, since that was the rank of the taxon in the initial comment and there were a few others like it. I also regenerated the names for any taxa that might have been affected. This should be resolved now
