### ISSUE TITLE
Disappearing coordinates when entering multiple records on photo uploader

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/inaturalist#399]
On Photo Uploader (http://www.inaturalist.org/observations/upload) I am entering a bunch of photos that have time info but no GPS info. I put several in from each place so after I enter one record I want to copy the lat lon into the next record. But... if I click in the window of the above record to copy the numbers, they sometimes vanish or change to zero. In fact even just tapping through the second observations' fields to enter it manually can cause this. It doesn't seem to delete the actual data from the observation but it is annoying as it makes it hard to copy over. 
I am using Chrome. Let me know if you can't duplicate it and i will try to describe it in more detail.

**Comment by kueda** [comment]
Pretty sure this refers to the old, defunct uploader, so I'm closing. If this seems like a problem with the current upload interface, please re-open.
