### ISSUE TITLE
When users create species checklists to Places with existing ones, the taxa display multiple times in Compare and Suggestions, and when the location filter is global, they duplicate excessively.

### ISSUE THREAD

**Issue by bdagley** [inaturalist/inaturalist#4027]
Most or all major inaturalist Places already have their own species checklist page, yet also allow users to create their own additional checklists for the pages, which for e.g. many even academic or non profit nature orgs have felt helpful or necessary to do. One of the main benefits of checklists is that a visual list of species suggestions can be viewed in Compare and Suggestions (which helpfully, even includes species that were added to the checklist but haven't been observed on inaturalist yet). 

The problem is that when users create checklists to Places that already have a checklist, the Compare/Suggestions results show duplicates of the taxa, making them much more difficult to use for the sake of identification. Furthermore, when the Compare/Suggestions location filter is set to global (or somehow "clears"/broadens on it's own), the duplicates massively increase in number, making the function virtually impossible to use. Further details about this have also been noted/documented on inaturalist, the inaturalist forum, and elsewhere (this is a known issue to the staff and developers).

Note: when I created this issue, the button seemed to require it be defined as a bug. I am unsure whether this is due to a bug or a mere bug-like issue, but it is a justifiable Issue to report regardless.

**Comment by pleary** [comment]
Duplicate taxa should no longer appear in Identify suggestions
