### ISSUE TITLE
Web banner and modal for unconfirmed users

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#4031]
For any unconfirmed user on any iNaturalist web page, add a green banner at the top of the site styled like this:
![Image](https://github.com/inaturalist/inaturalist/assets/598026/88a769d3-fcf0-4b1d-88a5-266247199a56)

The banner should say:
"Please confirm that [email address] is the best way to contact you. <ins>Click here to resend a confirmation email</ins>"

When the user clicks on the underlined portion, show a modal that says:
"Please click the link sent to [email address] to confirm your email address."

This functionality should be similar to the [existing warning and modal on profile](https://github.com/inaturalist/inaturalist/blob/main/app/webpack/users/edit/components/profile.jsx#L81) that has similar functionality to the banner:
![Image](https://github.com/inaturalist/inaturalist/assets/598026/55337b16-53c6-41ef-878c-61ea15eecac2)
and also similar functionality to the modal:
![Image](https://github.com/inaturalist/inaturalist/assets/598026/cb2f1d5b-ff3a-42c6-b2e1-1d3fa4918f3a)

**Comment by kueda** [comment]
If it's any help, 7776612f26b03d5e05e3971557a89a73b431bae1 was the commit that removed most of this functionality last fall.

**Comment by loarie** [comment]
@abhasinat do we need the underlined link in the banner to open a modal (analogous to what happens in the existing modal on profile) or can the underlined link in the banner just send the email directly? The latter would be easier

**Comment by abhasinat** [comment]
I think a modal is better to allow a user to confirm the email address. Sometimes users misspell their email addresses, and may not realize that if we don't show them the modal.

**Comment by pleary** [comment]
We have some older pages that don't yet implement bootstrap for styles, which makes it very difficult to re-use components build with bootstrap. For example https://www.inaturalist.org/taxa, https://www.inaturalist.org/places. For these older pages could we send the user to their profile page where they can trigger the confirmation resend from there? Or have some other behavior for those pages or everywhere.

Essentially - its not easy to show a consistent modal across all our pages. We can easily re-use the one on the user profile for most pages (the ones the implement bootstrap), but not for the ones that don't implement bootstrap. What should we do to address that?

**Comment by abhasinat** [comment]
I think the solution you proposed sounds good! I don't think a large number of users will click that modal from one of these more hidden, older pages. I imagine the small number that do would click the announcement again on profile and get the modal.

**Comment by tiwane** [comment]
Some accounts, either all or nearly all made via Facebook, have no email address. Right now, they see this:

<img width="603" alt="image" src="https://github.com/inaturalist/inaturalist/assets/15896181/3bbad2a4-0794-478b-ba2f-a7ca3ff25574">

@abhasinat any thoughts on what to show these people? Maybe something like "Your iNaturalist account has no email address. Please add one here so you can reset you password if necessary." and link to their account settings? I feel like password reset is a better carrot than being contacted by iNat.
