### ISSUE TITLE
Curators get whale shark when going to edit page of certain places

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#4036]
From https://forum.inaturalist.org/t/unable-to-edit-community-curated-place/49017/

1. When logged in as a curator, go to https://www.inaturalist.org/places/sfl5mr
2. Click on Edit place.
3. Get whale shark

As a staff member I can load the edit page fine.

Also, these are weird places with one point at 0,0 - would that have something to do with it?

**Comment by pleary** [comment]
This should be fixed now. We require places to have geometries when being created, but I guess some were made before that validation or have since lost their geometry somehow. That was a cause of the error page, which has hopefully since been fixed
