### ISSUE TITLE
Update en strings for controlled terms (annotations) & definitions

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#4046]
In order to improve the quality of plant phenology annotations, these en strings should be updated.

The name "plant phenology" should be updated to the more specific "flowers and fruits", and the term values changed slightly and mouseover definitions updated to clarify that the definitions are about the evidence presented rather than inference about an ongoing process on the plant.
- [ ] Plant Phenology -> Flowers and Fruits
- [ ] No flowers or fruits: No flowers, fruits, or seeds (in whole or part) are visible
- [ ] Flower buds: At least one closed flower bud
- [ ] Flowers: At least one open flower
- [ ] Fruits or Seeds: At least one fruit or seed

A new "Leaves" controlled term should have the following terms and mouseover definitions:
- [ ] Breaking leaf buds: At least one bud with its first new leaf or needle not fully unfolded
- [ ] Green leaves: At least one green leaf or needle (or reddish if this is the normal healthy color)
- [ ] Colored leaves: At least one leaf or needle has late season or drought color 
- [ ] No live leaves: No breaking leaf buds or green or colored leaves or needles are visible

**Comment by pleary** [comment]
I'd like to point out that we'll end up with some very long strings. Our current design on the observation details page says that we don't wrap these strings, which leads to overflow issues. We'll have to add some wrapping to break up these long strings onto new lines. 
<img width="781" alt="Screenshot 2024-03-19 at 4 12 43 PM" src="https://github.com/inaturalist/inaturalist/assets/48566/ed0aa9c6-7b32-49e2-a0f2-7c9aba100399">

**Comment by carrieseltzer** [comment]
I agree about the wrapping. It doesn't look like we'll necessarily need to change anything about the way the mouseover definitions work. They're not ideal since most people don't know they're there, but that can be a separate issue if we decide to deal with it.

**Comment by carrieseltzer** [comment]
I just updated the ticket with clarified terms, values, and definitions.
