### ISSUE TITLE
Update taxon page charts with new controlled terms (annotations)

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#4047]
Update taxon page charts to:

- [ ] Add a new chart tab for "Leaves"

<img width="598" alt="Screenshot 2024-03-17 at 11 00 29 PM" src="https://github.com/inaturalist/inaturalist/assets/7501183/5e98cdfb-3993-41d9-a6e7-fba9c4fb71bf">

**Comment by pleary** [comment]
We're going to hit space issues adding additional tabs, especially with the new longer label for `Flower and Fruit Phenology`. The problem is likely to be even worse in other languages . We should come up with a scalable UI solution if we want to keep adding tabs to that chart .<img width="569" alt="Screenshot 2024-03-19 at 3 54 57 PM" src="https://github.com/inaturalist/inaturalist/assets/48566/921f90f0-467e-48c3-9e64-0f054732ad74">

**Comment by carrieseltzer** [comment]
I see, and using "Reproductive Phenology" or "Flower & Fruit Phenology" doesn't really buy us much more space in English. Looks like either text wrapping within tabs, or scrolling to see more tabs could be solutions. 

We should get input from @abhasinat.

**Comment by abhasinat** [comment]
I think wrapping is a good solution here. I imagine translated languages will need wrapping as well.

**Comment by pleary** [comment]
@abhasinat if you get a chance, it would be great to have a mock-up of what you imagined. I don't think a simple text wrap would be a sufficient long-term solution if we ever wanted to add another term, or another say 10 terms to this chart, and still may not leave enough room in other languages. I think ideally we'd have a UI that accommodates at least one or two more terms. Maybe that means this needs to grow into a new tab on the taxon page or something else? At the very least, even if we just want to wrap the text and call it a day, it would be great to have a mockup of that so the wrapping is added the way you'd prefer. Thanks

**Comment by abhasinat** [comment]
Alrighty here's my solution:

- [ ] Add a title to the graph section
- [ ] change the tabs to be clickable buttons that have active and inactive states and wrap above the graph space
- [ ] Move the gear button and the question mark button down into the graph space

![image](https://github.com/inaturalist/inaturalist/assets/44380775/638c623e-cb33-4f8f-a3e6-e6abf77e925a)
![image](https://github.com/inaturalist/inaturalist/assets/44380775/c0b91768-6e77-4fb2-bab6-408d98c77253)

Here's the details for the spacing _inside_ each button:
<img width="307" alt="image" src="https://github.com/inaturalist/inaturalist/assets/44380775/269a69cf-c6ca-4b4b-895b-e6690f1afb54">

And here's the spacing between each button
<img width="307" alt="image" src="https://github.com/inaturalist/inaturalist/assets/44380775/c1d91555-d4e7-4949-b81d-34455200b93b">
