### ISSUE TITLE
Add keyboard shortcuts for new controlled terms (annotations)

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#4049]
Once the new annotations are added, they'll need keyboard shortcuts. 

Flowers and Fruits
~p then a for Recently fallen or removed fruits (Fresh fruits no longer attached to the plant)~ (decided not to add this)

Leaves
v then b for Breaking leaf buds
v then g for Green leaves
v then c for Colored leaves
v then n for No live leaves

**Comment by pleary** [comment]
This is another section that will get very crowded with new terms. We might consider adding a max-height to this popover panel and allow vertical scrolling if there is too much content. As it stands, if the browse is not tall enough some content will be rendered off screen and there is no way to access it, or easy way to close the panel once you open it. 
<img width="1082" alt="Screenshot 2024-03-19 at 4 27 38 PM" src="https://github.com/inaturalist/inaturalist/assets/48566/7dbc3452-788a-4a48-9cf2-14fbebea9e04">

**Comment by carrieseltzer** [comment]
My biggest concern here is the ability to close the popover. Max-height and scrolling seems reasonable to me, but @abhasinat may want to weigh in before full release.

**Comment by carrieseltzer** [comment]
Updated the keyboard shortcuts above for the simplified changes.
