### ISSUE TITLE
Password Reset Page: don't allow submissions that are not email addresses

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#4066]
We get a decent number of people who say that they don’t receive password reset emails when they use https://www.inaturalist.org/users/password/new. When I check, no password reset email address as been generated, so I suspect at least some of them enter their username, which we allow. If you submit something like "tiwane", you sees this banner:

<img width="919" alt="image" src="https://github.com/inaturalist/inaturalist/assets/15896181/b012e47d-90f7-4df6-a495-f4126fade041">

Which makes you think you entered a proper email address when you haven't.

Instead of allowing someone submit a non-email address, we should run the same check we use at https://www.inaturalist.org/signup and tell them they need to submit an actual email address here:

<img width="241" alt="image" src="https://github.com/inaturalist/inaturalist/assets/15896181/b363884e-e432-4daf-a7d1-ce7ed79913bf">

**Comment by pleary** [comment]
the password reset page is now using the same form validation as signup
