### ISSUE TITLE
Export failing due to PG::TRSerializationFailure

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#4067]
**Describe the bug**
I tried to export some records and the export failed even though it seems like it should work. Maybe a postgres replication problem.

**To Reproduce**
1. Go to https://www.inaturalist.org/observations/export
1. Make an export with the following params:
    *  Query: `quality_grade=research&identifications=any&geoprivacy=open&taxon_geoprivacy=open&iconic_taxa[]=Plantae&place_id=122851&native=true&acc_below_or_unknown=100&spam=false`
    * Columns:  `id, observed_on, url, latitude, longitude, positional_accuracy, scientific_name, iconic_taxon_name, taxon_id, taxon_family_name, taxon_genus_name` 
1. Start the export
1. It will take too long for the page to tell you whether it failed, so check back in a few mins and reload the page
1. Scroll to the bottom. Under "Recent Exports" it will show that your export failed

**Expected behavior**
Exports should work

**Screenshots**
<img width="994" alt="Screenshot 2024-03-28 at 9 50 39 AM" src="https://github.com/inaturalist/inaturalist/assets/22691/2fac5fda-42aa-4e26-8301-1bba35d6dfae">

**Context**
 - OS: MacOS 14.2.1
 - Browser Firefox
 - Version: 123.0.1 

**Additional context**
The [flow task page](https://www.inaturalist.org/flow_tasks/415040) shows a stack trace starting with this:

```
 	ActiveRecord::SerializationFailure :: PG::TRSerializationFailure: ERROR: canceling statement due to conflict with recovery
DETAIL: User query might have needed to see row versions that must be removed.

/home/inaturalist/deployment/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.1.7.7/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `exec_params'
/home/inaturalist/deployment/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.1.7.7/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `block (2 levels) in exec_no_cache'
/home/inaturalist/deployment/production/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.7.7/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/home/inaturalist/deployment/production/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.7.7/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/home/inaturalist/deployment/production/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.7.7/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/home/inaturalist/deployment/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.1.7.7/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `block in exec_no_cache'
/home/inaturalist/deployment/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.1.7.7/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
/home/inaturalist/deployment/production/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.7.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/home/inaturalist/deployment/production/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.7.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/home/inaturalist/deployment/production/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.7.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/home/inaturalist/deployment/production/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.7.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/home/inaturalist/deployment/production/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.7.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/home/inaturalist/deployment/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.1.7.7/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
/home/inaturalist/deployment/production/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.7.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/inaturalist/deployment/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.1.7.7/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
/home/inaturalist/deployment/production/shared/bundle/ruby/3.0.0/gems/activerecord-6.1.7.7/lib/active_record/connection_adapters/postgresql_adapter.rb:670:in `exec_no_cache'
(eval):47:in `block in exec_no_cache'
(eval):14:in `_makara_hijack'
(eval):43:in `exec_no_cache'
```

**Comment by pleary** [comment]
This should hopefully be resolved now. During our last scheduled maintenance we enabled [hot_standby_feedback](https://www.postgresql.org/docs/current/runtime-config-replication.html) on the replica DB. Without this enabled, queries against the replica were getting cancelled if rows they needed were cleaned from the primary and replicated back to the replica. With this enabled, the replica can inform the primary it needs some rows and allows processes like autovacuum to leave them untouched until the replica query is done.

From what I can see that has fixed errors stating `canceling statement due to conflict with recovery`. Can you report back if you are still experiencing this? If not I think this can be closed

**Comment by pleary** [comment]
I'll close this as I haven't seen cases of it recently after enabling hot_standby_feeback. Please reopen with examples if it comes up again
