### ISSUE TITLE
Upsert for POST /sounds and POST /photos

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#4078]
Currently `POST /observation_photos` and `POST /observation_sounds` upsert records based on the provided UUID attribute, i.e. if a client posts an obs photo with a given UUID and the request suceeds but the client never receives a response, when the client tries to post that same obs photo again with the same UUID, the server will not create a duplicate record and will instead update the existing record with the same UUID. This helps avoid the creation of duplicate media/observation associations.

However, `POST /photos` and `POST /sounds` do not support this functionality, presumably because our own mobile client applications have not made much use of those endpoints. iNaturalistReactNative uploads media _does_ use these endpoints like the web does, i.e. it posts photos and sounds before posting observation photo and observation sound associations. Since iNaturalistReactNative is a mobile app and will be making a lot of requests in less stable network conditions, upsert / dedupe functionality seems desirable.

- [x] `POST /photos` should find and update an existing photo matching the photo[uuid] attribute instead of creating a new record if such a photo exists, otherwise it should create a new record
- [x] `POST /sounds` should find and update an existing sound matching the sound[uuid] attribute instead of creating a new record if such a sound exists, otherwise it should create a new record
- [x] The equivalent endpoints in the API should behave the same way

**Comment by pleary** [comment]
should be working in production now
