### ISSUE TITLE
Gray out DQA items if they're irrelevant

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#4084]
See https://forum.inaturalist.org/t/prevent-dqa-voting-when-pre-requisite-conditions-arent-met/49859

People sometimes vote wrongly for some DQA items either maliciously (to make something casual) or because they're confused (eg voting "no" for "Evidence relates to a single subject" when there's one photo depicting, say, a flower and a bee). The ask is to gray out DQA items and make them unclickable if they're not currently relevant to the observation. 

- [x] Date is accurate - gray out if the observation has no date
- [x] Location is accurate - gray out if the observation has no location
- [x] Evidence of organism - gray out if the observation has no media evidence
- [x] Evidence related to a single subject - gray out if the observation only has one media file of evidence (eg one sound or one image)
- [x] Based on the evidence, can the Community Taxon still be confirmed or improved? - gray out if the observation has no community taxon

**Comment by tiwane** [comment]
>Evidence related to a single subject - gray out if the observation only has one media file of evidence (eg one sound or one image)

Mistake on my end, as it can lead to a situation like [this one](https://www.inaturalist.org/observations/237700422), where the observer has removed the extra photos and now no one can vote Yes to make it verifiable again. Is there a way to recalculate if the number of media items have been reduced? Or maybe not worth graying out if it's too complex to deal with this situation.

**Comment by pleary** [comment]
We've been running for a few weeks with this last modification - not graying out anything that already has votes. Did that resolve the major issue with graying out DQA items? Can this ticket be closed again, or is there anything we should do related to this request?

**Comment by pleary** [comment]
I believe this is resolved again. Please reopen with requirements if there are tasks still left to to
