### ISSUE TITLE
Taxonomy tab URLs should be functional

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#4085]
See https://forum.inaturalist.org/t/allow-direct-linking-to-specific-tabs-on-taxon-pages/48945

If you mouseover the tabs on taxon pages, you'll see that we use a # in the URL for that tab, eg https://www.inaturalist.org/taxa/748759-Lagrecacanthops-guyanensis#taxonomy-tab

However, if you paste that URL into a browser and go to the page, you are not taken to the page with that tab open (doesn't matter whether you're logged in or not). 

We should make those URLs work so that if I go to https://www.inaturalist.org/taxa/748759-Lagrecacanthops-guyanensis#taxonomy-tab the page should load with the Taxonomy tab opened. This is helpful for support and just general communication.

**Comment by pleary** [comment]
this should be working now
