### ISSUE TITLE
Help me make my first open source contribution:)

### ISSUE THREAD

**Issue by tomkoevoets** [inaturalist/inaturalist#4096]
## Hello Inaturalist Community!

I'm excited to be reaching out to you today as I'm eager to contribute to the Inaturalist open source project. However, I'm new to the world of open source and could use some guidance on where to begin.

As a first-year IT student, I'm keen on starting with a small, beginner-friendly patch to get acquainted with the project's codebase and workflows. Additionally, I have a school assignment coming up where I'll be required to contribute to an open source project, making this opportunity perfect for me to learn and grow.
For this the school project my contribution has to be bigger then the first one ofcourse.

I'm particularly drawn to Inaturalist because of my love for nature. It's been a challenge for me to find open source projects that align with my passion for environmental conservation and biodiversity, so discovering Inaturalist feels like a perfect fit.

Could someone please advise me on how I can get started? I'd greatly appreciate any help or guidance you can offer as I embark on this exciting journey into the world of open source.

Thank you in advance for your support!

**Comment by OrigamiBurger** [comment]
Hi @tomkoevoets, I'm just a minor contributor to this project but here are some of the resources I used to get started:
Contributing.md Doc: https://github.com/inaturalist/inaturalist/blob/main/CONTRIBUTING.md
Development Setup doc: https://github.com/inaturalist/inaturalist/wiki/Development-Setup-Guide

**Comment by kueda** [comment]
Sorry you never got a reply here, @tomkoevoets. The docs @OrigamiBurger linked to are a good place to start. This particular repo might be good if you're familiar with Rails (there's certainly tons of work to do), but it's probably our hardest dev environment to get running. Our [API web application](https://github.com/inaturalist/iNaturalistAPI) might be slightly easier to get running, and our [JS API wrapper](https://github.com/inaturalist/inaturalistjs) is probably even simpler to work on, though it doesn't have many issues. Our new(ish) React Native app is where I spend most of my time, and it's probably easier to get set up than the Rails app, though also not trivial.
