### ISSUE TITLE
Web uploader: shift + click doesnt work correctly if cards are reordered.

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#4107]
See https://forum.inaturalist.org/t/group-selection-quirks-in-upload-interface/14700/13?u=tiwane

1. Add about 5 photos to the uploader
2. Reorder them by dragging, say from 1 2 3 4 5 to 1 3 5 4 2
3. Click on 3
4. Hold shift then click on 2
5. Not all cards will be selected, the page seems to honor the original order of the cards

**Comment by OrigamiBurger** [comment]
I can take a look at this issue!

**Comment by pleary** [comment]
This PR has been released and looks like selection is working as expected. Thanks again!
