### ISSUE TITLE
Blockee can join blocker's projects

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#4108]
Just tested this out, and as a blocked user I could join projects my blocker had created - both collection and traditional projects. I assume umbrella projects too. They should definiteky not be able to do this. 

I'm wondering if we should remove blocked user from projects the blocker owns?

**Comment by rainhead** [comment]
Can I take this?

**Comment by pleary** [comment]
Yes feel free to work on this. Thanks!
