### ISSUE TITLE
automated spam filtering

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#411]
Spam has become enough of a problem on the site that I think we need an automated solution in addition to our existing manual curation tools.

- [x] add `spammer` boolean column to users, allow nil which will mean we don't know if they are or not
- [x] add `spam_count` integer column to users
- [x] for every request for a record that has a user column, render 404 if the user is a spammer
- [x] on users/show for suspended accounts, hide the description and user icon and show a banner saying the account was suspended
- [x] set up [rakismet](https://github.com/joshfrench/rakismet) for anything with a body or description field, especially observations, comments, identifications, posts, projects, lists, guides, guide taxa
- [x] if rakismet thinks a record is spam, add a flag, reason = spam, no user_id (i.e. attributed to iNat)
- [x] for every spam flag, increment `spam_count`. Only increment once per record
- [x] for show actions corresponding to spammable content, render 404 to everyone other than the resource owner if it's spam. For the owner, show the content with a banner reading, "This has been flagged as spam. If you don't think that's correct, contact help@inaturlaist.org" or something like that
- [x] if `spam_count` exceeds 3, suspend the account, set `spammer` to true
- [x] make a cron job that deletes spammable content of spammers every 3 days (this should include text fields in records that should not be deleted, like the `User` record and the user's life list.
- [ ] if `spammer` changes from true to false, send Akismet ham requests for all their spammable content
- [x] document our 3 strikes to suspension / 3 days to deletion spam policy on the Help page and/or the Curator's Guide so people know how it works

**Comment by pleary** [comment]
Some initial code on a branch of mine at https://github.com/pleary/inaturalist/commit/38dfefadcc4cf389c11a6d4eb18fed0deed6eea5

**Comment by pleary** [comment]
I added a rake task for deleting spammer content in https://github.com/pleary/inaturalist/commit/71d6e2cd0a54ef4ff7e2ff66dc4eeb6aa8e80598 . You might want to make sure this is is getting rid of everything it needs to, and isn't getting rid of too much.

I haven't yet done the thing about when spammer changes from true to false. I wonder if we want to tie that more to the flags. If something with spam flags loses its spam flags then we send those to Akismet as ham. I think the more likely case is Askismet improperly flags something, that person isn't a spammer, we delete the flag and want Akismet to know that is made a mistake.

Anyway, that is TBD as is the documentation. Do you have ideas of what you want to say? I figure we just need to add something to http://www.inaturalist.org/pages/help#inappropriate like:

Content can be flagged as spam by other users as well as automated methods. Any user with 3 or more submissions flagged as spam will be suspended and access to all of their content will be restricted. If you believe any of your content has been incorrectly flagged, please contact us. After being flagged for 7 days, all flagged content will be removed completely.

**Comment by naturalistcharlie** [comment]
Maybe this is paranoid but I can imagine situations where people could
maliciously flag to get data off the site for whatever reason, and if it
were fled or absent user, if their account were deleted a lot of data could
be lost. Another example would be if someone adds lots of good data but
then leaves the site, and then hackers get their account info and start
spamming. I wouldn't want that to mean all their good data would be deleted
too. I still feel like a human should be the one to pull the final trigger,
at least in cases where there are observations that are research grade or
etc. Thoughts?

On Thu, Jan 8, 2015 at 2:45 PM, Patrick Leary <notifications@github.com>
wrote:

> I added a rake task for deleting spammer content in pleary@71d6e2c
> <https://github.com/pleary/inaturalist/commit/71d6e2cd0a54ef4ff7e2ff66dc4eeb6aa8e80598>
> . You might want to make sure this is is getting rid of everything it needs
> to, and isn't getting rid of too much.
>
> I haven't yet done the thing about when spammer changes from true to
> false. I wonder if we want to tie that more to the flags. If something with
> spam flags loses its spam flags then we send those to Akismet as ham. I
> think the more likely case is Askismet improperly flags something, that
> person isn't a spammer, we delete the flag and want Akismet to know that is
> made a mistake.
>
> Anyway, that is TBD as is the documentation. Do you have ideas of what you
> want to say? I figure we just need to add something to
> http://www.inaturalist.org/pages/help#inappropriate like:
>
> Content can be flagged as spam by other users as well as automated
> methods. Any user with 3 or more submissions flagged as spam will be
> suspended and access to all of their content will be restricted. If you
> believe any of your content has been incorrectly flagged, please contact
> us. After being flagged for 7 days, all flagged content will be removed
> completely.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69236997>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by pleary** [comment]
I don't think it's overly paranoid. I should have said in my last comment what while I did create the task to delete the content, there's nothing yet in place to active it (and the code isn't even merged yet). I also recommend we hold off and see how this all unfolds.

We have also talked about an idea of identifying non-spammers by some other criteria. For example anyone with 3 or more research grade observations maybe gets special consideration when it comes to spam.

**Comment by naturalistcharlie** [comment]
Only thing I can think of that could get in the way of that is when people
flag spammers as humans because the spammer creates an erroneous species
entry and others don't want it there. People can check not
native-naturalized but don't always do that. Having three human RG
observations doesn't mean one is not a spammer...

Another idea is to actually have 'spam' as an entry in the species database
people can use instead of 'homo sapiens'. It makes sense in terms of
allowing users to easily label spam, but it is a little odd since spammers
haven't devolved into a separate species, yet. (unless one considers the
primitive AI type algorithms as a species, heh)

On Thu, Jan 8, 2015 at 2:53 PM, Patrick Leary <notifications@github.com>
wrote:

> I don't think it's overly paranoid. I should have said in my last comment
> what while I did create the task to delete the content, there's nothing yet
> in place to active it (and the code isn't even merged yet). I also
> recommend we hold off and see how this all unfolds.
>
> We have also talked about an idea of identifying non-spammers by some
> other criteria. For example anyone with 3 or more research grade
> observations maybe gets special consideration when it comes to spam.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69238186>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by kueda** [comment]
Added some documentation: http://www.inaturalist.org/pages/help#spam

**Comment by naturalistcharlie** [comment]
Watch Hawks: Yes
Hawk Watches: No

On Fri, Jan 9, 2015 at 4:13 PM, Ken-ichi <notifications@github.com> wrote:

> Added some documentation: http://www.inaturalist.org/pages/help#spam
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69399813>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by naturalistcharlie** [comment]
It just filtered a bunch of users as spam based on their life lists... they
don't have any content to their profile or any observations or anything...
not sure if there are life lists as spam I just can't see or if it's some
sort of bug. The accounts do seem to be spam accounts but i can't tell for
sure.

On Fri, Jan 9, 2015 at 4:31 PM, Charlie Hohn <naturalist.charlie@gmail.com>
wrote:

> Watch Hawks: Yes
> Hawk Watches: No
>
> On Fri, Jan 9, 2015 at 4:13 PM, Ken-ichi <notifications@github.com> wrote:
>
>> Added some documentation: http://www.inaturalist.org/pages/help#spam
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69399813>
>> .
>>
>
>
>
> --
> ============================
> Charlie Hohn
> Montpelier, Vermont
> coyot.es/slowwatermovement
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by kueda** [comment]
I think Akismet is marking some things as spam strictly based on IP address and email address, and these accounts look spammy to me, so I think we'll leave them. Also, technically, their content has been flagged as spam, not their accounts. Their accounts will be marked as spammers and suspended when they post 2 more items that get flagged as spam.

Right now the only user account that's been marked as a spammer is http://www.inaturalist.org/users/68755, and I'm not seeing any false positives in the [list of spam flags](http://www.inaturalist.org/flags?flag=spam), so I think we can close this.

**Comment by pleary** [comment]
Yeah that is unexpected and interesting. Their basic data is such a red flag that I bet anything they do will be flagged as spam. Like you - I'm not seeing any obvious false positives. And we've had our second valid automatic ban, so looking good so far.

**Comment by naturalistcharlie** [comment]
Everything I've seemed flagged as spam so far has appeared to be spam,
though I am not watching that closely since I only have the curator flags
window I occasionally glance at. The flagging also offers a human who is
watching a chance to suspend spammers, based on suspicious users that pop
up there.

On Mon, Jan 12, 2015 at 11:16 AM, Patrick Leary <notifications@github.com>
wrote:

> Yeah that is unexpected and interesting. Their basic data is such a red
> flag that I bet anything they do will be flagged as spam. Like you - I'm
> not seeing any obvious false positives. And we've had our second valid
> automatic ban, so looking good so far.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69595164>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by naturalistcharlie** [comment]
Update: This seems like a real person and her life list was flagged as spam:
http://www.inaturalist.org/users/70288

On Mon, Jan 12, 2015 at 11:17 AM, Charlie Hohn <naturalist.charlie@gmail.com
> wrote:

> Everything I've seemed flagged as spam so far has appeared to be spam,
> though I am not watching that closely since I only have the curator flags
> window I occasionally glance at. The flagging also offers a human who is
> watching a chance to suspend spammers, based on suspicious users that pop
> up there.
>
> On Mon, Jan 12, 2015 at 11:16 AM, Patrick Leary <notifications@github.com>
> wrote:
>
>> Yeah that is unexpected and interesting. Their basic data is such a red
>> flag that I bet anything they do will be flagged as spam. Like you - I'm
>> not seeing any obvious false positives. And we've had our second valid
>> automatic ban, so looking good so far.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69595164>
>> .
>>
>
>
>
> --
> ============================
> Charlie Hohn
> Montpelier, Vermont
> coyot.es/slowwatermovement
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by kueda** [comment]
Weird, let's keep watching for these. I resolved this one:

http://www.inaturalist.org/flags/3873
http://www.inaturalist.org/life_lists/170401-lauren3s-Life-List

**Comment by naturalistcharlie** [comment]
This person observed a yarrow... which makes me think probably not spam...
http://www.inaturalist.org/users/70321
i resolved their flag... hope that is OK

On Mon, Jan 12, 2015 at 5:47 PM, Ken-ichi <notifications@github.com> wrote:

> Weird, let's keep watching for these. I resolved this one:
>
> http://www.inaturalist.org/flags/3873
> http://www.inaturalist.org/life_lists/170401-lauren3s-Life-List
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69662482>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by naturalistcharlie** [comment]
another one for the files... this robin came up as spam:
http://www.inaturalist.org/observations/1175506
all i can think of... the photo IS present on another website but in this
case it is that same person's website.

I unflagged it.

On Mon, Jan 12, 2015 at 9:25 PM, Charlie Hohn <naturalist.charlie@gmail.com>
wrote:

> This person observed a yarrow... which makes me think probably not spam...
> http://www.inaturalist.org/users/70321
> i resolved their flag... hope that is OK
>
> On Mon, Jan 12, 2015 at 5:47 PM, Ken-ichi <notifications@github.com>
> wrote:
>
>> Weird, let's keep watching for these. I resolved this one:
>>
>> http://www.inaturalist.org/flags/3873
>> http://www.inaturalist.org/life_lists/170401-lauren3s-Life-List
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69662482>
>> .
>>
>
>
>
> --
> ============================
> Charlie Hohn
> Montpelier, Vermont
> coyot.es/slowwatermovement
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by naturalistcharlie** [comment]
Looking into this further... the image appears on Shutterstocl but it seems
that this user provided it to them rather than the other way around.  I
think. It's a bit confusing.

On Tue, Jan 13, 2015 at 8:40 AM, Charlie Hohn <naturalist.charlie@gmail.com>
wrote:

> another one for the files... this robin came up as spam:
> http://www.inaturalist.org/observations/1175506
> all i can think of... the photo IS present on another website but in this
> case it is that same person's website.
>
> I unflagged it.
>
> On Mon, Jan 12, 2015 at 9:25 PM, Charlie Hohn <
> naturalist.charlie@gmail.com> wrote:
>
>> This person observed a yarrow... which makes me think probably not
>> spam...
>> http://www.inaturalist.org/users/70321
>> i resolved their flag... hope that is OK
>>
>> On Mon, Jan 12, 2015 at 5:47 PM, Ken-ichi <notifications@github.com>
>> wrote:
>>
>>> Weird, let's keep watching for these. I resolved this one:
>>>
>>> http://www.inaturalist.org/flags/3873
>>> http://www.inaturalist.org/life_lists/170401-lauren3s-Life-List
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69662482>
>>> .
>>>
>>
>>
>>
>> --
>> ============================
>> Charlie Hohn
>> Montpelier, Vermont
>> coyot.es/slowwatermovement
>>
>
>
>
> --
> ============================
> Charlie Hohn
> Montpelier, Vermont
> coyot.es/slowwatermovement
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by kueda** [comment]
Yeah, but he posted it to iNat multiple times, which is not commercial but still kind of spammy. I think I would have left this one.

**Comment by naturalistcharlie** [comment]
Oh, I didn't see that, sorry!. I looked at the calendar and it only showed
once there, so I figured it was not posted multiple times. but now I see
that it was.  Not sure why it didn't display on the calendar.  I probably
just didn't look deep enough... sorry, I'll try not to pull the not spam
trigger so fast!

C

On Tue, Jan 13, 2015 at 12:42 PM, Ken-ichi <notifications@github.com> wrote:

> Yeah, but he posted it to iNat multiple times, which is not commercial but
> still kind of spammy. I think I would have left this one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69785688>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by naturalistcharlie** [comment]
i see... most of them weren't posted with a date.  Ugh.  I'm trying to do
too many things at once. Sorry

On Tue, Jan 13, 2015 at 1:13 PM, Charlie Hohn <naturalist.charlie@gmail.com>
wrote:

> Oh, I didn't see that, sorry!. I looked at the calendar and it only showed
> once there, so I figured it was not posted multiple times. but now I see
> that it was.  Not sure why it didn't display on the calendar.  I probably
> just didn't look deep enough... sorry, I'll try not to pull the not spam
> trigger so fast!
>
> C
>
> On Tue, Jan 13, 2015 at 12:42 PM, Ken-ichi <notifications@github.com>
> wrote:
>
>> Yeah, but he posted it to iNat multiple times, which is not commercial
>> but still kind of spammy. I think I would have left this one.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69785688>
>> .
>>
>
>
>
> --
> ============================
> Charlie Hohn
> Montpelier, Vermont
> coyot.es/slowwatermovement
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by carrieseltzer** [comment]
Hi folks. I'm REALLY sorry about the identical postings-- it's definitely a
glitch in the Great Nature Project site (you can see they all come from
App: Great Nature Project). I am 100% sure that this is not tomcurtis's
fault, and I just saw that he tried again 5 hours ago with a goose and it
posted 8 times and has been flagged as spam.

This multiple posting problem-- with varying degrees of completeness so
they aren't all 100% identical-- is something that has happened about 10
times now for different people, but we haven't been able to replicate it
yet. I've reached out via iNat message every time I've seen it, but I
haven't gotten any insights from that. I'll look into this more later today
since it's obviously causing you trouble now too! I'm so sorry.

On Tue, Jan 13, 2015 at 1:13 PM, Charlie <notifications@github.com> wrote:

> i see... most of them weren't posted with a date. Ugh. I'm trying to do
> too many things at once. Sorry
>
> On Tue, Jan 13, 2015 at 1:13 PM, Charlie Hohn <
> naturalist.charlie@gmail.com>
> wrote:
>
> > Oh, I didn't see that, sorry!. I looked at the calendar and it only
> showed
> > once there, so I figured it was not posted multiple times. but now I see
> > that it was. Not sure why it didn't display on the calendar. I probably
> > just didn't look deep enough... sorry, I'll try not to pull the not spam
> > trigger so fast!
> >
> > C
> >
> > On Tue, Jan 13, 2015 at 12:42 PM, Ken-ichi <notifications@github.com>
> > wrote:
> >
> >> Yeah, but he posted it to iNat multiple times, which is not commercial
> >> but still kind of spammy. I think I would have left this one.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69785688>
>
> >> .
> >>
> >
> >
> >
> > --
> > ============================
> > Charlie Hohn
> > Montpelier, Vermont
> > coyot.es/slowwatermovement
> >
>
>
>
> --
> ============================
> Charlie Hohn
> Montpelier, Vermont
> coyot.es/slowwatermovement
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69790960>
> .
>



-- 
Carrie E. Seltzer, Ph.D.
National Geographic's Great Nature Project
www.greatnatureproject.org

**Comment by naturalistcharlie** [comment]
it looks like tomcurtis was banned

On Wed, Jan 14, 2015 at 9:52 AM, carrieseltzer <notifications@github.com>
wrote:

> Hi folks. I'm REALLY sorry about the identical postings-- it's definitely
> a
> glitch in the Great Nature Project site (you can see they all come from
> App: Great Nature Project). I am 100% sure that this is not tomcurtis's
> fault, and I just saw that he tried again 5 hours ago with a goose and it
> posted 8 times and has been flagged as spam.
>
> This multiple posting problem-- with varying degrees of completeness so
> they aren't all 100% identical-- is something that has happened about 10
> times now for different people, but we haven't been able to replicate it
> yet. I've reached out via iNat message every time I've seen it, but I
> haven't gotten any insights from that. I'll look into this more later
> today
> since it's obviously causing you trouble now too! I'm so sorry.
>
> On Tue, Jan 13, 2015 at 1:13 PM, Charlie <notifications@github.com>
> wrote:
>
> > i see... most of them weren't posted with a date. Ugh. I'm trying to do
> > too many things at once. Sorry
> >
> > On Tue, Jan 13, 2015 at 1:13 PM, Charlie Hohn <
> > naturalist.charlie@gmail.com>
> > wrote:
> >
> > > Oh, I didn't see that, sorry!. I looked at the calendar and it only
> > showed
> > > once there, so I figured it was not posted multiple times. but now I
> see
> > > that it was. Not sure why it didn't display on the calendar. I
> probably
> > > just didn't look deep enough... sorry, I'll try not to pull the not
> spam
> > > trigger so fast!
> > >
> > > C
> > >
> > > On Tue, Jan 13, 2015 at 12:42 PM, Ken-ichi <notifications@github.com>
> > > wrote:
> > >
> > >> Yeah, but he posted it to iNat multiple times, which is not
> commercial
> > >> but still kind of spammy. I think I would have left this one.
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <
> >
> https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69785688>
>
> >
> > >> .
> > >>
> > >
> > >
> > >
> > > --
> > > ============================
> > > Charlie Hohn
> > > Montpelier, Vermont
> > > coyot.es/slowwatermovement
> > >
> >
> >
> >
> > --
> > ============================
> > Charlie Hohn
> > Montpelier, Vermont
> > coyot.es/slowwatermovement
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69790960>
>
> > .
> >
>
>
>
> --
> Carrie E. Seltzer, Ph.D.
> National Geographic's Great Nature Project
> www.greatnatureproject.org
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69926773>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by carrieseltzer** [comment]
Could someone with the power please un-suspend tomcurtis as a user? If
someone is suspended, do they still get messages sent with the iNat message
system?

(Just in case this matters somehow, I tried
www.inaturalist.org/users/70400/unsuspend to reactivate his account but it
didn't appear to work.)

On Wed, Jan 14, 2015 at 10:36 AM, Charlie <notifications@github.com> wrote:

> it looks like tomcurtis was banned
>
> On Wed, Jan 14, 2015 at 9:52 AM, carrieseltzer <notifications@github.com>
> wrote:
>
> > Hi folks. I'm REALLY sorry about the identical postings-- it's
> definitely
> > a
> > glitch in the Great Nature Project site (you can see they all come from
> > App: Great Nature Project). I am 100% sure that this is not tomcurtis's
> > fault, and I just saw that he tried again 5 hours ago with a goose and
> it
> > posted 8 times and has been flagged as spam.
> >
> > This multiple posting problem-- with varying degrees of completeness so
> > they aren't all 100% identical-- is something that has happened about 10
> > times now for different people, but we haven't been able to replicate it
> > yet. I've reached out via iNat message every time I've seen it, but I
> > haven't gotten any insights from that. I'll look into this more later
> > today
> > since it's obviously causing you trouble now too! I'm so sorry.
> >
> > On Tue, Jan 13, 2015 at 1:13 PM, Charlie <notifications@github.com>
> > wrote:
> >
> > > i see... most of them weren't posted with a date. Ugh. I'm trying to
> do
> > > too many things at once. Sorry
> > >
> > > On Tue, Jan 13, 2015 at 1:13 PM, Charlie Hohn <
> > > naturalist.charlie@gmail.com>
> > > wrote:
> > >
> > > > Oh, I didn't see that, sorry!. I looked at the calendar and it only
> > > showed
> > > > once there, so I figured it was not posted multiple times. but now I
> > see
> > > > that it was. Not sure why it didn't display on the calendar. I
> > probably
> > > > just didn't look deep enough... sorry, I'll try not to pull the not
> > spam
> > > > trigger so fast!
> > > >
> > > > C
> > > >
> > > > On Tue, Jan 13, 2015 at 12:42 PM, Ken-ichi <notifications@github.com>
>
> > > > wrote:
> > > >
> > > >> Yeah, but he posted it to iNat multiple times, which is not
> > commercial
> > > >> but still kind of spammy. I think I would have left this one.
> > > >>
> > > >> —
> > > >> Reply to this email directly or view it on GitHub
> > > >> <
> > >
> >
> https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69785688>
>
> >
> > >
> > > >> .
> > > >>
> > > >
> > > >
> > > >
> > > > --
> > > > ============================
> > > > Charlie Hohn
> > > > Montpelier, Vermont
> > > > coyot.es/slowwatermovement
> > > >
> > >
> > >
> > >
> > > --
> > > ============================
> > > Charlie Hohn
> > > Montpelier, Vermont
> > > coyot.es/slowwatermovement
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69790960>
>
> >
> > > .
> > >
> >
> >
> >
> > --
> > Carrie E. Seltzer, Ph.D.
> > National Geographic's Great Nature Project
> > www.greatnatureproject.org
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69926773>
>
> > .
> >
>
>
>
> --
> ============================
> Charlie Hohn
> Montpelier, Vermont
> coyot.es/slowwatermovement
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69934183>
> .
>



-- 
Carrie E. Seltzer, Ph.D.
National Geographic's Great Nature Project
www.greatnatureproject.org

**Comment by alexshepard** [comment]
He should be un-suspended now.

**Comment by pleary** [comment]
I also resolved the spam flags on his existing content

**Comment by carrieseltzer** [comment]
Just to update everyone on the multiple posting situation via the Great
Nature Project site, here's what I've learned. I dug into our analytics to
try and find any useful tidbit of information regarding the circumstances
under which a user has posted the same observation multiple times. Nothing
very clear came out of that effort, but I do know a couple of them used
Firefox (but one Mac and one Windows).

The fact that we never saw it in testing and can't replicate it, along with
some custom events that track how many times a user clicks the button to
add an observation makes me wonder if it's a user error due to design
ill-suited to a small browser window. I could see how someone might not
realize their observation was submitted, so then they go through the
process again. I'm going to keep a close eye out for the next time this
happens to get a better handle on it. If it is a design/messaging issue,
we'll figure out what we can do easily so that people aren't so easily
confused about whether or not their observation was submitted! Please feel
free to reach out to me directly if you happen to notice this before I do.


On Wed, Jan 14, 2015 at 10:48 AM, Patrick Leary <notifications@github.com>
wrote:

> I also resolved the spam flags on his existing content
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/411#issuecomment-69936326>
> .
>



-- 
Carrie E. Seltzer, Ph.D.
National Geographic's Great Nature Project
www.greatnatureproject.org
