### ISSUE TITLE
After Lato change, some slight misalignment issues on taxon page in Safari

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#4119]
See https://forum.inaturalist.org/t/taxon-text-offset/51946

1. Open Safari and go to a taxon page, like https://www.inaturalist.org/taxa/1514466-Inimia-nat
2. Go to the Taxonomy tab
3. Misalignments abound

<img width="417" alt="image" src="https://github.com/inaturalist/inaturalist/assets/15896181/b2d8dd07-497b-466a-9c18-1ab68f063f54">

I can't replicate in Chrome or Firefox.

**Comment by pleary** [comment]
This case should be fixed. I wouldn't be surprised if others pop up since Lato seems to behave a little differently in different browsers, and line heights have been a source of a lot of alignment problems
