### ISSUE TITLE
New flag not created, old flag unresolved if flag reason matches user's previous flag for taxon

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#4153]
From: https://forum.inaturalist.org/t/flags-mysteriously-unresolving/52650/

1. Find a taxon which you have already flagged, and make sure that flag has been resolved.
2. Flag that taxon again, and make sure the "Reason" field matches the "Reason" field from your resolved flag.
3. New flag is not saved, old flag gets unresolved.

**Comment by pleary** [comment]
resolved by #4157
