### ISSUE TITLE
Common name lexicons: merge `magyar` with `Hungarian`

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#4190]
See https://forum.inaturalist.org/t/remove-merge-duplicate-hungarian-lexicon/52612

There's a common name lexicon for `magyar`, but it shouldn't exist - we should just have the translated `Hungarian` lexicon. Can this be cleaned up when you run the lexicon cleaning script?

**Comment by kueda** [comment]
FWIW, this happens around https://github.com/inaturalist/inaturalist/blob/main/tools/clean_lexicons.rb#L100-L159
