### ISSUE TITLE
add GBIF tile layers to taxon maps

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#420]
Right now we only show GBIF data as a rather cruddy KML overlay on taxa/show, but GBIF has a much, much nicer tile server we could be using: http://www.gbif.org/developer/maps. Given that we have an existing system for adding image tiles to our maps I think it should be pretty straightforward to add these tiles to our taxon maps so people can see not just iNat observations of a given taxon but *all* GBIF observations of that taxon. The main challenge is that to my knowledge it will not accept scientific names, just GBIF's internal taxon keys, so turning on that layer would have to hit [GBIF's species API](http://www.gbif.org/developer/species) with the scientific name and either choose the best result or present the iNat user with a list of "Did you mean..." options.

I probably haven't through this all the way through, but here's a provisional spec:

- [ ] Add the ability to add a GBIF tile layer to any iNat map given a GBIF taxon key. The cartography might require fiddling, but I think their yellows_reds palette is different enough from ours to work. `resolution` should not be the default 1, which seems invisible when there's isn't much data, so play around with that value
- [ ] Add GBIF as a layer option to all taxon maps, turned off by default
- [ ] When the user turns on the GBIF layer, hit the GBIF species API for taxa matching that name (e.g. http://api.gbif.org/v1/species?name=Cantharellus). There's going to be a lot of crud, so try and winnow it by uniquing on phylum or kingdom. If there's more than one unique taxon, present a dialog to the user asking them to choose one of them. If there's only one, just show the tiles for that taxon key.

**Comment by pleary** [comment]
This was completed largely in 0a5e0ddedf59927230c48aef292b91c3d49c4f96 . The original GBIF API took a name and returned a KML file. There is no equivalent API for mapping, so we needed to split it up into two calls - 1) get the GBIF taxon ID from a name and a reasonable ancestor for accurate searching, 2) register the GBIF tileserver API as a layer using the found taxon ID. The search API results are cached at this point indefinitely using taxon_schemes
