### ISSUE TITLE
Obs Detail: links under top identifiers usernames show number of IDs but link to user's observations.

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#4216]
From: https://forum.inaturalist.org/t/clicking-top-identifier-link-leads-to-their-observations-not-ids/55336

1. Go to: https://www.inaturalist.org/observations/241382144
2. Scroll down to top identifiers and you'll see something like this. Each number of under the username shows how many IDs of that taxon they've made. 
3. Mouseover any of those numbers and the link leads to their observations, eg https://www.inaturalist.org/observations?user_id=samfellows566&place_id=any&verifiable=any

That link should lead to a search of observations of that taxon they've add an ID to.

**Comment by pleary** [comment]
@tiwane - @HannesOberreiter has kindly volunteered a fix for this. In their pull request a link is being made to the identifications page, e.g. https://www.inaturalist.org/identifications?user_id=samfellows566&taxon_id=4345. This is probably the best we can do as there is currently no way to filter the observations explore page by a combination of identifier user_id and the taxon they identified. The closest we could accurately get for Explore is linking to all observations the user has identified, e.g. https://www.inaturalist.org/observations?ident_user_id=samfellows566. A user could then filter by taxon, but that would apply a filter to the observation and it does not necessarily follow the `ident_user_id` added an identification of that taxon - they may have added an ID of a different taxon.

We don't often link to the identifications page, but it is the only page I think think of that we can both filter by identifier and identified taxon at the same time. Does that seem like the change we want to make here to address this ticket?

**Comment by tiwane** [comment]
What does the number under the username in the Top Identifiers section represent? IMO we should take the user to whatever represents that number, if possible.

**Comment by pleary** [comment]
The number represent the count of identifications the user has added to observations of the taxon, where the identification is current, unhidden, and the observation is research grade. Given that, linking to the identification page is the most accurate as the number is of identifications not observations, and we don't have a way to filter to those observations.

What we cannot do right now is filter the identifications page by the quality grade of the identified observation. So if we link to the identifications page, it won't be the _exact_ set of identifications counted in the top IDers section, rather it will be a larger set where the identifications counted in the top IDers section is a subset. In my opinion this is close enough, and much closer than what that section is linking to now. Does that sound OK to you?

**Comment by tiwane** [comment]
Sounds good, thanks!
