### ISSUE TITLE
Fine-tune spam detection

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#422]
After several days of being live, akismet has flagged 159 items: 147 lists, 8 observations, 2 guides, 2 posts. Every list is a life list, but one or two users created more than one life list. About 4 of these life lists are obviously spam. There is also a good chunk that have the default life list titles and descriptions that I wouldn't have flagged if presented with their account. What is raising the flag could either be those default fields, or the other session info which would be more of a flag on the user itself.

One thing that is possibly a problem is that the username is used in the life list title. Usernames can be very random, sometimes with numbers, and that can create spammy-looking text.

 - I recommend we only initiate a spam check on a life list if the title or description has changed from the default.
 - I also recommend we initiate checking the user description for spam and adding flags to the user account itself. That would essentially let us preserve the info we're getting now from flagged life lists - that there is something inherent in the session that smells of spam.

**Comment by kueda** [comment]
Both sound good to me. What would you send to Akismet for the user description, just the description author email, IP, but no title?

**Comment by pleary** [comment]
Yes that's right. We actually only send one field to akismet anyway, and had been merging things like title and description for other records. So for user, I'd just send the description, and then all the other normal stuff

**Comment by kueda** [comment]
I feel like we're seeing a lot more spam user accounts without any content after having implemented the filter, many of which are just putting SE"O" crap in the user description, so if we're going to start flagging user accounts as spam based on that, we should also make sure `UsersController#show` hides the content from public view like the other show methods. I suspect the `blocks_spam` filter will do that, but worth testing regardless.

**Comment by kueda** [comment]
#489 addressed some of this, but I think it's still messed up. Many new users are getting flagged as spam immediately after creation, even though their descriptions are blank. I tried this with an email address like foo+bar20150301@something.com and verified that it's happening. The screen right after signup look like:
![screen shot 2015-03-01 at 11 41 05 am](https://cloud.githubusercontent.com/assets/22691/6433051/c7257e48-c019-11e4-912a-03bfab7aca99.png)

I tried testing around this in f5f2730, but to no avail. Any idea what's happening?

**Comment by kueda** [comment]
FYI, I just turned off automated user spam checks in 5411e20 until we can figure this out.

**Comment by pleary** [comment]
67c2f3820aa17d41864435030d8cb2abf3643874 address spam in a couple ways. I had it set up to send user info for spam checks even when their descriptions were blank. This was meant to replace the positive benefit we were getting when sending checks for default life lists. This commit removes that and we'll only send checks when users have descriptions.

This also ensures the spam flash message shows on the spam page, and not the next page a user visits. It also fixes /flags by creating routes for User and CheckList flags, which are erroring out now due to missing path helpers.

**Comment by pleary** [comment]
Things seem to be working pretty well recently. I am seeing many flagged users, and have yet to see what seems like a false positive out of the top 30 or so. I think I'll close this since the initially proposed improvements are deployed and there are no longer any known problems.

**Comment by kueda** [comment]
Cool. I also updated http://www.inaturalist.org/pages/help#spam so I think it reflects our current code (code is law!).
