### ISSUE TITLE
See if we can remove i18n-js

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#426]
I just loaded the homepage and application_bundle.js was a 436KB download, compressed from the 1.4MB original size. The next largest non-google map asset is jquery at 62KB. This is largely due to translations in our application bundle.

I recommend that instead we start adding the labels we need in JS as attributes of HTML elements. That way we can just use Rails i18n to generate the views, which will generate consistently-named attributes that we can fetch dynamically with JS. I did a little of this when playing with map overlays https://github.com/inaturalist/inaturalist/commit/6446d57f6c9d4a483a07ba917a6f089cb5de614f#diff-127a850b7d7b20173ad3fba88f8a25e3R587 . There aren't a ton of cases where this is used, and I think the benefit we'll get over time is worth the cost to make the updates now.

There should be at least some improvements on just about every single page the web app generates, since nearly all pages user application_bundle.js. The effects will be most significant for users of the mobile site over slower cellular networks.

**Comment by kueda** [comment]
What about situations where the JS has been abstracted to work independent of specific markup, e.g. https://github.com/inaturalist/inaturalist/blob/master/app/assets/javascripts/application.js.erb#L73? In situations like that (where it's just a loading spinner with the word "Loading..."), we would either have to translate "Loading..." in the markup of every page that uses that code, or we'd have to shove those translations into a layout view or something right? Both seem awkward, but maybe not prohibitively awkward if there aren't many cases like that.

**Comment by pleary** [comment]
It looks like in some cases we are already setting the text in the view. See a few instances around https://github.com/inaturalist/inaturalist/blob/master/app/views/photos/show.html.erb#L122 . Granted "Loading..." is probably more common and explicitly adding that could be some overhead, but clearly we'd save a lot more overhead by not needing all the translations. I suspect we will make some view helpers, or some other construct, to keep everything clean rather than adding new labels all over the place

**Comment by md5** [comment]
You guys might just want to look at exporting a slimmer `translations.js` file by using [the config options](https://github.com/fnando/i18n-js#export-configuration-for-translations).

**Comment by md5** [comment]
I don't actually understand this comment that they make:

> But this does not affect anything if you use Asset Pipeline

Still, in theory, it should be possible to create a slimmer version of `translations.js` that isn't so bulky.

**Comment by pleary** [comment]
My guess is that this option might just not work with the asset pipeline. In production we pre-compile all the assets after deploy and cache them. Since they're fixed, we can't have the contents of translations.js change at all based on session info like user language.

I'm totally up for doing the work because I think it'll leave us in a cleaner place. I think there's like ~100 uses of i18n-js. Can you think of a reason (other than immediate development cost) to not try to remove translations.js completely? Just want to make sure I'm not missing something really cool about i18n-js, or recommending some ridiculous design pattern.

**Comment by md5** [comment]
@pleary not sure whether you were asking me about the benefits of `translations.js`, but it seems like it works for you guys now other than the fact that it's generating a file that's too large. Replacing it with a new mechanism created entirely for iNaturalist doesn't seem worthwhile unless there's no way to solve your actual problem which is that `translations.js` is too large.

Using the config options provided by `i18n-js`, I think you could use an `only` expression to limit the exported keys to only the keys that are used on the JS side. Since you'd export `*.frontend.*` or something like that, you'd have the values for all locales and switching based on user session shouldn't be an issue.

**Comment by md5** [comment]
BTW, I think what you did with the map overlay is entirely reasonable, but it doesn't seem like it could replace every use of client-side translations in a graceful way.

**Comment by pleary** [comment]
I created a rake task to generate the smallest translations.js possible 387bb4537897e9cf18e2f0ee8056ae03b0096351, which is being called in an after-deploy hook with Capistrano. That significantly reduced the size of the application_bundle JS. I'm going to close this as my major concern has been addressed, but I'd still like to slowly wean ourselves off of i18n-js.
