### ISSUE TITLE
Javascript error on obs/new in displaying boundary on map

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#429]
For projects with places, obs/new is giving a JS console error which is not displaying the place boundaries on the map and is screwing up subsequent JS like the photo/sounds picker
http://www.inaturalist.org/observations/new?project_id=4
![screen shot 2015-01-19 at 12 56 19 pm](https://cloud.githubusercontent.com/assets/598026/5807707/9fd02f82-9fda-11e4-8a0f-255485e55584.png)
http://www.inaturalist.org/observations/new?project_id=558
![screen shot 2015-01-19 at 12 54 44 pm](https://cloud.githubusercontent.com/assets/598026/5807708/a2e9444c-9fda-11e4-9589-dfe7ed7d1244.png)
No problem for projects without places 
http://www.inaturalist.org/observations/new?project_id=13
![screen shot 2015-01-19 at 1 00 29 pm](https://cloud.githubusercontent.com/assets/598026/5807757/2c5fb580-9fdb-11e4-8b92-bac6a43f8b2c.png)

**Comment by pleary** [comment]
Yep this was a bug introduced with the map overlay toggle work - my bad. This pull request should fix it

**Comment by loarie** [comment]
cool thanks
