### ISSUE TITLE
Default Search Place is set but appears unset in Settings

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#4290]
**Describe the bug**
When I (user_id 1) go to https://www.inaturalist.org/observations, the results are filtered by `place_id=122851` by default, but when I go to https://www.inaturalist.org/users/edit#account, the Default Search Place appears unset. In a console I see

```
3.0.4 :002 > u.search_place_id
 => 122851 
3.0.4 :003 > u.place_id
 => 14 
```

Furthermore, if I try to *set* the search place to something, it dispersal from the UI immediately, but if I save, it actually gets saved.

**To Reproduce**
1. Sign in
1. Go to https://www.inaturalist.org/users/edit#account
1. Under "Default Search Place" choose a place. Your choice will disappear immediately after you choose it
1. Click SAVE SETTINGS in the upper right
1. Go to https://www.inaturalist.org/observations
1. The place you choice is the default place search
1. Go backl to https://www.inaturalist.org/users/edit#account
1. Your "Default Search Place" is still blank

**Expected behavior**
1. If the default search place is set, it should appear under "Default Search Place" in settings.
1. When you choose a default search place, it should not disappear

**Context**
 - OS: Mac OS 14.6.1
 - Browser: Firefox 132.0.1

**Comment by pleary** [comment]
This should be fixed . Related to user settings now using API v2, and some needed changes to API v2 made in https://github.com/inaturalist/iNaturalistAPI/commit/87f42e16abd68e491b513dce19fb5a5f6141aed6
