### ISSUE TITLE
Taxon page: when using place restriction, leaderboard links point to wrong places

### ISSUE THREAD

**Issue by tiwane** [inaturalist/inaturalist#4292]
See https://forum.inaturalist.org/t/species-page-place-setting-changes-when-selecting-top-id-leaderboard/58417 I can replicate. 

1. Go to a taxon page like https://www.inaturalist.org/taxa/4343-Larus. Restrict the Place to California.
2. Click on "Leaderboard" under Top Identifier, it takes you to: https://www.inaturalist.org/observations?verifiable=true&taxon_id=4343&place_id=6b5b1d86-7c7b-46bc-b346-b5e16a4137b8&view=identifiers Which shows you the top _Larus_ identifiers in...Alaska.
3. Keep trying various Place restrictions on different taxon pages and you'll see the same thing: the link goes to an Explore search for the wrong place.

**Comment by pleary** [comment]
This was fixed by the API change in https://github.com/inaturalist/iNaturalistAPI/commit/05ebe9b247e2dfa1a44573435e496f42116f8b16
