### ISSUE TITLE
Observations appear lost after adding to a project

### ISSUE THREAD

**Issue by ckhanks** [inaturalist/inaturalist#433]
The following steps for adding an observation to the Red-crowned Parrot Project result in an observation appearing lost, but not actually deleted.

1. From the Project, click "add from your observations"
http://www.inaturalist.org/projects/red-crowned-parrot-project

This will pull up your observations that fit the rules of the project.

2. Click "view" under an observation.  The reason you might do this is to add an observation from the observation page to prompt the additional fields for this project.

3. Add observation to project via the project drop down and populate fields.

![image](https://cloud.githubusercontent.com/assets/10642144/5847104/3511fb4c-a18f-11e4-8ecf-47d3b9f681db.png)

The observation is now lost, but not deleted: 

![image](https://cloud.githubusercontent.com/assets/10642144/5847128/61e40d68-a18f-11e4-9f79-86ff338cdb90.png)

It is still in the project feed, and in my feed:

![image](https://cloud.githubusercontent.com/assets/10642144/5847198/2338bd42-a190-11e4-9bd3-c0f02c143821.png)

Furthermore, although I can't view the observation, I can still edit the observation: 

![image](https://cloud.githubusercontent.com/assets/10642144/5847181/fe180dec-a18f-11e4-965c-873162707edd.png)

**Comment by loarie** [comment]
Thanks @ckhanks  - this look s great. I suspect there's some bug thats effecting the view thats displaying this observation (which explains why the edit and index views work) probably something to do with the observation fields since those are a bit buggy - but we'll look into it ASAP - thanks again!
