### ISSUE TITLE
replace spatial_adater with rgeo

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#444]
`spatial_adapter` is essentially dead. There's been a bit of work to get it working with Rails 4, but not Rails 4.2. rgeo is pretty alive and 4.2 compatibility is imminent: https://github.com/rgeo/activerecord-postgis-adapter/tree/activerecord42.

- [x] remove all references to `spatial_adapter` and add `activerecord-postgis-adapter`
- [ ] refactor old migrations and make sure they work (is this necessary?)
- [x] refactor all situations in which we assign a GeoRuby geometry object to an AR attribute. Instead, assign rgeo geometries. There are a few cases in which we still need GeoRuby (JSON and KML conversion), so we'll probably need to create the objects with GeoRuby, then convert to rgeo objects using WKT/WKB

**Comment by kueda** [comment]
c9907eb handles most of this. Not sure if it's really worth updating the old migrations since presumably people will load the schema from `structure.sql`. Thoughts, @pleary?

**Comment by pleary** [comment]
I think that's fine. It shouldn't be a problem, and if it does become a problem for someone it should be a quick fix for them.
