### ISSUE TITLE
update or replace cache sweepers 

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#447]
sweepers were commented out in commits 54a47d3272b906fcda5df80a484955789ba40493 and 4b441ca188c7d02474ffae3a1801a103888dcc22

**Comment by kueda** [comment]
Do you have an opinion on updating or replacing? I don't love them, but they do seem to work.

**Comment by pleary** [comment]
I'm all for aiming for a drop in replacement. Hopefully this will do it https://github.com/rails/rails-observers
