### ISSUE TITLE
make sure forked preferences gem still has all functionality we need

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#455]

**Comment by kueda** [comment]
We use preferences pretty heavily in our specs, which are mostly passing at this point.  The changes to the fork we're using right now (mine) are pretty minimal, so I suspect this is working fine. Thoughts?

**Comment by pleary** [comment]
Yep seems to be working well. I can successfully change the number of observations I prefer to see. I'd also consider this closable
