### ISSUE TITLE
[i18n] Remove message keys which overlap the rails i18n gem

### ISSUE THREAD

**Issue by nemobis** [inaturalist/inaturalist#456]
Similar to https://github.com/europeana/Europeana1914-1918/commit/c78792a8f18ab170f838c4d25ca3db7c3d7f20db , I recommend to remove the keys whose i18n is already handled at https://github.com/svenfuchs/rails-i18n/tree/rails-3-x/rails/locale and to submit any missing translation upstream.

A removal from the "en" files will trigger an automatic cleanup upon next export from translatewiki.net, similar to https://github.com/europeana/Europeana1914-1918/commit/c7fe8e3c9aae6eebd94343141747e63fe02672c8 . Less wasted work means more translation time for what's actually needed. :)

**Comment by kueda** [comment]
Better late than never: while I agree in principle, we do have some locales that are not yet supported by rails, including `br`, `lb`, `oc`, and `sq`, and doing this would just throw away the work of the people who did those translations, which I don't want to do. IMO, we shouldn't have included these strings initially, but now that we have and almost all of them have been translated, the cost of removing them is greater than the benefit.
