### ISSUE TITLE
Add oauth_application_id field option to csv data export

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#457]
-Add names associated with numbers in the oauth_application_id field to options for data export

As a manager of a project that uses an iNat application to post observations (http://www.inaturalist.org/oauth/applications), I would like to see a field in a CSV export that shows which application was used to post observations. For example, I want to know how many observations are being submitted to the Great Nature Project using our website (oauth_application_id=62), iNaturalist (null), iOS (3), and Android (2).

**Comment by kueda** [comment]
To clarify, you want the oauth_application_id included as an option in CSV exports generated from http://www.inaturalist.org/observations/export?

**Comment by carrieseltzer** [comment]
Yes, that's what I was thinking. Also open to another suggestion if you
think it's too niche to include in the export options everyone uses.
Thanks, Ken-ichi!

On Tue, Feb 17, 2015 at 7:34 PM, Ken-ichi <notifications@github.com> wrote:

> To clarify, you want the oauth_application_id included as an option in CSV
> exports generated from http://www.inaturalist.org/observations/export?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/457#issuecomment-74787067>
> .
>



-- 
Carrie E. Seltzer, Ph.D.
National Geographic's Great Nature Project
www.greatnatureproject.org

**Comment by kueda** [comment]
Alrighty, it's in there.

**Comment by carrieseltzer** [comment]
Awesome-- thanks! Exporting data now to examine oauth_app_id for GNP!

On Tue, Feb 17, 2015 at 9:00 PM, Ken-ichi <notifications@github.com> wrote:

> Alrighty, it's in there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/457#issuecomment-74797119>
> .
>



-- 
Carrie E. Seltzer, Ph.D.
National Geographic's Great Nature Project
www.greatnatureproject.org

**Comment by carrieseltzer** [comment]
Would it be possible to have the export include the name associated with the app rather than just the app id? It looks like there are now at least 71 apps (some of which probably post essentially 0 observations) but it's a pain to match up all of the id numbers to the names of the apps. Also, exporting the names rather than just the id numbers would make it immediately clear what this field is.
