### ISSUE TITLE
Upgrading the image viewer

### ISSUE THREAD

**Issue by Murray-Dawson** [inaturalist/inaturalist#460]
**Project Description:**
This job is to provide replacement image viewing script that adds the ability to zoom and click/swipe through multiple images while staying within the viewer.

The current iNaturalist (http://www.inaturalist.org/) (including API’s such as NatureWatch NZ at http://naturewatch.org.nz/) script works fine for viewing one image at a time for an observation, with the ability to step between small - medium - large - original sizes.

However, for an observation that has several images associated with it, you cannot currently move back and forth between images within the same viewer instance, and you must jump out of and then back into the viewer to see the next image(s) for that observation.

The new functionality should be implemented as the replacement image viewer throughout iNaturalist, NatureWatchNZ and any API’s, e.g., http://www.inaturalist.org/observations/1206507 and http://www.inaturalist.org/taxa/41566-Megaptera-novaeangliae ; http://naturewatch.org.nz/observations/1081655 and http://naturewatch.org.nz/taxa/343580-Entelea-arborescens. However, image pages such as http://naturewatch.org.nz/photos/1358109 can remain without the viewer script.

**Functionality required:** 
• Cross-platform, multiple browser and device compatibility.
• Touch support for mobile devices.
• Mouse scroll wheel and touch drag to zoom / unzoom.
• Magnifier or +/- icons to indicate zoomability.
• Ability to pan around the zoomed image.
• Right click save of images.
• Copyright statements as in existing iNaturalist viewer.
• “View original” and “View details” links within the new viewer as in the current viewer.
• A nice-to-have (but not essential) is social media (Tweet and FB Like buttons) built into the viewer for each photo. Some of the scripts out there, including prettyPhoto, have this feature.

**Existing jquery image viewer exemplars:**
I think the preferred solution should have the appearence of a Lightbox clone with the added ability to zoom and pan around the enlarged image. A functional image viewer is required rather than an effects-heavy slideshow gallery.

The most suitable (and simple) example that I have seen is Smooth Zoom Pan, with their “Example 7” (http://vectorflower.com/preview/smooth_zoom/sample7.html#prettyPhoto) made using prettyPhoto lightbox. The prettyPhoto slideshow image gallery demo (http://www.no-margin-for-errors.com/projects/prettyphoto-jquery-lightbox-clone/) does not have the zoom ability but demonstrates caption display, mouseover left/right navigation elements and embedded previews of the image set.

Other examples tend to be more slideshow/large screen orientated and probably less suitable:
• PhotoSwipe (http://photoswipe.com/)
• Photobox (http://dropthebit.com/demos/photobox/)
• JackBox (http://codecanyon.net/item/jackbox-responsive-lightbox/3078222?ref=webdesigndev).

Lists of jQuery image viewing scripts are at:
• http://jquery-plugins.net/tag/image-zoom
• http://planetozh.com/projects/lightbox-clones/
• http://www.narga.net/promising-jquery-lightbox-plugins/
• http://blog.webrulon.com/10-jquery-lightbox-clone-plugins/
• http://www.webdesigndev.com/web-development/20-best-premium-free-jquery-lightbox-plugins
• http://www.1stwebdesigner.com/fresh-jquery-image-gallery-display-solutions/
• http://www.freshdesignweb.com/jquery-lightbox-plugin-image-gallery.html

**Budget:** Murray Dawson (dawsonm@rnzih.org.nz) has funding available for this work. Proposed range is a small project (USD$750-1500) following the Freelancer (https://www.freelancer.com) categories.

**Background info for post on Freelancer (https://www.freelancer.com/projects/Software-Architecture-Javascript/Upgrading-the-iNaturalist-image-viewer.html):** The iNaturalist code is open source Rails, and the coding, including this job (https://github.com/inaturalist/inaturalist/issues/460), is coordinated on GitHub. Project is considered complete upon acceptance of iNaturalist developers who will work with the coder to deploy the implementation. **Skills:** Ruby on Rails, Javascript.

**Comment by kueda** [comment]
Thanks for the write-up, Murray. To your questions:

> Should we add the Description of the observation as a caption in the viewer?

I don't think so. Presumably you could just close the viewer to see the rest of the observation details.

> Do you want the ability to have individual captions for each image? For example, Habit, Flower, Fruit, as appropriate?

Personally I feel like this is overkill, but I don't feel super strongly about it.

> Do you want video support added to this new viewer? The only examples of video I have seen have been animated gif’s in NatureWatchNZ. Do you want to go down the track of full video capability? 

No, I think that is way out of scope for this. We are not going to be supporting video any time soon.

> Likewise, some of the scripts out there, including prettyPhoto, have social media (Tweet and FB Like buttons) built into the viewer for each photo. Do you want this?

Maybe! We already have this for the observations, but maybe it would be good for individual photos. I would classify this as a nice-to-have, though, to be done if there's money/time leftover after working on the core functionality.

**Comment by Murray-Dawson** [comment]
Yes, I'm on board with those answers. I'll delete the original questions and modify the first post accordingly.

Then there is the preferred viewer type, which is either a Lightbox clone (which opens a viewer window, similar to current) or a mouse-over thumb magnifier (an effect over the existing thumbs).

**Comment by kueda** [comment]
I don't particularly like the mouse-over zoom, and prefer the first one you linked: http://vectorflower.com/preview/smooth_zoom/sample7.html#prettyPhoto

**Comment by Murray-Dawson** [comment]
I also prefer the first example, and I think the mouse-over zoom could be problematic for iNat, so I have deleted the following from the original post:

"An alternative approach is a mouseover enlargement of a thumb, with examples featured at http://www.tripwiremagazine.com/2013/07/jquery-image-zoom.html. For this to work on iNat / NatureWatch NZ you would either have to display all the thumbs at same size (e.g., the six thumbs at http://naturewatch.org.nz/observations/1081655 would have to be at the same size, or better, clicking one of the series of smallest thumbs would trigger replacement display of the single larger thumb, and then the mouseover zoom effect would be set to work only on that one larger thumb. This would effectively produce three sizes, the smallest thumb, the larger thumb, and then the panable mouseover zoom effect at the original size. "

**Comment by Murray-Dawson** [comment]
I also prefer the first example, and I think the mouse-over zoom could be problematic for iNat, so I have deleted the following from the original post:

"An alternative approach is a mouseover enlargement of a thumb, with examples featured at http://www.tripwiremagazine.com/2013/07/jquery-image-zoom.html. For this to work on iNat / NatureWatch NZ you would either have to display all the thumbs at same size (e.g., the six thumbs at http://naturewatch.org.nz/observations/1081655 would have to be at the same size, or better, clicking one of the series of smallest thumbs would trigger replacement display of the single larger thumb, and then the mouseover zoom effect would be set to work only on that one larger thumb. This would effectively produce three sizes, the smallest thumb, the larger thumb, and then the panable mouseover zoom effect at the original size. "

I think we are getting closer to a workable tender.

**Comment by Murray-Dawson** [comment]
I have opened the job at https://www.freelancer.com/projects/Software-Architecture-Javascript/Upgrading-the-iNaturalist-image-viewer.html

**Comment by Murray-Dawson** [comment]
On 8 Februray Jude Naveen Raj accepted this job through Freelancer.

**Comment by Murray-Dawson** [comment]
On 8 Februray Jude Naveen Raj accepted this job through Freelancer.

**Comment by kueda** [comment]
Cool. Make sure he knows he should be doing this through GitHub, so he'll
need to fork our repo (preferably in a topic branch), make his changes, and
issue a pull request. If none of that makes sense to you Murray, I assume
it will make sense to Jude.

**Comment by Murray-Dawson** [comment]
Yes, I said to Jude that you guys use GitHub for all code management and communication on this project. I gave this link for him to refer to. We also spoke of the push-pull requests and he has lots of experience with GitHub. He should be starting in a day or so.

**Comment by judenaveenraj** [comment]
Hi i have pulled the code and started working on an implementation. I am making a custom lightbox-like app in a seperate repository. When the functionality is all done, i will integrate it into your project repo and send you a pull request.

**Comment by Murray-Dawson** [comment]
Thanks very much - great to hear that your project is on its way!

**Comment by judenaveenraj** [comment]
https://github.com/judenaveenraj/infini-lightbox

You can track the progress of the project on this repo. It has the gallery plugin that i'm developing. You can have a look. @Murray-Dawson : You can approve and release appropriate milestones that were set on the project as you see the progress. @kueda : The code is a little rough around the edges, I will clean it up as each feature gets completed.

**Comment by kueda** [comment]
Ok. Is there a reason you didn't fork from https://github.com/scaron/prettyphoto?

**Comment by judenaveenraj** [comment]
No reason actually. I had a copy of it locally. And i was testing to see if the functionality can be added easily. I presume there's no issue, because i am doing this as a seperate repo for myself which i will be integrating with your application as part of the freelancer project. Please check the functionality from my repo and let me know if that satisfies your requirements spec. Integration will be done at the end.

**Comment by Murray-Dawson** [comment]
I have had a look at the functionality and great that to see a zoom and pan feature enabled.

It may be better to lock the edges of the white border frame so you don't drag in all the white space. When you click in that white space it greys the image out, which wouldn't happen if the borders were locked.

Also, consider a slightly quicker zoom with the scroll wheel. It may be a bit slow for large images which would need lots of magnification to see their full size.

Will the zoom work well for large image files and does the right click to download save the image at its original full size as we would like?

**Comment by judenaveenraj** [comment]
@kueda Hi one small question. Is the details view always "/photos/{id}"  or is it custom for every image?

@Murray-Dawson And with that all the functionality is for the given project is done. The gallery requires rendering just one line of code in javascript to enable it. I am a javascript expert, not a ruby on rails expert. So i will tell you the exact lines to render and i request you to just add the required initialization code to your project, if that wont be too much trouble. The entire image viewer has been packaged into that one js file.

**Comment by kueda** [comment]
`/photos/:id` *is* custom for every image, because each image has its own id.

**Comment by Murray-Dawson** [comment]
Great to see all the additional functionality on the latest version - looking great Jude! Here is some more feedback:

I noticed a minor bug in Firefox where the + and - buttons ceased to step in increments; they instead went directly from full to default size and vice versa.

The current script does not like running under IE 8 at all - it crashes IE or is exceptionally slow to run with no zoon and pan. Doubt if it is because I opened the index html file from a local copy. (Smooth View Pan and Prettyphoto worked fine from their URLs).

I have not tested the tablet/touch functionality.

Thanks for adding the Tweet button - could you also please also add a "Facebook like" button as part of the social media integration? Hopefully this would be a quick and simple addition as it is on the PrettyPhoto base code.

**Comment by kueda** [comment]
I'll give it a full evaluation when @judenaveenraj gets it integrated into the iNat app. Looks pretty good so far, though I'm not a fan of the social media buttons. Tried it on an iPad mini and it worked the same as a browser. No special touch functionality.

**Comment by Murray-Dawson** [comment]
Thanks @kueda - good to know the script is working on your portable device. Probably don't need to have special touch functionality to swipe to the next image, or touch-drag to enlarge as it works ok with the existing nav elements.

I personally wont use the social media buttons, but it is part of the agreed scope (as a nice-to-have) and included in the Freelancer milestones for @judenaveenraj . Because iNat is so community orientated, my thinking is that some people will like the social media feature on the viewer and we may as well have both Twitter and FB connection rather than just the one. Once that's added and the IE8 bug fixed the script should pretty well be there.

**Comment by judenaveenraj** [comment]
@Murray-Dawson : Okay i will work on the compatibility issue, but there have always been issues with ie8 and javascript packages and most don't even support ie8 because of the current usage statistics for IE8:

As on January 2015: IE8 usage is a mere 1.2% and compatibility for this small percentage is hard.
If i fix the firefox issue , then we would be supporting 98.8% of browsers worldwide. I hope that is enough and feasible.

**Comment by judenaveenraj** [comment]
@Murray-Dawson : For the facebook like button, you need to get me the iframe code from this link : https://developers.facebook.com/docs/plugins/like-button
And for the twitter button you need to set your preferences here and give me the code they provide you back.
https://about.twitter.com/resources/buttons

I have to input the generated code into my code. Please get this done and get back to me.

**Comment by Murray-Dawson** [comment]
Thanks @judenaveenraj . I just tested the script in IE10. It works, but it's also very slow to load in that version. IE is my least favorite browser, and I do appreciate it's tricky to optimize script for all.

However, the project does ask for multiple browser compatibility which we need for the large community of iNat users. We can't provide a replacement script that will cause problems for some users.

Works well in my version of Chrome, with the same minor zoom bug I noticed in Firefox.

**Comment by kueda** [comment]
FWIW, we do not target IE8, and frankly only test in IE when people complain. When we do, we test in IE9 or IE10. IE accounts for 11% of our total traffic, and IE 8 is a distant 4th on the list of IE versions among our visitors.

**Comment by Murray-Dawson** [comment]
I vote to keep the social media functions as simple as possible. The simplest code for the Twitter link    @judenaveenraj provided seems to be:

<a href="https://twitter.com/share" class="twitter-share-button">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

**Comment by Murray-Dawson** [comment]
For the FB button, could you use the simplest "Log in to your Facebook account to like" code as demo'ed at on the example gallery at http://www.no-margin-for-errors.com/projects/prettyphoto-jquery-lightbox-clone/#prettyPhoto ?

**Comment by judenaveenraj** [comment]
@kueda : Can you tell me exactly which views you want the lightbox to be integrated into?

**Comment by judenaveenraj** [comment]
@Murray-Dawson : If i use the generators to create it will use my facebook and twitter developer app ids. Which means if in the future i choose to clean up my facebook developer account (which is probable) your buttons will stop working. Its simple. You just have to sign up for the developer accounts and follow the instructions i provided. After that its simple. Also Please check the inbox in freelancer.com and get back to me on that.

**Comment by kueda** [comment]
Basically anywhere <a href="https://github.com/inaturalist/inaturalist/blob/master/app/helpers/application_helper.rb#L235">`modal_image`</a> is used, so definitely `observations/show` (e.g. http://www.inaturalist.org/observations/1231516), but maybe also taxa/show (e.g. http://www.inaturalist.org/taxa/121025-Laemostenus-complanatus). Maybe also on pages like http://www.inaturalist.org/guide_taxa/293788, which aren't using that modal thing.

**Comment by Murray-Dawson** [comment]
@judenaveenraj : thanks for clarifying the developer accounts for social media integration. I'm only the funder of your new viewer, so it would be far better to have the accounts sitting with the iNat developers so they have full control. Could you please action this @kueda , despite being perhaps a bit luke warm on this feature?

**Comment by kueda** [comment]
I'm not entirely sure what "action" means as a verb, but for the Facebook button all Jude needs, I think, is our Facebook app ID, which is 26558815027 (included as a meta tag on all pages of our website), and I don't think you need any custom stuff for twitter other than the URL of the photo or observation. Our twitter handle is, unsurprisingly, https://twitter.com/inaturalist.

That said, these values can be customized per "site" on iNat (e.g. NatureWatchNZ vs iNaturalist), so you might want to just make these Javascript variables that we can sub in based on the context.

**Comment by Murray-Dawson** [comment]
Awaiting final bug fixes and integration by @judenaveenraj  - hopefully this will be soon

**Comment by Murray-Dawson** [comment]
After many months of inactivity (on my part), I would like to get this project moving again. @kueda - is this image viewer still seen as a useful addition to iNat? The script is still not good in IE (using v.11 on my work machine) and the scroll-wheel zoom is slow.

**Comment by kueda** [comment]
This issue refers to a version of the obs detail view that was replaced several years ago, so I'm going to close it
