### ISSUE TITLE
Can't adjust observation date to a more recent date than what was entered

### ISSUE THREAD

**Issue by ChristopherTracey** [inaturalist/inaturalist#462]
When editing an observation date, one cannot select a date later than then original date entered when using the calendar popup.  For example, if I wanted to change the following to the same day in 2015, rather than 2014, and I clicked the calender icon the right-hand side, the most recent year I could get to would be 2014, and not 2015.

![image](https://cloud.githubusercontent.com/assets/8216371/6010014/186c9be2-aafd-11e4-9e36-c38919a7b9e2.png)

**Comment by kueda** [comment]
This works for me in Firefox on a Mac. What browser and OS are you using?

**Comment by ChristopherTracey** [comment]
I just checked and its still happening for me. Win7, Chrome ver40-something.
