### ISSUE TITLE
Selecting a country on 'Add to a place' spins forwver

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#464]
eg adding US to http://www.inaturalist.org/taxa/silverleaf_whitefly
![screen shot 2015-02-03 at 1 40 51 am](https://cloud.githubusercontent.com/assets/598026/6017743/c712f860-ab45-11e4-98e9-035e9e68de42.png)

**Comment by pleary** [comment]
Looks like this is working now. Would you mind checking when you get a chance?

**Comment by pleary** [comment]
I'm going to call this fixed. Please give an example if anyone disagrees

**Comment by loarie** [comment]
Yes just tested this it's fixed, thanks
