### ISSUE TITLE
ProjectUsers that are project creators of Invite-only-projects are invalid because they are failing user_invited? validation

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#469]
ProjectUsers that are project creators of Invite-only-projects are invalid because they are failing user_invited? validation
https://github.com/inaturalist/inaturalist/blob/master/app/models/project_user.rb#L76
this is causing various problems that rely on saving project users

**Comment by kueda** [comment]
Can you remember any specific problems this is causing?

**Comment by loarie** [comment]
admin's not appearing on leaderboards
