### ISSUE TITLE
use Simple Multimedia Extension in Darwin Core Archives

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#470]
Right now we include a single media URL for each occurrence in a DwC-A, but it doesn't include any separate licensing information, and that doesn't capture the fact that observations often have many images. DwC-A supports an extension called [Simple Multimedia](http://www.gbif.org/occurrence/1050328686) that has this functionality, and GBIF will use it, e.g. http://www.gbif.org/occurrence/1050328686.

This will require getting `dwca.rb` to create an additional CSV for the photos, each row of which will reference its observation using the `coreid` column specified in `meta.xml`. Docs for the vocabulary and semantics are at http://tools.gbif.org/dwca-assistant/ and http://rs.gbif.org/extension/gbif/1.0/multimedia.xml. Here's an example from our friends at GBIF of what the `meta.xml` file might look like using the `coreid` attribute:

```xml
<archive xmlns="http://rs.tdwg.org/dwc/text/" metadata="eml.xml">
  <core encoding="UTF-8" fieldsTerminatedBy="\t" linesTerminatedBy="\n" fieldsEnclosedBy="" ignoreHeaderLines="1" rowType="http://rs.tdwg.org/dwc/terms/Occurrence">
    <files>
      <location>occurrence.txt</location>
    </files>
    <id index="0" />
    <field index="1" term="http://purl.org/dc/terms/type"/>
    <field index="2" term="http://purl.org/dc/terms/modified"/>
    <field index="3" term="http://rs.tdwg.org/dwc/terms/institutionID"/>
    <field index="4" term="http://rs.tdwg.org/dwc/terms/datasetID"/>
    <field index="5" term="http://rs.tdwg.org/dwc/terms/institutionCode"/>
    <field index="6" term="http://rs.tdwg.org/dwc/terms/collectionCode"/>
    <field index="7" term="http://rs.tdwg.org/dwc/terms/basisOfRecord"/>
    <field index="8" term="http://rs.tdwg.org/dwc/terms/dynamicProperties"/>
    <field index="9" term="http://rs.tdwg.org/dwc/terms/occurrenceID"/>
    <field index="10" term="http://rs.tdwg.org/dwc/terms/catalogNumber"/>
  </core>
  <extension encoding="UTF-8" fieldsTerminatedBy="\t" linesTerminatedBy="\n" fieldsEnclosedBy="" ignoreHeaderLines="1" rowType="http://rs.gbif.org/terms/1.0/Image">
    <files>
      <location>image.txt</location>
    </files>
    <coreid index="0" />
    <field term="http://rs.tdwg.org/dwc/terms/occurrenceID"/>
    <field index="1" term="http://purl.org/dc/terms/identifier"/>
    <field index="2" term="http://purl.org/dc/terms/description"/>
  </extension>
</archive>
```

**Comment by kueda** [comment]
Some open questions (possibly for @mdoering):

1. Should the type be `StillImage` or `http://purl.org/dc/dcmitype/StillImage`? EOL asked for the latter for the photos we provide them, but maybe the convention is different for the Simple Multimedia extension
1. Should the identifier really be a URL to the image file if that URL is subject to change? For example, what if we decide to change S3 buckets and the image URL we provided changes from `http://static.inaturalist.org/photos/1234/original.jpg` to `http://static4.inaturalist.org/photos/1234/original.jpg`? Does that mess with GBIF's ability to uniquely identify the image record?

**Comment by mdoering** [comment]
GBIF handles both the full URI and just the string StillImage. If EOL prefers the full URI go ahead and use it. For Darwin Core Archives GBIF in general recommends short values from controlled vocabularies over full URIs. If you need the full URI we recommend to use an extra attribute on the field mapping in  the meta.xml that references the vocabulary the values are drawn from:

{noformat}
  <extension encoding="UTF-8" fieldsTerminatedBy="\t" linesTerminatedBy="\n" fieldsEnclosedBy="" ignoreHeaderLines="1" rowType="http://rs.gbif.org/terms/1.0/Multimedia">
    <files>
      <location>image.txt</location>
    </files>
    <coreid index="0" />
    <field index="0" term="http://rs.tdwg.org/dwc/terms/occurrenceID"/>
    <field default="StillImage" vocabulary="http://rs.gbif.org/vocabulary/dcterms/type.xml" term="http://purl.org/dc/terms/type"/>
  </extension>
{noformat}

Using dc:identifier for the URL to the highest resolution image is crucial for us. Unfortunately there is no better Dublin Core term to use and we preferred an extension made up purely from DC terms. If the urls change over time this is not an issue for us, just change them.

Notice that we have deprecated the rowType http://rs.gbif.org/terms/1.0/Image and recommend http://rs.gbif.org/terms/1.0/Multimedia now. We can still read the Image one, but if possible pelase use the broader Multimedia rowType.

**Comment by carrieseltzer** [comment]
Since it came up here, the gnp site uses the static image urls so if those changed we'd need some warning to 1) make sure those would update or 2) force them to update. Instagram recently moved a bunch of their older stuff which has left us with broken links, but since we're de-emphasizing Instagram anyways we aren't going to update the links. So please let me know if you do change s3 buckets. Thanks!



—

**Comment by kueda** [comment]
Thanks for the feedback @mdoering. One more: should we leave the `associatedMedia` column in the occurrences file?

**Comment by mdoering** [comment]
Probably best to remove it, but it doesnt harm our indexing if both exist
