### ISSUE TITLE
investigate excessive cache clearing

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#473]
DJ does WAY too much cache clearing, so much so that it might negate the advantage of caching in the first place. Starting with the issues @pleary raised in #449, look into caches that we should probably drop (e.g. cached components), and try to find the sources of those duplicate clearing jobs.

**Comment by pleary** [comment]
I'm hopeful that change to `LifeList.refresh_listed_taxon` (the final form is in 15a3d02a199facc321622f66a85ef86a25cff88c after a couple commits) will remove a double cache clear for deleted life list entries. It was previously saving the record then checking if it should be deleted, each step was clearing caches. I changed it to directly call the before_save filter we were depending on, and moved the destroy check above the save to ensure the record is saved only once.

Another fix was the removal of the `ListedTaxonSweeper` in 30be68c4a341fef7a76adc9793e2641da8695f1a. `ListedTaxon` has an `after_commit :expire_caches` which will clear the cache after any save or deletion. The sweeper was calling `expire_listed_taxon(listed_taxon)`, which is just `listed_taxon.expire_caches`. That means the caches were getting cleared, then the record was saved and caches were cleared again.
