### ISSUE TITLE
query for observations fields for research grade observations only

### ISSUE THREAD

**Issue by jhpoelen** [inaturalist/inaturalist#475]
Hi! 

I am using http://www.inaturalist.org/observation_field_values.json?type=taxon to retrieve any taxon observation fields from iNaturalist. In order to limit the results to research grade observations only, I am currently doing a query per observation (http://www.inaturalist.org/observations/[observationId].json) and this seems a bit inefficient.

Is there a way to restrict the observation_field_values query result to include research grade observations only? 

Thanks for all the good work! 
-jorrit

**Comment by kueda** [comment]
Ok, this should now work: http://www.inaturalist.org/observation_field_values.json?type=taxon&quality_grade=research

**Comment by jhpoelen** [comment]
Thanks!
