### ISSUE TITLE
organizations

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#479]
Currently we have no way to recognize groups of people beyond the scope of projects, which is a bit limiting, b/c organizations might have many projects, so the action of trusting that group might have to happen multiple times. It would also be nice to recognize institutional affiliations. It might be nice to charge for this feature, though we could grandfather in some existing projects. Or maybe we could charge if you have more than n users.
- [ ] add a new Organization model
- Organization `has_many :organization_users`
- Organization `has_many :users, through: organization_users`
- Organization should have an icon, title, description
- Organizations should only be creatable by site admins
- [ ] display Organization affiliations on user profiles

organizations/new
- [ ] only available to site admins
- [ ] normal CRUD

organizations/show
- [ ] show title, logo, description, users
- [ ] UI for adding users to organizations (we could do an invite model here, but I assume since we are trusting organizations we can trust them to only add the right people)

OrganizationUser model
- [ ] add position column, `validates_uniqueness_of :position, scope: [:organization_id, :user_id]`
- [ ] user's first OrganizationUser is their primary affiliation

Am I missing anything? I'm making a separate issue for the trust thing.

**Comment by loarie** [comment]
This looks good to me. Would we need a UI for linking organization_users with organizations, or would that be something site admins do? If so, than should there be a role associated with observation user for the primary organization user which can get passed among organization users if said person leaves,  or should all organization_users create destroy these associations within their org?

**Comment by kueda** [comment]
Since we are restricting access to this feature let's just keep it simple for now. One user creates and "owns" the organization and can add people to the organization, individual can't add or remove themselves from organizations. We'll probably want to do that eventually, but let's not over-engineer this at first.

Updated the spec with UI issues, though.

**Comment by loarie** [comment]
Ok - looks good to me

**Comment by loarie** [comment]
NPS is interested in having some sort of branding, link back to their website, and mechanisms for keeping track of their set of places on iNat in return for directing park visitors to the relevant place page on iNat. Is it too niche to expand this to have orgs have many places (restricted to a new kind of place 'protected area') and to use that to (1) display the org logo on the place page, (2) display the URL on the place page, (3) use the ;org has_many places' relation to keep track of which places are relevant to their org?

**Comment by kueda** [comment]
I think that's both out of scope for this particular issue and could use some broader community feedback, so maybe a post to the Google Group? If *all* they want is branding then I think I'm personally ok with it, but if they want actual restrictions on things like the boundary or the checklist, then I'm hesitant, so mention exactly what kind of controls you think they want when you post.

**Comment by pawsons** [comment]
Hi Kenichi/Scott,

Sorry but I really should follow the gitub stream more closely as there are definitely some clear benefits   for particular things we want to do in NZ from many of your threads. This one in particular, guess I am very late to the 'party' so to speak with regards to this. I will mull over and distribute a more comprehensive response to your current thread. Out of interest can you please update as to how far this functionality has progressed since Feb?

Many thanks

Steve

**Comment by loarie** [comment]
Hi Steve, there's been no progress on this functionality since Feb. Look forward to your feedback!
