### ISSUE TITLE
trust between users and organizations

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#480]
The only thing that requires trust on the site is private coordinates, and currently we handle that through projects. The problems with that are
- there's not way to participate in a project without trusting all the project curators
- the people you trust with your private coordinates may not have a project
- organizations who operate multiple projects need to receive that trust repeatedly for every project

So instead of trusting projects, let's start trusting people and organizations (#479). Here's a spec proposal, feel free to propose other implementations:
- [x] add `preference` to the `Friendship` model (`trusted`? `share_coordinates`?)
- [ ] add some kind of join model between User and Organization the indicates that you trust that organization, maybe TrustedOrganization
- [x] any time we decide whether or not someone can view coordinates (maybe just `Observation#coordinates_viewable_by?`)

Depends on #479, related to #237.

**Comment by naturalistcharlie** [comment]
i like this idea, solves a lot of potential and existing issues.

On Thu, Feb 19, 2015 at 8:40 PM, Ken-ichi <notifications@github.com> wrote:

> The only thing that requires trust on the site is private coordinates, and
> currently we handle that through projects. The problems with that are
>
>    - there's not way to participate in a project without trusting all the
>    project curators
>    - the people you trust with your private coordinates may not have a
>    project
>    - organizations who operate multiple projects need to receive that
>    trust repeatedly for every project
>
> So instead of trusting projects, let's start trusting people and
> organizations (#479
> <https://github.com/inaturalist/inaturalist/issues/479>). Here's a spec
> proposal, feel free to propose other implementations:
>
>    -  add preference to the Friendship model (trusted? share_coordinates?)
>    -  add some kind of join model between User and Organization the
>    indicates that you trust that organization, maybe TrustedOrganization
>    -  any time we decide whether or not someone can view coordinates
>    (maybe just Observation#coordinates_viewable_by?)
>
> Depends on #479 <https://github.com/inaturalist/inaturalist/issues/479>,
> related to #237 <https://github.com/inaturalist/inaturalist/issues/237>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/480>.
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by loarie** [comment]
could we piggy back observation/photo use licenses on this as well, or should they stay in the creation of project members. By that I mean if I make my observations/photos all rights reserved to the public, is there a way I could use this system to create an attribution license for use by a person or organization (e.g. I license NPS to use my photos if they attribute me but don't want to apply any CC license for use by the public)?

**Comment by naturalistcharlie** [comment]
It also brings up the question of access to auto obscured data.  I might
trust "bob's orchid theft affectionados' with my personal data but that
doesn't mean their project should necessarily have access to data that is
obscured due to being rare/at risk.  I know there are many issues with
this... I've never seen a project where this has been abused, and
iNaturalist can't stop people from exchanging data elsewhere (except I
think we reduce problematic sharing by raising awareness). So I don't think
it's a big problem now. but I have joined projects where I had no idea who
the person was or what their goals were and wondered about whether it was a
good idea to share these auto obscured observations.  (To be honest, I
don't add things that I'm really worried about, but others might).

Not urgent and sorry if too off topic, but I think it's worth thinking
about.

On Sun, Feb 22, 2015 at 5:23 PM, Scott Loarie <notifications@github.com>
wrote:

> could we piggy back observation/photo use licenses on this as well, or
> should they stay in the creation of project members. By that I mean if I
> make my observations/photos all rights reserved to the public, is there a
> way I could use this system to create an attribution license for use by a
> person or organization (e.g. I license NPS to use my photos if they
> attribute me but don't want to apply any CC license for use by the public)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/480#issuecomment-75466864>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by loarie** [comment]
Whats the proposal here for how users would trust users/orgs? I assume there would be a trust button next to follow on user/org show pages?

**Comment by kueda** [comment]
At a minimum. That's what "add some kind of join model between User and Organization" was about. Obviously will be fleshed out when we do this.

**Comment by kueda** [comment]
User-to-user trust happened in https://github.com/inaturalist/inaturalist/pull/2120. I don't think the organizations feature has a whole lot of support within the team, so I'm closing this.
