### ISSUE TITLE
taxon search can show duplicates

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/inaturalist#494]
![taxon_duplicates](https://cloud.githubusercontent.com/assets/515947/6476591/d40fe0bc-c1cc-11e4-9875-02b44abfc060.png)

**Comment by alexshepard** [comment]
minor issue. these are not duplicate taxa, both options are for taxon 350511

**Comment by kueda** [comment]
I *think* this has something to do with delta indexing in Sphinx... which makes it really hard to replicate.

**Comment by pleary** [comment]
I'm going to call this one fixed. We're no longer using Sphinx, and Elasticsearch doesn't have any delta indices, and uses primary keys of records to avoid duplicates. This particular example is working now, so until we have another example of this bug, I believe this is resolved.
