### ISSUE TITLE
GBIF API/links need to be updated

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#495]
GBIF changed their API on their end which leaves taxon_links and the map overlay and map overlay link broken. Referencing #420 incase we can hold off fixing these until this update
![screen shot 2015-03-04 at 11 14 18 am](https://cloud.githubusercontent.com/assets/598026/6491057/a3161d8a-c25f-11e4-90b2-65a7e65b1ca7.png)
![screen shot 2015-03-04 at 11 13 57 am](https://cloud.githubusercontent.com/assets/598026/6491058/a424daf4-c25f-11e4-8c80-585c98d359b7.png)

**Comment by kueda** [comment]
GBIF data on maps was addressed in https://github.com/inaturalist/inaturalist/pull/503, taxon link just isn't going to work until they implement some kind of name-based URL scheme, so I just deleted that taxon link.
