### ISSUE TITLE
replace sphinx with elastic search

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#508]
The need to regularly index sphinx and the (potentially) associated stability problems suggest we may have outgrown sphinx, and we need something a bit more robust and scalable on top of postgres anyway, so let's replace sphinx with ES.

**Comment by pleary** [comment]
I see this playing out something like this.
  - Evaluate functionality of Elasticsearch to see if it can replace everything we use Sphinx for
  - Connect ES with the Rails codebase
    - Define index structures, analyzers, search helpers, etc
  - Update features which depend on sphinx to use ES instead
  - Install production ES instance
  - Update production code so new records are writing to ES (no Sphinx features removal yet - we just want the model bindings now to get ES in sync)
  - Populate ES retroactively with old records
  - Verify ES is staying up-to-date, everything running smoothly
  - Update production code to swap Sphinx usage for ES
  - Verify everything working well
  - Remove sphinx
    - stop all crontabs
