### ISSUE TITLE
replace updates persistence with elastic search

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#509]
Our notifications system isn't great, and the updates table in particular is swelling to unmanageable proportions. As a step toward overhauling the entire system, how about replacing the updates table with Elastic Search. Persistence of update records isn't critical, and ES does disk-based persistence anyway. Hopefully it will improve performance of retrieval.

**Comment by pleary** [comment]
we completely re-wrote updates into update_actions and update_action_subscribers
