### ISSUE TITLE
Query observations by custom field transect_id 

### ISSUE THREAD

**Issue by JoanGi** [inaturalist/inaturalist#510]
Hi!

We are developing some new functionailities for the Drupal Inat plugin. We are working with an extra field called transect_id. By now, we have to query to all the observations of a project to get the observations related to this transect_id. We were wondering if it's possible to direct filter the query by this field (transect_id). The aim is to get observations not necessary related with projects, and highly improve the performance.

Thanks for the great work!!

**Comment by kueda** [comment]
I think what you want is doable, but not documented: http://www.inaturalist.org/observations.json?field:transect_id=

Is that what you need? E.g. filtering all observations by an observation field?

**Comment by JoanGi** [comment]
Thanks! works like a charm!

**Comment by JoanGi** [comment]
Until friday this query (with GET method) " http://www.inaturalist.org/observations.json?field:transect_id=67-48  " was working perfectly. But now get an "Internal Server Error" from. 

Has been any change during the last week that can explain this?

Thank you very much!!

**Comment by pleary** [comment]
There have been a few changes to search recently. I think I found the problem, and am currently testing the fix. If all goes well we will deploy a fix later today. Thanks for the report

**Comment by kueda** [comment]
As far as I can tell this is fixed.
