### ISSUE TITLE
'today' created_on value not behaving as expected

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#512]
I expect that created_on=today here http://www.inaturalist.org/observations/stats to encompass right now i.e. show observations happening right now regardless of what boundaries we are using to bound today/right now.

However, while the boundaries on a day are currently set based on UTC meaning that any given day (e.g. 2015-03-27) displays observations from 0:00:00 - 23:59:59 UTC, the created_on=today does not always show the day encompassing right now.

For example, at the time of this writing right now is 3:51:14 UTC 2015-03-27 or 8:51:14 -0600 2015-03-26 here in CA but http://www.inaturalist.org/observations/stats?created_on=today is showing data from from 0:00:00 - 23:59:59 UTC 2015-03-26 (which has passed) whereas observations posted right now are counting on 0:00:00 - 23:59:59 UTC 2015-03-27 (e.g. 'tomorrow').

'today' created_on value not behaving as expected
I expect that created_on=today here http://www.inaturalist.org/observations/stats to encompass right now i.e. show observations happening right now regardless of what boundaries we are using to bound today/right now.

However, while the boundaries on a day are currently set based on UTC meaning that any given day (e.g. 2015-03-27) displays observations from 0:00:00 - 23:59:59 UTC, the created_on=today does not always show the day encompassing right now.

For example, at the time of this writing right now is 3:51:14 UTC 2015-03-27 or 8:51:14 -0600 2015-03-26 here in CA but http://www.inaturalist.org/observations/stats?created_on=today is showing data from from 0:00:00 - 23:59:59 UTC 2015-03-26 (which has passed) whereas observations posted right now are counting on 0:00:00 - 23:59:59 UTC 2015-03-27 (e.g. 'tomorrow').

**Comment by pleary** [comment]
This ticket was a little confusing, so I'll explain where we should be right now. Right now, all observations will be indexed with created_at stored as UTC time. When a search is performed on 'today', we will use the UTC representation of 'now', and search for all observations created on the same UTC day as 'now'. Searches on 'today' will not factor in the time zone of the requestor - everything will be based on UTC.

Does that sound right? This is live in production now if you want to test it and let me know if this is working properly.

**Comment by carrieseltzer** [comment]
What if it looked for observations created_on_utc in the last 24 hours? Basically it could take "now" time in UTC, subtract 24 hours (or change the date to the previous day, whichever it easier). Then you would be sure to get everything within the last day. As currently explained above, it sounds like someone searching just after midnight UTC might not see much because that "day" will have just started. This way people will always see the most recent day's worth of observations added.

**Comment by pleary** [comment]
That would certainly be easy to do. You're right, as it stands right now there will be times the numbers are quite low and times the numbers are quite high, depending on what time of day you look at the stats. I agree it would make a little more sense for it to be a 24 hour window, but this would be a change to the functionality and I'm not sure how many people expect the current functionality of created_on=today. For example you wouldn't be able sit back and watch the numbers go up, and you might refresh the page and see that the numbers have gone down because a large batch of observations fell outside the 24 hour window.

**Comment by carrieseltzer** [comment]
You're totally right. Sorry, I didn't see that this was specifically with reference to the stats page where it would be confusing to sometimes see the number drop.

What if it takes the current date based on the user's profile settings, and then uses that date to query by date-only (using observed_on)? This way, no matter where you are in the world, you'd see the count increasing based on the day *you* are currently experiencing.

**Comment by kueda** [comment]
created_at=today is not a documented part of our API so I wouldn't worry
about changing it, Patrick. I'm fine with making it use the time zone of
the viewer.

**Comment by loarie** [comment]
I don't think we should use the timezone of the viewer because then there's no absolute yardstick to compare e.g. if I in CA say to Cullen in Texas there were X observations posted yesterday but Y today, X & Y will be relative. I suggest using UTC to define the day

**Comment by kueda** [comment]
Well that's how it works now, according to my understanding of how I coded
it and Patrick's description, so can we close this?

**Comment by loarie** [comment]
no because there's a bug as explained in the issue where its not properly showing me the UTC day that 'now' is in. let me know if I need to take another crack at explaining the bug

**Comment by pleary** [comment]
Scott, I believe I fixed the bug. See my comment above https://github.com/inaturalist/inaturalist/issues/512#issuecomment-101407560 . If what I described is not correct, then I would appreciate a re-wording of the acceptance criteria. It would be particularly helpful to have an example

**Comment by pleary** [comment]
Sounds like this is fixed

**Comment by loarie** [comment]
I think the easiest way for me to test this is to wait 1.5 hrs until 5PM PST today (ie June 3 UTC), will try to remember to do this

**Comment by loarie** [comment]
Just checked and I'm satisfied. So now it looks like 'today' is using the UTC reference frame. So here in CA it is still 5:30 PST on June 2, but its now June 3 UTC. So if I check http://www.inaturalist.org/observations/stats?created_on=today today defined by the boundaries of June 3 in UTC. 

I'm not saying this is the 'right' way to do this, but the but I was referring to where my observations posted right now weren't showing up in 'today' is no longer a problem
