### ISSUE TITLE
Cannot save or add observations to project--- need fix

### ISSUE THREAD

**Issue by zooga1961** [inaturalist/inaturalist#513]
project name: Biodiversity of Cedar Ridge Preserve, Dallas TX    
 ack!   no one can add any observations to this project     They either get a "shark" telling them something went wrong or they get a spinning wheel.     I tried multiple  ways    
1,  select project from within an observation....  result,, spinning wheel
2. add observation from within the project.. result  "shark"
3. add observation via Place can do but when trying to add to the project from there... i get the spinning wheel 
4, bulk add from my observations result is spinning wheel

i had one of my contributors notify me early this morning that he could not add observations to the project,,,

i tried looking around in the project itself   and even tried editing the location,,,,still spinning wheel

Please help.   Thanks in advance for your assistance with fixing
Deborah- 
admin for the Biodiversity of Cedar Ridge Preserve- Dallas TX project,

**Comment by loarie** [comment]
Hi Deborah - 

The issue here was that somehow the place rule was missing a place it just said 'must be observed in Place'. I removed that rule and re added it with the Cedar Ridge Preserve place and now it works:
![screen shot 2015-03-30 at 4 20 25 pm](https://cloud.githubusercontent.com/assets/598026/6909395/7b1676b8-d6fa-11e4-8be2-9e8a1e8db7ed.png)

But there's a bug here in that you shouldn't be able to add a place rule without specifying a place. Can you recall anything weird that happened, for instance did you maybe add a place rule with one place and then delete the place?

**Comment by zooga1961** [comment]
The only think I can think of is that last week it was brought to my attention there were several places in iNat named Cedar Ridge Preserve located in Dallas Texas. USA.     

When I set up the project there wasn't a place in iNat named Cedar Ridge Preserve in Dallas TX and so I had to create the place.. taught myself how to do the boundaries and everything....

. I was getting complaints from people (newbies) who were trying to navigate around for the first time and kept going to the wrong place .named Cedar Ridge Preserve in Dallas Texas.. and not finding the project   

(never mind that there is a project tab at the top of the page and they can "search" for the project ---SIGH }

Not wanting anyone to become frustrated and quit...  I merged all  the Cedar Ridge Preserves in, Dallas Texas locations into one place.    (there is only ONE Cedar Ridge Preserve in Dallas TX) 
and by doing so I unknowingly created a whole new problem.

 I am going to say that I am the cause of the problem... LOL   THANK YOU!!!  
 I know just enough to be dangerous.......   Deborah

**Comment by loarie** [comment]
Hi Deborah - no you didn't cause the problem - you helped uncover a bug - quite the opposite. I suspect that the merge tool has a bug where its not properly updating associated project place rule, hopefully this issue will be a reminder to look into this more in the bug queue. In the meantime, glad your issue is fixed

**Comment by zooga1961** [comment]
Hey Scott   -    Any reasoning why we can’t add our observation to a place?.. unless you add it directly to the place when entering it…you can’t go back and add it after.… iNat lets you import to a place from flicker, facebook and your photos… but not from your observations?   Things that make you say hmmmm.

 

Deborah

**Comment by loarie** [comment]
You mean project not place right?

**Comment by naturalistcharlie** [comment]
I am not Scott but... Most places are pretty huge meaning the location
would be hard to display in Inat's system. Also there's no way to map it,
someone would have to come up with an algorithm to make the uncertainty
circle the right size.
It's an interesting idea but I wouldn't use it. Personally I always want to
map my locations for stuff.

On Monday, March 30, 2015, Deborah Nelson <notifications@github.com> wrote:

> Hey Scott - Any reasoning why we can’t add our observation to a place?..
> unless you add it directly to the place when entering it…you can’t go back
> and add it after.… iNat lets you import to a place from flicker, facebook
> and your photos… but not from your observations? Things that make you say
> hmmmm.
>
>
>
> Deborah
>
>
>
>
>
>
>
> From: Scott Loarie [mailto:notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>]
> Sent: Monday, March 30, 2015 8:39 PM
> To: inaturalist/inaturalist
> Cc: Deborah Nelson
> Subject: Re: [inaturalist] Cannot save or add observations to project---
> need fix (#513)
>
>
>
> Hi Deborah - no you didn't cause the problem - you helped uncover a bug -
> quite the opposite. I suspect that the merge tool has a bug where its not
> properly updating associated project place rule, hopefully this issue will
> be a reminder to look into this more in the bug queue. In the meantime,
> glad your issue is fixed
>
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/inaturalist/inaturalist/issues/513#issuecomment-87895319>
> . <
> https://github.com/notifications/beacon/ALL1Lm4WWQ2JHS2JF8dmuZhYw1gSXbqXks5n6fIZgaJpZM4D3aO7.gif>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/513#issuecomment-87899973>
> .
>


-- 
Sent from Gmail Mobile

**Comment by zooga1961** [comment]
No I mean place

Thank you for the opportunity to be of service to you.
 
Deborah Nelson 
principal
 
Deborah Nelson & Associates LLC
3824 Cedar Springs Rd.  Ste.  538
Dallas, TX  75219
e: deborah@dn-assoc.com
p: 469.583.7781

Representing Architectural Design Products in Texas & Oklahoma
 
Jockimo - Advanced Architectural Products: Specialty Glass Flooring, LiquidLava, ImagenGlass & More 

OKITE - Visions Made Real: Natural Quartz Surfacing

O_KERA - by OKITE.  Large format (10’ long x ¼” thick) Ceramic Slab

Seeyond - Imagination Delivered: Walls, Facings, Clouds, Enclosures, Columns  (North Texas)

**Comment by zooga1961** [comment]
I agree however it is interesting to note that you can add an observation to a place directly, import photos from flicker & Facebook but you cannot add from your existing observations.   Just curious..

Deborah

**Comment by loarie** [comment]
Hi Deborah, iNat uses the coordinates to detect what places the obs falls
in (based on the boundary of the place) and then displays those places on
the obs page and displays those obs on the place page. But thats the extent
to which an observation can be linked to a place - just indirectly through
its coordinates

On Tue, Mar 31, 2015 at 9:09 AM, Deborah Nelson <notifications@github.com>
wrote:

> I agree however it is interesting to note that you can add an observation
> to a place directly, import photos from flicker & Facebook but you cannot
> add from your existing observations. Just curious..
>
> Deborah
>
> Sent from my iPhone
>
> > On Mar 31, 2015, at 7:08 AM, Charlie <notifications@github.com> wrote:
> >
> > I am not Scott but... Most places are pretty huge meaning the location
> > would be hard to display in Inat's system. Also there's no way to map it,
> > someone would have to come up with an algorithm to make the uncertainty
> > circle the right size.
> > It's an interesting idea but I wouldn't use it. Personally I always want
> to
> > map my locations for stuff.
> >
> > On Monday, March 30, 2015, Deborah Nelson <notifications@github.com>
> wrote:
> >
> > > Hey Scott - Any reasoning why we can’t add our observation to a
> place?..
> > > unless you add it directly to the place when entering it…you can’t go
> back
> > > and add it after.… iNat lets you import to a place from flicker,
> facebook
> > > and your photos… but not from your observations? Things that make you
> say
> > > hmmmm.
> > >
> > >
> > >
> > > Deborah
> > >
> > >
> > >
> > >
> > >
> > >
> > >
> > > From: Scott Loarie [mailto:notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>]
> > > Sent: Monday, March 30, 2015 8:39 PM
> > > To: inaturalist/inaturalist
> > > Cc: Deborah Nelson
> > > Subject: Re: [inaturalist] Cannot save or add observations to
> project---
> > > need fix (#513)
> > >
> > >
> > >
> > > Hi Deborah - no you didn't cause the problem - you helped uncover a
> bug -
> > > quite the opposite. I suspect that the merge tool has a bug where its
> not
> > > properly updating associated project place rule, hopefully this issue
> will
> > > be a reminder to look into this more in the bug queue. In the meantime,
> > > glad your issue is fixed
> > >
> > > —
> > > Reply to this email directly or view it on GitHub <
> > >
> https://github.com/inaturalist/inaturalist/issues/513#issuecomment-87895319
> >
> > > . <
> > >
> https://github.com/notifications/beacon/ALL1Lm4WWQ2JHS2JF8dmuZhYw1gSXbqXks5n6fIZgaJpZM4D3aO7.gif
> >
> > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/inaturalist/inaturalist/issues/513#issuecomment-87899973
> >
> > > .
> > >
> >
> >
> > --
> > Sent from Gmail Mobile
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/513#issuecomment-88145958>
> .
>



-- 
--------------------------------------------------
Scott R. Loarie, Ph.D.
Co-director, iNaturalist.org
California Academy of Sciences
55 Music Concourse Dr
San Francisco, CA 94118
--------------------------------------------------

**Comment by zooga1961** [comment]
Thanks.  

Thank you for the opportunity to be of service to you.
 
Deborah Nelson 
principal
 
Deborah Nelson & Associates LLC
3824 Cedar Springs Rd.  Ste.  538
Dallas, TX  75219
e: deborah@dn-assoc.com
p: 469.583.7781

Representing Architectural Design Products in Texas & Oklahoma
 
Jockimo - Advanced Architectural Products: Specialty Glass Flooring, LiquidLava, ImagenGlass & More 

OKITE - Visions Made Real: Natural Quartz Surfacing

O_KERA - by OKITE.  Large format (10’ long x ¼” thick) Ceramic Slab

Seeyond - Imagination Delivered: Walls, Facings, Clouds, Enclosures, Columns  (North Texas)

**Comment by pleary** [comment]
Seems like this is resolved
