### ISSUE TITLE
improve date display for 24 hour bioblitzes

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#518]
Currently, the way the start/end times for BioBlitz projects are displayed is as follows:

If duration <= 1 day
 display as:
  April 09, 2015, 9:00 AM - 5:00 PM PDT
else if duration > 1 day
 display as:
  April 09, 2015 - April 10, 2015

A problem is that a very common use case is the 24 hr Bioblitz, e.g. April 09, 2015, 4:00 PM - April 10, 2015 4:00 PM PDT. This currently displays as April 09, 2015, 4:00 PM - 4:00 PM PDT
![screen shot 2015-04-08 at 1 08 26 pm](https://cloud.githubusercontent.com/assets/598026/7055113/e59391b8-ddf5-11e4-8024-c3572572b0db.png)
which is understandably confusing and I've gotten at least two pings about this from confused 24-hour BioBlitz coordinators

since this is such a common use case, I propose changing the display to:

If duration < 1 day
 display as:
  April 09, 2015, 9:00 AM - 5:00 PM PDT
else if duration = 1 day
 display as:
  April 09, 2015, 9:00 AM - April 10, 9:00 AM PDT
else if duration > 1 day
 display as:
  April 09, 2015 - April 10, 2015

Thoughts?

**Comment by kueda** [comment]
Sounds fine to me.
