### ISSUE TITLE
Facebook Sign In Failing

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#519]
Cannot sign in with Facebook after making multiple attempts.

**Comment by kueda** [comment]
Working for me, so we'll need more info than that: error message, screenshots, etc.

**Comment by loarie** [comment]
I've always had problems with Facebook login - currently using v.2.5.3 build 93 I'm getting this on 'Log in with Facebook'
![photo 1 8](https://cloud.githubusercontent.com/assets/598026/7056046/5adaa388-ddfd-11e4-8a8d-f7892f0ac57c.PNG)
In the past, I've been able to fix some login problems by messing with Privacy settings in my iPhone Settings app but I don't see iNat as an option now:
![photo 2 10](https://cloud.githubusercontent.com/assets/598026/7056047/5bdc65c8-ddfd-11e4-9aa8-455de3bd7246.PNG)

**Comment by kueda** [comment]
Scott, that's a problem with the iOS app. Different repo. I assume @joellebel issue is with the website.

**Comment by loarie** [comment]
sorry didn't see that

**Comment by joellebel** [comment]
Closing this issue because it's filed under the wrong location. Do not have permissions or access to delete it.
