### ISSUE TITLE
Search for "captive=false" no longer working

### ISSUE THREAD

**Issue by tnywlls** [inaturalist/inaturalist#524]
For at least the last 12 hours searches trying to exclude captive/cultivated observations don't work - exactly the same observations are returned when selecting "any" or "no" for the "Captive / cultivated" option.  Selecting the "yes" button does appear to function though.  Here is an example search that should return no observations (as all Ostriches in NZ are captive/cultivated and all observations have been marked as such):
http://naturewatch.org.nz/observations?utf8=%E2%9C%93&q=&search_on=&quality_grade=any&captive=false&place_id=&swlat=-55.956&swlng=160.6&nelat=-25.901&nelng=-171.25&taxon_name=Struthionidae&taxon_id=20523&day=&month=&year=&order_by=observations.id&order=desc&rank=&hrank=&lrank=&site=&tdate=&d1=&d2=&filters_open=true&view=table

I have tested this with a variety of searches through both iNaturalist.org and the naturewatch.org.nz domain.

--Tony

**Comment by tnywlls** [comment]
I also note that if you select the "any" radio button, it is shown as cleared again when the results are displayed (the other 'any' radio buttons on the search page don't do this)

**Comment by pleary** [comment]
Thanks for the report Tony. I just committed a fix for this bug, which will be released later today. I'll let you know when the fix is out so you can test for yourself and let us know if everything is working as you'd expect.

**Comment by tnywlls** [comment]
Thanks Patrick, just tested it and seems to be working great.
