### ISSUE TITLE
Allow remote iframes

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#527]
Cullen Hanks, Peter Obering, and Carrie Seltzer are all working on projects that want to be able to iframe some parts of iNaturalist. Right now, the server responds to this page (http://greatnatureproject.org/events/world-parks-congress/map/) like this: 
X-Frame-Options:SAMEORIGIN 

Which produces this error in the console: 
Refused to display 'http://www.inaturalist.org/observations/map#14/-33.843/151.075&#39; in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'. 

From Peter: Error: Load denied by X-Frame-Options: https://www.inaturalist.org/observations/user_stats?projects[]=herps-of-texas does not permit cross-origin framing.

See also commentary from the google group: https://groups.google.com/forum/#!topic/inaturalist/knvYBGf-3tY

Can you allow iframing again?

**Comment by kueda** [comment]
K, so that's URLs like  `/observations/map` and `/observations/user_stats`. Any others? I was actually going to fix this a little while ago and it slipped my mind, so apologies for that.
