### ISSUE TITLE
Observation components on places/show not translated on Naturalista

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#529]
On gateways and when languages are changed, places on the site that show common names are localized as in:
![screen shot 2015-04-17 at 11 44 43 am](https://cloud.githubusercontent.com/assets/598026/7208650/37965d9e-e4f7-11e4-8253-5b59a35a514b.png)
Recently, this stopped happening on the observation component of places/show -> species guide
![screen shot 2015-04-17 at 11 44 53 am](https://cloud.githubusercontent.com/assets/598026/7208648/36827348-e4f7-11e4-94b8-2c37f0e8ced0.png)

**Comment by kueda** [comment]
There are no observation components visible on that screenshot of places/show. Are you talking about the listed taxa, e.g. "Barred Yellow" instead of something in Spanish?

**Comment by loarie** [comment]
correct

**Comment by kueda** [comment]
When I go to http://naturalista.conabio.gob.mx/places/morelos when signed out I see mostly Spanish names. Maybe this is something intermittent. If you see it again, please bug me so I check it out sooner.
