### ISSUE TITLE
Slugs no longer updating when project title changes

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#531]
Received complaint and was able to reproduce myself by changing the title of my project
'commercial use of biodiversity'
http://www.inaturalist.org/projects/commercial-use-of-biodiversity
'commercial uses of biodiversity'
however slug did not update to
http://www.inaturalist.org/projects/commercial-uses-of-biodiversity

**Comment by carrieseltzer** [comment]
I just want to chime in and say from my perspective that this is a feature, not a bug. Alternatively (and probably better all around), I'd like to have manual control over what the slug should be.

(I fretted for ages about adding the apostrophe to the Great Nature Project for fear of breaking links but then was thrilled when I realized it wouldn't change the slug.)

**Comment by kueda** [comment]
The way it's supposed to work is that slugs update without breaking URLs. If you change your project title from "Thing One" to "Thing Two", URLs like www.inaturalist.org/projects/thing-one should redirect to www.inaturalist.org/projects/thing-two. That's certainly how it was working originally.

**Comment by loarie** [comment]
looks fixed http://www.inaturalist.org/projects/commercial-uses-of-bio-diversity
