### ISSUE TITLE
Oauth google login for iNat account not working on Naturalista

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#532]
Should I be able to login to Naturalista using the same credentials as iNat? I use my Google account for iNat. I CAN login that way to naturewatchNZ.

Here's the error I got. 
![screen shot 2015-04-22 at 5 54 11 pm](https://cloud.githubusercontent.com/assets/7501183/7286304/f0fa1774-e918-11e4-8049-da00b2c78497.png)

**Comment by kueda** [comment]
Gar, forgotten config change. Can you give it another try? It just worked for me after I made the change to our Google API setup.

**Comment by carrieseltzer** [comment]
Works now! Thanks Ken-ichi!
