### ISSUE TITLE
'In place' criteria differ for obs search and project place rules

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#535]
These observations:
http://www.inaturalist.org/observations/111085
http://www.inaturalist.org/observations/15730
are returned by observations?place_id=5745
even though neither pass the 'must be in place rule' for place_id=5745

I'm not sure what's causing the discrepancy with the former
But the latter has public coordinates in the boundaries but not private coordinates, so there the bug seems to be that observations?place_id=5745 uses public rather than private coordinates

**Comment by pleary** [comment]
The first observation looks to be about 1 or 2 meters outside the boundary of that place. Elasticsearch's geo filtering isn't 100 percent precise, and I think I'm not even using the most precise indexing of shapes to save on memory while searching. Is it an big issue if we are off by a meter or two for place searches?

The second observation is no longer being returned, perhaps as a result of #554 being fixed

**Comment by pleary** [comment]
This should be fixed now. Regardless of whether we're searching the DB or ES, we should get the exact same results for observations in a place
