### ISSUE TITLE
Combining a bulk invitation to join a project with the sign-up tool for inaturalist

### ISSUE THREAD

**Issue by pawsons** [inaturalist/inaturalist#537]
Hi Kenichi/Scott,

We are in the process of ramping up our efforts to get all of these forestry folk in NZ working on looking up records. I have been a bit hampered in how to go about this given a recent change in position from one of the key players. This change is that they now want to include a group called the Farm Foresters, this is great as it is all the small forest owners around NZ and this means we will really get to the grass roots of forestry. Great outcome, however the result is that we are going to ask about 2,000 people if they want to join the forestry project.  This is a good opportunity to get new people into the community, however it is a bit of a logistical headache as most of them are not members of NatureWatch/inaturalist to being with.

As such I was wondering how difficult it would be to modify the project invite tool to simultaneously invite people to join NatureWatch/inaturalist?  That way we get around the awkward process of asking people to sign up to NatureWatch/inaturalist, subsequently advising us of the username they have chosen and then invite them to the project. With an email list of 2,000 potential people even if we get 5% on board that is still 100 manual transactions.

Would be really interested to hear your thoughts on this as it is something that is likely to be of use for many people setting up new projects where the community of interest is largely unaffiliated with inaturalist.

Many thanks for all your great work to date.

Steve Pawson

**Comment by loarie** [comment]
Hi Steve, I haven't personally ever used the invite-only feature and to my knowledge, you guys are the only folks using it, so I can't speak to whether it would be useful. My philosophy is to wait to build things until there's a clear problem, and its still not clear to me that there was a problem of unwelcome people joining problems. I ran my Berkeley class for two years as an iNat project and never had anyone not in the class join the projecthttp://www.inaturalist.org/projects/berkeley-geography-171-2013, http://www.inaturalist.org/projects/berkeley-geography-171-2014
So my gut reaction would be to try this not using the invite-only setting (e.g. tell people to join NatureWatch and then join the project) and then only if it becomes a problem of unwelcome folks joining the project, step one would be to kick them out and send them polite notes saying this is a project for a specific group of people. And if its still a problem of people rejoining or something, then think of a feature solution.

But in any case, since I don't think anyone else is using this feature, I personally don't have strong feelings about any changes to the invite-only features, but would be useful to see a mock-up of exactly the changes you have in mind

**Comment by kueda** [comment]
IMO, any project with potentially 2000 participants is essentially public and there is no reason to make it invite-only in the first place. Invite-only projects are pretty niche as it is, so I don't think building them out further is really justifiable at this point.

I think Scott's strategy would suit you just fine: keep the project open while the challenge is getting people to sign up. If you actually get so much traction that too many people are joining or the wrong people are joining, *then* make it invite-only and post instructions on how you are issuing invitations. If *that* becomes problematic, let's restart this conversation. I suspect some kind of "request to join" model would be preferable than a bulk inviter.

**Comment by pawsons** [comment]
Hi Scott, 

Thanks for the feedback. The invite-only project functionality is to be fair relatively specific to certain groups and will as you say not necessarily be of interest to all. The feature works great and does the job of restricting access to particular people. However the problem comes when we wish to invite lots of people to a project, particularly when that includes those that are not already iNat members. This creates a bottleneck for someone to approve members. See below for the current functionality and a description of proposed changes. Current functionality is as follows:

![image](https://cloud.githubusercontent.com/assets/6520847/7402295/cf8bfcb8-ef1e-11e4-931a-e9ade20d1b57.png)

The proposed change is that there would be two options for inviting people to a project. 1) Invite existing iNat/NatureWatch users to the project and 2) Invite new users to the project. Option 1 would stay as the existing steps listed on the right hand side of the screen. However, option 2 would have the following functionality.
1. Send them an email inviting them to join iNat/NatureWatch
2. Show and invitation in their dashboard to join the particular project
3. Enable them to join your project if it's been set to invite-only

So effectively in the 'About invitations' text box I would suggest the following.

About Invitations
Inviting people to your project is a bit different than inviting individual observations. Inviting people will

1. Send them an email inviting them to join your project and to join iNat/Naturewatch is they are a new member
2. Show an invitation on their dashboard
3. Enable them to join your project if it's been set to invite-only
Only project curators can invite people to join a project. You should be able to search for people by their iNat username or their complete email address, assuming we have that on file.

With regards to implementing the functionality perhaps the search box and invite tool
![image](https://cloud.githubusercontent.com/assets/6520847/7402446/f2757438-ef1f-11e4-80ab-9dd485f68c65.png)

could be replaced by two alternative options placed one on top of the others. I would suggest leaving the current functionality where it is except change the blue 'invite' button to read 'invite existing members'. The  field beneath this would then allow people to enter a list of email addresses and the button would say 'invite non-members to join' or words to that effect.

When implementing this there would need to be a check that the email address entered did not match that of any existing user to avoid confusion.

Any thoughts from others greatly appreciated. We currently need to invite about 2,000 people to a particular project and most are not current members (and probably a lot won't take up the offer), however anything that can smooth the process is appreciated as I really want to make it as easy as possible for these people so that we can capture as many new folks as possible. 

Cheers

Steve

**Comment by pawsons** [comment]
Hi Kenichi, 

I appreciate it is a bit chicken and egg, i.e., not many people using this functionality yet, hence why improve it to make it more flexible and attractive to others. However, I am in a bind in that I do have a particular group that feel strongly about having the project as invite only and I have to stick with this.

If a request to join model is more appropriate then I am happy to pursue that as an option as the functionality to invite people to join INat is already well established. However, the downside of the request to join is that someone still has to manually check on a regular basis against a list of members to ensure they are appropriate to join and any manual steps introduce delays to people's functionality. Such delays do not create a nice seamless experience for the user and may put people off by a bad first impression. People generally like things to happen instantly these days.

Cheers

Steve

**Comment by mjon** [comment]
Hi all,

Like Scott, I've run class projects over several years on NatureWatch NZ/iNat and haven't had any trouble getting students going through the two step process of signing up then joining the class projects. For those projects, I've never had anyone join a class project that wasn't part of the class, so I'm happy with them not being invite-only projects. 

Still, I sympathise with Steve's situation, which currently becomes a three step process: join, make the project admin aware of your user name, then wait for confirmation of the invitation to the project. That's very much not a seamless experience. 

Ken-ichi's suggestion of a "request to join" option would reduce this back to the usual two step process that I've not had any trouble with in my classes. 

In the interim, if you need to start the project right now, I expect it's worth a go at starting out with a regular project then converting it to "invite only" once the bulk of people have signed up and joined so you know all their user names. Or, if people are concerned about unsanctioned observations being added to the project, announce the deadline at the outset after which it becomes invite only and the foresters start adding observations.

Cheers,

Jon

**Comment by pawsons** [comment]
Hi all,

Jon in general I do agree. However my stakeholders in this particular
project are adamant with regards to invite only for reasons I won't go into
here. If we could get a "request to join" functionality running as an
interim solution that would make me a happy person.

Many thanks

Steve
