### ISSUE TITLE
inactive taxa no longer returned in taxon search components on views where they used to 

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#538]
On http://www.inaturalist.org/taxon_changes/new the taxon search components used to return inactive taxa along with the active taxa, since the ES update, these only return active taxa

likewise http://www.inaturalist.org/taxa/search has a 'Show active and inactive taxa' toggle which adds the is_active=any which used to return both active/inactive taxa. since the ES update, this param doesn't work

**Comment by pleary** [comment]
I just deployed the fix, and it looks like this is working now
