### ISSUE TITLE
Change common name piece of taxa associated with observations from 'the thing the user specifies' to 'the thing the viewer specifies' to be consistent with 

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#540]
Currently, by design, on the website the common name piece of taxa associated with observations in the observations component on obs/index and in the taxon name on the top portion of obs/show defaults to whatever the user originally entered (as stored in the 'species_guess' field) to deal with local/preferred names etc. (e.g. 'I entered Oregon Myrtle, why does it now say California Bay???')

Problems with this include:
1) Confusion with taxonomy, e.g. 'G' below where the user entered a synonym and the name now appears as two different scientific names side by side
2) Confusion with languages, e.g. 'F' below is 'Summer Tanager' which as an English speaker I would recognize but don't because I see the spanish version
![screen shot 2015-04-29 at 8 18 03 am](https://cloud.githubusercontent.com/assets/598026/7403066/ecbf0e12-ee86-11e4-80c9-f4b7d9f9bacd.png)
3) Inconsistencies among platforms as the Explore tabs on iOS and Android show the default common name, not the species_guess
![photo 20](https://cloud.githubusercontent.com/assets/598026/7403227/857b9318-ee88-11e4-91e5-6a04ea8d9ed2.PNG)
![screenshot_2015-04-29-15-49-42](https://cloud.githubusercontent.com/assets/598026/7403470/e6d54ecc-ee8a-11e4-89c4-7d2a5d2206f9.png)
Likewise, because we now have 'place names' to deal with local preferences like the Oregon Myrtle example, I propose we opt to show the default common name in the lexicon/place associated with the viewer's account rather than what the creator originally entered.

Thoughts?

**Comment by joellebel** [comment]
I agree we should show the default common name in the lexicon/place associated with the viewer's account rather than what the creator originally entered. This would make the most sense to users of every level.

**Comment by pleary** [comment]
One thing I realized while working on #546 is we offer a sort by "species names" feature on the observation sort form, which internally is sorting by the `species_guess` field on observation. If we implement this change to how taxon names are displayed, we would presumably want to update the search/sort mechanism with the same logic. This means we will need to update the search index to store the best `species_guess` for any language a user might be browsing in, and update the observation search code accordingly. (or we get rid of sorting by "species names"...)

**Comment by loarie** [comment]
true - (and I agree 'species names' is not super useful) but couldn't we also just have 'species names' sort by the associated taxon's scientific name rather than have it use species_guess?

**Comment by pleary** [comment]
yes, sorting by preferred scientific name would be the easiest thing to do. Just a quick code change, we already have the data we need in the index. I think it makes the most sense too - common names are just too variant ("a ...", "the ...", "common ...") for useful sorting in my opinion.

**Comment by loarie** [comment]
I'm clarifying that the places being referred to here as the 'title' appears on the web and mobile so we can refer to them more easily
![screen shot 2015-06-16 at 11 06 26 am](https://cloud.githubusercontent.com/assets/598026/8190516/d27478ba-1417-11e5-88e0-355e1efa50b0.png)
![screen shot 2015-06-16 at 11 06 35 am](https://cloud.githubusercontent.com/assets/598026/8190514/d0a4ad8e-1417-11e5-88f6-5d5fcd02732f.png)
I agree with Ken-ichi's common in https://github.com/inaturalist/design/issues/10 that in the Mobile Me tab we don't have the same expectation problems so I've left them out.

But in A-G above, I propose we follow this set of rules:
1. If no taxon associated with an observation and no species_guess show 'something'
2. If no taxon associated with an observation but species_guess show species guess
3. If taxon associated with an observation display taxon name(s) tailored to viewer's locale/place exactly as 'titles' on taxon pages are

**Comment by kueda** [comment]
I still feel like what I enter should be what appears, but clearly I'm in the minority, so let's just go with Scott's recommendation unless anyone disagrees and see how people react.

Regarding the sort by "species names," let's just remove that from the UI and continue to support it in the API as it works right now. I don't think anyone is actually using it, but I view the API docs as more of a firm contract with API consumers than the web UI.

**Comment by kueda** [comment]
Staging is current running solutions to most of this (I assume you'll file separate issues for iOS and Android). However, it’s going to seriously screw with a handful of people like http://www.inaturalist.org/observations/sunnetchan, who have been using species guess to hold local names of the species they’ve observed.  Sunny’s also done a good job of adding these as taxon_names, but s/he hasn’t been adding those names to places b/c s/he is not a curator.

Some options:
1. Make Sunny a curator, to him/her and anyone else who dislikes this change to add names to places and set the user place accordingly
1. Show `species_guess` when viewing your own observations, but not when viewing obs by others
1. Allow users to choose a common name for their observations (requested numerous times, can't find an issue)

Thoughts?

**Comment by loarie** [comment]
I'd prefer 1 and see if we get any complaints because 2 and 3 add additional complexity

**Comment by loarie** [comment]
the remaining edge case would be competing names within a place/lexicon - e.g. you and I both choose California as our place and English as our lexicon which means we don't see Oregon Myrtle but you prefer California Bay and I prefer California Bay Laurel. If this becomes an issue then adding 2 or 3 above might be a good option. But I don't think people will be any more vocal than they are about scientific name disputes which we can't get around

**Comment by loarie** [comment]
This change now matches whats currently displaying on the Android and iPhone explore tabs in terms of the species_guess rules. But to be consistent across platforms, we need to implement the following issues for common names to reflect the users preferences for locale:
https://github.com/inaturalist/iNaturalistAndroid/issues/59
https://github.com/inaturalist/INaturalistIOS/issues/176
and place:
https://github.com/inaturalist/iNaturalistAndroid/issues/60
https://github.com/inaturalist/INaturalistIOS/issues/177

**Comment by kueda** [comment]
This has now been deployed. Scott, I leave it to you to deal with the backlash. Another group that will be disgruntled: people who don't like common names at all.

**Comment by loarie** [comment]
thanks, I just emailed the google group

**Comment by naturalistcharlie** [comment]
Maybe "scientific names" could be selectable as a "place" for those people.
"Academia"?

On Thu, Jun 18, 2015 at 3:26 AM, Scott Loarie <notifications@github.com>
wrote:

> thanks, I just emailed the google group
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/540#issuecomment-113061546>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement
