### ISSUE TITLE
Images for guide tag values in Guides

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#542]
Kew is interested in using the tags infrastructure on guides as an identification key. I've played with doing that here: http://www.inaturalist.org/guides/1503

One of the things they would like is the ability to annotate values for specific tags by selecting an image from among the guide page images. For example, for the tag 'Number of Articles in Flagellum' value '2', I could associate the 3rd image here http://www.inaturalist.org/guide_taxa/283594.

On the web and mobile these images could display as modals when clicking on information icons something like this:
![screen shot 2015-04-30 at 11 33 47 am](https://cloud.githubusercontent.com/assets/598026/7419886/e7bb654a-ef2c-11e4-832b-d7e2494cf7d5.png)

**Comment by kueda** [comment]
I agree this would be cool, let's restrict this issue to the web, though. Implementation might be a bit tricky. Here's a tentative plan:

1. Allow GuidePhotos to be tagged so the tag value can be linked to individual photos
1. Support a special syntax for tags on GuidePhotos to indicate that they not only depict the character state, but that they are the preferred depiction of that trait within the guide, something like `Present in NoCA?=yes*` or something.
1. Add tags field for GuidePhotos on guide_taxa/edit
1. Maybe add some kind of character matrix UI for choosing photos for every character state.
