### ISSUE TITLE
Observation search by species guess broken

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#546]
Selecting 'species names' under order does add the order_by=species_guess param e.g.
http://www.inaturalist.org/observations?taxon_id=47851&order_by=species_guess&order=desc
vs http://www.inaturalist.org/observations?taxon_id=47851&order_by=observations.id&order=desc
but does not change the order, also the search UI shows order = 'date added' after this search is made rather than the selected 'species name' value that the user chose
![screen shot 2015-05-04 at 10 29 22 am](https://cloud.githubusercontent.com/assets/598026/7458352/b461f88e-f248-11e4-963a-50bd44a321f8.png)
mentioned on the google group here https://groups.google.com/forum/#!topic/inaturalist/VyTRAIeFLD4

**Comment by pleary** [comment]
I believe this is fixed with 57c87f72138213dca63ec62b7139685166df398c and 1afcbff57929b94e338df8dc22e8dcfa5dde3024

**Comment by loarie** [comment]
looks fixed to me
