### ISSUE TITLE
Project observations not displaying in observation search

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#548]
For example
https://www.inaturalist.org/observations/1459421
is not returned here
https://www.inaturalist.org/observations?user_id=rileypollom&project=871
the project observation seems to be fine
ProjectObservation id: 1280485, project_id: 871, observation_id: 1459421, created_at: "2015-05-06 13:00:42", updated_at: "2015-05-06 13:00:42", curator_identification_id: nil, tracking_code: nil

Correlation of problem with creation by Android app noticed, but I can't confirm this

**Comment by kueda** [comment]
I'm seeing it there. Maybe a lag in the ES index? Have you seen other examples?

**Comment by pleary** [comment]
I forgot to report that I manually reindexed this one. It was not in the ES index when I looked. I never went much further, but I suspect there will be other records out of sync, and that there is someplace in the code that needs to do some indexing.

**Comment by kueda** [comment]
FWIW, this also hit a number of observations in http://www.inaturalist.org/projects/intertidal-biodiversity-survey-at-pillar-point, supposedly around the time many of them were aggregated into http://www.inaturalist.org/projects/san-mateo-county-bio-blitz, though I've yet to figure out why.

**Comment by pleary** [comment]
over a year old with no updates - closing
