### ISSUE TITLE
observations without time not returned in obs searches with same day time constraints

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#553]
Technically, that obs doesn't have a time so technically its not in the BioBlitz time interval. However, because we get lots of obs without times, we previously had things without times always counted despite same day time constraints. We must have lost that functionality when we updated our search engine as
http://www.inaturalist.org/observations?d1=2015-04-25T06%3A00%3A00-07%3A00&d2=2015-04-25T20%3A00%3A00-07%3A00&taxon_id=6317  does not return http://www.inaturalist.org/observations/1424329

**Comment by pleary** [comment]
This is fixed as of 305d1f485de097e1ea1202a8fadd97e1c43999d2 . We will use the time component of date ranges to search observations which have a time_observed_at. And we will use the date component of the ranges to search all observations which don't have specific times
