### ISSUE TITLE
place searches should return obs based on private coords of obscured observations

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#554]
e.g. http://www.inaturalist.org/observations/taylorcg?place_id=77154 should return
http://www.inaturalist.org/observations/1424008

**Comment by naturalistcharlie** [comment]
Hmm, well that could be a problematic one, maybe it's already been
discussed too much but maybe a minimum size limit for where it would
display? Like, if there is a 1 acre place it shouldn't show you that an
obscured observation is there, but for a 10,000 acre place it should. But
maybe it's better not to worry about that again, i don't know.

On Mon, May 11, 2015 at 5:38 PM, Scott Loarie <notifications@github.com>
wrote:

> e.g. http://www.inaturalist.org/observations/taylorcg?place_id=77154
> should return
> http://www.inaturalist.org/observations/1424008
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/554>.
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by loarie** [comment]
hi Charlie, this is a bug issue for trying to restore previous functionality lost with our transition to a new Search Engine. I think there's an existing improvement issue for making it so that small places (<10*3.14km^2) don't display threatened species in the taxon search and many other places, but thats a longer term issue

**Comment by naturalistcharlie** [comment]
That makes sense, sorry if i was being repetitive or irrelevant :)

On Mon, May 11, 2015 at 8:50 PM, Scott Loarie <notifications@github.com>
wrote:

> hi Charlie, this is a bug issue for trying to restore previous
> functionality lost with our transition to a new Search Engine. I think
> there's an existing improvement issue for making it so that small places
> (<10*3.14km^2) don't display threatened species in the taxon search and
> many other places, but thats a longer term issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/554#issuecomment-101083607>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by pleary** [comment]
This is fixed as of 305d1f485de097e1ea1202a8fadd97e1c43999d2 . Elasticsearch is using private geometries for place filters, and that observation is now being returned by the search you referenced
