### ISSUE TITLE
'Most species' count on project header discrepancies

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#556]
The 'Most species' leaderboard display on projects, e.g. http://www.inaturalist.org/projects/coyote-point-bioblitz-2015 uses hrank=species

This should be rank=species

Clicking through to the link counts all taxa, e.g. http://www.inaturalist.org/observations/taxa?d1=2015-04-25T06%3A00%3A00-07%3A00&d2=2015-04-25T20%3A00%3A00-07%3A00&place_id=77154&user_id=dshell

The rank=species filter should be added to this link

**Comment by kueda** [comment]
Ended up just fixing the link to link to hrank=species as per our discussion at #555
