### ISSUE TITLE
Species count discrepancies in user_stats

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#557]
'Species count' in user_stats, e.g. 
http://www.inaturalist.org/observations/user_stats?d1=2015-04-25T06%3A00%3A00-07%3A00&d2=2015-04-25T20%3A00%3A00-07%3A00&place_id=77154
displays counts using hrank=species but links don't contain a rank param e.g. http://www.inaturalist.org/observations/taxa?d1=2015-04-25T06%3A00%3A00-07%3A00&d2=2015-04-25T20%3A00%3A00-07%3A00&place_id=77154&user_id=kewright

1. change displays to use rank=species rather than hrank

2. add rank=users param to links from the display

**Comment by kueda** [comment]
Ended up just fixing the link to link to hrank=species as per our discussion at #555
