### ISSUE TITLE
iNaturalist thinks some insects are plants

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/inaturalist#565]
These display as the green color on their maps as well as on the 'insects' map that otherwise shows only red dots

http://www.inaturalist.org/observations/1128559#comment-288765

http://www.inaturalist.org/observations/1088988

http://www.inaturalist.org/observations/1089009

They were each accidentally tagged as 'plants' and htne corrected to insects and their respective IDs but for some reason the map pin does not change.

Sorry, not sure if I should post this here or in windshaft I will repost there if that is where it belongs

**Comment by loarie** [comment]
yes this is a bug where the community ID change doesn't set the iconic_taxon_id - I've known about it but not sure anyone made an issue = thanks charlie

**Comment by kueda** [comment]
So if there's not an issue, can you explain what the underlying problem is in more detail? Sometimes the setting the community ID doesn't change the iconic taxon ID? If only sometimes, are there any consistent conditions?

**Comment by naturalistcharlie** [comment]
In the case of the three I saw. they were accidentally entered into the
database as plants and then soon after corrected to an insect. The name
attaches correctly but the color of the pins on any maps still shows up as
green. I suspect maybe it is something like if it is changed too fast after
upload the indexer gets confused but i don't really know what i am talking
about so...

On Thu, May 21, 2015 at 10:07 PM, Ken-ichi <notifications@github.com> wrote:

> So if there's not an issue, can you explain what the underlying problem is
> in more detail? Sometimes the setting the community ID doesn't change the
> iconic taxon ID? If only sometimes, are there any consistent conditions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/565#issuecomment-104475791>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by kueda** [comment]
Corrected how, but just changing the parent of the taxon record or by creating a taxon change?

**Comment by loarie** [comment]
this issue remains but was previously logged here https://github.com/inaturalist/inaturalist/issues/380
