### ISSUE TITLE
#obs displaying on projects/XX/members and projects/XX/contributors/YY not correct

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#566]
For example here:
http://www.inaturalist.org/projects/connecting-students-to-citizen-science-and-curated-collections/contributors/amandadonnelly

and here:

http://www.inaturalist.org/projects/connecting-students-to-citizen-science-and-curated-collections/members

count should display as 20 not 1

**Comment by kueda** [comment]
They look correct to me. Screenshot?

**Comment by kueda** [comment]
Is this still a bug? If not can you close this?
