### ISSUE TITLE
No way to tell from CSV export if coordinates are obscured

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#569]
Several project curators have been asking for tools to to see which observations in their project they have access to the private coordinates of. I've been advocating that they look in the CSV export. But I just realized that the CSV export doesn't give any indication if the values in latitude/longitude are accurate or not. For example, this is an obs of a threatened species so the lat/lon are not accurate, but I have no way of knowing that from the export:

| id | observed_on_string | observed_on | time_observed_at | time_zone | out_of_range | user_id | user_login | created_at | updated_at | quality_grade | license   url | image_url | tag_list | description | id_please | num_identification_agreements | num_identification_disagreements | captive_cultivated | oauth_application_id | place_guess | latitude | longitude | positional_accuracy | geoprivacy | positioning_method | positioning_device | species_guess | scientific_name | common_name | iconic_taxon_name | taxon_id |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 5914 | 3/7/2010 12:05:00 | 3/7/2010 | 2010-03-07 20:05:00 UTC | Pacific Time (US & Canada) | FALSE | 1 | kueda | 2010-03-09 08:27:48 UTC | 2014-10-20 03:12:27 UTC | research | CC-BY | http://www.inaturalist.org/observations/5914 | http://farm5.staticflickr.com/4063/4419561806_28f457cdb5.jpg | Didn't smell too fragrant to me, but boy, what a looker. | FALSE | 1 | 0 | FALSE |  | Edgewood County Park, San Mateo County, CA, USA | 37.44495777 | -122.2749524 |  |  |  |  | fragrant fritillary | Fritillaria liliacea | fragrant fritillary | Plantae | 53054 |

The geoprivacy column currently stores 'obscured' or 'private' if the obs owner chose to add geoprivacy - perhaps adding an additional value like 'threatened' if the obs is obscured automatically? If not, maybe another column that says whether the lat/lon represent precise or obscured values?

**Comment by pleary** [comment]
It would be easy enough to add `coordinates_obscured` to Observation::GEO_COLUMNS and have it appear in the export field list. Would that be enough? It would take a little more processing in the export to also add what the taxon's exact establishment_means is for all observations

**Comment by kueda** [comment]
You could also add `private_latitude` and `private_longitude` to the export, and make sure the viewer only sees private coordinates they have access to.

**Comment by loarie** [comment]
I see `private_latitude` and `private_longitude` are now part of the export, but that still assumes the user knows which species are having their coordinates automatically obscured. For example, take this record:

|id|species_guess|scientific_name|common_name|iconic_taxon_name|taxon_id|latitude|longitude|positional_accuracy|private_latitude|private_longitude|private_positional_accuracy|geoprivacy|positioning_method|positioning_device|curator_coordinate_access|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|1485885|Three-toed Box Turtle|Terrapene carolina triunguis|Three-toed Box Turtle|Reptilia|39818|30.09172708|-95.73833618|6109|||||||FALSE|

`private_latitude` and `private_longitude` are blank and `curator_coordinate_access` is FALSE. But the user would have to know a priori that Three-toed Box Turtle is automatically obscured to know that `latitude` and `longitude` do not hold the precise values.

Would an alternative solution of modifying the `geoprivacy` column to say 'obscured by owner' or 'obscured by taxon' to encompass all obscured observations while still distinguishing between these flavors?

**Comment by kueda** [comment]
I'd preferred @pleary's `coordinates_obscured` suggestion. That way there's just one column that tells you whether the coordinates were obscured, regardless of cause.

**Comment by loarie** [comment]
fine with me

**Comment by pleary** [comment]
ok I'll add that and take a look at #713

**Comment by kueda** [comment]
Thought about this a bit more. I think we should include `coordinates_obscured`, but there's still the problem of not knowing what the true coordinate uncertainty is, which varies by `positional_accuracy` and by `latitude`. We could address this by including `public_positional_accuracy`, which is `MAX(uncertainty_cell_diagonal_meters, positional_accuracy)`, and which we use to determine what place names to use when describing coordinates (i.e. don't be too precise if the coordinates aren't precise), but that's not really the same thing as coordinate uncertainty, b/c if the `positional_accuracy` is blank, we don't actually know what the coordinate uncertainty is, we just know how much *we* obscured the coordinates. If the true uncertainty is the size of California for an observation of a CA Condor but the `positional_accuracy` is blank, `public_positional_accuracy` will be incorrectly low, i.e. the size of the uncertainty cell, which is much smaller than the true uncertainty.

Proposal:

- [ ] include `coordinates_obscured` in obs CSV exports
- [ ] rename `public_positonal_accuracy` to `display_coordinate_uncertainty` and continue using it as we have been
- [ ] add `public_coordinate_uncertainty` and set it to `positional_accuracy ? MAX(positional_accuracy, uncertainty_cell_diagonal_meters) : null`
- [ ] set `public_coordinate_uncertainty` for all past observations
- [ ] include `public_coordinate_uncertainty` in obs CSV exports
- [ ] use `public_coordinate_uncertainty` for `coordinateUncertaintyInMeters` in DwC-A exports

**Comment by loarie** [comment]
do we have `public_positonal_accuracy` now? I thought we only had `positonal_accuracy`? What is  `public_positonal_accuracy` currently storing?

**Comment by kueda** [comment]
To quote myself from above, `public_positional_accuracy`
> is MAX(uncertainty_cell_diagonal_meters, positional_accuracy), and which we use to determine what place names to use when describing coordinates (i.e. don't be too precise if the coordinates aren't precise)

**Comment by loarie** [comment]
I thought 'rename public_positonal_accuracy to display_coordinate_uncertainty and continue using it as we have been' implied that this field currently exists. 'add public_coordinate_uncertainty and set it to positional_accuracy ? MAX(positional_accuracy, uncertainty_cell_diagonal_meters) : null' implies it doesn't

**Comment by kueda** [comment]
`public_positional_accuracy` exists and its value is `MAX(uncertainty_cell_diagonal_meters, positional_accuracy)`

I am proposing renaming that field so its name better describes what we use it for, and adding a new field called `public_coordinate_uncertainty` whose value would be `positional_accuracy ? MAX(positional_accuracy, uncertainty_cell_diagonal_meters) : null`

**Comment by loarie** [comment]
thats what I was after - thanks

**Comment by loarie** [comment]
proposal seems fine to me

**Comment by carrieseltzer** [comment]
Can we revisit this? I haven't found anything in the private_positional_accuracy field yet even though it exists. If I understand the above conversation correctly, I'd like to add the following proposal to this:

- [ ] copy `positional_accuracy` to `private_positional_accuracy`

I believe with the changes above, if a location is *not* obscured, `positional_accuracy` renamed as `public_coordinate_uncertainty` will remain the same as `private_positional_accuracy`, but if it *is* obscured, then `public_coordinate_uncertainty` will be different than `private_positional_accuracy`.

Do we know how this should work for private observations that are not mappable at all? Seems we should just have the `private_positional_accuracy` with no value for `public_coordinate_uncertainty`.

**Comment by kueda** [comment]
I don't think `private_positional_accuracy` actually does anything or is ever used, so I propose we remove it.

> `positional_accuracy` renamed as `public_coordinate_uncertainty` will remain the same as `private_positional_accuracy`

I don't think anyone is proposing that we rename `positional_accuracy` so I'm not sure what this means.

For private coordinates, `coordinated_obscured` will be true, `latitude` and `longitude` will be blank, and `private_latitude` and `private_longitude` will be set if you have access to them.

**Comment by carrieseltzer** [comment]
To date, I think `private_positional_accuracy` has been unused, but I think we *should* use it, rather than delete it.

Re-reading above, I see that `positional_accuracy` will remain. I tried and failed to make a table in here, so hand drew a table that hopefully better explains my ideas about how the fields will work under different geoprivacy conditions. 
![img_4570](https://user-images.githubusercontent.com/7501183/39489721-82d828e6-4d54-11e8-809c-e95383275b05.jpg)

**Comment by loarie** [comment]
Just reread all this and Ken-ichi's proposal makes sense to me and still seems like a good option to fix the remaining issue that an obs with positional_accuracy = nil should also have a nil public_coordinate_uncertainty.

Carrie - do you have any specific issues with this approach and if so can you help explain what they are and how what you describe above resolves them?

**Comment by carrieseltzer** [comment]
I agree with everything Ken-ichi proposed, with the exception of removing `private_positional_accuracy`. 

I propose that `private_positional_accuracy` contain a value derived from the `positional_accuracy` field when exporting private coordinates.

**Comment by kueda** [comment]
@carrieseltzer, just a reminder, this is sitting in a branch. I can get it on staging or something if/when you're ready to test.

**Comment by kueda** [comment]
Pretty sure this was dealt with in #2891. Going to close and remove the branch.
