### ISSUE TITLE
'must allow curator coordinate access for observations added by anyone' rule

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#572]
Project managers who want to ensure that they have access to private coords for all obs in their project would like to be able to use new tools like the aggregator. But to do so they would require a 'must allow curator coordinate access for observations added by anyone' rule which would require that new project observations belong to a user who has (1) joined the project and (2) the project users have set their preferences to allow coordinate access to anyone who adds the obs

**Comment by ckhanks** [comment]
To clarify, this would restrict the aggregator to observations from people who allow curators to add their observations and see precise coordinates.  However, observers would still be able to add their observations one by one, correct?

**Comment by naturalistcharlie** [comment]
Wouldn't it be easier just to have the aggregator exclude observations that
are obscured and don't grant that project access? I don't know exactly how
this would play out, but I don't allow 'access to anything ever' by any
project other than Vermont Atlas of Life and I can't imagine that many
people would. But I may be off on that.

On Tue, Jun 9, 2015 at 4:00 PM, ckhanks <notifications@github.com> wrote:

> To clarify, this would restrict the aggregator to observations from people
> who allow curators to add their observations and see precise coordinates.
> However, observers would still be able to add their observations one by
> one, correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/572#issuecomment-110486833>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by ckhanks** [comment]
Yes, that would be perfect.  I don't want to add observations where we do not have access to precise coordinates.  At the same time, we do have participants that would allow access to precise coordinates to all obs that we add.

**Comment by ckhanks** [comment]
Alternatively, it would work to just allow a project to require access to precise coordinates.

**Comment by loarie** [comment]
Correct Cullen, participants who don't give project curators access would still have to join the project and choose the 'Allow project curators to view the private coordinates of your observations when added to the project by you' setting. Then they could still manually add obs and the rule would pass. But the rule would fail for the aggregator since it wouldn't be the obs owner adding the obs. 

So lets call this 'must allow curator coordinate access'. It would be complex to query though as it would have to do the following:
a) if observation owner adding the observation -
     true if they have they joined project AND not selected the 'Allow project curators to view the private coordinates of your observations when added to the project by No One' setting?
b) if project curator adding the observation -
      true if obs owner joined the project and selected the 'Allow project curators to view the private coordinates of your observations when added to the project by Project Curators' setting?
c) else -
      false

the aggregator would work as if (b) a project curator was adding the observations so it would skip observations of people who hadn't joined + given curators access.

I have no idea if this is technically feasible, but I think it would be the only way to achieve the logic Cullen wants

**Comment by loarie** [comment]
addressed here https://github.com/inaturalist/inaturalist/issues/727
