### ISSUE TITLE
"view non-mobile site" from mobile dashboard doesn't seem to work

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/inaturalist#573]
The 'view non-mobile site' link on the mobile dashboard doesn't seem to work. It reloads the page and stays in the mobile version.

**Comment by kueda** [comment]
Is this still happening for you? It's not for me.

**Comment by kueda** [comment]
Please re-open if you notice this happening again.

**Comment by alexshepard** [comment]
Sorry, I missed your question.

Still happening for me.

Steps to reproduce:
Open iNat in mobile safari
Login
Select dashboard
Select view non-mobile site

Expected result: see desktop dashboard
Actual result: see mobile dashboard

Alternate repro steps:
Open iNat in mobile safari, login
Select view non-mobile site
Select dashboard from the "me" dropdown in the desktop site

Expected results: see the desktop dashboard
Actual results: see the mobile dashboard

I can show you in person next time we're both in the office if you still can't reproduce this.

**Comment by alexshepard** [comment]
To clarify, it's not the link that's broken. Continuing to navigate around the site makes it clear that the web app is in non-mobile mode.

The bug for is is that the mobile dashboard page doesn't seem to respect my "view non-mobile site" choice like the other pages in the app do.

Apologies if that wasn't clear earlier.

**Comment by kueda** [comment]
Actually I think that last commit might have fixed this. Can you try it again, Alex?

**Comment by kueda** [comment]
WFM, but re-open if it doesn't WFY
