### ISSUE TITLE
'Needs ID' state for observations

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#576]
From these discussions on the Google Group:
https://groups.google.com/forum/#!topic/inaturalist/F3HLBHQG0A0
https://groups.google.com/forum/#!topic/inaturalist/q4KiiVCwN-o
an algorithmic approach towards determining which observations 'Need ID' has been suggested

It was also suggested that this 'Need ID' state be independent of the existing 'Research Grade' and 'ID Please' state which would remain unchanged. This issue assumes (but does not advocate) that this be the case.

**Question 1**
It was suggested that the presence of media (photos/sound) would be required for 'Need ID' to be 'Yes'. Should we also require the other data quality states (date, georeferenced, etc.) to be considered? Doing so could make this less complex by piggybacking on that existing complexity.

If so, then like the requirements for Quality Grade=Research, 'Need ID' could be 'Yes' only if: Date?=Yes, Georeferenced?=Yes, Photos or sound?=Yes, Wild/Naturalized?=Yes|Null, location accurate?=Yes|Null, date accurate?=Yes|Null, appropriate=Yes

**Question 2**
Unlike Quality Grade=Research, Need ID=Yes would require Community supported ID?=No or either of two suggested possibilities:

***Suggestion A***
There are no finer suggested IDs, for example perhaps an ID of lizards (suborder=Sauria) and Anoles (genus=Anolis) create a Community supported ID?=Yes at lizards (suborder=Sauria), or perhaps an ID of geckos (family=Gekkonidae) and Anoles (genus=Anolis) create a Community supported ID?=Yes at lizards (suborder=Sauria). But in both cases there are suggested IDs at finer ranks than the community supported ID (suborder=Sauria), so 'finer ID suggestions'=Yes
![screen shot 2015-06-01 at 4 33 44 pm](https://cloud.githubusercontent.com/assets/598026/7925647/590a514e-087c-11e5-8139-cd826c162e2d.png)

***Suggestion B***
The rank of the observation is coarser than species, for example perhaps an ID of lizards (suborder=Sauria) and Anoles (genus=Anolis) create a Community supported ID?=Yes at lizards (suborder=Sauria) which is coarser than rank species.
![screen shot 2015-06-01 at 4 33 38 pm](https://cloud.githubusercontent.com/assets/598026/7925648/590a64cc-087c-11e5-9149-0b6fb5eb9105.png)

Which of these makes more sense? Any other suggestions?

**Question 3**
It was suggested that there should be a way for the community to override the 'Needs ID' algorithm if, for example, the community thinks that no finer ID is possible. For example, if we went with Suggestion B above, the algorithm would think any observation not at rank species or finer 'Needs ID' unless the community voted against it (e.g. its a blurry picture of some kind of lizard).

This could work by the community voting against the algorithm, something like:
![screen shot 2015-06-01 at 4 33 49 pm](https://cloud.githubusercontent.com/assets/598026/7925646/59059c26-087c-11e5-9f5e-0f01bce3a691.png)

Would something like this work? It does seem that without it, there would be a lot of instances where the algorithm would get things wrong.

**Comment by loarie** [comment]
We discussed this a bit last week in Bolinas. Does this capture what was proposed?
1. If an incoming obs failed the 'Candidate for Research Grade' conditions it would get placed in a 'Fragment' bin, otherwise it would go into the 'Needs ID' bin
2. The obs will stay in the Needs ID bin until Needs ID is turned off. This happens automatically if the Community ID reaches Rank species or finer, or can be voted off by the community.
3. If an obs with Needs ID turned off is of Rank family or coarser it goes into the Fragment bin (ie photos or sound present but not sufficient to produce a 'usable' ID)
4. If an obs with Needs ID turned off is of Rank finer than family it goes into the Research Quality bin
![screen shot 2015-06-19 at 6 20 18 pm](https://cloud.githubusercontent.com/assets/598026/8265483/d956ad5c-16af-11e5-9ed5-343d36d4c95d.png)
An advantage of this approach is that all observations would be in one of 3 non-overlapping bins: Fragment, Needs ID, & Research Quality
I think a main disadvantage is that the Rank cutoffs are somewhat arbitrary, but are in align with Donald Hobern's advice on what is useful to GBIF. And the community voting can turn Needs ID on/off if species or lower is not an appropriate cutoff.

**Comment by loarie** [comment]
Discussing this around the office - there was concern about the 'Fragment' bin because

1. its mixing two concepts
 * obs missing data that aid verification/make for 'complete' records and
 * obs of captive/planted stuff

2. Fragment and most other words like 'incomplete' make a value statement about these observations needing more work. In Ken-ichi's view sometimes the recorder never intended to add these fields so it wouldn't be fair to judge them as incomplete.

So I've redone the above splitting out 'Fragments' into 'Captive/planted' and 'Unverifiable'
![screen shot 2015-06-23 at 4 13 21 pm](https://cloud.githubusercontent.com/assets/598026/8319361/d3b50acc-19c2-11e5-8962-86b0f4241d71.png)
This slightly complicates things by adding a 4th bin, but it still preserves having a set of non-overlapping bins that every observation would be assigned to exactly one of. At the moment, obs on iNat would be proportioned as follows (but if this were in effect, turning off Needs ID would shunt obs to Research or Unverifiable based on the rank of the ID)
![screen shot 2015-06-23 at 4 06 15 pm](https://cloud.githubusercontent.com/assets/598026/8319285/d8830906-19c1-11e5-8807-0a4bffd0027f.png)

**Comment by kueda** [comment]
I'm confused about why you want to mix this into quality grade. Why should **research grade** and **needs ID** should be mutually exclusive categories? For example, http://www.inaturalist.org/observations/1617608 is an observation of Order Embiidina. It definitely **needs ID**, but is also completely accurate and complete, and therefore **research grade**. If you're going to mix the concepts as you propose, it would be **needs ID** and *not* **research grade**, even though it's perfectly accurate enough to share with data partners, and might actually be quite useful to a researcher using GBIF who was trying to revise Embiidina, or look for California collection localities.

I thought the whole point of this was to give us the power to separate things that genuinely need an ID from things that people expressed a desire for an ID.

**Comment by loarie** [comment]
>I'm confused about why you want to mix this into quality grade. Why should research grade and needs ID should be mutually exclusive categories?

I agree with you if research grade were not displayed prominantly/'gamefied' on the site. But it currently is and I doubt folks are going to let it go. So given that research grade is prominently displayed etc. its very confusing to the public how something could be both research grade and 'needs ID', plus having multiple categories for obs complicates the display and general presentation of these categories

>If you're going to mix the concepts as you propose, it would be needs ID and not research grade, even though it's perfectly accurate enough to share with data partners, and might actually be quite useful to a researcher using GBIF

if research grade being prominently displayed on the site weren't a concern, I agree that things can 'need ID' and still be potentially useful for some research/sharing with partners. But that said, D Hobern said on the google group that to GBIF 'records identified to family rank or higher are of very limited value'. Since they our are primary 'research' partner, if they don't even want this stuff, I don't see a huge cost of not calling it research grade, especially given the benefits having mutually exclusive categories bring that this change would facilitate

**Comment by loarie** [comment]
>Also, the voting: could this be handled by a "can't ID" vote as described in #611?

#611 describes a feature that would allow an individual to exclude things they have reviewed as individuals. Voting described above is a way to turn off 'Needs ID' which is a bin the obs would fall into and therefore effect everything. Very different IMO.

I guess I can see how to combine this if what qualifies as 'Needs ID' and 'Research grade' were different to me than to you or another viewer. But I think there's advantages to having everybody using and rallying around the same numbers/categories (ie this observation is Research Grade, or only 1% of California Herps still Need ID)

**Comment by kueda** [comment]
Voting: ok, don't feel strongly about it, just trying avoid building unnecessary functionality, and I feel like "doesn't need ID" could be derived from a lot of people saying "this cannot be ID'd."

Mutual exclusivity of "research grade" and "needs ID" does seem important to me.  They are already not mutually exclusive and of the many confusingly complicated things on our site, I have never heard anyone complain about that (they complain about removing the "ID Please" label all the time, but I never get the feeling it's because the observation is "research grade" or not, but prove me wrong with URLs). The quality grade is a statement about accuracy, not precision, and I don't like the idea of iNat telling me my data is not accurate (or of unknown accuracy) just because it is not precise, e.g. that webspinner observation.

Since we don't seem to agree, I guess we'll meet and see what the rest of the team thinks. Again, I think that's the last sticking point, though it's kind of a big one.

**Comment by kueda** [comment]
Assuming independence from quality grade and captive status, are we talking about three identification states?

1. Needs ID
1. Verified
1. Unverifiable

If so how's this for a spec:

- [ ] add `id_status` column to observations, possible values `needs`, `verified`, `unverifiable`
- [ ] set `id_status` when observation and identification save
  - [ ] `verified`: has community ID at species or lower
  - [ ] `needs`: has media, coordinates, date, passes all quality metrics, **note** voted down and **not** verified
  - [ ] `unverifiable`: not needs ID
- [ ] add a vote scope for observations called "needs_id"
- [ ] add UI to obs/show so people can vote on whether or not something needs ID (though we should probably separate this from the Data Quality Assessment if we're not going to have this affect quality grade)
- [ ] add `id_status` to the ES index and observations api
- [ ] add UI to the observation filters for needs_id

Maybe

- [ ] remove ID Please filter from observations
- [ ] show needs ID status instead of ID Please on obs components
- [ ] remove identification stats (most agree, most disagree, etc) from obs table and obs filter UI

**Comment by loarie** [comment]
looks good

**Comment by joellebel** [comment]
So what's the difference between Verified and Research Grade? I'm fine either way. I just want to make sure I'm understanding this.

**Comment by kueda** [comment]
Rg means it is *complete* and *accurate*. Verified means that only the
identification is *accurate* and *precise*

**Comment by loarie** [comment]
They are related, but Unverifiable vs Needs ID vs Verified involves the rank of the community ID and whether Needs ID is on or off while RG vs Casual involves the presence of a community ID and whether the obs is captive or not. Here's two flows to try to illustrate the relation (metadata? means none of the following are false: Date? Georeferenced? Photos or Sound? Does the location seem accurate? Does the date seem accurate?):

Unverifiable vs Needs ID vs Verified flow
![screen shot 2015-07-08 at 9 42 41 pm](https://cloud.githubusercontent.com/assets/598026/8588099/72dd6a7e-25ba-11e5-8d99-255b079430f1.png)

RG vs Casual flow
![screen shot 2015-07-08 at 9 43 48 pm](https://cloud.githubusercontent.com/assets/598026/8588097/71356604-25ba-11e5-9de0-4983e2e94998.png)

**Comment by loarie** [comment]
@kueda - in the obs search param you added is there a way of searching for id_status=needs_id+verified ?

**Comment by kueda** [comment]
No. What's the use case for that?

**Comment by loarie** [comment]
We'll need it to make the default to hide captive and unverified observations on obs/index, correct?

**Comment by loarie** [comment]
I'm moving this from Slack to this issue to keep things together:

My feedback on the NeedsID work on staging was to collapse ID and Quality Assessment to reduce adding more complexity to the observation form 
![screen_shot_2015-07-11_at_10 42 42_pm_360](https://cloud.githubusercontent.com/assets/598026/8686000/5ed5680c-2a37-11e5-9424-686da05e5671.png)

>loarie July 11th at 10:46 PM 
I don't think separate ID status and Data Quality Assessment sections are necessary, particularly since they repeat the majority of the contributing data. I vote for a single section that provides the details for Captive/ID status/and Research Quality. Maybe something like:

>kueda July 11th at 10:50 PM 
Yeah, separating them is awkward, but I took a stab at combining them at it ends up being really weird b/c you have to have “Community taxon at species or lower” AND “Community-supported ID.”  Combining them also gives the impression that the ID status and the quality grade influence one another, but they don’t. Regardless, I can try combining them again next week and see how it looks, but I think it’s awkward both ways.

>loarie July 11th at 11:12 PM 
Well curious to see what others think. But I think a little tooltip on ID Status and Quality Grade could describe how they work which would make it less necessary to provide every piece of data that contributes to them. I'm not sure showing 'Community taxon at species or lower' is necessary. And if you did want to spell it out, you could include a row for 'rank species or lower?' which would provide the same info without being some confusingly pseudo-duplicative of having two Community ID related rows

@kueda, @joellebel and others - any more thoughts on this?

**Comment by joellebel** [comment]
Hi all. This is some important stuff. Can we set aside some time talk about it verbally. Thanks.

**Comment by loarie** [comment]
Looking at staging, I'm increasingly thinking its a bad idea from a product standpoint to expose this 'Unverifiable/Needs ID/Verified' terminology ALONGSIDE 'Casual/Research Grade'. It introduces so much confusion and complication. Before releasing this functionality, I'd advocate not displaying Needs ID on observations show (i) at all (ii) to anyone but admins or (iii) to anyone but curators until we have a chance to revisit the display or treatment of Casual/Research Grade and more generally see this functionality in action. Thoughts?

**Comment by kueda** [comment]
I think hiding it entirely would be detrimental because it prevents people from seeing how the system actually works, even if they want to take the time to do so. We could just hide the ID Status and the Quality Assessment behind something like "Details" and just have it not show by default. Currently we show the Quality Assessment by default because no one was using it. Now people sort of use it, but mostly to compulsively say yes instead of constructively saying no (e.g. they still fail to flag things that are captive).

**Comment by loarie** [comment]
IMO the cost of introducing this complexity to 'normal visitors' (ie 'How is verified different from research grade??') outweighs the benefit of explaining to 'power users' the inner workings of the Needs ID algorithm. How about using other avenues to reach our power users such as putting it on gorilla for people to play with, but holding off releasing anything until we have a chance to discuss ways to avoid the added complexity of introducing new 'Unverifiable/Needs ID/Verified' terminology ALONGSIDE ''Casual/Research Grade' terminology?

Not to get ahead of things here, but I strongly feel that with this new 'ID status' there's no compelling reason to surface the 'Data Quality Assessment' or 'casual/research grade' states anywhere on the site (ie just use them for our backend purposes of filtering what gets sent to external partners). If anyone asks what gets sent to external partners, the answer could be 'all of our verified observations except captive ones as well as some coarsely identified observations that we think still Need IDs'.

The one caveat is we'd need a place for people to assess Wild/Captive outside of a to-be-removed-Data Quality-Assessment. Here I think we should reconsider the cost-benefit of keeping Wild/Captive separate from Unverifiable/Needs ID/Verified vs folding it in as I'd proposed above. The edge benefit of separating them being that people can solicit houseplant IDs (e.g. you could have a Captive observation that is also Needs ID or Verifiable) vs the complexity cost of showing a separate 'Wild/Captive Status' section outside of the 'ID Status' section (e.g. if its Captive its Unverifiable just like if it didn't have a location).

**Comment by loarie** [comment]
Regardless of the above question of how to roll things out, here are some ideas for how to make the 'ID Status' section clearer:

First, add an 'Is this observation of an organism' state (to prevent observations of clouds and trash getting a Needs ID state) alongside the existing photo/sound, georeferenced, & date states:
![screen shot 2015-07-14 at 5 38 37 pm](https://cloud.githubusercontent.com/assets/598026/8688614/23924500-2a53-11e5-8307-c9e5f5f677d6.png)
If any of these 4 states are No, then its Unverifiable - no need to show/ask anything else:
![screen shot 2015-07-14 at 6 09 52 pm](https://cloud.githubusercontent.com/assets/598026/8688648/8921826e-2a53-11e5-8c7b-76001cab97fb.png)
Only show these questions if the corresponding state is 'Yes'. And if any of these questions 'No' then Unverifiable. Note how the 'Still needs ID?' question is rephrased to correspond to the Evidence state:
![screen shot 2015-07-14 at 6 10 57 pm](https://cloud.githubusercontent.com/assets/598026/8688657/afc87c4c-2a53-11e5-9046-f0911abe7acf.png)
Only show information on the community ID and rank when an observation exits the Needs ID state, here because the ID gets a species level CID:
![screen shot 2015-07-14 at 6 12 46 pm](https://cloud.githubusercontent.com/assets/598026/8688687/03e61aa0-2a54-11e5-892e-5e537a362afb.png)
Likewise if someone votes off 'Needs ID' and the CID < rank family, its verified:
![screen shot 2015-07-14 at 6 12 51 pm](https://cloud.githubusercontent.com/assets/598026/8688724/58600a50-2a54-11e5-9e36-fc732fd04721.png)
if someone votes off 'Needs ID' and the CID >= rank family, its unverifiable:
![screen shot 2015-07-14 at 6 13 02 pm](https://cloud.githubusercontent.com/assets/598026/8688736/7c958558-2a54-11e5-936d-b5c6a118df23.png)
obs can also become unverifiable with 'Needs ID' voted off if there's no CID:
![screen shot 2015-07-14 at 6 13 08 pm](https://cloud.githubusercontent.com/assets/598026/8688744/9c260eec-2a54-11e5-9a40-f18d973dd90a.png)
or if there's no user ID at all (e.g. something)
![screen shot 2015-07-14 at 6 13 13 pm](https://cloud.githubusercontent.com/assets/598026/8688754/b8809e04-2a54-11e5-8113-fff00b14cfcb.png)

**Comment by loarie** [comment]
If we do decide to fold Wild/Captive into the 'ID Status' as proposed above, it could be as easy as adding one word 'Is this an observation of a **wild** organism?'
![screen shot 2015-07-14 at 6 22 40 pm](https://cloud.githubusercontent.com/assets/598026/8688810/527f04c8-2a55-11e5-908b-bcca93672bc9.png)
which would lump captive stuff in with obs of clouds and trash, but IMO thats more in keeping with the spirit of the site than adding a bunch of complexity to accommodate them as as a separate category

**Comment by naturalistcharlie** [comment]
I personally think it's important to the user to see if their observation
reaches research grade and is exported to gbif. I don't feel strongly but I
think it's an added motivation and also makes it easier to understand what
goes into place species lists, etc. apologizes if I misread.
I like all of the info - but I guess I definitely qualify as a power user.
What about someday having a way to expand the window to see the data
quality stuff, or even "casual" and "advanced" modes on the site? I realize
those are probably for further along in the Inat development process. But
just a few thoughts.

On Tuesday, July 14, 2015, Scott Loarie <notifications@github.com> wrote:

> If we do decide to fold Wild/Captive into the 'ID Status' as proposed
> above, it could be as easy as adding one word 'Is this an observation of a
> *wild* organism?'
> [image: screen shot 2015-07-14 at 6 22 40 pm]
> <https://cloud.githubusercontent.com/assets/598026/8688810/527f04c8-2a55-11e5-908b-bcca93672bc9.png>
> which would lump captive stuff in with obs of clouds and trash, but IMO
> thats more in keeping with the spirit of the site than adding a bunch of
> complexity to accommodate them as as a separate category
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/576#issuecomment-121448462>
> .
>


-- 
Sent from Gmail Mobile

**Comment by loarie** [comment]
For tomorrow's meeting, I'd like to discuss how we roll out Needs ID so as not to confuse people. Specifically:

**A.** Considering how the display of Needs ID will play nicely with the display of RG in a non-confusing way:
1) on the Observation Component:
Currently on production, the components display 'Research Grade and/or ID Please' badges. Currently on staging, the only badge that is displayed now is 'Needs ID' or nothing. Will not showing Research (or Verified) here bother people?
![screen shot 2015-07-15 at 11 59 09 am](https://cloud.githubusercontent.com/assets/598026/8707163/f3f75042-2ae8-11e5-888d-a790c49aea34.png)

2) on Observation Show:
Should the Data Quality Assessment and ID Status be combined
![screen shot 2015-07-15 at 11 51 23 am](https://cloud.githubusercontent.com/assets/598026/8707078/6977a35e-2ae8-11e5-86ea-a380958159a9.png)
or kept separate on obs show?
![screen shot 2015-07-15 at 11 50 51 am](https://cloud.githubusercontent.com/assets/598026/8707096/90f4daa0-2ae8-11e5-9b63-278b0cccb187.png)
How do we make these as clear as possible? Should these be collapsed or expanded by default? 

3) in the Observation Search filters
Currently the design here https://github.com/inaturalist/design/issues/20 has filters that when checked restrict to a subset, eg. Wild+Captive vs Wild, Unverifiable+NeedsID+Verified vs NeedsID+Verified, Casual+Research vs Research to avoid showing Verified alongside Research Grade are these constrained options versatile enough to accommodate searches people need
![screen shot 2015-07-15 at 11 52 35 am](https://cloud.githubusercontent.com/assets/598026/8707025/0bfa9efc-2ae8-11e5-806d-61de7199c4d8.png)

**B.** Alternatively, what about not displaying NeedsID in any of these three places (obs component, obs show, obs search filters) on launch and then later swapping it in by not displaying Research Grade in any of these three places as I proposed above?

**C.** Alternatively, revisit one of these options to move Unverified/NeedsID/Verified closer to Casual/Research in order to make their explanations less confusing (Option 1 is how things currently are, I prefer Option 4 then Option 2 to Option 1):
![screen shot 2015-07-15 at 12 14 44 pm](https://cloud.githubusercontent.com/assets/598026/8707530/23decdce-2aeb-11e5-9000-2497814105ba.png)

**Comment by kueda** [comment]
Currently running a version on staging that deals with most of your feedback.

A1) I don't think there's any disagreement there, and this proposal is already running on staging, e.g. http://staging.inaturalist.org/observations?id_status=needs_id&quality_grade=research

A2) Combined treatment currently on staging, e.g. http://staging.inaturalist.org/observations/1760899. IMO, it's confusing either way, not sure which is less confusing, but separate takes up more space (bad) and duplicates a lot of stuff (bad), but makes it clear the two qualifiers are separate.

A3) That seems fine to me. Is this really controversial enough to merit discussion?

B) IMO, not showing things sucks. If you don't show needs ID, identifiers lose the ability to distinguish observations that need their attention and those that don't at a glance anywhere on the site, and everyone loses insight into how the system is actually working. If you don't show the quality grade, again everyone loses insight and iNat becomes more of a black box, but you also lose the huge incentive achieving a higher quality grade provides (which, as we've discussed *ad nauseum*, I don't personally care for, but drives a lot of contribution and identification on the site). Also, these elements don't just provide insight into how iNat works, they are interactive, and provide opportunities for the community to improve our data. If we hide them, we lose that. We can de-emphasize these complexities to avoid confusing people who don't really care about them, but they should always be accessible to the people who do. Simply documenting how it works in help sections or blog posts seems like we are only revealing how the system works grudgingly. I think we should instead take pride in our transparency.

C) I admit after actually trying to fit these things onto a page they seem less orthogonal to me than they did before. As you've pointed out all your options have downsides, though they all seem equally bad to me, so I guess I don't have a preference here. Doing things like requiring wildness for things to be verifiable is a value statement about what kinds of information we're interested in, but I guess we already do that with research grade.

**Comment by loarie** [comment]
Ok - if you don't like (B) lets take it off the table (unless anyone else wants to go to bat for it) - which leaves (A) and (C). If you or anyone else don't feel strongly about (C), then I'd really like to push for C Option 4 and if not C Option 2.

C Option 4:
1. Add <=family rank constraint to RG, which would turn ~66k coarsely ID'd RG obs Casual
2. Add Wild constraint to NeedsID/Verified
3. Choose either Verified OR Research Grade as the single term and be consistent
4. Simplify 'Data Quality & ID Status' like so
![screen shot 2015-07-15 at 3 36 56 pm](https://cloud.githubusercontent.com/assets/598026/8711497/59281334-2b07-11e5-968f-3b7b9d547e7e.png)

C Option 2
1. Add <=family rank constraint to RG, which would turn ~66k coarsely ID'd RG obs Casual
2. Simplify 'Data Quality & ID Status' like so
![screen shot 2015-07-15 at 3 40 20 pm](https://cloud.githubusercontent.com/assets/598026/8711549/d1fe348c-2b07-11e5-96c6-5951f0c24326.png)

Curious here or in meeting tomorrow thoughts on: C Option 4 vs C Option 2 vs A

**Comment by carrieseltzer** [comment]
Hi guys. I wanted to chime in because I've been following this and I know you're meeting today (if you haven't already!).

I've lost track of the nuances of proposed functionalities of A-D and 1-4, but I just wanted to voice two concerns of mine.
1. That a non-wild observation can still get "needs id" status (I know that's one of the options outlined above, so this is my vote for that).
2. That a coarsely id'd observations (e.g. "plants") that can't be id'd all the way to species don't leave the "needs id" status until they can't go any further. In some cases it might be family, but in others it might be genus. It wasn't totally clear to me that the possibilities outlined would accommodate that.

Looking forward to hearing what comes out of today's discussion!

**Comment by loarie** [comment]
Hi Carrie - 
>1. That a non-wild observation can still get "needs id" status (I know that's one of the options outlined above, so this is my vote for that).

That would be C option 2 as opposed to C option 4. I'm personally in favor of C option 4 because IMO we shouldn't put observations of captive organisms or observations without metadata like photos or locations up front on the site by default (e.g. people should have to go looking for them to surface them) because they distract from the core use of the site which is sharing observations with a community for ID and creating high quality data for science along the way. IMO, the additional complexity of doing this separately for captive AND obs without metadata outweighs the benefit of this very small marginal use case of people posting captive things for ID and IDers wanting to/being able to ID captive obs. But I hear both sides of the argument.

>2. That a coarsely id'd observations (e.g. "plants") that can't be id'd all the way to species don't leave the "needs id" status until they can't go any further. In some cases it might be family, but in others it might be genus. It wasn't totally clear to me that the possibilities outlined would accommodate that.

way the feature is being proposed under all the options discussed here, Needs ID gets turned on at jobs creation and gets turned off automatically if an obs community ID was at species level. But users could vote it on or off for individual jobs as needed. So I think there's no concern here.

**Comment by carrieseltzer** [comment]
Thanks for the quick clarification, Scott. I don't feel that much more strongly about option C2 over C4 (I'm like a 4 on a 0-10 scale) and I think deciding to go with C4 is a sound strategic community decision. The use case I'm thinking of is mainly garden plants, which is how some people start, but there are obviously many other (and more targeted) resources for those scenarios anyways. I definitely agree with you in the case of observations without essential metadata. 

Regarding "needs id" status, that's great. So it defaults to on until people vote it off or it reaches species level id. That sounds awesome.

**Comment by naturalistcharlie** [comment]
Yeah, sorry to chime so much here but here are the cases where I think
cultivated plants are valuable additions to iNat:

-Native plants or pollinator-friendly plants that provide important habitat
for insects and other animal species
-Invasive plants planted in a landscape setting, or plants that are
harboring an invasive insect or disease.
-Observations of phenology which may be used to track climate change or
other such factors.

I don't think they should be tracked with wild plants, and I agree that
they are of little value without photo and location. But with photo and
location I think these are still worthy of an ID, if less so than wild
individuals.

With animals i can think of few if any cases where captive animals are
useful in iNat. A few weak examples could be outdoor cats that may eat
songbirds, or cattle in a field where grazing is ecologically important
(positive or negative effects).

I also don't feel strongly about it, but I do think it can be valuable to
track planted things, especially those which persist from year to year (for
instance plants that do not survive a Vermont winter are not of much
interest here).

On Thu, Jul 16, 2015 at 2:42 PM, carrieseltzer <notifications@github.com>
wrote:

> Thanks for the quick clarification, Scott. I don't feel that much more
> strongly about option C2 over C4 (I'm like a 4 on a 0-10 scale) and I think
> deciding to go with C4 is a sound strategic community decision. The use
> case I'm thinking of is mainly garden plants, which is how some people
> start, but there are obviously many other (and more targeted) resources for
> those scenarios anyways. I definitely agree with you in the case of
> observations without essential metadata.
>
> Regarding "needs id" status, that's great. So it defaults to on until
> people vote it off or it reaches species level id. That sounds awesome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/576#issuecomment-122046159>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by joellebel** [comment]
From a product standpoint I think it would be more beneficial to start out with the simpler approach of only having one status (Research Grade or Verified), and seeing if it can accommodate our main target audience which is naturalists (advanced or beginner) observing wild organisms. I think C4 targets this audience best with the least complexity. If that does not work we can certainly introduce more complexity down the road.

**Comment by kueda** [comment]
Ok, we decided to go with what Scott described as C option 4: collapse ID status and quality grade so that there are only 3 mutually exclusive states: unverifiable, needs ID, and research grade. Research grade will change so that it will require a community ID of family or lower.

Carrie and Charlie, we get that people who observe captive organisms still need IDs (especially new users who often observe captive / cultivated things first), but we decided that was a pretty niche activity on the site, and even if it wasn't, identifiers tend not to care about captive / cultivated stuff anyway, so even if we included them in the "needs ID" category most people would just ignore them. The only use-case we were really compelled by there is the need to welcome new users who observe their dog, and we might just want to build some specialized UI for that (maybe a part of some identifier-specific "help desk" functionality).

A spec I can follow:

- [ ] remove migration that creates id_status column
- [ ] remove id_status from ES index
- [ ] remove ID status from obs components, just show quality grade with different styles for different states
- [ ] change research grade determination to include the rank requirement (family or lower)
- [ ] either re-implement the needs ID vote as a QualityMetric or replace the other quality metrics with Votes (sort of made sense to use different systems when id_status and quality_grade were different things, but not if they're the same)

On release:

- [ ] update quality_grade on all observations
- [ ] rebuild the ES observations index

**Comment by naturalistcharlie** [comment]
That makes sense. I guess one could search for the non wild observations
anyway. I look forward to these changes!

On Thursday, July 16, 2015, Ken-ichi <notifications@github.com> wrote:

> Ok, we decided to go with what Scott described as C option 4: collapse ID
> status and quality grade so that there are only 3 mutually exclusive
> states: unverifiable, needs ID, and research grade. Research grade will
> change so that it will require a community ID of family or lower.
>
> Carrie and Charlie, we get that people who observe captive organisms still
> need IDs (especially new users who often observe captive / cultivated
> things first), but we decided that was a pretty niche activity on the site,
> and even if it wasn't, identifiers tend not to care about captive /
> cultivated stuff anyway, so even if we included them in the "needs ID"
> category most people would just ignore them. The only use-case we were
> really compelled by there is the need to welcome new users who observe
> their dog, and we might just want to build some specialized UI for that
> (maybe a part of some identifier-specific "help desk" functionality).
>
> A spec I can follow:
>
>    -  remove migration that creates id_status column
>    -  remove id_status from ES index
>    -  remove ID status from obs components, just show quality grade with
>    different styles for different states
>    -  change research grade determination to include the rank requirement
>    (family or lower)
>    -  either re-implement the needs ID vote as a QualityMetric or replace
>    the other quality metrics with Votes (sort of made sense to use different
>    systems when id_status and quality_grade were different things, but not if
>    they're the same)
>
> On release:
>
>    -  update quality_grade on all observations
>    -  rebuild the ES observations index
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/576#issuecomment-122105082>
> .
>


-- 
Sent from Gmail Mobile

**Comment by loarie** [comment]
Whats on staging looks really good. I can simulate the 'ID help desk' use case with
http://staging.inaturalist.org/observations?taxon_id=84718&quality_grade=needs_id&reviewed=false
which works great. 

I  have two questions:

1. we have 3 bins of obs now: unverifiable, needs ID, and research. On staging, needs ID and research obs components both get badges which is like 95% of all obs. Would it be better to decorate Unverifiable and Research but not Needs ID to reduce the amount of decoration or is it nice to be explicit about these two bins?

2. the current plan when we revisit the search UI is to have obs/index default to displaying quality_grade=needs_id OR quality_grade=research (ie not quality_grade=unverifiable) - it would be nice to play with this filter set with the params to see what this would be like, is there an easy way to do that?

**Comment by kueda** [comment]
1. I like decorating needs ID stuff because it shows things that need my attention. I certainly wouldn't want to display "Unverifiable" and "Needs ID" the same way, but if the plan is not to show unverifiable stuff by default, maybe we could try labeling RG, Unverifiable, and leave Needs ID undecorated, but maybe we should cross that bridge when we get to it, unless you think it's worth trying to tackle that before releasing this
1. Not at present but I think that would be easy to add. /observations?quality_grade=research,needs_id, perhaps? We use commas for some other URL params like that...

**Comment by loarie** [comment]
ok - in that case, is there anything that needs to happen before releasing this? Since this is a relatively big change, it might be nice to do the whole gorrilla, blog post, alerting of the Network members routine. Also, should we fold in the maps to a single release or stagger them?
