### ISSUE TITLE
export observations email error

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/inaturalist#585]
when tapping "Receive an email with your data" I see the following:

![screen shot 2015-06-03 at 9 21 22 pm](https://cloud.githubusercontent.com/assets/515947/7976864/c908ee7c-0a36-11e5-8ae5-c3b5e0c077e8.png)

**Comment by pleary** [comment]
I cannot replicate this problem. When a get a chance, could you check Alex and see if you're having the same problem? We run a rake task on every deploy to generate all the translations we us in JS, including this one, and maybe there was a problem with that rake task a couple weeks ago?

**Comment by alexshepard** [comment]
works for me now
