### ISSUE TITLE
sort on users screwy

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#586]
Initial sort when this loads is odd - wildmarin should be #1 by obs
http://www.inaturalist.org/places/point-reyes-national-seashore#peopletab
sorting by species and then by observations seems to fix it.

**Comment by kueda** [comment]
Seems like this might have been fixed in the interim.

**Comment by loarie** [comment]
Still looks screwy to me. Here's what I see [here](http://www.inaturalist.org/places/point-reyes-national-seashore#peopletab) on load
![screen shot 2015-07-02 at 2 36 45 pm](https://cloud.githubusercontent.com/assets/598026/8488493/d1cd4196-20c7-11e5-935a-c8a02eeadec1.png)
when I should see this:
![screen shot 2015-07-02 at 2 36 34 pm](https://cloud.githubusercontent.com/assets/598026/8488494/d1e5c824-20c7-11e5-9b0b-ec4edad2c262.png)
