### ISSUE TITLE
obs not displaying 'threatened badge' recognizing conservation status associated with taxon and place

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#598]
this obs which is in Indiana DOES auto-obscure the coordinates but DOES NOT display the 'threatened badge' on the identification component where the conservation status associated with this taxon in Indiana https://www.inaturalist.org/observations/1633265
its close to the Michigan border and obs of this taxon in the center of Indiana do recognize the conservation status, but I'm not sure that that border proximity is the problem

**Comment by kueda** [comment]
What's happening here is the public positional accuracy circle 10,000 m is not contained within the bounding box of Indiana, so if we say the observation was made in Indiana we're reducing the uncertainty of the coordinate obscuration by quite a bit. I believe the intent here was not to reduce the uncertainty of obscuration, as well as to try to make relatively accurate statements about where observations were, e.g. if the coordinate are in San Francisco but the accuracy circle extends to Reno, we can't say with certainty that the observation was made in San Francisco.

If we made an exception in this case, e.g. we pulled conservation statuses based on the coordinates without considering the spatial uncertainty, I guess we would provide more coordinate uncertainty b/c it would be auto-obscured, but less than we would if the user manually obscured it, b/c viewers would know the obs was made in Indiana. So I don't really see a perfect solution here.

**Comment by loarie** [comment]
I don't think I understood exactly what was going on here when I made this issue. Can you confirm that this is the case:
1. all observations of taxa in places with conservation statuses for that species (e.g. obs of sandhill cranes in Indiana) ARE being obscured automatically
2. but if the public positional accuracy overlaps the border, we DO NOT display the 'threatened in Indiana' badge on the observation page
I believe thats whats happening with this test obs http://www.inaturalist.org/observations/1635622. I was unaware when I made this issue that 1 was happening
![screen shot 2015-06-15 at 11 26 08 am](https://cloud.githubusercontent.com/assets/598026/8167169/5f3d0e96-1351-11e5-815d-d01b7bcc2953.png)

**Comment by kueda** [comment]
Well, be clear about what you're saying. These two statements are true:

1. all observations of taxa in places with conservation statuses for that species *AND have coordinates that lie within the boundaries of those places* (e.g. obs of sandhill cranes in Indiana) ARE being obscured automatically
1. but if the public positional accuracy overlaps the border, we DO NOT display the 'threatened in Indiana' badge on the observation page

It's inconsistent, but also seems to provide the maximum privacy for the observed organism. I don't feel incredibly strongly about which way to go on this, but imagine if the obscured coordinates for this observation were such that only a sliver of the circle entered Indiana. If we then revealed that the true coordinates were in Indiana by showing an Indiana conservation status, it would be very obvious where the true coordinates were, and would effectively remove the effect of obscuring the coordinates. It's an edge case, but one that would also apply if we switched to coordinate obscuration by coordinate rounding instead of choosing a random location within a radius.

**Comment by naturalistcharlie** [comment]
Seems to me with a large place like a state, nothing is lost by auto
obscuring any time it's in Indiana.  Either we auto obscure in which case
it's sometimes obvious where it is, or we don't in which case it is always
obvious. Right?
Of course, with a smaller place, like a 40 acre preserve, that isn't true.

Not sure what the answer is, just sharing thoughts.

On Mon, Jun 15, 2015 at 2:38 PM, Ken-ichi <notifications@github.com> wrote:

> Well, be clear about what you're saying. These two statements are true:
>
>    1. all observations of taxa in places with conservation statuses for
>    that species *AND have coordinates that lie within the boundaries of
>    those places* (e.g. obs of sandhill cranes in Indiana) ARE being
>    obscured automatically
>    2. but if the public positional accuracy overlaps the border, we DO
>    NOT display the 'threatened in Indiana' badge on the observation page
>
> It's inconsistent, but also seems to provide the maximum privacy for the
> observed organism. I don't feel incredibly strongly about which way to go
> on this, but imagine if the obscured coordinates for this observation were
> such that only a sliver of the circle entered Indiana. If we then revealed
> that the true coordinates were in Indiana by showing an Indiana
> conservation status, it would be very obvious where the true coordinates
> were, and would effectively remove the effect of obscuring the coordinates.
> It's an edge case, but one that would also apply if we switched to
> coordinate obscuration by coordinate rounding instead of choosing a random
> location within a radius.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/598#issuecomment-112166020>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by ChristopherTracey** [comment]
It seems similar to the issue of an obscured terrestrial species along the shore of a large body of water.  many times, the obscured point is placed in the body of water, where the species is very unlikely to be found, living that remaining sliver on land as a pretty good representation of where the species is.

Would it be possible to keep the obscured coordinates within the state boundary?

**Comment by loarie** [comment]
OK - thanks - my apologies for misunderstanding this issue - I think others, including the original reporter of this on the GoogleGroup are similarly confused about what's happening as I was https://groups.google.com/forum/#!topic/inaturalist/Ox_w4Yr48A4

I've adjusted the title and initial comment to clarify that:
1) There is no bug/unusual behavior with auto-obscuring. Observations ARE being auto-obscured. I'll chime in to the google group to clarify this.
2) The only issue here seems to be on whether we should display the 'Threatened' badge on the observation components:
![screen shot 2015-06-15 at 12 58 28 pm](https://cloud.githubusercontent.com/assets/598026/8169424/5536c63c-135e-11e5-9270-59b1b1deb01c.png)
As Ken-ichi clarified, in the example posted to the google group the public positional accuracy circle is not completely contained within Indiana so showing the 'EN in Indiana' would reveal additional information about this private location.

Since this is not a bug, I'm closing this 'bug issue', but I do think that the confusion introduced by the inconsistent display of threatened badges is a cost that outweighs the benefit of not revealing additional information about obscured points (which as CTracey says is analogous to existing issues with terrestrial obs along big bodies of water). So if someone wants to open an 'improvement issue' to suggest displaying threatened badges regardless of the public positional accuracy circle, IMO that would be a good idea
