### ISSUE TITLE
Replace Windshaft tiles with Ellasticsearch-based maps

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#601]
Windshaft tiles use the DB for querying, and this can cause slow performance when we need to generate tiles for anything that has not been denormalized. Here are some pros t switching to ES-based tiles:

 - We will no longer need to generate cache tables for grid map zoom level (and as a result the low-zoom tiles will no longer be limited to data generated at denormalization time - they will be based on real-time data)
 - Elasticsearch uses a geohash indexing system internally, which essentially gives use the ability to efficiently generate low-zoom tiles representing 10s of thousands of points
 - We will be able render tiles on demand for queries based on any field in Elasticsearch (as long as the code has been updated to support it). That means we can generate map tiles for just about any query generated from the form at http://www.inaturalist.org/observations/
 - Elasticsearch can generate real-time replicas in different data center, so we can host a copy at GoGrid and run our entire map tiling code there. That will allow us to get rid of two small Rackspace servers currently hosting Windshaft
 - The same code we use to generate queries for map tiles can be used in a data API that can one day replace a lot of observations API logic in the Rails codebase. This will also make new development easier, like getting into websocket-based features

I have my latest proposal for the first round design of the maps running on http://gonatus.inaturalist.org (same authentication as Staging). See https://github.com/inaturalist/design/issues/14 for more design discussion. Here is a summary of all changes compared to our Windshaft implementation:

 - All grids are replaced by dots with opacity 0.4, but using the same color schemes as grids use. So dots on http://gonatus.inaturalist.org/observations are all grey, and dots on http://gonatus.inaturalist.org/taxa/3/map are all blue. The transparency allows at least a minor level of representing point density
 - The high-zoom tiles (formerly grids) are also generating interactivity data so all map dots are clickable and open the corresponding observation. If there are many in a single interactivity grid cell, then the most recent will be shown
 - Not all filters have been implemented yet, but we can currently do place filtering with map tiles which we had to disable in Windshaft http://gonatus.inaturalist.org/observations?place_id=6793
 - I added a heatmap view of observations http://gonatus.inaturalist.org/observations/map (clickable like everything else)
 - It's worth noting that the Windshaft grids were more visible on Google's satellite maps since they had a white border, and the new dots have border because I thought it made high-zoom maps too noisy

I have gonatus accepting some extra parameters for testing:

To change the zoom where we cross over from summary dots to real points (it is currently set at zoom 9, the same as Windshaft, but we can set it to whatever we want):
  http://gonatus.inaturalist.org/observations/map?gridmaxzoom=3

To try different color of the dots (%23000000 is #000000 escaped):
  http://gonatus.inaturalist.org/observations/map?color=%23000000

My proposal is to release maps as seen on gonatus, with clickable grey or colored dots instead of grids. We can always change the styles later, but I am basically looking for confirmation we're happy with this as a first pass so that we can move off of Windshaft. It would be great of we could add any comments about changes wanted/needed before release of these maps to this ticket. Then any comments about future maps design directions can go to https://github.com/inaturalist/design/issues/14 , and any comments about future functionality can be added to the repo for the new maps https://github.com/inaturalist/iNaturalistAPI

**Comment by pleary** [comment]
Here are some links for comparison:

Observations index:
http://gonatus.inaturalist.org/observations
http://www.inaturalist.org/observations

Observations show:
http://gonatus.inaturalist.org/observations/1610563
http://www.inaturalist.org/observations/1610563

Observations map:
http://gonatus.inaturalist.org/observations/map
http://www.inaturalist.org/observations/map

Taxa map:
http://gonatus.inaturalist.org/taxa/3/map
http://www.inaturalist.org/taxa/3/map

Users show:
http://gonatus.inaturalist.org/observations/finatic
http://www.inaturalist.org/observations/finatic

Projects show:
http://gonatus.inaturalist.org/projects/national-geographic-great-nature-project
http://www.inaturalist.org/projects/national-geographic-great-nature-project

**Comment by loarie** [comment]
(reposting this comment because I put it on the wrong issue)
One thing I noticed on observtions/index is that a single click on one of the 'featured' markers launches two infowindows: a quickly loading one for the featured marker and a slower loading one from the tiles
![screen shot 2015-06-16 at 9 47 43 am](https://cloud.githubusercontent.com/assets/598026/8188868/52b7ecec-140d-11e5-874a-7556b6043aef.png)

**Comment by loarie** [comment]
Also, the infowindows clicking on the tiles at coarse zoom levels on obs/map don't seem to load for me at least over several minutes - anyone else seeing this?
![screen shot 2015-06-16 at 9 52 41 am](https://cloud.githubusercontent.com/assets/598026/8188890/76427b00-140d-11e5-86f8-e9f210530275.png)

**Comment by pleary** [comment]
The latter problem I think is due to data not being in sync. I am using the "production" version of the ES map tiler on gonatus, but the data on gonatus is a week or so old. So many new observations will try to render and won't be able to. I'll look into that first problem with the double info windows - seems like a legitimate bug.

**Comment by loarie** [comment]
I spent some time playing with this and I guess I'm fine with the default colors and heatmap/marker zoom level transition. I vote to release this as is

**Comment by kueda** [comment]
I think this is mostly looking good, with the one caveat you note that at high zoom levels the unbordered dots aren't very visible on satellite tiles, e.g.

![screen shot 2015-06-16 at 12 06 38 pm](https://cloud.githubusercontent.com/assets/22691/8192048/667a5040-1420-11e5-991c-e34c42487061.png)

I also agree the white borders are noisy, but I feel like that's only a problem when viewing *all* observations. Looks ok for single taxa:

![screen shot 2015-06-16 at 12 08 09 pm](https://cloud.githubusercontent.com/assets/22691/8192075/9f1f2bfa-1420-11e5-85f5-fdc136aa6c81.png)

I think it would look better on maps like http://gonatus.inaturalist.org/taxa/map?gridmaxzoom=1&taxa%5B%5D=134314&taxa%5B%5D=24259&taxa%5B%5D=120719&taxa%5B%5D=120720#6/38.446/-121.175 too (though the gridmaxzoom param doesn't seem to work there).

Could we only show the borderless dots for the all obs layer? Or maybe just show them when there's no taxon filter?

**Comment by pleary** [comment]
Right now there are 3 distinct styles - A) the blue-to-red heatmap, B) the slightly transparent colored dots, and C) the standard points with borders you get at the highest zoom levels. It sounds to me like you're suggesting that we simply use style C when we have a taxonID? That would be different than adding a border to style B since style B is half transparent, and style C is fully opaque (except for points representing captive observations which are slightly transparent).

If that's the case, then can you think of a place where we would show style B with any color other than grey? Or put another way - can you think of a place we'd want to show colored points which did not use style C?

**Comment by kueda** [comment]
I can't. I like that style B retains some indication of density, but I think seeing the points overrides that, so B and C are a tradeoff between density and detecting the points, then I lean toward C.

**Comment by pleary** [comment]
I updated gonatus with some changes. The double infowindow bug should be fixed. I also made it so we only ever show style B in grey, and that will continue to appear on observations/index, users/show and projects/show. Observations/show and taxa/show will use style C at all zooms, and taxa/map will use a slight variation on style C that bypasses the iconic_taxon color for a specified override color.

**Comment by loarie** [comment]
IMO we should go with Style B for all maps at coarse zoom levels (inc. obs/show and taxa/show) so we prioritize showing density and simulate something akin to a range map over trying to show what overlapping distinct observations. e.g.
http://gonatus.inaturalist.org/taxa/5212/map#3/37.298/-100

Whats the motivation for ever showing Style C at coarse zoom levels?

But either way, the current obscured convention for Style C maps is to hide the markers. So whats on gonatus currently won't work for threatened taxa e.g.
http://gonatus.inaturalist.org/taxa/64970/map#3/48.03/-122

**Comment by kueda** [comment]
Scott, read above: Style B is really hard to see over satellite tiles  for some colors, e.g. the green we use for plants (I had a screenshot of coast live oak above). IMO, it's more important to see that there are observations on the map than it is to see how dense they are. I would prefer to visualize both, but if we can't have grids (impossible apparently) or heat maps (also hard to see unless we use the horrifying ROYGBIV ramp) at high zooms, then I'd prefer to see that there are observations.

Patrick, is there a way to specify a heat map color ramp as a URL param?

**Comment by pleary** [comment]
> Whats the motivation for ever showing Style C at coarse zoom levels?

The main motivation is that Style B is can be very hard to see on satellite maps. Ken-ichi requested we try it, and I think what is on Gonatus now is basically what he requested. I actually like how the red tailed hawk map looks with only points. The most extreme example would be all animals http://gonatus.inaturalist.org/taxa/1/map#3/27.525/-71.628 . While it is very busy, I like it better than the grids it will be replacing. 

> So whats on gonatus currently won't work for threatened taxa

I'd forgotten that was one thing the grids gave us. What if we just used the obscured coordinates and placed a dot there according to the given style. Those dots would still be clickable when visible, but they would disappear when you got below our threshold zoom. Maybe they could be the borderless dots. I'll play around with it.

**Comment by pleary** [comment]
> Patrick, is there a way to specify a heat map color ramp as a URL param?

Not currently but I can add something like that

**Comment by naturalistcharlie** [comment]
To me (a plant person) it is very important that the dots don't disappear
against those air photos. I look at those maps a lot. I too like the
density maps but they aren't worth missing the ability to see things, in my
opinion.  If it is easy to do, maybe use the heat map only for the map and
switch to the dots for air photos? But I don't know if that would work or
not

On Tue, Jun 16, 2015 at 7:41 PM, Patrick Leary <notifications@github.com>
wrote:

> Patrick, is there a way to specify a heat map color ramp as a URL param?
>
> Not currently but I can add something like that
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/601#issuecomment-112603678>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by pleary** [comment]
You can test out different heatmap colors now http://gonatus.inaturalist.org/observations/map?heatmap_colors=violet0.4,blue0.5,green0.6,yellow0.9,orange0.97,red0.99

Read about the colorize-alhpa syntax at https://www.mapbox.com/blog/colorize-alpha-image-filter/

**Comment by naturalistcharlie** [comment]
I don't have the secret password :)

On Tue, Jun 16, 2015 at 8:02 PM, Patrick Leary <notifications@github.com>
wrote:

> You can test out different heatmap colors now
> http://gonatus.inaturalist.org/observations/map?heatmap_colors=violet0.4,blue0.5,green0.6,yellow0.9,orange0.97,red0.99
>
> Read about the colorize-alhpa syntax at
> https://www.mapbox.com/blog/colorize-alpha-image-filter/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/601#issuecomment-112606909>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by loarie** [comment]
>Style B is really hard to see over satellite tiles for some colors
How about using a single color poor-mans-heatmap with white border approach for taxa/show, e.g. http://gonatus.inaturalist.org/observations/map?heatmap_colors=green0.6,white0.4#3/19.394/-93.252 This seems to remedy the hard-to-see complaint

I don't think the hard-to-see problem is the issue as this can be remedy'd using both Style B-like and Style C approaches. I think the issue is more philosophically/aesthetically do we prefer to summarize/abstract individual observations at coarse zoom levels (eg Style A/B) or do we prefer to maintain the integrity of individual observations even at coarse zoom levels (eg Style C).

I can see pros-and-cons to both approaches

**Comment by kueda** [comment]
I think the pseudo heatmap with white border does a decent job with visibility for maps with a lot of points, but not so much when viewing small amounts of data with little spatial spread from very high zoom levels, e.g.

http://gonatus.inaturalist.org/observations/map?place_id=5586&heatmap_colors=green,white0.5#3/32.314/-75.101

If you turn off the place boundary, you get a white smudge which is hard to see with the satellite tiles and almost impossible to see over the terrain and road tiles.

Here's how the Cascades Panthea Moth looks [with the rainbow heatmap](http://www.inaturalist.org/observations/map?taxon_id=226911&heatmap=true&elastic=true#5/41.968/-118.828):

![screen shot 2015-06-16 at 10 55 23 pm](https://cloud.githubusercontent.com/assets/22691/8200512/e03cc1ce-147a-11e5-8b3d-37a727788ec3.png)

And here's [the same map with points](http://gonatus.inaturalist.org/observations/map?taxon_id=226911#5/41.03/-120.388):

![screen shot 2015-06-16 at 11 02 11 pm](https://cloud.githubusercontent.com/assets/22691/8200578/c20752ae-147b-11e5-8b22-82aa2d50c324.png)

There are aesthetics at play here, of course, but I think the hard-to-see problem is still a legit issue with the heatmaps.

**Comment by pleary** [comment]
I just put up another test. I found a compositing function that can allow borders on points and does a good job of fading the borders when points overlap. Here are samples of the same Coast Live Oak Ken-ichi posted before:

![screen shot 2015-06-17 at 11 40 59 am](https://cloud.githubusercontent.com/assets/48566/8211692/e5422dd8-14e5-11e5-8849-c239a7760971.png)

![screen shot 2015-06-17 at 11 41 10 am](https://cloud.githubusercontent.com/assets/48566/8211693/e75aef92-14e5-11e5-8a6a-9156852213ba.png)

I also added support for showing obscured observations above zoom level 8 (see http://gonatus.inaturalist.org/taxa/64970/map). I think this is getting closer to feeling like good replacement for the grids. Thoughts on this new point/heatmap mashup style?

**Comment by naturalistcharlie** [comment]
I think this one looks really good.

On Wednesday, June 17, 2015, Patrick Leary <notifications@github.com> wrote:

> I just put up another test. I found a compositing function that can allow
> borders on points and does a good job of fading the borders when points
> overlap. Here are samples of the same Coast Live Oak Ken-ichi posted before:
>
> [image: screen shot 2015-06-17 at 11 40 59 am]
> <https://cloud.githubusercontent.com/assets/48566/8211692/e5422dd8-14e5-11e5-8849-c239a7760971.png>
>
> [image: screen shot 2015-06-17 at 11 41 10 am]
> <https://cloud.githubusercontent.com/assets/48566/8211693/e75aef92-14e5-11e5-8a6a-9156852213ba.png>
>
> I also added support for showing obscured observations above zoom level 8
> (see http://gonatus.inaturalist.org/taxa/64970/map). I think this is
> getting closer to feeling like good replacement for the grids. Thoughts on
> this new point/heatmap mashup style?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/601#issuecomment-112856236>
> .
>


-- 
Sent from Gmail Mobile

**Comment by loarie** [comment]
Wow - I think that looks fantastic!

**Comment by loarie** [comment]
Assuming for the moment that everyone agrees this 'new point/heatmap mashup' is a good replacement for the grids:
![screen shot 2015-06-17 at 9 07 50 am](https://cloud.githubusercontent.com/assets/598026/8212408/6c4719d0-14d0-11e5-9d47-e9376ca40540.png)
Are you still thinking of keeping the convention of transitioning to a different style below zoom level 8 that preserves the integrity of individual markers:
![screen shot 2015-06-17 at 9 07 38 am](https://cloud.githubusercontent.com/assets/598026/8212407/6c4477b6-14d0-11e5-92b0-2463a3b7da8d.png)
as we currently do in production and you've mimic'd here on gonatus http://gonatus.inaturalist.org/taxa/1/map? Or did you also have on the table a single style across all zoom levels?

**Comment by pleary** [comment]
I'm thinking that for the initial release we could go with exactly what is on gonatus - so switching over classic points at zoom level 10 like we do in production now. That will give us these large dots to show obscured coordinates - which works well since the zoom cutoff (zoom 8) for obscured obs was based on the size of the grid cell, and these larger dots are fairly close to the size of those grids.

Effectively all we'd be releasing as far as the user is concerned is an alternative to the grids. Then we can make more changes once we settle into the new tileserver and come up with cool new ideas

**Comment by kueda** [comment]
Big circles / white borders look great, Patrick, and I think they address all our qualms. Nice.

**Comment by pleary** [comment]
Cool. To summarize where we ended up - there will be 4 different styles of map:
- the heatmap that only exists at http://gonatus.inaturalist.org/observations/map
- the small grey points on http://gonatus.inaturalist.org/observations
- the colored point/heatmaps like on http://gonatus.inaturalist.org/taxa/47115/map and http://gonatus.inaturalist.org/observations/finatic
- and then all of these switch over to the standard small colored points at zoom level 10

We can maybe talk briefly today about these styles, wether observations/index needs to be separate (I do like that the dots are smaller there), and the rollout plan for these new maps.
