### ISSUE TITLE
elasticsearch index does not replicate database date queries

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#609]
`Observation.query(user_id: 'kueda', on: '2015-6-8').count` should be the same as `Observation.elastic_query(user_id: 'kueda', on: '2015-6-8').count`, and http://www.inaturalist.org/calendar/kueda/2015/6/8 should show the same observations as http://www.inaturalist.org/observations/kueda?on=2015-6-8, but they don't because ES searches are only querying on UTC time. One solution would be to index observation date parts in addition to UTC date parts

**Comment by carrieseltzer** [comment]
I fully admit to not understanding the difference between ES and DB
searches, but I think that whenever a date query is run, that it should
query the observed_on field because that's the only one that is time zone
independent (i.e. you get results from that date no matter where in the
world it was on that date because it stores a raw date without a time stamp
or time zone). Just my 2 cents having thought about how iNat handles dates
because of the global snapshot.

On Thu, Jun 18, 2015 at 7:05 PM, Ken-ichi <notifications@github.com> wrote:

> Observation.query(user_id: 'kueda', on: '2015-6-8').count should be the
> same as Observation.elastic_query(user_id: 'kueda', on: '2015-6-8').count,
> and http://www.inaturalist.org/calendar/kueda/2015/6/8 should show the
> same observations as
> http://www.inaturalist.org/observations/kueda?on=2015-6-8, but they don't
> because ES searches are only querying on UTC time. One solution would be to
> index observation date parts in addition to UTC date parts
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/609>.
>



-- 
Carrie E. Seltzer, Ph.D.
National Geographic's Great Nature Project
www.greatnatureproject.org

**Comment by carrieseltzer** [comment]
For ease of reference, here are links to two threads in the google group where people mentioned what I think is this same problem:
-https://groups.google.com/forum/#!topic/inaturalist/VVIx6kCEXlE
-https://groups.google.com/forum/#!topic/inaturalist/iqZ_kbeX75Y

**Comment by pleary** [comment]
OK - it looks to me like Ken-ichi's example and the two examples in those Google groups threads are working as their reporters expect. Would someone mind sanity checking these few examples? I haven't reindexed all observations yet - only those from kueda, kestrel, and reallifeecology . The rest are slowly getting reindexed and should working properly later tonight. The key difference now is the last few weeks date searches have been based on UTC, which was admittedly weird. Now date searches are based on the time/date observed as recorded by the user, unless a timezone is specified in the search parameters

**Comment by pleary** [comment]
It's easier to compare Ken-ichi's example when sorting the observations by observed_on ascending:

http://www.inaturalist.org/observations/kueda?day=8&month=6&year=2015&order_by=observed_on&order=asc

http://www.inaturalist.org/calendar/kueda/2015/6/8

**Comment by kueda** [comment]
As far as I can tell you are sane.

**Comment by pleary** [comment]
A small miracle after getting my head wrapped up in time zones. I'm going to call this one resolved. I also commented on the two Google groups issues letting them know a fix is out
