### ISSUE TITLE
metrics to monitor iNat's performance as an identification provider

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#612]
We'd like to make some changes to help identifiers identify more and better, and thereby iNat a better place to get identifications and to make sure we are creating taxonomically verified data. Here are some metrics I think we should be monitoring:

1. time to ID: time between observation created_at and first identification created by someone other than the observer
1. time to community ID
1. number of unique identifiers
1. % identified

Here's some really gnarly SQL that will get at some of these:

```sql
DROP TABLE IF EXISTS identifications_for_others;
CREATE TABLE identifications_for_others AS
SELECT identifications.* 
FROM identifications JOIN observations ON identifications.observation_id = observations.id
WHERE identifications.user_id != observations.user_id;

DROP TABLE IF EXISTS community_identifications;
CREATE TABLE community_identifications AS
SELECT identifications.* 
FROM identifications JOIN observations ON identifications.observation_id = observations.id
WHERE 
  identifications.user_id != observations.user_id AND
  identifications.taxon_id = observations.community_taxon_id;

DROP TABLE IF EXISTS obs_id_stats;
CREATE TABLE obs_id_stats AS
SELECT
  o.id,
  o.created_at,
  count(i.id) AS identifications_count,
  o.community_taxon_id,
  MIN(t.rank_level) AS community_taxon_rank_level,
  MIN(i.id) AS first_identification_id,
  (EXTRACT(EPOCH FROM MIN(i.created_at)) - EXTRACT(EPOCH FROM o.created_at)) AS ttid,
  (EXTRACT(EPOCH FROM MIN(ci.created_at)) - EXTRACT(EPOCH FROM o.created_at)) AS ttcid
FROM observations o
  LEFT OUTER JOIN identifications_for_others i ON i.observation_id = o.id
  LEFT OUTER JOIN community_identifications ci ON ci.observation_id = o.id
  LEFT OUTER JOIN taxa t ON t.id = o.community_taxon_id
WHERE
  o.observation_photos_count > 0
GROUP BY o.id;

SELECT 
  round(AVG(ttid/60/60)::numeric, 2) AS avg_ttid, -- show as hours
  round(MEDIAN(ttid/60/60)::numeric, 2) AS med_ttid,
  round(MIN(ttid/60/60)::numeric, 2) AS min_ttid,
  round(MAX(ttid/60/60)::numeric, 2) AS max_ttid,
  round(AVG(ttcid/60/60)::numeric, 2) AS avg_ttcid,
  round(MEDIAN(ttcid/60/60)::numeric, 2) AS med_ttcid,
  round(MIN(ttcid/60/60)::numeric, 2) AS min_ttcid,
  round(MAX(ttcid/60/60)::numeric, 2) AS max_ttcid,
  round((count(first_identification_id) / count(*)::float * 100)::numeric, 2) AS percent_id,
  round((count(community_taxon_id) / count(*)::float * 100)::numeric, 2) AS percent_cid,
  round((count(CASE WHEN community_taxon_rank_level <= 20 THEN 1 ELSE NULL END) / count(*)::float * 100)::numeric, 2) AS percent_cid_to_genus,
  count(first_identification_id) AS total_id,
  count(community_taxon_id) AS total_cid,
  count(CASE WHEN community_taxon_rank_level <= 20 THEN 1 ELSE NULL END) AS total_cid_to_genus,
  count(*) AS total_observations
FROM obs_id_stats
WHERE
  obs_id_stats.created_at BETWEEN '2014-02-01' AND '2014-03-01'
```

which will yield

```
avg_ttid             | 407.44
med_ttid             | 2.74
min_ttid             | 0.01
max_ttid             | 10420.01
avg_ttcid            | 444.00
med_ttcid            | 2.77
min_ttcid            | 0.01
max_ttcid            | 10420.01
percent_id           | 71.91
percent_cid          | 70.68
percent_cid_to_genus | 64.66
total_id             | 18970
total_cid            | 18647
total_cid_to_genus   | 17059
total_observations   | 26381
```

That implementation has some caveats, mainly that the `ttcid` (time to community ID) is actually time until an identification added by someone else that matches the community ID, so not necessarily the time until there was enough confirmation to actually set the community ID, but maybe an ok proxy. `percent_cid_to_genus` is percent observationd ID'd to genus or lower.

Anyway, I propose that we add these as a new `SiteStatistic` type, where each day is a running average from the last 7 days like we're already recording. It will make the average TTID and percent identified look artificially low since it will miss observations that don't get ID'd for more than a week, but maybe it will still be informative.

@pleary, does this seem like a decent approach? We could also do something like store ttid and ttcid in the observations table, which might remove the need for some of these temp tables and/or sub-queries, and give us a more accurate ttcid.

**Comment by kueda** [comment]
Most of these have been implemented, just need to let them accumulate for a few days before they're visible at http://www.inaturalist.org/admin/stats

**Comment by naturalistcharlie** [comment]
Right now it's admin only, would you consider letting others (or at least
curators, or at least me) see it, once it's accumulated data? Maybe that
was the plan anyway.

On Fri, Jun 26, 2015 at 6:24 PM, Ken-ichi <notifications@github.com> wrote:

> Most of these have been implemented, just need to let them accumulate for
> a few days before they're visible at
> http://www.inaturalist.org/admin/stats
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/612#issuecomment-115908168>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement

**Comment by kueda** [comment]
Maybe eventually. Right now we're trying to come up with stats that are useful to us internally. Not really even sure if they're interesting yet.

**Comment by naturalistcharlie** [comment]
Fair enough. Some would probably be interesting to me, but i am a weird
nerd :)  I'll wait and see what you all come up with.

On Fri, Jun 26, 2015 at 9:15 PM, Ken-ichi <notifications@github.com> wrote:

> Maybe eventually. Right now we're trying to come up with stats that are
> useful to us internally. Not really even sure if they're interesting yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/612#issuecomment-115931298>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
coyot.es/slowwatermovement
