### ISSUE TITLE
point and summary tiles on /observations should match all filters

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#614]
Right now the tile server handles only a subset of the filters available at /observations, so basically taxon_id, place_id, and projects. Now that the tileserver is based directly on elasticsearch like /observations is, let's get the tiles to conform to all the filters.

Probably related to #541

**Comment by kueda** [comment]
http://www.inaturalist.org/observations?user_id=kueda&taxon_name=Diptera still doesn't work

http://www.inaturalist.org/observations?user_id=1&taxon_name=Diptera shows tiles for all of user 1's observations

http://www.inaturalist.org/observations?user_id=1&taxon_id=47822 seems to correctly show tiles of user 1's fly observations

**Comment by pleary** [comment]
OK I think all of these are addressed in e777e63 . The maps tiles were only mapping all users obs on by_login, and doing nothing at all on observations/project, both of which should be fixed. I also added support for taxon_name and for the user_id being a username

**Comment by kueda** [comment]
Rad, thanks.
