### ISSUE TITLE
Only show agree links once per taxon on observations/show

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#616]
Oft-requested, and the source of much confusion and redundant IDs.

**Comment by loarie** [comment]
The Android app is already doing this and is showing Agree on the earliest ID for each taxon
![screenshot_2015-06-29-14-34-47 1](https://cloud.githubusercontent.com/assets/598026/8419132/57fe7eaa-1e6c-11e5-8f01-f0ceb00d5bf6.png)
Is this how you're planning on making the web function?

**Comment by kueda** [comment]
Yup. Seem reasonable?

**Comment by loarie** [comment]
yeah I think it works well on Android
