### ISSUE TITLE
Display only project observations on project maps

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#619]
Currently, it appears that project maps show a handful of recent observations on top of every iNat observation (as grey dots).

Examples:
http://www.inaturalist.org/projects/new-zealand-global-snapshot-of-biodiversity-2015
http://www.inaturalist.org/projects/shutterbug-s-1998-at-thru-hike

Instead, it would be more relevant to display just the observations from that specific project (based on project_id for regular projects and time/place parameters for bioblitz projects).

**Comment by pleary** [comment]
I just fixed this in inaturalist/iNaturalistAPI@80ce7363e92caa83385f0d66974130210c68291b . My apologies - I released some map updates last night and introduced this bug. You may have tiles cached in your browser, so you may need to refresh the page or clear your cache (or wait an hour) to see the new tiles. You can also zoom into areas that aren't cached yet. Does that look OK to you?

**Comment by carrieseltzer** [comment]
Yes! That looks right now. Thanks!
