### ISSUE TITLE
Changing ID across iconic taxa does not update iconic_taxon_id

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#620]
e.g. http://www.inaturalist.org/observations/1668676
was created with ID of Amphibia, iconic_taxon_id was set accordingly
ID was added of Ray Finned Fishes, but iconic_taxon_id did not update

**Comment by loarie** [comment]
Some other examples:
http://www.inaturalist.org/observations/755865
http://www.inaturalist.org/observations/770917
http://www.inaturalist.org/observations/1420141

**Comment by kueda** [comment]
I think this is only happening when you edit the observation, not when you
add a new identification.

**Comment by loarie** [comment]
This issue was previously logged here https://github.com/inaturalist/inaturalist/issues/380
