### ISSUE TITLE
Taxon chooser should not return inactive taxa

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#623]
Some change is resulting in taxon choosers throughout returning inactive taxa. For example on Obs/new here:
![screen shot 2015-07-01 at 2 13 06 pm](https://cloud.githubusercontent.com/assets/598026/8464998/6de804b2-1ffb-11e5-9c42-8fb438b1f234.png)
Previously, the only taxon choosers that returned inactive taxa where on taxon_changes/new and edit
https://www.inaturalist.org/taxon_changes/new
![screen shot 2015-07-01 at 2 16 17 pm](https://cloud.githubusercontent.com/assets/598026/8465057/d27ea82c-1ffb-11e5-80ea-67f0fd743433.png)
and the main taxa search when 'show active and inactive taxa' was selected
![screen shot 2015-07-01 at 2 14 38 pm](https://cloud.githubusercontent.com/assets/598026/8465060/d5c9086a-1ffb-11e5-9ed0-af0e26154a9a.png)
It should be restored this way, mainly to prevent people from adding obs of inactive taxa

**Comment by pleary** [comment]
I think this is working as you describe. The new autocomplete isn't showing inactive taxa in any of the places we use it. The taxon changes interface uses the old taxon search, which does return inactive taxa. There's nothing preventing us from updating that taxon changes page to use the new autocomplete and add an option for that to return inactive taxa, but that would be for another ticket.

Does this seem resolved to you?

**Comment by pleary** [comment]
I'll tentatively close this. If this is still happening, please reopen with an example
