### ISSUE TITLE
Filtering for 'obscured observations' in user observations returns all observations

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/inaturalist#639]
This filter is returning all observations for me not only the obscured ones:

http://www.inaturalist.org/observations/charlie?utf8=%E2%9C%93&q=&search_on=&quality_grade=any&geoprivacy=obscured&identifications=any&captive=&place_id=&swlat=&swlng=&nelat=&nelng=&taxon_name=&taxon_id=&day=&month=&year=&order_by=observations.id&order=desc&rank=&hrank=&lrank=&site=&tdate=&d1=&d2=&filters_open=true&view=map

**Comment by pleary** [comment]
I think this is fixed now Charlie (b4d039c). Would you mind double checking?

**Comment by pleary** [comment]
I'm going to call this fixed, but please reopen with an failing example if you find one

**Comment by naturalistcharlie** [comment]
Oh no, my email i wrote earlier never sent! Sorry about that. In any event
it is working properly for me now.

On Mon, Jul 20, 2015 at 3:01 PM, Patrick Leary <notifications@github.com>
wrote:

> I'm going to call this fixed, but please reopen with an failing example if
> you find one
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/639#issuecomment-122989679>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
