### ISSUE TITLE
Correctly display number of IDs in table view

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#643]
I noticed that observations that don't have a taxon_id also don't display an observation count in table view. This happens when the user hasn't put an ID but someone else has.

Table view (shows no IDs, but it actually has one)
![screen shot 2015-07-14 at 10 48 28 am](https://cloud.githubusercontent.com/assets/7501183/8785989/82e3959a-2ef9-11e5-9f07-1680f67a4c04.png)

Observation page (shows someone else's id is already there, even though it doesn't display that in table view)
![screen shot 2015-07-14 at 10 48 36 am](https://cloud.githubusercontent.com/assets/7501183/8785994/889aa320-2ef9-11e5-9f69-793f6422dbf7.png)

Would this be resolved by implementing  #641?

Edited to add:
To see more examples (since that particular observation has an observer ID now), click on some of the observations from this search (old observations with photos from North America):
http://www.inaturalist.org/observations?utf8=✓&q=&search_on=&has%5B%5D=photos&quality_grade=any&identifications=any&captive=&iconic_taxa%5B%5D=unknown&place_id=9853&swlat=&swlng=&nelat=&nelng=&taxon_name=&taxon_id=&day=&month=&year=&order_by=observations.id&order=asc&rank=&hrank=&lrank=&site=&tdate=&d1=&d2=&filters_open=true&view=table

**Comment by loarie** [comment]
Hi Carrie, this isn't a bug, this is how the system was designed to work. Taxon_id kicks in if the obs user adds and ID or there is a community ID. Yes, #641 is a proposal to change this.

**Comment by carrieseltzer** [comment]
Ok. It just seems like table view should show that there IS an id on an observation even if the user hasn't added one. I'm all for solving this via #641!

**Comment by loarie** [comment]
sorry I thought you meant the taxon_id wasn't showing. If you think there's a bug where the ID isn't showing please include a URL, but keep in mind these displays are cached so changes don't show immediately

**Comment by carrieseltzer** [comment]
I do think this is a bug (and I think it's been this way for a while but I've never taken the time to report it). This might not need to be resolved separately from #641, but for the sake of documentation...

1. Click here:
http://www.inaturalist.org/observations?utf8=✓&q=&search_on=&has%5B%5D=photos&quality_grade=any&identifications=any&captive=&iconic_taxa%5B%5D=unknown&place_id=9853&swlat=&swlng=&nelat=&nelng=&taxon_name=&taxon_id=&day=&month=&year=&order_by=observations.id&order=asc&rank=&hrank=&lrank=&site=&tdate=&d1=&d2=&filters_open=true&view=table

2. See that no observations have any IDs indicated in the table view.

3. Click on the first observation (http://www.inaturalist.org/observations/523) -- by Ken-ichi :-)

4. See that it DOES have 1 id, even though no ids are shown in the table view.

**Comment by loarie** [comment]
got it, so
http://www.inaturalist.org/observations?user_id=whalend&year=2011&month=10&day=29
at the time of this writing only shows 
http://www.inaturalist.org/observations/37531
which should show '1ID' in table-view

**Comment by carrieseltzer** [comment]
This also has been fixed.
