### ISSUE TITLE
Spanish language text showing up on iNaturalist.org

### ISSUE THREAD

**Issue by md5** [inaturalist/inaturalist#645]
When I look at http://www.inaturalist.org/places/dukes-county, I'm seeing both Spanish taxon names and some of the tooltips are also in Spanish. The overall page is in English.

I thought this might be related to the fact that my `Accept-Language` header had Spanish in it as a secondary preferred language, but then I checked in another browser and saw the same behavior.

**Comment by pleary** [comment]
I think this was an issue of improper cache validation. I don't think we gain any measurable performance improvement from caching this partial, so I've removed it. This will be deployed later today

**Comment by md5** [comment]
Thanks @pleary!

**Comment by naturalistcharlie** [comment]
I am currently seeing Spanish text when I view the following place:
http://www.inaturalist.org/places/zebedee-wetland
see below:
![image](https://cloud.githubusercontent.com/assets/7171475/20270939/0b21b5a2-aa57-11e6-87cb-3afdc65c7a7c.png)
