### ISSUE TITLE
Changing order of names (places & lexicons) depending upon localization

### ISSUE THREAD

**Issue by zabas** [inaturalist/inaturalist#646]
I would like to request two new features: 
1) the ability to show or change default lexicons depending upon the location for new taxon names.
2) the ability to sort lexicons according to a logical order by that language

More info:
1) I am using iNaturalist in Japanese to add a lot of taxon names in Japanese, but it is a very clumsy process for me to search for Japanese out of the list. It would encourage more editing from users of the particular language if the process of finding their language was easier, for example, it becomes a default depending upon the user's locale.

Currently the universal defaults are:
-Unknown
-English
-Scientific name
-Spanish

2) The second feature also goes in hand with the first, "Japanese" is not so hard to find on the list if you are using the site in English (normally typing "j" will get you there instantly), but finding "Japanese" (日本語) in Japanese amidst a list of languages, some in Japanese, some not yet added to be translated, that are ordered by alphabetical order of their English name is very confusing and counterintuitive for other languages. Could there be language specific way of ordering languages?

<img width="637" alt="new taxon name" src="https://cloud.githubusercontent.com/assets/13493646/8889756/4a7864ce-3322-11e5-82fd-1a3e9db41746.png">

**Comment by kueda** [comment]
Def. agree on adding a place when creating a new name. Regarding sorting, here's a list of lexicons that have been translated into Japanese:

```
アフリカーンス語
ベンガル語
セブアノ語
ダバオ語
オランダ語
英語
フランス語
ゲラ語
ドイツ語
ハワイ語
ヘブライ語
ヒリガイノン語
アイスランド語
イロカノ語
イタリア語
日本語
韓国語
マルタ語
マオリ語
Misima-paneati
ノルウェー語
パンガシナン語
ポルトガル語
ルーマニア語
ロシア語
スペイン語
スェーデン語
タガログ語
タヒチ語
トケラウ語
トルコ語
ワライ語
```

And here's that list sorted using what our software thinks is the default sort for those characters:

```
Misima-paneati
アイスランド語
アフリカーンス語
イタリア語
イロカノ語
オランダ語
ゲラ語
スェーデン語
スペイン語
セブアノ語
タガログ語
タヒチ語
ダバオ語
トケラウ語
トルコ語
ドイツ語
ノルウェー語
ハワイ語
パンガシナン語
ヒリガイノン語
フランス語
ヘブライ語
ベンガル語
ポルトガル語
マオリ語
マルタ語
ルーマニア語
ロシア語
ワライ語
日本語
英語
韓国語
```

Sadly, despite being half-Japanese, I don't know enough about the language to tell if that looks correctly sorted. Does it look right to you?

**Comment by zabas** [comment]
The second list looks much better. Most of the languages listed are in the Japanese default a-i-u-e-o, ka-ki-ku-ke-ko, sa-shi-su-se-so, etc., order, however it gets complicated for the languages or words that use Kanji (the other languages use the phonetic katakana (kana) syllabary. Languages like "Japanese", "English", "Chinese", and "Korean" are written solely in Kanji, and in this case computers will automatically sort this by a default order which generally goes according to how complicated the characters are, which is counter intuitive to people.

Generally the way around this is to have another field in which the name is written phonetically using katakana or hiragana, so that all items can be sorted according to the phonetic field. iTunes and other software use this as well. I'm not too sure of how difficult it would be to add another phonetic field for automated sorting. This would prevent a person from having to manually input orders.

This phenomenon also happens on other parts of the site, (choose locations, including country names), and even the listing of taxa when browsing classification trees. As far as I can see the taxa are all organized alphabetically by the scientific name, and I believe this is an international standard though, so with regards to taxa, this could be kept as is. I'd be happy to help out on this if you need anything else just let me know.

**Comment by kueda** [comment]
Hm. I think http://www.localizingjapan.com/blog/2011/02/13/sorting-in-japanese-%E2%80%94-an-unsolved-problem/ summarizes what you're talking about pretty well, and recommends the same solution. Are language names and place names the only situations where you're hitting this? If that's the case, I think we could get around this by adding a separate translation file like `ja-phonetic.yml` where you could translate keys like "english" into a Hiragana representation of "英語".  We'd need to hide that locale as something people can select, and we'd somehow need to make it clear to the guys at translatewiki that such a file could *only* contain phonetic Hiragana.

@siebrand, does translatewiki provide a way to annotate certain translation files so translators know they should only be using a certain character set?

**Comment by zabas** [comment]
Yes, that post sums it up very well.

I tried thinking of some other areas where this becomes a problem, and so far I can only think of taxa names and how they are organized into a list. Currently taxa are organized as much as possible according to scientific name, which is universal and Latin and in alphabetical order. This really isn't a problem, at least for Japanese, since generally taxa are also ordered by the scientific name in Japanese as well, however there may be some different conventions for other languages. It could also be a future option to sort taxa by a certain order (alphabetical, phonetical, etc.) for certain lists (making it easier for different types of users), etc., but for now I am only experiencing this problem with place names and and lexicon names.

I'd be glad to translate the separate phonetic key files for Japanese of course. Let me know if there is anything I can do to help! Also, would it be possible to change the default lexicons that pop up depending upon the user's location/localization setting? I see this sort of being done with default taxon display names and it's an awesomely helpful feature!

**Comment by kueda** [comment]
@siebrand or @Nikerabbit, any opinions on adding a `ja-phonetic.yml` file for representing non-Roman translations as phonetic Roman-character translations so they can be sorted consistently? Does that kind of thing happen on translatewiki, or do you guys have another way you would do this?

**Comment by siebrand** [comment]
To answer the direct question: You can add that locale file to the source code, but that doesn't make it supported by twn. If your fallback system is so that all existing ui translations will be taken from the fallback code ja, that should be fine, I think. Is my assumption correct?

Something I'd like to point out: this ticket starts with "I'd like to make two feature requests." It's bad practice to do deal with multiple requests in a single issue in a ticketing system, so please split things up if this ticket stil, discusses multiple features.

**Comment by zabas** [comment]
Thanks for pointing that out. I'm still really new here and learning how it all works, but I've renamed the the ticket and will make another for the other issue.

**Comment by kueda** [comment]
> You can add that locale file to the source code, but that doesn't make it supported by twn.

Hm, so that would mean people could not use translatewiki to let people add strings to a `ja-phonetic.yml` file, os the only people who could contribute would be people on github who are ok editing the files directly and issuing pull requests, which is not ideal, but might work for the very motivated. How does that sound to you, @zabas?

**Comment by zabas** [comment]
I wasn't sure what the best format would be, however, I tried making a ja-phonetic.yml file and included what lexicons I could find, the defaults that have been included in the standard code. I'm not sure where or how to access the user submitted lexicons. I've submitted a pull request, but not sure if everything looks all right. Would you mind giving it a look over @kueda ?

**Comment by kueda** [comment]
Are you getting some kind of error message? The best way to do this is fork the repo, as you've done, then make a feature branch called "ja-phonetic" or something, make your changes on the branch, and push the branch to your repo. Then you should be able to issue a pull request to us from that branch and it will only contain the changes you made on that branch.

**Comment by zabas** [comment]
For some reason I couldn't do it earlier... The pull request has been submitted now.

**Comment by kueda** [comment]
@zabas I tried pulling in your changes and using them to sort the lexicons at http://gorilla.inaturalist.org/taxon_names/76085/edit?locale=ja. Can you take a look and see if it's ok?

**Comment by zabas** [comment]
Thank you for doing this! I think I need authorization or a login to view that. Can you let me know the ID and password?

**Comment by zabas** [comment]
Thanks for the login info. It looks great and comprehensible.

-I'm not sure why by Korean and Japanese are at the bottom, I suspect because they are written in Kanji, but it should be sorting everything by Hiragana. This is still much more understandable to almost all users. I'd like to localize some more of the lexicon names though but that is another project. Perhaps we'd need to import the recently added lexicons for translation?

For now though I would say this issue is about as resolved as I think we will get! Thank you!
