### ISSUE TITLE
obs w/ private coords showing map zoomed in on 0,0

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#648]
E.g. http://www.inaturalist.org/observations/1802119

**Comment by pleary** [comment]
This doesn't appear to be happening anymore. I'm not sure what changed to address this. We did re-obscure all obscured observations which may have helped. I think this can be closed now.

**Comment by kueda** [comment]
Also, I need to remember to include screenshots and not just URLs. Thanks for checking it out.
