### ISSUE TITLE
List taxa in /guides endpoint

### ISSUE THREAD

**Issue by premasagar** [inaturalist/inaturalist#650]
Guides aren't mentioned in the API documentation. By adding `.json` to a guide URI, a basic description of the guide is given, but with no mention of the taxa ids.

**Comment by kueda** [comment]
The guides API is not public, which for us means it might be publicly accessible, but it is not documented and we have made no commitment to maintain it, or maintain its responses in the form they are in now. At the moment we have no plans to make such a commitment
