### ISSUE TITLE
Hebrew characters not included in JSON response to observations/show

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#659]
To replicate, make a comment with a body of "בדיקה" and check the JSON response.

http://www.inaturalist.org/observations/1847929#comment-334221
https://www.inaturalist.org/observations/1847929.json
https://groups.google.com/d/topic/inaturalist/oVR0culw5ss/discussion

**Comment by pleary** [comment]
I fixed this in 7d11168 and it's been released to production. The above JSON representation seems to be working properly. I'll alert the Google group
