### ISSUE TITLE
Project required field indicator

### ISSUE THREAD

**Issue by kgarsuta** [inaturalist/inaturalist#66]
If a project specifies some fields (e.g. georeference) as required, there is no indicator that the field is required. Could you come up with a way to indicate this so that observations are not simply rejected from the project?

This could be a very good way to lose project contributions without the user noticing.

Custom fields do a good job by marking required fields with *'s. Thanks!

**Comment by kueda** [comment]
Required fields are indicated on obs/new and in the popup that appears on obs/show when adding to a project. obs/upload shows project obs field errors after upload.
