### ISSUE TITLE
Making Observation Detail Map Consistent

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#660]
Currently, the map markers in the observation detail screen use a teardrop to indicate the observation location and circles to indicate other observations of the same kind. This is inconsistent with map specs found here https://github.com/inaturalist/inaturalist/issues/599 where we are using circles to indicate observations with obscured locations. 

The proposal for the observation detail map is to use a big teardrop to indicate the observation and regular-sized teardrop markers for other observations with an open location. Circles would be used for observations with obscured locations as indicated in https://github.com/inaturalist/inaturalist/issues/599. 

This is pending completion of this issue:
https://github.com/inaturalist/inaturalist/issues/599

**Comment by pleary** [comment]
Do you have an example of this Joelle? When you say "teardrop to indicate the observation location and circles to indicate other observations of the same kind", I'm not clear what circles you're referring to.

Take http://www.inaturalist.org/observations/1798890 for example. When I first load the page I see:
<img width="317" alt="screen shot 2015-08-18 at 12 22 45 pm" src="https://cloud.githubusercontent.com/assets/48566/9335773/00b2cd9a-45a4-11e5-8498-8950337c4155.png">
These many slightly transparent circles are always used at higher zoom levels, and as far as I know we have no plans to change that.

If I zoom in further on some of them I see:
<img width="320" alt="screen shot 2015-08-18 at 12 23 14 pm" src="https://cloud.githubusercontent.com/assets/48566/9335797/28ffd7d4-45a4-11e5-8c87-a4117453f76c.png">
Which are the circles we are currently using to represent observations at a closer zoom-level. #559 is the ticket where we are discussing changing those markers, and Staging is already running the recommended changes.

The only other circles are around the main observation:
<img width="319" alt="screen shot 2015-08-18 at 12 23 33 pm" src="https://cloud.githubusercontent.com/assets/48566/9335824/5231e71e-45a4-11e5-8a19-86d3dea0cf00.png">

The observation is obscured hence the circle with a dot in it, and the other circle represents the boundary of uncertainty, both of which we have no plans to change.

So, I'm not sure what is being requested outside of what ticket #599 is describing

**Comment by joellebel** [comment]
Closing this issue because it looks like ob detail maps will get updated automatically when we launch the new maps.
