### ISSUE TITLE
Marking my own identification as not in need of ID causes me to fave it.

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/inaturalist#664]
-I had a nonstandard observation of a 'vernal pool' http://www.inaturalist.org/observations/89436

-Because it has no ID, it did not get marked as reviewed so I see it in needs ID.  This is a good thing.

-However, since there is no possible ID I mark it as 'does not need ID'

-This results in it  becoming a 'fave' and showing up as a fave in my faves list. However the star itself does not show as a fave. http://www.inaturalist.org/faves/charlie

-I unfave and then refave it to see if that removes it. Instead it faves it on the observation page too. It now shows up twice on my faves page.

**Comment by kueda** [comment]
I can see that your data is in the state you describe, but I'm having trouble replicating the issue. Is this consistent for all observations? Just you're own observations?

**Comment by naturalistcharlie** [comment]
here's how to make it happen:

make an observation with no ID, like this one:
http://www.inaturalist.org/observations/1862161

then tag your own id-less observation as not in need of ID.

It then is added to faves. It happened with that test one as well.

On Fri, Aug 14, 2015 at 6:35 PM, Ken-ichi <notifications@github.com> wrote:

> I can see that your data is in the state you describe, but I'm having
> trouble replicating the issue. Is this consistent for all observations?
> Just you're own observations?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/664#issuecomment-131259663>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by kueda** [comment]
Tried and it didn't work. http://www.inaturalist.org/observations/1862161 does not have any faves as far as I can tell. Are you seeing faves there? If so, screenshot?

**Comment by naturalistcharlie** [comment]
![inatfave](https://cloud.githubusercontent.com/assets/7171475/9285777/9abcf00e-42b7-11e5-8106-b05d43ff3bc7.jpg)
here you can see two of the vernal pools and one of the test observation in my faves

**Comment by kueda** [comment]
Is it showing up on your favorites page but not appearing as "faved" on the observation page? That's what I'm seeing, and is definitely fixable.

**Comment by naturalistcharlie** [comment]
This one: http://www.inaturalist.org/observations/89436 shows as a fave and when i unfave it and reload, the fave comes back.

Also of note: when I marked my observations as not identifable, I got a notification that it had been faved.  
![image](https://cloud.githubusercontent.com/assets/7171475/9285833/0eda092c-42b8-11e5-8b29-64205991481e.png)

(i didn't fave it, but I still got that)

**Comment by kueda** [comment]
As far as I can tell this was fixed in 487bc0c0798484021fb3f73cdd1ab8e023f407cc. Let me know if you're still seeing it.
