### ISSUE TITLE
obs field chooser for taxon not loading on obs/edit

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#670]
![screen shot 2015-08-21 at 10 26 02 am](https://cloud.githubusercontent.com/assets/22691/9414672/2792a1ea-47ef-11e5-9674-e34c7a398b16.png)

Seems like it's just not loading the taxon.

**Comment by pleary** [comment]
I think this is fixed in 2694867 . I turned them into taxa autocompletes and fixed up various things. It should now show the taxon name and thumbnails on the edit screen, also obs/new and the "add more fields" form on obs/show. This is on Staging now if you want to take a look

**Comment by kueda** [comment]
Looks good to me. Thanks.
