### ISSUE TITLE
Joining a project takes you to wrong project page sometimes

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#671]
Twice this week when I joined a project, it took me to the wrong page after I clicked "Yes, I want to join this project."

Here's how it happens:
Open two different projects in two different tabs.
e.g. 
http://www.inaturalist.org/projects/biodiversity-of-texas-a-citizen-science-project
and
http://www.inaturalist.org/projects/red-de-monitores-comunitarios-mayan-jays

THEN go back to the FIRST one you opened. Click join. See that after joining it takes you instead to the project that you opened most recently. 

This is a bit of an obscure case I admit, but could be confusing for people exploring several projects in different tabs. Might be somehow related/fixable along with #629.

**Comment by kueda** [comment]
It's based on your session, so if you open multiple tabs in the same session it redirects you back to the last page you requested. I can change that, I don't think it's a huge deal.
