### ISSUE TITLE
broken images in daily updates email

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#672]
![screen shot 2015-08-22 at 8 47 02 pm](https://cloud.githubusercontent.com/assets/22691/9426845/58ff27a0-490f-11e5-8165-52754ee2a8ca.png)
![screen shot 2015-08-22 at 8 46 44 pm](https://cloud.githubusercontent.com/assets/22691/9426846/5c7a87f8-490f-11e5-8ffa-a680603dfdb3.png)

**Comment by carrieseltzer** [comment]
Icons are also broken on the project view of "all observations", e.g. here (http://www.inaturalist.org/observations/project/national-geographic-great-nature-project). Screen shot attached. 

![screen shot 2015-08-24 at 2 57 20 pm](https://cloud.githubusercontent.com/assets/7501183/9449410/73e7db68-4a70-11e5-9261-edae104d6570.png)

Icon looks fine on the "edit project" page. Screenshot of my view:
![screen shot 2015-08-24 at 2 59 28 pm](https://cloud.githubusercontent.com/assets/7501183/9449445/9eec3d40-4a70-11e5-8c19-c172f1c9b4be.png)

**Comment by pleary** [comment]
I am hopeful 0c42a8ef30b will fix the broken images in update emails. It also looks like the Great Nature icon is working now on the "all observations" view. I'll close this for now, and if we see broken images again we can reopen it
