### ISSUE TITLE
Species chooser autocomplete matches disappear on first letter of second word

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#676]
For example, when typing 'Tobacco Brush', matches are available on 'Tobacco ', dissappear on 'Tobacco b' and reappear on 'Tobacco br'

other examples (where the middle step consistently gives no matches):
Acer negundo: 'Acer ' -> 'Acer n' -> 'Acer ne'
Scarlet gilia: 'Scarlet ' -> 'Scarlet g' -> 'Scarlet gi'

**Comment by pleary** [comment]
Fixed in 02bd273 . I manually updated the ES index in production (this code change would only apply if we completely wiped and rebuilt the index, which would result in only partial taxon search results for about an hour), and am in the progress of reindexing all taxa
