### ISSUE TITLE
enable versioning for s3?

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#680]
Photos are one of the few things we don't back up, so when they get deleted by users accidentally (or worse, by us accidentally due to a bug), there's just no way to recover them. I *think* we could change this by enabling versioning on S3, which would mean DELETE requests would not actually delete them from S3 (though I'm not sure what effect they *would* have, then). The downside is we apparently can't turn versioning off after we turn it on. I'm not sure if there's any impact on pricing aside from the fact that we never stop paying to host those archived versions. @pleary, can you think of any other reasons not to turn it on?

**Comment by md5** [comment]
You can delete object versions and even define a lifecycle for them, you just can't delete them with the `DELETE` command. The effect of the `DELETE` command becomes to hide the object from the list of objects in the bucket.

See here: http://docs.aws.amazon.com/AmazonS3/latest/dev/DeletingObjectVersions.html

**Comment by md5** [comment]
This too: http://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html

**Comment by kueda** [comment]
We ultimately decided to ditch this in favor of #690, largely b/c there are a bunch of versions we don't want to keep in s3, like the original file upload and any changes to the resized pics (sm, med, large, etc), and managing that would involve a lot of version management.
