### ISSUE TITLE
stop deleting photos from s3

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#690]
In lieu of using s3 versioning (#680), we decided to just stop deleting photos from s3. This means we can resurrect deleted photos if we need to without doing weird things like deleting original versions from s3, or deleting all versions of resized images.

- [x] override paperclip's s3 deletion
- [x] write a script or rake task that looks for photos in s3 that are not in the database and deletes them from s3. Run this script every 6 months

**Comment by pleary** [comment]
I think this is all done in ef18fdeea (not deployed). I needed to create a deleted_photos table so we know the unique IDs of the photos we need to remove from S3. There is a rake task to remove from s3 photos deleted over 6 months ago, but nothing in place right now to run it.

**Comment by kueda** [comment]
Looks good to me. Only remaining thing would be to use this stuff in the resurrection scripts, but I guess we can cross that bridge when we get to it.
