### ISSUE TITLE
show correct coordinate uncertainty on obs/show

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#696]
Even though we've switched to calculating private coordinates based on random position within a coordinate range, we're still displaying coordinate uncertainty on obs/show as a circle based on a random pt within a 10 km radius. I also think we're not setting `public_positional_accuracy` correct.

So... this is a bit open-ended. To be entirely accurate, we should probably stop showing a circle on obs/show and show a rectangle for the coordinate area within which the coordinates lie. I suppose you could also show a circle whose radius is that of the circle the circumscribes the rectangle, but that seems less accurate. Thoughts?

https://www.inaturalist.org/observations/1940203 was what set me off on this.

**Comment by carrieseltzer** [comment]
It seems like showing a rectangle around obscured points would be much truer. The change in how points are obscured is apparent in the areas where iNat has serious moth-ers in Maryland and Pennsylvania (http://www.inaturalist.org/observations/map?taxon_id=47157#9/39.732/-76.8).

Have you also changed how we describe location information to GBIF or other partners? For example, threatened taxa say "INFORMATION WITHHELD: Coordinate uncertainty increased by 10000m to protect threatened taxon" (e.g. http://www.gbif.org/occurrence/1052605437).
