### ISSUE TITLE
Deleting photo from one 'copied' observation deletes it from all

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/inaturalist#699]
I created an observation with a photo, and then copied it to create another observation with the same photo. I then copied it again but deleted the photo from the new observation (I wanted to record presence of a species I didn't get a photo of in the same location). The photo was deleted from all three. 
It makes sense that one photo might be linked to more than one observation, rather than saving the same photo multiple times, but maybe a way to unlink the photo without deleting. I suppose this would be done by unchecking the photo in the observation rather than deleting it.  So maybe best is just a popup if there are duplicates: "warning: this will delete this photo from all linked observations"

**Comment by kueda** [comment]
I'm having trouble replicating this. Here's what I did 

1. made an obs with a photos
1. copied that obs for a new obs
1. copied the copy but unchecked the box next to the photo and saved

Obs 1 and 2 have the photo, obs 3 does not, but the original photo was not deleted. Am I doing something wrong? If you're doing something different, can you list the steps?

**Comment by naturalistcharlie** [comment]
That sounds the same as what I did. I don't know why it didn't repeat! Maybe it was a one time thing or I somehow clicked something wrong.

**Comment by kueda** [comment]
Well, if you can come up with a list of steps that consistently recreates the issue, please re-open this.
