### ISSUE TITLE
can't select text with keyboard in comments for safari

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#707]
From @carrieseltzer:

> Running OS X 10.10.4 and Safari Version 8.0.7 (10600.7.12)
> 2. Comments box doesn't show text selections/cursor movements well.
> I noticed in the last couple of days that I can't interact with text as easily in comment boxes, especially using my usual keyboard shortcuts, like using shift+arrows to select text for copying or deleting. I realized accidentally that the shift+arrows IS selecting text, but the cursor and highlight isn't showing it. For example, if I use that keyboard shortcut and then hit delete, it will remove text even though I couldn't see what was highlighted. Text selection with the mouse is also less predictable. No idea what is causing this, but I've never noticed it before.

I can confirm this is happening but only in Safari, not in Firefox or Chrome. I haven't noticed any mouse issues. @pleary, timing seems to match up with the release of mentions, though functionally it seems like it could be related to my keyboard shortcut stuff. If you can think of any mentions-related explanations please holler, otherwise I'll take a look.

**Comment by kueda** [comment]
I can confirm this is a bug with the text highlighting lib we're using. You can replicate it on their demo page: http://mistic100.github.io/jquery-highlighttextarea/

@pleary, I don't think highlighting really adds much, that library is not maintained, and now there's the Safari issue. Should we drop it?

**Comment by pleary** [comment]
We can definitely drop it. It's a weird implementation that I suspect will just keep causing issues
