### ISSUE TITLE
obscure coordinates for observations with IDs of *any* threatened taxon?

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#711]
http://www.inaturalist.org/people/artem brought up a point that if you're looking at an observation with coordinates that have been obscured b/c of a threatened taxon, you can easily see the true coordinates by adding an ID that bumps the community ID up to a non-threatened taxon.

One solution would be to obscure the coordinates of the observation if any taxa proposed in the IDs are threatened. Artem also suggested that we reveal the coordinates when the observation becomes research grade if the community taxon is not threatened.

Thoughts or other solutions? This would add significant complication to coordinate obscuring, but it would plug this fairly significant hole.

**Comment by naturalistcharlie** [comment]
Hmm... that's a good point. It makes sense, though that could also be
abused by trolls, if any. I have a variety of mixed feelings but it seems
reasonable.

On Mon, Sep 28, 2015 at 3:50 PM, Ken-ichi <notifications@github.com> wrote:

> http://www.inaturalist.org/people/artem brought up a point that if you're
> looking at an observation with coordinates that have been obscured b/c of a
> threatened taxon, you can easily see the true coordinates by adding an ID
> that bumps the community ID up to a non-threatened taxon.
>
> One solution would be to obscure the coordinates of the observation if any
> taxa proposed in the IDs are threatened. Artem also suggested that we
> reveal the coordinates when the observation becomes research grade if the
> community taxon is not threatened.
>
> Thoughts or other solutions? This would add significant complication to
> coordinate obscuring, but it would plug this fairly significant hole.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/711>.
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by kueda** [comment]
This is now running on gorilla if anyone wants to check it out. Will probably release by the end of the week.
