### ISSUE TITLE
ListedTaxon refresh not working

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#719]
Stub, but http://www.inaturalist.org/listed_taxa/3171069 lists Poison oak for Sierra County, CA, but clicking refresh does not update the stats even though http://www.inaturalist.org/observations/1941248 is a RG obs of that taxon in that place.

**Comment by loarie** [comment]
I have an existing issue for this here https://github.com/inaturalist/inaturalist/issues/463
