### ISSUE TITLE
Unambiguous taxon change type 'Taxon Merge' not automatically moving content

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#721]
I noticed that there are lots of lingering observations associated with taxa inactivated by taxon merges
http://www.inaturalist.org/taxon_changes?filters%5Bmerge%5D=1
Since these changes are unambiguous, content should be automatically migrated (as in taxon swap, and not as in taxon split). However, this doesn't seem to be happening.

On staging, I tested this by swapping Lithobates catstebianus with Rana catestbiana and merging Pseudacris regilla sierra and hypochondriaca into Pseudacris regilla. As expected, soon after committing both all the Lithobates catestabianus obs had migrated to Rana catesbiana, but none of the Pseudacris obs had.

**Comment by loarie** [comment]
while there aren't alot of true taxon merges, alot of people seem to be using taxon merges as taxon swaps (1-1) so this is creating a fair amount of orphaned obs associated with inactive taxa

**Comment by kueda** [comment]
So there's the bug, that unambiguous TaxonMerges aren't transitioning data associated with the input taxon correctly, and then there's a separate issue, that TaxonMerge validation is apparently allowing only one input taxon. I'd make a separate issue for the latter.

**Comment by loarie** [comment]
added that here https://github.com/inaturalist/inaturalist/issues/722

**Comment by kueda** [comment]
For the record taxon merges are working... for taxa that don't have a lot of associated content. For those that do (like the Pseudacris example cited above), they're very slow, and I suspect those jobs are just getting repeatedly shut down before completion. I've made some changes that will hopefully make them a bit faster, but they're still pretty slow. Most of the slowdown seems to be in all the observation and identification callbacks involved in re-IDing, stuff, and that's really only going to get worse with #1233 and #1235, and as we grow. Another approach might be to partition the work into multiple jobs when we know there are a lot of records, e.g. if there are 1000 identifications, break it up into jobs that only deal with 100 identifications

**Comment by kueda** [comment]
I tried to make some performance improvements to taxon changes in general as a part of working on #1233 and #1235, so hopefully this is sort of resolved. If there are new changes that don't seem to be committing records, please re-open.
