### ISSUE TITLE
Minor project UI edits on Observation/show

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#730]
These are three minor issues I noticed on Observation/show relating to how projects are communicated 
1. On Observation/show #project_observation_settings, change to: 'Joining the project implies that you agree to the project terms.'

<img width="286" alt="screen shot 2015-10-30 at 1 58 48 pm" src="https://cloud.githubusercontent.com/assets/598026/10857916/67ab9178-7f0e-11e5-8000-b32fa4103499.png">
2. On Observation (below map) change to: 
'You've been granted permissions to see these coordinates as a curator of one of the projects to which this observation has
been added'
<img width="327" alt="screen shot 2015-10-30 at 1 57 23 pm" src="https://cloud.githubusercontent.com/assets/598026/10857888/2eba15b0-7f0e-11e5-9580-33dcd7f30a5f.png">

**Comment by carrieseltzer** [comment]
No longer a relevant issue due to updates since this was opened.
