### ISSUE TITLE
HTML carriage return code (&#13;) showing in email updates

### ISSUE THREAD

**Issue by simonkingston** [inaturalist/inaturalist#731]
![image](https://cloud.githubusercontent.com/assets/6931738/10340478/75d3fcfc-6ccd-11e5-9780-8e9014c6bff8.png)

I'm seeing the HTML carriage return code (&#13;) in update emails.  See screen cap above.

**Comment by carrieseltzer** [comment]
I've been meaning to report this for months. Thank you, Simon!

On Wed, Oct 7, 2015 at 10:31 AM, Simon Kingston <notifications@github.com>
wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/6931738/10340478/75d3fcfc-6ccd-11e5-9780-8e9014c6bff8.png>
>
> I'm seeing the HTML carriage return code ( ) in update emails. See screen
> cap above.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/731>.
>



-- 
Carrie E. Seltzer, Ph.D.
National Geographic's Great Nature Project
www.greatnatureproject.org

**Comment by simonkingston** [comment]
No problem, Carrie.  Glad to contribute!

**Comment by pleary** [comment]
This should be fixed in 0c42a8ef30b .  These &#13; will become proper new paragraphs. Thanks for the report!
