### ISSUE TITLE
research grade taxon observation field query includes 1614596 but (unexpectedly) excludes 1571339

### ISSUE THREAD

**Issue by jhpoelen** [inaturalist/inaturalist#733]
When paging through all research grade observations with taxon observation fields using http://www.inaturalist.org/observation_field_values.json?type=taxon&quality_grade=research (omitted paging params), I found that http://www.inaturalist.org/observations/1614596 is included, but http://www.inaturalist.org/observations/1571339 is excluded.  Both are research grade, but from the json (see screenscapes attached) I see that 1571339 has "id_please: true" and 1614596 has "id_please: false". Is this expected behavior?

![screen shot 2015-10-08 at 10 05 05 am](https://cloud.githubusercontent.com/assets/1084872/10373779/59ca5858-6da4-11e5-87a7-18816ee46dc7.png)
![screen shot 2015-10-08 at 10 05 14 am](https://cloud.githubusercontent.com/assets/1084872/10373778/59c9b2ae-6da4-11e5-8d51-e3fa4e9e868c.png)

**Comment by pleary** [comment]
Hi Jorrit - I can see both of the observations with this query: `http://www.inaturalist.org/observation_field_values.json?type=taxon&quality_grade=research&field=Polinizando` . Could it be a sorting problem and the result just isn't appearing on the page you expected it to be on? Or did you fetch every single page of results and failed to find it?

**Comment by jhpoelen** [comment]
Hey Patrick:
Thanks for your prompt reply!

I re-ran the import (see url patterns below) and printed each of the observation ids (including those with non-interaction observation fields and . . . 1571339 is not present. 

However, after removing the ```license=any``` it does include the observation.

Same is observed for http://www.inaturalist.org/observation_field_values.json?type=taxon&quality_grade=research&field=Polinizando&license=any . 

I would expect that selecting _all_ licenses any observation would be included. Why are fewer observation selected when ```license=any```. Is no license the same as any license?

```
http://www.inaturalist.org/observation_field_values.json?type=taxon&page=1&per_page=100&license=any&quality_grade=research
http://www.inaturalist.org/observation_field_values.json?type=taxon&page=2&per_page=100&license=any&quality_grade=research
...
http://www.inaturalist.org/observation_field_values.json?type=taxon&page=63&per_page=100&license=any&quality_grade=research
http://www.inaturalist.org/observation_field_values.json?type=taxon&page=64&per_page=100&license=any&quality_grade=research
```

**Comment by jhpoelen** [comment]
Removing the ```license=any``` solved this issue for me. Thanks for your help!
