### ISSUE TITLE
Add html editor for help pages

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#735]
As a curator on the site, I would like to be able to contribute to pages in the help section without having to know html. See google group thread here: https://groups.google.com/forum/#!topic/inaturalist/GzNzBbjWe-M

Possibly related if it makes sense to implement an editor site-wide: When adding comments or writing journal posts, I'd also like to use an html editor for basics like hyperlinks, images, bold, italics, etc. instead of using html tags.

**Comment by kueda** [comment]
If we do this I think we should do this site-wide. https://www.froala.com/wysiwyg-editor looks decent, not sure how it would preserve our styles, though. Haven't found a decent jquery plugin that just inserts HTML tags.

**Comment by carrieseltzer** [comment]
Help pages (aka wiki pages) need a lot more help than this (e.g. to be translatable, more easily organized, etc), so I'm closing this issue.
