### ISSUE TITLE
Project stats inconsistent across Site_id

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#736]
For example, observation totals here http://conabio.inaturalist.org/projects/moluscos-de-mexico are different from here http://www.inaturalist.org/projects/moluscos-de-mexico (currently 600 v 610)

**Comment by pleary** [comment]
I just want to confirm that the desired behavior is that none of the default site-specific filters are applied to queries about projects. Is that correct?

**Comment by loarie** [comment]
correct
