### ISSUE TITLE
some link out from observations to GloBI missing?

### ISSUE THREAD

**Issue by jhpoelen** [inaturalist/inaturalist#737]
Some inaturalist observations that are available through GloBI have a link from iNaturalist to GloBI (e.g. http://www.inaturalist.org/observations/563486), however, some don't (e.g. http://www.inaturalist.org/observations/2020957 , http://www.inaturalist.org/observations/374275). Why is that? It is due to a indexing delay on iNaturalist side? Or is the GloBI API not working as expected?

Please let me know if there's anything I can do to help resolve this. . . .

Related to issue https://github.com/jhpoelen/eol-globi-data/issues/115 .

**Comment by kueda** [comment]
Ugh, I'm not even sure that script is scheduled to run properly. I'll get it going again. Remind me how frequently you guys index us?

**Comment by jhpoelen** [comment]
about once or twice a week currently.

**Comment by kueda** [comment]
K, i'm going to set our script to run weekly. Will make sure it runs this afternoon.

**Comment by jhpoelen** [comment]
nice! will check later today. Cu Sat at Manylabs / n4n

**Comment by jhpoelen** [comment]
Just checked and looks great! Thanks for making this happen.
