### ISSUE TITLE
Issue installing inaturalist on Debian Wheezy

### ISSUE THREAD

**Issue by francesco1119** [inaturalist/inaturalist#740]
I'm stock at this point:

bobby@localhost:~/Desktop/inaturalist-master$ bundle exec gem uninstall rgeo
Could not find aasm-4.0.8 in any of the sources
Run `bundle install` to install missing gems.
bobby@localhost:~/Desktop/inaturalist-master$ bundle install
Fetching gem metadata from http://rubygems.org/........
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Fetching git://github.com/kueda/activerecord-postgis-adapter.git
There was a RuntimeError while loading activerecord-postgis-adapter.gemspec: 
can't modify frozen String from
/var/lib/gems/1.9.1/bundler/gems/activerecord-postgis-adapter-4d7c4c91720e/activerecord-postgis-adapter.gemspec:7:in
`block in <main>

Any tips?

**Comment by pleary** [comment]
I see `/var/lib/gems/1.9.1` - does that mean you're using Ruby 1.9? We are now using Ruby 2.2 (I updated the setup guide at https://github.com/inaturalist/inaturalist/wiki/Development-Setup-Guide to reflect that). Please try again with Ruby 2.2 to see if that works.

We run the site either in Ubuntu 14.04, or OSX for development, so it is possible there are unknown issues in Debian. If you continue to have problems I'll take a closer look.

**Comment by pleary** [comment]
I hope it worked out for you!
