### ISSUE TITLE
locations with obscured coordinates should have a generalized place guess equivalent

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/inaturalist#742]
Right now, locations with obscured coordinates don't show a place guess on the observation list view of the website, instead they show "(Somewhere)" as if there were no geocoordinates at all.

obs list view:
<img width="663" alt="screen shot 2015-10-16 at 11 58 29 am" src="https://cloud.githubusercontent.com/assets/515947/10550720/53353864-73fd-11e5-9fde-d6ce9c9003c1.png">

obs detail view:
<img width="706" alt="screen shot 2015-10-16 at 11 58 09 am" src="https://cloud.githubusercontent.com/assets/515947/10550725/58813dd6-73fd-11e5-8f4d-c427966e9b10.png">

It would be great if the website instead calculated the smallest enclosing administrative area and showed that as the place guess. Something like "Malaysia (coordinates obscured)"

**Comment by carrieseltzer** [comment]
I like the idea of using the smallest place name enclosing the box for obscured coordinates. Related to #635 which also addresses how private coordinates appear in table view.

**Comment by kueda** [comment]
FYI, all the place guesses should be set, I just need to make sure the node API recognizes that. Uh, it might also be necessary to re-index all the obs. Ugh.

**Comment by kueda** [comment]
K, I think this is finally resolved, e.g. http://www.inaturalist.org/observations/soonchye?taxon_name=Tanaecia
