### ISSUE TITLE
Remove HTML from display of project names in members, observations, and stats

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#743]
Can this be fixed so the html doesn't get stuck in there before the apostrophe? I couldn't find another example of a project with an apostrophe that had this issue. Let me know if there's a workaround (other than changing the name!).

See these links and screen shots:
http://www.inaturalist.org/projects/national-geographic-great-nature-project/members
http://www.inaturalist.org/projects/national-geographic-great-nature-project/contributors/carrieseltzer
http://www.inaturalist.org/projects/national-geographic-great-nature-project/stats

![screen shot 2015-10-16 at 3 25 46 pm](https://cloud.githubusercontent.com/assets/7501183/10551489/34b8f8d0-741b-11e5-9582-7d8898d71725.png)
![screen shot 2015-10-16 at 3 29 32 pm](https://cloud.githubusercontent.com/assets/7501183/10551491/34bae726-741b-11e5-8c35-f020844e2635.png)
![screen shot 2015-10-16 at 3 29 44 pm](https://cloud.githubusercontent.com/assets/7501183/10551490/34b97008-741b-11e5-905c-a3af9d5cbb9d.png)

**Comment by carrieseltzer** [comment]
Thanks! That was fast!

On Fri, Oct 16, 2015 at 4:18 PM, Patrick Leary <notifications@github.com>
wrote:

> Closed #743 <https://github.com/inaturalist/inaturalist/issues/743> via
> 64cf1b2
> <https://github.com/inaturalist/inaturalist/commit/64cf1b2effb45f0991c68c761694f2c2df18d5ac>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/743#event-437928095>.
>



-- 
Carrie E. Seltzer, Ph.D.
National Geographic's Great Nature Project
www.greatnatureproject.org

**Comment by carrieseltzer** [comment]
Sorry, when will it take effect?

On Fri, Oct 16, 2015 at 4:20 PM, Carrie Seltzer <carrieseltzer@gmail.com>
wrote:

> Thanks! That was fast!
>
> On Fri, Oct 16, 2015 at 4:18 PM, Patrick Leary <notifications@github.com>
> wrote:
>
>> Closed #743 <https://github.com/inaturalist/inaturalist/issues/743> via
>> 64cf1b2
>> <https://github.com/inaturalist/inaturalist/commit/64cf1b2effb45f0991c68c761694f2c2df18d5ac>
>> .
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/inaturalist/inaturalist/issues/743#event-437928095>.
>>
>
>
>
> --
> Carrie E. Seltzer, Ph.D.
> National Geographic's Great Nature Project
> www.greatnatureproject.org
>



-- 
Carrie E. Seltzer, Ph.D.
National Geographic's Great Nature Project
www.greatnatureproject.org

**Comment by pleary** [comment]
It's live now. Sorry, github has these fancy routines that can close tickets when we commit code, but that doesn't mean the code has been deployed. Maybe I should stop using them and close tickets only when the results are live. Thanks for the bug report!

**Comment by carrieseltzer** [comment]
Still happening here: http://www.inaturalist.org/projects/national-geographic-great-nature-project/contributors/carrieseltzer

![screen shot 2015-11-05 at 11 08 25 am](https://cloud.githubusercontent.com/assets/7501183/10973932/a9e15ce6-83ad-11e5-9010-e7b1731e9a97.png)

**Comment by pleary** [comment]
Ah, the broken case was when looking at your own contributions to a project. All fixed - should be working now
