### ISSUE TITLE
Project observations by a specific user still says "observations by everyone"

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#746]
For example, go here: http://www.inaturalist.org/projects/afribats
Click on jakob.
http://www.inaturalist.org/observations?projects%5B%5D=afribats&user_id=jakob
See that it says "Observations by Everyone" but that only observations from jakob are displayed.

![screen shot 2015-10-19 at 2 55 03 pm](https://cloud.githubusercontent.com/assets/7501183/10587923/8e46cd16-7671-11e5-9359-91af14ddc14a.png)

**Comment by naturalistcharlie** [comment]
I see I'm not the only one who usually has at least half a dozen
inaturalist tabs open at once

On Mon, Oct 19, 2015 at 2:57 PM, carrieseltzer <notifications@github.com>
wrote:

> For example, go here: http://www.inaturalist.org/projects/afribats
> Click on jakob.
>
> http://www.inaturalist.org/observations?projects%5B%5D=afribats&user_id=jakob
> See that it says "Observations by Everyone" but that only observations
> from jakob are displayed.
>
> [image: screen shot 2015-10-19 at 2 55 03 pm]
> <https://cloud.githubusercontent.com/assets/7501183/10587923/8e46cd16-7671-11e5-9359-91af14ddc14a.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/746>.
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by simonkingston** [comment]
I saw that as the name of the screen - "Observations by Everyone" and that the name of the screen wouldn't change depending on the search parameters you entered.  An alternative name for this screen would just be "Observations", and perhaps that would clear things up, as you wouldn't have a search term in the title.

I see this as opposed to the "[Username] Observations" screen I would get to by going to someone's profile and clicking the link to their observations there (e.g., http://www.inaturalist.org/observations/jakob), which has a different presentation and URL pattern from the "Observations by Everyone" screen.

![jakobsobservations](https://cloud.githubusercontent.com/assets/6931738/10650647/d1be6260-7807-11e5-88c6-e8c7fd0ebca9.png)

I suppose the real question is whether or not there should be two different presentations of observations, or if the link to the profile observations should just execute the search on "Observations by Everyone" with the user_id parameter filled in.  One thing you do get by hitting observations from a profile is the profile links across the top of the screen to other profile artifacts.

![profileartifacts](https://cloud.githubusercontent.com/assets/6931738/10650789/9c37cea0-7808-11e5-8d04-8373e9e4c6c7.png)

**Comment by pleary** [comment]
A lot has changed that affects this ticket. The initial concern is resolved since we released a new search and it doesn't use the text "Observations by Everyone". There is still http://www.inaturalist.org/observations/project/afribats?user_id=jakob but that header text is pretty reasonable. It seems like this could be closed, and if there are specific concerns with the new search they could be filed in separate tickets.

**Comment by carrieseltzer** [comment]
Yep, I agree this can be closed. Thanks @pleary!
