### ISSUE TITLE
Searching within a users's observations returns 0 results

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#747]
This is more problematic than #746. Starting from a user's observations from a project, searching within that user's observations returns 0 results. It appears the query string is not being composed properly (but I'm not sure what's broken).

Start here:
http://www.inaturalist.org/observations?projects%5B%5D=afribats&user_id=jakob

Open search field and search for a taxon (e.g. eidolon helvum) or month (e.g. june). See zero results returned.
Example url that returns 0 results:
http://www.inaturalist.org/observations?utf8=✓&q=&search_on=&quality_grade=any&reviewed=&identifications=any&captive=&place_id=&swlat=&swlng=&nelat=&nelng=&taxon_name=Straw-colored+fruit+bat&taxon_id=40827&day=&month=&year=&order_by=observations.id&order=desc&rank=&hrank=&lrank=&projects%5B%5D=&taxon_ids%5B%5D=&d1=&d2=&created_on=&site=&tdate=&list_id=&filters_open=true&view=table

![screen shot 2015-10-19 at 2 59 14 pm](https://cloud.githubusercontent.com/assets/7501183/10588184/ccd8d23a-7672-11e5-8870-6626bc41c8a3.png)
![screen shot 2015-10-19 at 2 59 22 pm](https://cloud.githubusercontent.com/assets/7501183/10588185/ccdd7222-7672-11e5-8058-e9527b18acab.png)

**Comment by tnywlls** [comment]
The afribats project includes no observations as far as I can see.  Clicking on a project member, from within the project, shows their current contributions to the project, zero for all members currently.
A user should see a link for adding suitable observations from their collection of observations, something like
http://www.inaturalist.org/observations/jakob?not_in_project=afribats
You can manually construct such a URL for some other person by substituting a user login name for 'jakob' in the middle there.

If you then refine that search you do run into a definite bug, in that the search does not pass on the "not_in_project=" specifications, but again you can manually construct a search
www.inaturalist.org/observations/jakob?taxon_name=Straw-colored+fruit+bat&taxon_id=40827&not_in_project=afribats

Is that useful? Or am I missing something :-)
--Tony.

**Comment by carrieseltzer** [comment]
Hi Tony,

It's odd that AfriBats showed no observations at all for you which would be a totally separate problem since it has >1600.

The original problem I outlined still stands as a bug. In this case, I wasn't interested in finding observations to add to the project but rather searching within a user's existing project observations for a particular species/place/time. I suppose it's not a very common search path or use case, but it's definitely still a bug. 

The same search can be accomplished successfully independent of a project, but it should work within it too. E.g. this search on jakob's observations of Eidolon helvum works. http://www.inaturalist.org/observations/jakob?utf8=✓&q=&search_on=&quality_grade=any&reviewed=&identifications=any&captive=&place_id=&swlat=&swlng=&nelat=&nelng=&taxon_name=Straw-colored+fruit+bat&taxon_id=40827&day=&month=&year=&order_by=observations.id&order=desc&rank=&hrank=&lrank=&taxon_ids%5B%5D=&d1=&d2=&created_on=&site=&tdate=&list_id=&filters_open=true&view=table

**Comment by carrieseltzer** [comment]
Other interface changes have fixed this.
