### ISSUE TITLE
get taxon autocomplete working in bootstrap

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#748]
Right now when you try to load it you get the error `Uncaught TypeError: Cannot set property '_move' of undefined`, and visually it looks something like this:

<img width="217" alt="screen shot 2015-10-19 at 2 35 40 pm" src="https://cloud.githubusercontent.com/assets/22691/10592116/de97f68a-766e-11e5-8dac-fd8769a10bb6.png">

**Comment by pleary** [comment]
From a local test, 6ad4325 seems to address all the problems I saw. Could you check it out and let me know you see other problems?

**Comment by pleary** [comment]
I think this is working now. If not, feel free to reopen with requirements
