### ISSUE TITLE
Observations API additions

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#749]
We'll need support for some additional API filters to complete New Observation Search #744. This is what I've come up with so far, may need to update later or add new issues.

- [x] verifiable: this basically means the same as `Observation#research_grade_candidate?`
- [x] threatened
- [x] introduced
- [x] ~~popular: I think this means "has > 0 faves," but we could also be something like "has faves or comments" or "has more than 5 faves or comments." @joellebel and @loarie, did you have something more specific in mind for this?~~
- [x] filter by multiple months: right now we can filter by a single month, but we'd like to be able to do something like /observations?month=7|8|9 or something.

For later...

- [ ] first report: pending another issue to be created by @loarie

**Comment by loarie** [comment]
For popular, I was also thinking "has > 0 faves" at least to start.

**Comment by loarie** [comment]
For first report. My only concern with the with using listed taxa is that since we don't create listed taxa until an obs is RG, and in many cases listings won't exist for these obs, finding First Reports based solely on comparisons with listings will require that only RG obs are considered. I'd prefer that first reports are independent of quality, if there's a way to implement that.

**Comment by pleary** [comment]
I'd rather see "Popular" as a sort option, or call it what is is, like "With Faves"

**Comment by pleary** [comment]
Everything except first reports is on staging now: http://staging.inaturalist.org/observations?threatened=true&months[]=8&months[]=9&popular=true . Not everything has threatened/introduced/native/endemic, and nothing yet has verifiable. The tileserver has also been updated on staging and should match the search results

**Comment by kueda** [comment]
I don't think first reports is making this cut. If that's still desirable, maybe make another issue.
