### ISSUE TITLE
Identotron map tiles missing parts of ranges

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#750]
I've noticed more problems recently with some map tiles missing parts of ranges. I'm not sure of the extent of this problem but it's definitely happen with maps in Identotron. Screen capture below from: http://www.inaturalist.org/observations/identotron?observation_id=2196842#establishment_means=&order=&place=59221&taxon=40268

![screen shot 2015-10-20 at 10 23 52 am](https://cloud.githubusercontent.com/assets/7501183/10610225/e52a1324-7714-11e5-8420-2a9466d902c9.png)

**Comment by pleary** [comment]
There was a failed process on one of the maps servers. I restarted it and this should be working now. I also added a Sensu check that will do this automatically for us inaturalist/chef-repo@4153ed2 (this is a private repository, but pretty boring so you're not missing much). Hopefully that will help with stability of the map polygon tiles.

**Comment by carrieseltzer** [comment]
Thanks Patrick! You've been super fast at closing the tickets I open
recently :-)

On Tue, Oct 20, 2015 at 11:35 AM, Patrick Leary <notifications@github.com>
wrote:

> There was a failed process on one of the maps servers. I restarted it and
> this should be working now. I also added a Sensu check that will do this
> automatically for us inaturalist/chef-repo@4153ed2
> <https://github.com/inaturalist/chef-repo/commit/4153ed2> (this is a
> private repository, but pretty boring so you're not missing much).
> Hopefully that will help with stability of the map polygon tiles.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/750#issuecomment-149605930>
> .
>



-- 
Carrie E. Seltzer, Ph.D.
National Geographic's Great Nature Project
www.greatnatureproject.org
