### ISSUE TITLE
Use unique_hash to prevent duplicate ProjectUser counts

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#755]
This morning we had about 14,000 duplicate of each of (28k total):
```
ProjectUser.delay(:priority => INTEGRITY_PRIORITY).update_observations_counter_cache_from_project_and_user(po.project_id, obs.user_id)
ProjectUser.delay(:priority => INTEGRITY_PRIORITY).update_taxa_counter_cache_from_project_and_user(po.project_id, obs.user_id)
```

Not sure exactly where it originated, but this was the project http://www.inaturalist.org/projects/whio-forever. This is a good place for the unique_hash to prevent duplication

**Comment by naturalistcharlie** [comment]
I was getting the heavy traffic error this morning, perhaps this is why

On Thu, Oct 22, 2015 at 10:35 AM, Patrick Leary <notifications@github.com>
wrote:

> This morning we had about 14,000 duplicate of each of (28k total):
>
> ProjectUser.delay(:priority => INTEGRITY_PRIORITY).update_observations_counter_cache_from_project_and_user(po.project_id, obs.user_id)
> ProjectUser.delay(:priority => INTEGRITY_PRIORITY).update_taxa_counter_cache_from_project_and_user(po.project_id, obs.user_id)
>
> Not sure exactly where it originated, but this was the project
> http://www.inaturalist.org/projects/whio-forever. This is a good place
> for the unique_hash to prevent duplication
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/755>.
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
