### ISSUE TITLE
curators should be able to enter new conservation status authorities

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#767]
On taxa/edit, they can enter new conservation statuses, but they can only select from pre-existing conservation status authorities. The chooser should either allow a free text entry, or the user should be able to replace it with a text input.

**Comment by carrieseltzer** [comment]
This is still an issue for curators (staff don't have this problem). While fixing this, fixing #1509 would make sense too to allow the curator to be listed as the authority (which is what text incorrectly suggests now). 

This has come up in the forum: https://forum.inaturalist.org/t/comprehensiveness-of-conservation-statuses-on-inaturalist/6604/17

Thinking I'd need to make a new issue, I made this screen shot. 
![Screen Shot 2019-11-24 at 11 29 33 PM](https://user-images.githubusercontent.com/7501183/69512800-6e724800-0f13-11ea-98d1-5791cc5f341a.png)
