### ISSUE TITLE
observation is already added to the project error

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/inaturalist#769]
When a user is creating a new observation, if she manually adds it to a project that it will get automatically added to upon upload (i.e. something with a geo boundary auto-add or something), then the app gets an error back that the project was already added to the project.

The sequence is:

1. User creates local observation in the iOS app with criteria that automatically add it to a project,
2. User creates local project observation in the iOS app with the same project as in step 1,
3. User triggers upload,
4, The uploader uploads the observation,
5. iNat server automatically adds the observation to the project,
6. The uploader tries to upload the project observation, but the server reports a failure because the observation already belongs to the project.

**Comment by kueda** [comment]
Fixed in 366696c8dbf61d225bda4b4da86a535aec02970c
