### ISSUE TITLE
Golan API requests

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#774]
From our partners working on an Israeli app:

- [x] include `user.name` in `GET /observations/:id.json`
- [x] ensure Hebrew lexicon maps to iw locale so http://www.inaturalist.org/taxa/42048-Canis-lupus.json?locale=iw` and `/observations.json?taxon_id=42048&locale=iw`
- [x] document `PUT /users/:id.json`
- [x] add `GET /project/:id/members.json` to the API

**Comment by carmelneta** [comment]
GET /project/:id/members.json
not working, the right url is:
GET /projects/:id/members.json
