### ISSUE TITLE
Add categories to email headers

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#777]
...in order to figure out why we're getting these huge spikes
described here:
https://sendgrid.com/docs/API_Reference/SMTP_API/categories.html
{
  "category": "Example Category"
}

maybe try:
Welcome
Updates
Messages
Invites

Anything else I'm missing?

**Comment by kueda** [comment]
I think this was handled by f048ca42a4303b8a0629ac826d094c154afa55ad
