### ISSUE TITLE
multiple currents ids for a user/observation

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#781]
There should only be one. not sure how this happened, any ideas?
http://www.inaturalist.org/observations/2361994
<img width="710" alt="screen shot 2015-11-09 at 12 50 43 pm" src="https://cloud.githubusercontent.com/assets/598026/11046156/8e8ee392-86e0-11e5-87dc-0f213b92668d.png">

**Comment by loarie** [comment]
not sure if this is still happening or not - that particular example seems to have cleared itself up

**Comment by kueda** [comment]
It's still happening, but maddeningly impossible to replicate. E.g. http://www.inaturalist.org/observations/2623326 was initially ID'd by the observer as Pulmonata, then ID'd by invertzoo as Hesperarion, then the observer clicked "Agree?" next to that ID, which added an ID of Hesperarion but left the observer's initial ID of Pulmonata as current. Anecdotally I feel like we eliminated this bug months ago, but it's come back recently, but again, just anecdotal.

**Comment by kueda** [comment]
Probably the same as #1042, which was fixed.
