### ISSUE TITLE
Need to Make decision on how to search for Obs for Centennial BioBlitz

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#792]
The Centennial BioBlitzes will be organized as a collection of BioBlitz projects each with place_id, d1, and d2 filters.

We need to decide on how we should we count stats for these projects. There are two options:

Option 1: Use stats from place, d1, & d2 params, e.g. http://www.inaturalist.org/observations?d1=2015-05-15T13%3A00%3A00-06%3A00&d2=2015-05-16T17%3A00%3A00-06%3A00&place_id=7222

Pros: 
1. stats more instantaneous
2. no aggregator load/performance issues

Option 2: Set up these projects so that (1) the aggregator is turned on and (2) Preferred submission model is Project Curators. Then use stats from project_id param, e.g.
http://www.inaturalist.org/observations?projects=4161

Pros: 
1. Observations display links to the project (making the project easier to find from the obs)
2. Can use existing Explore tab on mobile apps to filter (Explore tab search allows projects but not d1/d2 searches)

@pleary - are there any other pros/cons not included here? e.g. does filtering on place_id,d1,d2 create more of a load than filtering on project_id? what will the aggregator load/delay be like?

While not the case in the Hawaii example used here, stats from Option 1 and Option 2 CAN differ slightly depending on users' account project settings

If we go with Option 1, then we'll need:
a) a new way to display project observations/stats to mobile users rather than the existing explore tab - @alexshepard - this is related to the situation (need to make issue) 
b) find a way to link make it easier for BioBlitz participants to find their BioBlitz

If we go with Option 2, then we'll need:
b) a way to have Projects include StartTime EndTime params (like Type: BioBlitz) but display stats based on Project Observations rather than realtime stats (like Type: Normal)
c) make sure the aggregator can handle this for the Centennial

**Comment by carrieseltzer** [comment]
It seems like option 2 might be a structure that could incorporate bioblitzes as subprojects of place-based projects. This is touching on #441 (subproject support) and is a bit tangential, but this seems like a good time to think about it. 

Similarly, it also seems like assigning bioblitzes project ids would make it easier to aggregate bioblitz stats for the NPS centennial events. I'm sure there will be a separate issue for that, but I could see it working as listing a series of bioblitz project ids. 

Finally, I like the simplicity of the URL in option 2. I'm happy to help thing through this more, especially as it applies to the DC BioBlitz.

**Comment by loarie** [comment]
Chatted with Patrick about this today and it sounds like option 2 is the best strategy for the NPS BioBlitz - you must yield to the power of the aggregator
