### ISSUE TITLE
iNat place data management decisions...

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#793]
We need to make some decisions on a Data Management plan for iNat places. Here's my understanding of where we left things from today's discussion - please comment if I have things wrong... (for anyone non-staff reading this, we're working on changes to the Observation Search UI which surfaces places in a new way that probably necessitates some data management of places).

We're separating places into 2 bins: "Standard" and "Community Curated". The definition of Community Curated places will be places with admin_level = nil. The idea is that for now, Site Admins will manage which places are included in the Standard set by setting admin_level and they will include 'admin sanctioned' admin_level 0 (Countries), admin_level 1 ('States'), and admin_level 2 ('Counties') places as well as Continents and subset of Parks. This means we have to come up with admin_levels for Continents and Parks and also a plan for how these data will be managed...

# Continents
We'll need to:

1. Pick the set of continents. Any objections to adopting
<a href="https://en.wikipedia.org/wiki/Continent">the 7 continent model</a>? While I don't think it matters, keep in mind this model (a) doesn't play nicely with any sort of place hierarchy (e.g. the country Egypt spans Africa and Asia) and (b) doesn't cover all land (e.g. most islands don't fall into contients) <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/ContinentStatistics.svg/1084px-ContinentStatistics.svg.png" />.

2. Create the place_geometries. To ensure continent boundaries with pretty coastlines, I propose we derive continent boundaries from Admin 0 country boundaries (slicing accordingly) - I can do this if folks want.

3. Come up with the admin_level. 0, 1, & 2 are taken. -1?

# Parks
The idea here is that Site Admins will be responsible for promoting parks from the Community Curated bin into the Standard bin by adding an admin_level. That way we can do things like add every CA state park at once with a script, but we can also respond to individual requests (e.g. 'I made a place for my local county park, can you guys make it a Standard place?') without flooding Standard places with all sorts of Community Curated craziness. Does this seem maintainable? If so we need to:

1. Pick an admin_level. Any objections to 4?

2. Prime the pump with some parks. US NPS parks might be a timely set. I'm sure other sets will follow suit from some of our more active partners (e.g. CONABIO, Colorado State Parks). If this sounds like a plan, I can take on adding admin levels to the US NPS parks which need to be cleaned up a bit for the Centennial anyway.

# Revisiting Admin Level 0, 1, 2 Places
These were originally loaded from http://gadm.org/ circa 2011, aside from manual community curation, they haven't been updated since. Might be worth revisiting our plan for managing/maintaining these.

1) Should we continue using  GADM as the source for Admin Level 0,1,2 places?

Pros: 

a. GADM continues to be maintained

Cons:

a. Some partners, like CONABIO aren't crazy about these boundaries

b. GADM boundaries are huge because they derive coastlines from a gridded 30m coastlines. Previous efforts added a buffer to coastlines to reduce their complexity and ensure that low tides etc didn't result in observations outside the place. But an algorithm to add these buffers without creating any overlap between places would be very complex. The previous algorithm which did a pretty good job was:
```
1. create 'landmass' polygon by unioning all GADM places
2. create 'place buffer' for each GADM place by computing a buffer
3. Subtract landmass from place buffer to create coastal buffer
4. Union each coastal buffer and GADM place to create 
```

2) The current set of Admin 0,1,2 places has departed from GADM because there's some UI where admin_level can be set by the community. We should probably identify this UI and remove it and clean up the places so that they continue to match whatever source we go with.

3) We should probably come up with some plan for regularly updating our Admin 0,1,2 places to keep them up to date with the source.

# Towns ??
We could adopt the same data management policy for Towns as for Parks (e.g. Site Admins promote them from Community Curated to Standard on a more or less case by case basis). My gut says leave all towns in Community Curated for now and maybe revisit this later, but thought I'd bring this up...

**Comment by naturalistcharlie** [comment]
This all sounds like a good idea. Perhaps it can also be applied to
location descriptions in observations (so everything near San Bernardino
doesn't come up as 'Rachel's Area' and "Tracking Practice" doesn't come up
on any observation in southern New England. We should have a curator
protocol for dealing with data quality management. For instance some parks
that have already been uploaded have boundaries with pretty serious
problems. Perhaps also some sort of push to get people to add places and
then a mechanism to review some of them for admin level.

On the subject of towns, this seems to vary based on location. in Vermont
the towns are like tiny counties, everywhere is in a town more or less, and
they are a grid in the state. For Vermont I think we'd be better off with
the towns in Admin level, though it isn't necessary and I'm not sure if
they are even all uploaded or not.

On Tue, Dec 8, 2015 at 9:23 PM, Scott Loarie <notifications@github.com>
wrote:

> We need to make some decisions on a Data Management plan for iNat places.
> Here's my understanding of where we left things from today's discussion -
> please comment if I have things wrong... (for anyone non-staff reading
> this, we're working on changes to the Observation Search UI which surfaces
> places in a new way that probably necessitates some data management of
> places).
>
> We're separating places into 2 bins: "Standard" and "Community Curated".
> The definition of Community Curated places will be places with admin_level
> = nil. The idea is that for now, Site Admins will manage which places are
> included in the Standard set by setting admin_level and they will include
> 'admin sanctioned' admin_level 0 (Countries), admin_level 1 ('States'), and
> admin_level 2 ('Counties') places as well as Continents and subset of
> Parks. This means we have to come up with admin_levels for Continents and
> Parks and also a plan for how these data will be managed...
> Continents
>
> We'll need to:
>
>    1.
>
>    Pick the set of continents. Any objections to adopting
>    the 7 continent model <https://en.wikipedia.org/wiki/Continent>? While
>    I don't think it matters, keep in mind this model (a) doesn't play nicely
>    with any sort of place hierarchy (e.g. the country Egypt spans Africa and
>    Asia) and (b) doesn't cover all land (e.g. most islands don't fall into
>    contients)
>    <https://camo.githubusercontent.com/efc80a30468f9c4579b9245b3ec250b3fc09b4be/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f7468756d622f612f61632f436f6e74696e656e74537461746973746963732e7376672f3130383470782d436f6e74696e656e74537461746973746963732e7376672e706e67>
>    .
>    2.
>
>    Create the place_geometries. To ensure continent boundaries with
>    pretty coastlines, I propose we derive continent boundaries from Admin 0
>    country boundaries (slicing accordingly) - I can do this if folks want.
>    3.
>
>    Come up with the admin_level. 0, 1, & 2 are taken. -1?
>
> Parks
>
> The idea here is that Site Admins will be responsible for promoting parks
> from the Community Curated bin into the Standard bin by adding an
> admin_level. That way we can do things like add every CA state park at once
> with a script, but we can also respond to individual requests (e.g. 'I made
> a place for my local county park, can you guys make it a Standard place?')
> without flooding Standard places with all sorts of Community Curated
> craziness. Does this seem maintainable? If so we need to:
>
>    1.
>
>    Pick an admin_level. Any objections to 4?
>    2.
>
>    Prime the pump with some parks. US NPS parks might be a timely set.
>    I'm sure other sets will follow suit from some of our more active partners
>    (e.g. CONABIO, Colorado State Parks). If this sounds like a plan, I can
>    take on adding admin levels to the US NPS parks which need to be cleaned up
>    a bit for the Centennial anyway.
>
> Revisiting Admin Level 0, 1, 2 Places
>
> These were originally loaded from http://gadm.org/ circa 2011, aside from
> manual community curation, they haven't been updated since. Might be worth
> revisiting our plan for managing/maintaining these.
>
>    1. Should we continue using GADM as the source for Admin Level 0,1,2
>    places?
>
> Pros:
>
> a. GADM continues to be maintained
>
> Cons:
>
> b. Some partners, like CONABIO aren't crazy about these boundaries
>
> c. GADM boundaries are huge because they derive coastlines from a gridded
> 30m coastlines. Previous efforts added a buffer to coastlines to reduce
> their complexity and ensure that low tides etc didn't result in
> observations outside the place. But an algorithm to add these buffers
> without creating any overlap between places would be very complex. The
> previous algorithm which did a pretty good job was:
>
> 1. create 'landmass' polygon by unioning all GADM places
> 2. create 'place buffer' for each GADM place by computing a buffer
> 3. Subtract landmass from place buffer to create coastal buffer
> 4. Union each coastal buffer and GADM place to create
>
>
>    1.
>
>    The current set of Admin 0,1,2 places has departed from GADM because
>    there's some UI where admin_level can be set by the community. We should
>    probably identify this UI and remove it and clean up the places so that
>    they continue to match whatever source we go with.
>    2.
>
>    We should probably come up with some plan for regularly updating our
>    Admin 0,1,2 places to keep them up to date with the source.
>
> Towns ??
>
> We could adopt the same data management policy for Towns as for Parks
> (e.g. Site Admins promote them from Community Curated to Standard on a more
> or less case by case basis). My gut says leave all towns in Community
> Curated for now and maybe revisit this later, but thought I'd bring this
> up...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/793>.
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by ChristopherTracey** [comment]
Sounds like a good approach overall. I just added polygon based boundaries for 100+ Pennsylvania State Parks last week and I was wondering if there was a better way.

Has there been any thought to adding parks from national datasets (e.g. Protected Areas Database - US [PAD-US])?

**Comment by carrieseltzer** [comment]
I have a clarifying question: how will this overall change affect the user experience? Are there other ways that this will be visible aside from what Charlie mentioned?

**Comment by loarie** [comment]
thanks for the feedback guys,

Charlie: the idea here was not bite off editing/deleting places made by other users. Just a way of separating them from the 'Standard' places that we'd make some attempt to manage. So, as you say, 'Rachel's Area' and maybe 100 variations on 'Texas' will still be there, just in the 'Community Curated' bin rather than the 'Standard' bin. I agree that a curator protocol for interacting with non-standard places should probably be better laid out in the Curator Guide, but thats a separate topic from this issue here.

Chris: Getting the Pennsylvania State Parks promoted to 'Standard' places is a good example of what we could do with this new system. I'm not too familiar with the PAD-US, but we've had mixed results loading in parts of the WDPA. Seems like there's a sweet spot between where loading in sets of parks is better than manually loading parks in one at a time and where loading in giant archives just introduces a lot of garbage and artifacts. I think sets of parks coming directly from the end users (e.g. the US NPS system coming from US NPS) probably fall in the former, but really big sets like the WDPA are almost certainly the latter. Not sure where the PAD-US falls. But if it includes derivatives of the NPS boundaries that will almost certainly yield complaints from the NPS folks then probably the latter.

Carrie: as I mentioned above, for now just that in the changes we're putting out to Observation Search we're going to try to surface Standard places separately from Community Curated places. This issue is to decide how to select, identify, and manage Standard places.

**Comment by naturalistcharlie** [comment]
Hi Scott, thanks! I don't want to take Rachel's area away from her, but I
was hoping perhaps we could use this to change things so that observations
don't pull their auto-generated location descriptions from Community
Curated places. For instance, see
http://www.inaturalist.org/observations/1765846 . It reads

"Location: 34.15947, -117.184608
<http://www.inaturalist.org/observations?lat=34.15947&lng=-117.184608> (
Google <http://maps.google.com/?q=34.15947,-117.184608&z=17>, OSM
<http://www.openstreetmap.org/?mlat=34.15947&mlon=-117.184608&zoom=17>)
Places: Rachels Area <http://www.inaturalist.org/places/rachels-area>, San
Bernardino National Forest
<http://www.inaturalist.org/places/san-bernardino-national-forest>, San
Bernardino <http://www.inaturalist.org/places/san-bernardino-county>,Southern
California <http://www.inaturalist.org/places/southern-california>, US-CA
<http://www.inaturalist.org/places/california-us>, US
<http://www.inaturalist.org/places/united-states>, NA
<http://www.inaturalist.org/places/north-america>"

and I think it would be better if Rachel's Area weren't there like that.
Rachel's area is pretty benign but several times i have come across
user-created areas that were outright wrong, watersheds mapped in the wrong
place, whole mountain ranges misnamed, etc. I don't think we should take
away the option of people making their own places, but IMHO the
non-standardized ones should not be used the same way.

I know I am the fussiest map person ever, but I do think there's a lot of
potential for confusion with these places like this.

Another great option that might help would be to let people make private
places, since no one else really cares about Rachel's area (sorry to pick
on Rachel). I am biased because I want to create an auto generated life
list of our property but don't want to create a place for it, since I don't
really want that public.

C

On Wed, Dec 9, 2015 at 1:31 PM, Scott Loarie <notifications@github.com>
wrote:

> thanks for the feedback guys,
>
> Charlie: the idea here was not bite off editing/deleting places made by
> other users. Just a way of separating them from the 'Standard' places that
> we'd make some attempt to manage. So, as you say, 'Rachel's Area' and maybe
> 100 variations on 'Texas' will still be there, just in the 'Community
> Curated' bin rather than the 'Standard' bin. I agree that a curator
> protocol for interacting with non-standard places should probably be better
> laid out in the Curator Guide, but thats a separate topic from this issue
> here.
>
> Chris: Getting the Pennsylvania State Parks promoted to 'Standard' places
> is a good example of what we could do with this new system. I'm not too
> familiar with the PAD-US, but we've had mixed results loading in parts of
> the WDPA. Seems like there's a sweet spot between where loading in sets of
> parks is better than manually loading parks in one at a time and where
> loading in giant archives just introduces a lot of garbage and artifacts. I
> think sets of parks coming directly from the end users (e.g. the US NPS
> system coming from US NPS) probably fall in the former, but really big sets
> like the WDPA are almost certainly the latter. Not sure where the PAD-US
> falls. But if it includes derivatives of the NPS boundaries that will
> almost certainly yield complaints from the NPS folks then probably the
> latter.
>
> Carrie: as I mentioned above, for now just that in the changes we're
> putting out to Observation Search we're going to try to surface Standard
> places separately from Community Curated places. This issue is to decide
> how to select, identify, and manage Standard places.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/793#issuecomment-163350604>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by loarie** [comment]
Hi Charlie - noted for future issue(s) when we get to rethinking the web observation show page

**Comment by naturalistcharlie** [comment]
Makes sense, sorry if I roamed too far from the topic at hand.

On Wed, Dec 9, 2015 at 2:15 PM, Scott Loarie <notifications@github.com>
wrote:

> Hi Charlie - noted for future issue(s) when we get to rethinking the web
> observation show page
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/793#issuecomment-163361655>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by ChristopherTracey** [comment]
Scott,
  Good points and I'm happy that protected areas will get to a 'Standard Place' status. I'm not positive, but I think that while PAD-US aggregates many sources of data, some agencies, like NPS, are the sole provider of data. Nevertheless, it could fill in a lot of protected areas data.
http://gapanalysis.usgs.gov/padus/

**Comment by loarie** [comment]
notes from conversation with Patrick -
use admin_level -1 for continents and 10 for parks
stick with past GADM approach for any updates to level 0,1,2 places

**Comment by kueda** [comment]
I'm fine with all this, but I'd really like to figure out a solution to the coastal buffer issue. If we lose those it becomes a pretty giant bummer for anyone who likes observing things in the ocean, which is a lot of us. For example, in the US we're actually *not* currently using GADM data for counties at least, and are instead using US Census TIGER boundaries, which are great:

![screen shot 2015-12-15 at 12 15 03 pm](https://cloud.githubusercontent.com/assets/22691/11822856/985f7e52-a325-11e5-9c6e-62d08c46a0d3.png)

GADM in red, Census in blue. NatureWatch and NaturaLista folks are also going to be pretty particular about their boundaries and probably won't love GADM either. How about a protocol in which we have some preferred place-providers for some places, but use GADM for everything else? We could just script this: download shapefiles from trusted sources that provide them *publicly* within enough info for us to infer ISO country code, admin level, and name for every place, make or update iNat place boundaries, and then use GADM for the rest, or a version of GADM we've processed with coastal buffers.

**Comment by loarie** [comment]
I'm fine with that. But essentially outside of US (TIGER data) we're currently using all GAMD data.

Just wanted to clarify with this cartoon (obviously not to scale). You're right that the US county data in iNat is from TIGER. But we used TIGER as the standard for coming up with a buffer radius and a point simplification threshold that we applied to everything from GADM. As described in the gray box above, an algorithm was applied to GADM which adds a buffer (same radius as TIGER) then subtracts landmass and then adds the boundary. This does a pretty good job of emulating what TIGER does except for sorting out the intersection of buffers. With this approach, they overlap slightly.
<img width="1149" alt="screen shot 2015-12-15 at 1 08 25 pm" src="https://cloud.githubusercontent.com/assets/598026/11824166/f26d7da2-a32c-11e5-986f-25a796a2eea3.png">
The plan we discussed was to apply this same buffer algorithm to all GADM boundaries (and not replace the US County TIGER boundaries).

If anyone can come up with an algorithm that removes overlap in the coastal buffers (as in TIGER US Counties) - that would be awesome

One other thing. I kind of like having consistent coastal buffers for these standard places (e.g. which the GADM algorithm applies). Under your protocol, imagine Guatemala had their own set of preferred boundaries but they had a tight coastline (like the raw GADM) rather than a buffered coastline (like TIGER). Would the protocol include applying the Coastal Buffer algorithm to their data?

**Comment by kueda** [comment]
Re: the Guatemala example, I'd say no. Our policy can be that we use buffered GADM boundaries. If you are a paying partner and you want to use other boundaries, you need to provide a shapefile that has:

1. ISO country code, admin level (or equivalent), and name for all places
1. Includes ocean buffers analogous to what the buffered GADM shapes have
1. Be publicly accessible on the web so we can access it whenever we regenerate boundaries (if it disappears, we revert to GADM)

US Census TIGER boundaries meet both of these requirements, so they're good to go. If a Guatemalan group wants special boundaries, they must publish data that meets our requirements.

**Comment by loarie** [comment]
sounds good to me

**Comment by ChristopherTracey** [comment]
Scott, does this solve the overlapping coastal buffer issue?: http://ohi-science.org/pages/create_regions.html

**Comment by loarie** [comment]
@ChristopherTracey just saw this now - looks very promising! Let me investigate... Thanks!

**Comment by loarie** [comment]
@ChristopherTracey that totally works! Thanks for finding that! I got this voronoi step integrated into the script and it works at least on places like Costa Rica here: <img width="166" alt="screen shot 2016-02-01 at 9 01 48 am" src="https://cloud.githubusercontent.com/assets/598026/12724392/9bfe9f30-c8c2-11e5-91ef-8356ef0b1871.png">
I bet I'll need to do some futzing to get it to work on huge places like Canada, will investigate that this week.

Really cool to have a fix for those ugly overlaps!

**Comment by loarie** [comment]
this is done
