### ISSUE TITLE
Support social sign-in buttons on mobile web view

### ISSUE THREAD

**Issue by md5** [inaturalist/inaturalist#795]
When I receive an iNaturalist email and click on an image, it takes me to the mobile web view. I'd like to be able to log in easily from this view, but unlike the desktop view, it does not offer the social sign-in buttons (Facebook, Google, etc).

**Comment by md5** [comment]
I also noticed I'm seeing a weird number at the top of the screen on the login page. It looks like it's coming from this commit: https://github.com/inaturalist/inaturalist/commit/b2ccfea8ec131cf1aa34e8c75369e905d1498770

I'm using Chrome on Android 5.1.1.

**Comment by carrieseltzer** [comment]
Count me in on the desired support for mobile social sign in! 



—

**Comment by md5** [comment]
@carrieseltzer :+1:

**Comment by carrieseltzer** [comment]
The mobile web view is long gone, and social sign in is possible from the web sign in page (which is responsive), so I'm going to close this.
