### ISSUE TITLE
Styles missing from httpS://www.inaturalist.org/home

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#801]
I followed a link (from an NG page) that took me to https://www.inaturalist.org/home because I was already logged in. Styles are missing in both Chrome and Safari. See screen shot.

![screen shot 2016-01-05 at 11 37 25 am](https://cloud.githubusercontent.com/assets/7501183/12121059/5acbee18-b3a1-11e5-8e80-bb06cbb707a1.png)

Other pages appear unaffected, but /home consistently shows without styles even after clicking to other pages that are styled.

**Comment by loarie** [comment]
hmm - yeah assets from https seem broken for me too

**Comment by pleary** [comment]
It's all working for me. Anyone else seeing this? Is it still happening? What happens if you close the browser and reopen? Or log out and log back in?

**Comment by loarie** [comment]
still happening in for me, but logging out and back in fixed it

**Comment by carrieseltzer** [comment]
Still happening. If I log out and log back in, logging in takes me to
http://www.inaturalist.org/home# where styles are working. But if I'm
logged in and go to https://www.inaturalist.org/home
<https://www.inaturalist.org/home#> (or get redirected there from
https://www.inaturalist.or <https://www.inaturalist.org/home#>g) it's still
broken.

On Tue, Jan 5, 2016 at 12:12 PM, Patrick Leary <notifications@github.com>
wrote:

> It's all working for me. Anyone else seeing this? Is it still happening?
> What happens if you close the browser and reopen? Or log out and log back
> in?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/801#issuecomment-169064979>
> .
>



-- 
Carrie E. Seltzer, Ph.D.
National Geographic's Great Nature Project
www.greatnatureproject.org

**Comment by loarie** [comment]
oh good point, I see the same thing as Carrie - was forgetting to switch back to https.

But if I open a new browser (safari as opposed to chrome where I was seeing this) and log in its fixed

**Comment by carrieseltzer** [comment]
It looks like logging in always takes you to http instead of https, even if
you started at https, which is why it appears fixed.

On Tue, Jan 5, 2016 at 12:18 PM, Scott Loarie <notifications@github.com>
wrote:

> oh good point, I see the same thing as Carrie - was forgetting to switch
> back to https.
>
> But if I open a new browser (safari as opposed to chrome where I was
> seeing this) and log in its fixed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/801#issuecomment-169068659>
> .
>



-- 
Carrie E. Seltzer, Ph.D.
National Geographic's Great Nature Project
www.greatnatureproject.org

**Comment by pleary** [comment]
I've just cleared some caches. If you see any improvement let me know, otherwise I'll bother Scott later since he's experiencing the problem.

**Comment by pleary** [comment]
actually I think I see what's happening. I'll work on a fix

**Comment by pleary** [comment]
OK I think this should be fixed now. How is it looking for you?

**Comment by carrieseltzer** [comment]
Looks fixed to me too! Thanks!

On Tue, Jan 5, 2016 at 1:46 PM, Patrick Leary <notifications@github.com>
wrote:

> OK I think this should be fixed now. How is it looking for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/801#issuecomment-169093975>
> .
>



-- 
Carrie E. Seltzer, Ph.D.
National Geographic's Great Nature Project
www.greatnatureproject.org
