### ISSUE TITLE
mobile web page showing app store ID

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/inaturalist#802]
above the iNaturalist header and below the invitation to download the iNat app. (the invitation is blank on this screenshot because it's a simulator screenshot, but I see the same issue on my phone).

![simulator screen shot jan 5 2016 5 20 20 pm](https://cloud.githubusercontent.com/assets/515947/12132523/4413ffc8-b3d1-11e5-8e9b-77b93fbf517b.png)

**Comment by pleary** [comment]
All gone. I'm pretty sure that was there unintentionally, but @kueda can correct me if I'm wrong

**Comment by md5** [comment]
I thought I had reported this, but I guess it was just [a comment](https://github.com/inaturalist/inaturalist/issues/795#issuecomment-164891965)
