### ISSUE TITLE
too easy to make q= search, too hard to remove it (or even know that it's there)

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/inaturalist#809]
I used the Observations->Search Obs menu item to search for "squirrel". 

The search UI at this point was locked into showing search with q=squirrel. If I tried to search for something else, not using the menu item but instead using search species or place UI on the new search page, everything was still only shown with q=squirrel&taxon_id=47208. Once I realized what was going on, I started looking for how to remove the q=squirrel param using the UI, and it was only when I went into the filters section and removed the "squirrel" search from tags/description that I started seeing other results.

![image](https://cloud.githubusercontent.com/assets/515947/12361841/453a33c6-bb75-11e5-9e74-13831255b04a.png)

recommendation:
1) consider removing the Search Obs menu item from the menu
2) make it more obvious when filters are active

it should be just as easy to remove a filter as it is to add one.

**Comment by kueda** [comment]
Since that's almost always ends up being a taxon search, maybe we could just make that the default text of the taxon chooser, perhaps by resurrecting the `taxon_name` parameter. Thoughts, @pleary? Means another URL param to track and ignore in API requests.

**Comment by pleary** [comment]
Or we could put the taxon autocomplete form there (mentioned by @loarie yesterday), that way they can choose a taxon first and the ID can be sent to search. taxon_name wouldn't be a huge deal. I forsee us adding in lots of params like that in the coming days (like #811)

I also like the idea of summarizing the search somewhere that is visible "Showing results for: popular, threated, with photos..."

**Comment by kueda** [comment]
Talked about this on 2016-01-19 and we agreed to deal with this by resurrecting the `taxon_name` param. The header menu search will search on `taxon_name` instead of `q`, and in the Rails app we'll do our best to find a single taxon for that name and choose it for the angular app, and if we can't find one, we'll just fill in the taxon autocomplete.

**Comment by pleary** [comment]
fixed in 3aee108
