### ISSUE TITLE
Not sure where the establishment means E is coming from here

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#810]
Doesn't seem to be on the listing for that taxon/place
http://www.inaturalist.org/observations?place_id=2764&view=species&iconic_taxa=Reptilia
<img width="254" alt="screen shot 2016-01-15 at 11 01 41 am" src="https://cloud.githubusercontent.com/assets/598026/12362309/6251127a-bb77-11e5-94cb-e6efb7e97b72.png">
http://www.inaturalist.org/listed_taxa/4266814
<img width="384" alt="screen shot 2016-01-15 at 11 02 03 am" src="https://cloud.githubusercontent.com/assets/598026/12362320/70247176-bb77-11e5-85cc-4a204c4ed7c4.png">

**Comment by pleary** [comment]
Right now we're using a places ancestors to determine those flags. There is a record for that taxon being endemic to the US http://www.inaturalist.org/listed_taxa/137500

**Comment by kueda** [comment]
I think what Scott's driving at is that it would be nice to be able to link to the listed taxon that triggered that establishment means listing, which would mean indexing more than just threatened / introduced / native / endemic, but also indexing the listed taxon ID for each of those, which might not be performative. Not sure.

**Comment by pleary** [comment]
We index the relevant listed_taxa, but the ID isn't part of the payload right now. We could say what place it's relevant to, but to link to the LT we'd need to reindex. It's doable though

**Comment by loarie** [comment]
that seems like a good solution of saying the place its relevant to.

**Comment by pleary** [comment]
Staging is running with 3aee108 which includes place info in the title attribute when you mouse over these boxes. Does that look OK? Enough to close this ticket?

**Comment by pleary** [comment]
Any feedback on this?

**Comment by loarie** [comment]
yeah looks good - nice solution

**Comment by loarie** [comment]
yeah looks good - nice solution (comment fail)
