### ISSUE TITLE
infowindows from mousingover snippets don't always dismiss

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#812]
This is pretty minor but I thought I'd log it.
If you zip over the snippets quickly with your cursor its pretty easy to get a infowindow to trigger but not be dismissed. And it hangs around until you manually close it.
http://www.inaturalist.org/observations?iconic_taxa=Amphibia
<img width="821" alt="screen shot 2016-01-15 at 11 26 53 am" src="https://cloud.githubusercontent.com/assets/598026/12362955/e9a92d9a-bb7a-11e5-9be3-9a8317e285b4.png">

**Comment by pleary** [comment]
I think this is working pretty well now. How does it look for you?

**Comment by kueda** [comment]
@loarie, is this fixed for you? If so please close.

**Comment by loarie** [comment]
fixed!
