### ISSUE TITLE
make # observation links from species grid view actually links

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#813]
Right now they're just elements that trigger some JS, which means you can't open those links in a new window or tab if you want to. I think if we just actually link the the URL params they will make that will suffice, even if it refreshes the window.

**Comment by pleary** [comment]
I tried various ways to use angular magic sometimes, but still allow opening the links in new tabs and that was a pain. These are now just proper `<a href>` tags and will always reload the page
