### ISSUE TITLE
sometimes taxon photos aren't showing

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#825]
This seems to happen with Wikimedia Commons photos some of the time, but not all of the time.

http://www.inaturalist.org/observations?nelat=34.7524856&nelng=-119.96913540000003&swlat=34.7341482&swlng=-120.00115019999998&taxon_id=48225&view=species

http://www.inaturalist.org/observations?place_id=21&taxon_id=47328&view=species

**Comment by pleary** [comment]
URLs like http://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Tricyrtis_hirta_-_blossom_side_(aka).jpg/500px-Tricyrtis_hirta_-_blossom_side_(aka).jpg were a problem since we weren't using quotes in the `background-image: url( )` style
