### ISSUE TITLE
Project Page UX Quick Fixes

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#827]
Just a quick clean up of some UX hurdles. Please let me know a few days before coding and I will make some visual specs. 

![image](https://cloud.githubusercontent.com/assets/11527994/12433734/a87737f0-beb7-11e5-9632-b13772c8a034.png)

- [ ] uppercase "Most" column headers
- [ ] titlecase links
- [ ] replace "All X" links with "View all" links beneath "Most" columns
- [ ] move realtime and about links below the totals

**Comment by kueda** [comment]
I can do this this week. Doesn't seem like it needs more design work, but was that something you wanted to do?

**Comment by joellebel** [comment]
Ok. Great. As far as an interim design solution it's ready to go. I will whip up some specs early this week. One thing this mock up doesn't reflect is a matching height between the profile pics and the taxon pics in the "Most Observations, Most Species..." lists. This way the "View All" links will line up properly.

**Comment by joellebel** [comment]
@kueda 

Just a note... 

> One thing this mock up doesn't reflect is a matching height between the profile pics and the taxon pics in the "Most Observations, Most Species..." lists. This way the "View All" links will line up properly.

![image](https://cloud.githubusercontent.com/assets/11527994/12606298/1f370702-c481-11e5-9a9d-21e19d0c5c00.png)

**Comment by kueda** [comment]
Not sure what the "View all" links are supposed to link to. "View all" beneath "Most observations" would suggest you can see a full list of the *people* who had the most observations, but the "All observations" link above and to the right of the stats linked to full list of all the *observations."  Basically those links you've removed here just duplicated the links on the left below the "TOTALS" so how about we just omit them.

**Comment by kueda** [comment]
Waiting on an opinion re: view all links. Otherwise it's looking like this:

![screen shot 2016-02-08 at 4 17 26 pm](https://cloud.githubusercontent.com/assets/22691/12903813/76ded446-ce7f-11e5-9e38-8b57af3b2d74.png)

**Comment by joellebel** [comment]
I guess we could get rid of them. It's just that if someone was looking for their rank, they may not think to click on the "People >>" link. Is this up somewhere I can see it? Thnx.
