### ISSUE TITLE
date range search without times excludes obs with observed_on within d2 when it has a time

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#831]
For example, this search
http://www.inaturalist.org/observations?d1=2016-01-03&d2=2016-01-09&taxon_id=71268&verifiable=true
gives me 75 observations, but excludes observations like:
Obs.id: 2601968 which has observed_on: 2016-01-09 13:37:00 -0500
because it is within d2 but has a time.

I guess this is sort of arbitrary. But it would seem to me to make the most since if date range searches without times included all observations with a date or datetime >=d1 and <=d2 (right now its returning obs >=d1 and <=d2 when there is ONLY a date, but  >=d1 and <d2 when there is a date AND time)

Also would be a convenient setting for events like the critter calendar when we want to set the date range to a week but aren't concerned with times

**Comment by pleary** [comment]
Staging is running code which I hope meets these requirements. Let me know how this looks http://staging.inaturalist.org/observations?d1=2016-01-03&d2=2016-01-09&order=asc&order_by=observed_on&subview=table&taxon_id=71268&verifiable=any

It'll take some time to do the re-indexing, so I want to make sure I haven't missed something

**Comment by pleary** [comment]
I have Staging set up again today. Any feedback on this implementation of dates?

**Comment by loarie** [comment]
looks good to me
