### ISSUE TITLE
D-M-Y queries on own obs giving whale shark

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#832]
It looks like, since the switch to the new observation search format, that searching on one's own observations by date (specifically using month) doesn't work anymore. Something is wrong with the month parameter if you're searching within observations by a specific user.

Fails with D, M, & Y
https://www.inaturalist.org/observations/carrieseltzer?day=1&month=1&year=2016

Fails with M only
https://www.inaturalist.org/observations/carrieseltzer?day=&month=10&year=

Ok with D only
https://www.inaturalist.org/observations/carrieseltzer?day=1&month=&year=

Ok with D & Y
https://www.inaturalist.org/observations/carrieseltzer?day=1&month=&year=2015

Ok with Y only
https://www.inaturalist.org/observations/carrieseltzer?day=&month=&year=2007

**Comment by pleary** [comment]
Sorry about that. This was fixed in 26cbd6e, and has been deployed to production. The above URLs are now working

**Comment by carrieseltzer** [comment]
Thanks, Patrick!
