### ISSUE TITLE
Make iNaturalist home page link look better on Facebook

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#835]
Right now there's no preview image associated with www.inaturalist.org when you share it on Facebook. Individual pages usually have an image that pops up, but the main site doesn't and I think this is a big loss. See screen shot of how the home page looks on Facebook (setting post privacy to "only me" is useful for testing things like this).

Here are a few links that might be useful for fixing this:
https://developers.facebook.com/docs/sharing/best-practices
http://cypressnorth.com/social-network-media-marketing/how-to-customize-preview-thumbnail-images-for-pages-on-your-website/

![screen shot 2016-01-22 at 5 31 23 pm](https://cloud.githubusercontent.com/assets/7501183/12525040/6077b590-c12f-11e5-9736-1286d24463f0.png)

**Comment by naturalistcharlie** [comment]
When I share journal posts or other things like that i usually get my
profile picture. That can be kind of awkward when i am posting it as a
comment on a facebook page or a friend's page... I know I can remove the
picture but that isn't ideal either

On Fri, Jan 22, 2016 at 5:42 PM, carrieseltzer <notifications@github.com>
wrote:

> Right now there's no preview image associated with www.inaturalist.org
> when you share it on Facebook. Individual pages usually have an image that
> pops up, but the main site doesn't and I think this is a big loss. See
> screen shot of how the home page looks on Facebook (setting post privacy to
> "only me" is useful for testing things like this).
>
> Here are a few links that might be useful for fixing this:
> https://developers.facebook.com/docs/sharing/best-practices
>
> http://cypressnorth.com/social-network-media-marketing/how-to-customize-preview-thumbnail-images-for-pages-on-your-website/
>
> [image: screen shot 2016-01-22 at 5 31 23 pm]
> <https://cloud.githubusercontent.com/assets/7501183/12525040/6077b590-c12f-11e5-9736-1286d24463f0.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/835>.
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by carrieseltzer** [comment]
It's showing a preview now, but just the "download the app" icons. Is that what you intended? It would be much nicer to have one of the header images (mantis, snail, bird) come up, or even just the green inat bird logo. Photos would surely get more clicks though.

![screen shot 2016-02-02 at 8 07 20 pm](https://cloud.githubusercontent.com/assets/7501183/12769795/c2795408-c9e8-11e5-8b1d-51ed1232b9b6.png)

**Comment by kueda** [comment]
We haven't deployed it yet, Carrie. Try it again in a day or so.

**Comment by carrieseltzer** [comment]
Ah ok! Thanks!
