### ISSUE TITLE
"update search" button is unnecessary

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/inaturalist#838]
In the new observation search, when I open the filters section and start changing the active filters, the content behind the search popover updates live. The update search button doesn't really do anything.

**Comment by kueda** [comment]
We talked about this and I think we decided that changes to the map and stats were so obscured by the filters that it was never obvious that your actions in the filters box were actually taking effect, so the Update Search button at least kind of takes you to the next step in the interaction: viewing the results of your filter choices. Not sure if we've actually done any in-person testing to see if people miss it when we remove it.

**Comment by alexshepard** [comment]
Cool. I guess it was unexpected for me because when I see a Save button, I feel like I'm being promised that my changes won't take effect until I tap it.
