### ISSUE TITLE
site posts

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#839]
Make posts that are associated with a site.

- [x] add new parent type for Post
- [x] nest resources under `/news` or `/blog`
- [x] re-use existing post templates but make sure they work with Site as a parent
- [x] make sure all notifications (both of new posts and mentions) look right for Site posts
- [x] mix Site posts into `posts/for_project_user`, and consider changing that endpoint to `posts/for_user` or something since it's not just project stuff anymore

Open questions:

1. Are all members of a site automatically notified by posts from the site they're affiliated with?
1. Do we want some notion of a "default" site so people associated with NaturaLista get iNat's Critter Calendar stuff even though they're not affiliated with iNaturalist.org?

**Comment by loarie** [comment]
re: 1 do you mean posts appear in dashboard, as updates or both?
re: 2, seems like that might open a an of worms about data ownership/site allegiance etc. How about a profile setting like 'receive news from all sites'?

**Comment by kueda** [comment]
1. The dashboard and updates are the same thing. Not sure what kind of distinction you're drawing. Maybe the notifications in the header? Those are updates, just a subset. I was specifically talking about updates on the dashboard (or any updates at all). We could generate them for all users of a site, though that might kind of suck. Or we could just pilot them without notifications and only show them in the app, or show them in a special section of the dashboard, away from the normal updates.
1. If you have an opt-in "receive news from all sites" setting. with the default behavior being that you have to see updates from your site, then it will be up to site admins to ensure the news tab in the app has some content. I'm fine with that, also fine with just never showing posts from sites you're not affiliated with.
