### ISSUE TITLE
Link soundcloud button on conabio.inaturalist.org triggers 'invalid credentials'

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#84]
From conabio.inaturalist.org but not www.inaturalist.org, linking a soundcloud account
![screen shot 2013-06-25 at 5 55 01 pm](https://f.cloud.github.com/assets/598026/706780/1d7a8dd6-ddfb-11e2-8fd1-732f2d73d5dc.png)
redirects to www.inaturalist.org with the invalid credentials flash
![screen shot 2013-06-25 at 5 54 48 pm](https://f.cloud.github.com/assets/598026/706781/20088684-ddfb-11e2-993e-21b1e4b4784c.png)

**Comment by loarie** [comment]
This is still broken - I'm now getting 'redirect_uri_mismatch' when trying to Connect to Soundcloud from NaturaLista. As suggested in #79 should we abandon and close this issue?

**Comment by kueda** [comment]
Not really sure this is worth fixing. I'd rather see time and effort put into direct sound uploads. Soundcloud is pretty limited in how much you can store.

**Comment by patsimpson2000** [comment]
Hi guys, 
recorded a couple of bird calls and was trying to upload to iNat, but it's not working. I clicked "link your soundcloud acct", get to the sign in page of soundcloud to let iNat access, I sign in. I get the "Allow “iNaturalist” access to your SoundCloud account?" and click the connect button. That brings me to the iNat.org login screen. I login. I do to add an observation and add sound, and again it asks me to connect my iNat acct to my soundcloud acct. If I do that, I end up doing the same steps as above. It's an endless loop. Any suggestions?

**Comment by patsimpson2000** [comment]
I also tried clicking the "sign in with SoundCloud" on the iNat login screen. I get the same result. As soon as I click connect on the SoundCloud account, it kicks me back to the iNat login screen.
