### ISSUE TITLE
minor: sometimes changing a search filter changes the size of the map dots

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/inaturalist#840]
This doesn't happen all of the time, but when it does, it can be confusing.I notice it most often with the "has photos" filter.

The first time I noticed it, it looked like there were more observations with photos (bigger dots) than there were with or without photos (smaller dots).

here's a blurry animated gif conversion of a movie (because github doesn't support movies).

![y057h](https://cloud.githubusercontent.com/assets/515947/12564530/8f49429e-c364-11e5-84a0-fdfa93b8108d.gif)

**Comment by kueda** [comment]
That is weird. Maybe a caching issue, though maybe the styles for our tiles are varying based on different params?

**Comment by pleary** [comment]
on the older /observations we distinguished between the base layer and the "filtered" layer. The base layer always had smaller dots since it was showing everything, and the smaller dots looked better with more observations. On the new search were doing the same thing, but it's a little weird because deselecting "verifiable" gives more results, and since it's not the "base" layer it's using the larger dots. 

Would it be better if we just used the larger dots all the time?

**Comment by kueda** [comment]
I'd actually prefer everything smaller all the time, I think, but that's just me. Consistency is probably more important than which size we choose, so if we want to stick with large points for filtered and basically consider everything from obs search to be filtered, that works for me.

**Comment by naturalistcharlie** [comment]
Overall I mostly prefer the smaller dots also

On Mon, Jan 25, 2016 at 4:48 PM, Ken-ichi <notifications@github.com> wrote:

> I'd actually prefer everything smaller all the time, I think, but that's
> just me. Consistency is probably more important than which size we choose,
> so if we want to stick with large points for filtered and basically
> consider everything from obs search to be filtered, that works for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/840#issuecomment-174680668>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by pleary** [comment]
Well, I guess I went against the consensus here and for the last few weeks all the dots have been the larger kind. It's easy enough to change if people feel strongly about it. I'll close this for now since they're at least all the same size.
