### ISSUE TITLE
lrank-like equiv that incorporates descendants? how hard to implement?

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#843]
One issue with the leaf count that @kueda mentioned is that the existence of obs ID'd to rarely used subspecies hides the display of the more common species in the obs search species tab which can distort the usefulness of this feature for finding common taxa.
e.g. Western Fence Lizards isn't displayed here because of the presence of subspecies http://www.inaturalist.org/observations?place_id=any&taxon_id=36204&verifiable=any&view=species
<img width="817" alt="screen shot 2016-01-25 at 2 53 29 pm" src="https://cloud.githubusercontent.com/assets/598026/12567443/f9f6e24a-c373-11e5-8d20-6b290cbfc608.png">
Even though the species has the weight of the vast majority of obs:
<img width="506" alt="screen shot 2016-01-25 at 2 56 01 pm" src="https://cloud.githubusercontent.com/assets/598026/12567434/f110d6fe-c373-11e5-8e55-c2238f67969f.png">
Using 'lrank=species' could potentially be a hack round this by setting a floor at the species level, but its a shame to loose out on those 1,289 obs ID'd at subspecies level 
http://www.inaturalist.org/observations?lrank=species&place_id=any&taxon_id=36204&view=species&verifiable=any
<img width="805" alt="screen shot 2016-01-25 at 2 53 41 pm" src="https://cloud.githubusercontent.com/assets/598026/12567446/fb8038d2-c373-11e5-9893-5c3f313dd57e.png">
Just out of curiosity, how hard would it be to make a parameter that, like lrank, set the floor to a particular rank so that the species tab did not include subspecies. But unlike lrank, assembled this species list from all obs of that taxa and descendant taxa (e.g. not just obs of that taxa), so that the count on Western Fence would be 4,148+1,289 = 5,437 obs?

Not saying this is a good idea, just curious if something like this would involve a minor futz or an expensive post processing of elastic search data (as in the leaf count itself)

- IMO the behaviour the leaf count gives us of including coarse taxa without descendants (like beetle genera) in the species lists is a big benefit. But this behavior of automatically breaking up species into the shady world of subspecies (when any obs ID'd to subspecies are present) is less clear... definitely distorts how the order reflects commonness which I like

**Comment by loarie** [comment]
This issue was referenced in the google group here: 
https://groups.google.com/forum/#!searchin/inaturalist/$20inactive$20taxon$20are$20taking$20the$20sit$20if$20not$20the$20exact$20specie$20is$20filtered/inaturalist/hpCY5Pv1HOM/MtK2sg5NEAAJ

what would be involved in adding a parameter to api.inaturalist.org/observations/species_counts that counts species as either:
1. species
2. all taxa minus ancestors (leaves)
3. taxa (species or coarser) minus ancestors
?

**Comment by pleary** [comment]
I have a version of this running in production now. I added a new field that has the taxon ancestry, but down to a minimum of species, and I'm using that to calculate leaves. It's still possible to get the original leaf count if we want. I think this looks pretty good though. Thoughts?

**Comment by pleary** [comment]
Is this closable? If not what are the remaining requirements?

**Comment by loarie** [comment]
looks great
