### ISSUE TITLE
change semantics of 'Still Needs ID?'

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#851]
People are misunderstanding the 'Still Needs ID?' vote in the Data Quality Assessment to mean
'Do I think my own ID on this obs is incorrect?'

Here are some examples:
http://www.inaturalist.org/observations?place_id=any&quality_grade=casual

Suggest switching the label from "Still Needs ID?" to "Community can confirm/improve ID?"
<img width="292" alt="screen shot 2016-01-29 at 1 01 39 pm" src="https://cloud.githubusercontent.com/assets/598026/12688052/780284a2-c688-11e5-9f9b-9c6d99f121b4.png">

**Comment by kueda** [comment]
Fine with me.

**Comment by loarie** [comment]
I can probably take this one on

**Comment by pleary** [comment]
Scott resolved this with b2e8e2d

**Comment by loarie** [comment]
Still some confusion here https://groups.google.com/forum/#!topic/inaturalist/0ZDP9YKEaO8
In this pull request: https://github.com/inaturalist/inaturalist/pull/910 I made these additional changes:
<img width="926" alt="screen shot 2016-03-02 at 12 06 39 pm" src="https://cloud.githubusercontent.com/assets/598026/13473696/54b60ac2-e06f-11e5-8b63-818b1d41d667.png">

**Comment by naturalistcharlie** [comment]
Wouldn't you want it visible if there's a community ID of species or lower?
I thought one of the main points of this was to get a 'third opinion' if
you barely had research grade but wanted more feedback. I may be
misunderstanding but I thought that was the main point of having this
field. If it isn't, you could probably solve the problem by rewording it to
say 'observation can not be identified from photo' because that would be
the only other use for it, right?

Apologies if I'm not understanding.

On Wed, Mar 2, 2016 at 3:08 PM, Scott Loarie <notifications@github.com>
wrote:

> Still some confusion here
> https://groups.google.com/forum/#!topic/inaturalist/0ZDP9YKEaO8
> In this pull request: #910
> <https://github.com/inaturalist/inaturalist/pull/910> I made these
> additional changes:
> [image: screen shot 2016-03-02 at 12 06 39 pm]
> <https://cloud.githubusercontent.com/assets/598026/13473696/54b60ac2-e06f-11e5-8b63-818b1d41d667.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/851#issuecomment-191404832>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by pleary** [comment]
I also wonder if some re-wording would help. Something along the lines of "With available evidence is it possible to assign a more specific ID?" possible / not possible

**Comment by loarie** [comment]
charlie, if an obs has a community ID of species or lower, the only use case I can think of where you'd want to vote 'no' on "Community can confirm/improve ID?" is someone wanted to kick it back into Needs ID until it gets a subspecies/variety ID. But that seems pretty niche. 

We didn't have the third opinion use case in mind (or at least I hadn't thought about that). Under the current definition of Research grade which is at least 2 people agree on a community ID of rank family or finer (assuming it can't be ID'd further) doesn't seem quite right to be voting things out of research grade to get a 3rd opinion.

As for changing the semantics of the label. Fine with me.  'Observation can not be identified from photo' won't work because maybe it can be identified, jut not to a finer taxonomic rank. And also the evidence might be a sound rather than a photo.

"With available evidence is it possible to assign a more specific ID?" possible / not possible
seems fine. To nitpick I'd replace 'assign a more specific ID' with 'confirm/improve ID' because a major use case is someone posts a dark spec in a tree, calls it American Robin and it sits as 'Needs ID'. I'd want to vote it out of Needs ID, because I can't confirm the ID (not because I can't assign a more specific ID - its already at Robin). That would leave: 
"With available evidence is it possible confirm/improve ID?" possible / not possible
which is fine
I also tried to get the word 'community' in there to emphasize that this isn't you doing the confirming/improving but the community (remember our major problem is people voting no preemptively on their own observations). Which would make:
"With available evidence is it possible for community to confirm/improve ID?" possible / not possible
which IMO is longer, but a fine replacement for 
"Community can confirm/improve ID?" yes / no
