### ISSUE TITLE
Change definition of verifiable from research_grade_candidate? to quality_grade = (needs_id || research)

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#853]
Currently we define verifiable as research_grade_candidate?
https://github.com/inaturalist/inaturalist/blob/master/app/models/observation.rb#L1140

which differs subtly from the union of quality grades research and needs_id
https://github.com/inaturalist/inaturalist/blob/master/app/models/observation.rb#L1179

improvement proposal is to change the definition of verifiable to be quality_grade = (needs_id || research)
so that verifiable doesn't include the set of casual observations with research_grade_candidate?=true but voted_out_of_needs_id?=true

I had earlier interpreted this as a bug (rather than an intentional definition of verifiable) in this issue which I'm closing
https://github.com/inaturalist/inaturalist/issues/842

**Comment by pleary** [comment]
I think this is ready. The node and rails code is updated and on staging http://staging.inaturalist.org/observations?verifiable=true&quality_grade=casual

**Comment by pleary** [comment]
these changed have been deployed
