### ISSUE TITLE
Captive observations candidates for research grade

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#854]
captive observations should !passes_quality_metric?(QualityMetric::WILD)
https://github.com/inaturalist/inaturalist/blob/master/app/models/observation.rb#L1327
but there are a small set of captive obs that are verifiable
http://www.inaturalist.org/observations?verifiable=false&quality_grade=needs_id
not sure how its happening
such a small number its not a priority - but thought I'd log it

**Comment by pleary** [comment]
I think this is resolved now that we've changed what verifiable means. Can you confirm, @loarie and close if so

**Comment by loarie** [comment]
yeah thanks
