### ISSUE TITLE
Observation Search Persistent States

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#860]
@kueda and I discussed the need for persistent states on the obs search screen. They are as follows:

* Map/Grid/Table view selection would remain persistent. For example, if the user leaves the obs search screen and comes back or refreshes it, it will be in the last view that was selected. I am not sure if how or if you want this true for users who are not signed in. It would be nice if it's for all users, but I think the priority are those who are signed in, if there has to be a priority. 
* The map view (satellite/satellite, labels, terrain)

Note that this is not an explicitly set user preference. The state just remains the way the user last set it.

**Comment by kueda** [comment]
Patrick, assigning you since you mentioned this in kickoff this morning. Note that we have `UserController#update_session` if we're ok with this only persisting until you sign out. Otherwise we can just add user preferences and user `UserController#update` or something.

**Comment by pleary** [comment]
I think this is working as of 875e882, which is on Staging now if people want to try it out. It will update the session for any user even if they're not logged in, and if they are logged in it will save the preferences to the DB for later

**Comment by kueda** [comment]
Works for me. Release!

**Comment by pleary** [comment]
deployed
