### ISSUE TITLE
Aggregator not alerted to people changing project settings

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#861]
Updating your project settings (your Project_User record) should also update your account settings (your User record). its not, and since the aggregator is looking at the Users' record updated_at date to see whether to consider it for aggregation or not, there are observations eligible for aggregation that are not being aggregated.

For example, this one was added 2 days ago http://www.inaturalist.org/observations/2634173 and it didn't qualify for aggregation because the owner tnewman had his project settings to 'you'. Then yesterday he changed his project settings to 'project curators' which should make it elligable for aggregation by project 411 but it hasn't aggregated

Project.find(411).aggregate_observations seems to think there are no unaggregated elegible obs

**Comment by pleary** [comment]
This should be fixed in a1c1950
