### ISSUE TITLE
search tab showing wrong relative time

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/inaturalist#864]
I made this observation at 5:30pm pacific. at the time of the attached screenshot, it was 9:15pm pacific.
My account timezone is set to GMT-08:00 Pacific Time.

![pasted image at 2016_02_07 09_15 pm](https://cloud.githubusercontent.com/assets/515947/12879794/cc32e53c-cded-11e5-8964-5c8bab9209df.png)

**Comment by pleary** [comment]
I did find a bug here and fixed it. But I want to note something that's been bugging me and see what people think. We show relative times on the map view and the grid view. The map view's relative times are when the obs was added, but the grid view's relative times are when the obs was observed. The default sort of observation is by time added, so if you just go to http://www.inaturalist.org/observations and tap the grid view the relative times are all over the place:
<img width="956" alt="screen shot 2016-03-01 at 6 39 25 pm" src="https://cloud.githubusercontent.com/assets/48566/13445885/03ba64d4-dfdd-11e5-95e5-34d28ccfa8f6.png">

This is the reason why I don't like the shortened relative times in the grid view - they can be very different and it takes me a second to figure out the abbreviations. Should we make it so the relative times on the map and grid view are referring to the same field?
