### ISSUE TITLE
infowindows on obs search don't show translated common name

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#870]
...even though the snippet does, e.g. http://www.inaturalist.org/observations?place_id=10870&quality_grade=research&locale=it

![screen shot 2016-02-10 at 3 29 17 pm](https://cloud.githubusercontent.com/assets/22691/12965451/2ba84b46-d00b-11e5-95c0-443eac3c4944.png)

**Comment by pleary** [comment]
the Rails part of the fix is 23e6388 and the API part in inaturalist/iNaturalistAPI@28ac5040 . I'll update the production API servers then this is ready for deploy. It's running on Staging now
