### ISSUE TITLE
Observation Search Screen Remove "Near"

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#871]
In user testing it has come up that the word "Near" before the location field is confusing. When  searching a place like "California" users thought they would see observations NEAR California not IN California. Before we had the word "In" which is also deceiving if you entered an address because usually folks don't want to see observations limited to an address. 

I recommend removing the word "Near" and putting nothing in its place. I think it is pretty understood that typing in an address or location will render search results filtered to that area. However, I'm open to suggestions. 

If we do remove it, there will need to be less space between the two fields.

**Comment by joellebel** [comment]
Also, in reference to issue https://github.com/inaturalist/inaturalist/issues/895 we should probably change the word "Place" in the location text field to "Location" since it is technically not a "Place" with respect to iNat places.

**Comment by pleary** [comment]
Done and on Staging for testing

**Comment by joellebel** [comment]
Looking good. If it isn't too time consuming can we make the space between the two text fields the same as the space between the location field and the "Go" button. For reference, this is the desired space... 
![image](https://cloud.githubusercontent.com/assets/11527994/13446224/7f931432-dfc6-11e5-8134-d910dba0c5d4.png)

I just don't want folks to think the location field is mandatory. Plus, it's better for consistency.

**Comment by pleary** [comment]
"Near" is gone and I fixed up the spacing
