### ISSUE TITLE
Enable project aggregator for all BioBlitzes

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#874]
currently this is enabled for curators only

This was originally discussed here #819

**Comment by pleary** [comment]
On staging for testing. The aggregator options are shown on the project edit page after the project has been saved as a bioblitz project

**Comment by loarie** [comment]
Ok - I can confirm this works for non-curators. 2 questions:

1) when we role this out, all existing bioblitzes will suddenly have blank leaderboards. Rather than turn on the aggregator for this, I suggest we make a blog post with a clear explanation of these changes that explains how folks can turn the aggregator on for their past BioBlitzes. Sound good?

2) definitely clunky that you have to create the bioblitz project, save it, and the go back to the edit screen to turn on the aggregator - I foresee confusion here. But maybe we should hold off on that and start with nice tutorials rather than UX changes?

**Comment by pleary** [comment]
1) Totally up to you. We could possibly turn the aggregator on for all existing bioblitzes too. We might want to have the aggregator check if the BioBlitz is finished and then maybe not run it on finished bioblitz projects. Whatever works best for users

2) I fixed up the edit page and it now uses jQuery to hide and show the aggregator stuff based on the project type
