### ISSUE TITLE
Add must be verifiable rule

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#876]
Include this as a project rule and have the inclusion of verifiable=any in links to obs-search from projects consider presence/absence of this rule

This was originally discussed here #819

**Comment by pleary** [comment]
I think this is all set. There is a verifiable rule, and the links from project show to the obs search set both place_id and verifiable to any (unless otherwise set by the project rules) to override any default values

**Comment by loarie** [comment]
great - only thing I noticed is that obs search with a verifiable=true param is not properly checking the box in the filters menu (as it properly does when there's no verifiable param)
<img width="1057" alt="screen shot 2016-02-19 at 1 26 57 pm" src="https://cloud.githubusercontent.com/assets/598026/13189504/afa29ade-d70c-11e5-9f7d-176dd83afc9c.png">

**Comment by naturalistcharlie** [comment]
wow, you have a lot of unread messages!!!

On Fri, Feb 19, 2016 at 4:29 PM, Scott Loarie <notifications@github.com>
wrote:

> great - only thing I noticed is that obs search with a verifiable=true
> param is not properly checking the box in the filters menu (as it properly
> does when there's no verifiable param)
> [image: screen shot 2016-02-19 at 1 26 57 pm]
> <https://cloud.githubusercontent.com/assets/598026/13189504/afa29ade-d70c-11e5-9f7d-176dd83afc9c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/876#issuecomment-186414991>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by loarie** [comment]
believe it or not they are all 'thank you' type emails that close out back and forth conversations which I get in my inbox, but don't bother to click through to on iNat - it is embarrasing how they accumulate

**Comment by naturalistcharlie** [comment]
as i said in a recent ficus thread, i'm not judging :)  But yeah... my iNat
mailbox isn't like that but I have other ones that are.

On Fri, Feb 19, 2016 at 4:42 PM, Scott Loarie <notifications@github.com>
wrote:

> believe it or not they are all 'thank you' type emails that close out back
> and forth conversations which I get in my inbox, but don't bother to click
> through to on iNat - it is embarrasing how they accumulate
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/876#issuecomment-186419532>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont

**Comment by pleary** [comment]
I fixed that obs search URL to do the right thing for verifiable=true. So I think this is closable
