### ISSUE TITLE
Add leaves filter to taxon count in projects

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#877]
To achieve primary goal of consistent stats across projects and observation-search views

Discussed potential later on of (a) altering leaves algorithm, (b) switching to strict species count, (c) making this configurable. But for now decided to wait for more feedback/complaints/praise from community on leaves approach (as currently implemented in obs search)

This was originally discussed here #819

**Comment by pleary** [comment]
What are the requirements for this ticket? Project stats show users with the "Most Species" and the taxa "Most Observed Species". Do we want each of these to use leaves? Does this apply to all projects?

I took a look at an improved leaves approach and I can get it to count a taxon as it's species if the taxon is below species. We'll just need to reindex observations again

**Comment by loarie** [comment]
for the projects - my main goal is consistency with obs search
So just the Species total and Most Species which would be equiv to the Species stat on Obs Search and the first 5 entries on the Species tab

I'm working under the assumption that the leaderboards (Most Species on the Project page and the Observers equiv on the Obs Search page) can't count leaves efficiently - and that we are sticking with just species there.

Interesting about the leaves with a species floor. Would be neat to see, but prob not worth an index just for that - you indexing for anything else soon?

**Comment by pleary** [comment]
I updates the stats to use some angular code, and with that it's all running on the new API and the species counts are leaf counts. Its also all linked into the new obs search. Does that look OK?
