### ISSUE TITLE
Explore not_suitable filter

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#878]
Explore whether adding a 'not' wrapper to elastic search params would make it simple to proceed with a 'not_suitable' filter for the use case of removing observations from a project. If more complex than that probably not worth it.

This was originally discussed here #819

**Comment by pleary** [comment]
This is working in the API right now. I still need to allow the params into obs search. But, how will this work: http://staging.inaturalist.org:4000/observations?not_matching_project_rules_for=herps-of-texas&project_id=herps-of-texas ?

not_matching_project_rules_for just applies the inverse of the project rules, then you can apply any other params on top of that. I assume it would usually be combined with project_id

**Comment by loarie** [comment]
Ok - this seems to be working well - making me want a 'remove all unsuitable obs' button as I see how many obs in some of my projects are not suitable - but not necessary because those who care can do it manually

**Comment by pleary** [comment]
Closing since this seems resolved. Let me know if we need a link or button anywhere that links to this URL
