### ISSUE TITLE
Last aggregated timestamp

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#879]
Display last aggregated at timestamp on  projects/edit so project owners know when the aggregtor last ran.

This was originally discussed here #819

Also discussed a variety of ways to make the aggregator more robust (e.g. separate delayed jobs) and better error catching

**Comment by pleary** [comment]
On staging for testing. I just plopped in the date in the aggregation block. Easy to move it around or change the style if needed

**Comment by loarie** [comment]
Cool - looks fine - seems like maybe it shouldn't be in a field that looks editable but i don't have strong feelings about the styling.

But as for functionality, I  went to http://staging.inaturalist.org/projects/woodpecker-week-jan-10-16/edit and the 'last aggregated at' field was populated. Then I altered some project settings (changed some observation rules) and resaved and the last aggregated at field is cleared (which makes sense) but its been about 20 min and its still blank - any ideas if its actually aggregating?

**Comment by pleary** [comment]
the aggregator doesn't run on Staging. You'd have to run it for that project in a console. We do reset the last_aggregated at since we'll want to force aggregation after various changes, so I can see how that would be confusing. We'd need an additional field to both keep track of when the aggregator actually last ran, and some indicator of when it needs to run again

**Comment by loarie** [comment]
got it thanks - I'll run it from console to simulate the aggregator

**Comment by loarie** [comment]
I ran the aggregator in console and the field responded properly so seems to be working

**Comment by loarie** [comment]
it does look like altering the times is not reseting the last_aggregated field (and so I assume not forcing aggregation?) - it should do since these times are essentially project rules right?

**Comment by pleary** [comment]
pretty sure this is fixed now. I changed the display of the time on the edit page so it doesn't look editable, and it also only shows when the aggregation box is checked. The last_aggregated_at should also be reset when the start and end times change
