### ISSUE TITLE
Higher quality images in _stats.json calls

### ISSUE THREAD

**Issue by amitai52** [inaturalist/inaturalist#881]
Please include urls of higher quality user / taxa images in the following calls:
/observations/user_stats.json
/observations/taxa_stats.json

Thanks
Dan

**Comment by kueda** [comment]
We have a new version of our API that we're working on documenting right now, but it includes these higher res image URLs, e.g.

http://api.inaturalist.org/observations/observers?place_id=6815
http://api.inaturalist.org/observations/species_counts?place_id=6815

I'll try and leave a comment here when it's documented, but it should work right now. For user stats, you can always just modify the URL to get a larger version, e.g. http://www.inaturalist.org/attachments/users/icons/1-thumb.jpg to http://www.inaturalist.org/attachments/users/icons/1-medium.jpg

**Comment by kueda** [comment]
K, newer API documentation is up at http://api.inaturalist.org/v1/docs/.
