### ISSUE TITLE
wrong projects list for user

### ISSUE THREAD

**Issue by amitai52** [inaturalist/inaturalist#883]
After I join/leave the project via the web, the data about joined projects is not reflected on the API on Android.
I.e. API endpoint /projects/user/:login.json for joined projects returns old list of projects.
In order to reset the cache, the user has to logout and then sign back in again. This does cause the correct list of projects to appear.

**Comment by kueda** [comment]
I cannot replicate this using these steps:

1. Go to http://www.inaturalist.org/projects/user/kueda.json
1. Leave a project that is in that response using the website
1. Go back to http://www.inaturalist.org/projects/user/kueda.json and the project is no longer there

If you can provide a list of steps that can consistently reproduce this issue, please re-open.
