### ISSUE TITLE
API calls rejected with bearer token

### ISSUE THREAD

**Issue by amitai52** [inaturalist/inaturalist#884]
The following API calls will fail with Bearer token:
GET /projects/:id/members
POST /comments
POST /identifications
POST /observations

error we get is:
`{ "error": "You need to sign in or sign up before continuing."}`

we see that on Android they work because they are made with Basic Auth instead.
We tried that too, and then the command works fine

Can we have those work for bearer token? we'd like to avoid basic auth over the web and be uniform using bearer-token for all calls.

**Comment by kueda** [comment]
I'm definitely seeing a problem with `GET /projects/:id/members`, but not with the others. Can you try POSTing to endpoints like `https://www.inaturalist.org/comments.json` instead of `https://www.inaturalist.org/comments`?

**Comment by kueda** [comment]
K, that fix is live. If you can provide steps to reproduce the problems I couldn't reproduce, please re-open.
