### ISSUE TITLE
search obs with 1 object

### ISSUE THREAD

**Issue by amitai52** [inaturalist/inaturalist#885]
obs search via GET /observations.json with query params
usually returns a JSON array with the objects
when query yields only 1 result, it returns the object directly

we think it should return the array with a single object inside so the JSON data structure doesn't change when it deprecates to 1 object

**Comment by kueda** [comment]
Need more context here. What's the actual URL you're querying, what are the parameters, etc. When I request http://www.inaturalist.org/observations.json?taxon_id=106718&user_id=kueda, which has one result, it's an array, and when I request http://www.inaturalist.org/observations.json?taxon_id=106718, there are two results, also in an array.

**Comment by kueda** [comment]
Please re-open if you can provide the requested info.
