### ISSUE TITLE
prevent journals from inserting <br> tabs

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#886]
I'm noticing that saving a journal post embeds some `<br>` tags in my embedded html which is screwing up the formatting:
https://www.inaturalist.org/projects/test-project-of-unfathomable-awesomeness/journal/5377-week-in-review-jan-31-feb-6-2016

Anyway to prevent the journal posts from doing this?

**Comment by kueda** [comment]
We do some very simple formatting to replace line breaks in text with `<br>` so when people write something like

```
i am the very model
of a modern major general
```

they don't end up with

I am the very model of a modern major general

So a quick fix you can do is to remove newlines in your post body. We could also add a "formatting" option for posts, and have it default to "Simple" which inserts line breaks and autolinks URLs and the like, or "None" which just leaves the HTML to you. Preference?

**Comment by loarie** [comment]
thanks that makes sense. I'll just remove the newlines

**Comment by loarie** [comment]
Hmm - but why still not working with no linebreaks: https://www.inaturalist.org/projects/test-project-of-unfathomable-awesomeness/journal/5377-week-in-review-jan-31-feb-6-2016, here's the html:
<div style="background: #fbe6db;height: 70px;"><div><div style="height: 75px;"><div style="border-left: 1px solid #fff;width: 16.66666667%;float: left;position: relative;min-height: 1px;padding-right: 15px;padding-left: 15px;"><div style="margin: 15px 0;margin-left: -15px;padding-left: 15px;"><div style="color: #e56c25;font-size: 21px;line-height: 20px;font-family: Whitney,'Trebuchet MS',Arial,sans-serif;font-weight: 100;">37,819</div><div style="font-family: Whitney,'Trebuchet MS',Arial,sans-serif;font-size: 20px;line-height: 25px;text-transform: uppercase;padding-bottom: 5px;letter-spacing: .0em;color: #515151;font-size: 14px;position: relative;">Observations</div></div></div><div style="border-left: 1px solid #fff;width: 16.66666667%;float: left;position: relative;min-height: 1px;padding-right: 15px;padding-left: 15px;"><div style="margin: 15px 0;margin-left: -15px;padding-left: 15px;"><div style="color: #e56c25;font-size: 21px;line-height: 20px;font-family: Whitney,'Trebuchet MS',Arial,sans-serif;font-weight: 100;">37,819</div><div style="font-family: Whitney,'Trebuchet MS',Arial,sans-serif;font-size: 20px;line-height: 25px;text-transform: uppercase;padding-bottom: 5px;letter-spacing: .0em;color: #515151;font-size: 14px;position: relative;">Species</div></div></div><div style="border-left: 1px solid #fff;width: 16.66666667%;float: left;position: relative;min-height: 1px;padding-right: 15px;padding-left: 15px;"><div style="margin: 15px 0;margin-left: -15px;padding-left: 15px;"><div style="color: #e56c25;font-size: 21px;line-height: 20px;font-family: Whitney,'Trebuchet MS',Arial,sans-serif;font-weight: 100;">37,819</div><div style="font-family: Whitney,'Trebuchet MS',Arial,sans-serif;font-size: 20px;line-height: 25px;text-transform: uppercase;padding-bottom: 5px;letter-spacing: .0em;color: #515151;font-size: 14px;position: relative;">Identifiers</div></div></div><div style="border-left: 1px solid #fff;width: 16.66666667%;float: left;position: relative;min-height: 1px;padding-right: 15px;padding-left: 15px;"><div style="margin: 15px 0;margin-left: -15px;padding-left: 15px;"><div style="color: #e56c25;font-size: 21px;line-height: 20px;font-family: Whitney,'Trebuchet MS',Arial,sans-serif;font-weight: 100;">37,819</div><div style="font-family: Whitney,'Trebuchet MS',Arial,sans-serif;font-size: 20px;line-height: 25px;text-transform: uppercase;padding-bottom: 5px;letter-spacing: .0em;color: #515151;font-size: 14px;position: relative;">Observers</div></div></div></div></div></div>
