### ISSUE TITLE
Observation with Overflow of Species Tags:

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/inaturalist#889]
Something is clearly going on here, looks like a bug, the person who created the observation then made a dozen or so 'Dicots' IDs.

http://www.inaturalist.org/observations/2102844

Not sure what was going on, I guess it depends on if they did so on the website or app, this may be an iOS bug too, but thought you would want to know about it.

**Comment by alexshepard** [comment]
Looks like it may be a taxon swap gone bad:

https://groups.google.com/forum/m/#!topic/inaturalist/ndk6hlhovPc

**Comment by kueda** [comment]
My attempts to clean up bad data as a part of #794 led to more bad data. Will fix.
