### ISSUE TITLE
lingering old boundaries

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#890]
There's a bug where updating a place geom
http://www.inaturalist.org/places/moundville-archaeological-park
<img width="546" alt="screen shot 2016-02-18 at 10 31 04 am" src="https://cloud.githubusercontent.com/assets/598026/13153858/ee1da3cc-d62a-11e5-8483-47ad1b5e83c1.png">
makes changes that are immediately shown on obs-search
<img width="474" alt="screen shot 2016-02-18 at 10 33 29 am" src="https://cloud.githubusercontent.com/assets/598026/13153898/23e97a76-d62b-11e5-87fa-b257df5d1ff4.png">
but sometimes results in persistant old boundaries that display on places/show
<img width="904" alt="screen shot 2016-02-18 at 10 30 58 am" src="https://cloud.githubusercontent.com/assets/598026/13153859/ee20e672-d62a-11e5-9f93-aba1030a3510.png">
and associated projects/show
<img width="755" alt="screen shot 2016-02-18 at 10 33 45 am" src="https://cloud.githubusercontent.com/assets/598026/13153895/21a81736-d62b-11e5-961a-4f296525b6af.png">

Whats the plan here? Should we track down the bug that's not clearing the caches on places/projects or should we just change those maps to display using the obs-search infrastructure? thoughts @pleary @kueda?

**Comment by pleary** [comment]
I think this is a duplicate of #790. Not technically a bug, just a known deficiency. Our Varnish reverse proxy cache logic isn't in any way connected to the tile serving or app logic right now. The new obs search Places of Interest doesn't depend on these tiles, and its results are currently not cached at all, so they should reflect data in real-time

**Comment by loarie** [comment]
ok - I'll close this then. What's the best way to manually refresh the tiles though so I can help out @jcabbott with his launch of http://www.inaturalist.org/projects/moundville-archaeological-park-biodiversity-survey?
