### ISSUE TITLE
Receiving notification on a journal post you were mentioned in

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#891]
Currently, when someone posts a comment to a journal post you were mentioned in, you receive the following notification... 

![image](https://cloud.githubusercontent.com/assets/11527994/13188871/e794b6f6-d708-11e5-8a28-e45effa7ccf3.png)

Here's an example journal post: http://www.inaturalist.org/posts/4917-welcome-wagon#activity_comment_4917

Expected behavior: No notification should be sent to a person mentioned in the post when there is a new comment on that post. However, people should continue to receive notifications when they are mentioned in posts. 

...as discussed with @loarie

**Comment by kueda** [comment]
So if you mention someone in a post, that person keeps getting notifications like this every time people comment on the post?

**Comment by loarie** [comment]
In this particular instance, I was editing the journal post and resaving it. I don't think there's any evidence this is happening with comments

**Comment by kueda** [comment]
I think this was fixed by f7ad7ab996a4302ac8a406ef3ecb851ff702fe77
