### ISSUE TITLE
Observations I've Already IDed Showing Up in ID Please

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/inaturalist#892]
I've noticed that observations that I long ago identified as "dicots" are showing up in my ID Please:

![image](https://cloud.githubusercontent.com/assets/7171475/13207909/e0973678-d8e1-11e5-9bfd-6a8dba209e6e.png)

This is how they loaded, I didn't add the ID today.

i IDed them as Dicots long ago because they were not tagged to any species but I didn't know what they were. I think anything I did that with should be marked as reviewed. Yes it was a while ago and one or two of them perhaps I could figure out now but with 900 pages of plants to review in CA and 300 in Vermont, it seems more worth my time to look at ones I haven't seen yet.

I'm thinking maybe it's a bug, right?

**Comment by carrieseltzer** [comment]
I wonder if this is at all related to #643 where an observation that isn't attached to iNat taxonomy doesn't show any IDs in table view even if it has one (from someone other than the original observer).

**Comment by naturalistcharlie** [comment]
oh, there was also that weird bug where there was a taxon swap with
'dicots' that created a bunch of multiple IDs from people... this could be
related to that too, or both. I think it's a bug rather than a feature.
They should be tagging as already IDed by me but for some reason they
aren't.

Not a huge bother to me right now, but probably worth fixing if a bug.
Here's the URL since I forgot to include it earlier, but of course it will
look different for you because you don't have the same 'reviewed' as me.
http://www.inaturalist.org/observations/id_please?captive=&created_on=&d1=&d2=&day=&filters_open=true&hrank=&iconic_taxa%5B%5D=Plantae&iconic_taxa%5B%5D=unknown&identifications=any&list_id=&lrank=&month=&nelat=&nelng=&order=desc&order_by=observations.id&page=909&place_id=51727&q=&quality_grade=needs_id&rank=&reviewed=false&search_on=&site=&swlat=&swlng=&taxon_id=&taxon_ids%5B%5D=&taxon_name=&tdate=&utf8=%E2%9C%93&view=&year=

On Sun, Feb 21, 2016 at 9:33 PM, carrieseltzer <notifications@github.com>
wrote:

> I wonder if this is at all related to #643
> <https://github.com/inaturalist/inaturalist/issues/643> where an
> observation that isn't attached to iNat taxonomy doesn't show any IDs in
> table view even if it has one (from someone other than the original
> observer).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/892#issuecomment-186973808>
> .
>



-- 
============================
Charlie Hohn
Montpelier, Vermont
