### ISSUE TITLE
Add user_id to places imported by Yahoo

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#894]
Currently, when a user creates a place by importing with Yahoo there is no user_id:
<img width="939" alt="screen shot 2016-02-23 at 2 46 27 pm" src="https://cloud.githubusercontent.com/assets/598026/13269368/4424f90e-da3c-11e5-8a78-ebd4c4c04268.png">

problematic because:
1) without knowing who's responsible for these places hard to engage
for example this one was imported as a point from Yahoo by John Abbot http://www.inaturalist.org/places/university-of-alabama-tuscaloosa-al-us who later added a boundary, but no indication from the place record that John did this

2) since we're using presence/absence of user_id to surface places of interest, this is inadvertantly driving whether places get surfaced or not

**Comment by pleary** [comment]
This should be fixed now
