### ISSUE TITLE
How do user's find their places on obs search?

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#895]
Currently, the only way for someone to find the place they created on obs search is to:
1) manually enter a place_id param in the URL
2) navigate through Place page / observations / View more observations from University of Alabama
both of which are circuitous

Should we embrace this circuitous route or surface these places on obs search by:

A. Add a Place filter in the More Filters section?
Not unlike 'Projects'?
<img width="906" alt="screen shot 2016-02-23 at 2 34 01 pm" src="https://cloud.githubusercontent.com/assets/598026/13269885/42695d50-da3f-11e5-9a59-75d7a91447c8.png">

B. Surface them in Places of Interest?
I had envisioned the Community Curated section in Places of Interest of showing user created places. Currently, it is not - its showing non-standard places without user_ids which are either:
1. places created by iNat (which should IMO be standard)
2. places created by users using the import from Yahoo tool which isn't recording user_id (which IMO shouldn't happen #894)
3. (I think) places created by users before iNat had a user_id column on the place model

Patrick raises the point that since this list is limited to a truncated set of entries, it might not be a reliable alternative to A above.

But IMO in its current form it is confusing and misleading by only showing places with user_id = nil which (as I argue above) is a pretty meaningless subset.

I'd prefer to either remove the user_id = nil constraint here and show the truncated set of all relevant non-standard places. Or remove this right hand section of the places of interest box all together
<img width="527" alt="screen shot 2016-02-23 at 2 28 56 pm" src="https://cloud.githubusercontent.com/assets/598026/13270014/2554d27a-da40-11e5-8dd7-fd60c45340d0.png">

Thoughts?

I guess my preference would be: 
1. build the Places filter in More filters
2. also remove the user_id = nil constraint from Places of Interest

**Comment by pleary** [comment]
If we want to replace the user_id = nil restriction from Community Curated places then obviously more places will show up, so we should all agree that the change is more positive than negative. In my opinion, I'm not sure it is a net positive. It's meant to be Community **Curated**, not Community **Created**, so if we allow everything I'm not sure where the curation comes into play.

Here's just one example, but ideally everyone on the team takes a look and chimes in. I have Staging not applying the user_id = nil rule:

http://staging.inaturalist.org/observations?place_id=14
<img width="485" alt="screen shot 2016-03-01 at 3 00 46 pm" src="https://cloud.githubusercontent.com/assets/48566/13440283/4f02ad52-dfbf-11e5-90ea-bd9786d7e119.png">

http://www.inaturalist.org/observations?place_id=14
<img width="492" alt="screen shot 2016-03-01 at 3 00 51 pm" src="https://cloud.githubusercontent.com/assets/48566/13440295/5a9a5016-dfbf-11e5-8f52-95982f07ad7e.png">

I do like an explicit iNat place search as that's the only way to guarantee any place can be found. I'll look into implementing that in the new obs search

**Comment by loarie** [comment]
I agree with you that an explicit iNat place search in Obs search is the only way we can guarantee any place can be found so we prob should do that.

Re: Community Curated section of Nearby places

my main beef is that we're labeling that section Community Curated when thats not what it represents. Its the collection of places:
1. created by iNat (which should IMO be standard)
2. created by users using the import from Yahoo tool which isn't recording user_id (which IMO shouldn't happen #894)
3. (I think) places created by users before iNat had a user_id column on the place model

I'm fine with any of the three (my most preferred at the top):

1) remove  user_id = nil restriction
2) remove the section entirely (so it only shows standard)
3) renaming 'community curated' to something more accurate like - 'created by unknown user' (but again begs the question why we'd want to show that stuff)

**Comment by pleary** [comment]
what about another option, which is some real curation of places. Maybe they all start curated or non-curated (regardless of user_id). And there is some mechanism for curators to promote (or demote) places for this list. i.e we add a new field to places that we use and don't user user_id ?

**Comment by kueda** [comment]
Is there a functional problem with removing the user_id restriction, i.e. not a problem with the accuracy of the label but with the results returned? To me what's on staging right now (no user_id restriction) is functionally just fine: I seem to be able to find as many places as I could with the restriction. The label "Community Curated" is slightly inaccurate but not a big deal to me. I'd be happy with "Other".

My vote is to remove user_id = nil restriction and add an explicit place selector. I don't want to remove the "Community Curated" places from nearby places, I actually think that's useful.

**Comment by loarie** [comment]
I like Patricks suggestion - but sounds like a separate issue/future feature.

Assuming no functional problem I second  Ken-ichi's vote (remove user_id = nil restriction and add an explicit place selector)

 I don't mind the term 'Community curated' because in theory all of those places can be edited by site curators. 

But I just realized that standard places can also be edited by site curators - wasn't aware of that and that might be something we want to disable:
<img width="829" alt="screen shot 2016-03-01 at 12 39 17 pm" src="https://cloud.githubusercontent.com/assets/598026/13441140/a2c8b612-dfaa-11e5-9432-b2ede2cd5cc1.png">

**Comment by joellebel** [comment]
I like the idea of a places filter in the More Filters section with a way to limit it to user-generated, iNat places or all since it's inherently different than the "location" field.

I also like having the "Community Curated" column because things like local open spaces show up there that I wouldn't see in the Standard column, so I guess I'm all for removing the restriction.

**Comment by joellebel** [comment]
Just a note that I revised my comment above.

**Comment by pleary** [comment]
I think this is done now. Places of Interest now include all places, even those with user_ids. We also have a place autocomplete under "more filters". The filters menu is getting a little tall, and I know we have more we want to add to it #873 , but that's a separate matter.
