### ISSUE TITLE
Observation Search View Button Recommendation

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#897]
Map view is the default view and the first view many folks see. It has come up in user testing that folks are missing the view buttons. This is probably because there is so much going on with the map.

I am making a UX recommendation to add labels to these buttons for better usability. 

![image](https://cloud.githubusercontent.com/assets/11527994/13307426/03957302-db20-11e5-9765-bbbb0ab089bd.png)

**Comment by joellebel** [comment]
...just a heads up the font size of the labels will need some adjusting, but the above mock up is just to give you an idea.

**Comment by pleary** [comment]
this went out too. Didn't see the second note about text size. How does it look?

**Comment by joellebel** [comment]
@pleary This looks great. One minor thing and if it's time consuming, we can forget about it...

It would fabulous if the labels vertically lined up with the icons. The labels are slightly too high on all browsers, so hopefully that means no customization for certain browsers:

Chrome:
![image](https://cloud.githubusercontent.com/assets/11527994/13763506/eb181d00-ea03-11e5-9aff-05b162ed94f9.png)

FF:
![image](https://cloud.githubusercontent.com/assets/11527994/13763511/f02ff7d6-ea03-11e5-9f37-c4e9f51cec27.png)

Safari:

![image](https://cloud.githubusercontent.com/assets/11527994/13763519/fdb0859c-ea03-11e5-8a23-c7106aeaaa42.png)


I fiddled with it in the web dev tools and couldn't get it right, so it really may be something difficult. (I think Ken-ichi has mentioned something about icons and labels being tricky) Anyways, if it's something that would take longer than 5min, no worries.

Thanks for taking care of this!

**Comment by pleary** [comment]
the button labels are a little better vertically aligned now
