### ISSUE TITLE
Taxon Swap corrupting community ID

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#903]
Crappy taxon swap aside, something with the swap is corrupting the community ID here
http://www.inaturalist.org/observations/459504
haven't tried to sleuth this further, but before I do does this ring a bell @kueda?

**Comment by kueda** [comment]
For the record, by "corrupting" Scott meant it looked like this:

![screen shot 2016-02-29 at 9 53 56 am](https://cloud.githubusercontent.com/assets/22691/13403554/67415012-deca-11e5-9ce1-e49ab4c9b2b2.png)

I.e. despite the fact that all identifiers agreed on the same apparently genus-level taxon, the community ID was at the family level. However, the taxon they agreed at was *not* a genus. Instead, someone had entered "genero" as the rank, which is not something iNat recognizes when trying to determine the community ID, so instead it looked up the tree to the nearest common ancestor it did recognize, which was the family/

**Comment by loarie** [comment]
got it, thanks - should have sleuthed more before pinging you
