### ISSUE TITLE
Needs ID! page should show initial user's ID not only community ID

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/inaturalist#907]
I was going through some Needs ID! and saw the below observation.
![image](https://cloud.githubusercontent.com/assets/7171475/13413541/511d01b0-df19-11e5-9a7e-44bace648914.png)

I saw that the photo was clearly of an iris. I didn't know the species but since the IDs I saw were already to genus only, I agreed with Ken-Ichi that it is in the Iris genus.

The problem is though that the initial observer later identified it to a species after Ken-Ichi's initial Iris observation. So in me agreeing with Ken-Ichi from within the Needs ID page I was effectively disagreeing with the observer's species level ID even though I did not mean to. I did not see that until i clicked on the observation.

![image](https://cloud.githubusercontent.com/assets/7171475/13413589/ab04b448-df19-11e5-803d-7e188f7a8f80.png)

I guess this page should be modified to show the MOST RECENT ID by the observer, in addition to the community-sponsored ID. Otherwise I have to open them all individually which reduces the value of having that page there.

Incidentally it would also save a lot of time if there was an 'agree?' link on the initial iD.

**Comment by kueda** [comment]
URL please.

**Comment by naturalistcharlie** [comment]
oops, sorry. Here's the filter I was using for Needs ID:

http://www.inaturalist.org/observations/id_please?
captive=&created_on=&d1=&d2=&day=&filters_open=true&hrank=&iconic_taxa%5B%5D=Plantae&iconic_taxa%5B%5D=unknown&identifications=any&list_id=&lrank=&month=&nelat=&nelng=&order=desc&order_by=observations.id&page=1&place_id=4016&q=&quality_grade=needs_id&rank=&reviewed=false&search_on=&site=&swlat=&swlng=&taxon_id=&taxon_ids%5B%5D=&taxon_name=&tdate=&utf8=%E2%9C%93&view=&year=

and this is the observation

http://www.inaturalist.org/observations/1463452

of course if you haven't marked the same things reviewed as me you may not see that observation on that page

**Comment by kueda** [comment]
Sorry, I misunderstood this, thought there was an issue with setting the community ID. Needs ID is getting completely overhauled, so please save your feedback for the new version... if I ever actually get anywhere with it (turning into a nightmare feature).

**Comment by naturalistcharlie** [comment]
Ah, makes sense, I will wait on that then, thanks! :) Good luck with the nightmare slog!
