### ISSUE TITLE
some obs can be private but show 0,0 coordinates

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#914]
http://www.inaturalist.org/observations/2647745

<img width="986" alt="screen shot 2016-03-03 at 3 08 45 pm" src="https://cloud.githubusercontent.com/assets/22691/13512815/daac8e66-e151-11e5-8e5e-6b6f11e0b0ea.png">

Obs has private coordinates.

**Comment by pleary** [comment]
Not happening any more for this observation. I guess I'll close this until we have another example. I tried looking in the DB for various combinations of "private" and other fields, and didn't find any more like this in the short time investigating.
