### ISSUE TITLE
Recent updates: Incorrect message when I've made a project member into a project manager

### ISSUE THREAD

**Issue by simonkingston** [inaturalist/inaturalist#915]
When I have made a project member into a project manager, I get a notification in my Recent updates tab on the iNat home page (http://www.inaturalist.org/home) that says "[Project Name] curators added some of your observations", which is not the correct message.

The subsequent part of the message is correct, saying "[username] is now a manager for [Project Name]"

See attached screen capture.
![addedmanagernotification](https://cloud.githubusercontent.com/assets/6931738/13576843/d45d12a8-e44c-11e5-93da-aa1ccdb1199f.png)

**Comment by pleary** [comment]
This should be fixed now. Does it look OK to you?

**Comment by simonkingston** [comment]
Looks good, Patrick.  Thanks.

Simon


*Simon Kingston*
*Data Ranger*

National Park Service
Natural Resource Stewardship and Science
Inventory & Monitoring Division
1201 Oakridge Drive, Suite 150
Fort Collins, CO 80525

970-225-3551 ph
970-225-3597 fax

iNaturalist profile: http://www.inaturalist.org/users/forester93

*I stand for enthusiastic discovery in myself and others.*
