### ISSUE TITLE
Recent updates: Carriage return line feed HTML code appears in notification

### ISSUE THREAD

**Issue by simonkingston** [inaturalist/inaturalist#916]
On the Recent updates tab of the iNaturalist home page (http://www.inaturalist.org/home), the HTML carriage return line feed code appears in the message.  See attached screen capture.

![recentupdates_carriagereturnlinefeedhtmlcode](https://cloud.githubusercontent.com/assets/6931738/13577017/a5560c2a-e44d-11e5-809b-8ce6298c60b5.png)

**Comment by pleary** [comment]
This should be fixed now. Does it look OK to you?

**Comment by simonkingston** [comment]
Looks good, Patrick.  Thanks.

Simon


*Simon Kingston*
*Data Ranger*

National Park Service
Natural Resource Stewardship and Science
Inventory & Monitoring Division
1201 Oakridge Drive, Suite 150
Fort Collins, CO 80525

970-225-3551 ph
970-225-3597 fax

iNaturalist profile: http://www.inaturalist.org/users/forester93

*I stand for enthusiastic discovery in myself and others.*
