### ISSUE TITLE
Observation Search Filters Button

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#918]
After watching more and more folks either miss this button or not click on it because they thought it was a settings button during the Mclaren Bioblitz meetup, I'm making a recommendation to add the word "Filters". See below mock up...

![image](https://cloud.githubusercontent.com/assets/11527994/13649221/710eaf9e-e5f1-11e5-8d51-9c02273fcf85.png)

**Comment by pleary** [comment]
done

**Comment by joellebel** [comment]
awesome. thanks!
