### ISSUE TITLE
project observation aggregator not updating ProjectUser stats?

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#919]
Or possibly ProjectUser stats aren't getting set when the user joins the project *after* the project has aggregated their observations. Specifically referring to the "0 taxa" and "0 observations" at http://www.inaturalist.org/projects/clarkia-biogeography/contributors/kueda:

<img width="1200" alt="screen shot 2016-03-09 at 5 52 38 pm" src="https://cloud.githubusercontent.com/assets/22691/13656891/cbfb89da-e61f-11e5-834a-3741b46e9b6c.png">

**Comment by pleary** [comment]
This should be fixed now. I have the aggregator updating taxa and observation counts for each project when it's done aggregating. I've also updated the existing counts
