### ISSUE TITLE
Identification Warning for Coarser IDs

### ISSUE THREAD

**Issue by joellebel** [inaturalist/inaturalist#920]
While watching folks at the Mclaren meetup and others it has come up quite often that a beginner nature enthusiast will attempt to ID something at a coarser level than the current ID. They do this accidentally thinking they are helping rather than possibly hindering the ob.

I propose a warning modal that could help remedy this. See below...

![image](https://cloud.githubusercontent.com/assets/11527994/13686502/df6deb56-e6ca-11e5-83cd-b7fe1f71d478.png)

Feel free to wordsmith. As you can see, the user can elect to never see this dialogue again so as not to be disturbed in the future. 

It would also be nice to show a diagram of the level of the current Community of ID and where the user is trying to make their ID, but this sounds like some advanced logic that can be put off until the future.

**Comment by loarie** [comment]
Maybe something like:
"Your coarser ID of Birds implies that disagree with kenvinhinta's finer ID of Great Blue Heron - is this what you meant to do? Learn more about identifications here."

**Comment by joellebel** [comment]
Yes. I like that better! Much more explicit and shorter.

**Comment by naturalistcharlie** [comment]
Great idea. Maybe encourage people to also comment on why they disagree. If
there's a way to do that.

On Thursday, March 10, 2016, joellebel <notifications@github.com> wrote:

> Yes. I like that better! Much more explicit and shorter.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/920#issuecomment-195109410>
> .
>


-- 
Sent from Gmail Mobile

**Comment by loarie** [comment]
any progress on this @pleary - just wondering how to treat it in the tutorials?

**Comment by pleary** [comment]
I put what I have on Staging. The "do not show again" checkbox isn't hooked up to anything right now

**Comment by loarie** [comment]
Looking great!
<img width="988" alt="screen shot 2016-03-31 at 10 03 04 am" src="https://cloud.githubusercontent.com/assets/598026/14183986/cc37d64c-f727-11e5-99cb-6d206619a8cd.png">

**Comment by pleary** [comment]
If we're OK with this I can get this and the project aggregator confirmation #911 code merged into master. Do we want still want the "do not show again" box?

**Comment by pleary** [comment]
If we do still want the "do not show again" checkbox, then I assume that means globally across the site, not just for the one observation. And presumably there would need to be a corresponding option on the users edit page to allow them to turn it back on?

**Comment by kueda** [comment]
IMO yes, we want the "do not show" box, yes it should be global. Not sure there needs to be a way to turn it back on. This is essentially a kind of onboarding, and usually that can't be turned back on, right?

**Comment by joellebel** [comment]
Yes, I think it should be global. 

@pleary You bring up a good point... I don't think this modal needs to be turned back on. However, down the road when we have more extensive onboarding, an onboarding reset switch will be good for new users and users that haven't used the site in awhile.

**Comment by joellebel** [comment]
The modal is looking good to me. I like the separation of the "Learn more about how identifications work" from the first sentence. However, can we add a little &raquo; action in there so it looks like this...

"Learn more about how identifications work »" 

Gracias.

**Comment by pleary** [comment]
The checkbox now works, forever silencing the coarser ID confirmation. I also added the >> to the Learn More link. I think this is ready to go

**Comment by joellebel** [comment]
Tested and working for me.

**Comment by pleary** [comment]
deployed
