### ISSUE TITLE
Limit editability of large places

### ISSUE THREAD

**Issue by pleary** [inaturalist/inaturalist#925]
@loarie : did that validation that  community created places must have areas <= Texas get added?

@pleary : Would be good to know who can do it? can curators, or admins? Also does it affect editing of large places

Would be good to get some requirements here. What restrictions do we want to apply, and to whom?

**Comment by loarie** [comment]
'must be site admin' would be most restrictive, 'must be site curator' would be less restrictive. It should be one of the two. I don't feel strongly about which.

**Comment by pleary** [comment]
In #925 I made it so place geometries will not save if their area is greater than 1million square km, or about the size of Ethiopia, a little larger than Texas. Users will get an error "Place geometry is too large to import". The place itself will save, but the geometry will not. Does this seem reasonable?

**Comment by pleary** [comment]
deployed
