### ISSUE TITLE
return existing project observations in response to POST /project_observations.json

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#928]
This is kind of a bug and a proposal for discussion: we currently have a problem in which clients like the apps can make a project observation locally, POST that data to `/project_observations.json`, and get get a 422 because that observation was already added to the project by the aggregator, i.e. the aggregator added the observation to the project in the time between when it was POSTed from the client and when the client POSTed the project observation. Maybe the aggregator just happened to be aggregating for that project at that moment, maybe the client hit another error between obs and project obs upload and the user just didn't bother with it for hours / days. Just had one support request that I think is due to this, and I'm guessing this is becoming more of a problem now that we're using the aggregator so much more.

My proposed solution: have `POST /project_observations.json` return an existing project observation for that project / observation combination instead of a duplicate record validation. Pro: deals with the problem for all clients in a single place. Con: totally unReSTful (right?). Thoughts, @pleary, @alexshepard, @budowski?

**Comment by budowski** [comment]
@kueda - Looks good on my end.
Currently, if that endpoint would be changed to return the existing project observation instead of an error, it should be handled gracefully by the app.

**Comment by pleary** [comment]
While looking at this more closely, I noticed that the website uses `ProjectsController::add` to create project observations, which seems pretty much the same as `ProjectObservationsController::create`, and add is not listed on https://www.inaturalist.org/pages/api+reference

My thoughts are, I agree with your pros and cons. Ideally there would be some simple GET method so the client could check if they wanted. I'd be OK with the proposal
