### ISSUE TITLE
mobile naturewatch.org.nz footer links to wrong iOS app

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/inaturalist#941]
Navigate to naturewatch.org.nz on your mobile device. Tap the link in the footer. It tries to take you to http://itunes.apple.com/nz/app/naturewatch-nz/id556791608?mt=8 which is the old NatureWatch NZ app. Since that app isn't in the app store anymore (we're just distributing the iNaturalist app), you get a notice that the app is not available from the iOS app store app.

Do the same on your desktop browser, and you get taken to https://itunes.apple.com/us/app/inaturalist/id421397028?mt=8 which is the correct link and points to the iNaturalist iOS app.

I looked at the NatureWatchNZ site config but I couldn't figure out what was wrong.

**Comment by pleary** [comment]
I think this is fixed now. Nice catch!
