### ISSUE TITLE
Failed to upload image using POST /observation_photos

### ISSUE THREAD

**Issue by Keda87** [inaturalist/inaturalist#943]
Hi I'm developing android application using iNaturalist API.
I've got a problem when I uploading image for an observation, these are step by step my android logic using iNaturalist API.

I sent 3 request sequentially:
- POST /observations (Success)
- POST /project_observations (Success)
- POST /observation_photos (Failed)

Here is the error response from my third request once uploading photo:
 `{"errors":"Observation hasn't been added to iNaturalist.org"}`

I'm sure that I have put valid observation ID, because I get the ID from my first API call response and the second request also sent successfully that also require observation id.

**Comment by Keda87** [comment]
I found some clue on my android debug message.
`Response{protocol=http/1.1, code=422, message=Unprocessable Entity, url=https://www.inaturalist.org/observation_photos.json}`
but I don't have any idea with the error message.

**Comment by kueda** [comment]
Can you post the entire HTTP POST request you're making, including all headers and the POST body?

**Comment by Keda87** [comment]
Here is the success callback after submitting observation. I sent 2 paraller request for registering to project and post the image.
```
@Override
protected void onPostExecute(ObservationResponse observation) {
        if (observation == null) {
            BusProvider.getInstance().post(Helper.Constant.ERROR);
        } else {
            if (Helper.isConnected(context)) {
                String observationId = String.valueOf(observation.observationId);  // Observation ID.

                // Register observation to project.
                Map<String, String> payload = new HashMap<>();
                payload.put("project_observation[observation_id]",  observationId);
                payload.put("project_observation[project_id]",      context.getResources().getString(R.string.project_id));
                new CreateProjectObservationTask(context).execute(payload);

                // Upload photo for new added observation.
                File photo = new File(imageLocation);  // Observation Image.
                RequestBody requestFile = RequestBody.create(MediaType.parse("multipart/form-data"), photo);
                MultipartBody.Part body = MultipartBody.Part.createFormData("file", photo.getName(), requestFile);
                new ImageUploadTask(context).execute(observationId, body);
            } else  {
                BusProvider.getInstance().post(Helper.Constant.ERROR);
            }
        }
    }
```

Here is my task class for uploading the image.
```
public class ImageUploadTask extends AsyncTask<Object, Void, ImageResponse> {

    private static final String TAG = ImageUploadTask.class.getSimpleName();
    private Context context;

    public ImageUploadTask(Context context) {
        this.context = context;
    }

    @Override
    protected ImageResponse doInBackground(Object... params) {
        InatService service = ServiceGenerator.createService(InatService.class);
        try {
            Response<ImageResponse> response = service.iNatObservationPhoto(
                Helper.getToken(context),
                (String) params[0],             // Observation ID
                (MultipartBody.Part) params[1]  // Image
            ).execute();

            if (response.isSuccessful()) {
                return response.body();
            } else {
                Log.d(TAG, response.errorBody().string());
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    @Override
    protected void onPostExecute(ImageResponse imageResponse) {
        if (imageResponse != null) {
            Log.i(TAG, "Image successfully uploaded");
        } else {
            Log.i(TAG, "Failed to upload observation image");
        }
    }
}
```

I'm using retrofit2 for my http library, and here is my snippet
```
// My constants
public static final String BASE_URL = "https://www.inaturalist.org";
public static final String CREATE_PROJECT_OBSERVATIONS = BASE_URL + "/project_observations.json";

@Multipart
@POST(InatURL.OBSERVATION_PHOTO)
Call<ImageResponse> iNatObservationPhoto(@Header("Authorization") String token,
                                             @Part("observation_photo[observation_id]") String observationId,
                                             @Part MultipartBody.Part file);
```

and I only put `Authorization` header on my request

**Comment by Keda87** [comment]
Hi, is there any update about this?

I'm trying to read the backend source code, I found this line https://github.com/inaturalist/inaturalist/blob/master/app/controllers/observation_photos_controller.rb#L31
I guess that may error produced coming from. But I don't know ruby I don't know why this error occured.

**Comment by kueda** [comment]
That's where the error is coming from, but the only reason it would be generated is if you were submitting an observation photo for an observation that doesn't exist yet. That's why I asked to see the actual text of your HTTP request, not the code that generates it, so I can see the actual values that you are submitting and verify that the `observation_photo[observation_id]` param corresponds to a real observation in our system. Looking at your code it *seems* like you're constructing the request correctly, but I can't help you any further without know what you are actually sending us.

**Comment by Keda87** [comment]
I'm not sure with the error, but I'm sure that the observation response was correct. because on success callback. I'm successfully post data to  `/project_observations` which is the `observation_id` is required on here.

Do you have any documentation to run inaturalist on local machine, I'm trying to debug it on my laptop.

**Comment by Keda87** [comment]
Hi @kueda , probably the issue caused by my android library. I have trying with another library and work fine. You can close my issue.
