### ISSUE TITLE
API: User observations that belong to a project

### ISSUE THREAD

**Issue by kgarsuta** [inaturalist/inaturalist#951]
There is currently no parameter that enables filtering of a user's observations in a given project (i.e. a user's observations that belong to given project). Is it possible to add this?

If this already exists, is it possible to provide some documentation? I was unable to find any at https://www.inaturalist.org/pages/api+reference

Perhaps something like: http://www.inaturalist.org/observations/katieg628.json&project=projectslug

**Comment by pleary** [comment]
You can use a URL like this (not in that documentation):
http://www.inaturalist.org/observations/katieg628.json?projects[]=projectslug

If you're interested, we're starting to use a new read-only API that has an observation search method with improved documentation, and should be a little faster: http://api.inaturalist.org/v1/docs/#!/Observations/get_observations

**Comment by pleary** [comment]
This would be a way to query observations by project with the newer API http://api.inaturalist.org/v1/observations?user_id=katieg628&project_id=iseahorse

**Comment by kgarsuta** [comment]
Thanks a lot @pleary 

I will definitely look in to the newer API as well
