### ISSUE TITLE
move user images to s3 and support larger file sizes

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#955]
S3 is pretty self-explanatory. The only larger size that we really need right now is `500x500>`, so I guess that could be `large`. Both changes will necessitate re-processing all our images, so maybe they can be done at once.

**Comment by kueda** [comment]
Just re-discovering this. This would theoretically break the obs widget for all people still using it, and anyone else deep-linking to our user images. @budowski and @alexshepard, does that include our apps?

**Comment by budowski** [comment]
@kueda - do you mean if the app somewhere saves old image URLs and does not update them?

**Comment by kueda** [comment]
Yeah, but only the user profile image.

**Comment by budowski** [comment]
OK, got it - the Android app doesn't have any of those kind of user-image references.

**Comment by pleary** [comment]
This would help on the server end. The NFS server hosting these images frequently runs low on space (at least once a month when we generate the GBIF export), and this would free up about 11GB. So I'd be interested in seeing this happen

**Comment by kueda** [comment]
Forgot I'd assigned myself. Go for it if you have the time, Patrick.
