### ISSUE TITLE
bootstrapify dashboard and add localized getting started material

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#959]
Designs here: http://thinkmoredesign.com/inat/Getting_Started/home.html#

steps:
1. re-style using Bootstrap layout
2. Replace existing 'getting started' content for new users with dismissable how-to-observe and how-to-follow content
3. Localize content based on user location

**Comment by loarie** [comment]
progress report:
in loarie-dev, mostly done with 1 and 2
re: 3.
a. plan was to use users' ip which we store in users.last_ip
b. realized new user last_ips blank and fixed bug where we were only storing ip on log-in not sign-up
c. tried using geocoder gem to populate new latitude/longitude columns on user using ip address
d. by default <a href="https://github.com/alexreisner/geocoder#ip-address-services">geocoder gem</a> uses https://freegeoip.net/ as DB which has been down all week, geocoder gem compatible alternatives are paid or involve us setting up our own service
e. temporarily hacked in fetching json from freegeoip.net alternative of unknown reliability  directly: http://getcitydetails.geobytes.com/GetCityDetails?fqcn=108.251.105.25
under assumption that  freegeoip.net will come back online and is still a reliable choice
f. realized last_ip mostly populated with load balancer ips, not client ips. Will try replacing request.env['REMOTE_ADDR'] with request.env["HTTP_X_FORWARDED_FOR"] then request.env["HTTP_X_CLUSTER_CLIENT_IP"] 

@pleary/@kueda I'm going to try to finish 1 & 2, before revisiting 3, but any comments on solutions to getting new user's locations and the path I'm exploring?

**Comment by loarie** [comment]
Ok, this is mostly done and on staging and in the loarie-dev branch. Here's how the dismissable panels look
1. on new user on signup using my SF IP-address (The target taxa images aren't loading which I'll investigate):
<img width="1211" alt="screen shot 2016-04-09 at 12 15 05 am" src="https://cloud.githubusercontent.com/assets/598026/14402359/2b8a315a-fde8-11e5-8be6-b59afd650080.png">
2. once there are updates:
<img width="1235" alt="screen shot 2016-04-09 at 12 14 19 am" src="https://cloud.githubusercontent.com/assets/598026/14402360/2d4e10f6-fde8-11e5-897d-da8438b64b38.png">
<img width="417" alt="screen shot 2016-04-09 at 12 22 09 am" src="https://cloud.githubusercontent.com/assets/598026/14402397/561dcb6a-fde9-11e5-857c-a9d83c5b94b4.png">
And I haven't yet touched the actual rendering of the updates (e.g. followings obs, comments and IDs etc) yet, which need some work:
<img width="765" alt="screen shot 2016-04-09 at 12 21 54 am" src="https://cloud.githubusercontent.com/assets/598026/14402392/33a4d8da-fde9-11e5-87ea-ddbfa2b76baa.png">

but other than those, any feedback @joellebel?

@pleary getting last_ip from request.env["HTTP_X_FORWARDED_FOR"] then request.env["HTTP_X_CLUSTER_CLIENT_IP"] seems to now work. But my hack for getting coordinates from the IP might not be very reliable. Would like your feedback on the best approach here.

**Comment by joellebel** [comment]
This is looking great. Here's an alternative to the "You've Got Updates!" panel. Folks tend to read and digest things better in bullet points. 



### Inaturalist updates you when there is activity on the following...

* **Your Observations:** Activity on your observations might include comments, identifications, or faves from the iNaturalist.org community. They also occur when someone adds your observation to a project or annotated it with additional fields. 

* **Following People:** You'll be updated when the people you follow post observations or journal posts.

* **Organisms, Places and Projects:** You can also follow observations of specific organisms and places. Join a project to follow its journal posts.

**Comment by loarie** [comment]
@joellebel, here are examples of the 9 kinds of notifications rendered in the dashboard
mention
<img width="621" alt="screen shot 2016-04-11 at 3 33 02 pm" src="https://cloud.githubusercontent.com/assets/598026/14444505/cdbbd1f4-fffa-11e5-90c6-80708b94e3b9.png">

activity
<img width="656" alt="screen shot 2016-04-11 at 3 32 35 pm" src="https://cloud.githubusercontent.com/assets/598026/14444513/d2cba426-fffa-11e5-8aa9-4598ad8b6118.png">

created_observation(s)
<img width="611" alt="screen shot 2016-04-11 at 3 32 22 pm" src="https://cloud.githubusercontent.com/assets/598026/14444514/d74892ac-fffa-11e5-9ac8-e4f5bc5a4e8e.png">

<img width="615" alt="screen shot 2016-04-11 at 3 32 11 pm" src="https://cloud.githubusercontent.com/assets/598026/14444515/d946324e-fffa-11e5-9d18-3fd2420f4a5b.png">

new_observations (same as created_observations)
<img width="644" alt="screen shot 2016-04-11 at 3 39 46 pm" src="https://cloud.githubusercontent.com/assets/598026/14444648/b8f685d8-fffb-11e5-903b-aa9cc2d617c9.png">

your_observations_added
<img width="632" alt="screen shot 2016-04-11 at 3 32 02 pm" src="https://cloud.githubusercontent.com/assets/598026/14444565/3224f756-fffb-11e5-9a46-a94938bd7b12.png">

curator_change 
<img width="617" alt="screen shot 2016-04-11 at 3 39 58 pm" src="https://cloud.githubusercontent.com/assets/598026/14444647/b6ca0488-fffb-11e5-9b2b-5fff4b300f71.png">

committed
<img width="654" alt="screen shot 2016-04-11 at 3 43 00 pm" src="https://cloud.githubusercontent.com/assets/598026/14444697/1ad163f4-fffc-11e5-9a75-fa583a0818ca.png">

invited
<img width="630" alt="screen shot 2016-04-11 at 3 45 13 pm" src="https://cloud.githubusercontent.com/assets/598026/14444748/6dda0c7c-fffc-11e5-93c0-ffacc9ad1cd9.png">

created_post
<img width="612" alt="screen shot 2016-04-11 at 3 46 44 pm" src="https://cloud.githubusercontent.com/assets/598026/14444767/9de500f2-fffc-11e5-98b3-e7d437e6b133.png">

**Comment by joellebel** [comment]
Lord have mercy on our souls

**Comment by loarie** [comment]
notification designs c/o @joellebel http://thinkmoredesign.com/inat/Dashboard/index.html

**Comment by joellebel** [comment]
# Dashboard Punch List
@loarie 
Here's a final punch list of items.... Let me know if anything is too complicated

- [ ] Move tooltip to be above help icon 
![image](https://cloud.githubusercontent.com/assets/11527994/16064005/6128f6ea-3252-11e6-938e-e8f7bbcf20bb.png)
- [ ] Replace ob timeline snippet with new CSS
- [ ] Replace sub tabs with new CSS
- [ ] Make all taxon colored links same color as body text (rgb 51,51,51)
- [ ] Can we ellipsize the taxon here so it doesn't go to two lines like this... 
![image](https://cloud.githubusercontent.com/assets/11527994/16064337/0590f0fa-3255-11e6-82e5-13755102a1e1.png)

**Comment by joellebel** [comment]
# Latest Punch List

For visual reference see image below...

![image](https://cloud.githubusercontent.com/assets/11527994/16135056/d1928638-33d5-11e6-894d-b1d1514f15c5.png)

- [ ] Add this to the dashboard css stylesheet:

i.glyphicon.glyphicon-map-marker {
	margin-left: -3px;
}
​
.divider_bullet {
color:#888		
}
​
.media-body>ul>li>span>.glyphicon {
	color: #333;
	font-size: 12px;
}
​
.media-body>ul>li, .media-body>ul>li a {
    color: #333;
}
​
 .timeline-body h3 {margin-top: 0}


- [ ] Replace this style...

.label_research_grade {
	padding-left: 10px;
	border-left: 1px solid #ddd;
	padding: .5em .6em .5em .6em;
	background-color: #74ac00;
	font-weight: normal;
	color: white;
	font-size: 12px;
	border-radius: 2px;
}

- [ ] Text replacement for "All Updates" tab:

## Check back here for updates on...
* **Your Content:** Updates will appear here when there is activity on your observations such as comments, identifications, faves or when added to a project.
* **People:** Follow people to better track their latest observations and journal posts.
* **Organisms, Projects & Places:** You can also recieve updates on observations of specific organisms or places by subscribing to them. Join projects to follow their news feeds. Ongoing Conversations You'll be automatically subscribed to content you contribute comments or identifications to. Use the 'Manage your subscriptions' tool to stop recieving updates.


- [ ] Text replacement for this...


Should look like this...
![image](https://cloud.githubusercontent.com/assets/11527994/16135022/a5626510-33d5-11e6-8ddb-db8fb1d510bc.png)
