### ISSUE TITLE
Update project species list

### ISSUE THREAD

**Issue by kgarsuta** [inaturalist/inaturalist#963]
There's some unwanted species on our project list but I can't seem to be able to update the list from the project edit page. Did this go elsewhere? The "Project List" group is empty as shown below.

![project_list](https://cloud.githubusercontent.com/assets/4367787/14517046/1fa635f8-01be-11e6-9b44-53e63dbeb554.PNG)

PS: This is with regards to the "iseahorse" project

**Comment by loarie** [comment]
The project list has always been here http://www.inaturalist.org/lists/84817-iSeahorses-Check-List?rank=species
check that box if you want to display a link to it from http://www.inaturalist.org/projects/iseahorse

**Comment by kgarsuta** [comment]
Thanks @loarie
