### ISSUE TITLE
New user's photos all showing as "forbidden"

### ISSUE THREAD

**Issue by danrademacher** [inaturalist/inaturalist#966]
Here's someone who started blitzing today (including at the McLaren blitz) and for some reason all their pics are failing and breaking their observation pages:
http://www.inaturalist.org/observations/loiscapades

![image](https://cloud.githubusercontent.com/assets/1423200/14584724/a3212e0a-0408-11e6-8207-5282a619f552.png)

![image](https://cloud.githubusercontent.com/assets/1423200/14584728/ab328ff8-0408-11e6-90f4-977506ada064.png)

**Comment by kueda** [comment]
Ugh, bummer. I looked at one and while we have a file at S3, it's not an image file. I suspect something might be weird with her phone. I can tell she was using an old version of Android and what seems like an older phone. @budowski, do you know if the Android app should even work with with SDK 15?

**Comment by kueda** [comment]
Still don't know what happened here, but I'm not sure we can hunt it down without more info.

**Comment by budowski** [comment]
It should work with SDK 15, though it's very old. Very strange bug  indeed. 
What happens when you look at the files in a hex editor? What kind of header does it have?
