### ISSUE TITLE
Portuguese versioning not working

### ISSUE THREAD

**Issue by carrieseltzer** [inaturalist/inaturalist#969]
Neither of these links (which I think should work) are displaying anything in Portuguese on the site. 

http://www.inaturalist.org/observations?locale=pt
http://www.inaturalist.org/observations?locale=pt-br

For comparison, these languages DO work:
http://www.inaturalist.org/observations?locale=es
http://www.inaturalist.org/observations?locale=id (less translated than Brazilian Portuguese).

Changing my account setting did work to display in Portuguese. Am I doing something wrong?

**Comment by loarie** [comment]
its http://www.inaturalist.org/observations/2984852?locale=br-pt
