### ISSUE TITLE
Searching for Taxon ID results in all observations of any taxa being displayed

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/inaturalist#974]
In an attempt to add observations to a project, via clickign on the 'add from my observations', i see the below

http://www.inaturalist.org/observations/charlie?utf8=%E2%9C%93&q=&search_on=&quality_grade=any&reviewed=&geoprivacy=&identifications=any&captive=&place_id=47&swlat=&swlng=&nelat=&nelng=&taxon_name=&taxon_id=&day=&month=&year=&order_by=observations.id&order=desc&rank=&hrank=&lrank=&taxon_ids%5B%5D=47124%2C47132%2C47148%2C47351%2C47362%2C47538%2C47539%2C47570%2C47697%2C47779%2C47892%2C48543%2C49041%2C51741%2C51874%2C54222%2C54763%2C54811%2C55757%2C55847%2C55850%2C55972%2C56031%2C56061%2C57278%2C58727%2C58728%2C59773%2C59778%2C60462%2C61291%2C61321%2C62671%2C63134%2C63337%2C64237%2C64540%2C64694%2C64697%2C69819%2C72187%2C75758%2C77130%2C77131%2C78882%2C79697%2C81599%2C81711%2C84227%2C116710%2C117433%2C119792%2C123638%2C124544%2C125387%2C125472%2C127306%2C129038%2C130228%2C131249%2C158005%2C159836%2C161399%2C163336%2C166636%2C237892%2C242945&d1=&d2=&created_on=&site=&tdate=&list_id=&filters_open=true&view=map&changed_fields=&changed_since=&change_project_id=

A similar search but just for one taxa to see if the multiple taxa thing was messing it up:

![image](https://cloud.githubusercontent.com/assets/7171475/14926655/2870a790-0e1b-11e6-9a3f-d1dee7bc603c.png)

you can see it is returning many taxa. 

Previously when I anted to add observations to this project (http://www.inaturalist.org/projects/mapping-for-healthy-forests-vermont) that same search resulted in returning only the relevant species (invasive plants).

Apologies if this is something you are in the middle of working on, or something redundant.

**Comment by kueda** [comment]
The first two taxon IDs in the list are for Magnoliopsida and Rosales, so I would expect that search to return a ton of different results. Can you provide a URL that has  `taxon_ids[]` set where the returned observations are *not* of the selected taxa?
