### ISSUE TITLE
NPS Jumbotron Slideshow

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#979]
# Bioblitzes
Park Bioblitzes are identified by the following group
```
Project.where(group: "2016 National Parks BioBlitz")
```
Umbrella Bioblitzes are 
```
[6810,7109,7110,7107,6790]
```
# Slide Order
The Slide Order for Park Bioblitzes (using the order of slides in nps_visualizations_rnd_03.pdf as the identifiers) is:
```
[1,2,3,4,5,6]
```
The Slide Order for Umbrella Bioblitzes (using the order of slides in nps_visualizations_rnd_03.pdf as the identifiers) is:
```
[8,2,3,4,5,6,7]
```

# Slide Duration
```
{1: 10, 2: 20, 3: 20, 4: 25, 5: 30, 6: 20, 7: 30, 8: 15}
```
# Included Bioblitzes
All Umbrella Bioblitzes and all Park Bioblitzes with at least one observation are eligible for inclusion in the Slide show

# Umbrella children
The children of 6810 are all Park Bioblitzes, for the other Umbrella Bioblitzes, the children are as follows:
[{parent: 7110, children: [6822,7301,7302,6816,7281,7025,6814,6815,7299,6819,7298,6840,6833,6835]},{parent: 7107, children: [6824,6465,6478]},{parent: 7109, children: [6859,7069,6832,7026,6864,6846,6818]},{parent: 6790, children: [7168,6852,7167,6851,6850]}]
```

# Umbrella place boundaries for display
(we can't use Project.place for this, since that would add unwanted 'must-be-in-place'-like behavior to the Bioblitz Project)
```
[{project: 6810, place: 1},{project: 7109, place: 46},{project: 7110, place: 5},{project: 7107, place: 51727},{project: 6790, place: 43}]
```

# Bioblitz order in Slideshow:
1. Umbrella: 6810 display slides
2. draw 5 Park Bioblitzes not children of other umbrellas and display slides
3. Umbrella: 7110 display slides
4. draw 1 Park Bioblitz child of 7110 and display slides
5. Umbrella: 7109 display slides
6. draw 1 Park Bioblitz child of 7109 and display slides
7. Umbrella: 7107 display slides
8. draw 1 Park Bioblitz child of 7107 and display slides
9. Umbrella: 6790 display slides
10. draw 1 Park Bioblitz child of 6790 and display slides

**Comment by loarie** [comment]
# Proposed changes:
1. Switch order of NatGeo and NPS logo order in header (Nat Geo should be on right)
2. When date range is less than 24hrs render as (3/12/16) rather than (3/12/16 - 3/12/16)
3. Adjusted slide durations (coming soon)

# Known formatting issues:
1. Logo cut off in IE 11
<img width="645" alt="screen shot 2016-05-17 at 10 47 37 am" src="https://cloud.githubusercontent.com/assets/598026/15333030/ce3a9b68-1c1c-11e6-9141-1b7c08c0ce9b.png">
2. First bar lower than others in Safari 9.1
<img width="588" alt="screen shot 2016-05-17 at 10 49 00 am" src="https://cloud.githubusercontent.com/assets/598026/15333067/fc9a14f2-1c1c-11e6-926b-635bd6130449.png">
3. Bargraphs upside down in Safari 8.0.5
<img width="1430" alt="screen shot 2016-05-17 at 10 50 05 am" src="https://cloud.githubusercontent.com/assets/598026/15333205/99281666-1c1d-11e6-855c-1f3e922a7e47.png">

**Comment by loarie** [comment]
Iconic taxon icons missing in IE 11 
<img width="623" alt="screen shot 2016-05-17 at 1 11 25 pm" src="https://cloud.githubusercontent.com/assets/598026/15337496/f16b5136-1c30-11e6-921b-028d6ac24e42.png">

**Comment by pleary** [comment]
Applied all the proposed changed. I might have fixed the IE logo stretch bug - would be good for the person who saw that to check. There might be IE10 problems with number formatting, but people on IE versions 10 or below represent less than 1% of our visitors. As far as I can tell everything is done
