### ISSUE TITLE
ability to load static images over HTTPS (e.g. for widgets)

### ISSUE THREAD

**Issue by npdoty** [inaturalist/inaturalist#982]
I want to use the handy iNat widget on my personal homepage so that people know what observations I've made recently. While I can load the script from HTTPS, the images are all loaded from http://static.inaturalist.org, hosted by S3 and doesn't currently support HTTPS. This lead to mixed content warnings.

Eventually, it would be great if all of iNaturalist could move to HTTPS, but this would be a useful step in the meantime, especially since widgets are often embedded in other pages that may use HTTPS.

**Comment by npdoty** [comment]
Or, perhaps an easier fix would just be to change the observation image URLs created by the widget JS to refer to `https://s3.amazonaws.com/static.inaturalist.org/$1` instead of `http://static.inaturalist.org/$1`.

**Comment by kueda** [comment]
In theory this should be working now, so give it a try.

**Comment by npdoty** [comment]
Yep, resolved. Thanks!

**Comment by npdoty** [comment]
Regression as of this week, images created by the widget are being explicitly src'ed to http:// rather than an https:// URL, with resulting mixed content warnings, as before.

**Comment by kueda** [comment]
Is it working now?

**Comment by npdoty** [comment]
Yep, working for me now. Images are being loaded from ﻿﻿﻿﻿﻿﻿﻿﻿`https://s3.amazonaws.com/static.inaturalist.org/photos/`.
