### ISSUE TITLE
Fields with - in result lack the "Observations with * in field" option

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/inaturalist#989]
For the Natural Community field, any "-" seems to lack the appropriate link to its observations. For instance:

![image](https://cloud.githubusercontent.com/assets/7171475/15628891/625f9ca0-24db-11e6-9f7a-85e8efcaa5ef.png)

Conversely, an observation with that field filled out with an option w/o the "-" : 
![image](https://cloud.githubusercontent.com/assets/7171475/15628896/9eb78b86-24db-11e6-8df9-7ef25dca294c.png)

that one displays properly

**Comment by kueda** [comment]
Showing that link is based on the length of the value, not whether or not it has hyphens. I'll change the cap to 100 characters.
