### ISSUE TITLE
CONABIO site is using North America for the Establishment Banner and not Mexico

### ISSUE THREAD

**Issue by loarie** [inaturalist/inaturalist#992]
any idea why the CONABIO site is using North America for the Establishment Banner and not Mexico? http://conabio.inaturalist.org/taxa/44576-Rattus-norvegicus ?

weirdness compounded by the fact that this isn't listed as native on the ListedTaxon http://www.inaturalist.org/listed_taxa/7742188
 the site should be configured to look at Mexico listings - as the Canada site seems to be successfully doing http://canada.inaturalist.org/taxa/44576-Rattus-norvegicus

here's the listing i'd think the Mexico site would be pulling for the Species pages http://www.inaturalist.org/listed_taxa/3436667

**Comment by kueda** [comment]
Fixed in b1fd82a69ff8f673b2b076001914446a052fcda9
