### ISSUE TITLE
allow rejection of a community ID even if you agree at a more specific taxonomic level

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#993]
<img width="1200" alt="screen shot 2016-06-05 at 12 34 11 pm" src="https://cloud.githubusercontent.com/assets/22691/15806803/e352fd7c-2b19-11e6-9847-f027a7a70753.png">

The sequence of IDs on this observation of mine was

Viburnum
Viburnum
Viburnum dentatum
Viburnum dentatum (me)

So the community ID is Viburnum, and I agree but I have a more specific opinion. I should be able to force the obs to be associated with my own opinion.

**Comment by naturalistcharlie** [comment]
When I get that I just reject the community Id. But maybe we should have it
tag with the most recent observer added ID in this situation.

On Sunday, June 5, 2016, Ken-ichi <notifications@github.com> wrote:

> [image: screen shot 2016-06-05 at 12 34 11 pm]
> <https://cloud.githubusercontent.com/assets/22691/15806803/e352fd7c-2b19-11e6-9847-f027a7a70753.png>
>
> The sequence of IDs on this observation of mine was
>
> Viburnum
> Viburnum
> Viburnum dentatum
> Viburnum dentatum (me)
>
> So the community ID is Viburnum, and I agree but I have a more specific
> opinion. I should be able to force the obs to be associated with my own
> opinion.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/inaturalist/inaturalist/issues/993>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AG1tkyuf3OkUh3oP5FqJTSTRrrTrn7nCks5qIvstgaJpZM4IuZGH>
> .
>


-- 
Sent from Gmail Mobile

**Comment by loarie** [comment]
You can do this by opting out of the community ID

**Comment by kueda** [comment]
I think this was post-bioblitz brain failure. The community ID is obviously *not* at Viburnum, so there's nothing to reject. Moving on...
