### ISSUE TITLE
Spanish translation for Identify

### ISSUE THREAD

**Issue by kueda** [inaturalist/inaturalist#994]
I'm hoping to release http://www.inaturalist.org/observations/identify by the end of this week (and by that I mean link to it and announce it), but there are still several strings that need to be translated into `es` and/or `es-MX`. Here's the list:

* `identify_title`
* `mark_all_as_reviewed`
* `mark_all_as_unreviewed`
* `x_observations_reviewed_html`
* `top_identifiers`
* `keyboard_shortcuts`
* `agree_with_current_taxon`
* `users_identification_html`
* `users_comment_html`

@calonso-conabio, can you take a look at this?

**Comment by kueda** [comment]
FYI, this has been released, @calonso-conabio. Here are a few more:

* `view_more_unreviewed`
* `skip_to_next_page`
* `views.observations.identify.you_reviewed_message`
* `that_was_the_last_observation_matching_the_current_filters`
* `finished_with_page`

**Comment by calonso-conabio** [comment]
Hi Ken-ichi!

sure i can help sending a pull request for those keys, 
is "identify-alternate" the test branch?

regards

**Comment by kueda** [comment]
They're all in master now, so just issue a PR against there.

**Comment by calonso-conabio** [comment]
ok, great!

**Comment by kueda** [comment]
Fixed in 0909435890cf9148379029d71c911bfea1d5bc1e
