### ISSUE TITLE
Observation in same project two times

### ISSUE THREAD

**Issue by naturalistcharlie** [inaturalist/inaturalist#996]
this observation apparently is double-added to Vermont Atlas of Life:

http://www.inaturalist.org/observations/3396952

![image](https://cloud.githubusercontent.com/assets/7171475/15860273/52d3908a-2c96-11e6-847f-103c151bd6f5.png)

**Comment by kueda** [comment]
Do you remember how you added this observation to that project? E.g. did you add it manually, or was it added via the aggregator?

**Comment by kueda** [comment]
Well, I removed the duplicates, but I still have no clue how they got there. If you can come up with some conditions under which this seems to be happening, please re-open this issue and let us know.
