### ISSUE TITLE
Observations/Identify Project filter does not accept Project IDs

### ISSUE THREAD

**Issue by simonkingston** [inaturalist/inaturalist#997]
When using Filters on the [Observations](http://www.inaturalist.org/observations) or [Identify](http://www.inaturalist.org/observations/identify) page, the Project filter does not accept Project IDs.  On both of those pages, I  entered the Project ID 6810 and clicked the Update Search button and no filter was applied to the page.

**Comment by loarie** [comment]
Those are intended to be text searches on the project title, not the ID:
<img width="588" alt="screen shot 2016-06-07 at 1 06 58 pm" src="https://cloud.githubusercontent.com/assets/598026/15872908/bf1c29f4-2cb0-11e6-9987-c6522ad153b7.png">

**Comment by kueda** [comment]
We either need to change the placeholder text or support Simon's request, b/c the placeholder definitely says you can enter an ID. I don't really care one way or the other since autocomplete basically solves the problem, but I think the original intent was to support IDs.

**Comment by loarie** [comment]
Oh shoot - your right - I didn't notice the placeholder text
<img width="297" alt="screen shot 2016-06-07 at 2 14 12 pm" src="https://cloud.githubusercontent.com/assets/598026/15874865/23b792f0-2cba-11e6-87d6-55a4e449b46e.png">

**Comment by loarie** [comment]
I don't have strong preferences about:
1) changing placeholder text
or
2) adding IDs

Since 1 seems easier, unless there's a strong desire for 2 my preference would be to go with 1

**Comment by simonkingston** [comment]
Agreed that easiest mode is to change placeholder text to only include URL
slug.


*Simon Kingston*
*Data Ranger*

National Park Service
Natural Resource Stewardship and Science
Inventory & Monitoring Division
1201 Oakridge Drive, Suite 150
Fort Collins, CO 80525

970-225-3551 ph
970-225-3597 fax

iNaturalist profile: http://www.inaturalist.org/users/forester93

*I stand for enthusiastic discovery in myself and others.*

<https://www.nps.gov/subjects/biodiversity/national-parks-bioblitz.htm>
